### ISSUE TITLE
Weaver crash with ScErrUnhandledWeaverException (SCERR6066), NullReferenceException

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#1203]
@malx122 reported in this https://github.com/Starcounter/Starcounter/issues/1013#issuecomment-26894556 he's experiencing a problem in the weaver that we need to investigate.

Clearing the weaver cache gets him past it.

The exception reported is

```
"ScErrWeavingError (SCERR2030): At least one error has been detected during weaving of the application code. Process exit code: 6066.
Arguments=--maxerrors=1 --ErrorParcelId=A4A7D6FA-EB34-442A-B579-DBB1DBB859E3 Weave ""C:\Projects\GitHub\Tunity-2.0\Tunity.Application\bin\Debug\Tunity.exe"" --outdir=""C:\Users\David Rosendahl\Documents\Starcounter\2.0.1042.3\Personal\Temp\Default\Default-20131022T144540668\weaver\ unity.exe-FF5691E56F020B7F4FDD7074D14AEB73095A7748""
Output:
A4A7D6FA-EB34-442A-B579-DBB1DBB859E3System.Exception: ScErrUnhandledWeaverException (SCERR6066): An unhandled, unidentified (non-Starcounter) exception occurred in the weaver.
Version: 2.0.1042.3.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR6066. ---> System.NullReferenceException: Object reference not set to an instance of an object.
at Starcounter.Internal.Weaver.BackingInfrastructure.TypeSpecificationEmit.AssignInstanceLevelFields() in c:\ScBuildSystem\TeamCity6\buildAgent\work\build-nightly-2.0.1042.3\Level1\src\scweaver\Starcounter.Internal.Weaver\BackingInfrastructure\TypeSpecificationEmit.cs:line 168
at Starcounter.Internal.Weaver.BackingInfrastructure.AssemblySpecificationEmit.IncludeDatabaseClass(TypeDefDeclaration databaseClassTypeDef) in c:\ScBuildSystem\TeamCity6\buildAgent\work\build-nightly-2.0.1042.3\Level1\src\scweaver\Starcounter.Internal.Weaver\BackingInfrastructure\AssemblySpecificationEmit.cs:line 80
at Starcounter.Internal.Weaver.ScTransformTask.Execute() in c:\ScBuildSystem\TeamCity6\buildAgent\work\build-nightly-2.0.1042.3\Level1\src\scweaver\Starcounter.Internal.Weaver\ScTransformTask.cs:line 250
at PostSharp.Sdk.Extensibility.Project.ExecutePhase(String phase)
at PostSharp.Hosting.PostSharpObject.ExecuteProjects()
at PostSharp.Hosting.PostSharpObject.ProcessAssemblies(ModuleLoadStrategy[] modules)
at Weaver.CodeWeaver.Execute() in c:\ScBuildSystem\TeamCity6\buildAgent\work\build-nightly-2.0.1042.3\Level1\src\scweaver\CodeWeaver.cs:line 256
at Weaver.Program.ExecuteWeaveCommand(String inputDirectory, String outputDirectory, String cacheDirectory, String fileName, ApplicationArguments arguments) in c:\ScBuildSystem\TeamCity6\buildAgent\work\build-nightly-2.0.1042.3\Level1\src\scweaver\Program.cs:line 200
at Weaver.Program.ApplyOptionsAndExecuteGivenCommand(ApplicationArguments arguments) in c:\ScBuildSystem\TeamCity6\buildAgent\work\build-nightly-2.0.1042.3\Level1\src\scweaver\Program.cs:line 151
at Weaver.Program.Main(String[] args) in c:\ScBuildSystem\TeamCity6\buildAgent\work\build-nightly-2.0.1042.3\Level1\src\scweaver\Program.cs:line 33
--- End of inner exception stack trace ---A4A7D6FA-EB34-442A-B579-DBB1DBB859E3
System.Exception: ScErrUnhandledWeaverException (SCERR6066): An unhandled, unidentified (non-Starcounter) exception occurred in the weaver.
Version: 2.0.1042.3.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR6066. ---> System.NullReferenceException: Object reference not set to an instance of an object.
at Starcounter.Internal.Weaver.BackingInfrastructure.TypeSpecificationEmit.AssignInstanceLevelFields() in c:\ScBuildSystem\TeamCity6\buildAgent\work\build-nightly-2.0.1042.3\Level1\src\scweaver\Starcounter.Internal.Weaver\BackingInfrastructure\TypeSpecificationEmit.cs:line 168
at Starcounter.Internal.Weaver.BackingInfrastructure.AssemblySpecificationEmit.IncludeDatabaseClass(TypeDefDeclaration databaseClassTypeDef) in c:\ScBuildSystem\TeamCity6\buildAgent\work\build-nightly-2.0.1042.3\Level1\src\scweaver\Starcounter.Internal.Weaver\BackingInfrastructure\AssemblySpecificationEmit.cs:line 80
at Starcounter.Internal.Weaver.ScTransformTask.Execute() in c:\ScBuildSystem\TeamCity6\buildAgent\work\build-nightly-2.0.1042.3\Level1\src\scweaver\Starcounter.Internal.Weaver\ScTransformTask.cs:line 250
at PostSharp.Sdk.Extensibility.Project.ExecutePhase(String phase)
at PostSharp.Hosting.PostSharpObject.ExecuteProjects()
at PostSharp.Hosting.PostSharpObject.ProcessAssemblies(ModuleLoadStrategy[] modules)
at Weaver.CodeWeaver.Execute() in c:\ScBuildSystem\TeamCity6\buildAgent\work\build-nightly-2.0.1042.3\Level1\src\scweaver\CodeWeaver.cs:line 256
at Weaver.Program.ExecuteWeaveCommand(String inputDirectory, String outputDirectory, String cacheDirectory, String fileName, ApplicationArguments arguments) in c:\ScBuildSystem\TeamCity6\buildAgent\work\build-nightly-2.0.1042.3\Level1\src\scweaver\Program.cs:line 200
at Weaver.Program.ApplyOptionsAndExecuteGivenCommand(ApplicationArguments arguments) in c:\ScBuildSystem\TeamCity6\buildAgent\work\build-nightly-2.0.1042.3\Level1\src\scweaver\Program.cs:line 151
at Weaver.Program.Main(String[] args) in c:\ScBuildSystem\TeamCity6\buildAgent\work\build-nightly-2.0.1042.3\Level1\src\scweaver\Program.cs:line 33
--- End of inner exception stack trace ---

Version: 2.0.1042.3.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR2030."
```

Assigning this to me, and will make it part of my current sprint (Milestone 14)

**Comment by dan31** [comment]
@per-samuelsson I do not trace anything relevant to the end of 2016 in there, please reconsider it as opened if you think otherwise 💯
