### ISSUE TITLE
Nightly build failed with timestamp server problem during signing

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#1969]
It's again signing problem, but the error is new:
>[03:49:13][Step 42/47] SignTool Error: The specified timestamp server either could not be reached
[03:49:13][Step 42/47] or returned an invalid response.
[03:49:13][Step 42/47] 	This may happen if you specify an RFC 3161 timestamp URL but used
[03:49:13][Step 42/47] 	the /t option or you specified a legacy Authenticode timestamp URL
[03:49:13][Step 42/47] 	but used the /tr option.
[03:49:13][Step 42/47] SignTool Warning: Signing succeeded, but an error occurred while attempting to
[03:49:13][Step 42/47] 	timestamp: C:\TeamCity\TeamCity8\buildAgent\work\build-nightly-2.0.1841.3\Level1\Bin\Release\scnetworkgatewayloopedtest.exe
[03:49:13][Step 42/47] 
[03:49:13][Step 42/47] Build utility exception:
[03:49:13][Step 42/47] 2014-05-14 03:49:13 (C:\TeamCity\TeamCity8\buildAgent\work\build-nightly-2.0.1841.3\Level1\bsbin\Debug\GenerateInstaller.exe): System.Exception: Signing failed!
[03:49:13][Step 42/47]    at BuildSystemHelper.BuildSystem.SignFiles(String[] allFilesToSign, String companyName, String productName, String pathToCertificate) in c:\TeamCity\TeamCity8\buildAgent\work\build-nightly-2.0.1841.3\BuildSystem\src\BuildSystemHelper\BuildSystemHelper.cs:line 815
[03:49:13][Step 42/47]    at GenerateInstaller.GenerateInstaller.Main(String[] args) in c:\TeamCity\TeamCity8\buildAgent\work\build-nightly-2.0.1841.3\BuildSystem\src\GenerateInstaller\GenerateInstaller.cs:line 390
[03:49:13][Step 42/47] 

[the build](https://scbuildserver/viewLog.html?tab=buildLog&buildTypeId=bt24&buildId=21646&state=&expand=none#_focus=33703&state=33703)

**Comment by k-rus** [comment]
Too old issue, thus closing.
