### ISSUE TITLE
Number casting in Typed JSON

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2132]
I stumbled upon this error in InvoiceDemo.

Consider the following patch:

``` json
[{"op":"replace","path":"/Invoice/Items/0/Price$","value":"11"}]
```
- If `Price` property is of type **decimal** (declared in JSON as `"price": 0.0`), the above patch value will be _correctly_ converted to decimal `11`.
- If `Price` property is of type **long** (declared in JSON as `"price": 0`), the above patch value will trigger exception:

```
500 InternalServerError

System.FormatException: ScErrJsonValueWrongType (SCERR14004): The value does not correspond to the template property type. Property="Quantity (Int64)", Value="3"
Version: 2.0.2147.3.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR14004.
   at Starcounter.XSON.JsonPatch.JsonPatch.ParseAndProcess(TLong property, Json parent, IntPtr valuePtr, Int32 valueSize) in c:\TeamCity\TeamCity8\buildAgent\work\build-nightly-2.0.2147.3\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 759
   at Starcounter.XSON.JsonPatch.JsonPatch.<>c__DisplayClass9.b__8() in c:\TeamCity\TeamCity8\buildAgent\work\build-nightly-2.0.2147.3\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 700
   at Starcounter.Transaction.Add(Action action) in c:\TeamCity\TeamCity8\buildAgent\work\build-nightly-2.0.2147.3\Level1\src\Starcounter\Transaction.cs:line 278
   at Starcounter.XSON.JsonPatch.JsonPatch.HandleParsedPatch(Session session, JsonPointer pointer, IntPtr valuePtr, Int32 valueSize) in c:\TeamCity\TeamCity8\buildAgent\work\build-nightly-2.0.2147.3\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 692
   at Starcounter.XSON.JsonPatch.JsonPatch.EvaluatePatches(Session session, IntPtr patchArrayPtr, Int32 patchArraySize) in c:\TeamCity\TeamCity8\buildAgent\work\build-nightly-2.0.2147.3\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 437
   at Starcounter.Internal.PuppetRestHandler.b__2(Session session, Request request) in c:\TeamCity\TeamCity8\buildAgent\work\build-nightly-2.0.2147.3\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 43
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegates(Request req, IntPtr methodAndUri, IntPtr rawParamsInfo, UriHandlersManager uhm) in c:\TeamCity\TeamCity8\buildAgent\work\build-nightly-2.0.2147.3\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 197
   at Starcounter.Rest.UriHandlersManager.RunDelegate(Request r, Response& resp) in c:\TeamCity\TeamCity8\buildAgent\work\build-nightly-2.0.2147.3\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 524
   at Starcounter.Internal.Web.AppRestServer.HandleRequest(Request request, Int32 handlerLevel) in c:\TeamCity\TeamCity8\buildAgent\work\build-nightly-2.0.2147.3\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 121
HResult=-2146233033
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR14004
```

I find such behaviour is at least inconsistent. Attractive solution from my perspective would be to convert strings to longs in similar manner as they are converted to doubles.

You might ask why Puppet client sends string patches to server when number was expected. The answer is that in HTML, value of every form element is a string. If server cannot handle the conversion, we will need to build converting logic in Puppet.js, which is also doable.

**Comment by warpech** [comment]
@chrhol I think that this issue can be finally closed :)

**Comment by chrhol** [comment]
😉

**Comment by dan31** [comment]
There must be such icon: ![](https://avatars3.githubusercontent.com/u/1658979?v=3&s=32)
