### ISSUE TITLE
Unexpected transaction conflict

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2249]
I am running a regression test on adopted Starcounter for #1731 changes in kernel, i.e., issue #2228. One select statement fails with transaction conflict abort, however I don't see any reason why it can happen. The operation before is drop index, which is run in own transaction scope. And I can confirm that when the select statement does first call to the kernel to create iterator, only implicit read transaction exists.

I suspect that the reason for the transaction conflict is that the query cache is not cleaned. However, I don't understand why transaction conflict is reported and why the problem does not appear in develop branch.

To reproduce:

1. Fetch Metadata branches for Level0 and Level1
2. Build Level0, SqlProcessor and Level1
3. Move to output bin folder, e.g., *Level1\bin\Debug*
4. Run QueryProcessingTest by *s\QueryProcessingTest\run_queryprocessingtest.bat*
5. The exception will happen in *WebVisitTests.cs* line 34

The exception:

```
Starcounter.TransactionConflictException: ScErrTransactionConflictAbort (SCERR80
02): A transaction was aborted because it was in conflict with another transacti
on.
Version: 2.0.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR8002.
   at Starcounter.IteratorHelper.GetEnumeratorCached_NoCodeGenFilter(UInt32 rang
eFlags, Byte[] firstKey, Byte[] lastKey, Enumerator cachedEnum) in c:\GitReposit
ories\Starcounter\Level1\src\Starcounter\Mock\IteratorHelper.cs:line 197
   at Starcounter.Query.Execution.IndexScan.CreateEnumerator() in c:\GitReposito
ries\Starcounter\Level1\src\Starcounter\Query\Execution\Enumerators\IndexScan.cs
:line 319
   at Starcounter.Query.Execution.IndexScan.MoveNextManaged() in c:\GitRepositor
ies\Starcounter\Level1\src\Starcounter\Query\Execution\Enumerators\IndexScan.cs:
line 471
   at Starcounter.Query.Execution.IndexScan.MoveNext() in c:\GitRepositories\Sta
rcounter\Level1\src\Starcounter\Query\Execution\Enumerators\IndexScan.cs:line 51
2
   at Starcounter.Query.Execution.Join.NextRightAndLeftEnumerators() in c:\GitRe
positories\Starcounter\Level1\src\Starcounter\Query\Execution\Enumerators\Join.c
s:line 280
   at Starcounter.Query.Execution.Join.MoveNext() in c:\GitRepositories\Starcoun
ter\Level1\src\Starcounter\Query\Execution\Enumerators\Join.cs:line 253
   at Starcounter.Query.Execution.Join.MoveNext() in c:\GitRepositories\Starcoun
ter\Level1\src\Starcounter\Query\Execution\Enumerators\Join.cs:line 226
   at Starcounter.Query.Execution.Sort.CreateEnumerator() in c:\GitRepositories\
Starcounter\Level1\src\Starcounter\Query\Execution\Enumerators\Sort.cs:line 115
   at Starcounter.Query.Execution.Sort.MoveNext() in c:\GitRepositories\Starcoun
ter\Level1\src\Starcounter\Query\Execution\Enumerators\Sort.cs:line 143
   at Starcounter.Query.Execution.Aggregation.MoveNext() in c:\GitRepositories\S
tarcounter\Level1\src\Starcounter\Query\Execution\Enumerators\Aggregation.cs:lin
e 188
   at Starcounter.Query.Execution.Sort.CreateEnumerator() in c:\GitRepositories\
Starcounter\Level1\src\Starcounter\Query\Execution\Enumerators\Sort.cs:line 115
   at Starcounter.Query.Execution.Sort.MoveNext() in c:\GitRepositories\Starcoun
ter\Level1\src\Starcounter\Query\Execution\Enumerators\Sort.cs:line 143
   at Starcounter.SqlEnumerator`1.MoveNext() in c:\GitRepositories\Starcounter\L
evel1\src\Starcounter\Query\Execution\Enumerators\GenericEnumerator.cs:line 32
   at QueryProcessingTest.WebVisitTests.TestVisits() in c:\GitRepositories\Starc
ounter\Level1\src\Samples\QueryProcessingTest\WebVisitTests.cs:line 34
   at QueryProcessingTest.QueryProcessingTestProgram.Main(String[] args) in c:\G
itRepositories\Starcounter\Level1\src\Samples\QueryProcessingTest\QueryProcessin
gTestProgram.cs:line 28
Starcounter.DbException: ScErrFailingEntrypoint (SCERR4259): The user code entry
point method raised an exception. ScErrTransactionConflictAbort (SCERR8002): A t
ransaction was aborted because it was in conflict with another transaction.
Version: 2.0.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR8002.
Version: 2.0.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4259.
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application) in
c:\GitRepositories\Starcounter\Level1\src\Hosting\Starcounter.Hosting\Package.cs
:line 362
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application ap
plication) in c:\GitRepositories\Starcounter\Level1\src\Hosting\Starcounter.Host
ing\Package.cs:line 187
   at Starcounter.Hosting.Package.Process() in c:\GitRepositories\Starcounter\Le
vel1\src\Hosting\Starcounter.Hosting\Package.cs:line 120
   at Starcounter.Hosting.Package.Process(IntPtr hPackage) in c:\GitRepositories
\Starcounter\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 53
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in c:\G
itRepositories\Starcounter\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:l
ine 66
ErrorCode=4259
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4259
---> System.Reflection.TargetInvocationException: Exception has been thrown by t
he target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments,
 Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Objec
t[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invoke
Attr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Starcounter.Hosting.Package.<>c__DisplayClass11.<ExecuteEntryPoint>b__d()
in c:\GitRepositories\Starcounter\Level1\src\Hosting\Starcounter.Hosting\Package
.cs:line 345
   at Starcounter.Db.MicroTask(Action action, Int32 maxRetries) in c:\GitReposit
ories\Starcounter\Level1\src\Starcounter\Db.cs:line 323
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application) in
c:\GitRepositories\Starcounter\Level1\src\Hosting\Starcounter.Hosting\Package.cs
:line 344
HResult=-2146232828
---> Starcounter.TransactionConflictException: ScErrTransactionConflictAbort (SC
ERR8002): A transaction was aborted because it was in conflict with another tran
saction.
Version: 2.0.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR8002.
   at Starcounter.IteratorHelper.GetEnumeratorCached_NoCodeGenFilter(UInt32 rang
eFlags, Byte[] firstKey, Byte[] lastKey, Enumerator cachedEnum) in c:\GitReposit
ories\Starcounter\Level1\src\Starcounter\Mock\IteratorHelper.cs:line 197
   at Starcounter.Query.Execution.IndexScan.CreateEnumerator() in c:\GitReposito
ries\Starcounter\Level1\src\Starcounter\Query\Execution\Enumerators\IndexScan.cs
:line 319
   at Starcounter.Query.Execution.IndexScan.MoveNextManaged() in c:\GitRepositor
ies\Starcounter\Level1\src\Starcounter\Query\Execution\Enumerators\IndexScan.cs:
line 471
   at Starcounter.Query.Execution.IndexScan.MoveNext() in c:\GitRepositories\Sta
rcounter\Level1\src\Starcounter\Query\Execution\Enumerators\IndexScan.cs:line 51
2
   at Starcounter.Query.Execution.Join.NextRightAndLeftEnumerators() in c:\GitRe
positories\Starcounter\Level1\src\Starcounter\Query\Execution\Enumerators\Join.c
s:line 280
   at Starcounter.Query.Execution.Join.MoveNext() in c:\GitRepositories\Starcoun
ter\Level1\src\Starcounter\Query\Execution\Enumerators\Join.cs:line 253
   at Starcounter.Query.Execution.Join.MoveNext() in c:\GitRepositories\Starcoun
ter\Level1\src\Starcounter\Query\Execution\Enumerators\Join.cs:line 226
   at Starcounter.Query.Execution.Sort.CreateEnumerator() in c:\GitRepositories\
Starcounter\Level1\src\Starcounter\Query\Execution\Enumerators\Sort.cs:line 115
   at Starcounter.Query.Execution.Sort.MoveNext() in c:\GitRepositories\Starcoun
ter\Level1\src\Starcounter\Query\Execution\Enumerators\Sort.cs:line 143
   at Starcounter.Query.Execution.Aggregation.MoveNext() in c:\GitRepositories\S
tarcounter\Level1\src\Starcounter\Query\Execution\Enumerators\Aggregation.cs:lin
e 188
   at Starcounter.Query.Execution.Sort.CreateEnumerator() in c:\GitRepositories\
Starcounter\Level1\src\Starcounter\Query\Execution\Enumerators\Sort.cs:line 115
   at Starcounter.Query.Execution.Sort.MoveNext() in c:\GitRepositories\Starcoun
ter\Level1\src\Starcounter\Query\Execution\Enumerators\Sort.cs:line 143
   at Starcounter.SqlEnumerator`1.MoveNext() in c:\GitRepositories\Starcounter\L
evel1\src\Starcounter\Query\Execution\Enumerators\GenericEnumerator.cs:line 32
   at QueryProcessingTest.WebVisitTests.TestVisits() in c:\GitRepositories\Starc
ounter\Level1\src\Samples\QueryProcessingTest\WebVisitTests.cs:line 34
   at QueryProcessingTest.QueryProcessingTestProgram.Main(String[] args) in c:\G
itRepositories\Starcounter\Level1\src\Samples\QueryProcessingTest\QueryProcessin
gTestProgram.cs:line 56
ErrorCode=8002
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR8002

7EDE1D87-8181-4B1C-B1DF-CB939706F8CF--FC8F607939BC-FD1B-C1B4-1818-78D1EDE7ScErrT
ransactionConflictAbort (SCERR8002): A transaction was aborted because it was in
 conflict with another transaction.
Version: 2.0.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR8002.
   at Starcounter.IteratorHelper.GetEnumeratorCached_NoCodeGenFilter(UInt32 rang
eFlags, Byte[] firstKey, Byte[] lastKey, Enumerator cachedEnum) in c:\GitReposit
ories\Starcounter\Level1\src\Starcounter\Mock\IteratorHelper.cs:line 197
   at Starcounter.Query.Execution.IndexScan.CreateEnumerator() in c:\GitReposito
ries\Starcounter\Level1\src\Starcounter\Query\Execution\Enumerators\IndexScan.cs
:line 319
   at Starcounter.Query.Execution.IndexScan.MoveNextManaged() in c:\GitRepositor
ies\Starcounter\Level1\src\Starcounter\Query\Execution\Enumerators\IndexScan.cs:
line 471
   at Starcounter.Query.Execution.IndexScan.MoveNext() in c:\GitRepositories\Sta
rcounter\Level1\src\Starcounter\Query\Execution\Enumerators\IndexScan.cs:line 51
2
   at Starcounter.Query.Execution.Join.NextRightAndLeftEnumerators() in c:\GitRe
positories\Starcounter\Level1\src\Starcounter\Query\Execution\Enumerators\Join.c
s:line 280
   at Starcounter.Query.Execution.Join.MoveNext() in c:\GitRepositories\Starcoun
ter\Level1\src\Starcounter\Query\Execution\Enumerators\Join.cs:line 253
   at Starcounter.Query.Execution.Join.MoveNext() in c:\GitRepositories\Starcoun
ter\Level1\src\Starcounter\Query\Execution\Enumerators\Join.cs:line 226
   at Starcounter.Query.Execution.Sort.CreateEnumerator() in c:\GitRepositories\
Starcounter\Level1\src\Starcounter\Query\Execution\Enumerators\Sort.cs:line 115
   at Starcounter.Query.Execution.Sort.MoveNext() in c:\GitRepositories\Starcoun
ter\Level1\src\Starcounter\Query\Execution\Enumerators\Sort.cs:line 143
   at Starcounter.Query.Execution.Aggregation.MoveNext() in c:\GitRepositories\S
tarcounter\Level1\src\Starcounter\Query\Execution\Enumerators\Aggregation.cs:lin
e 188
   at Starcounter.Query.Execution.Sort.CreateEnumerator() in c:\GitRepositories\
Starcounter\Level1\src\Starcounter\Query\Execution\Enumerators\Sort.cs:line 115
   at Starcounter.Query.Execution.Sort.MoveNext() in c:\GitRepositories\Starcoun
ter\Level1\src\Starcounter\Query\Execution\Enumerators\Sort.cs:line 143
   at Starcounter.SqlEnumerator`1.MoveNext() in c:\GitRepositories\Starcounter\L
evel1\src\Starcounter\Query\Execution\Enumerators\GenericEnumerator.cs:line 32
   at QueryProcessingTest.WebVisitTests.TestVisits() in c:\GitRepositories\Starc
ounter\Level1\src\Samples\QueryProcessingTest\WebVisitTests.cs:line 34
   at QueryProcessingTest.QueryProcessingTestProgram.Main(String[] args) in c:\G
itRepositories\Starcounter\Level1\src\Samples\QueryProcessingTest\QueryProcessin
gTestProgram.cs:line 56
7EDE1D87-8181-4B1C-B1DF-CB939706F8CF--FC8F607939BC-FD1B-C1B4-1818-78D1EDE7
```

**Comment by chrhol** [comment]
I've tested and verified that the test works without the workaround. The workaround code was not in develop, only in next and I have removed it there.

Closing this issue.
