### ISSUE TITLE
NullReferenceException in Starcounter.Templates

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#2303]
As part of @linkdata working on Yahoo Cloud Serving Benchmark (YCSB), he has found a `NullReferenceException` in `Starcounter.Templates`. 

I've ran it on my machine in a debug environment to get some improved error information, and in the log, we now have this:

```
[09:49:29, Error, Starcounter.Host (default)]
System.ArgumentNullException: Value cannot be null.
Parameter name: type
   at System.RuntimeType.IsSubclassOf(Type type)
   at Starcounter.Templates.TValue.VerifyBinding(Type dataType) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.XSON\Templates\Foundation\TValue.cs:line 212
   at Starcounter.Templates.TValue.UseBinding(Json parent) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.XSON\Templates\Foundation\TValue.cs:line 197
   at Starcounter.Templates.Property`1.BoundOrUnboundGet(Json parent) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 33
   at Starcounter.Advanced.XSON.StandardJsonSerializerBase._EstimateSizeBytes(Json obj) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 106
   at Starcounter.Advanced.XSON.StandardJsonSerializerBase.EstimateSizeBytes(Json obj) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 20
   at Starcounter.Templates.TObject.ToJson(Json json) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.XSON\Templates\TObject.cs:line 477
   at Starcounter.Json.ToJson() in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.XSON\Class Json\Json.Serializing.cs:line 31
   at YCBS.Program.<Main>b__a(String user_name) in c:\Users\Per\Proj\ycsb_server\ycsb_server\ycsb_server\Program.cs:line 134
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegates(Request req, IntPtr methodAndUri, IntPtr rawParamsInfo, UriHandlersManager uhm) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 199
   at Starcounter.Rest.UriHandlersManager.RunDelegate(Request r, Response& resp) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 529
   at Starcounter.Internal.Web.AppRestServer.HandleRequest(Request request, Int32 handlerLevel) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 117
ParamName=type
HResult=-2147467261


[09:47:24, Error, Starcounter.Host (default)]
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , Json , String )
   at Starcounter.Templates.Property`1.BoundOrUnboundSet(Json parent, T value) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 41
   at UserMsg.set_field4(String value) in c:\Users\Per\Proj\ycsb_server\ycsb_server\ycsb_server\obj\x64\Debug\UserMsg.json:line 8
   at YCBS.Program.<Main>b__8(String user_name, Request req) in c:\Users\Per\Proj\ycsb_server\ycsb_server\ycsb_server\Program.cs:line 97
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegates(Request req, IntPtr methodAndUri, IntPtr rawParamsInfo, UriHandlersManager uhm) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 199
   at Starcounter.Rest.UriHandlersManager.RunDelegate(Request r, Response& resp) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 529
   at Starcounter.Internal.Web.AppRestServer.HandleRequest(Request request, Int32 handlerLevel) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 117
HResult=-2147467261


[09:45:34, Error, Starcounter.Host (default)]
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , Json , String )
   at Starcounter.Templates.Property`1.BoundOrUnboundSet(Json parent, T value) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 41
   at UserMsg.set_field2(String value) in c:\Users\Per\Proj\ycsb_server\ycsb_server\ycsb_server\obj\x64\Debug\UserMsg.json:line 6
   at YCBS.Program.<Main>b__8(String user_name, Request req) in c:\Users\Per\Proj\ycsb_server\ycsb_server\ycsb_server\Program.cs:line 97
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegates(Request req, IntPtr methodAndUri, IntPtr rawParamsInfo, UriHandlersManager uhm) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 199
   at Starcounter.Rest.UriHandlersManager.RunDelegate(Request r, Response& resp) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 529
   at Starcounter.Internal.Web.AppRestServer.HandleRequest(Request request, Int32 handlerLevel) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 117
HResult=-2147467261


[09:43:51, Error, Starcounter.Host (default)]
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , Json , String )
   at Starcounter.Templates.Property`1.BoundOrUnboundSet(Json parent, T value) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 41
   at UserMsg.set_field0(String value) in c:\Users\Per\Proj\ycsb_server\ycsb_server\ycsb_server\obj\x64\Debug\UserMsg.json:line 4
   at YCBS.Program.<Main>b__8(String user_name, Request req) in c:\Users\Per\Proj\ycsb_server\ycsb_server\ycsb_server\Program.cs:line 97
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegates(Request req, IntPtr methodAndUri, IntPtr rawParamsInfo, UriHandlersManager uhm) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 199
   at Starcounter.Rest.UriHandlersManager.RunDelegate(Request r, Response& resp) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 529
   at Starcounter.Internal.Web.AppRestServer.HandleRequest(Request request, Int32 handlerLevel) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 117
HResult=-2147467261


[09:43:42, Error, Starcounter.Host (default)]
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , Json , String )
   at Starcounter.Templates.Property`1.BoundOrUnboundSet(Json parent, T value) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 41
   at UserMsg.set_field0(String value) in c:\Users\Per\Proj\ycsb_server\ycsb_server\ycsb_server\obj\x64\Debug\UserMsg.json:line 4
   at YCBS.Program.<Main>b__8(String user_name, Request req) in c:\Users\Per\Proj\ycsb_server\ycsb_server\ycsb_server\Program.cs:line 97
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegates(Request req, IntPtr methodAndUri, IntPtr rawParamsInfo, UriHandlersManager uhm) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 199
   at Starcounter.Rest.UriHandlersManager.RunDelegate(Request r, Response& resp) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 529
   at Starcounter.Internal.Web.AppRestServer.HandleRequest(Request request, Int32 handlerLevel) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 117
HResult=-2147467261


[09:43:08, Error, Starcounter.Host (default)]
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , Json , String )
   at Starcounter.Templates.Property`1.BoundOrUnboundSet(Json parent, T value) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 41
   at UserMsg.set_field0(String value) in c:\Users\Per\Proj\ycsb_server\ycsb_server\ycsb_server\obj\x64\Debug\UserMsg.json:line 4
   at YCBS.Program.<Main>b__8(String user_name, Request req) in c:\Users\Per\Proj\ycsb_server\ycsb_server\ycsb_server\Program.cs:line 97
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegates(Request req, IntPtr methodAndUri, IntPtr rawParamsInfo, UriHandlersManager uhm) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 199
   at Starcounter.Rest.UriHandlersManager.RunDelegate(Request r, Response& resp) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 529
   at Starcounter.Internal.Web.AppRestServer.HandleRequest(Request request, Int32 handlerLevel) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 117
HResult=-2147467261


[09:42:53, Error, Starcounter.Host (default)]
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , Json , String )
   at Starcounter.Templates.Property`1.BoundOrUnboundSet(Json parent, T value) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 41
   at UserMsg.set_field1(String value) in c:\Users\Per\Proj\ycsb_server\ycsb_server\ycsb_server\obj\x64\Debug\UserMsg.json:line 5
   at YCBS.Program.<Main>b__8(String user_name, Request req) in c:\Users\Per\Proj\ycsb_server\ycsb_server\ycsb_server\Program.cs:line 97
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegates(Request req, IntPtr methodAndUri, IntPtr rawParamsInfo, UriHandlersManager uhm) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 199
   at Starcounter.Rest.UriHandlersManager.RunDelegate(Request r, Response& resp) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 529
   at Starcounter.Internal.Web.AppRestServer.HandleRequest(Request request, Int32 handlerLevel) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 117
HResult=-2147467261


[09:42:23, Error, Starcounter.Host (default)]
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , Json , String )
   at Starcounter.Templates.Property`1.BoundOrUnboundSet(Json parent, T value) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 41
   at UserMsg.set_field5(String value) in c:\Users\Per\Proj\ycsb_server\ycsb_server\ycsb_server\obj\x64\Debug\UserMsg.json:line 9
   at YCBS.Program.<Main>b__8(String user_name, Request req) in c:\Users\Per\Proj\ycsb_server\ycsb_server\ycsb_server\Program.cs:line 97
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegates(Request req, IntPtr methodAndUri, IntPtr rawParamsInfo, UriHandlersManager uhm) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 199
   at Starcounter.Rest.UriHandlersManager.RunDelegate(Request r, Response& resp) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 529
   at Starcounter.Internal.Web.AppRestServer.HandleRequest(Request request, Int32 handlerLevel) in c:\Users\Per\Git\Starcounter\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 117
HResult=-2147467261
```

**Comment by chrhol** [comment]
Will close this one. #3863 is the issue for solving these problems.
