### ISSUE TITLE
ScErrCodeHostProcessRefusedStop when starting application

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#2314]
When working with #2107, I discovered that occasionally ```ScErrCodeHostProcessRefusedStop``` can occur when I'm starting an application.

I have investigated, and the scenario is:

1. Start an application, e.g. ```app1```.
2. Start another application that crashes in the entrypoint, e.g. ```app2```.
3. Start ```app1``` again.

Then the below error appears (occasionally).

The reason is, I think, that the server tries to restart the application at the same time as the client ask to start it, and the code host has been started but net yet ready for applications to be executed.

I have an idea how this should be fixed, and I hope I can do so as part of #2107.

> [15:27:18, Error, Starcounter.Server (scadminserver)]
Starcounter.DbException: ScErrCodeHostProcessRefusedStop (SCERR10017): When asked to shut down, the user code process actively refused it. , PID=4544, Database=default - URI not found: DELETE /codehost/default 
Version: 2.0.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10017.
   at Starcounter.Server.DatabaseEngine.StopCodeHostProcess(Database database) in c:\Users\Per\Git\Starcounter\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseEngine.cs:line 401
   at Starcounter.Server.Commands.StopExecutableCommandProcessor.<>c__DisplayClass8.<Execute>b__1(CommandTask task) in c:\Users\Per\Git\Starcounter\Level1\src\Server\Starcounter.Server\Commands\Processors\StopExecutableCommandProcessor.cs:line 82
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Action`1 action) in c:\Users\Per\Git\Starcounter\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 482
   at Starcounter.Server.Commands.StopExecutableCommandProcessor.Execute() in c:\Users\Per\Git\Starcounter\Level1\src\Server\Starcounter.Server\Commands\Processors\StopExecutableCommandProcessor.cs:line 81
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in c:\Users\Per\Git\Starcounter\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 261
ErrorCode=10017
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR10017

**Comment by miyconst** [comment]
I am getting similar excepion:

```
Starcounter.DbException: ScErrCodeHostProcessRefusedStop (SCERR10017): When asked to shut down, the user code process actively refused it. , PID=99704, Database=default
 Version: 2.0.3118.3.
 Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10017.
 at Starcounter.Server.DatabaseEngine.StopCodeHostProcess(Database database) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3118.3\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseEngine.cs:line 375
 at Starcounter.Server.Commands.StopExecutableCommandProcessor.<>c__DisplayClass8.<Execute>b__1(CommandTask task) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3118.3\Level1\src\Server\Starcounter.Server\Commands\Processors\StopExecutableCommandProcessor.cs:line 82
 at Starcounter.Server.Commands.CommandProcessor.<>c__DisplayClass1.<WithinTask>b__0(CommandTask t) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3118.3\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 484
 at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3118.3\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 510
 at Starcounter.Server.Commands.StopExecutableCommandProcessor.Execute() in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3118.3\Level1\src\Server\Starcounter.Server\Commands\Processors\StopExecutableCommandProcessor.cs:line 81
 at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3118.3\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
 ErrorCode=10017
 HResult=-2146233088
 HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR10017
```

This happens in `Images` application after wrong file upload.
https://github.com/Polyjuice/Images/blob/master/ImageUpload.cs#L39

@alemoi could you please take a look? It started to appear after your changes in https://github.com/Starcounter/Starcounter/issues/2653

**Comment by mtornwall** [comment]
I'm seeing this too. +1

**Comment by warpech** [comment]
@miyconst is it still reproducible? Then please open a new issue because this ticket was related to `ScErrCodeHostProcessRefusedStop` while starting an app, not when using it.

@mtornwall - same as above. Do you have some error message in log? Could you describe when this happens?

**Comment by miyconst** [comment]
No, I didn't see the error for quite a while.

**Comment by mtornwall** [comment]
@warpech I still have this. It tends to happen when I'm repeatedly starting and stopping apps. If you want I'll investigate further. 

In the logs the pattern seems to be (in chronological order):

1. `ScErrCodeHostProcessRefusedStop` exception is reported.
2. This is followed immediately by a `ScErrServerCommandFailed` ("the operation 'stopping <something>' failed").
3. About 10 seconds later, the code host process crashes (`ScErrDatabaseEngineTerminated`).

**Comment by warpech** [comment]
Thanks, reopening then.
