### ISSUE TITLE
Out of memory error for three running databases on build server

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2389]
I try to run my regression test with three simple apps on the build server. Each app creates own database. When third database creates a database I get the error (see, e.g., [this build](https://scbuildserver/viewLog.html?buildId=24172&buildTypeId=Starcounter_DevelopDaily&tab=buildLog):
>[14:41:05][Step 14/42] [14:41:04, Critical, Starcounter (selectonnull2362db)]
[14:41:05][Step 14/42] System.OutOfMemoryException: ScErrOutOfMemory (SCERR1003): Operation failed because needed memory couldn't be allocated.
[14:41:05][Step 14/42] Version: 2.0.8424.2.
[14:41:05][Step 14/42] Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR1003.
[14:41:05][Step 14/42]    at StarcounterInternal.Bootstrap.Control.ConnectDatabase(UInt32 schedulerCount, UInt64 hmenv, UInt64 hlogs) in c:\TeamCity\TeamCity8\buildAgent\work\build-daily-develop-2.0.8424.2\Level1\src\Starcounter.Bootstrap\Control.cs:line 557
[14:41:05][Step 14/42]    at StarcounterInternal.Bootstrap.Control.Setup(String[] args) in c:\TeamCity\TeamCity8\buildAgent\work\build-daily-develop-2.0.8424.2\Level1\src\Starcounter.Bootstrap\Control.cs:line 208
[14:41:05][Step 14/42]    at StarcounterInternal.Bootstrap.Control.Main(String[] args) in c:\TeamCity\TeamCity8\buildAgent\work\build-daily-develop-2.0.8424.2\Level1\src\Starcounter.Bootstrap\Control.cs:line 55
[14:41:05][Step 14/42] HResult=-2147024882
[14:41:05][Step 14/42] HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR1003

Currently I disabled the third test app, since it will fail nightly build due to this problem. After I fix #2362 I will return to this one and describe how to reproduce.
If anyone can hint about the problem, post here.

**Comment by k-rus** [comment]
It is unclear why out of memory was experienced, but I guess it will not be an issue in future version. I close the issue as I don't think we will spend time on it.
