### ISSUE TITLE
Problem when upgrading starcounter, ScErrSchemaCodeMismatch

### ISSUE THREAD

**Issue by malx122** [Starcounter/Starcounter#2439]
Tried upgrading one of our server to use a new starcounter (and a upgraded version of our application). Started with newest version 2014-12-09 but that version I cant get to work even locally on my computer. I will report that in a separat issue. So I choosed to upgrade our server to the version of starcounter I was using locally instead. Its maybe two weeks old (2.0.2907.3).
This one works perfectly locally but when installed on our server (with the same application version as I use locally) I get this error in one part of the application:

No idea what it means:

```
Starcounter.DbException: ScErrSchemaCodeMismatch (SCERR4177): Operation failed be because input does not match schema.
 Version: 2.0.2907.3.
 Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4177.
 at Starcounter.Binding.Bindings.CreateExceptionOnTypeDefNotFound() in c:\TeamCity\TeamCity8\buildAgent\work\build-nightly-develop-2.0.2907.3\Level1\src\Starcounter\Binding\Bindings.cs:line 334
 at Starcounter.Binding.Bindings.BuildTypeBindingFromTypeDef(TypeDef typeDef) in c:\TeamCity\TeamCity8\buildAgent\work\build-nightly-develop-2.0.2907.3\Level1\src\Starcounter\Binding\Bindings.cs:line 251
 at Starcounter.Binding.Bindings.BuildTypeBindingFromTypeDef(Int32 tableId) in c:\TeamCity\TeamCity8\buildAgent\work\build-nightly-develop-2.0.2907.3\Level1\src\Starcounter\Binding\Bindings.cs:line 224
 at Starcounter.Enumerator.MoveNext() in c:\TeamCity\TeamCity8\buildAgent\work\build-nightly-develop-2.0.2907.3\Level1\src\Starcounter\Mock\Enumerator.cs:line 239
 at Starcounter.Query.Execution.IndexScan.MoveNextManaged() in c:\TeamCity\TeamCity8\buildAgent\work\build-nightly-develop-2.0.2907.3\Level1\src\Starcounter\Query\Execution\Enumerators\IndexScan.cs:line 475
 at Starcounter.Query.Execution.IndexScan.MoveNext() in c:\TeamCity\TeamCity8\buildAgent\work\build-nightly-develop-2.0.2907.3\Level1\src\Starcounter\Query\Execution\Enumerators\IndexScan.cs:line 551
 at Starcounter.Query.Execution.Sort.CreateEnumerator() in c:\TeamCity\TeamCity8\buildAgent\work\build-nightly-develop-2.0.2907.3\Level1\src\Starcounter\Query\Execution\Enumerators\Sort.cs:line 115
 at Starcounter.Query.Execution.Sort.MoveNext() in c:\TeamCity\TeamCity8\buildAgent\work\build-nightly-develop-2.0.2907.3\Level1\src\Starcounter\Query\Execution\Enumerators\Sort.cs:line 143
 at Concepts.Ring8.Tunity.TodoList.<get_Todos>d__1.MoveNext() in c:\Projects\Github\Tunity-2.0\Concepts.Ring8.Tunity\Todo\TodoList.cs:line 176
 at Starcounter.Json.CheckBoundArray(IEnumerable boundValue) in c:\TeamCity\TeamCity8\buildAgent\work\build-nightly-develop-2.0.2907.3\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 279
 at Starcounter.Json.InitBoundArrays(TObject template) in c:\TeamCity\TeamCity8\buildAgent\work\build-nightly-develop-2.0.2907.3\Level1\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 138
 at Starcounter.Json.InternalSetData(Object data, TObject template, Boolean readOperation) in c:\TeamCity\TeamCity8\buildAgent\work\build-nightly-develop-2.0.2907.3\Level1\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 103
 at Starcounter.Transaction.Starcounter.Advanced.ITransaction.Add[T1,T2](Action`2 action, T1 arg1, T2 arg2) in c:\TeamCity\TeamCity8\buildAgent\work\build-nightly-develop-2.0.2907.3\Level1\src\Starcounter\Transaction.cs:line 307
 at Starcounter.Json.set_Data(Object value) in c:\TeamCity\TeamCity8\buildAgent\work\build-nightly-develop-2.0.2907.3\Level1\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 38
 at Starcounter.Json.CheckBoundArray(IEnumerable boundValue) in c:\TeamCity\TeamCity8\buildAgent\work\build-nightly-develop-2.0.2907.3\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 284
 at Starcounter.Json.InitBoundArrays(TObject template) in c:\TeamCity\TeamCity8\buildAgent\work\build-nightly-develop-2.0.2907.3\Level1\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 138
 at Starcounter.Json.InternalSetData(Object data, TObject template, Boolean readOperation) in c:\TeamCity\TeamCity8\buildAgent\work\build-nightly-develop-2.0.2907.3\Level1\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 103
 at Starcounter.Transaction.Starcounter.Advanced.ITransaction.Add[T1,T2](Action`2 action, T1 arg1, T2 arg2) in c:\TeamCity\TeamCity8\buildAgent\work\build-nightly-develop-2.0.2907.3\Level1\src\Starcounter\Transaction.cs:line 307
 at Starcounter.Json.set_Data(Object value) in c:\TeamCity\TeamCity8\buildAgent\work\build-nightly-develop-2.0.2907.3\Level1\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 38
 at Tunity.Organizer.Kanban.set_Data(KanbanView value) in c:\Projects\Github\Tunity-2.0\Tunity.Organizer\obj\x64\Debug\Todo\Kanban.json.g.cs:line 0
 at Tunity.Organizer.Kanban.Create(Something something) in c:\Projects\Github\Tunity-2.0\Tunity.Organizer\Todo\Kanban.json.cs:line 42
 at Tunity.Organizer.Kanban.Create(String objId) in c:\Projects\Github\Tunity-2.0\Tunity.Organizer\Todo\Kanban.json.cs:line 30
 at Tunity.Organizer.TunityApplication.<>c__DisplayClass33.<Main>b__16(MainPage mp) in c:\Projects\Github\Tunity-2.0\Tunity.Organizer\Tunity.Organizer.Application.cs:line 91
 at Tunity.Common.TunityX.BuildOn[T](String uri, Func`2 func) in c:\Projects\Github\Tunity-2.0\Tunity.Utils\Utils\TunityX.cs:line 170
 at Tunity.Common.TunityX.BuildOn[T](Request req, String uri, Func`2 func) in c:\Projects\Github\Tunity-2.0\Tunity.Utils\Utils\TunityX.cs:line 109
 at Tunity.Organizer.TunityApplication.<Main>b__15(Request req, String objId) in c:\Projects\Github\Tunity-2.0\Tunity.Organizer\Tunity.Organizer.Application.cs:line 88
 at lambda_method(Closure , Request , IntPtr , IntPtr )
 at Starcounter.Rest.UserHandlerInfo.RunUserDelegates(Request req, IntPtr methodAndUri, IntPtr rawParamsInfo, UriHandlersManager uhm) in c:\TeamCity\TeamCity8\buildAgent\work\build-nightly-develop-2.0.2907.3\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 200
 at Starcounter.Rest.UriHandlersManager.RunDelegate(Request r, Response& resp) in c:\TeamCity\TeamCity8\buildAgent\work\build-nightly-develop-2.0.2907.3\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 533
 at Starcounter.Internal.Web.AppRestServer.HandleRequest(Request request, HandlerLevels handlerLevel) in c:\TeamCity\TeamCity8\buildAgent\work\build-nightly-develop-2.0.2907.3\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 106
 ErrorCode=4177
 HResult=-2146233088
 HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4177
```

**Comment by dan31** [comment]
Archived. The track for improving schema migrations is born starting from v2.3.
