### ISSUE TITLE
Access denied on build server during process kill

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2483]
I experienced in [my build](https://scbuildserver/viewLog.html?tab=buildLog&buildTypeId=Starcounter_DevelopDaily&buildId=25250) the following error:

>[09:33:39][Step 1/1] Build utility exception:
[09:33:39][Step 1/1] 2015-01-15 09:33:39 (C:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.8807.2\Level1\bsbin\Release\PostBuildTasks.exe): System.ComponentModel.Win32Exception (0x80004005): Access is denied
[09:33:39][Step 1/1]    at System.Diagnostics.Process.Kill()
[09:33:39][Step 1/1]    at BuildSystemHelper.BuildSystem.KillDisturbingProcesses(String[] procNames) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.8807.2\BuildSystem\src\BuildSystemHelper\BuildSystemHelper.cs:line 251
[09:33:39][Step 1/1]    at BuildSystemHelper.BuildSystem.KillAll() in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.8807.2\BuildSystem\src\BuildSystemHelper\BuildSystemHelper.cs:line 265
[09:33:39][Step 1/1]    at PostBuildTasks.PostBuildTasks.Main(String[] args) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.8807.2\BuildSystem\src\PostBuildTasks\PostBuildTasks.cs:line 237

**Comment by k-rus** [comment]
[Another my personal test](https://scbuildserver/viewLog.html?tab=buildLog&buildTypeId=Starcounter_DevelopDaily&buildId=25255) failed with this error

**Comment by alemoi** [comment]
Maybe some has started build agent not as Administrator. I will check.

**Comment by k-rus** [comment]
I merged latest change from develop and [my last build](https://scbuildserver/viewLog.html?buildId=25289&tab=buildResultsDiv&buildTypeId=Starcounter_DevelopDaily) succeeded. I consider this issue to be resolved. Will open if meet this problem again.
