### ISSUE TITLE
The operation failed because the current thread wasn't attached to the scheduler.

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#2488]
Sometimes when starting my test locally using star.exe, I have the following error:

```
System.Exception: ScErrThreadNotAttached (SCERR1004): The operation failed because the current thread wasn't attached to the scheduler.
Version: 2.0.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR1004.
   at Starcounter.Db.Transaction(Action action, UInt32 flags, Boolean forceSnapshot, Int32 maxRetries) in c:\github\Level1\src\Starcounter\D
b.cs:line 263
   at Starcounter.Db.Transaction(Action action, Boolean forceSnapshot, Int32 maxRetries) in c:\github\Level1\src\Starcounter\Db.cs:line 165
   at Starcounter.Hosting.Package.CreateOrUpdateDatabaseTable(TypeDef typeDef) in c:\github\Level1\src\Hosting\Starcounter.Hosting\Package.c
s:line 370
   at Starcounter.Hosting.Package.UpdateDatabaseSchemaAndRegisterTypes(TypeDef[] unregisteredTypeDefs) in c:\github\Level1\src\Hosting\Starc
ounter.Hosting\Package.cs:line 274
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application) in c:\github\Level1\src\Hosting\Starcounter.Hosti
ng\Package.cs:line 194
   at Starcounter.Hosting.Package.Process() in c:\github\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 125
   at Starcounter.Hosting.Package.Process(IntPtr hPackage) in c:\github\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 56
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in c:\github\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:li
ne 66
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR1004
```

To reproduce just run `star.exe --nodb s\NetworkIoTest\NetworkIoTest.exe DbNumber=1 PortNumber=8080 TestType=MODE_NODE_TESTS` from StarcounterBin.

**Comment by alemoi** [comment]
I have noticed that it happens when I start the application for the first time. Restart works properly. On the build server when this command is executed in one of my tests - it also works fine. It also works fine when I don't use `--nodb` parameter.

**Comment by dan31** [comment]
@per-samuelsson, this reminds me of something we've met already with nodb, don't you have the same feeling?
