### ISSUE TITLE
SCERR12015: Unable to attach the debugger to the database process because the database process was not found

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2494]
After installing current nightly 2.0.2994.3 (over version 2.0.2987.3) I got an error preventing to start application from Visual Studio 2012 (Windows 8):

> Error	1	Unable to attach the debugger to the database process because the database process was not found. Database "default" in process 0. (ScErrDebugNoDbProcess (SCERR12015))

Restarting Windows did not help.

Deleting database `default` in Administrator and creating a new one helped.

The same problem was encountered today by @tomalec

**Comment by per-samuelsson** [comment]
Possibly relating to #2490, which is being fixed.

**Comment by dan31** [comment]
@warpech, haven't you met with that since that moment?

**Comment by per-samuelsson** [comment]
Could this be caused by those versions that (wrongly) started databases in session 0?

**Comment by warpech** [comment]
@dan31 No, I have never reproduced it anymore

**Comment by parherman** [comment]
We've experienced that now with installing 2.0.3033 on @parherman machine. Before it had some Starcounter builds performed. We also started Personal server and Starcounter service right after the installation, that didn't help.
> Error	1	Unable to attach the debugger to the database process because the database process was not found. Database "default" in process 0. (ScErrDebugNoDbProcess (SCERR12015))
(Double-click here for additional help)		0	0

**Comment by per-samuelsson** [comment]
> We've experienced that now with installing 2.0.3033 on @parherman machine.

Anything in the log? That the PID is 0 indicates the code host has terminated, probably due to some error.

**Comment by per-samuelsson** [comment]
> Anything in the log?

And [staradmin list log](https://github.com/Starcounter/Starcounter/wiki/Error-log#using-command-line-tools) is your friend. :smile:

**Comment by dan31** [comment]
We have this condition for reproduction frozen on @parherman laptop :) @parherman, don't reinstall your Windows 7 until we can dig to the roots! On my VM, the same version works, this means that there is just something with OS configuration.

**Comment by parherman** [comment]
@per-samuelsson, this is from the logs:

```

[08:50:54, Critical, Starcounter (default)]
Starcounter.DbException: ScErrIndexNotFound (SCERR4229): Index requested not found.
Version: 2.0.3037.3.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4229.
   at Starcounter.SqlProcessor.SqlProcessor.CleanClrMetadata() in c:\BuildAgent\work\sc-2.0.3037.3\Level1\src\Starcounter\SqlProcessor\SqlProcessor.cs:line 63
   at Starcounter.Hosting.Package.UpdateDatabaseSchemaAndRegisterTypes(TypeDef[] unregisteredTypeDefs) in c:\BuildAgent\work\sc-2.0.3037.3\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 258
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application) in c:\BuildAgent\work\sc-2.0.3037.3\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 182
   at Starcounter.Hosting.Package.Process() in c:\BuildAgent\work\sc-2.0.3037.3\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 125
   at Starcounter.Hosting.Package.Process(IntPtr hPackage) in c:\BuildAgent\work\sc-2.0.3037.3\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 57
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in c:\BuildAgent\work\sc-2.0.3037.3\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 70
ErrorCode=4229
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4229


[08:50:54, Notice, Starcounter (default)]
The database has been unloaded.
```

**Comment by k-rus** [comment]
> @per-samuelsson, this is from the logs:
> 
> 
> [08:50:54, Critical, Starcounter (default)]
> Starcounter.DbException: ScErrIndexNotFound (SCERR4229): Index requested not found.
> Version: 2.0.3037.3.
> Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4229.
>    at Starcounter.SqlProcessor.SqlProcessor.CleanClrMetadata() in c:\BuildAgent\work\sc-2.0.3037.3\Level1\src\Starcounter\SqlProcessor\SqlProcessor.cs:line 63
>    at Starcounter.Hosting.Package.UpdateDatabaseSchemaAndRegisterTypes(TypeDef[] unregisteredTypeDefs) in c:\BuildAgent\work\sc-2.0.3037.3\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 258
>    at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application) in c:\BuildAgent\work\sc-2.0.3037.3\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 182
>    at Starcounter.Hosting.Package.Process() in c:\BuildAgent\work\sc-2.0.3037.3\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 125
>    at Starcounter.Hosting.Package.Process(IntPtr hPackage) in c:\BuildAgent\work\sc-2.0.3037.3\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 57
>    at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in c:\BuildAgent\work\sc-2.0.3037.3\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 70
> ErrorCode=4229
> HResult=-2146233088
> HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4229
> 
> 
> [08:50:54, Notice, Starcounter (default)]
> The database has been unloaded.

Thank you for reporting the issue. It is identical to #2495 
The issue is due to change in the meta-data schema. The solution is to create the database from scratch. If the data is needed to be preserved, then unload it with the old installation of Starcoutner and then reload into newly created database on the new installation of Starcounter.

If there is no more questions or issues, the issue can be closed as it is a duplicate.

**Comment by dan31** [comment]
Okay, it's now clear, we simply didn't remove the database folder. This bug then belongs to a group "Versioning".

**Comment by k-rus** [comment]
> This bug then belongs to a group "Versioning".

imho, it is just duplicate of #2495 and I suggest to close this one, since it does not bring any more info, e.g., it does not contain reproduction and test.

**Comment by parherman** [comment]
@k-rus, is all you have to do to reproduce this:

1. Install Starcounter and let it create the default database
2. Uninstall Starcounter
3. Install new Starcounter version with meta-data schema change
4. Star starcounter service

Would this make for a good acceptance test?

**Comment by k-rus** [comment]
> @k-rus, is all you have to do to reproduce this:
> 
> Install Starcounter and let it create the default database
> Uninstall Starcounter
> Install new Starcounter version with meta-data schema change
> Star starcounter service
> Would this make for a good acceptance test?

No. The meta-data schema change is valid change and failing such change is incorrect. If the test is combined with versioning (#2550), which is not in place, then the test can expect or not the error.

**Comment by andwah** [comment]
was just hit with this.

Solve it by deleting the "default" database.
