### ISSUE TITLE
ScErrIndexNotFound (SCERR4229) without information about the index

### ISSUE THREAD

**Issue by malx122** [Starcounter/Starcounter#2495]
```
Starcounter.DbException: ScErrIndexNotFound (SCERR4229): Index requested not found.
 Version: 2.0.2994.3.
 Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4229.
 at Starcounter.SqlProcessor.SqlProcessor.CleanClrMetadata() in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.2994.3\Level1\src\Starcounter\SqlProcessor\SqlProcessor.cs:line 62
 at Starcounter.Hosting.Package.UpdateDatabaseSchemaAndRegisterTypes(TypeDef[] unregisteredTypeDefs) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.2994.3\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 257
 at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.2994.3\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 193
 at Starcounter.Hosting.Package.Process() in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.2994.3\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 125
 at Starcounter.Hosting.Package.Process(IntPtr hPackage) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.2994.3\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 56
 at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.2994.3\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 66
 ErrorCode=4229
 HResult=-2146233088
 HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4229
```
Another error message without the meaningful information: "WHAT index was not found, which property in which table?".

**Comment by k-rus** [comment]
Thank you! This error demonstrates a bug in Starcounter. Thus it cannot be meaningful. Is it the same error as in #2487?

**Comment by malx122** [comment]
Probably, I removed "Type" property from polyjuice SO ring1.Something. (With my updated ring8 code so NO object have a property named "Type" now). Still using database from server running older code (with a "Type" property (of different types) on many  Ring 8 classes). CALL ME!

**Comment by k-rus** [comment]
This problem appears due to mismatch between meta-data schemas. This requires to do unload/reload between Starcounter versions. I will investigate how Starcounter can notify users that the manual upgrade is necessary or see if I can do another fix.

**Comment by malx122** [comment]
And the problem is that we can't do a unload on our server due to bugs... hm... we really should need a polyjuice edition SC from 22 december.

**Comment by k-rus** [comment]
Immediate tasks in this issue:

1. Reproduce issue on a small sample.
2. Fix error message to give more meaningful information.

Long term solutions are either auto-fixing meta-data, issue #2460, or unload/reload request during installation, issue #2496.

**Comment by k-rus** [comment]
> Immediate tasks in this issue:
> 
> Reproduce issue on a small sample.
> Fix error message to give more meaningful information.
> Long term solutions are either auto-fixing meta-data, issue #2460, or unload/reload request during installation, issue #2496.

See [my comment](https://github.com/Starcounter/Starcounter/issues/2487#issuecomment-73664893) in #2487.

This issue will implement better error message after #2550.
