### ISSUE TITLE
After staradmin unload apps cannot be restarted

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2506]
I run an application and then do unload using *staradmin*. After the unload I modified the app and tried to start. This triggers restart, which restarts the unload application. See:

```
D:\TempProjects\UnloadReproduce>star UnloadReproduce.cs
UnloadReproduce -> default (started, default port 8080, admin 8181)
Adding path to static web server "D:\TempProjects\UnloadReproduce"

D:\TempProjects\UnloadReproduce>staradmin unload --file=here.sql
Unloading Default (done)
Adding path to static web server "D:\TempProjects\UnloadReproduce"
Unload started at 14:00:36.1089910
Unloaded: 1 objects (14:00:36.1714964)

D:\TempProjects\UnloadReproduce>star UnloadReproduce.cs
UnloadReproduce -> default (restarting default (and 1 other executable(s)) .)
```

The logged error:

>Starcounter.DbException: ScErrFailingEntrypoint (SCERR4259): The user code entrypoint method raised an exception. ScErrUnloadTableNoClass (SCERR4275): Unloading a table fails, since its class is not loaded. An application, where the class is declared, needs to be loaded before unload is called. Table ReproduceClass cannot be unloaded.
 Version: 2.0.0.0.
 Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4275.
 Version: 2.0.0.0.
 Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4259.
 at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application) in c:\GitRepositories\Starcounter\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 430
 at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application) in c:\GitRepositories\Starcounter\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 194
 at Starcounter.Hosting.Package.Process() in c:\GitRepositories\Starcounter\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 125
 at Starcounter.Hosting.Package.Process(IntPtr hPackage) in c:\GitRepositories\Starcounter\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 56
 at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in c:\GitRepositories\Starcounter\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 66
 ErrorCode=4259
 HResult=-2146233088
 HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4259
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
 at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
 at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
 at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
 at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application) in c:\GitRepositories\Starcounter\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 415
 HResult=-2146232828
 ---> Starcounter.DbException: ScErrUnloadTableNoClass (SCERR4275): Unloading a table fails, since its class is not loaded. An application, where the class is declared, needs to be loaded before unload is called. Table ReproduceClass cannot be unloaded.
 Version: 2.0.0.0.
 Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4275.
 at Starcounter.Reload.Unload(String fileName, UInt64 shiftId, Boolean unloadAll) in c:\GitRepositories\Starcounter\Level1\src\Starcounter\Mock\Reload.cs:line 55
 at Starcounter.Db.Unload(String fileName, UInt64 shiftId, Boolean unloadAll) in c:\GitRepositories\Starcounter\Level1\src\Starcounter\Mock\Db.cs:line 138
 at UnloadDatabase.Program.Main(String[] args) in c:\GitRepositories\Starcounter\Level1\bin\Debug\cli-apps\UnloadDatabase.cs:line 24
 ErrorCode=4275
 HResult=-2146233088
 HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4275

I think there was a related issue that `staradmin unload` should not use an application, which would fix this issue.

**Comment by per-samuelsson** [comment]
Thanks for reporting. Clearly a bug.

I'll fix so that the unload application is not restarted eventually, or so that it is stopped right after its ran.

Meanwhile, as a workaround, users can stop it manually using the below command:

> C:\foo> staradmin stop app starcounter_internal_unload_utility

**Comment by miyconst** [comment]
+1
