### ISSUE TITLE
Json serializer strange exception

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#2513]
I got this one once when running PokerDemo test on `next`.
Here is the build link: https://scbuildserver/viewLog.html?buildId=25445&buildTypeId=Starcounter_NextDaily&tab=buildLog#_focus=61&state=61
The following stack trace:

```
[18:25:37]System.NullReferenceException: Object reference not set to an instance of an object.
[18:25:37]   at Starcounter.Json._Add(Object item) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.358.7\Level1\src\Starcounter.XSON\Class Json\Json.IList.cs:line 325
[18:25:37]   at Starcounter.Json.NewItem() in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.358.7\Level1\src\Starcounter.XSON\Class Json\Json.IList.cs:line 173
[18:25:37]   at Starcounter.Advanced.XSON.StandardJsonSerializer.Populate(Json obj, IntPtr source, Int32 sourceSize) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.358.7\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 533
[18:25:37]   at Starcounter.Templates.TObject.PopulateFromJson(Json json, Byte[] src, Int32 srcSize) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.358.7\Level1\src\Starcounter.XSON\Templates\TObject.cs:line 552
[18:25:37]   at Starcounter.Rest.UriManagedHandlersCodegen.ReadMessageParam(Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.358.7\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 168
[18:25:37]   at lambda_method(Closure , Request , IntPtr , IntPtr )
[18:25:37]   at Starcounter.Rest.UserHandlerInfo.RunUserDelegates(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, HandlerOptions handlerOptions) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.358.7\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 230
[18:25:37]   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req, HandlerOptions handlerOptions) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.358.7\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 139
[18:25:37]   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.358.7\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 219
[18:25:37]HResult=-2147467261
[18:25:37]
```

For now assigned to @chrhol but let's see how it goes.

**Comment by alemoi** [comment]
Another example of failure when running Pokerdemo: 
```
[18:44:21]System.NullReferenceException: Object reference not set to an instance of an object.
[18:44:21]   at Starcounter.Templates.Property`1.BoundOrUnboundGet(Json parent) in c:\BuildAgent\work\sc-2.0.9210.2\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 34
[18:44:21]   at Starcounter.Advanced.XSON.StandardJsonSerializerBase._EstimateSizeBytes(Json obj) in c:\BuildAgent\work\sc-2.0.9210.2\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 111
[18:44:21]   at Starcounter.Advanced.XSON.JsonExtension.Scope[T,TResult](Json json, Func`2 func, T arg) in c:\BuildAgent\work\sc-2.0.9210.2\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 132
[18:44:21]   at Starcounter.Templates.TObject.ToJsonUtf8(Json json) in c:\BuildAgent\work\sc-2.0.9210.2\Level1\src\Starcounter.XSON\Templates\TObject.cs:line 486
[18:44:21]   at PokerDemoApp.Program.<Main>b__9(Int32 playerId) in c:\BuildAgent\work\sc-2.0.9210.2\PokerDemo\PokerDemoApp\Program.cs:line 29
[18:44:21]   at lambda_method(Closure , Request , IntPtr , IntPtr )
[18:44:21]   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, HandlerOptions handlerOptions) in c:\BuildAgent\work\sc-2.0.9210.2\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 241
[18:44:21]   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req, HandlerOptions handlerOptions) in c:\BuildAgent\work\sc-2.0.9210.2\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 139
[18:44:21]   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\BuildAgent\work\sc-2.0.9210.2\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 228
[18:44:21]HResult=-2147467261
```

in https://scbuildserver/viewLog.html?buildId=26074&buildTypeId=Starcounter_DevelopDaily&tab=buildLog

**Comment by alemoi** [comment]
And this one:

```
[18:54:28]System.NullReferenceException: Object reference not set to an instance of an object.
[18:54:28]   at Starcounter.Json._Add(Object item) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.9211.2\Level1\src\Starcounter.XSON\Class Json\Json.IList.cs:line 325
[18:54:28]   at Starcounter.Json.NewItem() in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.9211.2\Level1\src\Starcounter.XSON\Class Json\Json.IList.cs:line 173
[18:54:28]   at Starcounter.Advanced.XSON.StandardJsonSerializer.Populate(Json obj, IntPtr source, Int32 sourceSize) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.9211.2\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 506
[18:54:28]   at Starcounter.Templates.TObject.PopulateFromJson(Json json, Byte[] src, Int32 srcSize) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.9211.2\Level1\src\Starcounter.XSON\Templates\TObject.cs:line 552
[18:54:28]   at Starcounter.Rest.UriManagedHandlersCodegen.ReadMessageParam(Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.9211.2\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 168
[18:54:28]   at lambda_method(Closure , Request , IntPtr , IntPtr )
[18:54:28]   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, HandlerOptions handlerOptions) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.9211.2\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 241
[18:54:28]   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req, HandlerOptions handlerOptions) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.9211.2\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 139
[18:54:28]   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.9211.2\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 228
[18:54:28]HResult=-2147467261
```
in https://scbuildserver/viewLog.html?buildId=26075&buildTypeId=Starcounter_DevelopDaily&tab=buildLog#_focus=4779

**Comment by alemoi** [comment]
And the last Nightly actually failed with the same error:
```
[03:28:03]System.NullReferenceException: Object reference not set to an instance of an object.
[03:28:03]   at Starcounter.Json._Add(Object item) in c:\BuildAgent\work\sc-2.0.3054.3\Level1\src\Starcounter.XSON\Class Json\Json.IList.cs:line 325
[03:28:03]   at Starcounter.Json.NewItem() in c:\BuildAgent\work\sc-2.0.3054.3\Level1\src\Starcounter.XSON\Class Json\Json.IList.cs:line 173
[03:28:03]   at Starcounter.Advanced.XSON.StandardJsonSerializer.Populate(Json obj, IntPtr source, Int32 sourceSize) in c:\BuildAgent\work\sc-2.0.3054.3\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 523
[03:28:03]   at Starcounter.Templates.TObject.PopulateFromJson(Json json, Byte[] src, Int32 srcSize) in c:\BuildAgent\work\sc-2.0.3054.3\Level1\src\Starcounter.XSON\Templates\TObject.cs:line 552
[03:28:03]   at Starcounter.Rest.UriManagedHandlersCodegen.ReadMessageParam(Request req) in c:\BuildAgent\work\sc-2.0.3054.3\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 168
[03:28:03]   at lambda_method(Closure , Request , IntPtr , IntPtr )
[03:28:03]   at Starcounter.Rest.UserHandlerInfo.RunUserDelegates(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, HandlerOptions handlerOptions) in c:\BuildAgent\work\sc-2.0.3054.3\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 239
[03:28:03]   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req, HandlerOptions handlerOptions) in c:\BuildAgent\work\sc-2.0.3054.3\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 139
[03:28:03]   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\BuildAgent\work\sc-2.0.3054.3\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 227
[03:28:03]HResult=-2147467261
```

https://scbuildserver/viewLog.html?buildId=26039&buildTypeId=Starcounter_DevelopNightly&tab=buildLog

**Comment by chrhol** [comment]
Yes, strange exception. I see nothing directly in the code. The only thing I can think of is that some part of this code is not threadsafe and when running on many schedulers maybe something initializes in the wrong order. 

There is some places when it comes to creating and modyfing the underlying template which is not threadsafe.

I will investigate.

**Comment by chrhol** [comment]
I saw now that there was two different exceptions reported. Both of them looks like synchronization issues. There is another issue also reported, #2303, which might be the same as the second exception here.

It looks like we need to go through the code for Templates and determine how we want to handle synchronization. It might be too costly to use locks so maybe some other solution is needed.

**Comment by alemoi** [comment]
I'm not sure if its related but here is another stack from Next-Nightly:

```c#
[04:53:57]System.NullReferenceException: Object reference not set to an instance of an object.
[04:53:57]   at Starcounter.Templates.Property`1.BoundOrUnboundGet(Json parent) in c:\BuildAgent\work\sc-2.0.213.8\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 34
[04:53:57]   at Starcounter.Advanced.XSON.StandardJsonSerializerBase._Serialize(Json obj, Byte[] buf, Int32 origOffset) in c:\BuildAgent\work\sc-2.0.213.8\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 334
[04:53:57]   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3,TResult](Json json, Func`4 func, T1 arg1, T2 arg2, T3 arg3) in c:\BuildAgent\work\sc-2.0.213.8\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 108
[04:53:57]   at Starcounter.Advanced.XSON.StandardJsonSerializerBase.Serialize(Json obj, Byte[] buf, Int32 origOffset) in c:\BuildAgent\work\sc-2.0.213.8\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 18
[04:53:57]   at Starcounter.Templates.TObject.ToJsonUtf8(Json json) in c:\BuildAgent\work\sc-2.0.213.8\Level1\src\Starcounter.XSON\Templates\TObject.cs:line 479
[04:53:57]   at PokerDemoApp.Program.<Main>b__9(Int32 playerId) in c:\BuildAgent\work\sc-2.0.213.8\PokerDemo\PokerDemoApp\Program.cs:line 28
[04:53:57]   at lambda_method(Closure , Request , IntPtr , IntPtr )
[04:53:57]   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, HandlerOptions handlerOptions) in c:\BuildAgent\work\sc-2.0.213.8\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 218
[04:53:57]   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req, HandlerOptions handlerOptions) in c:\BuildAgent\work\sc-2.0.213.8\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 136
[04:53:57]   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\BuildAgent\work\sc-2.0.213.8\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 287
[04:53:57]HResult=-2147467261
```

from here: https://scbuildserver/viewLog.html?buildId=26698&buildTypeId=Starcounter_NextNightly&tab=buildLog

**Comment by alemoi** [comment]
Here is another one from Debug Nightly:

```
[02:20:21]System.NullReferenceException: Object reference not set to an instance of an object.
[02:20:21]   at Starcounter.Templates.Property`1.BoundOrUnboundGet(Json parent) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.91.3\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 34
[02:20:21]   at Starcounter.Advanced.XSON.StandardJsonSerializerBase._EstimateSizeBytes(Json obj) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.91.3\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 116
[02:20:21]   at Starcounter.Advanced.XSON.JsonExtension.Scope[T,TResult](Json json, Func`2 func, T arg) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.91.3\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 84
[02:20:21]   at Starcounter.Advanced.XSON.StandardJsonSerializerBase.EstimateSizeBytes(Json obj) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.91.3\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 14
[02:20:21]   at Starcounter.Templates.TObject.ToJsonUtf8(Json json) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.91.3\Level1\src\Starcounter.XSON\Templates\TObject.cs:line 478
[02:20:21]   at Starcounter.Json.ToJsonUtf8() in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.91.3\Level1\src\Starcounter.XSON\Class Json\Json.Serializing.cs:line 49
[02:20:21]   at PokerDemoApp.Program.<Main>b__9(Int32 playerId) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.91.3\PokerDemo\PokerDemoApp\Program.cs:line 28
[02:20:21]   at lambda_method(Closure , Request , IntPtr , IntPtr )
[02:20:21]   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.91.3\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 224
[02:20:21]   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.91.3\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 97
[02:20:21]   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.91.3\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 259
[02:20:21]HResult=-2147467261
```

here: https://scbuildserver/viewLog.html?buildId=27001&buildTypeId=Starcounter_Develop_Nightly_Debug&tab=buildLog

**Comment by alemoi** [comment]
Still occurs. Here is the example:

```c#
System.NullReferenceException: Object reference not set to an instance of an object.
   at Starcounter.Templates.Property`1.BoundOrUnboundGet(Json parent) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3171.3\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 34
   at Starcounter.Advanced.XSON.StandardJsonSerializerBase._EstimateSizeBytes(Json obj) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3171.3\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 153
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T,TResult](Json json, Func`2 func, T arg) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3171.3\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 84
   at Starcounter.Templates.TObject.ToJsonUtf8(Json json) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3171.3\Level1\src\Starcounter.XSON\Templates\TObject.cs:line 478
   at PokerDemoApp.Program.<Main>b__9(Int32 playerId) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3171.3\PokerDemo\PokerDemoApp\Program.cs:line 28
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3171.3\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 265
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3171.3\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 97
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3171.3\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 324
HResult=-2147467261
```

in https://scbuildserver/viewLog.html?buildId=27905&buildTypeId=Starcounter_DevelopNightly&tab=buildLog

**Comment by alemoi** [comment]
Just reporting that problem still in place (https://scbuildserver/viewLog.html?buildId=28801&buildTypeId=Starcounter_DevelopNightly&tab=buildLog&state=56#_state=56&focus=5578):
```c#
System.NullReferenceException: Object reference not set to an instance of an object.
   at Starcounter.Templates.Property`1.BoundOrUnboundGet(Json parent) in c:\BuildAgent\work\sc-2.0.3206.3\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 36
   at Starcounter.Advanced.XSON.StandardJsonSerializerBase.EstimateString(TypedJsonSerializer serializer, Json json, Template template) in c:\BuildAgent\work\sc-2.0.3206.3\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 127
   at Starcounter.Advanced.XSON.StandardJsonSerializerBase.EstimateObject(TypedJsonSerializer serializer, Json json) in c:\BuildAgent\work\sc-2.0.3206.3\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 184
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,TResult](Json json, Func`3 func, T1 arg1, T2 arg2) in c:\BuildAgent\work\sc-2.0.3206.3\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 96
   at Starcounter.Advanced.XSON.StandardJsonSerializerBase.ScopeAndEstimateObject(TypedJsonSerializer serializer, Json json, Template template) in c:\BuildAgent\work\sc-2.0.3206.3\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 141
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,TResult](Json json, Func`3 func, T1 arg1, T2 arg2) in c:\BuildAgent\work\sc-2.0.3206.3\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 96
   at Starcounter.Advanced.XSON.StandardJsonSerializerBase.EstimateSizeBytes(Json json) in c:\BuildAgent\work\sc-2.0.3206.3\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 44
   at Starcounter.Json.ToJsonUtf8() in c:\BuildAgent\work\sc-2.0.3206.3\Level1\src\Starcounter.XSON\Class Json\Json.Serializing.cs:line 54
   at PokerDemoApp.Program.<Main>b__9(Int32 playerId) in c:\BuildAgent\work\sc-2.0.3206.3\PokerDemo\PokerDemoApp\Program.cs:line 28
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in c:\BuildAgent\work\sc-2.0.3206.3\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 266
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in c:\BuildAgent\work\sc-2.0.3206.3\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 97
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\BuildAgent\work\sc-2.0.3206.3\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 349
HResult=-2147467261
```

**Comment by chrhol** [comment]
Will close this issue. #3863 is the issue for solving these problems.
