### ISSUE TITLE
No attributes specified on index creation

### ISSUE THREAD

**Issue by Ripipip** [Starcounter/Starcounter#2533]
When trying to create the following ndex it works fine. 

Starcounter.Db.SQL("CREATE INDEX ClassifiedAdIndex ON ClassifiedAd (Removed, Age)");

This index however throws an error (the only difference being changing the order of the attributes).

{ Starcounter.Db.SQL("CREATE INDEX ClassifiedAdIndex ON ClassifiedAd (Age, Removed)");

Starcounter.DbException: ScErrNoAttributesOnIndex (SCERR4168): No attributes specified on index creation.
 Version: 2.0.2999.3.
 Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4168.
 at Starcounter.Query.QueryPreparation.PrepareOrExecuteQuery[T](String query, Boolean slowSql, Object[] values) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.2999.3\Level1\src\Starcounter\Query\QueryPreparation.cs:line 67
 at Starcounter.Query.Sql.SqlEnumCache.CacheOrExecuteEnumerator[T](String query, Boolean slowSQL, Object[] values) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.2999.3\Level1\src\Starcounter\Query\SQL\_SqlEnumCache.cs:line 123
 at Starcounter.Db.FullQueryProcess[T](String query, Boolean slowSQL, Object[] values) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.2999.3\Level1\src\Starcounter\Mock\Db.cs:line 126
 at AdFenix.Server.Handlers.InitData.<Register>b__6f() in c:\adfenix-backend\src\Server\Handlers\InitData.cs:line 212
 at Starcounter.Rest.UserHandlerInfo.RunUserDelegates(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, HandlerOptions handlerOptions) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.2999.3\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 213
 at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req, HandlerOptions handlerOptions) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.2999.3\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 139
 at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.2999.3\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 217
 ErrorCode=4168
 HResult=-2146233088
 HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4168

Not a problem anymore but strange behavior.

**Comment by k-rus** [comment]
Thank you for reporting the issue!
How to reproduce the behaviour? For example, what is the schema?

**Comment by k-rus** [comment]
BUMP

**Comment by Ripipip** [comment]
The problem probably lies in me trying to put an index on an GET accessor. 

This is the age attribute in ClassifiedAd.

**Comment by k-rus** [comment]
> Not that strange that it failed - the weird thing was rather that the error only appeared if I put the boolean after the get accessor.

Thank you for clarifying!
You are right it is weird that the index statement succeeds in one case and reports a strange error in another case. We will look at it. Thank you for reporting.

**Comment by k-rus** [comment]
I confirm the issue and was able to reproduce using a simple program:
```c#
using Starcounter;

class Program {
	static void Main() {
		Db.SQL("create index PersonAgeIndx on Person (NickName, Age)");
        var p = Db.SQL<Person>("select p from person p where nickname = ? and age = ?", "nick", 3).First;
        ScAssertion.Assert(p == null);
	}
}

[Database]
public class Person {
	public string FirstName;
	public string LastName;
	public string NickName;
    public int Age { get { int age = 3; return age; } }
}
```

This issue contains two tasks:

- [ ] Fixed the bug that index is successfully created if a code property is part of a compound index.
- [ ] Improve error message for non-existing stored property

**Comment by k-rus** [comment]
The error message will look like:

>System.Exception: ScErrSQLUnknownName (SCERR7026): Specified name of class, property or other object name does not exist in the database. Property Age in table Person is not a stored property.
