### ISSUE TITLE
Error on upstart with "unknown" status of db 

### ISSUE THREAD

**Issue by malx122** [Starcounter/Starcounter#2547]
I got this when going back to our application after tried starting some of the launcher applications in the same database earlier. I'm sorry but I do not have the database any more since I deleted it to try and see if that was the cause... so no way o repeating it.
```
System.NullReferenceException: Object reference not set to an instance of an object.
 at Starcounter.SqlProcessor.MetadataPopulation.<>c__DisplayClass4.<PopulateClrMetadata>b__3() in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3025.3\Level1\src\Starcounter\SqlProcessor\MetadataPopulation.cs:line 76
 at Starcounter.Db.Transaction(Action action, UInt32 flags, Boolean forceSnapshot, Int32 maxRetries) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3025.3\Level1\src\Starcounter\Db.cs:line 225
 at Starcounter.Hosting.Package.UpdateDatabaseSchemaAndRegisterTypes(TypeDef[] unregisteredTypeDefs) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3025.3\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 328
 at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3025.3\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 193
 at Starcounter.Hosting.Package.Process() in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3025.3\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 125
 at Starcounter.Hosting.Package.Process(IntPtr hPackage) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3025.3\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 56
 at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3025.3\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 66
 HResult=-2147467261
```

**Comment by k-rus** [comment]
Thank you for reporting.
Was there change in Starcounter versions between runs?

**Comment by malx122** [comment]
I had a SC version (two weeks old) that I runned with our application creating a default db with some things.
Then I installed fridays version of SC and launcher e.t.c.
Tried running launcher, useradmin, userlogin apps but failed starting it in default db. (Don't remember why). So I created another db for that test.
Last I went back working on our current application and then I got that error trying to running it in the default db. Then I got the error.

Upgrading our server from the same SC to the same SC, but without playing with launcher apps created no error but the db is of course not 100% identical ...

**Comment by k-rus** [comment]
> Tried running launcher, useradmin, userlogin apps but failed starting it in default db. (Don't remember why). So I created another db for that test.
> Last I went back working on our current application and then I got that error trying to running it in the default db. Then I got the error.

Did I understand you correctly, last you try to run your application on default db, which you failed to start before with launcher, useradmin and userlogin apps, so the error is subsequent?



> Upgrading our server from the same SC to the same SC, but without playing with launcher apps created no error but the db is of course not 100% identical ...

If you do the same, but run launcher it fails, correct?
