### ISSUE TITLE
Browsing the online API documentation sometimes fails with IndexOutOfRangeException

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Starcounter#2573]
Browsing the online API documentation shows the following exception first time a page is loaded (and I guess when it's not cached serverside):
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.Dictionary`2.Resize(Int32 newSize, Boolean forceNewHashCodes)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Starcounter.Internal.Web.StaticWebServer.GetFileResource(Response cached, String relativeUri, Request req) in c:\TeamCity\TeamCity8\buildAgent\work\build-nightly-2.0.2648.3\Level1\src\Starcounter.Hypermedia\StaticWebServer.File.cs:line 143
   at Starcounter.Internal.Web.StaticWebServer.GetStatic(String relativeUri, Request request) in c:\TeamCity\TeamCity8\buildAgent\work\build-nightly-2.0.2648.3\Level1\src\Starcounter.Hypermedia\StaticWebServer.cs:line 129
   at Starcounter.Internal.Web.AppRestServer.OnResponseHttp(Request req, Response resp) in c:\TeamCity\TeamCity8\buildAgent\work\build-nightly-2.0.2648.3\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 65
HResult=-2146233080

More information about this error may be available in the server error log.
```

Clicking on the same link again loads the page correctly.

**Comment by alemoi** [comment]
Thanks for reporting! I wonder how old is the version there?

**Comment by chrhol** [comment]
Good question, probably quite old. A first step should be to update the current version and see if the problem still occurs.

**Comment by alemoi** [comment]
Did we notice anything like that with newer versions of Starcounter?

**Comment by alemoi** [comment]
Closing the issue because of no evidence of this in the latest versions of Starcounter.
