### ISSUE TITLE
ScErrUnhandledWeaverException when refering to a dll that extends SO 

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2579]
Below is explanation of a problem that I had this morning. It is a quite common yet very confusing problem.

Starcounter version 2.0.3038.3

I created a new project in Visual Studio, and refered to `SocietyObjects.Concepts.Ring8.Polyjuice.Procurement.dll` from another project. Visual Studio sets "Copy Local" property of a newly added reference to `True` by default, and this is what happened next.

When I started the project, I got the following exception:

```
System.Exception:  ScErrUnhandledWeaverException (SCERR6066): An unhandled, unidentified (non-Starcounter) exception occurred in the weaver. Version: 2.0.3038.3. Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR6066. ---> System.ArgumentException: An item with the same key has already been added.    at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)    at Sc.Server.Weaver.Schema.DatabaseAssemblyCollection.Add(DatabaseAssembly item) in c:\BuildAgent\work\sc-2.0.3038.3\Level1\src\Starcounter\Mock\Schema\DatabaseAssembly.cs:line 251    at Starcounter.Internal.Weaver.ScAnalysisTask.Execute() in c:\BuildAgent\work\sc-2.0.3038.3\Level1\src\scweaver\Starcounter.Internal.Weaver\ScAnalysisTask.cs:line 435    at PostSharp.Sdk.Extensibility.Project.ExecutePhase(String phase)    at PostSharp.Hosting.PostSharpObject.ExecuteProjects()    at PostSharp.Hosting.PostSharpObject.ProcessAssemblies(ModuleLoadStrategy[] modules)    at Starcounter.Weaver.CodeWeaver.Execute() in c:\BuildAgent\work\sc-2.0.3038.3\Level1\src\scweaver\CodeWeaver.cs:line 283    at Starcounter.Weaver.CodeWeaver.ExecuteCurrent(CodeWeaver weaver) in c:\BuildAgent\work\sc-2.0.3038.3\Level1\src\scweaver\CodeWeaver.cs:line 199    at Starcounter.Weaver.Program.ExecuteWeaveCommand(String inputDirectory, String outputDirectory, String cacheDirectory, String fileName, ApplicationArguments arguments) in c:\BuildAgent\work\sc-2.0.3038.3\Level1\src\scweaver\Program.cs:line 199    at Starcounter.Weaver.Program.ApplyOptionsAndExecuteGivenCommand(ApplicationArguments arguments) in c:\BuildAgent\work\sc-2.0.3038.3\Level1\src\scweaver\Program.cs:line 153    at Starcounter.Weaver.Program.Main(String[] args) in c:\BuildAgent\work\sc-2.0.3038.3\Level1\src\scweaver\Program.cs:line 35    --- End of inner exception stack trace ---
   at Starcounter.Server.WeaverService.LogAndRaiseExceptionFromFailingWeaver(ToolInvocationException e) in c:\BuildAgent\work\sc-2.0.3038.3\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 181
   at Starcounter.Server.WeaverService.Weave(String givenAssembly, String runtimeDirectory) in c:\BuildAgent\work\sc-2.0.3038.3\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 116
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.<>c__DisplayClass7.<Execute>b__3(CommandTask task) in c:\BuildAgent\work\sc-2.0.3038.3\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 99
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Action`1 action) in c:\BuildAgent\work\sc-2.0.3038.3\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 481
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.Execute() in c:\BuildAgent\work\sc-2.0.3038.3\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 104
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in c:\BuildAgent\work\sc-2.0.3038.3\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 263
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR6066
```

As it turned out, file `SocietyObjects.Concepts.Ring8.Polyjuice.Procurement.dll` has a internal reference to `SocietyObjects.Concepts.Ring1.dll`, because it extends one of its classes. In result, the file `SocietyObjects.Concepts.Ring1.dll` was copied to `bin/debug` subdirectory of my project.

Removing all dlls from `bin/debug`, adding explicit reference to Assemblies → Extensions → "SocietyObjects.Concepts.Ring1", then rebuilding fixes the problem. 

---

Now when I wanted to reproduce the problem again by removing the reference to "SocietyObjects.Concepts.Ring1" and rebuilding, the error message is by far less cryptical:

```
Starcounter.DbException:  ScErrTypeNameDuplicate (SCERR4078): Two classes of the same full name were found. Class ""Concepts.Ring1.Something"" in assembly ""SocietyObjects.Concepts.Ring1"" clash with class ""Concepts.Ring1.Something"" in assembly ""SocietyObjects.Concepts.Ring1"". Version: 2.0.3038.3. Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4078.    at Sc.Server.Weaver.Schema.DatabaseSchema.IndexDatabaseClass(DatabaseClass databaseClass) in c:\BuildAgent\work\sc-2.0.3038.3\Level1\src\Starcounter\Mock\Schema\DatabaseSchema.cs:line 113    at Sc.Server.Weaver.Schema.DatabaseAssemblyCollection.Add(DatabaseAssembly item) in c:\BuildAgent\work\sc-2.0.3038.3\Level1\src\Starcounter\Mock\Schema\DatabaseAssembly.cs:line 247    at Starcounter.Internal.Weaver.WeaverCache.Get(String assemblyName) in c:\BuildAgent\work\sc-2.0.3038.3\Level1\src\scweaver\Starcounter.Internal.Weaver\WeaverCache.cs:line 298    at Starcounter.Weaver.FileManager.Open() in c:\BuildAgent\work\sc-2.0.3038.3\Level1\src\scweaver\FileManager.cs:line 144    at Starcounter.Weaver.CodeWeaver.Execute() in c:\BuildAgent\work\sc-2.0.3038.3\Level1\src\scweaver\CodeWeaver.cs:line 217    at Starcounter.Weaver.CodeWeaver.ExecuteCurrent(CodeWeaver weaver) in c:\BuildAgent\work\sc-2.0.3038.3\Level1\src\scweaver\CodeWeaver.cs:line 199    at Starcounter.Weaver.Program.ExecuteWeaveCommand(String inputDirectory, String outputDirectory, String cacheDirectory, String fileName, ApplicationArguments arguments) in c:\BuildAgent\work\sc-2.0.3038.3\Level1\src\scweaver\Program.cs:line 199    at Starcounter.Weaver.Program.ApplyOptionsAndExecuteGivenCommand(ApplicationArguments arguments) in c:\BuildAgent\work\sc-2.0.3038.3\Level1\src\scweaver\Program.cs:line 153    at Starcounter.Weaver.Program.Main(String[] args) in c:\BuildAgent\work\sc-2.0.3038.3\Level1\src\scweaver\Program.cs:line 35
   at Starcounter.Server.WeaverService.LogAndRaiseExceptionFromFailingWeaver(ToolInvocationException e) in c:\BuildAgent\work\sc-2.0.3038.3\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 181
   at Starcounter.Server.WeaverService.Weave(String givenAssembly, String runtimeDirectory) in c:\BuildAgent\work\sc-2.0.3038.3\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 116
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.<>c__DisplayClass7.<Execute>b__3(CommandTask task) in c:\BuildAgent\work\sc-2.0.3038.3\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 99
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Action`1 action) in c:\BuildAgent\work\sc-2.0.3038.3\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 481
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.Execute() in c:\BuildAgent\work\sc-2.0.3038.3\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 104
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in c:\BuildAgent\work\sc-2.0.3038.3\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 263
ErrorCode=4078
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4078
```

At least now I know that "SocietyObjects.Concepts.Ring1" clashes with something. The initial error message only said "An item with the same key has already been added". Can this somehow be explained?

---

Could such errors be turned into log warnings, if the checksum of the dll that I am trying to load is the same as already loaded?

**Comment by per-samuelsson** [comment]
Hi @warpech,

Thanks for reporting and providing such a nice explaination!

> Could such errors be turned into log warnings, if the checksum of the dll that I am trying to load is the same as already loaded?

We could definitely do better in terms of covering errornous cases like this. It's just that there has been no real effort doing so. The whole thing with "edition libraries" was one of those things that just "happened", becuase they were needed at a certain time. Tests and covering all possibly "missuses" were not really taken care of, unfortunatelly.

Not sure when I'll get time to fit this in, but it should of course be done sooner or later!

**Comment by per-samuelsson** [comment]
I'll assign it to me at least.

**Comment by per-samuelsson** [comment]
I'm spending some time investigating this now, and I can see the initial problem. When the weaver meets a locally deployed library (e.g. in "bin\debug") that is a duplicate of an edition library, it does not know how to treat this case.

Another thing that is somewhat related, that we have discussed before, is when you have locally deployed Starcounter libraries, such as ```Starcounter.dll```. The effects of this is currently somewhat fuzzy, but will most likely mean the locally deployed library will be kept there, but never loaded (because the code host has already loaded it from the installation directory when the application launch). I'm wondering if we shouldn't change this to a more strict policy instead, failing weaving with an error.

**Comment by per-samuelsson** [comment]
> I'm spending some time investigating this now, and I can see the initial problem. When the weaver meets a locally deployed library (e.g. in "bin\debug") that is a duplicate of an edition library, it does not know how to treat this case.

I'm redesigning the weaver a bit, to detect abnormalties i the form of locally deployed edition libraries and to produce a more descriptive error for this case. The result will be something like this when you try starting the application from within VS.

![image](https://cloud.githubusercontent.com/assets/2902045/6686725/86068000-cca4-11e4-9e78-260585034b51.png)

And a similar error message will be shown when running it from from ```star.exe```, and in both cases, the error will be logged.

Long-term, we might want to do better, like allowing edition libraries to be locally deployed with the application, but since I'm not 100% sure on how it should work, I won't attempt such thing to begin with.

**Comment by per-samuelsson** [comment]
OK, now everything in the [above comment](https://github.com/Starcounter/Starcounter/issues/2579#issuecomment-82304485) is done, merged and pushed to develop (in https://github.com/Starcounter/Starcounter/commit/7cc11a9de96fb3562cb837c4e8a4a79702bb7bb4).

@warpech, with this, and considering what I have written above, should we close this issue do you think?

**Comment by per-samuelsson** [comment]
> @warpech, with this, and considering what I have written above, should we close this issue do you think?

Friday-bump (One year later!) :older_man: :smile:
