### ISSUE TITLE
Having Polyjuice.dll in EditionLibraries fails query processing test and some other

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#2591]
When running the query processing test and having Polyjuice.dll in `StarcounterBin\EditionLibraries` (run_queryprocessingtest.bat) it throws an assertion:
```
[14:23:08]System.Exception: Test assertion failure. 
[14:23:08]   at Starcounter.Internal.ErrorHandling.TestTraceListener.Fail(String message) in c:\BuildAgent\work\sc-2.0.9184.2\Level1\src\Starcounter.Internal\ErrorHandling\TestTraceListener.cs:line 16
[14:23:08]   at System.Diagnostics.TraceInternal.Fail(String message)
[14:23:08]   at QueryProcessingTest.MetadataTest.TestTypeMetadata() in c:\BuildAgent\work\sc-2.0.9184.2\Level1\src\Samples\QueryProcessingTest\MetadataTest.cs:line 104
[14:23:08]   at QueryProcessingTest.MetadataTest.TestPopulatedMetadata() in c:\BuildAgent\work\sc-2.0.9184.2\Level1\src\Samples\QueryProcessingTest\MetadataTest.cs:line 14
[14:23:08]   at QueryProcessingTest.QueryProcessingTestProgram.Main(String[] args) in c:\BuildAgent\work\sc-2.0.9184.2\Level1\src\Samples\QueryProcessingTest\QueryProcessingTestProgram.cs:line 38
[14:23:08]7EDE1D87-8181-4B1C-B1DF-CB939706F8CF--FC8F607939BC-FD1B-C1B4-1818-78D1EDE7ScErrFailingEntrypoint (SCERR4259): The user code entrypoint method raised an exception. System.Exception: Test assertion failure. 
[14:23:08]   at Starcounter.Internal.ErrorHandling.TestTraceListener.Fail(String message) in c:\BuildAgent\work\sc-2.0.9184.2\Level1\src\Starcounter.Internal\ErrorHandling\TestTraceListener.cs:line 16
[14:23:08]   at System.Diagnostics.TraceInternal.Fail(String message)
[14:23:08]   at QueryProcessingTest.MetadataTest.TestTypeMetadata() in c:\BuildAgent\work\sc-2.0.9184.2\Level1\src\Samples\QueryProcessingTest\MetadataTest.cs:line 104
[14:23:08]   at QueryProcessingTest.MetadataTest.TestPopulatedMetadata() in c:\BuildAgent\work\sc-2.0.9184.2\Level1\src\Samples\QueryProcessingTest\MetadataTest.cs:line 14
[14:23:08]   at QueryProcessingTest.QueryProcessingTestProgram.Main(String[] args) in c:\BuildAgent\work\sc-2.0.9184.2\Level1\src\Samples\QueryProcessingTest\QueryProcessingTestProgram.cs:line 56
[14:23:08]Version: 2.0.9184.2.
```
Polyjuice DLL (https://github.com/Polyjuice/Polyjuice) does not really run any database-related code (to start using library, `Init` function should be called explicitly in it). That's why it is strange.

Having Polyjuice.dll in EditionLibraries also caused the issue with --nodb flag and `The operation failed because the current thread wasn't attached to the scheduler`.

To reproduce, build Polyjuice project (it automatically copies its output to EditionLibraries folder) and then run `s\QueryProcessingTest\run_queryprocessingtest.bat` in StarcounterBin.

**Comment by k-rus** [comment]
The test assumes no other classes are loaded, thus it fails that number of tables in meta-data does not match expected number, since SO classes are also loaded. The best approach is to remove SO classes before running the tests, otherwise it is necessary to calculate number of expected instances in the meta-data.

**Comment by k-rus** [comment]
A better approach can be to exclude meta-data about SO classes from query results used in the assertions.

**Comment by alemoi** [comment]
Now this should not be an issue since I added the Polyjuice database flag: http://starcounter.io/nightly-changes/polyjuice-database-flag/
Closing the issue until any further problems.
