### ISSUE TITLE
Could not run a query with LEFT JOIN: System.NotImplementedException

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2616]
Could not run the following query over Simplified database:
```sql
SELECT * 
FROM Simplified.Ring2.Person p
	LEFT JOIN Simplified.Ring3.AddressRelation ar ON ar.Somebody = p
```

The exception:
>System.NotImplementedException
![left-join-exception](https://cloud.githubusercontent.com/assets/6435556/6640776/987e999a-c9aa-11e4-84a0-3ce2cbac8b1b.PNG)

The query works with JOIN, but not with LEFT JOIN.

**Comment by k-rus** [comment]
Thank you for reporting the issue. Can you provide the stack trace?

**Comment by miyconst** [comment]
Sure, here it is:

**Comment by miyconst** [comment]
System.NotImplementedException: The method or operation is not implemented.
 at Starcounter.Query.Execution.NullObject.get_Identity() in c:\BuildAgent\work\sc-2.0.3086.3\Level1\src\Starcounter\Query\Execution\Enumerators\NullObject.cs:line 40
 at Starcounter.Query.Execution.ObjectNoProperty.EvaluateToUInteger(IObjectView obj) in c:\BuildAgent\work\sc-2.0.3086.3\Level1\src\Starcounter\Query\Execution\Properties\ObjectNoProperty.cs:line 82
 at Starcounter.Query.Execution.Row.GetUInt64(Int32 index) in c:\BuildAgent\work\sc-2.0.3086.3\Level1\src\Starcounter\Query\Execution\Row\Row.cs:line 855
 at Starcounter.Internal.SqlRestHandler.ExecuteQuery(String query) in c:\BuildAgent\work\sc-2.0.3086.3\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\SqlRestHandler.cs:line 257
 HResult=-2147467263

**Comment by miyconst** [comment]
The exception valid for SELECT * queries only.
This SQL works:
```SQL
SELECT p.Name
FROM Simplified.Ring2.Person p
    LEFT JOIN Simplified.Ring3.AddressRelation ar ON ar.Somebody = p
```

**Comment by k-rus** [comment]
Thank you for the stack trace. I will look to the bug at the end of next week. I might need your help to reproduce it.

**Comment by k-rus** [comment]
I was not able to reproduce this problem in a simple example. I guess it is related to the complex schema and data together with the selection of everything. Can I get the simplified database? Preferably the code, which creates the data. I guess the schema is SO, correct?

**Comment by k-rus** [comment]
> I was not able to reproduce this problem in a simple example. I guess it is related to the complex schema and data together with the selection of everything. Can I get the simplified database?

I was able to reproduce. So no need in help. Thank you!
