### ISSUE TITLE
An operation was attempted on something that is not a socket 127.0.0.1:8066

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2626]
System.Net.Sockets.SocketException: An operation was attempted on something that is not a socket 127.0.0.1:8066
   at Starcounter.Query.QueryPreparation.PrepareOrExecuteQuery[T](String query, Boolean slowSql, Object[] values) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3100.3\Level1\src\Starcounter\Query\QueryPreparation.cs:line 67
   at Starcounter.Query.Sql.SqlEnumCache.CacheOrExecuteEnumerator[T](String query, Boolean slowSQL, Object[] values) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3100.3\Level1\src\Starcounter\Query\SQL\_SqlEnumCache.cs:line 123
   at Starcounter.Db.FullQueryProcess[T](String query, Boolean slowSQL, Object[] values) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3100.3\Level1\src\Starcounter\Mock\Db.cs:line 126
   at People.PersonsProvider.SelectPersons() in e:\GitHub\People\Server\Database\PersonsProvider.cs:line 8
   at People.PersonsPage.RefreshPersons() in e:\GitHub\People\Server\PersonsPage.json.cs:line 14
   at People.Program.<RegisterPartials>b__36() in e:\GitHub\People\Server\Program.cs:line 187
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, HandlerOptions handlerOptions) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3100.3\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 218
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req, HandlerOptions handlerOptions) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3100.3\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 96
   at Starcounter.Rest.UriManagedHandlersCodegen.RunUriMatcherAndCallHandler(String methodSpaceUriSpace, String methodSpaceUriSpaceLower, Request req, UInt16 portNumber, HandlerOptions handlerOptions, Response& resp) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3100.3\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 997
   at Starcounter.Node.DoRESTRequestAndGetResponse(String method, String relativeUri, Dictionary`2 headersDictionary, Byte[] bodyBytes, Action`2 userDelegate, Object userObject, Int32 receiveTimeoutMs, HandlerOptions handlerOptions, Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3100.3\Level1\src\Starcounter.Node\Node.cs:line 808
   at Starcounter.X.GET[T](String uri, Int32 receiveTimeoutMs, HandlerOptions ho) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3100.3\Level1\src\Starcounter.Node\X.cs:line 272
   at People.Program.GetLauncherPage(String Url, Boolean DbScope) in e:\GitHub\People\Server\Program.cs:line 368
   at People.Program.<Main>b__8() in e:\GitHub\People\Server\Program.cs:line 67
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, HandlerOptions handlerOptions) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3100.3\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 218
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req, HandlerOptions handlerOptions) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3100.3\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 96
   at Starcounter.Rest.UriManagedHandlersCodegen.RunUriMatcherAndCallHandler(String methodSpaceUriSpace, String methodSpaceUriSpaceLower, Request req, UInt16 portNumber, HandlerOptions handlerOptions, Response& resp) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3100.3\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 997
   at Starcounter.Node.DoRESTRequestAndGetResponse(String method, String relativeUri, Dictionary`2 headersDictionary, Byte[] bodyBytes, Action`2 userDelegate, Object userObject, Int32 receiveTimeoutMs, HandlerOptions handlerOptions, Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3100.3\Level1\src\Starcounter.Node\Node.cs:line 808
   at Starcounter.X.GET(String uri, Func`1 substituteHandler) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3100.3\Level1\src\Starcounter.Node\X.cs:line 351
   at Polyjuice.LauncherHelper.WrapInLauncher(Request req, String appName) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3100.3\Polyjuice\src\LauncherHelper.cs:line 177
   at Starcounter.Handle.RunMiddlewareFilters(Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3100.3\Level1\src\Starcounter.Internal\Handle.cs:line 233
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3100.3\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 267
ErrorCode=10038
NativeErrorCode=10038
HResult=-2147467259

**Comment by miyconst** [comment]
SC: Polyjuice-DevelopNightlyBuilds-2.0.3100 (Mar 23, 2015 3:59:22 AM)

This exception occurs on attempt to access database in People application.
Method `SelectPersons`:
https://github.com/Polyjuice/People/blob/master/Server/Database/PersonsProvider.cs#L8

Steps to reproduce:
1. Open Launcher app in a VS instance.
2. Open People app in another VS instance.
3. Run Launcher via Ctrl + F5.
4. Run People app via F5 (debug mode).
5. Try to access url: http://localhost:8080/people/persons without loading launcher first.

**Comment by miyconst** [comment]
Same happens in here:
http://localhost:8080/people/organizations
https://github.com/Polyjuice/People/blob/master/Server/Database/OrganizationsProvider.cs#L8

**Comment by miyconst** [comment]
Forget to mention, that everything works fine without debugging.

**Comment by miyconst** [comment]
The issue is gone after updating Launcher.
