### ISSUE TITLE
Misleading exception when handler does not include app name

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2628]
Starcounter now disallows applications to register URL handlers that do not begin with `/<AppName>`.

In case I try to register such URL handler, the exception message is quite misleading though...

![misleading](https://cloud.githubusercontent.com/assets/566463/6784025/909637bc-d17d-11e4-8111-58b418e7ddb8.png)

> System.ArgumentOutOfRangeException was unhandled by user code
  HResult=-2146233086
  Message=Specified argument was out of the range of valid values.
Parameter name: Error registering handler: GET /master. Polyjuice applications can only register handlers starting with application name prefix, for example, /myapp/foo
  Source=Starcounter.REST
  ParamName=Error registering handler: GET /master. Polyjuice applications can only register handlers starting with application name prefix, for example, /myapp/foo
  StackTrace:
       at Starcounter.Rest.UriManagedHandlersCodegen.RegisterDelegate(UInt16 port, String methodAndUriInfo, MethodInfo userDelegateInfo, Expression delegExpr, NetworkProtocolType protoType, HandlerOptions ho) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3100.3\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 471
       at Starcounter.Rest.UriManagedHandlersCodegen.GenerateParsingDelegate(UInt16 port, String methodAndUriInfo, Func`1 userDelegate, HandlerOptions ho, NetworkProtocolType protoType) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3100.3\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 726
       at Starcounter.Rest.RestRegistrationProxy.RegisterHandler(UInt16 port, String methodAndUriInfo, Func`1 handler, HandlerOptions ho) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3100.3\Level1\src\Starcounter.Rest\RestInitialization.cs:line 59
       at Starcounter.Handle.GET(String uriTemplate, Func`1 code, HandlerOptions ho) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3100.3\Level1\src\Starcounter.Internal\Handle.GET.cs:line 115
       at Program.Main() in c:\StarcounterProjects\InvoiceDemo\invoiceapp\Program.cs:line 6
  InnerException:

**Comment by alemoi** [comment]
Thanks for reporting! Yes, the message dialog is very misleading :) Slightly improved the exception in ccc7654b54113f2defce613d0212441654a26bb4
