### ISSUE TITLE
Terrible situation: responseSizeBytes_ > estimatedNumBytes

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2640]
From time to time I meet a strange exception.
This happens on page refresh.
The page hangs, but after another refresh it works again.

I could not figure out how to reproduce the bag, it occurs in very different situations.

Here is the stack trace from the admin panel.

```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
 Parameter name: Terrible situation: responseSizeBytes_ > estimatedNumBytes
 at Starcounter.Response.ConstructFromFields(Request req, Byte[] givenBuffer) in c:\BuildAgent\work\sc-2.0.9457.2\Level1\src\Starcounter.Internal\Http\Response.cs:line 783
 at Starcounter.Request.SendResponse(Response resp, Byte[] serializationBuf) in c:\BuildAgent\work\sc-2.0.9457.2\Level1\src\Starcounter.Internal\Http\Request.cs:line 1138
 at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\BuildAgent\work\sc-2.0.9457.2\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 296
 at Starcounter.GatewayHandlers.HandleHttpRequest(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in c:\BuildAgent\work\sc-2.0.9457.2\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 406
 ParamName=Terrible situation: responseSizeBytes_ > estimatedNumBytes
 HResult=-2146233086
```

StarCounter version:
http://downloads.starcounter.com/download/Polyjuice/DevelopDailyBuilds/2.0.9457.2

**Comment by miyconst** [comment]
Another stack trace which came together with the previous exception:

```
Access violation (C0000005) detected at bmx_manager.cpp:119 (Thread 11924). 
00007FFECEAE606C KERNELBASE! 
00007FFEB8A77729 clr! 
00007FFEB8A7775B clr! 
00007FFEB8A77765 clr! 
00007FFE597A023C <unknown>! 
FFFFFFFFFFFFFFFE <unknown>! 
00007FFEB8B24F79 clr! 
000000C9F1D15120 <unknown>! 
000000D0CF74F628 <unknown>! 
00007FFE5954F67C <unknown>! 
000000D0CF74F9C0 <unknown>! 
00007FFE597A01E2 <unknown>! 
FFFFFFFFFFFFFFFE <unknown>! 
00007FFEB6AAAD20 clrjit! 
000004E20000002A <unknown>! 
000000CE00000000 <unknown>! 
000000C9F3AF3230 <unknown>! 
00007FFE5954F6AD <unknown>! 
00007FFE59415F60 <unknown>! 
00007FFEB8B24FF1 clr! 
00007FFEB8B24097 clr! 
00007FFEB8B23F8F clr! 
00007FFEB8B23EE0 clr! 
00007FFED14A439D ntdll! 
00007FFED146328C ntdll! 
00007FFEB8B253C0 clr! 
00007FFEB8B25374 clr! 
00007FFED14A431D ntdll! 
00007FFED1463057 ntdll! 
00007FFED1462309 ntdll! 
00007FFECEAE606C KERNELBASE! 
00007FFEB8B245BA clr! 
00007FFEB8B256AE clr! 
00007FFE593737C0 <unknown>! 
0000000070001D41 <unknown>! 
00007FFE59258F08 <unknown>! 
0000000000000024 <unknown>! 
00007FFE5955ADA8 <unknown>! 
000000D0CF74F710 <unknown>! 
000000CCF4253538 <unknown>! 
000000CCF436E308 <unknown>! 
000000CCF436E230 <unknown>! 
0000000000000001 <unknown>! 
0000000000000002 <unknown>!
```

**Comment by miyconst** [comment]
Okay, I found how to reproduce the exception:

1. Run Launcher, GoogleSignInApp, UserAdminApp all together.
2. Go to the main page (http://localhost:8080/)
3. Sign in with Google.
4. Sign out.

Repeat the steps 3 and 4 a couple more times.
The exception will be there.

**Comment by dan31** [comment]
> Terrible situation:

Nice name given! :)

**Comment by per-samuelsson** [comment]
> Nice name given! :)

Haha, I thought exactly the same. It might be good to avoid such terminology, especially in end-user scenarios. :smile:

**Comment by alemoi** [comment]
I found the issue. Will ve fixed soon. Thank you for reporting!

**Comment by alemoi** [comment]
I on purpose used this "Terrible situation" thingy, so that we can get back to this in future. The thing is that this situation should never occur, its like `Assert(False)`. I by mistake forgot to add estimation of buffer size for outgoing cookies. The reason I left it because I don't know how to do an equivalent of native `assert(false)` in managed code, with process termination and error log entry. Can anyone advice? Thank you!
