### ISSUE TITLE
StaticWebServer - NullReferenceException

### ISSUE THREAD

**Issue by andwah** [Starcounter/Starcounter#2645]
Now and then i get this error in my log.

```Error sc://abc/personal Starcounter.Host - System.NullReferenceException: 
Object reference not set to an instance of an object.
at Starcounter.Internal.Web.StaticWebServer.GetFileResource(Response cached, String relativeUri, Request req) in c:\\github\\Level1\\src\\Starcounter.Hypermedia\\StaticWebServer.File.cs:line 90
at Starcounter.Internal.Web.StaticWebServer.GetStaticResponseClone(String relativeUri, Request request) in c:\\github\\Level1\\src\\Starcounter.Hypermedia\\StaticWebServer.cs:line 131
at Starcounter.Internal.Web.AppRestServer.ResolveAndPrepareFile(String relativeUri, Request req) in c:\\github\\Level1\\src\\Starcounter.Apps.JsonPatch\\AppRestServer.cs:line 137
at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in c:\\github\\Level1\\src\\Starcounter.Apps.JsonPatch\\AppRestServer.cs:line 116
at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\\github\\Level1\\src\\Starcounter.Apps.JsonPatch\\AppsBootstrapper.cs:line 256\r\nHResult=-2147467261
```

At the moment i don't have so much more info report,

**Comment by alemoi** [comment]
Thanks for reporting! I will check it.

**Comment by andwah** [comment]
I did some more digging, this is what i found.

In my case the client tries to GET glyphicons-halflings-regular.woff2 (web font format 2.0). 

And that mime type is not "registered" in my windows registry (i think woff2 is not yet adopted officially but i may be wrong).
