### ISSUE TITLE
Callback before merging of Self.GET responses

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2690]
For the purpose of Layout app (which serves layouts for `Self.GET` response and its siblings), a callback before merging of `Self.GET` responses is needed.

As a parameter, the callback should provide the array of responses.

In response to this callback, the Layout app will return a sibling page of it's own:

```json
{
  "PartialID": "",
  "LayoutSetup": {}
}
```

`PartialID` is the value of the `Html` property of the first response in array.
`LayoutSetup` is based on all responses in the array.

cc @tomalec, @chrhol

**Comment by miyconst** [comment]
@warpech what this callback is for?

**Comment by warpech** [comment]
To achieve "1b. PartialId - desired structure" from https://github.com/Polyjuice/Launcher/issues/114

The difference is that `PartialId` would be created by a callback in the Launcher app, not by the serializer.

**Comment by warpech** [comment]
As discussed today with @miyconst and @chrhol, this will also solve point 3 from https://github.com/StarcounterSamples/GoogleSignIn/issues/6#issuecomment-103860894 by allowing Launcher to check if an app handled the request by returning something from handler.

Currently Launcher creates a workspace for SignIn & GoogleSignIn, even when the app response is null. This is because Launcher doesn't actually have a way to check that response, and just [appends it blindly to the workspaces](https://github.com/StarcounterSamples/Launcher/blob/5b1773967c49e874b0b71ab5e35a9238baaba2b7/src/Launcher/Api/LauncherHelper.cs#L193).

**Comment by warpech** [comment]
@chrhol is has a solution for this, which is being implemented in branches:

- https://github.com/Starcounter/Starcounter/tree/issue/2690
- https://github.com/StarcounterPrefabs/Launcher/tree/mergecallback

It works quite well already! We just have the following problems (might be connected):

1. `JsonResponseMerger.RegisterMergeCallback` is called a little more times than desired
2. After visiting few partials in the same Launcher workspace, you will see too many `Launcher` entries in `AppResponses`:

![2016-03-04 17_53_40-launcher](https://cloud.githubusercontent.com/assets/566463/13533997/44aa9bf0-e233-11e5-9fad-8267cf04dc3d.png)

@chrhol I was not able to find the solution for this. Could you please investigate further?

**Comment by per-samuelsson** [comment]
@chrhol 

I sneeked a bit at the code and I really like the way this thing is going, e.g how there are now specializations of the serializer handling that feature-specific stuff.

As we discussed last week, let's see how/if we can shape it up to fit our new middleware pattern once it gets ready for merge. Ping me when you get there and we can take a look at it together.

**Comment by chrhol** [comment]
> It works quite well already! We just have the following problems (might be connected):
1. `JsonResponseMerger.RegisterMergeCallback` is called a little more times than desired
2. After visiting few partials in the same Launcher workspace, you will see too many `Launcher` entries in `AppResponses`:

Number 2 is solved. I think this was a really old problem/bug that was made visible now that we intercept and display more info about the merging-process.

For number 1 I'm not quite sure what can be done. Lets involve @alemoi and see if there is some way to improve this.

I think we're in a quite good shape then. Should be possible to push this to develop soon.

@per-samuelsson: I think we're just about done and ready to push it. Lets take a quick look when you have time and decide if we should use a middleware pattern for this.

**Comment by per-samuelsson** [comment]
> @per-samuelsson: I think we're just about done and ready to push it. Lets take a quick look when you have time and decide if we should use a middleware pattern for this.

Wow, sweet! Well done! :+1: 

> Lets take a quick look when you have time and decide if we should use a middleware pattern for this.

Sure, I'm just off to eat something, we can do it after that if you like!

**Comment by alemoi** [comment]
I have a suggestion: lets write a full list of situations when merger should be called and document them simply.

**Comment by per-samuelsson** [comment]
> I have a suggestion: lets write a full list of situations when merger should be called and document them simply.

Good idea! I'll then add this idea: lets write an overview of what "the merger" is, where it runs (client, code host, only in some app (like launcher), or a mix of those). And what **functional role** it has, and what is needed to activate it. :smile:

**Comment by per-samuelsson** [comment]
@chrhol 

I did some extra reviewing and I ended up thinking that you either just push this when done, and provide some simple code sample and/or references to use-cases (like in Launcher), and I take it on from there, and eventually suggest a middleware tweak if it seem to doable. Then we make that a separate issue. Or you just provide the sample / references, and wait pushing it, and I do the same in that branch.

**Comment by warpech** [comment]
I have just tested `Starcounter-DevelopDailyBuilds-2.1.1382-Setup.exe` (which is supposed to be a build from the current `issue/2690` branch) with Launcher `mergecallback` branch and People `master` branch.

There is some exception that I get when switching from "Organisation" to "People" in the left menu:

<img width="1435" alt="screen shot 2016-03-10 at 12 36 39" src="https://cloud.githubusercontent.com/assets/566463/13668390/c73a763e-e6bc-11e5-9044-4cca2aa71d04.png">

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Starcounter.Templates.TString.CheckAndSetBoundValue(Json parent, Boolean addToChangeLog) in C:\BuildAgent\work\sc-develop-daily-1118\Level1\src\Starcounter.XSON\Templates\TString.cs:line 50
   at Starcounter.Json.<LogObjectValueChangesWithDatabase>b__123_0(ChangeLog clog, Json json, Boolean css) in C:\BuildAgent\work\sc-develop-daily-1118\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 236
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3](Json json, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in C:\BuildAgent\work\sc-develop-daily-1118\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 111
   at Starcounter.Json.LogArrayChangesWithDatabase(ChangeLog changeLog, Boolean callStepSiblings) in C:\BuildAgent\work\sc-develop-daily-1118\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 160
   at Starcounter.Json.<LogObjectValueChangesWithDatabase>b__123_0(ChangeLog clog, Json json, Boolean css) in C:\BuildAgent\work\sc-develop-daily-1118\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 231
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3](Json json, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in C:\BuildAgent\work\sc-develop-daily-1118\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 111
   at Starcounter.Json.<LogObjectValueChangesWithDatabase>b__123_0(ChangeLog clog, Json json, Boolean css) in C:\BuildAgent\work\sc-develop-daily-1118\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 216
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3](Json json, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in C:\BuildAgent\work\sc-develop-daily-1118\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 111
   at Starcounter.Json.<LogObjectValueChangesWithDatabase>b__123_0(ChangeLog clog, Json json, Boolean css) in C:\BuildAgent\work\sc-develop-daily-1118\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 259
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3](Json json, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in C:\BuildAgent\work\sc-develop-daily-1118\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 111
   at Starcounter.Json.LogArrayChangesWithDatabase(ChangeLog changeLog, Boolean callStepSiblings) in C:\BuildAgent\work\sc-develop-daily-1118\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 160
   at Starcounter.Json.<LogObjectValueChangesWithDatabase>b__123_0(ChangeLog clog, Json json, Boolean css) in C:\BuildAgent\work\sc-develop-daily-1118\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 216
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3](Json json, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in C:\BuildAgent\work\sc-develop-daily-1118\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 111
   at Starcounter.Json.LogObjectValueChangesWithDatabase(ChangeLog changeLog, Boolean callStepSiblings) in C:\BuildAgent\work\sc-develop-daily-1118\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 183
   at Starcounter.XSON.ChangeLog.Generate(Boolean flushLog) in C:\BuildAgent\work\sc-develop-daily-1118\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\ChangeLog.cs:line 86
   at Starcounter.XSON.JsonPatch.Generate(ChangeLog changeLog, Boolean includeNamespace, Boolean flushLog, Byte[]& patches) in C:\BuildAgent\work\sc-develop-daily-1118\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 112
   at Starcounter.XSON.JsonPatch.Generate(Json json, Boolean flushLog, Boolean includeNamespace, Byte[]& patches) in C:\BuildAgent\work\sc-develop-daily-1118\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 90
   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(Byte[] bs, WebSocket ws) in C:\BuildAgent\work\sc-develop-daily-1118\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 62
   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 managedHandlerId, UInt32 groupId, WebSocket ws) in C:\BuildAgent\work\sc-develop-daily-1118\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 288
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\BuildAgent\work\sc-develop-daily-1118\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 768
HResult=-2147467261
```

@chrholm could you please take a look?

**Comment by chrhol** [comment]
> @chrhol could you please take a look?

Investigating...

**Comment by chrhol** [comment]
Hmm, I have found the problem and it is kind of obvious when you see it. It's strange that I didn't think of it before this.

It's the `WrapInLauncher` method in the Launcher that doesn't work correctly when a workspace already exists. 

The substitute-handler always creates a new instance of `LayoutInfo` but if the workspace exists we never use the return-value, which means that the workspace-page for the Lancher will be the previous one, and the siblings for the new ones will be messed up (since the partial from People-app is reused but points to new layout which is not used).

In the old solution the workspace-page from the launcher was reused if it existed. Not sure on how to solve this properly, and I'm leaving soon and not working tomorrow :( I guess the long-awaited fix for AppName will have to wait until later this weekend or beginning of next week.

```csharp
static Response WrapInLauncher(Request req) {
    LauncherPage launcher = Self.GET<LauncherPage>("/launcher");
    launcher.uri = req.Uri;

    // Call proxied request
    Response resp = Self.CallUsingExternalRequest(req, () => { return new LayoutInfo(); });
    var page = resp.Resource as LayoutInfo;
    bool createWorkspace = true;
    for (var i = 0; i < launcher.workspaces.Count; i++) {
        var ws = (launcher.workspaces[i] as LayoutInfo);
        if ((launcher.workspaces[i] as LayoutInfo).AppName.ToLower() == page.AppName.ToLower()) {
            createWorkspace = false;
            break;
        }
    }

    if (createWorkspace)
         launcher.workspaces.Add(page);

    return launcher;
}
```

**Comment by per-samuelsson** [comment]
Question about this: will it somehow affect (e.g. replace) the dependency on `Json.GetHtmlPartialUrl()`? 

I'm having real trouble doing this middleware-thingy out of Page/Partial because of that single method (meaning that any `Json` object always have to be self-sufficient and capable of returning a path to a "partial URL").

**Comment by chrhol** [comment]
> Question about this: will it somehow affect (e.g. replace) the dependency on Json.GetHtmlPartialUrl()?

The dependency for `Json.GetHtmlPartialUrl()` is for the html-merger, which needs to be redesigned. So not directly solved by this. We need to discuss how it should work. The html-merger part is the last part to be removed from the serializer

**Comment by per-samuelsson** [comment]
> The dependency for `Json.GetHtmlPartialUrl()` is for the html-merger, which needs to be redesigned. So not directly solved by this. We need to discuss how it should work. The html-merger part is the last part to be removed from the serializer

OK, I see. I tried look again at the code, to understand better. And I noticed that now the launcher callback use this method, so it kind of answered my question. But good you made it even clearer.

I'll try to rethink a little what options that leave me for the thing I'm trying to achieve. Thanks.

**Comment by chrhol** [comment]
> OK, I see. I tried look again at the code, to understand better. And I noticed that now the launcher callback use this method, so it kind of answered my question. But good you made it even clearer.

Yeah, it uses it, but only because it's available. If we solve the htmlmerger part, then this code can either be reomoved or use the same solution as the other.

**Comment by per-samuelsson** [comment]
> If we solve the htmlmerger part, then this code can either be reomoved or use the same solution as the other.

When you have a minute to spare, can you comment on this related https://github.com/Starcounter/Starcounter/issues/3407#issuecomment-196312062? No stress, just want to get your knowledge about it, and confirm if I remember / understand correctly.

**Comment by warpech** [comment]
I just tested current branches:

- https://github.com/Starcounter/Starcounter/tree/issue/2690
- https://github.com/StarcounterPrefabs/Launcher/tree/mergecallback

All the known problems are fixed. I recommend merging to develop branches.

**Comment by Starcounter-Jack** [comment]
Are you aware of the orchestrator discussion?

**Comment by chrhol** [comment]
I've merged the changes to develop (and pnext). I will close this issue since everything in it is solved. 

> Are you aware of the orchestrator discussion?

Maybe this should be discussed in its own thread. The orchestrator is a long-term goal while this issue concerns a needed fix for the current implementation.

**Comment by Starcounter-Jack** [comment]
Agreed. I just think understanding the role of the orchestrator and when the other GETs should be called makes it easier to see what fix is the correct one.

In the furure orchestrator, each ```Self.GET``` is recorded in a log. When the request is processed by a single app (the one catching/handling the request) the orchestrator will call the mapped gets and then perform the merge.

**Comment by dan31** [comment]
I will put the orchestrator description into our dnx plan on gitbook.
Several requested clarification recently.

**Comment by per-samuelsson** [comment]
> I will put the orchestrator description into our dnx plan on gitbook.

Please do. I would very much want to know where it fits in, and how it relates to, the request pipeline and in combo with the new middleware stuff we are currently introducing.
