### ISSUE TITLE
ScErrQueryResultTypeMismatch

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2691]
What this exception means?

I have created a db class:

```csharp
namespace DemoShop
{
    [Database]
    public class Product
    {
        public string Name;
        public string Supllier;
        public string Category;
        public string Description;
    }
}
```

Added some values:
```csharp
Db.Transact(() =>
{
	Product p = new Product();

	p.Name = "Core i7-4770k";
	p.Category = "CPUs";
	p.Supllier = "Intel";
	p.Description = "LGA 1150 intel processor";
});
```

And unable to retrieve the rows:

```csharp
Db.SQL<Product>("SELECT * FROM DemoShop.Product");
```

I also tried
```csharp
Db.SQL("SELECT * FROM DemoShop.Product").First;
```

This query executes with no error, but returns some object, whith type `Starcounter.Query.Execution.Row` instead of `DemoShop.Product`.

```
"System.Exception: ScErrQueryResultTypeMismatch (SCERR7031): Expected generic result type does not match with query result type. The result type DemoShop.Product cannot be assigned from the query result, which is of type Starcounter.Query.Execution.Row.
Version: 2.0.3139.3.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR7031.
   at Starcounter.Query.QueryPreparation.MatchEnumeratorResultAndExpectedType[T](IExecutionEnumerator execEnum) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3139.3\Level1\src\Starcounter\Query\QueryPreparation.cs:line 92
   at Starcounter.Query.QueryPreparation.PrepareOrExecuteQuery[T](String query, Boolean slowSql, Object[] values) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3139.3\Level1\src\Starcounter\Query\QueryPreparation.cs:line 85
   at Starcounter.Query.Sql.SqlEnumCache.CacheOrExecuteEnumerator[T](String query, Boolean slowSQL, Object[] values) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3139.3\Level1\src\Starcounter\Query\SQL\_SqlEnumCache.cs:line 123
   at Starcounter.Db.FullQueryProcess[T](String query, Boolean slowSQL, Object[] values) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3139.3\Level1\src\Starcounter\Mock\Db.cs:line 126
   at DemoShop.IndexPage.RefreshProducts() in e:\GitHub\StarcounterDemoShop\DemoShop\DemoShop\ViewModels\IndexPage.json.cs:line 9
   at DemoShop.Program.<Main>b__0() in e:\GitHub\StarcounterDemoShop\DemoShop\DemoShop\Program.cs:line 14
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3139.3\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 254
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3139.3\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 97
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3139.3\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 313
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR7031
"
```

**Comment by k-rus** [comment]
Thank you for your question!


> And unable to retrieve the rows:
> 
> Db.SQL<Product>("SELECT * FROM DemoShop.Product");

`Product` is not a row, it is an object, while `SELECT *` returns a row, i.e., projection of all columns. Thus mismatch between the type in generic and query result happens.
Projection of more then one column is always represented by `Starcounter.Query.Execution.Row`. See [this page](https://github.com/Starcounter/Starcounter/wiki/SQL-Query-Result) on the wiki for more information.
If you want to get an object of `Product`, then it should be explicitly specified in the query by aliasing:
```c#
Db.SQL<Product>("SELECT p FROM DemoShop.Product p");
```

Let me know if it answers your question.

**Comment by miyconst** [comment]
@k-rus thank you.

It works as you described.

**Comment by k-rus** [comment]
> If you want to get an object of Product, then it should be explicitly specified in the query by aliasing:
> 
> Db.SQL<Product>("SELECT p FROM DemoShop.Product p");

I forgot to say that obtaining object instance as above is preferable way. Obtaining rows of values should be avoided and is mainly for use from Administrator.
