### ISSUE TITLE
Starcounter.SqlException: ScErrSQLIncorrectSyntax with escaped table name

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#2704]
In 1.x, certain applications used square brackets - [, ] - to escape table names when doing queries, as a way to assure table names did not colide with reserved words.

Hence, a typical query would look something like:

> SELECT a FROM [Concepts].[Ring1].[AttributeKind] a WHERE ...

Such query in 2.x (**next**) now generates an exception such as

```
Starcounter.SqlException: ScErrSQLIncorrectSyntax (SCERR7021): Incorrect SQL syntax. Unexpected token. The error near or at position 14, near or at token: [
In query: SELECT a FROM [Concepts].[Ring1].[AttributeKind] a WHERE a.Name = ? AND a.ValueKind = ?
Version: 2.0.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR7021.
   at Starcounter.Query.QueryPreparation.PrepareOrExecuteQuery[T](String query, Boolean slowSql, Object[] values) in c:\Users\Per\Git\Starcounter\Next\Level1\src\Starcounter\Query\QueryPreparation.cs:line 70
   at Starcounter.Query.Sql.SqlEnumCache.CacheOrExecuteEnumerator[T](String query, Boolean slowSQL, Object[] values) in c:\Users\Per\Git\Starcounter\Next\Level1\src\Starcounter\Query\SQL\_SqlEnumCache.cs:line 123
   at Starcounter.Db.FullQueryProcess[T](String query, Boolean slowSQL, Object[] values) in c:\Users\Per\Git\Starcounter\Next\Level1\src\Starcounter\Mock\Db.cs:line 125
   at Starcounter.Db.SQL[T](String query, Object[] values) in c:\Users\Per\Git\Starcounter\Next\Level1\src\Starcounter\Mock\Db.cs:line 92
   at Concepts.Ring1.AttributeKind.AssureKind(String name, Kind valueKind) in c:\Users\Per\Git\Heads.Next\src\Heads.Concepts.Ring1\Attribute.cs:line 87
   at Heads.Application.Program.<TestAttributes>b__0() in c:\Users\Per\Git\Heads.Next\src\Heads.Application\Program.cs:line 47
   at Starcounter.Db.Transact(Action action, UInt32 flags, Boolean forceSnapshot, Int32 maxRetries) in c:\Users\Per\Git\Starcounter\Next\Level1\src\Starcounter\Db.cs:line 269
   at Starcounter.Db.Transact(Action action, Boolean forceSnapshot, Int32 maxRetries) in c:\Users\Per\Git\Starcounter\Next\Level1\src\Starcounter\Db.cs:line 229
   at Heads.Application.Program.TestAttributes() in c:\Users\Per\Git\Heads.Next\src\Heads.Application\Program.cs:line 44
   at Heads.Application.Program.<Main>b__8() in c:\Users\Per\Git\Heads.Next\src\Heads.Application\Program.cs:line 122
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in c:\Users\Per\Git\Starcounter\Next\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 265
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in c:\Users\Per\Git\Starcounter\Next\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 97
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\Users\Per\Git\Starcounter\Next\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 318
ScErrorCode=7021
ErrorMessage=Unexpected token. The error near or at position 14, near or at token: [
In query: SELECT a FROM [Concepts].[Ring1].[AttributeKind] a WHERE a.Name = ? AND a.ValueKind = ?
Token=[
BeginPosition=14
EndPosition=14
Query=SELECT a FROM [Concepts].[Ring1].[AttributeKind] a WHERE a.Name = ? AND a.ValueKind = ?
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR7021
```

Has the notation changed? Should I adapt these queries to something similar?

**Comment by k-rus** [comment]
The syntax to surround identifiers described on [our wiki](https://github.com/Starcounter/Starcounter/wiki/SQL-Identifiers)
Basically use double quotes. Square brackets are reserved for property or array access.

**Comment by per-samuelsson** [comment]
> The syntax to surround identifiers described on our wiki

Thanks! Really stupid of me not to check the wiki first obv. But now we at least have recorded that there is a convertion needed when specifying escaped idenifiers going from 1.x to 2.x, along with the regular syntax conversion.

I'll close this issue.

**Comment by k-rus** [comment]
> Thanks! Really stupid of me not to check the wiki first obv. But now we at least have recorded that there is a convertion needed when specifying escaped idenifiers going from 1.x to 2.x, along with the regular syntax conversion.

Yes. The old convention was removed some time ago as we started to work with new SQL syntax. I guess this is another note to fix in the old code during porting to latest Starcounter.
