### ISSUE TITLE
Unclear error message when property getter overridden

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2707]
As a generalisation of https://github.com/Polyjuice/Simplified/issues/1:

The below code gives unclear error message when tried loading:

```c#
using Starcounter; 

[Database]
public class BasicStuff {
    public string MyProp {
        get {
            return "";
        }
    }
}

public class AdvancedStuff : BasicStuff {
    public string MyProp;
}
```

Error log reports 3 errors at the same timestamp:

```
"ScErrServerCommandFailed (SCERR10011): The operation ""Starting Products in default"" failed.
Version: 2.0.3159.3.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10011."

=======

"System.Exception: ScErrWeavingError (SCERR2030): At least one error has been detected during weaving of the application code. Process exit code: 4050
Version: 2.0.3159.3.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR2030.
   at Starcounter.Server.WeaverService.LogAndRaiseExceptionFromFailingWeaver(ToolInvocationException e) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3159.3\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 140
   at Starcounter.Server.WeaverService.Weave(String givenAssembly, String runtimeDirectory) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3159.3\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 118
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.<>c__DisplayClass7.<Execute>b__3(CommandTask task) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3159.3\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 99
   at Starcounter.Server.Commands.CommandProcessor.<>c__DisplayClass1.<WithinTask>b__0(CommandTask t) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3159.3\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 484
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3159.3\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 510
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.Execute() in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3159.3\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 104
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3159.3\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR2030
---> System.FormatException: ScErrWrongErrorMessageFormat (SCERR1033): Parsing an error message string failed due to an incorrect message format. Message: SCDCV06 - ScErrFieldRedeclaration (SCERR4050): A database class declared a persistent field that has already been declared in one of the parent classes. Version: 2.0.3159.3. Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4050. <,0,0>
Version: 2.0.3159.3.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR1033.
   at Starcounter.Internal.ParsedErrorMessage.InternalParseMessage(String errorMessage) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3159.3\Level1\src\Starcounter.Internal\ErrorHandling\ParsedErrorMessage.cs:line 114
   at Starcounter.Internal.ParsedErrorMessage.Parse(String errorMessage) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3159.3\Level1\src\Starcounter.Internal\ErrorHandling\ParsedErrorMessage.cs:line 65
   at Starcounter.Server.WeaverService.LogAndRaiseExceptionFromFailingWeaver(ToolInvocationException e) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3159.3\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 173
HResult=-2146233033
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR1033
"

=======

"ScErrWeavingError (SCERR2030): At least one error has been detected during weaving of the application code. Process exit code: 4050.
Arguments=--maxerrors=1 --ErrorParcelId=A4A7D6FA-EB34-442A-B579-DBB1DBB859E3 Weave ""C:\PolyjuiceProjects\Polyjuice\Products\bin\Debug\Products.exe"" --outdir=""c:\db\Personal\Temp\default\default-20150511T131946170\weaver\A073DD180505CECE716ABA9303FFCBAEDCD12A99""
Output:
A4A7D6FA-EB34-442A-B579-DBB1DBB859E3SCDCV06 - ScErrFieldRedeclaration (SCERR4050): A database class declared a persistent field that has already been declared in one of the parent classes.
Version: 2.0.3159.3.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4050. <,0,0>A4A7D6FA-EB34-442A-B579-DBB1DBB859E3
SCDCV06 - ScErrFieldRedeclaration (SCERR4050): A database class declared a persistent field that has already been declared in one of the parent classes.
Version: 2.0.3159.3.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4050. <,0,0>

Version: 2.0.3159.3.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR2030."
```

Mind that when **not** using getter, the error message is clearer, though it results in as much as **4 errors** in total reported at the same time:

```c#
[Database]
public class BasicStuff {
    public string MyProp;
}

public class AdvancedStuff : BasicStuff {
    public string MyProp;
}
```

Error log shows 4 (!) errors at the same timestamp:

```
"ScErrServerCommandFailed (SCERR10011): The operation ""Starting Products in default"" failed.
Version: 2.0.3159.3.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10011."

=======

"Starcounter.DbException: ScErrFieldsDifferInCaseOnly (SCERR4261): A field in a database class can not have the same name as a another field in the same class, or in a base class, not even if they differ in casing. Field MyProp in class AdvancedStuff, field MyProp in class BasicStuff. Version: 2.0.3159.3. Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4261. <,0,0>
   at Starcounter.Server.WeaverService.LogAndRaiseExceptionFromFailingWeaver(ToolInvocationException e) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3159.3\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 140
   at Starcounter.Server.WeaverService.Weave(String givenAssembly, String runtimeDirectory) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3159.3\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 118
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.<>c__DisplayClass7.<Execute>b__3(CommandTask task) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3159.3\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 99
   at Starcounter.Server.Commands.CommandProcessor.<>c__DisplayClass1.<WithinTask>b__0(CommandTask t) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3159.3\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 484
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3159.3\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 510
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.Execute() in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3159.3\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 104
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3159.3\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
ErrorCode=4261
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4261
"

=======

"ScErrFieldsDifferInCaseOnly (SCERR4261): A field in a database class can not have the same name as a another field in the same class, or in a base class, not even if they differ in casing. Field MyProp in class AdvancedStuff, field MyProp in class BasicStuff. Version: 2.0.3159.3. Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4261. <,0,0>"

=======

"ScErrWeavingError (SCERR2030): At least one error has been detected during weaving of the application code. Process exit code: 4261.
Arguments=--maxerrors=1 --ErrorParcelId=A4A7D6FA-EB34-442A-B579-DBB1DBB859E3 Weave ""C:\PolyjuiceProjects\Polyjuice\Products\bin\Debug\Products.exe"" --outdir=""c:\db\Personal\Temp\default\default-20150511T131946170\weaver\A073DD180505CECE716ABA9303FFCBAEDCD12A99""
Output:
A4A7D6FA-EB34-442A-B579-DBB1DBB859E3ScErrFieldsDifferInCaseOnly (SCERR4261): A field in a database class can not have the same name as a another field in the same class, or in a base class, not even if they differ in casing. Field MyProp in class AdvancedStuff, field MyProp in class BasicStuff.
Version: 2.0.3159.3.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4261. <,0,0>A4A7D6FA-EB34-442A-B579-DBB1DBB859E3
ScErrFieldsDifferInCaseOnly (SCERR4261): A field in a database class can not have the same name as a another field in the same class, or in a base class, not even if they differ in casing. Field MyProp in class AdvancedStuff, field MyProp in class BasicStuff.
Version: 2.0.3159.3.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4261. <,0,0>

Version: 2.0.3159.3.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR2030."
```

**Comment by per-samuelsson** [comment]
Thanks for reporting this and being so descriptive,  @warpech. I'll assign it to myself to eventually fix, as we have discussed.

A few short comments:

> Mind that when **not** using getter, the error message is clearer:

Thanks for highlighting that. I will make sure error reporting is equal for both cases, and I would probably not have noticed unless you had stressed this.

> Error log shows 4 (!) errors [...]

Yes, and the simple answer is that there are several components in play here - all using the server log, i.e. the admin server report an error that it cannot fullfill the request, and also the weaver generates errors itself.

This is "by design", but not really ideal from a users perspecitve, because it is ill-defined.

If you look closer, you'll see that source/host is differing for some of the errors. I think we should probably consider doing some kind of filtering as a default when clicking "Log" tab. Similar to what I have done in the command-line, when errors are shown there (basically, it filters by default on database/weaver errors, and only shows server/admin errors if no errors from the first category exist). And provide as an **option** to show all, similar to how we do with severity (where we normally dont show debug/trace severity by default, but rather just warnings and up).

**Comment by per-samuelsson** [comment]
Somewhat related to #2629.

**Comment by warpech** [comment]
I have to admit that in Visual Studio only one error shows up in each case, respectively. 

In case of overwriting a getter:

> Error	3	At least one error has been detected during weaving of the application code. Process exit code: 4050 (ScErrWeavingError (SCERR2030))

In case of overwriting a regular string:

> Error	5	A field in a database class can not have the same name as a another field in the same class, or in a base class, not even if they differ in casing. Field MyProp in class AdvancedStuff, field MyProp in class BasicStuff. (ScErrFieldsDifferInCaseOnly (SCERR4261))
