### ISSUE TITLE
Application.Current.WorkingDirectory returns wrong value

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2723]
I have two app running:

1. Launcher.
2. Images.

Images app has a POST handler to upload files.
In this handler `Application.Current.WorkingDirectory` equals to `C:\Data\GitHub\Images\src\Images\wwwroot\media` which is correct.

Images app has a handle for Save button, and here `Application.Current.WorkingDirectory` has wrong value of `C:\Data\GitHub\Launcher\src\Launcher\wwwroot\media`.

@alemoi is it your responsibility?

**Comment by alemoi** [comment]
Thanks for reporting!

> @alemoi is it your responsibility?

Not really, but I can check it when have time. Probably `Application.Current` is not set for Handles.

**Comment by alemoi** [comment]
Sorry for the late response. Is this still not working @miyconst ?

**Comment by miyconst** [comment]
Previously it returned wrong value, and now it throws an exception:

```cs
void Handle(Input.Save Action) {
    var folder = Application.Current.WorkingDirectory; //This line throws an exception.
}
```

Throws:
```
System.InvalidOperationException was unhandled by user code
  HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4264
  HResult=-2146233079
  Message=ScErrApplicationCantBeResolved (SCERR4264): The application could not be resolved based on the given arguments or context.
Version: 2.0.3263.3.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4264.
  Source=Starcounter(2.0.3263.3)
  StackTrace:
       at Starcounter.Application.get_Current() in c:\BuildAgent\work\sc-2.0.3263.3\Level1\src\Starcounter.Internal\Application.cs:line 98
       at Images.IllustrationPage.Handle(Save Action) in e:\GitHub\Images\src\Images\ViewModels\IllustrationPage.json.cs:line 58
       at Images.IllustrationPage.JsonByExample.Schema.<.ctor>b__1d(Json pup, Input`1 input) in e:\GitHub\Images\src\Images\obj\x64\Debug\ViewModels\IllustrationPage.json.g.cs:line 0
       at Starcounter.Templates.Property`1.InvokeHandler(Json parent, Input`1 input) in c:\BuildAgent\work\sc-2.0.3263.3\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 225
       at Starcounter.Templates.Property`1.ProcessInput(Json parent, T value) in c:\BuildAgent\work\sc-2.0.3263.3\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 247
       at Starcounter.XSON.DefaultPatchHandler.ParseAndProcess(TLong property, Json parent, IntPtr valuePtr, Int32 valueSize) in c:\BuildAgent\work\sc-2.0.3263.3\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 105
       at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in c:\BuildAgent\work\sc-2.0.3263.3\Level1\src\Starcounter\TransactionManager.cs:line 449
       at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in c:\BuildAgent\work\sc-2.0.3263.3\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 22
       at Starcounter.XSON.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, IntPtr valuePtr, Int32 valueSize) in c:\BuildAgent\work\sc-2.0.3263.3\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 37
       at Starcounter.XSON.JsonPatch.Apply(Json root, IntPtr patchArrayPtr, Int32 patchArraySize, Boolean strictPatchRejection) in c:\BuildAgent\work\sc-2.0.3263.3\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 599
       at Starcounter.Internal.PuppetRestHandler.<RegisterJsonPatchHandlers>b__3(Session session, Request request) in c:\BuildAgent\work\sc-2.0.3263.3\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 102
       at lambda_method(Closure , Request , IntPtr , IntPtr )
       at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in c:\BuildAgent\work\sc-2.0.3263.3\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 200
       at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in c:\BuildAgent\work\sc-2.0.3263.3\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
       at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\BuildAgent\work\sc-2.0.3263.3\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 327
```

**Comment by alemoi** [comment]
I appreciate your response! Will check this tomorrow!

**Comment by miyconst** [comment]
Any progress on this issue?

**Comment by alemoi** [comment]
No progress yet, but I will check this tonight! :)

**Comment by alemoi** [comment]
I was a bit struggling with this tonight to get some workaround because not familiar with the code. Just pushed a possible solution via 10f3f1fc7012c5083385abcbd98c60543bfd532b
Please @chrhol review the change and probably correct it :)
@miyconst thanks for testing it!

**Comment by miyconst** [comment]
The issue is solved. Thank you @alemoi.
