### ISSUE TITLE
Weaver exception on project start.

### ISSUE THREAD

**Issue by ivarbergman** [Starcounter/Starcounter#2729]
Hi! 
(Starcounter-DevelopNightlyBuilds-2.0.3182)

I have a problem when starting our Tunity project from VS. Immediately after Start, the system halts with the following exception:

    Error	1	System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
       at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
       at Sc.Server.Weaver.Schema.DatabaseClassRef.Resolve(DatabaseClassRef databaseClassRef, DatabaseSchemaElement element) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3182.3\Level1\src\Starcounter\Mock\Schema\DatabaseClassRef.cs:line 84
       at Sc.Server.Weaver.Schema.DatabaseSchema.RecursivePopulateOrderedEntityClasses(DatabaseEntityClass databaseClass, IList`1 orderedClasses, Dictionary`2 index) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3182.3\Level1\src\Starcounter\Mock\Schema\DatabaseSchema.cs:line 353
       at Sc.Server.Weaver.Schema.DatabaseSchema.PopulateOrderedDatabaseEntityClasses2(IList`1 list) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3182.3\Level1\src\Starcounter\Mock\Schema\DatabaseSchema.cs:line 257
       at Starcounter.Internal.SchemaLoader.LoadAndConvertSchema(DirectoryInfo inputDir) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3182.3\Level1\src\Starcounter\Internal\Loader.cs:line 124
       at StarcounterInternal.Hosting.Loader.ExecuteApplication(Void* hsched, String applicationName, String applicationFile, String applicationBinaryFile, String applicationHostFile, String workingDirectory, String[] entrypointArguments, Boolean execEntryPointSynchronously, Stopwatch stopwatch) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3182.3\Level1\src\Hosting\Starcounter.Hosting\Loader.cs:line 172
       at Starcounter.Bootstrap.Management.ExecutablesHandler.OnPOST(Request request) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3182.3\Level1\src\Starcounter.Bootstrap\Management\ExecutablesHandler.cs:line 50
    HResult=-2146232969
    

To reproduce:
1 - Create a empty default database.
2 - Pull the latest Tunity2.0 code from github.
3 - Clean, Build, Start the Tunity2.0 application.
4 - Stop the application
5 - Start the application again.

Now the Exception is thrown. 

What does the exception indicates?

**Comment by ivarbergman** [comment]
Also: 

I did a fresh install of the latest Starcounter-DevelopNightlyBuilds-2.0.3182.
And removed the Simple dll from the EditionLibraries folder.

/Ivar

**Comment by ivarbergman** [comment]
@chrhol have you experienced this behaviour when working with TunityCoLab apps?

**Comment by per-samuelsson** [comment]
Hi @ivarbergman,

Thanks for reporting. I'm trying to set up an environment where I can reproduce this.

> Pull the latest Tunity2.0 code from github.

Where can I find that?

**Comment by per-samuelsson** [comment]
> Clean, **Build**, Start the Tunity2.0 application.

Does it help if you **rebuild** the application? Not sure Clean+Build always perform the same as rebuild, and I suspect this *might* have something to do with references in the weaver cache, possibly caused by the manual removing from EditionLibraries (and that we don't handle that well).

**Comment by per-samuelsson** [comment]
> Where can I find that?

Got the invite. Thanks!

**Comment by ivarbergman** [comment]
Great!

If I Rebuild the solution before the second Start. I get the following error:


    System.Exception: ScErrWeaverCantUseCache (SCERR6077): The weaver was unable to weave the application because of an internal problem with the weaver cache. Run the weaver with the --nocache option to remedy. Assembly: Assembly SocietyObjects.Concepts.Ring1 Version: 2.0.3182.3. Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR6077.
     at Starcounter.Server.WeaverService.LogAndRaiseExceptionFromFailingWeaver(ToolInvocationException e) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3182.3\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 198
     at Starcounter.Server.WeaverService.Weave(String givenAssembly, String runtimeDirectory, Boolean disableEditionLibraries) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3182.3\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 121
     at Starcounter.Server.Commands.StartExecutableCommandProcessor.<>c__DisplayClass7.<Execute>b__3(CommandTask task) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3182.3\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 99
     at Starcounter.Server.Commands.CommandProcessor.<>c__DisplayClass1.<WithinTask>b__0(CommandTask t) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3182.3\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 484
     at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3182.3\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 514
     at Starcounter.Server.Commands.StartExecutableCommandProcessor.Execute() in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3182.3\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 108
     at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3182.3\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
     HResult=-2146233088
     HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR6077

**Comment by per-samuelsson** [comment]
> If I Rebuild the solution before the second Start. I get the following error.

OK, but that does error surface, or is it just in the log? There are a few known problem areas around building especially SO-stuff, and the server should handle them by re-running the weaver a second time, with the cache disabled. And that should work. Does it not in your case?

Furthermore, when I try to build Tunity 2.0, it complain that it doesnt find references to SO-libraries. But as I understood from your GitHub ReadMe, these should be part of the project, should they not? I mean, I don't need to build the manually, right?

**Comment by ivarbergman** [comment]
> OK, but that does error surface, or is it just in the log?

The error shows both in the log and in the VS error console. VS indicates that the application is in Ready state. However, the Tunity application is never started. (Ie Main method never reached.)

>  I mean, I don't need to build the manually, right?
No, you should not need to build SO. The SO files from the Starcounter installation are used (EditionLibraries & Public Assemblies folder)

Do you still have problems with the SO references?

**Comment by per-samuelsson** [comment]
> No, you should not need to build SO. The SO files from the Starcounter installation are used (EditionLibraries & Public Assemblies folder)

> Do you still have problems with the SO references?

Well, yes. But I don't have any EditionLibraries, since I'm running a local build of the latest code which, I thought, corresponded to DevelopNightlyBuilds. But then appearently it does not. And I was also under the impression that EditionLibraries was only part of Polyjuice edition of Starcounter, but its somewhat a moving target it seems, so I guess I need to catch up.

Anyway, I'll try to figure out how to get the environment right myself. Thanks for now!

**Comment by per-samuelsson** [comment]
I now have an environment up, where I can reproduce this. Just a short check:

> To reproduce:
1 - Create a empty default database.
2 - Pull the latest Tunity2.0 code from github.
3 - Clean, Build, Start the Tunity2.0 application.
4 - **Stop the application**
5 - Start the application again.

With [4], you are using **Stop** in VS, right? Thats what I tried at least. And that does not really stop the application, it just detach the debugger. I don't think it really matters, just wanted to make sure we are doing the same thing.

I'll get back to you as soon as I have something to report.

**Comment by ivarbergman** [comment]
> With [4], you are using Stop in VS, right?

Yes I did a Stop in VS.

**Comment by per-samuelsson** [comment]
> Yes I did a Stop in VS.

OK, thanks.

Just for the record, I can reproduce this same thing from the command-line:

> star tunity.exe
> staradmin stop app tunity
> star tunity.exe

**Comment by per-samuelsson** [comment]
Update:

After some researching and stepping code, this seem to be some inconsistency introduced by recent ```PolyjuiceDatabaseFlag```, which is probably why it hasn't occured before. You can read about this flag in #2703 and here: http://starcounter.io/nightly-changes/polyjuice-database-flag/

In short, the second start of the application operates with this flag **not** set, so the edition libraries pulled into the application in the first start is (correctly) removed. And dependencies to them can not be resolved, causing the crash.

Since I haven't really been involved how this all are meant to work together, I can't yet tell you how you should get around this. I guess you can try configure the flag and set it to true, but I'm not sure if your application is really a "polyjuice application" or not, and I think that if you set it to true, other stuff will also start to happen.

I'll further investigate and will get back to you with a better answer.

**Comment by per-samuelsson** [comment]
Found the bug: its an issue from this recent commit: https://github.com/Starcounter/Starcounter/commit/b5962cb3cfed459c3986274598f35e7627f7dc8e. The ```WeaverService.CreateWeaverCommandLine``` method is changed to include another parameter, and the call to it when the server retries without the weaver cache always invokes it with edition libraries enabled (not respecting the configuration).

I will fix this. The problem is that what it will do is that your application will not start even the first time, since it won't be able to resolve the references to the edition libraries. Only if you apply the ```PolyjuiceDatabaseFlag```, the application will work again. And I can't tell you if you should do that or not, unfortunatelly. My guess is you should though, since you are using polyjuice edition libraries.

**Comment by per-samuelsson** [comment]
This is now fixed and merged in https://github.com/Starcounter/Starcounter/commit/f0745c9cede2880b2c84a1fc37a05ca129cd9daa. Let us know how it works @ivarbergman! And thanks for all the help in resolving this!

**Comment by ivarbergman** [comment]
Unfortunately our apps is not yet ready to enable the PolyjuiceDatabaseFlag. (For example we need to rewrite our http uri handling, and this is something we plan to do, but it will take some time.)

This means that Tunity2.0 fails run on the current Starcounter version. We need to find some temporary solution to get us up and running again, until we support the Polyjuice requirements. 

Any suggestions? 

@dan31 , @chrhol : since you are familiar with our Tunity2.0 system, do you have any suggestion on how to run our apps without the PolyjuiceDatabaseFlag?

**Comment by ivarbergman** [comment]
Update: It seems like I can get our application to run with the PolyjuiceDatabaseFlag disabled, by changing the SoC References Property "Copy local" from false to true.
