### ISSUE TITLE
ScErrWeavingError on application start

### ISSUE THREAD

**Issue by peterbergman** [Starcounter/Starcounter#2747]
Hi,

I have a strange issue that started to occur after re-installing a Starcounter edition version from the DevelopNightlyBuilds channel (v. 2.0.3185). When I try to start an application from Visual Studio I get an pop-up with an error message (see screenshot) followed by a stack trace. Also, in the Starcounter error logs the following mesages appear:

First message:
```
ScErrWeavingError (SCERR2030): At least one error has been detected during weaving of the application code. Process exit code: 1.
 Arguments=--FLAG:DisableEditionLibraries --maxerrors=1 --ErrorParcelId=A4A7D6FA-EB34-442A-B579-DBB1DBB859E3 Weave "C:\Users\Peter\Development\Git\DRTB\AccountManager\AccountManager\bin\Debug\AccountManager.exe" --outdir="C:\Users\Peter\Documents\Personal\Temp\accountmanager\accountmanager-20150601T152520193\weaver\C7F5FBD396EDBF90D3FB4B24F0B14C01FC03AF82"
 Output:
 
 Version: 2.0.3185.3.
 Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR2030.
```

Second message:
```
System.Exception: ScErrWeavingError (SCERR2030): At least one error has been detected during weaving of the application code. Process exit code: 1
 Version: 2.0.3185.3.
 Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR2030.
 at Starcounter.Server.WeaverService.LogAndRaiseExceptionFromFailingWeaver(ToolInvocationException e) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3185.3\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 198
 at Starcounter.Server.WeaverService.Weave(String givenAssembly, String runtimeDirectory, Boolean disableEditionLibraries) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3185.3\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 121
 at Starcounter.Server.Commands.StartExecutableCommandProcessor.<>c__DisplayClass7.<Execute>b__3(CommandTask task) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3185.3\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 99
 at Starcounter.Server.Commands.CommandProcessor.<>c__DisplayClass1.<WithinTask>b__0(CommandTask t) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3185.3\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 484
 at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3185.3\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 514
 at Starcounter.Server.Commands.StartExecutableCommandProcessor.Execute() in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3185.3\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 108
 at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3185.3\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
 HResult=-2146233088
 HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR2030
```

Third and final message:
```
ScErrServerCommandFailed (SCERR10011): The operation "Starting AccountManager in accountmanager" failed.
 Version: 2.0.3185.3.
 Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10011.
```

I have tried to uninstall/install the same version a couple of times but the errors persist. Also, I have manually removed all the folder files under the ```Personal``` folder to make sure that no old files remained after the uninstallation.

I know another user who also uses the same version of Starcounter and he is able to run the application that fails on my machine. So it feels like there is something in my Starcounter installation that is corrupt. Do you have any ideas on what the problem might be? 

Screenshot:
![Screenshot](http://i288.photobucket.com/albums/ll169/Peter_Bergman/Screen%20Shot%202015-06-01%20at%2016.19.18_zpsafu29qon.png)

**Comment by peterbergman** [comment]
I might add that the database seems to be created. Also, the same issue occurs if I start the application from command line with the ```star``` command.

**Comment by peterbergman** [comment]
I  think I found the possible source of the error. One of my database classes contained a private field which was an array of another database class. If I remove that array, the error goes away. Can you confirm that this is a bug or something that is by design?
