### ISSUE TITLE
Can't modify the state of the transaction on assigning ViewModel.Data value from Hook

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2766]
I have three apps: `GoogleSignIn`, `SignIn`, `Chatter`.

All of the apps have hooks to `SystemUserSession` for all actions. If user signs in with an app, the other one updates. This works as long as the view model which is being updated is not inside a `Db.Scope`.

In the `Chatter` app I call ViewModel.RefreshUser inside a commit hook:

```csharp
public void RefreshUser() {
    SystemUserSession session = this.GetCurrentSystemUserSession(); //A simple Db.SQL query to select an the session object.

    if (session != null) {
        SystemUser user = session.Token.User;

        this.SystemUser.Data = user; //This line of code throws the exception if the ViewModel is inside Db.Scope, works fine without it.
        this.UserName = user.Username;
    } else {
        this.SystemUser.Data = null;
        this.UserName = "Anonymous";
    }
}
```

Here is the exception text:

```
"Starcounter.DbException: ScErrTransactionLockedOnThread (SCERR4031): Can't modify the state of the transaction.
Version: 2.0.3204.3.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4031.
   at Starcounter.Internal.TransactionManager.Scope[T1,T2](TransactionHandle handle, Action`2 action, T1 arg1, T2 arg2) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3204.3\Level1\src\Starcounter\TransactionManager.cs:line 471
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2](Json json, Action`2 action, T1 arg1, T2 arg2) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3204.3\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 45
   at Starcounter.Json.set_Data(Object value) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3204.3\Level1\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 38
   at Chatter.ChatGroupPage.ChatGroupPageSystemUser.set_Data(SystemUser value) in g:\GitHub\Chatter\obj\x64\Debug\ViewModels\ChatGroupPage.json.g.cs:line 0
   at Chatter.ChatGroupPage.RefreshUser() in g:\GitHub\Chatter\ViewModels\ChatGroupPage.json.cs:line 31
   at Chatter.CommitHooks.RefreshSignInState() in g:\GitHub\Chatter\Api\CommitHooks.cs:line 81
   at Chatter.CommitHooks.<Register>b__0(SystemUserSession s) in g:\GitHub\Chatter\Api\CommitHooks.cs:line 16
   at Starcounter.InvokableHook.InvokeAllWithKey(HookKey key, Object instance) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3204.3\Level1\src\Starcounter\CommitHooks\InvokableHook.cs:line 62
   at Starcounter.Internal.TransactionManager.Commit(Int32 tran_locked_on_thread, Int32 detach_and_free) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3204.3\Level1\src\Starcounter\TransactionManager.cs:line 699
   at Starcounter.Db.Transact(Action action, UInt32 flags, Boolean forceSnapshot, Int32 maxRetries) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3204.3\Level1\src\Starcounter\Db.cs:line 203
   at GoogleSignIn.SignInOut.SignInSystemUser(SystemUser SystemUser) in g:\GitHub\GoogleSignIn\src\GoogleSignIn\Helpers\SignInOut.cs:line 18
   at GoogleSignIn.SignInPage.SignIn(String GoogleAccessToken) in g:\GitHub\GoogleSignIn\src\GoogleSignIn\ViewModels\SignInPage.json.cs:line 60
   at GoogleSignIn.MainHandlers.<Register>b__3(String GoogleAccessToken) in g:\GitHub\GoogleSignIn\src\GoogleSignIn\Api\MainHandlers.cs:line 41
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3204.3\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 266
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3204.3\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 97
   at Starcounter.Self.CallUsingExternalRequest(Request req, Func`1 substituteHandler) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3204.3\Level1\src\Starcounter.Node\Self.cs:line 286
   at LauncherNamespace.LauncherHelper.WrapInLauncher(Request req, String appName) in g:\GitHub\Launcher\src\Launcher\api\LauncherHelper.cs:line 156
   at LauncherNamespace.LauncherHelper.<Init>b__3(Request req) in g:\GitHub\Launcher\src\Launcher\api\LauncherHelper.cs:line 47
   at Starcounter.Handle.RunMiddlewareFilters(Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3204.3\Level1\src\Starcounter.Internal\Handle.cs:line 424
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3204.3\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 340
ErrorCode=4031
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4031
"
```

@chrhol could you take a look please?

**Comment by miyconst** [comment]
`GoogleSignIn` and `SignIn` are updated to use new Commit Hooks. Chatter does not longer update signed in user automatically, a page refresh is required.

When this issue is fixed, the app will be updated and will work as before again.

**Comment by miyconst** [comment]
I found a workaround for Chatter app. Replacing `IBound<SystemUser>` ViewModel with plain text properties fixed the issue.

This issue should still be fixed though.

**Comment by chrhol** [comment]
I dont think this is an issue that can be solved, at least not to make it work according to the first part of the code.

You are (as far as I understand) allowed to modify and add/delete database objects that belongs to the same transaction as is committed, but you cannot switch to another transaction and as a part of that, modify database objects that belongs to another transaction.

In this case (or before the workaround) you are trying to set an object belonging to one transaction on a Data-property which viewmodel has another transaction attached.

I guess the problem here might be that the commit-hook is called during a commit, and not after the commit is successful.

**Comment by miyconst** [comment]
Okay, this sounds reasonable. Can I somehow force a piece of code be executed in scope of another transaction?

For example I start a new thread, attach it to the ViewModel's transaction and start it?

**Comment by chrhol** [comment]
Not sure if this issue is still valid? 

After changes in task-scheduling (#3490, #3529), it should now be possible to call `Session.ScheduleTask` with the sessionid for the session to switch over to, that will be triggered after the commithook is executed, which means that the viewmodel can be updated and changes pushed.

**Comment by miyconst** [comment]
@chrhol is right. This issue is no longer relevant.

Now we can use `Session.ScheduleTask` and `JsonPage.Transaction.Scope` methods to execute some code in scope of a specific session and/or transaction.

Closing this issue.
