### ISSUE TITLE
Exception and unable to shut down application

### ISSUE THREAD

**Issue by andwah** [Starcounter/Starcounter#2778]
**Reproducing steps** (all done within the Administrator)
1. Start the database
2. Install the Launcher (2.0.0-pre14) from the AppStore.
3. Start the Launcher
4. Stop the Launcher....
(it's now not even possible to stop the database)
```
System.MissingFieldException: Field not found: 'Starcounter.Internal.StarcounterEnvironment.AppName'.
   at LauncherNamespace.LauncherHelper.<Init>b__3(Request req)
   at Starcounter.Handle.RunMiddlewareFilters(Request req) in c:\github\Level1\src\Starcounter.Internal\Handle.cs:line 422
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\github\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 339
HResult=-2146233071
```

**Comment by miyconst** [comment]
Similar exception if trying to open Launcher instead of stopping it:

```
System.MissingFieldException: Field not found: 'Starcounter.Internal.StarcounterEnvironment.AppName'.
   at LauncherNamespace.LauncherHelper.<Init>b__3(Request req)
   at Starcounter.Handle.RunMiddlewareFilters(Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3222.3\Level1\src\Starcounter.Internal\Handle.cs:line 424
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3222.3\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 327
HResult=-2146233071
```

**Comment by miyconst** [comment]
This does not happen with Images app, maybe this is Launcher's problem, but it worked on previous versions of Starcounter.

**Comment by andwah** [comment]
I build a new Launcher version and deployed it on the AppStore (2.0.0-pre15). with that everything works.

**Comment by miyconst** [comment]
Again happens for me, with the build: `Polyjuice-DevelopNightlyBuilds-2.0.3231 (Jun 23, 2015 3:00:29 AM)`

```
System.MissingFieldException: Field not found: 'Starcounter.Internal.StarcounterEnvironment.AppName'.
   at LauncherNamespace.LauncherHelper.<Init>b__3(Request req)
   at Starcounter.Handle.RunMiddlewareFilters(Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3231.3\Level1\src\Starcounter.Internal\Handle.cs:line 424
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3231.3\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 332
HResult=-2146233071
```

The exception does not appear when I build and start Launcher from Visual Studio, but the fact that the same exception was caught by three different people (me, @warpech, @andwah) tells me that something is wrong in there.

@alemoi, @chrhol, could you take a look, please?

**Comment by alemoi** [comment]
Thank you for the question! This is a strange exception, it feels that its some mismatch in DLLs. Are you sure there are no local copies of Starcounter libraries around?

**Comment by alemoi** [comment]
Or you are using an old version of Launcher?

**Comment by miyconst** [comment]
This happens when I update SC and then install Launcher from the app store which was compiled under previous version of SC.

Recompilation with new version of SC with no change to the code fixes the issue.
