### ISSUE TITLE
QueryProcessingTest fails on buildserver

### ISSUE THREAD

**Issue by parherman** [Starcounter/Starcounter#2792]
QueryProcessingTest fails on both buildservers:

```
[02:17:54][Step 1/1] System.Exception: Test assertion failure. 
[02:17:54][Step 1/1]    at Starcounter.Internal.ErrorHandling.TestTraceListener.Fail(String message) in c:\BuildAgent\work\sc-2.0.3240.3\Level1\src\Starcounter.Internal\ErrorHandling\TestTraceListener.cs:line 16
[02:17:54][Step 1/1]    at System.Diagnostics.TraceInternal.Fail(String message)
[02:17:54][Step 1/1]    at QueryProcessingTest.MetadataTest.TestTypeMetadata() in c:\BuildAgent\work\sc-2.0.3240.3\Level1\src\Samples\QueryProcessingTest\MetadataTest.cs:line 103
[02:17:54][Step 1/1]    at QueryProcessingTest.MetadataTest.TestPopulatedMetadata() in c:\BuildAgent\work\sc-2.0.3240.3\Level1\src\Samples\QueryProcessingTest\MetadataTest.cs:line 14
[02:17:54][Step 1/1]    at QueryProcessingTest.QueryProcessingTestProgram.Main(String[] args) in c:\BuildAgent\work\sc-2.0.3240.3\Level1\src\Samples\QueryProcessingTest\QueryProcessingTestProgram.cs:line 39
[02:17:54][Step 1/1] 7EDE1D87-8181-4B1C-B1DF-CB939706F8CF--FC8F607939BC-FD1B-C1B4-1818-78D1EDE7ScErrFailingEntrypoint (SCERR4259): The user code entrypoint method raised an exception. System.Exception: Test assertion failure. 
[02:17:54][Step 1/1]    at Starcounter.Internal.ErrorHandling.TestTraceListener.Fail(String message) in c:\BuildAgent\work\sc-2.0.3240.3\Level1\src\Starcounter.Internal\ErrorHandling\TestTraceListener.cs:line 16
[02:17:54][Step 1/1]    at System.Diagnostics.TraceInternal.Fail(String message)
[02:17:54][Step 1/1]    at QueryProcessingTest.MetadataTest.TestTypeMetadata() in c:\BuildAgent\work\sc-2.0.3240.3\Level1\src\Samples\QueryProcessingTest\MetadataTest.cs:line 103
[02:17:54][Step 1/1]    at QueryProcessingTest.MetadataTest.TestPopulatedMetadata() in c:\BuildAgent\work\sc-2.0.3240.3\Level1\src\Samples\QueryProcessingTest\MetadataTest.cs:line 14
[02:17:54][Step 1/1]    at QueryProcessingTest.QueryProcessingTestProgram.Main(String[] args) in c:\BuildAgent\work\sc-2.0.3240.3\Level1\src\Samples\QueryProcessingTest\QueryProcessingTestProgram.cs:line 54
[02:17:54][Step 1/1] Version: 2.0.3240.3.
```

[log](https://scbuildserver/viewLog.html?buildId=29298&buildTypeId=Starcounter_DevelopNightly&tab=buildLog#_focus=4195)

To reproduce on the build server, run a new job and only select QueryProcessingTest and it will fail

**Comment by chrhol** [comment]
The reason was that new databaseclasses was added and the assertions for number of tables, columns and indexes fails.

I've updated the test with correct assertions, waiting for a personal build to succeed before pushing to develop.

**Comment by chrhol** [comment]
I've pushed a fix for this and Started a nigthly build. Will close this issue once it succeeds.
