### ISSUE TITLE
Index was out of range exception - on client-server patch to replace entire object in an array

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2812]
Server throws the following exception if client tries to replace entire object in an array:

The patch:
```javascript
[
    {op: "replace", path: "/_ver#c$", value: 1},
    {op: "test", path: "/_ver#s", value: 0}, 
    {op: "replace", path: "/CurrentPage/Images/Illustrations/0", value: {Name$: "Test", ImageURL$: null}}
]
```

The exception:
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.System.Collections.IList.get_Item(Int32 index)
   at Starcounter.XSON.JsonProperty.EvalutateCurrent(JsonPointer ptr, ViewModelVersion version, Boolean& nextIsIndex) in c:\BuildAgent\work\sc-2.0.3257.3\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonProperty.cs:line 115
   at Starcounter.XSON.JsonProperty.<DoEvaluate>b__0(JsonProperty prop, JsonPointer ptr, ViewModelVersion pv, Boolean isIndex) in c:\BuildAgent\work\sc-2.0.3257.3\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonProperty.cs:line 82
   at Starcounter.Internal.TransactionManager.Scope[T1,T2,T3,T4,TResult](TransactionHandle handle, Func`5 func, T1 arg1, T2 arg2, T3 arg3, T4 arg4) in c:\BuildAgent\work\sc-2.0.3257.3\Level1\src\Starcounter\TransactionManager.cs:line 548
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3,T4,TResult](Json json, Func`5 func, T1 arg1, T2 arg2, T3 arg3, T4 arg4) in c:\BuildAgent\work\sc-2.0.3257.3\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 119
   at Starcounter.XSON.JsonProperty.DoEvaluate(JsonPointer pointer, Json root) in c:\BuildAgent\work\sc-2.0.3257.3\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonProperty.cs:line 79
   at Starcounter.XSON.JsonProperty.Evaluate(JsonPointer pointer, Json root) in c:\BuildAgent\work\sc-2.0.3257.3\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonProperty.cs:line 59
   at Starcounter.XSON.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, IntPtr valuePtr, Int32 valueSize) in c:\BuildAgent\work\sc-2.0.3257.3\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 18
   at Starcounter.XSON.JsonPatch.Apply(Json root, IntPtr patchArrayPtr, Int32 patchArraySize, Boolean strictPatchRejection) in c:\BuildAgent\work\sc-2.0.3257.3\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 599
   at Starcounter.Internal.PuppetRestHandler.<RegisterJsonPatchHandlers>b__3(Session session, Request request) in c:\BuildAgent\work\sc-2.0.3257.3\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 102
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in c:\BuildAgent\work\sc-2.0.3257.3\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 200
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in c:\BuildAgent\work\sc-2.0.3257.3\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 97
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\BuildAgent\work\sc-2.0.3257.3\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 357
ParamName=index
HResult=-2146233086

More information about this error may be available in the server error log.
```

**Comment by miyconst** [comment]
I have created a laboratory branch in Images application. There is a `TEST` button on the main page.

Steps to test:

1. Insert at least one image and save it.
2. Navigate to the main page at http://localhost:8080/images.
3. Press the `TEST` button.

There should be the exception.

The button does the following action:
```js
this.templateInstance.model.Illustrations[0] = { Name$: 'Test', ImageURL$: null }
```

**Comment by miyconst** [comment]
The patch may be invalid from the server point of view, but the exception should be more informative.

**Comment by miyconst** [comment]
cc @chrhol

**Comment by miyconst** [comment]
Met same exception when trying to delete an image.

The patch:
```js
{op: "replace", path: "/workspaces/0/Images/CurrentPage/Images/Illustrations/0/Delete$", value: 2}
```

This worked before, but stopped to work.

**Comment by chrhol** [comment]
I have fixed the problem that led to the NullReferenceException that you described in the first comment (and the same for the delete).
I have also added a proper errormessage for sending a patch from the client that is not supported.

Both fixes are pushed to develop.

**Comment by miyconst** [comment]
The response for an incorrect patch is good for http request:

```
HTTP 400 BadRequest
Only patches for primitive values (boolean, number, string) are allowed from client. Patch: {"op":"replace","path":"/workspaces/0/Images/CurrentPage/Images/Illustrations/0","value":{"Name$":"Test","ImageURL$":null}}
```

But not for WebSocket, which simply accepts the patch with no answer at all.

**Comment by chrhol** [comment]
> But not for WebSocket, which simply accepts the patch with no answer at all.

When I run websocket I get this text in the console output, no other notification though:

![ws_err](https://cloud.githubusercontent.com/assets/1658979/8718471/ecc2dc80-2ba4-11e5-8c9f-43058cc50d2d.jpg)

**Comment by miyconst** [comment]
Okay I check it again.

**Comment by miyconst** [comment]
Yes. The exception is visible. Closing the issue.
