### ISSUE TITLE
Transaction.Rollback: The operation failed because of an invalid object access

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2814]
Trying to rollback transaction 

```cs
void Handle(Input.CancelChanges Action) {
    this.Transaction.Rollback();
}
```

causes this error:

```
Starcounter.DbException: ScErrInvalidObjectAccess (SCERR4174): The operation failed because of an invalid object access.
Version: 2.0.3259.3.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4174.
   at Starcounter.Internal.DbState.ReadString(UInt64 oid, UInt64 address, Int32 index) in c:\BuildAgent\work\sc-2.0.3259.3\Level1\src\Starcounter\Internal\DbState.cs:line 595
   at Starcounter.Templates.TString.CheckAndSetBoundValue(Json parent, Boolean addToChangeLog) in c:\BuildAgent\work\sc-2.0.3259.3\Level1\src\Starcounter.XSON\Templates\TString.cs:line 43
   at Starcounter.Json.<LogObjectValueChangesWithDatabase>b__2(ChangeLog clog, Json json, Boolean css) in c:\BuildAgent\work\sc-2.0.3259.3\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 227
   at Starcounter.Internal.TransactionManager.Scope[T1,T2,T3](TransactionHandle handle, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in c:\BuildAgent\work\sc-2.0.3259.3\Level1\src\Starcounter\TransactionManager.cs:line 482
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3](Json json, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in c:\BuildAgent\work\sc-2.0.3259.3\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 61
   at Starcounter.Json.LogArrayChangesWithDatabase(ChangeLog changeLog, Boolean callStepSiblings) in c:\BuildAgent\work\sc-2.0.3259.3\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 154
   at Starcounter.Json.<LogObjectValueChangesWithDatabase>b__2(ChangeLog clog, Json json, Boolean css) in c:\BuildAgent\work\sc-2.0.3259.3\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 216
   at Starcounter.Internal.TransactionManager.Scope[T1,T2,T3](TransactionHandle handle, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in c:\BuildAgent\work\sc-2.0.3259.3\Level1\src\Starcounter\TransactionManager.cs:line 482
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3](Json json, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in c:\BuildAgent\work\sc-2.0.3259.3\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 61
   at Starcounter.Json.<LogObjectValueChangesWithDatabase>b__2(ChangeLog clog, Json json, Boolean css) in c:\BuildAgent\work\sc-2.0.3259.3\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 256
   at Starcounter.Internal.TransactionManager.Scope[T1,T2,T3](TransactionHandle handle, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in c:\BuildAgent\work\sc-2.0.3259.3\Level1\src\Starcounter\TransactionManager.cs:line 482
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3](Json json, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in c:\BuildAgent\work\sc-2.0.3259.3\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 61
   at Starcounter.Json.LogArrayChangesWithDatabase(ChangeLog changeLog, Boolean callStepSiblings) in c:\BuildAgent\work\sc-2.0.3259.3\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 154
   at Starcounter.Json.<LogObjectValueChangesWithDatabase>b__2(ChangeLog clog, Json json, Boolean css) in c:\BuildAgent\work\sc-2.0.3259.3\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 216
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3](Json json, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in c:\BuildAgent\work\sc-2.0.3259.3\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 61
   at Starcounter.Json.LogObjectValueChangesWithDatabase(ChangeLog changeLog, Boolean callStepSiblings) in c:\BuildAgent\work\sc-2.0.3259.3\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 266
   at Starcounter.XSON.ChangeLog.Generate(Boolean flushLog) in c:\BuildAgent\work\sc-2.0.3259.3\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\ChangeLog.cs:line 86
   at Starcounter.XSON.JsonPatch.Generate(ChangeLog changeLog, Boolean includeNamespace, Boolean flushLog, Byte[]& patches) in c:\BuildAgent\work\sc-2.0.3259.3\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 99
   at Starcounter.XSON.JsonPatch.Generate(Json json, Boolean flushLog, Boolean includeNamespace, Byte[]& patches) in c:\BuildAgent\work\sc-2.0.3259.3\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 83
   at Starcounter.Internal.JsonMimeConverter.Convert(Request request, Object before, MimeType mimeType, MimeType& resultingMimeType) in c:\BuildAgent\work\sc-2.0.3259.3\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\JsonMimeConverter.cs:line 21
   at Starcounter.Page.AsMimeType(MimeType mimeType, MimeType& resultingMimeType, Request request) in c:\BuildAgent\work\sc-2.0.3259.3\Level1\src\Starcounter\Page.cs:line 49
   at Starcounter.Response.ConstructFromFields(Request req, Byte[] givenBuffer) in c:\BuildAgent\work\sc-2.0.3259.3\Level1\src\Starcounter.Internal\Http\Response.cs:line 804
   at Starcounter.Request.SendResponse(Response resp, Byte[] serializationBuf) in c:\BuildAgent\work\sc-2.0.3259.3\Level1\src\Starcounter.Internal\Http\Request.cs:line 1174
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\BuildAgent\work\sc-2.0.3259.3\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 398
ErrorCode=4174
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4174

More information about this error may be available in the server error log.
```

cc @chrhol

**Comment by chrhol** [comment]
My first thought is that this is probably the same problem as in #2140 

Puppets does not correctly handle databaseobjects that is deleted or does not exist anymore (which might happen if you create a new object and then rollback the transaction).

**Comment by miyconst** [comment]
Any progress on this issue?

**Comment by miyconst** [comment]
Having same issue when deleting an object inside a `Db.Scope`.

**Comment by miyconst** [comment]
After note from @warpech I did like this:

```cs
this.Data.Delete();
this.Data = null;
```

And deleting works. It should be documented somewhere, that the object should be manually detached from json after/before deleted.

**Comment by chrhol** [comment]
Sorry for the late response. 

> After note from @warpech I did like this:

> And deleting works. It should be documented somewhere, that the object should be manually  detached from json after/before deleted.

Yep, agree. However it should work without it as well I think. We need to see that an object have been deleted when we gather changes to be sent to the client and properly handle it when the viewmodel is stateful. 

I'm working on fixing this and will try to find some place to add the solution in the previous comment in some documentation.

**Comment by miyconst** [comment]
In current applications I manually remove json item before removing it from database. This approach seems not to be possible when two or  more applications share same screen.

The main application, which contains `Save` and `Cancel` buttons, knows when to update json view-model, but the secondary apps have no idea of when the main app is going to rollback transaction.

So, the questions are:

- Are there any progress on this issue?
- Are there any events in `Starcounter.Transaction`, so the secondary apps can subscribe for rollback and update json according to database state?

**Comment by chrhol** [comment]
> - Are there any progress on this issue?

I started implementing check for invalid dataobjects, but did not finish. I got stuck on the proper way of handling an jsonobject having a deleted dataobject. Should the dataobject be removed or should the whole jsonobject be removed? And then I got sidetracked before finishing. 

> - Are there any events in Starcounter.Transaction, so the secondary apps can subscribe for rollback and update json according to database state?

No, there are no events on Transaction (or anywhere else for that matter) other than Commithooks, and I'm not sure listening to database changes is the right way for this case, since we are talking about changes in the viewmodel before the transactions is committed.

> The main application, which contains Save and Cancel buttons, knows when to update json view-model, but the secondary apps have no idea of when the main app is going to rollback transaction.

This is another issue I think that also is important, that we have discussed before. What is the correct pattern for save/cancel behaviour. Shouldn't all apps get a chance to handle these kind of events? (https://github.com/StarcounterSamples/Polyjuice/issues/62)
