### ISSUE TITLE
Dynamic Json and unsupported types

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2820]
I met the following limitations with dynamic json, not sure it is a bug though.

### Response type
```cs
dynamic json = new Json();
json.Center = Self.GET("/website/partial/team");
```

```
System.Exception: Cannot add the Center property to the template as the type Response is not supported for Json properties
```

### Dynamic type
```cs
dynamic json = new Json();
json.Person = new { FirstName = "Konstantin", LastName = "Mi" };
```

```
System.Exception: Cannot add the Person property to the template as the type <>f__AnonymousType0`4 is not supported for Json properties
```

@chrhol take a look, please.

**Comment by miyconst** [comment]
Looks like I can't assign value of any class type, not only dynamic type.

**Comment by chrhol** [comment]
I start with how it works at the moment.

**Response type**: Json have implicit conversions between Response and Json which means ordinarily you don't need to convert a Response to Json when used with for example `Self.GET`. However when used as dynamic you have to manually cast the response to Json to make it work.

```csharp
dynamic json = new Json();
json.Center = (Json)Self.GET("/website/partial/team");
```

**Dynamic type**: The use of dynamic Json does not work with single objects. So the code here would need to be changed to this:

```csharp
dynamic json = new Json();
json.Person = new Json();
json.Person.FirstName =  "Konstantin";
json.Person.LastName = "Mi";
```
The problem here is converting the anonymous type to an instance of Json before the properties are set.

For the first part, I think it should be doable to have the implicit conversion work when used in a dynamic way. For the second part, I'm not sure how it could be improved, to write the code as you did would be the preferred outcome. Not sure if it's doable though. We have to investigate it I guess.

**Comment by miyconst** [comment]
So, the main restriction is that dynamic json may contain properties with primitive types. The objects should be of type `Json`. Right?

I have a class:

```cs
class Person : Starcounter.Json {
	public string Key { get; set; }
	public string FirstName { get; set; }
	public string LastName { get; set; }
	public string Url { get; set; }
}
```

And dynamic json:

```cs
var peson = new Person();
dynamic json = new Json();

json.Person = person;
```

This throws the following exception:

```
System.Exception: Cannot change parent of objects in Typed JSON trees
   at Starcounter.Json.set_Parent(Json value) in c:\BuildAgent\work\sc-2.0.3269.3\Level1\src\Starcounter.XSON\Class Json\Json.cs:line 348
   at Starcounter.Templates.TContainer.UpdateParentAndIndex(Json parent, Json newValue) in c:\BuildAgent\work\sc-2.0.3269.3\Level1\src\Starcounter.XSON\Templates\Foundation\TContainer.cs:line 43
   at Starcounter.Templates.TObject.BoundOrUnboundSet(Json parent, Json value) in c:\BuildAgent\work\sc-2.0.3269.3\Level1\src\Starcounter.XSON\Templates\TObject.cs:line 137
   at CallSite.Target(Closure , CallSite , Object , Person )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Website.Program.GetMemberValue(String Key) in e:\GitHub\Website\Website\Website\Program.cs:line 125
   at Website.Program.GetMemberPage(String Key) in e:\GitHub\Website\Website\Website\Program.cs:line 131
   at Website.Program.<Main>b__16(String Key) in e:\GitHub\Website\Website\Website\Program.cs:line 55
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in c:\BuildAgent\work\sc-2.0.3269.3\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 266
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in c:\BuildAgent\work\sc-2.0.3269.3\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\BuildAgent\work\sc-2.0.3269.3\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 325
HResult=-2146233088

More information about this error may be available in the server error log.
```

**Comment by chrhol** [comment]
The problem is that the Jsonobject is just a proxy-object, so you cannot create a class that inherits json and add properties like this. You need a Template defining the values and then the properties in the Json-class use the template to get and set the value.

The actual value/s is not necessarily stored on the instance, but it's decided based on the template and underlying storage.

For example a Json containing only `FirstName` would look like this (a bit simplified):

```csharp
class Person : Starcounter.Json {
    private static TObject defaultTemplate;
    private static TString firstNameTemplate;

    public Person() {
        Template = defaultTemplate;
    }
    static Person() {
        defaultTemplate = new TObject();
        firstNameTemplate = defaultTemplate.Add<TString>("FirstName");
    }

    public string FirstName { 
        get { return firstNameTemplate.Getter(this); }
        set { firstNameTemplate.Setter(this, value); }
    }
}
```

In this example the value for `FirstName` would be stored in an array and not as a member of the class.

When you use static files (JSON-by-example) the code creating the template is generated compile-time and when you use a dynamic object the template is built runtime but you always have a template that is connected to the json proxyobject.

**Comment by chrhol** [comment]
Actually, I don't get the exception you get. I just get an empty json.

Could you paste the whole bit you are running when you get this?

**Comment by miyconst** [comment]
Thank you for the explanation. Looks like creating typed json is much simpler then manually fill template.

**Comment by miyconst** [comment]
You can take the whole project: https://github.com/Polyjuice/Website

Uncomment two lines:
```
Person.cs line 8
Program.cs line 125
```

Navigate to `http://localhost:8080/website/team/konstantin`.

**Comment by miyconst** [comment]
Another exception when trying to assign an array value to a dynamic json.

```cs
public class ContainerPage : Json {
}

dynamic json = new Json();
json.Rows = new Arr<ContainerPage>();
```

```
System.InvalidCastException was unhandled by user code
  HResult=-2147467262
  Message=Unable to cast object of type 'Starcounter.Arr`1[Website.ViewModels.ContainerPage]' to type 'Starcounter.Arr`1[Starcounter.Json]'.
  Source=Starcounter.XSON
  StackTrace:
       at Starcounter.Templates.TArray`1.SetValueAsObject(Json parent, Object value) in c:\BuildAgent\work\sc-2.0.3271.3\Level1\src\Starcounter.XSON\Templates\TArray.cs:line 148
       at Starcounter.Json.set_Item(String key, Object value) in c:\BuildAgent\work\sc-2.0.3271.3\Level1\src\Starcounter.XSON\Class Json\Json.cs:line 450
       at Starcounter.Json.set_Item(String key, Object value) in c:\BuildAgent\work\sc-2.0.3271.3\Level1\src\Starcounter.XSON\Class Json\Json.cs:line 450
       at CallSite.Target(Closure , CallSite , Object , String , Arr`1 )
       at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
       at Website.Program.<>c__DisplayClass13.<AddHandle>b__e() in e:\GitHub\Website\Website\Website\Program.cs:line 102
       at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in c:\BuildAgent\work\sc-2.0.3271.3\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 266
       at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in c:\BuildAgent\work\sc-2.0.3271.3\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
       at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\BuildAgent\work\sc-2.0.3271.3\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 325
  InnerException: 
```

Some reading:
https://msdn.microsoft.com/en-us/library/dd799517(v=vs.110).aspx
https://msdn.microsoft.com/en-us/library/dd997386(v=vs.110).aspx

**Comment by miyconst** [comment]
And another exception:

```cs
public class ContainerPage : Json {
}

dynamic json = new Json();
Arr<Json> rows = new Arr<Json>();

rows.Add(new ContainerPage()); //The exception happens here.
json.Rows = rows;
```

```
System.InvalidOperationException: Can only be called on arrays.
   at Starcounter.Json.VerifyIsArray() in c:\BuildAgent\work\sc-2.0.3271.3\Level1\src\Starcounter.XSON\Class Json\Json.IList.cs:line 17
   at Starcounter.Json.VerifyJsonForInserting(Object item) in c:\BuildAgent\work\sc-2.0.3271.3\Level1\src\Starcounter.XSON\Class Json\Json.IList.cs:line 239
   at Starcounter.Json._Add(Object item) in c:\BuildAgent\work\sc-2.0.3271.3\Level1\src\Starcounter.XSON\Class Json\Json.IList.cs:line 315
   at Website.Program.<>c__DisplayClass13.<AddHandle>b__e() in e:\GitHub\Website\Website\Website\Program.cs:line 98
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in c:\BuildAgent\work\sc-2.0.3271.3\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 266
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in c:\BuildAgent\work\sc-2.0.3271.3\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\BuildAgent\work\sc-2.0.3271.3\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 325
HResult=-2146233079
```

**Comment by chrhol** [comment]
I've been going through the dynamic parts of Typed Json and I think we need to review and rework all parts so that it works as we want. I have found a lot of stuff that simply does not work or is just confusing.

The problems in both these exceptions above is that the array (`Arr<T>`) is created directly and then set as a property on an jsonobject, or I should rather say the problem lies in the implementation, not that the array is created directly.

In the first exception, `System.InvalidCastException`,wrong template is created (`TArray<Json>` instead of `TArray<ContainerPage>`, and adding items fail

In the second exception, no template at all is created and the check if the jsonobject is an array or not fails. 

Currently the only way I could get to work is to add items to an ordinary `List<Json>` and assign that one to the property:

```csharp
public class ContainerPage : Json {
}

dynamic json = new Json();
List<Json> rows = new List<Json>();

rows.Add(new ContainerPage()); 
json.Rows = rows;
```

I will add another issue that collects the existing issues and to have a starting point for discussing how working with dynamic json should work.

**Comment by miyconst** [comment]
Thanks for looking into this, for now I went with a solution with type json view model.

**Comment by miyconst** [comment]
Unable to set value of a dynamic json, if it was initialized with json string:

```cs
dynamic json = new Json(jsonString);
json.Html = ""; //This throws exception
```

```
An attempt was made to set the property Html to a String on an Obj object not having the property defined in the template.
```

This is probably not a bug, but I still expect it to work.

**Comment by miyconst** [comment]
Closing this issue as outdated.
