### ISSUE TITLE
Administrator does enormous amount of DbSession.RunAsync calls

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#2912]
Here is a problem:

```c#
at Starcounter.Hosting.TaskSchedulerImpl.Run(ITask task, Byte schedId)
at Starcounter.Session.ForAll(UInt64 cargoId, Action`1 action)
at Administrator.Server.Model.AppStoreStore.Applications_CollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
at Administrator.Server.Model.Database.UpdateAppStoreApplications(AppStoreStore store, IList`1 freshAppStoreApplications)
at Administrator.Server.Managers.AppStoreManager.<>c__DisplayClass3.<GetApplications>b__1(Response response, Object userObject)
at Starcounter.Task.Run()
at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask)
at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched)

at Starcounter.Hosting.TaskSchedulerImpl.Run(ITask task, Byte schedId)
at Starcounter.Session.ForAll(UInt64 cargoId, Action`1 action)
at Administrator.Server.Model.AppStoreStore.Applications_CollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
at Administrator.Server.Model.Database.UpdateAppStoreApplications(AppStoreStore store, IList`1 freshAppStoreApplications)
at Administrator.Server.Managers.AppStoreManager.<>c__DisplayClass3.<GetApplications>b__1(Response response, Object userObject)
at Starcounter.Task.Run()
at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask)
at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched)

at Starcounter.Hosting.TaskSchedulerImpl.Run(ITask task, Byte schedId)
at Starcounter.Session.ForAll(UInt64 cargoId, Action`1 action)
at Administrator.Server.Model.AppStoreStore.Applications_CollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
at Administrator.Server.Model.Database.UpdateAppStoreApplications(AppStoreStore store, IList`1 freshAppStoreApplications)
at Administrator.Server.Managers.AppStoreManager.<>c__DisplayClass3.<GetApplications>b__1(Response response, Object userObject)
at Starcounter.Task.Run()
at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask)
at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched)

at Starcounter.Hosting.TaskSchedulerImpl.Run(ITask task, Byte schedId)
at Starcounter.Session.ForAll(UInt64 cargoId, Action`1 action)
at Administrator.Server.Model.AppStoreStore.Applications_CollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
at Administrator.Server.Model.Database.UpdateAppStoreApplications(AppStoreStore store, IList`1 freshAppStoreApplications)
at Administrator.Server.Managers.AppStoreManager.<>c__DisplayClass3.<GetApplications>b__1(Response response, Object userObject)
at Starcounter.Task.Run()
at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask)
at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched)

at Starcounter.Hosting.TaskSchedulerImpl.Run(ITask task, Byte schedId)
at Starcounter.Session.ForAll(UInt64 cargoId, Action`1 action)
at Administrator.Server.Model.AppStoreStore.Applications_CollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
at Administrator.Server.Model.Database.UpdateAppStoreApplications(AppStoreStore store, IList`1 freshAppStoreApplications)
at Administrator.Server.Managers.AppStoreManager.<>c__DisplayClass3.<GetApplications>b__1(Response response, Object userObject)
at Starcounter.Task.Run()
at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask)
at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched)

at Starcounter.Hosting.TaskSchedulerImpl.Run(ITask task, Byte schedId)
at Starcounter.Session.ForAll(UInt64 cargoId, Action`1 action)
at Administrator.Server.Model.AppStoreStore.Applications_CollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
at Administrator.Server.Model.Database.UpdateAppStoreApplications(AppStoreStore store, IList`1 freshAppStoreApplications)
at Administrator.Server.Managers.AppStoreManager.<>c__DisplayClass3.<GetApplications>b__1(Response response, Object userObject)
at Starcounter.Task.Run()
at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask)
at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched)

at Starcounter.Hosting.TaskSchedulerImpl.Run(ITask task, Byte schedId)
at Starcounter.Session.ForAll(UInt64 cargoId, Action`1 action)
at Administrator.Server.Model.AppStoreStore.Applications_CollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
at Administrator.Server.Model.Database.UpdateAppStoreApplications(AppStoreStore store, IList`1 freshAppStoreApplications)
at Administrator.Server.Managers.AppStoreManager.<>c__DisplayClass3.<GetApplications>b__1(Response response, Object userObject)
at Starcounter.Task.Run()
at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask)
at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched)

at Starcounter.Hosting.TaskSchedulerImpl.Run(ITask task, Byte schedId)
at Starcounter.Session.ForAll(UInt64 cargoId, Action`1 action)
at Administrator.Server.Model.AppStoreStore.Applications_CollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
at Administrator.Server.Model.Database.UpdateAppStoreApplications(AppStoreStore store, IList`1 freshAppStoreApplications)
at Administrator.Server.Managers.AppStoreManager.<>c__DisplayClass3.<GetApplications>b__1(Response response, Object userObject)
at Starcounter.Task.Run()
at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask)
at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched)

at Starcounter.Hosting.TaskSchedulerImpl.Run(ITask task, Byte schedId)
at Starcounter.Session.ForAll(UInt64 cargoId, Action`1 action)
at Administrator.Server.Model.AppStoreStore.Applications_CollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
at Administrator.Server.Model.Database.UpdateAppStoreApplications(AppStoreStore store, IList`1 freshAppStoreApplications)
at Administrator.Server.Managers.AppStoreManager.<>c__DisplayClass3.<GetApplications>b__1(Response response, Object userObject)
at Starcounter.Task.Run()
at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask)
at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched)
```

To enable this trace add the following 2 lines to the `void Run(ITask task, Byte schedId = Byte.MaxValue) ` in TaskSchedulerImpl.cs:

```c#
System.Diagnostics.StackTrace t = new System.Diagnostics.StackTrace();
Console.WriteLine(t.ToString());
```
This was causing not being able even to start `scservice.exe` on the build servers (problem causes input queue to be full which makes scadminserver.exe die).

Commenting the following line in database.cs solves the problem:
```c#
this.AppStoreStores.CollectionChanged += AppStoreStores_CollectionChanged;
```
I have commented this line.
Assigning @andwah.

**Comment by andwah** [comment]
For each time i call ```Session.ForAll(...)``` ```Starcounter.Hosting.TaskSchedulerImpl.Run``` is called atleast eight times,

I have optimized some code in the administrator so  ```Session.ForAll(...)``` will be called some fewer times (code not pushed yet). But this issue above will still occure i guess but not as often.

When the datamodel is changed i need to push out the changes to the clients, I use ```Session.ForAll(...)``` to accomplish that push.

**Comment by alemoi** [comment]
Hmm I wonder how we can fix this permanently.
The issue that I experienced on scbuildserver was a pure start of scservice.exe, no applications, no clients. During that start the scadminiserver.exe was immediately dying because of ScErrInputQueueFull exception, which means the number of unprocessed scheduled tasks was more that 4095 per scheduler. When I commented the following:
```c#
this.AppStoreStores.CollectionChanged += AppStoreStores_CollectionChanged;
```
then problem disappeared.
I would say calling `Session.ForAll(...)` is not a problem at all, and it should be called! The problem is frequency of `Session.ForAll(...)` calls, which was enormous in the case I described here. So something is wrong there. I can try to reproduce this problem again to see if you can check it on the build server.

**Comment by andwah** [comment]
@alemoi I did some re-factoring on how event's is fired. now there should be less calls to DbSession.RunAsync. Can you check if it's okey? if so please close this issue
