### ISSUE TITLE
Unhelpful error message when Html path not given in Page class

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2952]
When I declare a Page without Html property, or with empty value, I get the following runtime exception:

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Starcounter.Self.DoSelfNodeCall(UInt16 portNumber, String method, String relativeUri, Dictionary`2 headersDictionary, String body, Byte[] bodyBytes, HandlerOptions handlerOptions, Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-36\Level1\src\Starcounter.Internal\Rest\Self.cs:line 334
   at Starcounter.Self.GET(UInt16 port, String uri, Dictionary`2 headersDictionary, HandlerOptions ho) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-36\Level1\src\Starcounter.Internal\Rest\Self.cs:line 133
   at Starcounter.Page.AsMimeType(MimeType mimeType, MimeType& resultingMimeType, Request request) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-36\Level1\src\Starcounter\Page.cs:line 49
   at Starcounter.Response.ConstructFromFields(Request req, Byte[] givenBuffer) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-36\Level1\src\Starcounter.Internal\Http\Response.cs:line 800
   at Starcounter.Request.SendResponse(Response resp, Byte[] serializationBuf) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-36\Level1\src\Starcounter.Internal\Http\Request.cs:line 1192
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-36\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 507
HResult=-2146233080

More information about this error may be available in the server error log.
```

It looks much better when the file is not found:

```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: Can not find file in Page->Html property: "/kkkk"
   at Starcounter.Page.AsMimeType(MimeType mimeType, MimeType& resultingMimeType, Request request) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-36\Level1\src\Starcounter\Page.cs:line 54
   at Starcounter.Response.ConstructFromFields(Request req, Byte[] givenBuffer) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-36\Level1\src\Starcounter.Internal\Http\Response.cs:line 800
   at Starcounter.Request.SendResponse(Response resp, Byte[] serializationBuf) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-36\Level1\src\Starcounter.Internal\Http\Request.cs:line 1192
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-36\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 507
ParamName=Can not find file in Page->Html property: "/kkkk"
HResult=-2146233086

More information about this error may be available in the server error log.
```

**Comment by alemoi** [comment]
Fixed via 30f5ace729caa1503c01f6e601ffd9acd650d5c3
Thank you for reporting!
