### ISSUE TITLE
Question: Is it possible to hide the stack trace on an internal error?

### ISSUE THREAD

**Issue by mtornwall** [Starcounter/Starcounter#2959]
The stack trace presented by the server is useful for debugging, but may contain sensitive information that shouldn't be leaked to users. Is there a configuration option that I can set to disable the stack traces in my production environment?

**Comment by dan31** [comment]
Good input, @alemoi WDYT?

**Comment by warpech** [comment]
In other platforms, application exception produces a HTTP 500 status code, which can be handled using an error handler that uses a web template (for `Accept: text/html`) or just a string response (for other types):

RoR: http://wearestac.com/blog/dynamic-error-pages-in-rails
Django: https://docs.djangoproject.com/en/1.8/howto/error-reporting/
Express: http://expressjs.com/guide/error-handling.html
Sinatra: http://hawkins.io/2013/06/error-handling-in-sinatra-apis/
ASP.NET MVC 6: http://weblogs.asp.net/imranbaloch/custom-errors-aspnet5-mvc6

In our case, I guess we would like to use a `Page` response.

The 500 error pages produce different amount of information basing on the error reporting level, which our case should live in the server config (set per database, I suppose).

**Comment by warpech** [comment]
Today this problem arose again in #4034. 

To extend my previous response: All mature web frameworks have such options. In ASP.NET Core and Ruby on Rails you can specify the environment type (production or development)

- https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling
- http://stackoverflow.com/questions/12849597/rails-turn-off-error-display

In few popular PHP frameworks that I've found there are no environment type switches, but you can change error reporting level in config:

- http://stackoverflow.com/questions/10711517/turning-error-reporting-off-php

**Comment by per-samuelsson** [comment]
I vote we try to address this in 2.4. I think it will need some collaboration where @andwah is also involved.

As for the exact nature of the API / customization approach, I'm open for all options @warpech suggested. I think probably the best is to adopt to something like aspnet.core, since in .NET hosting, that's where we are heading and hence it would allow that audience to feel most comfortable.

**Comment by mmnosek** [comment]
> I vote we try to address this in 2.4. I think it will need some collaboration where @andwah is also involved.

Absolutely agree! IMO it might be extremely useful. It should be specified on the database level and be related to option like "Environment type" or "Enviroment". Maybe not only debug/production but more, like debug/testing/production? I can imagine much more features relying on that:
* Showing custom error page, the same for whole database
* Showing custom error message in browser console if PuppetJS error occurred
* Showing custom 404 and access denied page (it's related to Starcounter/authorization library)
* More app-specific features like "if in debug mode, redirect all email notifications to some test address" or "if in debug mode, use real credit card payments API instead of testing" or "if in debug mode, assume that all users has permissions to everything". I used something similar in other software stacks and I find it very useful.

So hiding errors is one thing, but it should be also available in Starcounter API.

**Comment by per-samuelsson** [comment]
To bring this closer to something we can actually implement, can we include some code illustrations of what scenarios we want to address?

If I'm starting this app:

```cs
void Main() {
  Handle.GET("/foo", () => {
    return 404;
  });
}
```

and fetch `http://localhost:8080/foo`, I see this:

![image](https://cloud.githubusercontent.com/assets/2902045/21883320/cc1cea4e-d8ae-11e6-8b4e-e56301d447bb.png)

Instead fetching `http://localhost:8080/foo2`, give me a simple text:

> Error 404: Resource "/foo2" not found.

**Comment by per-samuelsson** [comment]
Instead returning internal error (501) from "/foo" give me this:

![image](https://cloud.githubusercontent.com/assets/2902045/21883577/28410e58-d8b0-11e6-9db3-a12c231a0c64.png)

**Comment by per-samuelsson** [comment]
And complementing with this handler:

```
Handle.GET("/foo3", () => {
  throw new Exception("Thats bad :(");
});
```

give me a page with this (raw text) content:

> System.Exception: Thats bad :(
   at Issue4034.Program.<>c.<Main>b__0_2() in C:\Users\Per\proj\Issue4034\Issue4034\Program.cs:line 19
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\Users\Per\Git\Starcounter\Develop\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\Users\Per\Git\Starcounter\Develop\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\Users\Per\Git\Starcounter\Develop\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 763
HResult=-2146233088

> More information about this error may be available in the server error log.

Is that the main use case we want to address? Being able to customize what to show when any user-defined handler fail with an exception slipping out?

**Comment by per-samuelsson** [comment]
One key concern here is actually where to host code that would customize any kind of response output (like 5xx, 4xx mainly). I've actually been thinking some lately that I think we need a discussion on how to approach things similar to this request and make sure it's future proof, considering all stuff in the pipeline. I'll try to initiate such discussion in parallel.

**Comment by warpech** [comment]
I think that this can also be solved on the middleware level - as presented here: https://github.com/Starcounter/TechComm/issues/256#issuecomment-271857771

**Comment by per-samuelsson** [comment]
> I think that this can also be solved on the middleware level - as presented here: Starcounter/TechComm#256 (comment)

For sure, and frankly, I think that is a more natural approach, but I don't want to just ignore requests to have stuff on database level (as database configuration).

And it's that topic we need a more holistic discussion about before addressing this. Basically, the discussion I want is one that consider those things in the pipe now, and how they will effect the runtime environments of apps. More specifically: self-hosting and system apps. I came to a clear insight that this case highly depend on (and need to slave under) the things going on with that.

Again, let me initiate that discussion and I'm sure it will get clearer, and then we decide on this. Assigned it to me because of that.

**Comment by warpech** [comment]
Ok. Just one more idea - the app that creates this "error page middleware" can be a separate micro app. I think that this would be quite elegant actually.

**Comment by per-samuelsson** [comment]
> Ok. Just one more idea - the app that creates this "error page middleware" can be a separate micro app.

Cool. Certainly something we must consider. Might play really nice with system apps too.

**Comment by per-samuelsson** [comment]
> Again, let me initiate that discussion and I'm sure it will get clearer, and then we decide on this. Assigned it to me because of that.

[Gather holistic perspective of app and host/server relationship](https://github.com/Starcounter/CompanyTrack/issues/289).
