### ISSUE TITLE
System.OverflowException - if SQL query contains too big number

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2988]
```sql
SELECT * 
FROM Starcounter.Metadata.Type
WHERE ObjectNo = 18446744073709551420
```

```
System.OverflowException: Value was either too large or too small for an Int64.
   at System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   at Starcounter.Query.Sql.Creator.IntegerParse(String literal) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-51\Level1\src\Starcounter\Query\SQL\_Creator.cs:line 2356
   at Starcounter.Query.Sql.Creator.CreateIntegerLiteral(Term literalTerm) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-51\Level1\src\Starcounter\Query\SQL\_Creator.cs:line 2369
   at Starcounter.Query.Sql.Creator.CreateLiteral(Term typeTerm, Term nameTerm) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-51\Level1\src\Starcounter\Query\SQL\_Creator.cs:line 2215
   at Starcounter.Query.Sql.Creator.CreateValueExpression(RowTypeBinding rowTypeBind, Term exprTerm, VariableArray varArray) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-51\Level1\src\Starcounter\Query\SQL\_Creator.cs:line 2011
   at Starcounter.Query.Sql.Creator.CreateComparisonNumerical(RowTypeBinding rowTypeBind, Term opTerm, Term exprTerm1, Term exprTerm2, VariableArray varArray) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-51\Level1\src\Starcounter\Query\SQL\_Creator.cs:line 1275
   at Starcounter.Query.Sql.Creator.CreateComparison(RowTypeBinding rowTypeBind, Term typeTerm, Term opTerm, Term exprTerm1, Term exprTerm2, VariableArray varArray) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-51\Level1\src\Starcounter\Query\SQL\_Creator.cs:line 1095
   at Starcounter.Query.Sql.Creator.CreateLogicalExpression(RowTypeBinding rowTypeBind, Term term, VariableArray varArray) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-51\Level1\src\Starcounter\Query\SQL\_Creator.cs:line 1045
   at Starcounter.Query.Sql.Creator.MapTermsToOptimizerInput(RowTypeBinding rowTypeBind, Term nodeTreeTerm, Term whereCondTerm, Term orderbyComparerListTerm, Term fetchTerm, Term hintListTerm, VariableArray varArray, String query) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-51\Level1\src\Starcounter\Query\SQL\_Creator.cs:line 134
   at Starcounter.Query.Sql.Creator.CreateOptimizerInput(RowTypeBinding rowTypeBind, Term term, VariableArray varArray, String query) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-51\Level1\src\Starcounter\Query\SQL\_Creator.cs:line 32
   at Starcounter.Query.QueryPreparation.PrepareOrExecuteQuery[T](String query, Boolean slowSql, Object[] values) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-51\Level1\src\Starcounter\Query\QueryPreparation.cs:line 73
   at Starcounter.Query.Sql.SqlEnumCache.CacheOrExecuteEnumerator[T](String query, Boolean slowSQL, Object[] values) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-51\Level1\src\Starcounter\Query\SQL\_SqlEnumCache.cs:line 127
   at Starcounter.Db.FullQueryProcess[T](String query, Boolean slowSQL, Object[] values) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-51\Level1\src\Starcounter\Mock\Db.cs:line 126
   at Starcounter.Internal.SqlRestHandler.ExecuteQuery(String query) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-51\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\SqlRestHandler.cs:line 95
HResult=-2146233066
```

**Comment by k-rus** [comment]
Thanks for reporting! I will put in my backlog list.

**Comment by miyconst** [comment]
The issue seems to be fixed. Now queries with `1844674407370955161` value executed without errors. Closing the issue.
