### ISSUE TITLE
Invalid exception text when trying to execute wrong SQL query on application start

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2993]
In my application I had a class, which was removed later, but an SQL statement left in `Program.cs` which was executed on application start. 

Trying to start such application results in the following exception, which looks like something internal. The exception should indicate why the application failed to start and show the original exception text.

```
"Starcounter.DbException: ScErrDatabaseEngineTerminated (SCERR10007): The server detected that the user code host executable (sccode.exe) unexpectedly terminated during a management operation. , PID=8644, Database=default
Version: 2.1.260.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10007.
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.<>c__DisplayClass7.<Execute>b__4(CommandTask task) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-267\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 179
   at Starcounter.Server.Commands.CommandProcessor.<>c__DisplayClass1.<WithinTask>b__0(CommandTask t) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-267\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 484
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-267\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 510
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.Execute() in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-267\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 193
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-267\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
ErrorCode=10007
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR10007
---> Starcounter.DbException: ScErrProcessExitCodeNotAvailable (SCERR10040): The exit code of the terminating process was not available.
Version: 2.1.260.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10040.
ErrorCode=10040
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR10040
"
```

**Comment by per-samuelsson** [comment]
> The exception should indicate why the application failed to start and show the original exception text.

Totally agree. I think *has* worked, but your stuff look terrible indeed.

**Comment by per-samuelsson** [comment]
So, @miyconst, can you create just a new isolated application (e.g. `staradmin +`) and copy/paste in this content:

```C#
using Starcounter;
using System;

class Program {
    static void Main() {
        var x = Db.SQL("SELECT f FROM Foo f").First;
    }
}
```

Then run it with `star app.cs`.

When I do, I get:

> [11:40:45, Error, Starcounter.Server.Commands (scadminserver)]
Starcounter.DbException: ScErrFailingEntrypoint (SCERR4259): The user code entrypoint method raised an exception. Failed to process query: SELECT f FROM Foo f: Unknown class Foo.

**Comment by miyconst** [comment]
Well, I just minified my application and can't longer reproduce the error.
Now I see a valid exception for a missing class.

Closing the issue as not reproducible.
