### ISSUE TITLE
Application restart required to see change in static files

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3013]
Recently I have noticed that application restart is required to see changes in static files.

My environment:
Windows 10
Visual Studio 2015 Community
Starcounter DevelopNightlyBuilds-2.1.300

This is very annoying, because application restart takes quite some time, especially on slow machines.

The easiest way to check:

1. Checkout https://github.com/miyconst/Playground.
2. Start the application.
3. Navigate to http://localhost:8080/playground.
4. Open /Playground/wwwroot/Playground/IndexPage.html file and replace `<legend>Text</legend>` with `<legend>Changed text</legend>`.
5. Go back to browser and refresh page.
6. The old text will be displayed.

cc @alemoi

**Comment by warpech** [comment]
Related? https://github.com/Starcounter/Starcounter/issues/2946

**Comment by miyconst** [comment]
Probably related, but have to ask @alemoi.

**Comment by alemoi** [comment]
Maybe something specific with Windows 10. I will take a look at this later.

**Comment by alemoi** [comment]
Linking this issue: https://github.com/Starcounter/Starcounter/issues/2946

**Comment by Starcounter-Jack** [comment]
There is a cache invalidation mechanism based on file system changes. It uses a .NET api. Put a breakpoint in the callback function and see if we recieve notifications when file changes.

**Comment by alemoi** [comment]
> There is a cache invalidation mechanism based on file system changes. It uses a .NET api. Put a breakpoint in the callback function and see if we recieve notifications when file changes.

Yes, and it suppose to work. Maybe some differences with how Win10 works.

**Comment by alemoi** [comment]
@warpech I tried this in the same environment in Virtual Box as yours and it worked fine. Is it occasional behavior or you can constantly reproduce on your machine? Can I check on your machine tomorrow?

**Comment by alemoi** [comment]
After investigation we found that its again an issue with Parallells and their network folders sharing (PSF). I have added now a check when resource directory is registered: in case if its a network folder or on network drive - the exception is thrown. Pretty much like in installer regarding server directory. @miyconst is going to test this solution and then I will push the changes.

**Comment by miyconst** [comment]
Seems to work right.

Trying to start an app from a network drive end with the following exception:

```
"ScErrServerCommandFailed (SCERR10011): The operation ""Starting Launcher in default"" failed.
Version: 2.1.370.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10011."
```

Starcounter logs have more details:

```
"System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: You are trying to use a resource directory that is on network drive (file modifications are not observable on network drives): Z:\Documents\GitHub\Samples\Launcher\src\Launcher\wwwroot
   at Starcounter.Internal.AppsBootstrapper.InternalAddStaticFileDirectory(UInt16 port, String webResourcesDir, String appName) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-350\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 220
   at Starcounter.Internal.AppsBootstrapper.Bootstrap(UInt16 port, String webResourcesDir, String appName) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-350\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 429
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-350\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 250
   at Starcounter.Hosting.Package.Process() in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-350\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 143
   at Starcounter.Hosting.Package.Process(IntPtr hPackage) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-350\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 56
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-350\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 71
ParamName=You are trying to use a resource directory that is on network drive (file modifications are not observable on network drives): Z:\Documents\GitHub\Samples\Launcher\src\Launcher\wwwroot
HResult=-2146233086
"
```

**Comment by alemoi** [comment]
Thank you for testing! I will fix so that Starcounter specific error is returned instead of out of range exception.

**Comment by miyconst** [comment]
Would be also cool if all of such exception would be visible and not require digging into log entries.
Another very common error is when working directory is pointing to a wrong folder.

**Comment by alemoi** [comment]
I agree. @andwah how is it possible to display the message in tray icon? Do you have some REST API for that. I mean that we log an error and displaying notification in tray icon.

> Another very common error is when working directory is pointing to a wrong folder.

For example, if a folder does not exist or you provide a file path instead of folder?

**Comment by andwah** [comment]
@alemoi We have an Rest api for getting the log, the tricky part will be filtering out the right log entry to show in the try.

**Comment by miyconst** [comment]
@alemoi

Most of the time it happens when project was moved, renamed, or one of the parents folder got renamed. So, it happens when working directory path points to a non existing folder.

**Comment by alemoi** [comment]
Very reasonable. I will add this check as well!

**Comment by alemoi** [comment]
Unfortunately is not that simple after I did some tests: for example, adding a shared network directory as resources directory works fine, and this functionality seems to be very useful. Probably its some border case with Parallels shared folder.

**Comment by miyconst** [comment]
@alemoi, didn't @per-samuelsson suggested to stop working at 2am :laughing:?

**Comment by alemoi** [comment]
Hahah :smiley_cat: No comments!
In any case I added only a check for existence of directory for now via c4dc1a5c363ec60bde19213e9d88d06396b1edd0
I will add documentation regarding Parallels case specifically.

**Comment by miyconst** [comment]
Sounds good. Close the issue when done.

**Comment by miyconst** [comment]
@alemoi, this is done, am I right?

**Comment by alemoi** [comment]
This is the current state: network directories work fine in general. Its only the case with Parallels, and maybe some other software.

> Unfortunately is not that simple after I did some tests: for example, adding a shared network directory as resources directory works fine, and this functionality seems to be very useful. Probably its some border case with Parallels shared folder.

**Comment by miyconst** [comment]
I tested Starcounter with a Network path and it failed to start an app as desired. Closing the issue.

**Comment by alemoi** [comment]
>  it failed to start an app as desired

Can you provide the details please?

**Comment by miyconst** [comment]
Hm, just checked with the latest nightly build, and the app started from a network drive, and the changes in static files are not reflected unless restarted.

**Comment by miyconst** [comment]
I remember I tested it a while ago, and apps failed to start from a network drive.

**Comment by miyconst** [comment]
@alemoi anything with this issue?

**Comment by alemoi** [comment]
Its simple: network drives worked for me fine, including changes pick up. The issue only was when using parallels, thats why the issue is suspended.

**Comment by alemoi** [comment]
Is it the case for you as well that network drives are working but not Parallels?

**Comment by miyconst** [comment]
I didn't test with the network drives, but it for sure does not work from Parallels.

**Comment by alemoi** [comment]
That's true and it surprisingly works for normal network drives. There are issues regarding Parallels on the net - I will find.

**Comment by dan31** [comment]
@miyconst @alemoi I thought that generally Starcounter doesn't work well from network drive as many other native apps by default. (There are many reasons why it might be so, as one developing in Visual Studio I remember that it isn't a friend with network drives either). @miyconst do you experience the opposite and Starcounter worked fine for you from network drive except this issue? Also @k-rus can tell you more on his experience with running Starcounter in Parallels involving network drives, once he has time.

**Comment by dan31** [comment]
However, similar is noticeable presumably on non-network drives. See:
https://github.com/Starcounter/Starcounter/issues/2946
https://github.com/Starcounter/Starcounter/issues/1166

**Comment by k-rus** [comment]
> Also @k-rus can tell you more on his experience with running Starcounter in Parallels involving network drives, once he has time.

The installer prevents to use network drive for the database. Network drive, which shares Mac folders into Parallels VM, is extremely slow. I tried to use to our repos and have to stop.

**Comment by miyconst** [comment]
>@miyconst do you experience the opposite and Starcounter worked fine for you from network drive except this issue?

It worked fine for me except not able to put database files on a network drive and this issue.
