### ISSUE TITLE
Nightly builds failing

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3023]
The last available for download nightly build is `2.1.324 (Oct 30, 2015 9:52:22 AM)`, and today is November 3.

cc @alemoi

**Comment by alemoi** [comment]
Thank you for letting us know! The builds are successful on build server. I guess something happens on download server, cc @andwah

**Comment by alemoi** [comment]
Most probably related to recent switch to VS 2015.

**Comment by andwah** [comment]
Some snippets from the build log from the build/download server

```
Starting tool: 'Starting Starcounter unique version builder...'
Starting generating unique setup EXE...
Replacing unique build information in sources, license, etc...
Building empty managed setup EXE...
Building unique Starcounter.Tracking DLL...
Build utility exception:
10/30/2015 8:58:19 AM (d:\versions\source\Starcounter\DevelopNightlyBuilds\2.1.324\GenerateInstaller.exe): System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at GenerateInstaller.GenerateInstaller.BuildMsbuildProject(String pathToProject, String configuration, String platform, String extraArguments) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-60\BuildSystem\src\GenerateInstaller\GenerateInstaller.cs:line 226
   at GenerateInstaller.GenerateInstaller.GenerateUniqueBuild(String uniqueDownloadKey, String destinationDir, String pathToCertificateFile) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-60\BuildSystem\src\GenerateInstaller\GenerateInstaller.cs:line 100
   at GenerateInstaller.GenerateInstaller.Main(String[] args) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-60\BuildSystem\src\GenerateInstaller\GenerateInstaller.cs:line 264


2015-10-30 08:58:22 ERROR: Failed to build, error code 123 (retry 0).
```

**Another one**:
```

Successfully signed files...
Building final native installer wrapper...
Microsoft (R) Build Engine version 14.0.23107.0
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 10/31/2015 4:02:59 AM.
     1>Project "d:\versions\source\Starcounter\DevelopNightlyBuilds\2.1.330\Level1\src\Starcounter.Installer\Starcounter.InstallerNativeWrapper\Starcounter.InstallerNativeWrapper.vcxproj" on node 1 (Build target(s)).
     1>PrepareForBuild:
         Creating directory "Release\".
     1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid version number. [d:\versions\source\Starcounter\DevelopNightlyBuilds\2.1.330\Level1\src\Starcounter.Installer\Starcounter.InstallerNativeWrapper\Starcounter.InstallerNativeWrapper.vcxproj]
         Creating directory "Release\Starcoun.65E33B74.tlog\".
       InitializeBuildStatus:
         Creating "Release\Starcoun.65E33B74.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
       ClCompile:
         CL.exe /c /Zi /nologo /W3 /WX /O2 /Oi /Oy- /GL /D WIN32 /D NDEBUG /D _CONSOLE /D _UNICODE /D UNICODE /Gm- /EHsc /MT /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Release\\" /Fd"Release\vc140.pdb" /Gd /TP /analyze- /errorReport:queue Starcounter.InstallerNativeWrapper.cpp
     1>TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [d:\versions\source\Starcounter\DevelopNightlyBuilds\2.1.330\Level1\src\Starcounter.Installer\Starcounter.InstallerNativeWrapper\Starcounter.InstallerNativeWrapper.vcxproj]
         
         
     1>Done Building Project "d:\versions\source\Starcounter\DevelopNightlyBuilds\2.1.330\Level1\src\Starcounter.Installer\Starcounter.InstallerNativeWrapper\Starcounter.InstallerNativeWrapper.vcxproj" (Build target(s)) -- FAILED.

Build FAILED.

       "d:\versions\source\Starcounter\DevelopNightlyBuilds\2.1.330\Level1\src\Starcounter.Installer\Starcounter.InstallerNativeWrapper\Starcounter.InstallerNativeWrapper.vcxproj" (Build target) (1) ->
       (PrepareForBuild target) -> 
         C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid version number. [d:\versions\source\Starcounter\DevelopNightlyBuilds\2.1.330\Level1\src\Starcounter.Installer\Starcounter.InstallerNativeWrapper\Starcounter.InstallerNativeWrapper.vcxproj]


       "d:\versions\source\Starcounter\DevelopNightlyBuilds\2.1.330\Level1\src\Starcounter.Installer\Starcounter.InstallerNativeWrapper\Starcounter.InstallerNativeWrapper.vcxproj" (Build target) (1) ->
       (ClCompile target) -> 
         TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [d:\versions\source\Starcounter\DevelopNightlyBuilds\2.1.330\Level1\src\Starcounter.Installer\Starcounter.InstallerNativeWrapper\Starcounter.InstallerNativeWrapper.vcxproj]

    1 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.34
Build utility exception:
10/31/2015 4:02:59 AM (d:\versions\source\Starcounter\DevelopNightlyBuilds\2.1.330\GenerateInstaller.exe): System.Exception: Building Level1\src\Starcounter.Installer\Starcounter.InstallerNativeWrapper\Starcounter.InstallerNativeWrapper.vcxproj project failed with error code: 1
   at GenerateInstaller.GenerateInstaller.BuildMsbuildProject(String pathToProject, String configuration, String platform, String extraArguments) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-61\BuildSystem\src\GenerateInstaller\GenerateInstaller.cs:line 231
   at GenerateInstaller.GenerateInstaller.GenerateUniqueBuild(String uniqueDownloadKey, String destinationDir, String pathToCertificateFile) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-61\BuildSystem\src\GenerateInstaller\GenerateInstaller.cs:line 172
   at GenerateInstaller.GenerateInstaller.Main(String[] args) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-61\BuildSystem\src\GenerateInstaller\GenerateInstaller.cs:line 264
```

**Comment by alemoi** [comment]
Installer now needs VS 2015 to be build and I guess there ia no VS 2015 installed on download server. Please correct me if im wrong @andwah I will check meanwhile how native installer is built.

**Comment by andwah** [comment]
```Microsoft Visual Studio Community 2015``` was installed on the server at ```2015-10-30```

**Comment by alemoi** [comment]
> Microsoft Visual Studio Community 2015 was installed on the server at 2015-10-30

Is it installed with C++ support as described here? Seems its not. https://github.com/Starcounter/Starcounter/issues/2981#issuecomment-151836580

Since the build servers are building the installation package fine.

**Comment by alemoi** [comment]
Yes, the problem is that VC++ and other tools are not installed on the download server. However I can't install them, because of the following situation:

![image](https://cloud.githubusercontent.com/assets/208134/10922050/54f1dff6-8279-11e5-9d1d-8db50eac0050.png)

**Comment by per-samuelsson** [comment]
> However I can't install them, because of the following situation:

Whatt? Just do your usual magic?! :tophat:

**Comment by alemoi** [comment]
> Whatt? Just do your usual magic?! :tophat:
Sure :) Just need to clean this C:\Windows\Winsxs directory,

**Comment by dan31** [comment]
Guys, I move pagefile to D:, give it a sec to restart.

**Comment by dan31** [comment]
> Just need to clean this C:\Windows\Winsxs directory

I think if you literally clean it, windows will no longer work :100:

**Comment by alemoi** [comment]
No, I was talking about this: https://technet.microsoft.com/en-us/library/dn251565.aspx

But then provocative question, @dan31 why do we have so little space on our main download server? :)

**Comment by alemoi** [comment]
I guess because the price for Amazon hosting jumps up significantly with more space?

**Comment by dan31** [comment]
Provocative answer @alemoi, go check and see, it is 8 Gb now :grin:
But really, 30 gb for main drive is a given default. However the D: disk is 200 gb.

**Comment by alemoi** [comment]
Thanks @dan31 
Now I updated VS 2015 with native packages, so the build should succeed tonight. Let's observe this.

**Comment by alemoi** [comment]
Nightly was published fine tonight, so closing the issue.

**Comment by miyconst** [comment]
Nightly builds are missing again, the last one was on `Nov 26`.

**Comment by alemoi** [comment]
That's probably because some tests needed to be added to longtests.txt. I will take a look soon!

**Comment by alemoi** [comment]
This was the case. Some tests took longer time to complete and were not in longtests.txt. Now everything should work fine again.

**Comment by miyconst** [comment]
No nightly builds again, the latest one `2.1.1605 (Apr 3, 2016 3:12:53 PM)`.

**Comment by chrhol** [comment]
Bump. Been quite some time now when we had a nightly that succeeded.

**Comment by alemoi** [comment]
Yes. The reasons are now identified, strange changes in environment and locking files after one test. I'm running now new pnext nightly. And later will start develop nightly. Both only without LaL test. So today we have both nightlies.

**Comment by miyconst** [comment]
Closing the issue as too old.
