### ISSUE TITLE
pnext: scdata started by server exit with error "bad arguments"

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3044]
Get this when trying to start a (new) database when working on #3029.

```
[08:56:58, Error, Starcounter.Server.Commands (scadminserver)]
Starcounter.DbException: ScErrDbProcTerminated (SCERR10028): The server detected that the database data process unexpectedly terminated during a management operation. scdata.exe, PID=8708, Database=default, Exitcode=1001
Version: 2.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10028.
   at Starcounter.Server.DatabaseEngine.StartDatabaseProcess(Database database) in C:\Users\Per\Git\Starcounter\Develop\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseEngine.cs:line 183
   at Starcounter.Server.Commands.Processors.StartDatabaseCommandProcessor.<>c__DisplayClass2_0.<Execute>b__0(CommandTask task) in C:\Users\Per\Git\Starcounter\Develop\Level1\src\Server\Starcounter.Server\Commands\Processors\StartDatabaseCommandProcessor.cs:line 54
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) in C:\Users\Per\Git\Starcounter\Develop\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 510
   at Starcounter.Server.Commands.Processors.StartDatabaseCommandProcessor.Execute() in C:\Users\Per\Git\Starcounter\Develop\Level1\src\Server\Starcounter.Server\Commands\Processors\StartDatabaseCommandProcessor.cs:line 43
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\Users\Per\Git\Starcounter\Develop\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 298
ErrorCode=10028
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR10028
---> System.ArgumentException: ScErrBadArguments (SCERR1001): One or more arguments was invalid.
Version: 2.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR1001.
HResult=-2147024809
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR1001
```

I'm running Bluestar pnext + Level1 pnext (latest, merged into pnextmerge2728 branch).

Guess its something done in the native parts that haven't been fixed in the admin server? I think I'll try finding the error myself, since I'm not really up for waiting at this point.

**Comment by per-samuelsson** [comment]
> Guess its something done in the native parts that haven't been fixed in the admin server?

Just found out myself: yes, thats it, considering [company track #126](https://github.com/Starcounter/CompanyTrack/issues/126). So I guess I should start doing that one, because completing #3029 will be rather hard wihout even being able to start the database. :smile:

**Comment by per-samuelsson** [comment]
> So I guess I should start doing that one, because completing #3029 will be rather hard wihout even being able to start the database.

Seems not after all. Got a confirmation from @k-rus that at the moment, management stuff is broken, and the only way to run a database is a sequence of manually starting processes; `star.exe` is not operative at this moment.

I'll just adapt to that and try to get #3029 going with such a setup.

**Comment by k-rus** [comment]
Currently, pnext uses low level API to run tests and does not use admin server. There are broken changes described in another issue.

**Comment by per-samuelsson** [comment]
Closing this, because its a known issue then (we'll need to rewrite management parts to adapt to [company track #126](https://github.com/Starcounter/CompanyTrack/issues/126).
