### ISSUE TITLE
Cant start application

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3080]
Hi!

I've had an application up and running. But now I can't get it to launch again. I've tried

    staradmin kill all

Then restarted my app with star.exe

But I just keep getting:

```
System.Net.WebException: The remote server returned an error: (404) Not Found.
   at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-81\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 113
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-81\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 67
HResult=-2146233079


Starcounter.DbException: ScErrDatabaseEngineTerminated (SCERR10007): The server detected that the user code host executable (sccode.exe) unexpectedly terminated during a management operation. , PID=8716, Database=default
Version: 2.1.469.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10007.
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.<>c__DisplayClass4_0.<Execute>b__3(CommandTask task) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-81\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 180
   at Starcounter.Server.Commands.CommandProcessor.<>c__DisplayClass68_0.<WithinTask>b__0(CommandTask t) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-81\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 484
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-81\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 510
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.Execute() in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-81\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 194
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-81\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
ErrorCode=10007
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR10007
---> Starcounter.DbException: ScErrProcessExitCodeNotAvailable (SCERR10040): The exit code of the terminating process was not available.
Version: 2.1.469.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10040.
ErrorCode=10040
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR10040
```

**Comment by careri** [comment]
My bad, uncaught exception in an attached thread
