### ISSUE TITLE
Weaver exception

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3115]
One of our machines throws this exception when trying to run an application.

The same code works good on other machines.

@per-samuelsson if you have any clue what can cause it, tell me please. If no, then I just close the issue as it looks to be a machine issue.

```
ScErrServerCommandFailed (SCERR10011): The operation "Starting TEOMixPanel in default" failed.
Version: 2.1.177.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10011.
```
```
System.Exception: ScErrWeavingError (SCERR2030): At least one error has been detected during weaving of the application code. Process exit code: 1
Version: 2.1.177.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR2030.
   at Starcounter.Server.WeaverService.LogAndRaiseExceptionFromFailingWeaver(ToolInvocationException e) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 198
   at Starcounter.Server.WeaverService.Weave(String givenAssembly, String runtimeDirectory, Boolean disableEditionLibraries) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 121
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.<>c__DisplayClass7.<Execute>b__3(CommandTask task) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 99
   at Starcounter.Server.Commands.CommandProcessor.<>c__DisplayClass1.<WithinTask>b__0(CommandTask t) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 484
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 514
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.Execute() in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 108
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR2030
```
```
ScErrWeavingError (SCERR2030): At least one error has been detected during weaving of the application code. Process exit code: 1.
Arguments=--maxerrors=1 --ErrorParcelId=A4A7D6FA-EB34-442A-B579-DBB1DBB859E3 Weave "E:\Projects\TEO_Starcounter\Src-Dev\TEO.MixPanel\bin\Debug\TEOMixPanel.exe" --outdir="C:\Users\adhingra.TEO\Documents\Starcounter\Personal\Temp\Default\Default-20151125T160527928\weaver\640282CE0D47E37E1C3A00FCE3A0E261EAEA2262"
Output:

Version: 2.1.177.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR2030.

```

**Comment by miyconst** [comment]
Not sure it was the reason, but during investigation we discovered that VS key has expired. The issue has gone after applying new key.

**Comment by per-samuelsson** [comment]
> Not sure it was the reason, but during investigation we discovered that VS key has expired. The issue has gone after applying new key.

@miyconst, happy you got pass it, but seems unlikely it was the cause. Bit strange. But yeah, it *could* be that, something that when the weaved assembly are to be rebuilt, it fails b/c invalid license. Never seen that before though.

If you want me to investigate it, can you take a lock in the logs, see if there's something there? From th above, I can only see that the weaver fails, not why.

**Comment by miyconst** [comment]
No need to waste time on this, thank you. If it will appear again, then I will try to gather some more information.
