### ISSUE TITLE
pnext indexquery test fails with transaction 

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#3124]
Just so we can track current issues with pnext tests separately.

Here is the issue stack trace:
```
[11:47:00]7EDE1D87-8181-4B1C-B1DF-CB939706F8CF--FC8F607939BC-FD1B-C1B4-1818-78D1EDE7ScErrConstraintViolationAbort (SCERR8001): A transaction was aborted because a constraint was violated.
[11:47:00]Version: 2.3.47.
[11:47:00]Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR8001.
[11:47:00]   at IndexQueryTest.IndexQueryTests.CreateIndexUserLN() in C:\BuildAgent\work\sc-2.0.1037\Level1\src\Samples\IndexQueryTest\TestsWithSchema.cs:line 52
[11:47:00]   at IndexQueryTest.IndexQueryTests.TestCreateIndexWithoutQuery() in C:\BuildAgent\work\sc-2.0.1037\Level1\src\Samples\IndexQueryTest\TestsWithSchema.cs:line 137
[11:47:00]   at IndexQueryTest.IndexQueryTests.Main(String[] args) in C:\BuildAgent\work\sc-2.0.1037\Level1\src\Samples\IndexQueryTest\Program.cs:line 20
```
in https://scbuildserver/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=32276#_focus=6267

**Comment by bigwad** [comment]
This test tries to issue "CREATE INDEX" sql statement twice in a row to test that second time statement will fail with specific error so customer will know that index already exists.
The problem is that due to latest changes in the kernel (https://github.com/Starcounter/CompanyTrack/issues/120#issuecomment-159921368), kernel's stari_transaction_create_index function doesn't return as error in such case anymore. Metalayer is not adapted for this change and actually tries to create second index and store related information in metatables and finally fails with some unique constraint in meta-tables. @alexanderstc

**Comment by alexanderstc** [comment]
I'm on this.

**Comment by alexanderstc** [comment]
@bigwad please verify #41.

**Comment by bigwad** [comment]
it's ok now
