### ISSUE TITLE
ScErrTransactionClosed

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3130]
Hi!

I'm writing a performance test where I stress a message queue that I'm implementing. 
My first attempt was to use SemaphoreSlim to synchronize the writing. But I wasn't satisified with the performance. 8000 messages took 2sec to write.
So I though that I just handle any TransactionConflicts or ConstraintViolations that occur and try again.

The Ensure/Create-methods in the code below first tries to find a matching instance using the current transaction.
If no match is found I call a for loop that handles conflicts/constraint violations. 
Each itteration creates a new Transaction with merging writes.
If the itteration succeeds the result is returned.
If the itteration fails the transaction is disposed and the exception is caught and we move on to the next attempt.
Once the maximum itterations (100) are reached I return false. I don't throw any exceptions.

I have no sleep between itterations.

I did one mistake that consistently brings down the application, if an exception is thrown on Commit I didn't Dispose the transaction. That yields the exception below.

Sorry to say that the performance is pretty much the same between using the transaction approach and SemaphoreSlim.
Seems like I may need to write a more sophisticated scheduler.

```
private static void PerformanceTest()
{
    var watch = Stopwatch.StartNew();
    s_log.Info("Stressing queue");
    int outerCount = Environment.ProcessorCount;
    int innerCount = 1000;

    Parallel.For(0, outerCount, i =>
    {
        ScdbHelper.RunAttached(() =>
        {
            // Stress one queue
            MQueue queue = null;

            TransHelper.WriteSingle(() =>
            {
                queue = MQueue.Ensure("Carl", "Direct" + i);

                for (int j = 0; j < innerCount; j++)
                {
                    try
                    {
                        MQItem item;

                        if (!queue.TryCreate("Server", "Update", i + "." + j, DateTime.Now, out item))
                        {

                        }
                    }
                    catch (Exception ex)
                    {
                        Debug.WriteLine(ex);
                    }
                }
            });
        });
    });
    s_log.Info("{0} Added in: {1}", outerCount * innerCount, watch.Elapsed);
}
```

The exception
```
Starcounter.DbException: ScErrTransactionClosed (SCERR4260): An operation failed because transaction has been closed.
Version: 2.1.656.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4260.
   at Starcounter.Internal.TransactionManager.Cleanup() in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-106\Level1\src\Starcounter\TransactionManager.cs:line 360
   at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-106\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 117
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-106\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 67
ErrorCode=4260
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4260
```

**Comment by chrhol** [comment]
Are you using `Db.Scope(...)` or `Transaction` directly for this test? Creating alot of longrunning transactions in the same request will be really slow since all created transactions are kept and cleaned up in the end. There is a limited number that are fast to handle, but after that the performance will drop.

The exception should be checked and handled though.

**Comment by careri** [comment]
Im creating long running transaction. I'll look into the Db.Scope. What is the difference between Db.Scope and Db.Transact?

I'm guessing that Db.Transact will create a new transaction?

**Comment by chrhol** [comment]
> Im creating long running transaction. I'll look into the Db.Scope. What is the difference between Db.Scope and Db.Transact?

> I'm guessing that Db.Transact will create a new transaction?

Both creates a new transaction, but the `Db.Scope()` transaction does not check for conflicts and you need to handle commits and rollbacks manually. They are mainly used together with a viewmodel, when the transaction needs to survive between requests.

`Db.Transact` checks for conflicts and have automatic retries in case of conflict (can be turned off though). 

If you create a lot of new transactions using `Db.Scope` in one task they will be a lot slower than using `Db.Transact` since all created `Db.Scopes` are kept and cleaned up in the end of the task.

Transactions are documented starting here: http://starcounter.io/guides/transactions

**Comment by careri** [comment]
Ok. I'll try using Db.Transact for this case. Thanks
