### ISSUE TITLE
Uploading installation failed due to disk space

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#3179]
[Last nightly build](https://scbuildserver/viewLog.html?tab=buildLog&buildTypeId=Starcounter_DevelopNightly&buildId=32612) failed with:
>[05:47:05][Step 1/1] Uploading all-in-one build package to public server...
[05:47:44][Step 1/1] Error in response: System.IO.IOException: There is not enough space on the disk.
[05:47:44][Step 1/1] 
[05:47:44][Step 1/1]    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
[05:47:44][Step 1/1]    at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
[05:47:44][Step 1/1]    at Starcounter.Applications.UsageTrackerApp.API.Versions.Upload.<>c__DisplayClassb.<BootStrap>b__a(Request req, String uploadId) in c:\github\Starcounter\VersionManager\src\Api\Upload.POST.cs:line 63
[05:47:44][Step 1/1]    at lambda_method(Closure , Request , IntPtr , IntPtr )
[05:47:44][Step 1/1]    at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-28\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 266
[05:47:44][Step 1/1]    at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-28\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
[05:47:44][Step 1/1]    at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-28\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 458
[05:47:44][Step 1/1] HResult=-2147024784

**Comment by careri** [comment]
Any progress? Now the newest build is from the 6th December

**Comment by alemoi** [comment]
Attaching this one: https://github.com/Starcounter/Starcounter/issues/3071
@dan31 please prioritize this issue with @andwah

**Comment by andwah** [comment]
i have freed up some space by deleting available version's.

**Comment by warpech** [comment]
Seems fixed now

**Comment by alemoi** [comment]
@andwah temporary fixed the empty space. He will soon properly fix the thing.
