### ISSUE TITLE
pnext: logopt.exe stays hanging in pnext builds, blocking the whitelist cleanup

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#3187]
The new process logopt.exe is not killed by "staradmin kill all" (or some other means) which make it impossible to do white-list cleanup in pnext. Here is an error:

```
2015-12-15 11:42:23 (C:\TeamCity\TeamCity8\buildAgent\work\sc-1176\Level1\bsbin\Release\PostBuildTasks.exe): System.UnauthorizedAccessException: Access to the path 'C:\TeamCity\TeamCity8\buildAgent\work\sc-1176\Level1\Bin\Release\logopt.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at PostBuildTasks.PostBuildTasks.CleanBasedOnWhiteList(String whiteListFilePath, String pathToExclusionLog, String dirToClean) in C:\TeamCity\TeamCity8\buildAgent\work\sc-1176\BuildSystem\src\PostBuildTasks\PostBuildTasks.cs:line 208
   at PostBuildTasks.PostBuildTasks.CleanOutputDirectory(String pathToWhiteListFile, String pathToExclusionLog, String outputDir) in C:\TeamCity\TeamCity8\buildAgent\work\sc-1176\BuildSystem\src\PostBuildTasks\PostBuildTasks.cs:line 95
   at PostBuildTasks.PostBuildTasks.Main(String[] args) in C:\TeamCity\TeamCity8\buildAgent\work\sc-1176\BuildSystem\src\PostBuildTasks\PostBuildTasks.cs:line 264
```

Here is the build:

https://scbuildserver/viewLog.html?buildId=32706&buildTypeId=Starcounter_PnextDailyWindows&tab=buildLog

**Comment by chrhol** [comment]
I can take a look at this. Would be nice to have it running properly.

**Comment by bigwad** [comment]
@eriohl, I'm going to fix it by creating a job object for logopt. And I don't see the code to cleanup orphaned temporary files - will fix this as well.
Any objections?

**Comment by bigwad** [comment]
Will create a job object for scdblog, thus logopt will belong to it automatically.

**Comment by bigwad** [comment]
Oh, wait. We don't want scdblog to die immediately once scdata had died. scdblog should flush data and dies after then. Right? So, back to original idea and make job object for logopt only.

**Comment by bigwad** [comment]
Fixed. logopt now is automatically terminated once scdblog dies.
As to orphaned temporary files - I'll create new issue for this.
