### ISSUE TITLE
Important: The transaction was aborted because of a failure to allocate file storage space.

### ISSUE THREAD

**Issue by Ripipip** [Starcounter/Starcounter#3222]
Our starcounter apps are suddenly no longer starting and I get the error below.

I can see no lack of space (over 60GB left on hard drive) nor are we close at reaching full usage of memory.  

Starcounter.TransactionAbortedException: ScErrOutOfFileStorageAbort (SCERR8010): The transaction was aborted because of a failure to allocate file storage space.
Version: 2.0.3226.3.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR8010.
   at Starcounter.Internal.TransactionManager.Commit(Int32 tran_locked_on_thread, Int32 detach_and_free) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3226.3\Level1\src\Starcounter\TransactionManager.cs:line 699
   at Starcounter.Db.Transact(Action action, UInt32 flags, Boolean forceSnapshot, Int32 maxRetries) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3226.3\Level1\src\Starcounter\Db.cs:line 203
   at EncryptedAudience.Database.Browser.FromRequest(Request r) in c:\EncryptedAudience\StarcounterApplication1\Database\Browser.cs:line 20
   at EncryptedAudience.Database.Pixel.GetEncryptedStringFromRequest(String requestString, Request r) in c:\EncryptedAudience\StarcounterApplication1\Database\Pixel.cs:line 83
   at EncryptedAudience.Tracking.Tracking.<Register>b__3(String trackerString, Request r) in c:\EncryptedAudience\StarcounterApplication1\Tracking\Tracking.cs:line 15
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3226.3\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 266
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3226.3\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 97
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3226.3\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 349
ErrorCode=8010
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR8010

More information about this error may be available in the server error log.

**Comment by chrhol** [comment]
I've been in contact with @Ripipip and they solved it (temporarily) by using a backup which contained all important data, so now they can run the apps again, which means we have some time to figure out why this happened.

I will receive a copy of the failing database later.

**Comment by dan31** [comment]
Any news on this one?

**Comment by eriohl** [comment]
Starcounter allocates a fixed size file based on the size of the memory of the machine. Generally you should not be able to run out of this space unless you moved the database to a machine with more memory without recreating the database image (although in theory file fragmentation along with swapping could cause this error as well).

This issue has been addressed in next version of Starcounter (where the image file has been dropped.)
