### ISSUE TITLE
System.MissingFieldException: Field not found: 'Starcounter.Handle.ResolveStaticResource'

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3236]
Opening a non existing playground results in the following exception:

```
System.MissingFieldException: Field not found: 'Starcounter.Handle.ResolveStaticResource'.
   at PlaygroundHost.Program.<Main>b__3(String uri, Request req)
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-77\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 260
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-77\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-77\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 473
HResult=-2146233071

More information about this error may be available in the server error log.
```

**Comment by miyconst** [comment]
Solved by upgrading the machine with the latest nightly build.
