### ISSUE TITLE
Non-informative ArgumentOutOfRangeException when deriving Page and not assigning "Html"

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3252]
Relate to #3251, #3200, #3202.

Having this JSON:

```json
{
  "Name":  "value"
}
```

with this code-behind

```cs
partial class Test : Page {}
```

and returning it like

```cs
Handle.GET("/test", () => {
  return new Test();
});
```

gives me this

```
System.ArgumentOutOfRangeException: Self should be called with URI starting with a slash.
   at Starcounter.Self.DoSelfNodeCall(UInt16 portNumber, String method, String relativeUri, Dictionary`2 headersDictionary, String body, Byte[] bodyBytes, HandlerOptions handlerOptions, Request req) in C:\Users\Per\Git\Starcounter\Develop\Level1\src\Starcounter.Internal\Rest\Self.cs:line 339
   at Starcounter.Self.GET(UInt16 port, String uri, Dictionary`2 headersDictionary, HandlerOptions ho) in C:\Users\Per\Git\Starcounter\Develop\Level1\src\Starcounter.Internal\Rest\Self.cs:line 133
   at Starcounter.Self.GET(String uri, Dictionary`2 headersDictionary, HandlerOptions ho) in C:\Users\Per\Git\Starcounter\Develop\Level1\src\Starcounter.Internal\Rest\Self.cs:line 117
   at Starcounter.Self.GET[T](String uri, HandlerOptions ho) in C:\Users\Per\Git\Starcounter\Develop\Level1\src\Starcounter.Internal\Rest\Self.cs:line 22
   at Starcounter.Page.AsMimeType(MimeType mimeType, MimeType& resultingMimeType, Request request) in C:\Users\Per\Git\Starcounter\Develop\Level1\src\Starcounter\Page.cs:line 50
   at Starcounter.Response.ConstructFromFields(Request req, Byte[] givenBuffer) in C:\Users\Per\Git\Starcounter\Develop\Level1\src\Starcounter.Internal\Http\Response.cs:line 848
   at Starcounter.Request.SendResponse(Response resp, Byte[] serializationBuf) in C:\Users\Per\Git\Starcounter\Develop\Level1\src\Starcounter.Internal\Http\Request.cs:line 1243
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\Users\Per\Git\Starcounter\Develop\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 595
ParamName=
HResult=-2146233086

More information about this error may be available in the server error log.
```

The reason is I haven't assigned the "magic" `Html` property.

We are about to remove `Page`. But I wanted to highlight this anyway, making sure we provide a better experience even when we register a middleware that instruct the MIME type converter to consume some special property. The error must be clear, telling the user what is wrong.

**Comment by warpech** [comment]
Fixing this would improve developer UX a lot. Almost every new developer that talks to me has experienced this problem and did not know what to do because of the vague error message.

This issue is reproducible both with `Page` and with `HtmlFromJsonProvider` middleware.

The smallest app that reproduces it (with middleware): https://github.com/warpech/SimplePuppet/compare/Starcounter_issue_3252

Steps to reproduce:

1. Start the project 
2. Load `http://localhost:8080/simple` in your browser.

**Comment by dan31** [comment]
I had a couple of coding sessions with our partners just recently, as a feedback I confirm that the error messages received (not specifically this one) are pretty difficult to use purposefully. I was impressed how people learned to find out and resolve problems in code only using the error message pretty much like Yes/No indicator (there is some unknown problem, or there is no problem). However, it is difficult to reason how exactly we shall approach this topic. Probably @per-samuelsson has ideas?

**Comment by per-samuelsson** [comment]
> Probably @per-samuelsson has ideas?

Well, I can think of two things only:

Either we create the best error message we can, and have the exception occur on the server, with that error message (producing a page with a stack trace on the client). 

Or we define some fallback strategy - we catch that specific error and return some default web page that describes the problem.

Maybe @warpech can give his opinion on what would be most reasonable / expected?

**Comment by warpech** [comment]
I think that the correct messages would be: 

1. `Html property is not defined. HtmlFromJsonProvider expects a Html property defined in Json, which holds a URI to a HTML template`
2. `Html property is empty. HtmlFromJsonProvider expects a Html property defined in Json, which holds a URI to a HTML template`

**Comment by miyconst** [comment]
There should also be a proper message when a wrong value is provided for the `Html` property.

The message should not only include the wrong value of the property, but also list of all paths where file was looked for.
