### ISSUE TITLE
pnext: missing index for Starcounter.Metadata.DataType

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Starcounter#3253]
The exception below is thrown when executing the following query in the administrator

`SELECT * FROM Starcounter.Metadata.DataType`

Exception:
```
System.Exception: ScErrSqlInternalError (SCERR7000): Unexpected internal error in SQL module. There is no index for type: Starcounter.Metadata.DataType
Version: 2.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR7000.
   at Starcounter.Query.Optimization.ExtentNode.CreateExecutionEnumerator(INumericalExpression fetchNumExpr, INumericalExpression fetchOffsetExpr, IBinaryExpression fetchOffsetKeyExpr, Boolean topNode, Byte& nodeId) in d:\code\Starcounter\Pnext\Level1\src\Starcounter\Query\Optimization\_ExtentNode.cs:line 528
   at Starcounter.Query.Optimization.OptimizationTree.CreateExecutionEnumerator(INumericalExpression fetchNumExpr, INumericalExpression fetchOffsetExpr, IBinaryExpression fetchOffsetKeyExpr) in d:\code\Starcounter\Pnext\Level1\src\Starcounter\Query\Optimization\_OptimizationTree.cs:line 197
   at Starcounter.Query.Optimization.Optimizer.Optimize(OptimizerInput args) in d:\code\Starcounter\Pnext\Level1\src\Starcounter\Query\Optimization\_Optimizer.cs:line 60
   at Starcounter.Query.QueryPreparation.PrepareOrExecuteQuery[T](String query, Boolean slowSql, Object[] values) in d:\code\Starcounter\Pnext\Level1\src\Starcounter\Query\QueryPreparation.cs:line 77
   at Starcounter.Query.Sql.SqlEnumCache.CacheOrExecuteEnumerator[T](String query, Boolean slowSQL, Object[] values) in d:\code\Starcounter\Pnext\Level1\src\Starcounter\Query\SQL\_SqlEnumCache.cs:line 127
   at Starcounter.Db.FullQueryProcess[T](String query, Boolean slowSQL, Object[] values) in d:\code\Starcounter\Pnext\Level1\src\Starcounter\Mock\Db.cs:line 130
   at Starcounter.Db.SlowSQL[T](String query, Object[] values) in d:\code\Starcounter\Pnext\Level1\src\Starcounter\Mock\Db.cs:line 115
   at Starcounter.Db.SlowSQL(String query, Object[] values) in d:\code\Starcounter\Pnext\Level1\src\Starcounter\Mock\Db.cs:line 104
   at Starcounter.Internal.SqlRestHandler.ExecuteQuery(String query) in d:\code\Starcounter\Pnext\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\SqlRestHandler.cs:line 93
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR7000
```

Other queries on metadata tables works (have not tried all though)

**Comment by k-rus** [comment]
Why do you try to select from `DataType`? There is no index defined for it. I wonder if there is use case to query it?
This will work as soon the global index is in place. The work is on-going and will be merged into pnext.

**Comment by chrhol** [comment]
> Why do you try to select from DataType?

Since there are very little documentation on how to use metadata, mostly when I need to do something it's trial and error. I found the best way for me is to select all values in the administrator and try to find what I need. I don't use it in code, there I have it as reference from `Column`.

> This will work as soon the global index is in place. The work is on-going and will be merged into pnext.

Then it will be solved by that.

**Comment by chrhol** [comment]
> I wonder if there is use case to query it?

About this, I guess not really. You probably never query datatype directly except for just curiosity.

**Comment by dan31** [comment]
@k-rus what's your suggestion on documenting the metadata tables? I remember we've had a documentation for it internally with a nice picture for more than a year. Maybe it is a time to publish it. What do you think?

**Comment by k-rus** [comment]
> @k-rus what's your suggestion on documenting the metadata tables? I remember we've had a documentation for it internally with a nice picture for more than a year. Maybe it is a time to publish it. What do you think?

There is an issue to document meta-data.

Existing graphs are out dated. More changes in meta-schema will be done. It would be nice to generate graph based on `metaschema.json`, which contains the actual state.

**Comment by chrhol** [comment]
I think this issue can be closed. A fix for this will be available when the global index is in place.
