### ISSUE TITLE
Error message for bound IEnumerable on Json

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3304]
Hi!

If a bound property returns null instead of a valid IEnumerable you get a crypthic error message. By compiling my own version of the code I managed to figure out that I returned null. 

But a better error message would be nice

> System.NullReferenceException: Object reference not set to an instance of an object.
   at Starcounter.Json.CheckBoundArray(IEnumerable boundValue) in d:\external-source\Starcounter\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 378
   at Starcounter.Json.Refresh(Template property) in d:\external-source\Starcounter\src\Starcounter.XSON\Class Json\Json.cs:line 300
   at Starcounter.Json.InitBoundArrays(TValue template) in d:\external-source\Starcounter\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 148
   at Starcounter.Json.InternalSetData(Object data, TValue template, Boolean readOperation) in d:\external-source\Starcounter\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 98
   at Starcounter.Json.<set_Data>b__a(Json j, Object v) in d:\external-source\Starcounter\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 47
   at Starcounter.Internal.TransactionManager.Scope[T1,T2](TransactionHandle handle, Action`2 action, T1 arg1, T2 arg2) in C:\BuildAgent\work\sc-develop-nightly-167\Level1\src\Starcounter\TransactionManager.cs:line 471
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2](Json json, Action`2 action, T1 arg1, T2 arg2) in d:\external-source\Starcounter\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 77
   at Starcounter.Json.set_Data(Object value) in d:\external-source\Starcounter\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 38
   at Starcounter.Json.CheckBoundArray(IEnumerable boundValue) in d:\external-source\Starcounter\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 383
   at Starcounter.Json.Refresh(Template property) in d:\external-source\Starcounter\src\Starcounter.XSON\Class Json\Json.cs:line 300
   at Starcounter.Json.InitBoundArrays(TValue template) in d:\external-source\Starcounter\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 148
   at Starcounter.Json.InternalSetData(Object data, TValue template, Boolean readOperation) in d:\external-source\Starcounter\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 98
   at Starcounter.Json.<set_Data>b__a(Json j, Object v) in d:\external-source\Starcounter\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 47
   at Starcounter.Internal.TransactionManager.Scope[T1,T2](TransactionHandle handle, Action`2 action, T1 arg1, T2 arg2) in C:\BuildAgent\work\sc-develop-nightly-167\Level1\src\Starcounter\TransactionManager.cs:line 471
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2](Json json, Action`2 action, T1 arg1, T2 arg2) in d:\external-source\Starcounter\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 77
   at Starcounter.Json.set_Data(Object value) in d:\external-source\Starcounter\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 38
   at Starcounter.Json.CheckBoundArray(IEnumerable boundValue) in d:\external-source\Starcounter\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 383
   at Starcounter.Json.Refresh(Template property) in d:\external-source\Starcounter\src\Starcounter.XSON\Class Json\Json.cs:line 300
   at Starcounter.Json.InitBoundArrays(TValue template) in d:\external-source\Starcounter\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 148
   at Starcounter.Json.InternalSetData(Object data, TValue template, Boolean readOperation) in d:\external-source\Starcounter\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 98
   at Starcounter.Json.<set_Data>b__a(Json j, Object v) in d:\external-source\Starcounter\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 47
   at Starcounter.Internal.TransactionManager.Scope[T1,T2](TransactionHandle handle, Action`2 action, T1 arg1, T2 arg2) in C:\BuildAgent\work\sc-develop-nightly-167\Level1\src\Starcounter\TransactionManager.cs:line 471
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2](Json json, Action`2 action, T1 arg1, T2 arg2) in d:\external-source\Starcounter\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 77
   at Starcounter.Json.set_Data(Object value) in d:\external-source\Starcounter\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 38
   at AdminApp.set_Data(AdminAppViewModel value) in d:\source\Scdb2Apps\HeadsAdmin\HSM\WebUI\obj\Debug\AdminApp.json.g.cs:line 0
   at HAD.WebUI.HADWebApp.<Start>b__2() in d:\source\Scdb2Apps\HeadsAdmin\HSM\WebUI\HADWebApp.cs:line 110
   at Starcounter.Db.Scope[TResult](Func`1 func, Boolean isReadOnly) in C:\BuildAgent\work\sc-develop-nightly-167\Level1\src\Starcounter\Db.cs:line 304
   at HAD.WebUI.HADWebApp.<Start>b__1(Request r) in d:\source\Scdb2Apps\HeadsAdmin\HSM\WebUI\HADWebApp.cs:line 103
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\BuildAgent\work\sc-develop-nightly-167\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\BuildAgent\work\sc-develop-nightly-167\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\BuildAgent\work\sc-develop-nightly-167\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 557
HResult=-2147467261

More information about this error may be available in the server error log.

**Comment by chrhol** [comment]
I think it should simply handle that a bound value can be null. So this is clearly a bug. I will fix it.

On another note: we will start to work on getting a roadmap in place for future enhancements for TypedJSON and supporting null values are one item that's been popping up from time to time.

**Comment by chrhol** [comment]
Fix pushed to develop.
