### ISSUE TITLE
pnext: Nightly build failed with timeout on UDP test

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#3308]
[This build](https://teamcity.starcounter.org/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=536#_focus=12205) fails with:

>[04:00:35][udp_test-bat] Process did not exit within allowed time: "C:\TeamCity\TeamCity9\buildAgent\work\sc-40\Level1\src\Samples\UdpTest\udp_test.bat " and allowed time(sec): 100
[04:00:35][udp_test-bat] -- Running process "staradmin kill all"
[04:00:35][udp_test-bat] System.Exception: Process did not exit within allowed time: "C:\TeamCity\TeamCity9\buildAgent\work\sc-40\Level1\src\Samples\UdpTest\udp_test.bat " and allowed time(sec): 100
[04:00:35][udp_test-bat]    at BuildSystemHelper.BuildSystem.StartProcessAndWaitForExitAndGetStandardOutput(String pathToExe, String args, String& standardOutput, Int32 msToWait) in C:\TeamCity\TeamCity9\buildAgent\work\sc-40\BuildSystem\src\BuildSystemHelper\BuildSystemHelper.cs:line 794
[04:00:35][udp_test-bat]    at TestRunner.TestRunner.RunTests(String pathToCheckoutDir, TestTypes testType, List`1 testsToSkip, Dictionary`2 longTestsDurationsSeconds, Boolean continueTestsAfterFirstFail) in C:\TeamCity\TeamCity9\buildAgent\work\sc-40\BuildSystem\src\TestRunner\TestRunner.cs:line 446

**Comment by alemoi** [comment]
Thank you for reporting! I will check the problem.

**Comment by dan31** [comment]
@alemoi have you checked the problem.
