### ISSUE TITLE
pnext: Crash when creating new database

### ISSUE THREAD

**Issue by linkdata** [Starcounter/Starcounter#3310]
While creating a new database named `repl2`. After restarting everything, the database seems to have been created. This may be an UI refresh issue.

First exception, from `Starcounter`:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask) in C:\TeamCity\TeamCity9\buildAgent\work\sc-39\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 132
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\TeamCity9\buildAgent\work\sc-39\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 86
```

Second exception, from `Starcounter.Server.Commands`:

```
ScErrUnexpectedCommandException (SCERR10016): Creating database repl2 failed due to an unexpected problem.
Version: 2.3.605.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10016.
 System.NullReferenceException: Object reference not set to an instance of an object.
   at Administrator.Server.Managers.ServerManager.ServerModel_Changed(Object sender, EventArgs e) in C:\TeamCity\TeamCity9\buildAgent\work\sc-39\Level1\src\Starcounter.Administrator\Server\Managers\ServerManager.cs:line 302
   at Administrator.Server.Model.Server.OnChanged(Object sender, EventArgs e) in C:\TeamCity\TeamCity9\buildAgent\work\sc-39\Level1\src\Starcounter.Administrator\Server\Model\Server.cs:line 194
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at Administrator.Server.Model.Server.InvalidateDatabases() in C:\TeamCity\TeamCity9\buildAgent\work\sc-39\Level1\src\Starcounter.Administrator\Server\Model\Server.cs:line 223
   at Administrator.Server.Managers.ServerManager.<>c.<RegisterInternalModelApi>b__8_0(Request request) in C:\TeamCity\TeamCity9\buildAgent\work\sc-39\Level1\src\Starcounter.Administrator\Server\Managers\ServerManager.cs:line 258
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\TeamCity9\buildAgent\work\sc-39\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-39\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Rest.UriManagedHandlersCodegen.RunUriMatcherAndCallHandler(String methodSpaceUriSpace, String methodSpaceUriSpaceLower, Request req, UInt16 portNumber, Response& resp) in C:\TeamCity\TeamCity9\buildAgent\work\sc-39\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 1114
   at Starcounter.Self.DoSelfNodeCall(UInt16 portNumber, String method, String relativeUri, Dictionary`2 headersDictionary, String body, Byte[] bodyBytes, HandlerOptions handlerOptions, Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-39\Level1\src\Starcounter.Internal\Rest\Self.cs:line 392
   at Starcounter.Self.POST(String uri, String body, Byte[] bodyBytes, Dictionary`2 headersDictionary, UInt16 port, HandlerOptions ho) in C:\TeamCity\TeamCity9\buildAgent\work\sc-39\Level1\src\Starcounter.Internal\Rest\Self.cs:line 155
   at Starcounter.Server.PublicModelProvider.AddDatabase(Database database) in C:\TeamCity\TeamCity9\buildAgent\work\sc-39\Level1\src\Server\Starcounter.Server\PublicModelProvider.cs:line 61
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\TeamCity\TeamCity9\buildAgent\work\sc-39\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 298
```

**Comment by dan31** [comment]
Similar or equal to https://github.com/Starcounter/Starcounter/issues/3298 ? CC @andwah

**Comment by andwah** [comment]
@dan31 equal to #3298 

@linkdata I think this is fixed in "level1" branch but not yet merged into pNext.

**Comment by dan31** [comment]
@andwah what is a status for it being in pnext now?

**Comment by andwah** [comment]
@dan31 Not sure i have never tested pNext. but the source-code looks the same in develop and pNext for this case.  does this exception still occurs?

**Comment by per-samuelsson** [comment]
I merged latest **develop** into **pnext** early this morning, so if @andwah haven't done anything particular in a merge previous to that, this should be part of **pnext** for sure.

I haven't experienced it for quite a while, running a mix of both branches. Have you done so recently, @dan31? Otherwise, I suggest we close this one as fixed.
