### ISSUE TITLE
pnext: IndexOutOfRangeException in Starcounter.Profiler.Current

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3336]
Built a local Starcounter build of **pnext** at 16fce5c517990f8a31edb1d0b8291ce845a5c8b6. When I'm trying to explicitly create a new database in web administrator, it fails with this exception ending up in the log:

```
"ScErrUnexpectedCommandException (SCERR10016): Creating database Harbor failed due to an unexpected problem.
Version: 2.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10016.
 System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Starcounter.Profiler.get_Current() in C:\Users\Per\Git\Starcounter\PNext\Level1\src\Starcounter.Internal\Profiler\Profiler.cs:line 318
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\Users\Per\Git\Starcounter\PNext\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 70
   at Starcounter.Rest.UriManagedHandlersCodegen.RunUriMatcherAndCallHandler(String methodSpaceUriSpace, String methodSpaceUriSpaceLower, Request req, UInt16 portNumber, Response& resp) in C:\Users\Per\Git\Starcounter\PNext\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 1114
   at Starcounter.Self.DoSelfCall(UInt16 portNumber, String method, String relativeUri, Dictionary`2 headersDictionary, String body, Byte[] bodyBytes, HandlerOptions handlerOptions, Request req) in C:\Users\Per\Git\Starcounter\PNext\Level1\src\Starcounter.Internal\Rest\Self.cs:line 392
   at Starcounter.Self.POST(String uri, String body, Byte[] bodyBytes, Dictionary`2 headersDictionary, UInt16 port, HandlerOptions ho) in C:\Users\Per\Git\Starcounter\PNext\Level1\src\Starcounter.Internal\Rest\Self.cs:line 155
   at Starcounter.Server.PublicModelProvider.AddDatabase(Database database) in C:\Users\Per\Git\Starcounter\PNext\Level1\src\Server\Starcounter.Server\PublicModelProvider.cs:line 66
   at Starcounter.Server.Commands.CreateDatabaseCommandProcessor.Execute() in C:\Users\Per\Git\Starcounter\PNext\Level1\src\Server\Starcounter.Server\Commands\Processors\CreateDatabaseCommandProcessor.cs:line 39
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\Users\Per\Git\Starcounter\PNext\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 298
HResult=-2146233080
"
```

**Comment by alemoi** [comment]
Thanks for reporting! This issue is already fixed. Just pull the latest pnext.

**Comment by k-rus** [comment]
(it was reported in #3332)
