### ISSUE TITLE
pnext: When `star.exe` tries to create a database automatically, it uses a hardcoded collation DLL

### ISSUE THREAD

**Issue by linkdata** [Starcounter/Starcounter#3343]
```
ScErrUnexpectedCommandException (SCERR10016): Creating database skronk failed due to an unexpected problem.
Version: 2.3.729.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10016.
 Starcounter.Server.ToolInvocationException: Error invoking ""C:\Program Files\Starcounter\sccreatedb.exe" -ip "C:\Users\Johan\Documents\Starcounter\Personal\Data\skronk\skronk-20160204T104729604" -coll TurboText_en-GB_3.dll -oid 1 -lastoid 4611686018427387903 skronk": exit code is 0x1. Tool output:

 Starcounter permanent storage creation utility.
Copyright (C) Starcounter AB 2007-2016. All rights reserved.

Error: ScErrDatabaseLangUnsupported (SCERR2023): One of more of the languages the database is configured for isn't supported by the current system.


   at Starcounter.Server.ToolInvocationHelper.InvokeTool(ProcessStartInfo processStartInfo, Boolean checkExitCode) in C:\TeamCity\TeamCity9\buildAgent\work\sc-47\Level1\src\Server\Starcounter.Server\ToolInvocationHelper.cs:line 167
   at Starcounter.Server.DatabaseStorageService.CreateStorage(String name, String imagePath, DatabaseStorageConfiguration configuration) in C:\TeamCity\TeamCity9\buildAgent\work\sc-47\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseStorageService.cs:line 144
   at Starcounter.Server.DatabaseSetup.CreateFiles() in C:\TeamCity\TeamCity9\buildAgent\work\sc-47\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseSetup.cs:line 114
   at Starcounter.Server.DatabaseSetup.CreateDatabase() in C:\TeamCity\TeamCity9\buildAgent\work\sc-47\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseSetup.cs:line 134
   at Starcounter.Server.Commands.CreateDatabaseCommandProcessor.Execute() in C:\TeamCity\TeamCity9\buildAgent\work\sc-47\Level1\src\Server\Starcounter.Server\Commands\Processors\CreateDatabaseCommandProcessor.cs:line 31
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\TeamCity\TeamCity9\buildAgent\work\sc-47\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
ExitCode=1
HResult=-2146233088
```

The file `TurboText_en-GB_3.dll` is hard coded, but not available in the `pnext` distrubution.

**Comment by eriohl** [comment]
I changed the hardcoded reference in code to version 4. I would guess that in your case it is reading from configuration file from previous installation or something. New installation works fine for me.

**Comment by linkdata** [comment]
Yep, it's in the `Personal.server.config`. Possibly this should be fixed by installer then? Having a check in it that changes references from `TurboText_*_3.dll` to `TurboText_*_4.dll`? Alternatively, if the referenced DLL doesn't exist, reset it to the hardcoded default.

/cc @alemoi

**Comment by alemoi** [comment]
Yes, its a general problem with configuration files changing between versions. I never worked with file conversions unfortunately so can't say what is the right approach in this case. @dan31 any experience with configuration file converters?

**Comment by dan31** [comment]
@alemoi We can write one. I have one written in Perl. I will get you
accustomed so that you can recreate the one in csharp once we bounce on the
issue. Not particularly urgent yet deserves attention.

**Comment by per-samuelsson** [comment]
FWIW, all our configuration files are serialized/deserialized from/to POCO's into XML, with every config type being strongly typed in the `Starcounter.Server` namespace/assembly. Could be an alternative to go that route supporting conversions.

**Comment by per-samuelsson** [comment]
We now have a customer suffering from this, we need to come with some advice / bump it.

**Comment by per-samuelsson** [comment]
Suggested workaround until fixed:

1. Open a prompt and run `staradmin kill all`
2. Then open the file `Personal.server.config`. If you have installed using defaults, it will be under `C:\Users\[yourname]\Documents\Starcounter\Personal\
3. In that file, locate the value of the `<CollationFile>` attribute, change it from **TurboText_en-GB_3.dll** to **TurboText_en-GB_4.dll**

From [here](https://github.com/Starcounter/Starcounter/issues/4051#issuecomment-273793355).
