### ISSUE TITLE
pnext: When starting an application from Visual Studio 2015 and `sccreatedb.exe` fails, no error message is shown

### ISSUE THREAD

**Issue by linkdata** [Starcounter/Starcounter#3344]
Hitting F5 when the solution is configured to use a database that does not exist, it tries to create the database and fails. But the error message only appears in the Starcounter log, and no indication of why it failed to launch is shown in Visual Studio 2015.

Related to https://github.com/Starcounter/Starcounter/issues/3343.

**Comment by per-samuelsson** [comment]
Thanks for creating this issue. I'll assign it to me to eventually take a look.

**Comment by per-samuelsson** [comment]
I tested this. First in the CLI, using

```
star -d=i3344 app.cs
```

(where database "i3344" does not exist), I get this error in the console:

```
[13:13:13, Error, Starcounter.Server.Commands (scadminserver)]
ScErrUnexpectedCommandException (SCERR10016): Creating database i3344 failed due to an unexpected problem.
Version: 2.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10016.
 Starcounter.Server.ToolInvocationException: Error invoking ""C:\Users\Per\Git\Starcounter\PNext\Level1\bin\Debug\sccreatedb.exe" -ip "C:\Users\Per\Documents\Starcounter\Personal\Data\i3344\i3344-20160210T131313804" -coll TurboText_en-GB_4.dll-- -oid 1 -lastoid 4611686018427387903 i3344": exit code is 0x1. Tool output:

 Starcounter permanent storage creation utility.
Copyright (C) Starcounter AB 2007-2016. All rights reserved.

Error: ScErrDatabaseLangUnsupported (SCERR2023): One of more of the languages the database is configured for isn't supported by the current system.


   at Starcounter.Server.ToolInvocationHelper.InvokeTool(ProcessStartInfo processStartInfo, Boolean checkExitCode) in C:\Users\Per\Git\Starcounter\PNext\Level1\src\Server\Starcounter.Server\ToolInvocationHelper.cs:line 170
   at Starcounter.Server.ToolInvocationHelper.InvokeTool(ProcessStartInfo processStartInfo) in C:\Users\Per\Git\Starcounter\PNext\Level1\src\Server\Starcounter.Server\ToolInvocationHelper.cs:line 36
   at Starcounter.Server.DatabaseStorageService.CreateStorage(String name, String imagePath, DatabaseStorageConfiguration configuration) in C:\Users\Per\Git\Starcounter\PNext\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseStorageService.cs:line 143
   at Starcounter.Server.DatabaseSetup.CreateFiles() in C:\Users\Per\Git\Starcounter\PNext\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseSetup.cs:line 106
   at Starcounter.Server.DatabaseSetup.CreateDatabase() in C:\Users\Per\Git\Starcounter\PNext\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseSetup.cs:line 134
   at Starcounter.Server.Commands.CreateDatabaseCommandProcessor.Execute() in C:\Users\Per\Git\Starcounter\PNext\Level1\src\Server\Starcounter.Server\Commands\Processors\CreateDatabaseCommandProcessor.cs:line 35
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\Users\Per\Git\Starcounter\PNext\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 298
ExitCode=1
HResult=-2146233088
```

Then I went to VS and created a new "Starcounter Application" project, set the command-line to "-d=i3344", hit F5 and in **Error List**, I get this:

```
Creating database i3344 failed due to an unexpected problem. ("Error invoking ""C:\Users\Per\Git\Starcounter\PNext\Level1\bin\Debug\sccreatedb.exe" -ip "C:\Users\Per\Documents\Starcounter\Personal\Data\i3344\i3344-20160210T131313804" -coll TurboText_en-GB_4.dll-- -oid 1 -lastoid 4611686018427387903 i3344": exit code is 0x1. Tool output:

 Starcounter permanent storage creation utility.
Copyright (C) Starcounter AB 2007-2016. All rights reserved.

Error: ScErrDatabaseLangUnsupported (SCERR2023): One of more of the languages the database is configured for isn't supported by the current system.

"). (ScErrUnexpectedCommandException (SCERR10016))

(Double-click here for additional help)			0	
```

None of them super-nice in terms of format, but still better than "no error".

@linkdata, I'm guessing you either didn't get this, or that you expected error output somewhere else?

**Comment by per-samuelsson** [comment]
> @linkdata, I'm guessing you either didn't get this, or that you expected error output somewhere else?

I verified this with @linkdata, and we can reproduce it on his machine every time. But then we tried on other machines, and we can not. We decided to close it down until we get some reason to analyze it further.
