### ISSUE TITLE
TypeInitializationException with Static Constructor

### ISSUE THREAD

**Issue by andwah** [Starcounter/Starcounter#3377]
Sometimes i always get this exception when i have a static constructor on the class.

A database restart do not solve it, but in a new database it starts to work, then suddenly this error  starts occurring.
Sorry no easy way to reproduce, i hope you will find a good clue from the stacktrace below.

Code:
```
new App();
```

Class:
```
[Database]
public class App{
  static App() {
    ...
  }
}

```

Exception
```
System.TypeInitializationException: The type initializer for 'Warehouse.Suite' threw an exception.
   at Warehouse.Suite..ctor(Uninitialized u)
   at gen.Warehouse.Suite.Warehouse.Suite_Binding.NewUninitializedInst()
   at Starcounter.Binding.TypeBinding.NewInstance(UInt64 addr, UInt64 oid) in C:\github\Level1\src\Starcounter\Binding\TypeBinding.cs:line 183
   at Starcounter.Internal.DbState.ReadObject(UInt64 oid, UInt64 address, Int32 index) in C:\github\Level1\src\Starcounter\Internal\DbState.cs:line 460
   at Warehouse.OrganizationSoftware.get_Application()
   at Starcounter.Binding.PropertyBinding.GetObject(Object obj) in C:\github\Level1\src\Starcounter\Binding\PropertyBinding.cs:line 292
   at Starcounter.Internal.DbState.View.GetObject(TypeBinding binding, Int32 index, Object proxy) in C:\github\Level1\src\Starcounter\Internal\DbState.cs:line 71
   at Warehouse.OrganizationSoftware.Starcounter.IObjectView.GetObject(Int32 index)
   at Starcounter.Query.Execution.ObjectProperty.EvaluateToObject(IObjectView obj) in C:\github\Level1\src\Starcounter\Query\Execution\Properties\ObjectProperty.cs:line 131
   at Starcounter.Query.Execution.ObjectProperty.AppendToByteArray(ByteArrayBuilder key, IObjectView obj) in C:\github\Level1\src\Starcounter\Query\Execution\Properties\ObjectProperty.cs:line 106
   at Starcounter.Query.Execution.CodeGenFilterPrivate.GetDataStream(Row obj) in C:\github\Level1\src\Starcounter\Query\Execution\CodeGeneration\CodeGenFilterPrivate.cs:line 250
   at Starcounter.Query.Execution.FullTableScan.CreateEnumerator() in C:\github\Level1\src\Starcounter\Query\Execution\Enumerators\FullTableScan.cs:line 413
   at Starcounter.Query.Execution.FullTableScan.MoveNext() in C:\github\Level1\src\Starcounter\Query\Execution\Enumerators\FullTableScan.cs:line 477
   at Starcounter.Query.Execution.Join.NextRightAndLeftEnumerators() in C:\github\Level1\src\Starcounter\Query\Execution\Enumerators\Join.cs:line 280
   at Starcounter.Query.Execution.Join.MoveNext() in C:\github\Level1\src\Starcounter\Query\Execution\Enumerators\Join.cs:line 253
   at Starcounter.SqlEnumerator`1.MoveNext() in C:\github\Level1\src\Starcounter\Query\Execution\Enumerators\GenericEnumerator.cs:line 32
   at Starcounter.Json.CheckBoundArray(IEnumerable boundValue) in C:\github\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 379
   at Starcounter.Json.Refresh(Template property) in C:\github\Level1\src\Starcounter.XSON\Class Json\Json.cs:line 300
   at Starcounter.Json.InitBoundArrays(TValue template) in C:\github\Level1\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 148
   at Starcounter.Json.InternalSetData(Object data, TValue template, Boolean readOperation) in C:\github\Level1\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 98
   at Starcounter.Json.<>c.<set_Data>b__218_0(Json j, Object v) in C:\github\Level1\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 47
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2](Json json, Action`2 action, T1 arg1, T2 arg2) in C:\github\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 79
   at Starcounter.Json.set_Data(Object value) in C:\github\Level1\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 38
   at Warehouse.ViewModels.OrganizationPage.set_Data(Organization value) in C:\github\Starcounter\Warehouse\src\obj\x64\Debug\ViewModels\OrganizationPage.json.g.cs:line 0
   at Warehouse.Api.OrganizationHandlers.<>c.<RegisterPartials>b__1_2(String key) in C:\github\Starcounter\Warehouse\src\Api\OrganizationHandlers.cs:line 220
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\github\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\github\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Rest.UriManagedHandlersCodegen.RunUriMatcherAndCallHandler(String methodSpaceUriSpace, String methodSpaceUriSpaceLower, Request req, UInt16 portNumber, Response& resp) in C:\github\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 1114
   at Starcounter.Self.DoSelfCall(UInt16 portNumber, String method, String relativeUri, Dictionary`2 headersDictionary, String body, Byte[] bodyBytes, HandlerOptions handlerOptions, Request req) in C:\github\Level1\src\Starcounter.Internal\Rest\Self.cs:line 397
   at Starcounter.Self.GET(UInt16 port, String uri, Dictionary`2 headersDictionary, HandlerOptions ho) in C:\github\Level1\src\Starcounter.Internal\Rest\Self.cs:line 133
   at Starcounter.Self.GET(String uri, Dictionary`2 headersDictionary, HandlerOptions ho) in C:\github\Level1\src\Starcounter.Internal\Rest\Self.cs:line 117
   at Starcounter.Self.GET(String uri) in C:\github\Level1\src\Starcounter.Internal\Rest\Self.cs:line 74
   at Warehouse.Api.OrganizationHandlers.<>c.<Register>b__0_1(String key) in C:\github\Starcounter\Warehouse\src\Api\OrganizationHandlers.cs:line 50
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\github\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\github\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Self.CallUsingExternalRequest(Request req, Func`1 substituteHandler) in C:\github\Level1\src\Starcounter.Internal\Rest\Self.cs:line 285
   at Launcher.LauncherHelper.WrapInLauncher(Request req, String appName) in D:\GitHub\Samples\Launcher\src\Launcher\Api\LauncherHelper.cs:line 182
   at Launcher.LauncherHelper.<>c.<Init>b__0_0(Request req) in D:\GitHub\Samples\Launcher\src\Launcher\Api\LauncherHelper.cs:line 46
   at Starcounter.Handle.RunRequestFilters(Request req) in C:\github\Level1\src\Starcounter.Internal\Handle.cs:line 476
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\github\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 550
TypeName=Warehouse.Suite
HResult=-2146233036
---> Starcounter.DbException: ScErrTransactionLockedOnThread (SCERR4031): Can't modify the state of the transaction.
Version: 2.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4031.
   at Starcounter.Hooks.RuntimeDelegate`1.InstallCommitHook(UInt16 tableId, UInt32 hookConfiguration, InvokableHook entry) in C:\github\Level1\src\Starcounter\Hooks\RuntimeDelegate.cs:line 155
   at Starcounter.Hooks.RuntimeDelegate`1.add_CommitInsert(EventHandler`1 value) in C:\github\Level1\src\Starcounter\Hooks\RuntimeDelegate.cs:line 109
   at Starcounter.Hook`1.add_CommitInsert(EventHandler`1 value) in C:\github\Level1\src\Starcounter\Hooks\Hook.cs:line 44
   at Warehouse.Suite..cctor() in C:\github\Starcounter\Warehouse\src\Database\Suite.cs:line 10
ErrorCode=4031
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4031

More information about this error may be available in the server error log.
```

**Comment by per-samuelsson** [comment]
@andwah 

1. I'm not sure how well we handle static constructors in database classes. I don't see any case that we should not allow them though, it's more of a general disclaimer.
2. The stacktrace indicates the exception is raised from the static constructor of `Warehouse.Suite`. So would be interesting to see what you have in there.

**Comment by per-samuelsson** [comment]
My initial guess is you are suffering from #2766.

**Comment by andwah** [comment]
Instead of using a static constructor to register my `hooks` i switch it to `public static void RegisterHooks()` in my class and called it when my app starts, that seems to work better, have not got any exception yet.

Inside my constructor:
```
   Hook<Suite>.CommitInsert += (sender, suite) => {

                Organization organization = Db.SQL<Organization>("SELECT o.Organization FROM Warehouse.OrganizationSoftware o WHERE o.Application=?", suite).First;
                if (organization != null) {
                    // Grant all organization users access to the app by creating permissions for each user
                    QueryResultRows<OrganizationPermission> orgPermissions = Db.SQL<OrganizationPermission>("SELECT o FROM Warehouse.OrganizationPermission o WHERE o.Organization=?", organization);
                    foreach (OrganizationPermission permission in orgPermissions) {

                        ApplicationPermission applicationPermission = Db.SQL<ApplicationPermission>("SELECT o FROM Warehouse.ApplicationPermission o WHERE o.User=?", permission.User).First;
                        if (applicationPermission != null) {
                            continue; // Duplicated
                        }
                        new ApplicationPermission() { User = permission.User, Application = suite };
                    }
                    return;
                }

                throw new InvalidOperationException("Applications is not connected to an organization");
            };

            Hook<Suite>.BeforeDelete += (sender, suite) => {

                // Delete permissions assosiated to this app
                var result = Db.SQL<ApplicationPermission>("SELECT o FROM Warehouse.ApplicationPermission o WHERE o.Application=?", suite);
                foreach (ApplicationPermission s in result) {
                    s.Delete();
                }

                // Delete all relation between this software and a organization
                var relations = Db.SQL<OrganizationSoftware>("SELECT o FROM Warehouse.OrganizationSoftware o WHERE o.Application=?", suite);
                foreach (OrganizationSoftware relation in relations) {
                    relation.Delete();
                }

                // Delete all relation between this software and a depot
                var depotRelations = Db.SQL<DepotSoftware>("SELECT o FROM Warehouse.DepotSoftware o WHERE o.Software=?", suite);
                foreach (DepotSoftware relation in depotRelations) {
                    relation.Delete();
                }
            };
```
