### ISSUE TITLE
pnext: Create table failed because one or more columns shared the same name token as another column

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3378]
I am trying to start an application (Warehouse) and receiving this exception:

```
ScErrColumnNameNotUnique: Create table failed because one or more columns shared the same name token as another column.
```

Most likely this is not an issue in Starcounter, but the exception text should be improved with explanation, of what columns in what tables are not unique.

cc @chrhol, @k-rus

**Comment by miyconst** [comment]
Hm. The issue has gone after restarting same application.

**Comment by miyconst** [comment]
```
"Starcounter.DbException: ScErrColumnNameNotUnique (SCERR4277): Create table failed because one or more columns shared the same name token as another column.
Version: 2.3.852.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4277.
   at Starcounter.SqlProcessor.SqlProcessor.MetalayerThrowIfError(UInt32 err) in C:\TeamCity\TeamCity9\buildAgent\work\sc-59\Level1\src\Starcounter\SqlProcessor\SqlProcessor.cs:line 282
   at Starcounter.Binding.TableUpgrade.Eval() in C:\TeamCity\TeamCity9\buildAgent\work\sc-59\Level1\src\Starcounter\Binding\TableUpgrade.cs:line 102
   at Starcounter.Hosting.Package.CreateOrUpdateDatabaseTable(TypeDef typeDef) in C:\TeamCity\TeamCity9\buildAgent\work\sc-59\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 423
   at Starcounter.Hosting.Package.UpdateDatabaseSchemaAndRegisterTypes(String fullAppId, TypeDef[] unregisteredTypeDefs, TypeDef[] allTypeDefs) in C:\TeamCity\TeamCity9\buildAgent\work\sc-59\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 334
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application) in C:\TeamCity\TeamCity9\buildAgent\work\sc-59\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 261
   at Starcounter.Hosting.Package.Process() in C:\TeamCity\TeamCity9\buildAgent\work\sc-59\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 143
   at Starcounter.Hosting.Package.Process(IntPtr hPackage) in C:\TeamCity\TeamCity9\buildAgent\work\sc-59\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 56
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\TeamCity9\buildAgent\work\sc-59\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 86
ErrorCode=4277
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4277
"
```

**Comment by miyconst** [comment]
```
"Starcounter.DbException: ScErrColumnNameNotUnique (SCERR4277): Create table failed because one or more columns shared the same name token as another column. Version: 2.3.852. Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4277. 
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.<>c__DisplayClass4_0.<Execute>b__3(CommandTask task) in C:\TeamCity\TeamCity9\buildAgent\work\sc-59\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 180
   at Starcounter.Server.Commands.CommandProcessor.<>c__DisplayClass68_0.<WithinTask>b__0(CommandTask t) in C:\TeamCity\TeamCity9\buildAgent\work\sc-59\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 484
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) in C:\TeamCity\TeamCity9\buildAgent\work\sc-59\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 510
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.Execute() in C:\TeamCity\TeamCity9\buildAgent\work\sc-59\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 194
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\TeamCity\TeamCity9\buildAgent\work\sc-59\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
ErrorCode=4277
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4277
"
```

**Comment by k-rus** [comment]
cc @alexanderstc

**Comment by k-rus** [comment]
@miyconst 
Which version of Starcounter do you run? pnext or develop?

**Comment by miyconst** [comment]
@k-rus, it is `Version: 2.3.852` as shown in the stack trace.

**Comment by dan31** [comment]
@miyconst thanks for renaming. @k-rus, so far @miyconst incubates ```pnext``` in regular Starcounter development. And so do @per-samuelsson and @jwillmer.

**Comment by k-rus** [comment]
@alexanderstc 
Can you create error message with the request information, i.e., name of the table and name of the column? Can you also correct the error code, since the error is not in create table, but in alter table?

**Comment by k-rus** [comment]
> @miyconst thanks for renaming. @k-rus, so far @miyconst incubates pnext in regular Starcounter development. And so do @per-samuelsson and @jwillmer.

Thank you for clarifying. Please, be patient as I will ask every time when I am not 100% sure.

**Comment by alexanderstc** [comment]
@miyconst is this easily reproducible?
If it is, I'd like to ask you to keep it that way (create necessary branches whatever).

**Comment by miyconst** [comment]
It's not reproducible at all. Restarting same application without a change, in same environment solved the issue. Starting the app in an empty database also didn't rise the issue.

**Comment by alexanderstc** [comment]
> It's not reproducible at all

@k-rus OK then I'll just make a unit test to force this.

**Comment by alexanderstc** [comment]
@k-rus
> Can you create error message with the request information, i.e., name of the table and name of the column? Can you also correct the error code, since the error is not in create table, but in alter table?

I'll do all that, will take me some typing on keyboard.

**Comment by k-rus** [comment]
The experienced error is due to schema upgrade, which can happen only if an application with updated schema is started. Thus it cannot happen on empty database. However, I would expect that restarting application should fail. Then it is probably the bug in managed code related to #3387.
After @alexanderstc fix of the error message the bug will be open for further investigation.

@miyconst Do you have the database and application code, which failed to start? If so, can you copy into my exchange folder on dropbox?

**Comment by alexanderstc** [comment]
> Can you create error message with the request information, i.e., name of the table and name of the column? Can you also correct the error code, since the error is not in create table, but in alter table?

Done, in pnext.
In case of conflicting colum definitions star_alter_table_add_columns() returns SCERRCOLUMNSARENTUNIQUE and creates a human-readable error message, available via star_metalayer_errbuf().

**Comment by alexanderstc** [comment]
If metalayer finds no conflicting columns, but the kernel still think they are in conflict, star_alter_table_add_columns() returns SCERRUNEXPMETADATA and a message with the table name in star_metalayer_errbuf().

**Comment by alexanderstc** [comment]
I'd also like to ask @eriohl and @bigwad to consider accepting metalayer's per-context error message buffers (or similar) into the kernel and, like metalayer does, use ucs2_stream to create human-readable error messages for kernel errors, with details, e.g. which exactly columns conflict in case of SCERRCOLUMNNAMENOTUNIQUE, see the implementation of star_alter_table_add_columns() for how a similar message is created.
CC @k-rus.

**Comment by k-rus** [comment]
> If metalayer finds no conflicting columns, but the kernel still think they are in conflict, star_alter_table_add_columns() returns SCERRUNEXPMETADATA and a message with the table name in star_metalayer_errbuf().

That's correct. I guess it is hypothetical case and if we meet in reality it will be a bug for an investigation.

**Comment by alexanderstc** [comment]
> it is hypothetical case and if we meet in reality it will be a bug for an investigation.
My thoughts exactly.

**Comment by alexanderstc** [comment]
Done of Feb 22.
