### ISSUE TITLE
pnext: NullReferenceException in binding after dropping table

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3387]
Running on a local **pnext** build, pulled like 1-2 days ago.

Can easily be reproduced every time:

1. Create a new application with `staradmin +`.
2. Edit the generated `app.cs` like shown below.
3. Run it in a new database, e.g. `star -d=newdb app.cs`
4. Stop the application: `staradmin -d=newdb stop app app`
5. Go to web admin SQL, database `newdb`, execute `DROP TABLE Foo`.
6. Restart the application: `star -d=newdb app.cs`

```
[19:30:20, Critical, Starcounter (newdb)]
System.NullReferenceException: Object reference not set to an instance of an object.
   at Starcounter.Binding.ColumnDef.Equals(ColumnDef columnDef) in C:\Users\Per\Git\Starcounter\PNext\Level1\src\Starcounter\Binding\ColumnDef.cs:line 66
   at Starcounter.Binding.TableDef.Equals(TableDef tableDef) in C:\Users\Per\Git\Starcounter\PNext\Level1\src\Starcounter\Binding\TableDef.cs:line 209
   at Starcounter.Hosting.Package.CreateOrUpdateDatabaseTable(TypeDef typeDef) in C:\Users\Per\Git\Starcounter\PNext\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 421
   at Starcounter.Hosting.Package.UpdateDatabaseSchemaAndRegisterTypes(String fullAppId, TypeDef[] unregisteredTypeDefs, TypeDef[] allTypeDefs) in C:\Users\Per\Git\Starcounter\PNext\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 334
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application) in C:\Users\Per\Git\Starcounter\PNext\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 261
   at Starcounter.Hosting.Package.Process() in C:\Users\Per\Git\Starcounter\PNext\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 143
   at Starcounter.Hosting.Package.Process(IntPtr hPackage) in C:\Users\Per\Git\Starcounter\PNext\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 55
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\Users\Per\Git\Starcounter\PNext\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 86
HResult=-2147467261
```

**app.cs**
```cs
using Starcounter;
using System;

[Database] public class Foo {
}

class Program {
    static void Main() {
        Console.WriteLine("{0} starting...", Application.Current);
    }
}
```

Noticed this by chance when I tested #3386, and have confirmed it happens every time.

**Comment by k-rus** [comment]
Thank you for reporting!
The issue is related to the need to revisit usage of native API after BAH project, which was to merge incompatible develop and pnext. In a sense the main issue is #3070, but this one clearly shows existing bugs related to needed refactoring and highers the priority.
Basically, now Level1 uses metalayer and kernel APIs in parallel, which are not designed to work in this way. Kernel API is internal, while metalayer should be used publicly.

**Comment by k-rus** [comment]
> Basically, now Level1 uses metalayer and kernel APIs in parallel, which are not designed to work in this way. Kernel API is internal, while metalayer should be used publicly.

This can be fixed after Starcounter/CompanyTrack#137

**Comment by k-rus** [comment]
The bug is reproduced by a regression test `DropTableBug3387_test.bat` in branch ` bug/pnextDropTable3387`.

**Comment by dan31** [comment]
Is this one still an issue?

**Comment by k-rus** [comment]
I started a build where I enabled this test: https://teamcity.starcounter.org/viewLog.html?buildId=20079&buildTypeId=Starcounter_DevelopDailyWindows&tab=buildResultsDiv

It is necessary inspect the result of the build when finished if the test was run and its result.

**Comment by k-rus** [comment]
Enabling through environment variable didn't work, since it is black listed.

**Comment by k-rus** [comment]
There was nothing indicating that the issue was fixed. I took time and run the test locally, which confirmed that the test is not fixed.
