### ISSUE TITLE
pnext: Crash in Starcounter.TransactionLog

### ISSUE THREAD

**Issue by linkdata** [Starcounter/Starcounter#3404]
Under heavy load, the `Starcounter.TransactionLog.LogReader` crashed with:

```
System.AggregateException: One or more errors occurred. ---> 
Starcounter.TransactionLog.TransactionLogException: Exception of type 'Starcounter.TransactionLog.TransactionLogException' was thrown.
 at Starcounter.TransactionLog.LogReader.d__5.MoveNext() in C:\TeamCity\TeamCity9\buildAgent\work\sc-68\Level1\src\Server\Starcounter.TransactionLog\LogReader.cs:line 35
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
 at LogStreamer.FilteredLogReader.d__16.MoveNext() in C:\Proj\LogStreamer\FilteredLogReader.cs:line 268
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at LogStreamer.LogStreamerSession.d__117.MoveNext() in C:\Proj\LogStreamer\LogStreamerSession.cs:line 494
 --- End of inner exception stack trace ---
 ---> (Inner Exception #0) Starcounter.TransactionLog.TransactionLogException: Exception of type 'Starcounter.TransactionLog.TransactionLogException' was thrown.
 at Starcounter.TransactionLog.LogReader.d__5.MoveNext() in C:\TeamCity\TeamCity9\buildAgent\work\sc-68\Level1\src\Server\Starcounter.TransactionLog\LogReader.cs:line 35
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
 at LogStreamer.FilteredLogReader.d__16.MoveNext() in C:\Proj\LogStreamer\FilteredLogReader.cs:line 268
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at LogStreamer.LogStreamerSession.d__117.MoveNext() in C:\Proj\LogStreamer\LogStreamerSession.cs:line 494
 <---
```

**Comment by bigwad** [comment]
Do you have a crash dump?
Otherwise I can think of two possible reasons: corrupted log (can be checked with db restart) or unserialized access to LogReader (it's not thread-safe class).

**Comment by linkdata** [comment]
No crash dump.
I can start and stop the database with no problem.
Access is serialized by using Tasks. It won't initiate a new Task on the LogReader until the previous has been completed.

**Comment by bigwad** [comment]
Please setup your lab as stated here: https://github.com/Starcounter/Starcounter/issues/3297#issuecomment-174574035 to make sure we have a crash dump should it crash again.

**Comment by linkdata** [comment]
Ok, I've set it up. I'll see if I can force it again.

**Comment by linkdata** [comment]
Got the error again. For some reason I didn't get a dump file, even though it had been set up.

```
Exception of type 'Starcounter.TransactionLog.TransactionLogException' was thrown.
   at Starcounter.TransactionLog.LogReader.<read_next_transaction>d__5.MoveNext() in C:\TeamCity\TeamCity9\buildAgent\work\sc-90\Level1\src\Server\Starcounter.TransactionLog\LogReader.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LogStreamer.FilteredLogReader.<ReadAsync>d__19.MoveNext() in C:\Proj\LogStreamer\FilteredLogReader.cs:line 234
```

The exception object had `Code 6005` set on it, if that helps.

**Comment by dan31** [comment]
@bigwad Have you investigated this one further on? I thought I have seen something similar today about pnext tests (also without having any dump recorded for some strange reason, but haven't find an issue).

**Comment by bigwad** [comment]
It's not a crash - it's legitimate __managed__ exception on some problem with transaction log processing.

##### Why did exception raised?
There are 3 possible reasons:
1. Physically corrupted log.
2. Log streamer got behind the log retention, i.e. log retention had removed some files had not been sent yet.
3. Corrupted log reader state due to non serialized access (log reader is not thread safe by design).

1 and 2 are unrecoverable and should be reproducible on db restart. I suppose it's not the case in the current issue.
As regarding to 3 @linkdata claims - there shouldn't be concurrent access to log reader.
I don't see other possible reasons, so, I should either spot non serialized access in log streamer or make it thread safe (or both). I'll take it.


##### Why crash dump wasn't generated?
That's because code host intercepts all managed exceptions, dumps call stack and exits the process. Probably, subject to change.
