### ISSUE TITLE
ScErrInputQueueFull (SCERR1026) from Starcounter.Apps.JsonPatch

### ISSUE THREAD

**Issue by linkdata** [Starcounter/Starcounter#3405]
Under heavy load, this message was produced in the log:

```
System.Exception: ScErrInputQueueFull (SCERR1026): Operation failed because the target input queue was full.
Version: 2.3.907.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR1026.
   at Starcounter.Hosting.TaskSchedulerImpl.Run(ITask task, Byte schedId) in C:\TeamCity\TeamCity9\buildAgent\work\sc-68\Level1\src\Hosting\Starcounter.Hosting\TaskSchedulerImpl.cs:line 37
   at Starcounter.DbSession.RunAsync(Action action, Byte schedId) in C:\TeamCity\TeamCity9\buildAgent\work\sc-68\Level1\src\Starcounter\DbSession.cs:line 143
   at Starcounter.Internal.AppsBootstrapper.<>c__DisplayClass6_0.<InitAppsBootstrapper>b__8(Object state) in C:\TeamCity\TeamCity9\buildAgent\work\sc-68\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 235
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
HResult=-2146233088
```

I propose that we apply the same technique I use in `LogStreamer` to change `DbSession.RunAsync()` to retry scheduling a few times with incremental backoff before throwing an exception, since very few (I would like to say 'none') applications gracefully handle random tasks not being scheduled. 

It's an easy change and should be safe enough.

**Comment by dan31** [comment]
@linkdata great idea, see also https://github.com/Starcounter/Starcounter/issues/3388. Can you put your hands on this and see if there is a fix that you can add? The scheduling code is in a managed part and perhaps 100 lines at most. I remember you already participated in discussing this with @chrhol.

**Comment by linkdata** [comment]
I'll do it for pnext to start with, see how it works out. It's a bit of a showstopper for me since it prevents me from testing the LogStreamer under heavy load.

**Comment by dan31** [comment]
That sounds good.
