### ISSUE TITLE
pnext: System.IndexOutOfRangeException from Starcounter.Query.Execution.CodeGenFilterCacheShared.AddNewFilter()

### ISSUE THREAD

**Issue by linkdata** [Starcounter/Starcounter#3410]
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Starcounter.Query.Execution.CodeGenFilterCacheShared.AddNewFilter(DbTypeCode[] varTypes, UInt64 filterHandle) in C:\Proj\level1\src\Starcounter\Query\Execution\CodeGeneration\CodeGenFilterCache.cs:line 98
   at Starcounter.Query.Execution.CodeGenFilterCacheShared.CreateFilter(CodeGenFilterInstrArray instrArray, DbTypeCode[] varTypes, UInt32 maxStackSize, UInt32 dataCount, RowTypeBinding typeBinding, Int32 extentNumber) in C:\Proj\level1\src\Starcounter\Query\Execution\CodeGeneration\CodeGenFilterCache.cs:line 202
   at Starcounter.Query.Execution.CodeGenFilterPrivate.GetFilterHandle() in C:\Proj\level1\src\Starcounter\Query\Execution\CodeGeneration\CodeGenFilterPrivate.cs:line 238
   at Starcounter.Query.Execution.FullTableScan.CreateEnumeratorWithNativeFilter() in C:\Proj\level1\src\Starcounter\Query\Execution\Enumerators\FullTableScan.cs:line 293
   at Starcounter.Query.Execution.FullTableScan.CreateEnumerator() in C:\Proj\level1\src\Starcounter\Query\Execution\Enumerators\FullTableScan.cs:line 402
   at Starcounter.Query.Execution.FullTableScan.MoveNext() in C:\Proj\level1\src\Starcounter\Query\Execution\Enumerators\FullTableScan.cs:line 411
   at Starcounter.QueryResultRows`1.get_First() in C:\Proj\level1\src\Starcounter\Query\SQL\SqlResultGeneric.cs:line 143
   at LogStreamer.LogStreamerSession.<SendLastPositions>b__126_0() in C:\Proj\LogStreamer\LogStreamerSession.cs:line 672
   at Starcounter.Db.Transact(Action action, UInt32 flags, TransactOptions opts) in C:\Proj\level1\src\Starcounter\Db.cs:line 287
   at Starcounter.Db.Advanced.Transact(TransactOptions opts, Action action) in C:\Proj\level1\src\Starcounter\Db.cs:line 233
   at Starcounter.Db.Transact(Action action, Boolean forceSnapshot, Int32 maxRetries) in C:\Proj\level1\src\Starcounter\Db.cs:line 207
   at LogStreamer.LogStreamerSession.SendLastPositions() in C:\Proj\LogStreamer\LogStreamerSession.cs:line 669
   at LogStreamer.LogStreamerSession.ProcessStringMessage(String message) in C:\Proj\LogStreamer\LogStreamerSession.cs:line 608
```

The query in question at `LogStreamerSession.cs` line 672 is:

`LastPosition dbRepl = Db.SQL<LastPosition>("SELECT p FROM LogStreamer.LastPosition p WHERE p.TableId = ?", PeerTableIdPrefix).First;`

/cc @k-rus @alemoi

**Comment by alemoi** [comment]
Thanks for reporting. I will take a look at this one.

**Comment by alemoi** [comment]
Strange since this code was not touched for ages. I looked at it and seems the filter is generated too many times for this query by some reason. Maximum number of filters is 4 now. Is it possible for you to put the breakpoint in CodeGeneration\CodeGenFilterCache.cs line 95? I can sit with you and see why.

**Comment by alemoi** [comment]
@k-rus do we have a test that does Db.SQL with code generation on many schedulers, like the SQLCacheTrasher did before? We are worrying that SQL cache processing could have some race conditions (i.e. when executed on several schedulers at the same time).

**Comment by k-rus** [comment]
No, I am not aware about tests of SQL on several schedulers.

**Comment by alemoi** [comment]
Ok, but are there tests that ensure thread-safeness of Db.SQL calls that are executed simultaneously on different schedulers?

**Comment by k-rus** [comment]
> Ok, but are there tests that ensure thread-safeness of Db.SQL calls that are executed simultaneously on different schedulers?

To my knowledge old query processor and its cache were implemented to be thread safe and were tested on thread safety and usage on several threads. 

Those regression tests, which I am aware of, do not do tests on multiple schedulers and thus cannot check thread-safeness.

**Comment by alemoi** [comment]
Yes, that's correct. I thought that there could be changes in the meantime that caused thread-unsafeness.

**Comment by dan31** [comment]
Is that still a bug?

**Comment by linkdata** [comment]
Probably. Race conditions are hard to find.
