### ISSUE TITLE
ScErrUnhandledWeaverException (SCERR6066) when weaving locked file

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3411]
If an application change, and need to be re-weaved when restarted, and the executable file is locked by some other process, the error you see is unspecific and confusing.

```
System.Exception:  ScErrUnhandledWeaverException (SCERR6066): An unhandled, unidentified (non-Starcounter) exception occurred in the weaver. Version: 2.0.0. Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR6066. ---> System.IO.IOException: The process cannot access the file 'C:\Users\Per\Documents\Starcounter\Personal\Temp\abc\abc-20160301T095112231\weaver\A119CFFE94C5001FEE38722501EA391D727D7864\app.exe' because it is being used by another process.    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)    at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)    at Starcounter.Internal.Weaver.ScCopyTask.Execute() in C:\Users\Per\Git\Starcounter\Develop\Level1\src\scweaver\Starcounter.Internal.Weaver\ScCopyTask.cs:line 76    at PostSharp.Sdk.Extensibility.Project.ExecutePhase(String phase)    at PostSharp.Hosting.PostSharpObject.ExecuteProjects()    at PostSharp.Hosting.PostSharpObject.ProcessAssemblies(ModuleLoadStrategy[] modules)    at Starcounter.Weaver.CodeWeaver.Execute() in C:\Users\Per\Git\Starcounter\Develop\Level1\src\scweaver\CodeWeaver.cs:line 327    at Starcounter.Weaver.CodeWeaver.ExecuteCurrent(CodeWeaver weaver) in C:\Users\Per\Git\Starcounter\Develop\Level1\src\scweaver\CodeWeaver.cs:line 226    at Starcounter.Weaver.Program.ExecuteWeaveCommand(String inputDirectory, String outputDirectory, String cacheDirectory, String fileName, ApplicationArguments arguments) in C:\Users\Per\Git\Starcounter\Develop\Level1\src\scweaver\Program.cs:line 204    at Starcounter.Weaver.Program.ApplyOptionsAndExecuteGivenCommand(ApplicationArguments arguments) in C:\Users\Per\Git\Starcounter\Develop\Level1\src\scweaver\Program.cs:line 154    at Starcounter.Weaver.Program.Main(String[] args) in C:\Users\Per\Git\Starcounter\Develop\Level1\src\scweaver\Program.cs:line 36    --- End of inner exception stack trace ---
   at Starcounter.Server.WeaverService.LogAndRaiseExceptionFromFailingWeaver(ToolInvocationException e) in C:\Users\Per\Git\Starcounter\Develop\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 198
   at Starcounter.Server.WeaverService.Weave(String givenAssembly, String runtimeDirectory, Boolean disableEditionLibraries) in C:\Users\Per\Git\Starcounter\Develop\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 121
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.<>c__DisplayClass4_0.<Execute>b__2(CommandTask task) in C:\Users\Per\Git\Starcounter\Develop\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 99
   at Starcounter.Server.Commands.CommandProcessor.<>c__DisplayClass68_0.<WithinTask>b__0(CommandTask t) in C:\Users\Per\Git\Starcounter\Develop\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 483
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) in C:\Users\Per\Git\Starcounter\Develop\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 510
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Action`1 action) in C:\Users\Per\Git\Starcounter\Develop\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 482
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.Execute() in C:\Users\Per\Git\Starcounter\Develop\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 91
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\Users\Per\Git\Starcounter\Develop\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 298
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR6066
```

**Comment by andwah** [comment]
More info:

I got an exception in Main()  (it was a call to `DbMapping.MapDefault<Simplified.Ring2.Organization, Organization>();` that failed.

I removed that call and then i hit `F5` again and got `ScErrUnhandledWeaverException`
Did `staradmin kill all` Hit `F5` still `ScErrUnhandledWeaverException`

I run the tool 'Handle' (after i did `staradmin kill all`) as you suggested this is the relevant parts (i guess):

Look for the `warehouse` in the output below
```
msvsmon.exe pid: 27764 HEADSUTV19\Anders
    8: File  (---)   C:\Windows\System32
    C: File  (---)   C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.9600.18006_none_623f33d3ecbe86e8
   18: File  (---)   C:\Windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.9600.18123_none_932c6b81474ee6d2
  21C: Section       \BaseNamedObjects\__ComCatalogCache__
  24C: Section       \BaseNamedObjects\__ComCatalogCache__
  258: File  (---)   C:\Windows\Registration\R00000000000d.clb
  27C: File  (---)   C:\Users\Anders\Documents\Starcounter\Personal\Temp\warehouse\warehouse-20160229T230409341\weaver\6037754934068643BAA3129F3F785FB5EFBEDC1B\Warehouse.exe
  2A0: File  (---)   C:\github\Level1\bin\Debug\Starcounter.XSON.dll
  2F0: File  (---)   C:\github\Level1\bin\Debug\Starcounter.Internal.dll
  318: File  (---)   C:\github\Level1\bin\Debug\Starcounter.Apps.JsonPatch.dll
  340: File  (---)   C:\Users\Anders\Documents\Starcounter\Personal\Temp\warehouse\warehouse-20160229T230409341\weaver\6037754934068643BAA3129F3F785FB5EFBEDC1B\Simplified.Data.Model.dll
  3C4: File  (---)   C:\github\Level1\bin\Debug\Starcounter.dll
  4E4: File  (---)   C:\github\Level1\bin\Debug\Starcounter.Internal.dll
  624: Section       \BaseNamedObjects\Cor_Private_IPCBlock_v4_27764

```

**Comment by andwah** [comment]
ps. when i killed the `msvsmon.exe` process everything was back to normal.

**Comment by per-samuelsson** [comment]
Thanks a lot, @andwah. Then we are 100% this is caused by that locked file.

So its the bloody **remote debugger** that locks it on your machine! Have you used that recently? I was under the impression that thing don't just run by default, but maybe it does in some scenarios.

No matter what, we seem not to be the only people in the world having suffered from this: [Google "msvsmon.exe lock file"](https://www.google.se/search?q=msvsmon.exe&oq=msvsmon.exe&aqs=chrome..69i57j0l5.603j0j7&sourceid=chrome&es_sm=93&ie=UTF-8#q=msvsmon.exe+lock+file).

Not sure exactly what action I should take here long term. I need to consider this some. But thanks again for providing all the valuable feedback.

**Comment by andwah** [comment]
> Remote debugger, 
Have you used that recently?

Not that im aware of, but i use `Remote Desktop` to work on my machine.

**Comment by andwah** [comment]
> Not sure exactly what action I should take here long term.

Short term, check if files are locked, if so. generate new ones,  it's only temp files right and they can be regenerated right?

**Comment by per-samuelsson** [comment]
> Short term, check if files are locked, if so. generate new ones, it's only temp files right and they can be regenerated right?

Nah, unfortunately not. They are the files that represent the actual running application, after we have fully prepared it. So it's not that simple. Some kind of solution in that direction is certainly *doable*, just that it's not a quick fix. More like a day of work I think.

Anyway, I don't think its a high prio right now, like not at the top of our list or anything. Let me consider it some more and see where and when we should fix it.
