### ISSUE TITLE
Exception SCERR6066: PostSharp.Sdk.CodeModel.BindingException: Cannot find the type 'System.Runtime.Versioning.TargetFrameworkAttribute' in assembly 'mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#3413]
I am trying to debug @malx122 problem with Stacounter nightly/Polymer 1.3, but I cannot start his application.

This is the stack trace that I get when trying to start the program:

```txt
"ScErrWeavingError (SCERR2030): At least one error has been detected during weaving of the application code. Process exit code: 6066.
Arguments=--nocache --maxerrors=1 --ErrorParcelId=A4A7D6FA-EB34-442A-B579-DBB1DBB859E3 Weave ""c:\www\	unity\Tunity-3\Tunity.UserManagement\bin\Debug\	unity_users.exe"" --outdir=""c:\db\Personal\Temp\Default\Default-20160301T151612902\weaver\D3B11E787AFE67A3EA5D0E6F6D9D8218C2EDA9E2""
Output:
A4A7D6FA-EB34-442A-B579-DBB1DBB859E3System.Exception: ScErrUnhandledWeaverException (SCERR6066): An unhandled, unidentified (non-Starcounter) exception occurred in the weaver.
Version: 2.1.1316.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR6066. ---> PostSharp.Sdk.CodeModel.BindingException: Cannot find the type 'System.Runtime.Versioning.TargetFrameworkAttribute' in assembly 'mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at PostSharp.Sdk.CodeModel.AssemblyEnvelope.GetTypeDefinition(String typeName, BindingOptions bindingOptions)
   at PostSharp.Sdk.CodeModel.TypeRefDeclaration.GetTypeDefinition(BindingOptions bindingOptions)
   at PostSharp.Sdk.Extensibility.Tasks.AnnotationRepositoryTask.^wwGmHrz+(IAnnotationInstance _0)
   at PostSharp.Sdk.Extensibility.Tasks.AnnotationRepositoryTask.Execute()
   at PostSharp.Sdk.Extensibility.Project.ExecutePhase(String phase)
   at PostSharp.Hosting.PostSharpObject.ExecuteProjects()
   at PostSharp.Hosting.PostSharpObject.ProcessAssemblies(ModuleLoadStrategy[] modules)
   at Starcounter.Weaver.CodeWeaver.Execute() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-203\Level1\src\scweaver\CodeWeaver.cs:line 327
   at Starcounter.Weaver.CodeWeaver.ExecuteCurrent(CodeWeaver weaver) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-203\Level1\src\scweaver\CodeWeaver.cs:line 226
   at Starcounter.Weaver.Program.ExecuteWeaveCommand(String inputDirectory, String outputDirectory, String cacheDirectory, String fileName, ApplicationArguments arguments) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-203\Level1\src\scweaver\Program.cs:line 205
   at Starcounter.Weaver.Program.ApplyOptionsAndExecuteGivenCommand(ApplicationArguments arguments) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-203\Level1\src\scweaver\Program.cs:line 156
   at Starcounter.Weaver.Program.Main(String[] args) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-203\Level1\src\scweaver\Program.cs:line 36
   --- End of inner exception stack trace ---A4A7D6FA-EB34-442A-B579-DBB1DBB859E3
System.Exception: ScErrUnhandledWeaverException (SCERR6066): An unhandled, unidentified (non-Starcounter) exception occurred in the weaver.
Version: 2.1.1316.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR6066. ---> PostSharp.Sdk.CodeModel.BindingException: Cannot find the type 'System.Runtime.Versioning.TargetFrameworkAttribute' in assembly 'mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at PostSharp.Sdk.CodeModel.AssemblyEnvelope.GetTypeDefinition(String typeName, BindingOptions bindingOptions)
   at PostSharp.Sdk.CodeModel.TypeRefDeclaration.GetTypeDefinition(BindingOptions bindingOptions)
   at PostSharp.Sdk.Extensibility.Tasks.AnnotationRepositoryTask.^wwGmHrz+(IAnnotationInstance _0)
   at PostSharp.Sdk.Extensibility.Tasks.AnnotationRepositoryTask.Execute()
   at PostSharp.Sdk.Extensibility.Project.ExecutePhase(String phase)
   at PostSharp.Hosting.PostSharpObject.ExecuteProjects()
   at PostSharp.Hosting.PostSharpObject.ProcessAssemblies(ModuleLoadStrategy[] modules)
   at Starcounter.Weaver.CodeWeaver.Execute() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-203\Level1\src\scweaver\CodeWeaver.cs:line 327
   at Starcounter.Weaver.CodeWeaver.ExecuteCurrent(CodeWeaver weaver) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-203\Level1\src\scweaver\CodeWeaver.cs:line 226
   at Starcounter.Weaver.Program.ExecuteWeaveCommand(String inputDirectory, String outputDirectory, String cacheDirectory, String fileName, ApplicationArguments arguments) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-203\Level1\src\scweaver\Program.cs:line 205
   at Starcounter.Weaver.Program.ApplyOptionsAndExecuteGivenCommand(ApplicationArguments arguments) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-203\Level1\src\scweaver\Program.cs:line 156
   at Starcounter.Weaver.Program.Main(String[] args) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-203\Level1\src\scweaver\Program.cs:line 36
   --- End of inner exception stack trace ---

Version: 2.1.1316.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR2030."
```

I am stuck on this. Help appreciated.

**Comment by warpech** [comment]
cc @per-samuelsson

**Comment by per-samuelsson** [comment]
@warpech 

Don't have more than like a minute now, but very likely to do with some deviation in installed .NET framework between your env and his. Kind of weird though, I must admit.

https://www.google.se/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=targetframeworkattribute%20attribute%20not%20found

I'll get back on it later or tomorrow if you are still stuck.

**Comment by per-samuelsson** [comment]
Any news on this @warpech?

If you can't resolve it, could you give me access to the failing application and I can set up a local environment on my end and do some testing?

**Comment by warpech** [comment]
No news :(

I am running Windows 10. Please let me know if I can provide more details.

I will ask @malx122 to give you access

**Comment by per-samuelsson** [comment]
@warpech 

After setting up that environment locally, and diagnosing the weaver, I found I could successfully weave the application if I added `Microsoft.VisualStudio.QualityTools.UnitTestFramework.dll` to the `weaver.ignore`. It's some reference from there that failed.

Try that, please.

Meanwhile, I'll take a look if the user experience can be improved, and add it to the pile of other such issues that we never get the time to address. :sunglasses:

**Comment by warpech** [comment]
Yeah, it worked! Thanks!

**Comment by per-samuelsson** [comment]
> Yeah, it worked! Thanks!

Good. Not very happy myself though, since UX here is obv extremely unsatisfying. But I'm glad you could get back doing your thing.

Also, don't forget to promote that to Tunity guys, since they would want to update their master copy of weaver.ignore with that for sure.

**Comment by warpech** [comment]
Any idea why it works OK for them?

**Comment by per-samuelsson** [comment]
> Any idea why it works OK for them?

Most likely because they have installed some software that unit-testing library reference, and hence all dependencies from it can be resolved on their environments, while you and I don't have that on ours. The weaver depend on that all references from any assembly it process must be resolvable. And the way to relax that is to include them in the ignore file.

**Comment by per-samuelsson** [comment]
I'm currently investigating how we can improve the UX, like I wrote above. 

Since the weaver is really a low-level tool, and normally invoked by a server, it's a bit hard to revolutionize it without doing a largish redesign on how this whole chain of operations come together, and I think we can't afford that kind of effort right now. In the upcoming DNX-weaver, we should design with this in mind from the beginning.

WTBS, I'll try to suggest a few things that could at least help users help themselves a little better, even if that mean they have to switch to tooling. If we would have that, we could hint about some "How to diagnose ..."-guide in any similar errors, and users could give it a try.

I'll open up a new issue (or issues) for that. Closing this one.

**Comment by k-rus** [comment]
I was hit by exactly this usability issue and took me a lot of time to understand the problem that I was missing an installation of a software. (do you remember @per-samuelsson , I was buzzering with this in chat)

**Comment by per-samuelsson** [comment]
> I was hit by exactly this usability issue and took me a lot of time to understand the problem that I was missing an installation of a software.

Yeah, and there are three inherit problems here that make this (and similar issues) complex to "solve" without a largish redesign:

1. The weaver is pretty much a blackbox
2. The weaver is invoked somewhat deep in the tooling chain: (process) star (IPC ->) (process) admin server (IPC ->) (process) weaver (-> unhandled exception)
3. Exception in dependency resolving comes from underlying PostSharp, and exception don't indicate what assembly referenced the failing dependency, it pretty much hit us with only the info that is already shown in the initial post (message + stacktrace)

What I'm currently thinking about is to support some kind of simple guide and a convenience CLI for the weaver to write out diagnostic information. So that when this kind of error occur, we point the user to a guide that basically ask them to

1. Open a prompt
2. Run ```app-diag path\to\app.exe```

and `app-diag` is basically just wrapping a call to `scweaver --nocache --verbosity=diagnostic path\to\app.exe` and we extend what we output there a little further, to include stuff such as what files are actually considered, which files have been ignored by `weaver.ignore`, all paths we use to resolve dependencies, etc.
