### ISSUE TITLE
pnext: PnextDailyWindows doesn't build

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3422]
Seem to be since sometime yesterday, and what I can get from the logs it's the below failing.

Build server report this as the first failure:
First failure: #2.3.956 	const.miyang (2) 	02 Mar 16 14:27

@miyconst, any ideas? Did you explicitly merge that new thing you pushed yesterday into **pnext** and if so, did you run the personal build first?

```
[00:20:19][dbmapping_test-bat] -- Running process "C:\BuildAgent\work\sc-1917\Level1\src\Starcounter.Extensions.Tests\dbmapping_test.bat "
[00:20:19][dbmapping_test-bat] 
[00:20:19][dbmapping_test-bat] C:\BuildAgent\work\sc-1917\Level1\src\Starcounter.Extensions.Tests>set DBNAME=DbMappingTestsDb 
[00:20:19][dbmapping_test-bat] 
[00:20:19][dbmapping_test-bat] C:\BuildAgent\work\sc-1917\Level1\src\Starcounter.Extensions.Tests>staradmin start server 
[00:20:22][dbmapping_test-bat] 
[00:20:22][dbmapping_test-bat] C:\BuildAgent\work\sc-1917\Level1\src\Starcounter.Extensions.Tests>staradmin --database=DbMappingTestsDb delete --force db 
[00:20:23][dbmapping_test-bat] Database DbMappingTestsDb successfully deleted
[00:20:23][dbmapping_test-bat] 
[00:20:23][dbmapping_test-bat] C:\BuildAgent\work\sc-1917\Level1\src\Starcounter.Extensions.Tests>IF 0 NEQ 0 GOTO FAILED 
[00:20:23][dbmapping_test-bat] 
[00:20:23][dbmapping_test-bat] C:\BuildAgent\work\sc-1917\Level1\src\Starcounter.Extensions.Tests>star.exe --database=DbMappingTestsDb "C:\BuildAgent\work\sc-1917\Level1\Bin\Release\s\ExtensionsTests\StarcounterExtensionsTests.exe" 
[00:21:05][dbmapping_test-bat] 
[00:21:05][dbmapping_test-bat] [00:20:41, Critical, Starcounter (dbmappingtestsdb)]
[00:21:05][dbmapping_test-bat] Starcounter.DbException: ScErrFailingEntrypoint (SCERR4259): The user code entrypoint method raised an exception. System.TypeInitializationException: The type initializer for 'Starcounter.Extensions.ModificationMapGenerator' threw an exception. ---> System.Reflection.AmbiguousMatchException: Ambiguous match found.
[00:21:05][dbmapping_test-bat]    at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
[00:21:05][dbmapping_test-bat]    at System.Type.GetMethod(String name, BindingFlags bindingAttr)
[00:21:05][dbmapping_test-bat]    at Starcounter.Extensions.ModificationMapGenerator..cctor() in C:\BuildAgent\work\sc-1917\Level1\src\Starcounter.Extensions\ModificationMapGenerator.cs:line 19
[00:21:05][dbmapping_test-bat]    --- End of inner exception stack trace ---
[00:21:05][dbmapping_test-bat]    at Starcounter.Extensions.ModificationMapGenerator.Create[TFrom,TTo]() in C:\BuildAgent\work\sc-1917\Level1\src\Starcounter.Extensions\ModificationMapGenerator.cs:line 63
[00:21:05][dbmapping_test-bat]    at Starcounter.Extensions.DbMapping.MapDefault[TFrom,TTo](Boolean twoWay) in C:\BuildAgent\work\sc-1917\Level1\src\Starcounter.Extensions\DatabaseMapping.cs:line 297
[00:21:05][dbmapping_test-bat]    at DbMappingTest.DbMappingTest.Main() in C:\BuildAgent\work\sc-1917\Level1\src\Starcounter.Extensions.Tests\DbMappingTest.cs:line 780
[00:21:05][dbmapping_test-bat] Version: 2.3.959.
[00:21:05][dbmapping_test-bat] Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4259.
[00:21:05][dbmapping_test-bat]    at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application) in C:\BuildAgent\work\sc-1917\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 513
[00:21:05][dbmapping_test-bat]    at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application) in C:\BuildAgent\work\sc-1917\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 261
[00:21:05][dbmapping_test-bat]    at Starcounter.Hosting.Package.Process() in C:\BuildAgent\work\sc-1917\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 143
[00:21:05][dbmapping_test-bat]    at Starcounter.Hosting.Package.Process(IntPtr hPackage) in C:\BuildAgent\work\sc-1917\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 56
[00:21:05][dbmapping_test-bat]    at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\BuildAgent\work\sc-1917\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 86
[00:21:05][dbmapping_test-bat] ErrorCode=4259
[00:21:05][dbmapping_test-bat] HResult=-2146233088
[00:21:05][dbmapping_test-bat] HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4259
[00:21:05][dbmapping_test-bat] ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
[00:21:05][dbmapping_test-bat]    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
[00:21:05][dbmapping_test-bat]    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
[00:21:05][dbmapping_test-bat]    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[00:21:05][dbmapping_test-bat]    at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application) in C:\BuildAgent\work\sc-1917\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 487
[00:21:05][dbmapping_test-bat] HResult=-2146232828
[00:21:05][dbmapping_test-bat] ---> System.TypeInitializationException: The type initializer for 'Starcounter.Extensions.ModificationMapGenerator' threw an exception.
[00:21:05][dbmapping_test-bat]    at Starcounter.Extensions.ModificationMapGenerator.Create[TFrom,TTo]() in C:\BuildAgent\work\sc-1917\Level1\src\Starcounter.Extensions\ModificationMapGenerator.cs:line 63
[00:21:05][dbmapping_test-bat]    at Starcounter.Extensions.DbMapping.MapDefault[TFrom,TTo](Boolean twoWay) in C:\BuildAgent\work\sc-1917\Level1\src\Starcounter.Extensions\DatabaseMapping.cs:line 297
[00:21:05][dbmapping_test-bat]    at DbMappingTest.DbMappingTest.Main() in C:\BuildAgent\work\sc-1917\Level1\src\Starcounter.Extensions.Tests\DbMappingTest.cs:line 780
[00:21:05][dbmapping_test-bat] TypeName=Starcounter.Extensions.ModificationMapGenerator
[00:21:05][dbmapping_test-bat] HResult=-2146233036
[00:21:05][dbmapping_test-bat] ---> System.Reflection.AmbiguousMatchException: Ambiguous match found.
[00:21:05][dbmapping_test-bat]    at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
[00:21:05][dbmapping_test-bat]    at System.Type.GetMethod(String name, BindingFlags bindingAttr)
[00:21:05][dbmapping_test-bat]    at Starcounter.Extensions.ModificationMapGenerator..cctor() in C:\BuildAgent\work\sc-1917\Level1\src\Starcounter.Extensions\ModificationMapGenerator.cs:line 19
[00:21:05][dbmapping_test-bat] HResult=-2147475171
[00:21:05][dbmapping_test-bat] 
[00:21:05][dbmapping_test-bat] 
[00:21:05][dbmapping_test-bat] 
[00:21:05][dbmapping_test-bat] C:\BuildAgent\work\sc-1917\Level1\src\Starcounter.Extensions.Tests>IF 4259 NEQ 0 GOTO FAILED 
[00:21:05][dbmapping_test-bat] 
[00:21:05][dbmapping_test-bat] C:\BuildAgent\work\sc-1917\Level1\src\Starcounter.Extensions.Tests>ECHO Exiting test with error code ! 
[00:21:05][dbmapping_test-bat] Exiting test with error code !
[00:21:05][dbmapping_test-bat] 
[00:21:05][dbmapping_test-bat] C:\BuildAgent\work\sc-1917\Level1\src\Starcounter.Extensions.Tests>EXIT /b 1 
[00:21:05][dbmapping_test-bat] Test failed: "dbmapping_test.bat" at "C:\BuildAgent\work\sc-1917\Level1\src\Starcounter.Extensions.Tests\dbmapping_test.bat" with error code 1.
[00:21:05][dbmapping_test-bat] -- Running process "staradmin kill all"
[00:21:05][dbmapping_test-bat] System.Exception: Test failed: "dbmapping_test.bat" at "C:\BuildAgent\work\sc-1917\Level1\src\Starcounter.Extensions.Tests\dbmapping_test.bat" with error code 1.
[00:21:05][dbmapping_test-bat]    at TestRunner.TestRunner.RunTests(String pathToCheckoutDir, TestTypes testType, List`1 testsToSkip, Dictionary`2 longTestsDurationsSeconds, Boolean continueTestsAfterFirstFail) in C:\BuildAgent\work\sc-1917\BuildSystem\src\TestRunner\TestRunner.cs:line 467
[00:21:05][dbmapping_test-bat] 00:20:42.5953393: process 'scservice' successfully killed!
[00:21:05][dbmapping_test-bat] 00:20:42.5994516: process 'scipcmonitor' successfully killed!
[00:21:05][dbmapping_test-bat] 00:20:42.5994516: process 'scnetworkgateway' successfully killed!
[00:21:05][dbmapping_test-bat] 00:20:42.6004806: process 'scadminserver' successfully killed!
[00:21:05][dbmapping_test-bat] 00:20:42.6015100: process 'sccode' successfully killed!
[00:21:05][dbmapping_test-bat] 00:20:42.6025385: process 'scdata' successfully killed!
[00:21:05][dbmapping_test-bat] 00:20:42.6035813: process 'scdblog' successfully killed!
[00:21:05][dbmapping_test-bat] 00:20:42.6056333: process 'scsqlparser' successfully killed!
[00:21:05][dbmapping_test-bat] 00:20:42.6067179: process 'sctrayicon' successfully killed!
[00:21:05][dbmapping_test-bat] -- Running test "3LevelSchemaChange_test.bat" (max duration: 120 s) at "C:\BuildAgent\work\sc-1917\Level1\src\Tests\3LevelSchemaChange\3LevelSchemaChange_test.bat"
[00:21:06][dbmapping_test-bat] 3LevelSchemaChange_test-bat (1m:06s)
[00:21:06][3LevelSchemaChange_test-bat] -- Running process "C:\BuildAgent\work\sc-1917\Level1\src\Tests\3LevelSchemaChange\3LevelSchemaChange_test.bat "
[00:21:06][3LevelSchemaChange_test-bat] Running 3LevelSchemaChange regression test.
[00:21:11][3LevelSchemaChange_test-bat] Database 3LevelSchemaChangeDb successfully deleted
[00:21:11][3LevelSchemaChange_test-bat] Run Step 1 to create initial schema
[00:21:37][3LevelSchemaChange_test-bat] Run Step 2 to update the initial schema with more columns
[00:21:56][3LevelSchemaChange_test-bat] Run Step 1 again to update the schema with less columns
[00:22:13][3LevelSchemaChange_test-bat] Database 3LevelSchemaChangeDb successfully deleted
[00:22:13][3LevelSchemaChange_test-bat] 3LevelSchemaChange regression test succeeded.
[00:22:13][dbmapping_test-bat] -- Running process "staradmin kill all"
[00:22:13][dbmapping_test-bat] 00:21:49.9027287: process 'scservice' successfully killed!
[00:22:13][dbmapping_test-bat] 00:21:49.9058060: process 'scipcmonitor' successfully killed!
[00:22:13][dbmapping_test-bat] 00:21:49.9058060: process 'scnetworkgateway' successfully killed!
[00:22:13][dbmapping_test-bat] 00:21:49.9068332: process 'scadminserver' successfully killed!
[00:22:13][dbmapping_test-bat] 00:21:49.9099342: process 'scsqlparser' successfully killed!
[00:22:13][dbmapping_test-bat] 00:21:49.9111397: process 'sctrayicon' successfully killed!
[00:22:13][dbmapping_test-bat] -- Running test "ClassSchemaChange_test.bat" (max duration: 60 s) at "C:\BuildAgent\work\sc-1917\Level1\src\Tests\ClassSchemaChange\ClassSchemaChange_test.bat"
[00:22:14][dbmapping_test-bat] ClassSchemaChange_test-bat (49s)
[00:22:14][ClassSchemaChange_test-bat] -- Running process "C:\BuildAgent\work\sc-1917\Level1\src\Tests\ClassSchemaChange\ClassSchemaChange_test.bat "
[00:22:14][ClassSchemaChange_test-bat] Running TestClassSchemaChange regression test.
[00:22:18][ClassSchemaChange_test-bat] Database ClassSchemaChangeDb successfully deleted
[00:22:18][ClassSchemaChange_test-bat] Run Step 1 to create initial schema
[00:22:44][ClassSchemaChange_test-bat] Run Step 2 to update initial schema with more columns
[00:23:03][ClassSchemaChange_test-bat] Database ClassSchemaChangeDb successfully deleted
[00:23:03][ClassSchemaChange_test-bat] ClassSchemaChange regression test succeeded.
[00:23:04][dbmapping_test-bat] 
[00:23:04][dbmapping_test-bat] C:\BuildAgent\work\sc-1917\Level1\bin\Release>IF ERRORLEVEL 1 GOTO FAILED 
[00:23:04][dbmapping_test-bat] 
[00:23:04][dbmapping_test-bat] C:\BuildAgent\work\sc-1917\Level1\bin\Release>ECHO Generating documentation. 
[00:23:04][dbmapping_test-bat] Generating documentation.
[00:23:04][dbmapping_test-bat] 
[00:23:04][dbmapping_test-bat] C:\BuildAgent\work\sc-1917\Level1\bin\Release>PUSHD "C:\BuildAgent\work\sc-1917/Level1/src/BuildSystem/Documentation" 
[00:23:04][dbmapping_test-bat] 
[00:23:04][dbmapping_test-bat] C:\BuildAgent\work\sc-1917\Level1\src\BuildSystem\Documentation>CALL "C:\BuildAgent\work\sc-1917/Level1/src/BuildSystem/Documentation/generate_all.bat" 
[00:23:04][dbmapping_test-bat] Executing post build tasks.
[00:23:04][dbmapping_test-bat] 00:22:41.8182446: process 'scservice' successfully killed!
[00:23:04][dbmapping_test-bat] 00:22:41.8202984: process 'scipcmonitor' successfully killed!
[00:23:04][dbmapping_test-bat] 00:22:41.8213235: process 'scnetworkgateway' successfully killed!
[00:23:04][dbmapping_test-bat] 00:22:41.8223522: process 'scadminserver' successfully killed!
[00:23:04][dbmapping_test-bat] 00:22:41.8264663: process 'scsqlparser' successfully killed!
[00:23:05][dbmapping_test-bat] 00:22:41.8265007: process 'sctrayicon' successfully killed!
[00:23:05][dbmapping_test-bat] Cleaning output directory using white list...
[00:23:06][dbmapping_test-bat] Generating one-file installer for Starcounter edition.
[00:23:06][dbmapping_test-bat] ---------------------------------------------------------------
[00:23:06][dbmapping_test-bat] Starting tool: 'Starting Starcounter installer generator...'
[00:23:06][dbmapping_test-bat] Skipping generation of a installer...
[00:23:06][dbmapping_test-bat] Copying built Level0 binaries.
[00:23:07][dbmapping_test-bat] ---------------------------------------------------------------
[00:23:07][dbmapping_test-bat] Starting tool: 'Level0 Build'
[00:23:07][dbmapping_test-bat] Uploading Level0 'pnext' build artifacts to mapped FTP directory: 'Z:\SCBuilds\Level0\pnext\LatestStable'
[00:23:14][dbmapping_test-bat] Updating Error Help Pages on Github wiki.
[00:23:14][dbmapping_test-bat] Skipping updating error pages...
[00:23:14][dbmapping_test-bat] Switching back to build output directory.
[00:23:14][dbmapping_test-bat] Process exited with code 0
[00:23:14][dbmapping_test-bat] ##teamcity[buildStatisticValue key='buildStageDuration:buildStepRUNNER_9' value='1092427.0']
```

**Comment by per-samuelsson** [comment]
I did some investigation, and this is a result of that `DbHelper.FromID` overload for sure.

Take a look at this expression (part of **pnext**, and ran in the tests):
https://github.com/Starcounter/Starcounter/blob/pnext/src/Starcounter.Extensions/ModificationMapGenerator.cs#L19

```cs
private static MethodInfo fromIDMethod = typeof(DbHelper).GetMethod("FromID", BindingFlags.Static | BindingFlags.Public);
```

That one will be ambiguous as soon as any overload is introduced, and hence this is what blows up:

```
[00:21:05][dbmapping_test-bat] The type initializer for 'Starcounter.Extensions.ModificationMapGenerator' threw an exception. ---> System.Reflection.AmbiguousMatchException: Ambiguous match found.
```

cc @alemoi @miyconst, either that code has to be redesigned, or the overload removed.

Let me know if I can be of any help!

**Comment by alemoi** [comment]
I guess I have to read another thread to understand the thing about FromID changes.

**Comment by alemoi** [comment]
I wasn't familiar with that code @per-samuelsson so I looked at the history and I found that @chrhol wrote it. @chrhol can you please check?

**Comment by per-samuelsson** [comment]
> I wasn't familiar with that code (ModificationMapGenerator.cs) @per-samuelsson so I looked at the history and I found that @chrhol wrote it. @chrhol can you please check?

Aha, sorry, I thought it was you that wrote it.

If we want to keep that overload @miyconst submitted, I guess what we have to do is to make the code more specific when binding to it, specifying what overload to grab.

**Comment by alexanderstc** [comment]
> If we want to keep that overload @miyconst submitted

Could you guys do your consideration on a branch other than pnext please?

**Comment by k-rus** [comment]
According to git history and teamcity history the breaking change was commited by @miyconst without testing in personal branch, which is against our policy. Any pushes to non-personal branches such as `develop` and `pnext` should be guarded with running personal builds on personal branch. (we want to automate this, but don't have resources to fix it). As I see in the history many developers do not run personal builds before pushing changes into public branches. This impede other developers.

I don't know if @chrhol is available, thus
@miyconst can you take responsibility to fix pnext as soon as possible? For example, by reverting your breaking change in develop and pnext.

**Comment by miyconst** [comment]
@k-rus, @per-samuelsson, @alemoi, @chrhol, @alexanderstc I apologize for this issue.

I have removed the `FromID(string oid)` overload from both of the branches, and won't push any changes to Starcounter till I have environment to build and test it locally.

**Comment by per-samuelsson** [comment]
@miyconst 

Nice. And don't worry, it can happen to the best of us. :smile: 

> [...] and won't push any changes to Starcounter till I have environment to build and test it locally.

Let me know if I can help you set something like that up! 

And on a related note: you can actually do fine without a local install for simpler cases and as long as you just define some test. Then you can just host it in a branch, and give it to the build server to test it, and if it works, you're good to go. Same thing there: if you are interested, I'll happily give you a tour on how to do that!

**Comment by miyconst** [comment]
>if you are interested, I'll happily give you a tour on how to do that!

Yes definitely. Will approach you on Monday.

**Comment by per-samuelsson** [comment]
> Will approach you on Monday.

Cool. The prerequisite is you can access the build server from your box, requiring a VPN if your not connected to the network. Ping `teamcity.starcounter.org` to see you can do that (require that the DNS recognize it, or its in your hosts file).

**Comment by per-samuelsson** [comment]
Confirmed it builds now btw, lets close this one down.

**Comment by alemoi** [comment]
Welcome to the team @miyconst :D
Happened many times for all of us :)

> Yes definitely. Will approach you on Monday.

I can give you a lecture, guys.

**Comment by alexanderstc** [comment]
FFS

**Comment by miyconst** [comment]
>FFS

What is up this time?

**Comment by alexanderstc** [comment]
Probably a re-merge of the problematic code.

**Comment by k-rus** [comment]
> Probably a re-merge of the problematic code.

@alexanderstc It is good if you look to actual error in the log. If it is the error due to this issue, then it is good to reopen. Otherwise it is much better if you open another issue.

The actual error in the log is:

>[16:20:04][Step 1/1] C:\TeamCity\TeamCity9\buildAgent\work\sc-1924\Level0\src\include\sccoreerr.h(8): fatal error C1083: Cannot open include file: 'sccoreerr_internal.h': No such file or directory [C:\TeamCity\TeamCity9\buildAgent\work\sc-1924\Level0\cmake_vs2015\src\tests\ucs2_unittest\ucs2_unittest.vcxproj]

and build fails.

It is not the same issue.
I close this issue.

@alexanderstc 
It is great that you noticed the build fail. Please, report this in a separate issue.

**Comment by alexanderstc** [comment]
Let's wait and see if the re-build succeeds.

**Comment by alexanderstc** [comment]
It did succeed, so it was just another one of those build server mood swings.
Great, no need for the new issue.
