### ISSUE TITLE
Invalid SQL IS execution

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3424]
In SweOffshore we have two classes: `Simplified.Ring2.Person : Simplified.Ring2.Somebody`, `SweOffshore.Person : Simplified.Ring2.Person`.

I try to execute a query:

```sql
SELECT c.Person 
FROM Simplified.Ring2.OrganizationPerson c 
WHERE c.Person IS Sweoffshore.Person AND c.Organization = ?
```

The query goes fine in the administrator, but fails from c#:

```cs
vare people = Db.SQL<SweOffshore.Person>("SELECT c.Person FROM Simplified.Ring2.OrganizationPerson c WHERE c.Person IS Sweoffshore.Person AND c.Organization = ?", CurrentOrganization);
```

But it throws the following exception:

```
"System.Exception: ScErrQueryResultTypeMismatch (SCERR7031): Expected generic result type does not match with query result type. The result type Sweoffshore.Person cannot be assigned from the query result, which is of type Simplified.Ring2.Person.
Version: 2.3.797.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR7031.
   at Starcounter.Query.QueryPreparation.MatchEnumeratorResultAndExpectedType[T](IExecutionEnumerator execEnum) in C:\TeamCity\TeamCity9\buildAgent\work\sc-53\Level1\src\Starcounter\Query\QueryPreparation.cs:line 117
   at Starcounter.Query.QueryPreparation.PrepareOrExecuteQuery[T](String query, Boolean slowSql, Object[] values) in C:\TeamCity\TeamCity9\buildAgent\work\sc-53\Level1\src\Starcounter\Query\QueryPreparation.cs:line 88
   at Starcounter.Query.Sql.SqlEnumCache.CacheOrExecuteEnumerator[T](String query, Boolean slowSQL, Object[] values) in C:\TeamCity\TeamCity9\buildAgent\work\sc-53\Level1\src\Starcounter\Query\SQL\_SqlEnumCache.cs:line 127
   at Starcounter.Db.FullQueryProcess[T](String query, Boolean slowSQL, Object[] values) in C:\TeamCity\TeamCity9\buildAgent\work\sc-53\Level1\src\Starcounter\Mock\Db.cs:line 128
   at PeopleOnboard.ViewModel.CrewPage.RefreshPersons() in E:\GitHub\SweOffshore\SweOffshore\Sweoffshore\PeopleOnboard\ViewModel\Crew\CrewPage.json.cs:line 108
   at PeopleOnboard.ViewModel.CrewPage.Handle(SelectPersonClick Action) in E:\GitHub\SweOffshore\SweOffshore\Sweoffshore\PeopleOnboard\ViewModel\Crew\CrewPage.json.cs:line 281
   at PeopleOnboard.ViewModel.CrewPage.JsonByExample.Schema.<>c.<.ctor>b__0_39(Json pup, Input`1 input) in E:\GitHub\SweOffshore\SweOffshore\Sweoffshore\PeopleOnboard\obj\x64\Debug\ViewModel\Crew\CrewPage.json.g.cs:line 0
   at Starcounter.Templates.Property`1.InvokeHandler(Json parent, Input`1 input) in C:\TeamCity\TeamCity9\buildAgent\work\sc-53\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 225
   at Starcounter.Templates.Property`1.ProcessInput(Json parent, T value) in C:\TeamCity\TeamCity9\buildAgent\work\sc-53\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 247
   at Starcounter.XSON.DefaultPatchHandler.ParseAndProcess(TLong property, Json parent, IntPtr valuePtr, Int32 valueSize) in C:\TeamCity\TeamCity9\buildAgent\work\sc-53\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 105
   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\TeamCity\TeamCity9\buildAgent\work\sc-53\Level1\src\Starcounter\TransactionManager.cs:line 463
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\TeamCity9\buildAgent\work\sc-53\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 27
   at Starcounter.XSON.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, IntPtr valuePtr, Int32 valueSize) in C:\TeamCity\TeamCity9\buildAgent\work\sc-53\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 37
   at Starcounter.XSON.JsonPatch.Apply(Json root, IntPtr patchArrayPtr, Int32 patchArraySize, Boolean strictPatchRejection) in C:\TeamCity\TeamCity9\buildAgent\work\sc-53\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 638
   at Starcounter.Internal.PuppetRestHandler.<>c.<RegisterJsonPatchHandlers>b__4_0(Session session, Request request) in C:\TeamCity\TeamCity9\buildAgent\work\sc-53\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 100
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\TeamCity9\buildAgent\work\sc-53\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 161
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-53\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-53\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 560
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR7031
"
```

![image](https://cloud.githubusercontent.com/assets/6435556/13520169/460bdffe-e1de-11e5-9850-594090451ca7.png)

All of the selected items in the query are `Sweoffshore.Person`, but I still can't select it as a `QueryResultRow<Sweoffshore.Person>`.

**Comment by k-rus** [comment]
Thank you for your question. WHERE clause is responsible for selection condition. The comparison of the types is done at query compilation time by comparing generic type and result type.

Administrator does not fail because it does not use generics.

In your example, you can use matching generic and then cast it to needed type using C# casting facility or redesign the query to select the expected type.

**Comment by miyconst** [comment]
So, there is no way or plan to fix it on Starcounter level?

**Comment by k-rus** [comment]
> So, there is no way or plan to fix it on Starcounter level?

In my opinion such problems solved by improving the design of applications. Your example is exactly case for `SynonymousTo`.

Furthermore, C# will also fail in your case, since the types are not fully compatible. Explicit casting is required. By the way, you can try to use [cast](http://starcounter.io/guides/sql/cast-operation/) in your query.

So the answer is NO due to many reasons and also least surprise.

**Comment by miyconst** [comment]
Okay, then I close the issue as won't fixed. I know I can cast the values after the query completed.

**Comment by k-rus** [comment]
> Okay, then I close the issue as won't fixed.

I guess I didn't explain well the problem of your proposal, otherwise `won't fix` term is incorrect here.
I don't really see that it is good to include implicit cast in the situation where explicit cast is required.

**Comment by miyconst** [comment]
I agree with your statement, but for me this looks like explicit cast. It explicitly tells `Db.SQL` that I want to get list of `SweOffshore.Person` in the result.

```cs
Db.SQL<SweOffshore.Person>
```

This would be incorrect:

```cs
QueryResultRow<SweOffshore.Person> list = Db.SQL<Simplified.Ring2.Person>("...");
```

**Comment by k-rus** [comment]
I see your point. You want to treat generics as cast operator. I think we already discussed this in some issue some time ago.

**Comment by k-rus** [comment]
> I think we already discussed this in some issue some time ago.

The open issue is #1306, so this one is duplicate to it. However, no decision was made there either.

**Comment by miyconst** [comment]
Yes, it's a duplicate then.
