### ISSUE TITLE
Registering too long group name: StarcounterFileUploadWebSocketGroup

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3435]
I am trying to register a `Handle.WebSocket` hanlder:

```cs
Handle.WebSocket("StarcounterFileUploadWebSocketGroup", () => { ... });
```

But it fails with the following exception:

```
"Starcounter.DbException: ScErrFailingEntrypoint (SCERR4259): The user code entrypoint method raised an exception. System.Exception: Registering too long group name: StarcounterFileUploadWebSocketGroup
   at Starcounter.Internal.AllWsGroups.RegisterHandlerInternal(UInt16 port, String groupName) in C:\TeamCity\TeamCity9\buildAgent\work\sc-80\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 217
   at Starcounter.Internal.AllWsGroups.RegisterWsDelegate(UInt16 port, String groupName, Action`2 userDelegate) in C:\TeamCity\TeamCity9\buildAgent\work\sc-80\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 250
   at KitchenSink.HandleFile.GET(String Url, Action`1 UploadingAction) in D:\GitHub\Samples\KitchenSink\src\KitchenSink\HandleFile.cs:line 51
   at KitchenSink.Program.Main() in D:\GitHub\Samples\KitchenSink\src\KitchenSink\Program.cs:line 97
Version: 2.3.977.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4259.
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application) in C:\TeamCity\TeamCity9\buildAgent\work\sc-80\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 513
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application) in C:\TeamCity\TeamCity9\buildAgent\work\sc-80\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 273
   at Starcounter.Hosting.Package.Process() in C:\TeamCity\TeamCity9\buildAgent\work\sc-80\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 143
   at Starcounter.Hosting.Package.Process(IntPtr hPackage) in C:\TeamCity\TeamCity9\buildAgent\work\sc-80\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 56
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\TeamCity9\buildAgent\work\sc-80\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 86
ErrorCode=4259
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4259
---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application) in C:\TeamCity\TeamCity9\buildAgent\work\sc-80\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 487
HResult=-2146232828
---> System.Exception: Registering too long group name: StarcounterFileUploadWebSocketGroup
   at Starcounter.Internal.AllWsGroups.RegisterHandlerInternal(UInt16 port, String groupName) in C:\TeamCity\TeamCity9\buildAgent\work\sc-80\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 217
   at Starcounter.Internal.AllWsGroups.RegisterWsDelegate(UInt16 port, String groupName, Action`2 userDelegate) in C:\TeamCity\TeamCity9\buildAgent\work\sc-80\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 250
   at KitchenSink.HandleFile.GET(String Url, Action`1 UploadingAction) in D:\GitHub\Samples\KitchenSink\src\KitchenSink\HandleFile.cs:line 51
   at KitchenSink.Program.Main() in D:\GitHub\Samples\KitchenSink\src\KitchenSink\Program.cs:line 97
HResult=-2146233088
"
```

- I think the maximum available group name should be extended.
- The exception message text should indicate what is the maximum length.

cc @alemoi

**Comment by alemoi** [comment]
Thanks for the question! Current maximum in name length is 32 characters. I will improve the exception message, but it still we be thrown.

**Comment by miyconst** [comment]
What is the reason for such limitation?

**Comment by alemoi** [comment]
I think some performance reasons previously but now I extended it to 64 characters, I guess its more than enough.
