### ISSUE TITLE
Can't register URI handler "GET /sc/db/{?}/{?}" on port 8080

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3466]
I am trying to start multiple applications in same database: [Launcher, Warehouse, SignIn] and getting the following exception.

@alemoi do you have any idea how this could happen and what it means?

```
Starcounter-DevelopNightlyBuilds-2.1.1562 (Mar 28, 2016 11:43:03 PM)
```

```
"ScErrServerCommandFailed (SCERR10011): The operation ""Starting database warehouse."" failed.
Version: 2.1.1562.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10011."
```

```
"System.Exception: ScErrHandlerAlreadyRegistered (SCERR13003): This handler has already been registered. Can't register URI handler ""GET /sc/db/{?}/{?}"" on port 8080. This handler is already registered. Version: 2.1.1562. Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR13003. 
   at Starcounter.Server.DatabaseEngine.WaitUntilCodeHostOnline(Process codeHostProcess, Database database) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-240\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseEngine.cs:line 370
   at Starcounter.Server.Commands.Processors.StartDatabaseCommandProcessor.<>c__DisplayClass2_0.<Execute>b__3(CommandTask task) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-240\Level1\src\Server\Starcounter.Server\Commands\Processors\StartDatabaseCommandProcessor.cs:line 82
   at Starcounter.Server.Commands.CommandProcessor.<>c__DisplayClass68_0.<WithinTask>b__0(CommandTask t) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-240\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 484
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-240\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 510
   at Starcounter.Server.Commands.Processors.StartDatabaseCommandProcessor.Execute() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-240\Level1\src\Server\Starcounter.Server\Commands\Processors\StartDatabaseCommandProcessor.cs:line 87
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-240\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR13003
"
```

```
"System.Exception: ScErrHandlerAlreadyRegistered (SCERR13003): This handler has already been registered. Can't register URI handler ""GET /sc/db/{?}/{?}"" on port 8080. This handler is already registered.
Version: 2.1.1562.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR13003.
   at Starcounter.GatewayHandlers.RegisterHttpHandlerInGateway(UInt16 port, String appName, String methodSpaceUri, Byte[] nativeParamTypes, UInt16 managedHandlerIndex, UInt64& handlerInfo) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-240\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 610
   at Starcounter.Rest.UriHandlersManager.RegisterUriHandler(UInt16 port, String methodSpaceUri, Byte[] nativeParamTypes, Type messageType, Func`4 wrappedDelegate, NetworkProtocolType protoType, HandlerOptions ho) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-240\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 617
   at Starcounter.Rest.UriManagedHandlersCodegen.RegisterDelegate(UInt16 port, String methodSpaceUri, MethodInfo userDelegateInfo, Expression delegExpr, NetworkProtocolType protoType, HandlerOptions ho) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-240\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 615
   at Starcounter.Rest.RestRegistrationProxy.RegisterHandler[T1,T2,T3](UInt16 port, String methodSpaceUri, Func`4 handler, HandlerOptions ho) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-240\Level1\src\Starcounter.Rest\RestInitialization.cs:line 87
   at Starcounter.Handle.GET[T1,T2,T3](String uriTemplate, Func`4 code, HandlerOptions ho) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-240\Level1\src\Starcounter.Internal\Handle.GET.cs:line 229
   at Starcounter.UriMapping.Init() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-240\Level1\src\Starcounter\Apps\OntologyAndOrdinaryMapping.cs:line 994
   at Starcounter.Internal.AppsBootstrapper.InitAppsBootstrapper(Byte numSchedulers, UInt16 defaultUserHttpPort, UInt16 defaultSystemHttpPort, UInt32 sessionTimeoutMinutes, String dbName, Boolean noNetworkGateway) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-240\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 118
   at StarcounterInternal.Bootstrap.Control.Setup(String[] args) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-240\Level1\src\Starcounter.Bootstrap\Control.cs:line 223
   at StarcounterInternal.Bootstrap.Control.Main(String[] args) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-240\Level1\src\Starcounter.Bootstrap\Control.cs:line 55
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR13003
"
```

```
Attempt to register URI handler duplicate on port "8080" and URI "GET /sc/db/{?}/{?}".
```

**Comment by alemoi** [comment]
Thanks for asking! Usually it was the case when starting in 2 databases but same user port. Are you sure you start in one? No changes were made in that context.

**Comment by miyconst** [comment]
Yes, looks like so.

I remember some time ago I saw another error message, explaining that the current port is not available. Can we fix the error message?
