### ISSUE TITLE
System.ArgumentOutOfRangeException when gathering changes for patches.

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Starcounter#3472]
The following exception is thrown from time to time in Tunitys environment.
Starcounter version 1569

```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at Starcounter.Json.LogArrayChangesWithDatabase(ChangeLog changeLog, Boolean callStepSiblings) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-243\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 155
   at Starcounter.Json.<LogObjectValueChangesWithDatabase>b__123_0(ChangeLog clog, Json json, Boolean css) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-243\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 232
   at Starcounter.Internal.TransactionManager.Scope[T1,T2,T3](TransactionHandle handle, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-243\Level1\src\Starcounter\TransactionManager.cs:line 482
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3](Json json, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-243\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 109
   at Starcounter.Json.LogObjectValueChangesWithDatabase(ChangeLog changeLog, Boolean callStepSiblings) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-243\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 183
   at Starcounter.Json.<LogObjectValueChangesWithDatabase>b__123_0(ChangeLog clog, Json json, Boolean css) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-243\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 232
   at Starcounter.Internal.TransactionManager.Scope[T1,T2,T3](TransactionHandle handle, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-243\Level1\src\Starcounter\TransactionManager.cs:line 482
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3](Json json, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-243\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 109
   at Starcounter.Json.LogObjectValueChangesWithDatabase(ChangeLog changeLog, Boolean callStepSiblings) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-243\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 183
   at Starcounter.Json.LogArrayChangesWithDatabase(ChangeLog changeLog, Boolean callStepSiblings) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-243\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 154
   at Starcounter.Json.<LogObjectValueChangesWithDatabase>b__123_0(ChangeLog clog, Json json, Boolean css) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-243\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 232
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3](Json json, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-243\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 113
   at Starcounter.Json.LogObjectValueChangesWithDa
```

Reported by @malx122 

I have a version of Tunity running locally and will try to reproduce it there to be able to investigate what goes wrong. Might be concerning concurrent access to session and pushing changes.

**Comment by chrhol** [comment]
I think I have found the problem (or atleast one problem). Sometimes when scheduling a task for a specific session the current transaction was still set on the thread which lead to that viewmodels in different sessions shared transactions, which lead to some strange errors further on. 

I have pushed a fix to develop and soon to pnext.

**Comment by chrhol** [comment]
I will keep this issue open until @malx122 can verify that it solved the inital problem.

**Comment by malx122** [comment]
Do you think that this will solve the "sometimes not working push"-problem as well?

**Comment by chrhol** [comment]
> Do you think that this will solve the "sometimes not working push"-problem as well?

Possibly yes. I think there's a good chance at least.

**Comment by chrhol** [comment]
So far the fix seems to have solved the problems. I will close the issue.
