### ISSUE TITLE
TypedJSON: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by atifsheikh** [Starcounter/Starcounter#3475]
I keep getting the following error in my code : 

> "System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , Json )
   at Starcounter.Templates.TObject.BoundOrUnboundGet(Json parent) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-245\Level1\src\Starcounter.XSON\Templates\TObject.cs:line 130
   at Starcounter.Advanced.XSON.StandardJsonSerializer.PopulateObject(Json json, Template template, JsonReader reader) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-245\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 707
   at Starcounter.Advanced.XSON.StandardJsonSerializer.Populate(Json json, IntPtr source, Int32 sourceSize) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-245\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 761
   at Starcounter.Advanced.XSON.StandardJsonSerializer.PopulateObject(Json json, Template template, JsonReader reader) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-245\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 707
   at Starcounter.Advanced.XSON.StandardJsonSerializer.Populate(Json json, IntPtr source, Int32 sourceSize) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-245\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 761
   at Starcounter.Json.PopulateFromJson(Byte[] source, Int32 sourceSize) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-245\Level1\src\Starcounter.XSON\Class Json\Json.Serializing.cs:line 131
   at Starcounter.Rest.UriManagedHandlersCodegen.ReadMessageParam(Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-245\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 211
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-245\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-245\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-245\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 562
HResult=-2147467261
"

I investigated the issue, and my code paused on a line of code as shown in the following image : 
![sc error](https://cloud.githubusercontent.com/assets/4388707/14344168/4c45d5b8-fca6-11e5-959b-0d1c173f273c.jpg)

But the strange thing is, if i replay the  same line of code, everything works fine. By replay i mean, i drag the control (Green pointer in VS on left) and drop the control in 1 line above the error line. the control gets yellow, and if i hit F5 the code works perfectly fine.

**Comment by chrhol** [comment]
Hi atif, 
do you get this every time or just sometimes? 

My suspicion is that it might have to do with the binding between the dataobject and the typedjson object is recreated due to being used with different dataobjects (or with no dataobject set) from more than one place at the same time. We have a number of issues reported for this which yields some strange errors.

If that is the case then this would also explain why it works when you replay it again.

**Comment by atifsheikh** [comment]
@chrhol I get this sometimes.

**Comment by atifsheikh** [comment]
and what is the recommended way to fix this kind of issues with typedjson?

**Comment by chrhol** [comment]
Ok, then I think my guess is correct. As to exactly why you get it here I cannot say directly. In #3224 the problem arose from setting the `Data`-property to null, and the quick workaround was to not set it to null explicitly. 

The proper solution is that we rewrite the parts that handles bindings and make sure they are thread-safe or that they are not allowed to be recreated on the fly (which might be a bad decision from us from the beginning).

Lets start to see if we can find some way to avoid the problem in your code and then we have to raise the priority in this one I think to fix properly.

**Comment by chrhol** [comment]
Linking the other issues for this: #2303, #2513

**Comment by chrhol** [comment]
I think I have access to your repo, is this code pushed? I can take a look and see if I can see something we can do as workaround if you like.

**Comment by atifsheikh** [comment]
That would be great. This code with bug is in Atif-simpleConfigs branch. 
Project : AdFenix
File : Configs.cs
Line of exception : 520 (but its not constant with this line, the exception appears on different lines of this function.)

**Comment by chrhol** [comment]
I've been looking through the code and I see no obvious place to try to add some workaround. 

The `SyncConfigsSeller` object seems to be used with the same type of dataobject everywhere. The only thing I can think of is that maybe `PublicationOwner` or `Seller` database objects might be null sometimes which makes the bindings being invalidated (`DownloadQueue.cs` row 75-76, `Configs.cs` row 1205).

You could try to add a null-check and don't set the `Data` property if null. 

Just to make things clear: The problem lies in Starcounter and there is nothing strange in your code. It should work as is. We need to fix it at our side. I'm not sure how much work it will be though.

**Comment by Ripipip** [comment]
I have a very similar problem. I am just trying to reference an object that is stored as a value in another database object. I am 100% certain that the object is there. As you can see on line above the yellow I have gotten the Name of the SegmentationRule. But when I try to access the SegmentationRule itself it throws a NullReference exception which doesn't make sense. This is completely reproducable. 

Before exception:
![sc error 1](https://cloud.githubusercontent.com/assets/7534151/14352392/9618fa84-fcd4-11e5-9d21-b99b71c98cdb.png)


After exception:
![sc error 2](https://cloud.githubusercontent.com/assets/7534151/14352395/99b369c2-fcd4-11e5-9f69-fe7872b6166c.png)

**Comment by chrhol** [comment]
@Ripipip: Could you post the stacktrace from the exception you get.

**Comment by Ripipip** [comment]
@chrhol    at AdFenix.ApiMirror.FacebookApi.v2_5.AdSet.UpdateAdset(String adSetId, String attributes, String action, Campaign campaign, String AdsetName, FacebookAdCampaign facebookAdCampaign) in c:\adfenix-backend\src\ApiMirror\FacebookApi\v2_5\AdSet.cs:line 231
   at AdFenix.ApiMirror.FacebookApi.v2_5.AdSet.CreateAdset(Campaign campaign, String adAccountId, String AdsetName, DateTime StartTime, String CampaignID, Int32 BidAmount, BudgetTemplate budgetTemplate, String adSetId, String action) in c:\adfenix-backend\src\ApiMirror\FacebookApi\v2_5\AdSet.cs:line 134
   at AdFenix.ApiMirror.FacebookApi.v2_5.AdReachEstimate.CheckReachs(Campaign campaign) in c:\adfenix-backend\src\ApiMirror\FacebookApi\v2_5\AdReachEstimate.cs:line 41
   at AdFenix.ApiMirror.FacebookApi.ManageCampaign.CheckStats(Campaign campaign) in c:\adfenix-backend\src\ApiMirror\FacebookApi\ManageCampaign.cs:line 189
   at AdFenix.Server.Handlers.TimedFeatures.<Register>b__2b(String status, Request r) in c:\adfenix-backend\src\Server\Handlers\TimedFeatures.cs:line 447

**Comment by chrhol** [comment]
@Ripipip: I think your issue is a separate problem. Judging by the stacktrace it's not coming from the same place. I think we should move it to a separate issue and continue investigating it.

**Comment by chrhol** [comment]
Update: I'm currently working on this. The full solution requires some rewrite which will take a bit longer to solve (and to determine exactly how it should work).

As an intermediate step I will change so that setting the `Data`-property to null does not invalidate the bindings. However I need to test it a bit more, so I hope I will have time to push it later tonight or tomorrow.

With this step it should be enough for you to not be hindered by the exception above.

**Comment by atifsheikh** [comment]
:+1: Sounds good. I will test the code with your update on monday

**Comment by atifsheikh** [comment]
do you have permission to commit anything in our repository?

**Comment by chrhol** [comment]
> do you have permission to commit anything in our repository?

I dont think so, but I hope this fix will work without any changes in your code.

**Comment by chrhol** [comment]
There is some problem with our nightly builds so I made a daily build for you which contains my changes. Please try it out and see if you still get this exception. Hopefully it will be gone.

Link to installer: http://downloads.starcounter.com/download/Starcounter/DevelopDailyBuilds/2.1.1708

**Comment by atifsheikh** [comment]
@chrhol Thanks for the update, I will test this daily build today.

**Comment by atifsheikh** [comment]
@chrhol I have installed your suggested SC Version, and im also feeding traffic to the server, lets see how it performs. So far no exception occurred.

**Comment by chrhol** [comment]
Great, lets hope there will be no exception :)

**Comment by atifsheikh** [comment]
@chrhol It works perfectly fine for me. The code have processed more than 30K requests with JSON, and i haven't received a single error or exception. 
Also we are going to Upgrade SC Version on our Live servers, Do you think we can use [the Daily Build](http://downloads.starcounter.com/download/Starcounter/DevelopDailyBuilds/2.1.1708)? 
or should we wait for the next Nightly Build?

**Comment by chrhol** [comment]
> @chrhol It works perfectly fine for me. The code have processed more than 30K requests with JSON, and i haven't received a single error or exception. 

Awesome!

> Also we are going to Upgrade SC Version on our Live servers, Do you think we can use the Daily Build? 
or should we wait for the next Nightly Build?

Lets wait for the nightly build I think. We are fixing some other issues as well that might be good to get if you are upgrading.

**Comment by atifsheikh** [comment]
Sure, We can wait till tomorrow then. Thanks for the update

**Comment by chrhol** [comment]
I will consider this issue resolved then. Thanks for reporting the issue and testing the fix @atifsheikh :+1:

**Comment by atifsheikh** [comment]
My server crashed with the following error in SC Admin Logs: 

"Access violation (C0000005) detected at bmx.cpp:63 (Thread 8452).
    00007FFB49248A5C KERNELBASE!
    00007FFB3C51E429 clr!
    00007FFB3C51E45B clr!
    00007FFB3C51E465 clr!
    00007FFADD6E4D3C <unknown>!
    000000EBDAA1BF50 <unknown>!
    00007FFB3C40936D clr!

"
Do you think this crash is only in your Daily build (Version 2.1.1708) ?

**Comment by alemoi** [comment]
Thanks for reporting! I suppose its some unexpected uncaught managed exception that occurred. I now added wrapper around most outer call, that should log this exception details. Will be available in the coming nightly.

**Comment by atifsheikh** [comment]
@alemoi Thank you

**Comment by atifsheikh** [comment]
And by upcoming nightly, you mean the one after 2.1.1735, right?

**Comment by alemoi** [comment]
> And by upcoming nightly, you mean the one after 2.1.1735, right?

Yes, exactly. I will start the new nightly now. Hopefully we will see the exact stack trace in your logs when this error occurs. Thanks!

**Comment by atifsheikh** [comment]
Thanks for the Nightly Build, I am testing It. Will update here if I get any crashes again.
