### ISSUE TITLE
Object reference not set to an instance of an object (2)

### ISSUE THREAD

**Issue by Ripipip** [Starcounter/Starcounter#3479]
I have a very similar problem. I am just trying to reference an object that is stored as a value in another database object. I am 100% certain that the object is there. As you can see on line above the yellow I have gotten the Name of the SegmentationRule. But when I try to access the SegmentationRule itself it throws a NullReference exception which doesn't make sense. This is completely reproducable. 

Starcounter version: Starcounter-Stable-2.1.177 (Oct 14, 2015 5:28:43 PM)

Before exception:
![sc error 1](https://cloud.githubusercontent.com/assets/7534151/14352392/9618fa84-fcd4-11e5-9d21-b99b71c98cdb.png)

After exception:
![sc error 2](https://cloud.githubusercontent.com/assets/7534151/14352395/99b369c2-fcd4-11e5-9f69-fe7872b6166c.png)

Stacktrace: 

AdFenix.ApiMirror.FacebookApi.v2_5.AdSet.UpdateAdset(String adSetId, String attributes, String action, Campaign campaign, String AdsetName, FacebookAdCampaign facebookAdCampaign) in c:\adfenix-backend\src\ApiMirror\FacebookApi\v2_5\AdSet.cs:line 231
at AdFenix.ApiMirror.FacebookApi.v2_5.AdSet.CreateAdset(Campaign campaign, String adAccountId, String AdsetName, DateTime StartTime, String CampaignID, Int32 BidAmount, BudgetTemplate budgetTemplate, String adSetId, String action) in c:\adfenix-backend\src\ApiMirror\FacebookApi\v2_5\AdSet.cs:line 134
at AdFenix.ApiMirror.FacebookApi.v2_5.AdReachEstimate.CheckReachs(Campaign campaign) in c:\adfenix-backend\src\ApiMirror\FacebookApi\v2_5\AdReachEstimate.cs:line 41
at AdFenix.ApiMirror.FacebookApi.ManageCampaign.CheckStats(Campaign campaign) in c:\adfenix-backend\src\ApiMirror\FacebookApi\ManageCampaign.cs:line 189
at AdFenix.Server.Handlers.TimedFeatures.b__2b(String status, Request r) in c:\adfenix-backend\src\Server\Handlers\TimedFeatures.cs:line 447

**Comment by Ripipip** [comment]
@chrhol I would guess you are the guy to notice this :)

**Comment by chrhol** [comment]
I've investigated this together with @Ripipip and we think we found the cause.

In VS when you debug there is a feature where you can change the execution point, both backward and forward, to allow jumping over pieces of code and execute certain parts. 

This is documented here: https://msdn.microsoft.com/en-us/library/y740d9d3.aspx#Anchor_3

In the Caution-block it is specified that this may cause stack corruption in some cases (the third bulletpoint)

> Moving the next statement to another function or scope usually results in call-stack corruption, causing a run-time error or exception

We suspect that this is what happened in this case. Sometimes it will work to move the execution point and sometimes not. 

For now we assume that this issue is solved (or at least the cause found).
