### ISSUE TITLE
Error in Json merger

### ISSUE THREAD

**Issue by malx122** [Starcounter/Starcounter#3485]
I probably do something wrong in our apps, but no idea what...
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Starcounter.Internal.JsonResponseMerger.DoMerge(Request req, Response resp, List`1 responses) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1330\Level1\src\Starcounter\Apps\JsonResponseMerger.cs:line 83
   at Starcounter.Internal.JsonResponseMerger.DefaultMerger(Request req, Response resp, List`1 responses) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1330\Level1\src\Starcounter\Apps\JsonResponseMerger.cs:line 41
   at Starcounter.UriMapping.MappingHandler(Request req, List`1 mappedHandlersList, String stringParam) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1330\Level1\src\Starcounter\Apps\OntologyAndOrdinaryMapping.cs:line 239
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1330\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 161
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1330\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
...
...
```

**Comment by chrhol** [comment]
Looks like we missed the check if a response is null in one place. So you probably return null from one of your handlers that returns a partial response. Depending on the order the responses comes in this might happen.

I will fix it.

**Comment by malx122** [comment]
Ok, good. Quite important to be able to return null in a partial ;).

**Comment by chrhol** [comment]
Fix pushed to develop and pnext branches now.
