### ISSUE TITLE
Administrator stopped working (develop)

### ISSUE THREAD

**Issue by andwah** [Starcounter/Starcounter#3488]
With the latest develop nightly the administrator caches when user clickes a button (Start Database)

Nightly version:
2.1.1690 (10 apr 2016 03:00:40) : NOT WORKING
2.1.1605 (3 apr 2016 15:12:53) : WORKING

```
  System.Exception: ScErrThreadNotAttached (SCERR1004): The operation failed because the current thread wasn't attached to the scheduler. 
  Version: 2.0.0. 
  Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR1004. 
  at Starcounter.Internal.TransactionManager.CreateAndSetCurrent(Boolean readOnly, Boolean detectConflicts, Boolean isImplicit)  in c:\github\Starcounter\Level1\src\Starcounter\TransactionManager.cs:line 154
  at Starcounter.Internal.TransactionManager.CreateImplicitAndSetCurrent(Boolean readOnly) in c:\github\Starcounter\Level1\src\Starcounter\TransactionManager.cs:line 104
  at Starcounter.Internal.TransactionManager.Starcounter.Internal.ITransactionManager.CreateImplicitAndSetCurrent() in c:\github\Starcounter\Level1\src\Starcounter\TransactionManager.cs:line 100
  at Starcounter.Session.ScheduleTask(String sessionId, SessionTask task, Boolean waitForCompletion) in c:\github\Starcounter\Level1\src\Starcounter.XSON\Sessions\Session.cs:line 276
  at Starcounter.Session.ScheduleTask(IEnumerable`1 sessionIds, SessionTask task, Boolean waitForCompletion) in c:\github\Starcounter\Level1\src\Starcounter.XSON\Sessions\Session.cs:line 332
  at Administrator.Server.Managers.ServerManager.ServerModel_Changed(Object sender, EventArgs e) in c:\github\Starcounter\Level1\src\Starcounter.Administrator\Server\Managers\ServerManager.cs:line 331
  at Administrator.Server.Model.Server.OnChanged(Object sender, EventArgs e) in c:\github\Starcounter\Level1\src\Starcounter.Administrator\Server\Model\Server.cs:line 194
  at Administrator.Server.Model.Server.Database_Changed(Object sender, EventArgs e) in c:\github\Starcounter\Level1\src\Starcounter.Administrator\Server\Model\Server.cs:line 183
  at Administrator.Server.Model.Database.OnChanged(Object sender, EventArgs e) in c:\github\Starcounter\Level1\src\
```

**Comment by chrhol** [comment]
My bad. When fixing so that current transaction was reset when calling Session.ScheduleTask for a session on the same scheduler I did not take the `nodb` switch/setting into account. 

I will add a check if transactions are available or not.

**Comment by andwah** [comment]
Tested and it seems to work, thanks for the quick response+fix
