### ISSUE TITLE
Argument types do not match? I think its a custom binding that fails but the error does not say much

### ISSUE THREAD

**Issue by malx122** [Starcounter/Starcounter#3491]
```
puppet.js:285 Uncaught Error: PuppetJs JSON response error. Server responded with error 500 InternalServerError

System.ArgumentException: Argument types do not match
   at System.Linq.Expressions.Expression.Condition(Expression test, Expression ifTrue, Expression ifFalse)
   at Starcounter.XSON.TemplateDelegateGenerator.CreateBinding[T](BindingInfo bInfo, Boolean createGetBinding, Expression instance, ParameterExpression value, Template origin) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1330\Level1\src\Starcounter.XSON\TemplateDelegateGenerator.cs:line 415
   at Starcounter.XSON.TemplateDelegateGenerator.GenerateBoundGetExpression[T](BindingInfo bInfo, Template origin) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1330\Level1\src\Starcounter.XSON\TemplateDelegateGenerator.cs:line 339
   at Starcounter.XSON.TemplateDelegateGenerator.GenerateBoundDelegates(TObject property, Json json) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1330\Level1\src\Starcounter.XSON\TemplateDelegateGenerator.cs:line 216
   at Starcounter.Templates.TObject.GenerateBoundGetterAndSetter(Json parent) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1330\Level1\src\Starcounter.XSON\Templates\TObject.cs:line 65
   at Starcounter.Templates.TObject.BoundOrUnboundGet(Json parent) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1330\Level1\src\Starcounter.XSON\Templates\TObject.cs:line 129
   at Starcounter.Advanced.XSON.StandardJsonSerializerBase.ScopeAndEstimateObject(TypedJsonSerializer serializer, Json json, Template template) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1330\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 150
   at Starcounter.Advanced.XSON.StandardJsonSerializerBase.EstimateObject(TypedJsonSerializer serializer, Json json) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1330\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 191
   at Starcounter.Internal.TransactionManager.Scope[T1,T2,TResult](TransactionHandle handle, Func`3 func, T1 arg1, T2 arg2) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1330\Level1\src\Starcounter\TransactionManager.cs:line 531
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,TResult](Json json, Func`3 func, T1 arg1, T2 arg2) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1330\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 182
   at Starcounter.Advanced.XSON.StandardJsonSerializerBase.ScopeAndEstimateObject(TypedJsonSerializer serializer, Json json, Template template) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1330\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 156
   at Starcounter.Advanced.XSON.StandardJsonSerializerBase.EstimateObject(TypedJsonSerializer serializer, Json json) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1330\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 191
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,TResult](Json json, Func`3 func, T1 arg1, T2 arg2) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1330\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 183
   at Starcounter.Advanced.XSON.StandardJsonSerializerBase.ScopeAndEstimateObject(TypedJsonSerializer serializer, Json json, Template template) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1330\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 156
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,TResult](Json json, Func`3 func, T1 arg1, T2 arg2) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1330\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 183
   at Starcounter.Advanced.XSON.StandardJsonSerializerBase.EstimateSizeBytes(Json json) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1330\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 40
   at Starcounter.Advanced.XSON.StandardJsonSerializerBase.EstimateObject(TypedJsonSerializer serializer, Json json) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1330\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 225
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,TResult](Json json, Func`3 func, T1 arg1, T2 arg2) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1330\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 183
   at Starcounter.Advanced.XSON.StandardJsonSerializerBase.ScopeAndEstimateObject(TypedJsonSerializer serializer, Json json, Template template) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1330\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 156
   at Starcounter.Advanced.XSON.StandardJsonSerializerBase.EstimateObject(TypedJsonSerializer serializer, Json json) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1330\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 191
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,TResult](Json json, Func`3 func, T1 arg1, T2 arg2) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1330\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 183
   at Starcounter.Advanced.XSON.StandardJsonSerializerBase.ScopeAndEstimateObject(TypedJsonSerializer serializer, Json json, Template template) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1330\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 156
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,TResult](Json json, Func`3 func, T1 arg1, T2 arg2) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1330\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 183
   at Starcounter.Advanced.XSON.StandardJsonSerializerBase.EstimateSizeBytes(Json json) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1330\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 40
   at Starcounter.Json.ToJsonUtf8() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1330\Level1\src\Starcounter.XSON\Class Json\Json.Serializing.cs:line 70
   at Starcounter.Internal.PuppetRestHandler.<>c.<RegisterJsonPatchHandlers>b__4_1(Request request, Session session) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1330\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 132
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1330\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1330\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1330\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 598
HResult=-2147024809

More information about this error may be available in the server error log.
```

**Comment by chrhol** [comment]
Strange, it should provide a better description of the failing binding. Is there some way to reproduce it in Tunity apps?

**Comment by chrhol** [comment]
I have reproduced it. There are a couple of issues to solve here:
- The message from the exception needs to pinpoint the problem.
- There is a bug in the code that generates the binding when the property is an object itself. Creating a binding to a string or other primitive value works.

**Comment by chrhol** [comment]
I've added a little better errormessage, so that there is at least enough information about which property and binding that fails. To note here is that this exception actually was a bug in the code that generates the binding, so it was not an expected exception. The expected exceptions should provide more detailed messages.

The bug is also fixed and pushed to develop and pnext, so the binding you were trying to use should work starting from the next nightly. 

I will close this issue and assume that it solves your problem :) If not give me a ping and I will reopen it.
