### ISSUE TITLE
Unspecified error in kernelbase during application start

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#3500]
I use local build of latest develop. I created an app in branch `bug/CountQueryInheritedOpt3447`. Started it few times in default and another database. Last time I started it in default and aborted on assertion failure. The next try gave me kernel error:

```bash
Level1\src\Samples\TestApps\CountQueryInheritedOpt3447>star CountQueryInheritedOpt3447.cs
CountQueryInheritedOpt3447 -> default (starting application ...)                
[11:49:25, Starcounter (default)]
Unhandled unspecified error (80000003) detected (Thread 7484).
    00007FF81B6E2D52 KERNELBASE!
    00007FF80169A40F clr!
    00007FFFFF7EC4B9 mscorlib.ni!
    00007FF800E29C84 System.ni!
    00007FF800E27995 System.ni!
    00007FF800E2B69B System.ni!
    00007FF7A1E21DFC <unknown>!
```

The log contains the same stack trace and then exception:
>Starcounter.DbException: ScErrDatabaseEngineTerminated (SCERR10007): The server detected that the user code host executable (sccode.exe) unexpectedly terminated during a management operation. , PID=2400, Database=default
Version: 2.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10007.
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.<>c__DisplayClass4_0.<Execute>b__3(CommandTask task) in C:\GitRepositories\Starcounter\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 180
   at Starcounter.Server.Commands.CommandProcessor.<>c__DisplayClass68_0.<WithinTask>b__0(CommandTask t) in C:\GitRepositories\Starcounter\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 483
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) in C:\GitRepositories\Starcounter\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 510
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Action`1 action) in C:\GitRepositories\Starcounter\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 482
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.Execute() in C:\GitRepositories\Starcounter\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 108
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\GitRepositories\Starcounter\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 298
ErrorCode=10007
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR10007
---> Starcounter.DbException: ScErrProcessExitCodeNotAvailable (SCERR10040): The exit code of the terminating process was not available.
Version: 2.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10040.
ErrorCode=10040
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR10040

cc @eriohl

**Comment by eriohl** [comment]
It is a breakpoint exception (STATUS_BREAKPOINT). Probably from the CLR somewhere. Is this develop?

**Comment by eriohl** [comment]
Regardless, there is nothing in the trace indicating that there is an error from the kernel. It is as I wrote a breakpoint. It is intercepted by the unhandled exception handler and logged. This log doesn't make much sense however since it only logs the unmanaged stack trace. It is not designed to intercept any exceptions from managed code.

Check the (Windows) event log see if you have a stack trace that contains more information.

**Comment by dan31** [comment]
I recall we have some instruction from @bigwad somewhere in comments on how to activate dump recording on Windows, so that on crash it contains needed traces. I couldn't find it now, @bigwad maybe you remember what I refer to and can point us out.

**Comment by k-rus** [comment]
@eriohl Thank you for the reply.
It might be related to the assert in the code, which supposes to bring an assert window.

**Comment by bigwad** [comment]
@dan31, here it is: https://github.com/Starcounter/Starcounter/issues/3297#issuecomment-174574035
But I doubt you'll get the dump in this case, as kernel seems to handle this exception.

**Comment by k-rus** [comment]
I didn't get the exception any more. I suggest it is related to `System.Diagnostics.Trace.Assert`, however I cannot confirm.

I close the issue.
