### ISSUE TITLE
develop/pnext tpcc long test fails becuase of PrivateAssemblyStore KeyNotFoundException

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#3501]
Here is the first time it failed:

https://teamcity.starcounter.org/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=2672#_focus=6778

@per-samuelsson are there any related changes you can think of?

Assigning to @bigwad for the moment.

**Comment by alemoi** [comment]
Note that this is both in develop and pnext.

**Comment by per-samuelsson** [comment]
> @per-samuelsson are there any related changes you can think of?

Yep, I made changes to `PrivateAssemblyStore` yesterday, and everything passed the daily builds. Didn't know about failing nightly builds. Sorry for that.

It's clearly on me to investigate.

**Comment by per-samuelsson** [comment]
(BTW, shouldn't we keep these infrastructure issues on some other tracker, as suggested by @dan31 some time ago?)

**Comment by alemoi** [comment]
Yeah, I agree, if its an internal issue, then sure!

**Comment by dan31** [comment]
@per-samuelsson is correct, I think any devops/infra thing is a noise for customers.

**Comment by dan31** [comment]
Guys keep this one here, but in future let's try to post to public tracker only things which make sense for the users. I don't think they are interested in our failing tests.

**Comment by per-samuelsson** [comment]
Update: I was able to reproduce this constantly on my box last night, but I still haven't found the reason. As soon as I do and I can fix it, I'll manually run new nightlies.

**Comment by per-samuelsson** [comment]
With some fresh eyes, it was quite an easy bug to spot after all. Now it's fixed, merged and pushed in https://github.com/Starcounter/Starcounter/commit/34deac0a8ae539fb6887264f95982b24b88b98bd.

I've started a new #develop-nightly-274 build, and will merge it into **pnext**, later running that nightly too.

**Comment by per-samuelsson** [comment]
> I've started a new #develop-nightly-274 build [...]

I was able to run that for about 2 hours, but then the build crashed on something else. I've investigated it, and here's the most relevant extract from the build log:

```
[11:31:28][umbrella_node_test-bat] C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-274\Level1\src\Samples\NodeTest>ECHO Performance Tests: Node WebSockets. 
[11:31:28][umbrella_node_test-bat] Performance Tests: Node WebSockets.
[11:31:28][umbrella_node_test-bat] 
[11:31:28][umbrella_node_test-bat] C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-274\Level1\src\Samples\NodeTest>CALL node_test.bat -ProtocolType=ProtocolWebSockets -AsyncMode=ModeSync -NumEchoesPerWorker=10000 
[11:31:28][umbrella_node_test-bat] 
[11:31:28][umbrella_node_test-bat] C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-274\Level1\src\Samples\NodeTest>IF "True" == "False" GOTO :EOF 
[11:31:28][umbrella_node_test-bat] 
[11:31:28][umbrella_node_test-bat] C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-274\Level1\src\Samples\NodeTest>staradmin kill all 
[11:31:28][umbrella_node_test-bat] 
[11:31:28][umbrella_node_test-bat] C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-274\Level1\src\Samples\NodeTest>star.exe "C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-274\Level1\Bin\Release\s\NetworkIoTest\NetworkIoTest.exe" DbNumber=1 PortNumber=8080 TestType=MODE_NODE_TESTS 
[11:31:48][umbrella_node_test-bat] 
[11:31:48][umbrella_node_test-bat] C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-274\Level1\src\Samples\NodeTest>NodeTest.exe -ProtocolType=ProtocolWebSockets -AsyncMode=ModeSync -NumEchoesPerWorker=10000 
[11:31:48][umbrella_node_test-bat] Node test settings!
[11:31:48][umbrella_node_test-bat] ServerIp: 127.0.0.1
[11:31:48][umbrella_node_test-bat] ServerPort: 8080
[11:31:48][umbrella_node_test-bat] ProtocolType: ProtocolWebSockets
[11:31:48][umbrella_node_test-bat] NumWorkers: 3
[11:31:48][umbrella_node_test-bat] MinEchoBytes: 1
[11:31:48][umbrella_node_test-bat] MaxEchoBytes: 10000
[11:31:48][umbrella_node_test-bat] NumEchoesPerWorker: 10000
[11:31:48][umbrella_node_test-bat] NumEchoesPerConnection: 10
[11:31:48][umbrella_node_test-bat] NumSecondsToWait: 5000
[11:31:48][umbrella_node_test-bat] AsyncMode: ModeSync
[11:31:48][umbrella_node_test-bat] UseAggregation: False
[11:31:48][umbrella_node_test-bat] 0: test started..
[11:31:48][umbrella_node_test-bat] 1: test started..
[11:31:48][umbrella_node_test-bat] 2: test started..
[11:31:48][umbrella_node_test-bat] 
[11:31:48][umbrella_node_test-bat] Unhandled Exception: 
[11:31:48][umbrella_node_test-bat] Unhandled Exception: System.Exception: WebSocket connection was closed unexpectedly!
[11:31:48][umbrella_node_test-bat]    at NodeTest.NodeTestInstance.<>c__DisplayClass11_0.<PerformSyncWebSocket4NetEcho>b__3(Object s, EventArgs e) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-274\Level1\src\Samples\NodeTest\NodeTest.cs:line 464
[11:31:48][umbrella_node_test-bat]    at WebSocket4Net.WebSocket.FireClosed()
[11:31:48][umbrella_node_test-bat]    at WebSocket4Net.WebSocket.OnClosed()
[11:31:48][umbrella_node_test-bat]    at SuperSocket.ClientEngine.ClientSession.OnClosed()
[11:31:48][umbrella_node_test-bat]    at SuperSocket.ClientEngine.AsyncTcpSession.ProcessReceive(SocketAsyncEventArgs e)
[11:31:48][umbrella_node_test-bat]    at SuperSocket.ClientEngine.AsyncTcpSession.StartReceive()
[11:31:48][umbrella_node_test-bat]    at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
[11:31:48][umbrella_node_test-bat]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[11:31:48][umbrella_node_test-bat]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[11:31:48][umbrella_node_test-bat]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
[11:31:48][umbrella_node_test-bat]    at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
[11:31:48][umbrella_node_test-bat]    at System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
[11:31:48][umbrella_node_test-bat]    at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
[11:31:48][umbrella_node_test-bat] System.Exception: WebSocket connection was closed unexpectedly!
[11:31:48][umbrella_node_test-bat]    at NodeTest.NodeTestInstance.<>c__DisplayClass11_0.<PerformSyncWebSocket4NetEcho>b__3(Object s, EventArgs e) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-274\Level1\src\Samples\NodeTest\NodeTest.cs:line 464
[11:31:48][umbrella_node_test-bat]    at WebSocket4Net.WebSocket.FireClosed()
[11:31:48][umbrella_node_test-bat]    at WebSocket4Net.WebSocket.OnClosed()
[11:31:48][umbrella_node_test-bat]    at SuperSocket.ClientEngine.ClientSession.OnClosed()
[11:31:48][umbrella_node_test-bat]    at SuperSocket.ClientEngine.AsyncTcpSession.ProcessReceive(SocketAsyncEventArgs e)
[11:31:48][umbrella_node_test-bat]    at SuperSocket.ClientEngine.AsyncTcpSession.StartReceive()
[11:31:48][umbrella_node_test-bat]    at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
[11:31:48][umbrella_node_test-bat]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[11:31:48][umbrella_node_test-bat]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[11:31:48][umbrella_node_test-bat]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
[11:31:48][umbrella_node_test-bat]    at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
[11:31:48][umbrella_node_test-bat]    at System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
[11:31:48][umbrella_node_test-bat]    at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
[11:31:48][umbrella_node_test-bat] 
[11:31:48][umbrella_node_test-bat] Unhandled Exception: System.Exception: WebSocket connection was closed unexpectedly!
[11:31:48][umbrella_node_test-bat]    at NodeTest.NodeTestInstance.<>c__DisplayClass11_0.<PerformSyncWebSocket4NetEcho>b__3(Object s, EventArgs e) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-274\Level1\src\Samples\NodeTest\NodeTest.cs:line 464
[11:31:48][umbrella_node_test-bat]    at WebSocket4Net.WebSocket.FireClosed()
[11:31:48][umbrella_node_test-bat]    at WebSocket4Net.WebSocket.OnClosed()
[11:31:48][umbrella_node_test-bat]    at SuperSocket.ClientEngine.ClientSession.OnClosed()
[11:31:48][umbrella_node_test-bat]    at SuperSocket.ClientEngine.AsyncTcpSession.ProcessReceive(SocketAsyncEventArgs e)
[11:31:48][umbrella_node_test-bat]    at SuperSocket.ClientEngine.AsyncTcpSession.StartReceive()
[11:31:48][umbrella_node_test-bat]    at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
[11:31:48][umbrella_node_test-bat]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[11:31:48][umbrella_node_test-bat]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[11:31:48][umbrella_node_test-bat]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
[11:31:48][umbrella_node_test-bat]    at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
[11:31:48][umbrella_node_test-bat]    at System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
[11:31:48][umbrella_node_test-bat]    at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
[11:31:49][umbrella_node_test-bat] Finished echoes: 10 out of 30000, last second: 10
[11:33:28][umbrella_node_test-bat] -- Killing started process because it runs longer than allowed.
[11:33:28][umbrella_node_test-bat] The test has failed. See build log for details.
[11:33:28][Step 1/1] System.Exception: Process did not exit within allowed time: "C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-274\Level1\src\Samples\NodeTest\umbrella_node_test.bat " and allowed time(sec): 240
[11:33:28][Step 1/1]    at BuildSystemHelper.BuildSystem.StartProcessAndWaitForExit(String pathToExe, String args, String& stringOutput, Int32 secondsToWait, Boolean printOutput) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-274\BuildSystem\src\BuildSystemHelper\BuildSystemHelper.cs:line 1058
[11:33:28][Step 1/1]    at TestRunner.TestRunner.RunTests(String pathToCheckoutDir, TestTypes testType, List`1 testsToSkip, Dictionary`2 longTestsDurationsSeconds, Boolean continueTestsAfterFirstFail) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-274\BuildSystem\src\TestRunner\TestRunner.cs:line 545
```

@alemoi, do you have a take on that one?

**Comment by alemoi** [comment]
Yes, I will check it. I also noticed that server log is overwritten or something. I will add a fix that server log is printed after every failing test! That would be an improvement!

**Comment by alemoi** [comment]
The above problem I just fixed. Thanks for reporting @per-samuelsson
