### ISSUE TITLE
Upper and lowercase letters in appname

### ISSUE THREAD

**Issue by malx122** [Starcounter/Starcounter#3508]
This must be reported earlier but I can't find any issue.
Was testing some startup scripts and couldn't understand why it failed. I was using
```
star -d=default --resourcedir="c:\projects\Github\SignIn\src\SignIn\wwwroot;c:\projects\Github\Tunity-3\Tunity.Common\Client" "c:\projects\Github\SignIn\bin\Debug\signin.exe"
```
and got 
```
"System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Starcounter.Hosting.PrivateAssemblyStore.ImmutableState.Starcounter.Hosting.IPrivateAssemblyStore.GetAssembly(String filePath) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-272\Level1\src\Hosting\Starcounter.Hosting\PrivateAssemblyStore.cs:line 56
   at Starcounter.Hosting.AssemblyResolver.ResolveApplication(String applicationHostFile) in 
...
```
When I had nearly given up I changing the startupline to:
```
star -d=default --resourcedir="c:\projects\Github\SignIn\src\SignIn\wwwroot;c:\projects\Github\Tunity-3\Tunity.Common\Client" "c:\projects\Github\SignIn\bin\Debug\SignIn.exe"
```
and everything was working fine.
(I changed `signin.exe` to `SignIn.exe`)

**Comment by per-samuelsson** [comment]
@malx122 

Sorry to see you experience this. It's a bug recently introduced, and then fixed, so in never builds, you won't experience it again. It was originally reported and fixed in #3501.
