### ISSUE TITLE
Failure to create database after changing settings on existing database and then deleting

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Starcounter#3523]
Do the following steps to reproduce

1. Create database 
2. Go to settings for that database in administrator
3. Change some value, "Http port" for example, and save.
4. Stop and delete database.
5. Create a new database with the same name.

```
ScErrUnexpectedCommandException (SCERR10016): Creating database Default failed due to an unexpected problem.
Version: 2.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10016.
 System.IO.IOException: Cannot create a file when that file already exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at Starcounter.Server.DatabaseSetup.CreateFiles() in d:\code\Starcounter\Develop\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseSetup.cs:line 120
   at Starcounter.Server.DatabaseSetup.CreateDatabase() in d:\code\Starcounter\Develop\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseSetup.cs:line 134
   at Starcounter.Server.Commands.CreateDatabaseCommandProcessor.Execute() in d:\code\Starcounter\Develop\Level1\src\Server\Starcounter.Server\Commands\Processors\CreateDatabaseCommandProcessor.cs:line 34
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in d:\code\Starcounter\Develop\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 298
HResult=-2147024713
```

The cause seems to be that the administrator creates a backup file for the configuration and the delete operation does not delete it properly. In my case `Databases\default\default.db.config.bak`

I got the same behaviour by manually editing the file with notepad++ and having backup enabled in notepad++, so it looks like any file that gets added that does not follow a specific pattern will mess things up.

If I manually delete the `default` folder and the file inside I can create the database again.

**Comment by per-samuelsson** [comment]
Thanks for producing such good description. This clearly is a bug. I'll assign it to me to fix.

**Comment by per-samuelsson** [comment]
Had a good discussion with @chrhol on how to best solve this where he gave some feedback we decided to go with.

First of all, this

> I got the same behaviour by manually editing the file with notepad++ and having backup enabled in notepad++, **so it looks like any file that gets added that does not follow a specific pattern will mess things up**.

is by design. I choose that approach to assure we don't risk deleting files by accident. It's similar to how `MsBuild | Clean` work - it cleans only those files managed by itself / belonging to the project.

We decided to tackle this in two ways:

1. We'll drop generating `.bak` files ourselves, since they are kind of a legacy, and not something we really use.
2. We'll stick with the same strategy, but we will add a more specific error when a database is being created and the deleted one has not fully deleted all content. The user should get an error saying what folder contains files we don't want to delete, and be asked to delete them manually.
