### ISSUE TITLE
Non-informative NullReferenceException when binding a data property to an empty array item in JSON-by-example

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#3526]
I encountered it by accident. When you declare an **empty** array item in JSON-by-example that has the same key name as a property name in the bound data object, you end up with an exception that doesn't give any meaningful clue.

This is my `Person.cs`:

```cs
[Database]
public class Person {
    public string FirstName;
    public string LastName;

    public IEnumerable<Expense> Expenses => Db.SQL<Expense>("SELECT e FROM Expense e WHERE e.Spender = ?", this);

    public decimal Total => Db.SQL<decimal>("SELECT SUM(e.Amount) FROM Expense e WHERE e.Spender = ?", this).First;
}
```

This is my `PersonJson.json`:

```json
{
    "Html": "/HelloWorld/PersonJson.html",
    "FirstName$": "",
    "Expenses": [
        {
        }
    ],
    "NewExpense": {
        "Description$": "",
        "Amount$": 0.0
    },
    "Add$": 0,
    "Total": 0.0,
    "ClearAll$": 0
}
```

*Note that the JSON `Expenses` array item has no properties declared.*

When I start the app, I get the following exception:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Starcounter.Json.CheckBoundArray(IEnumerable boundValue) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-282\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 392
   at Starcounter.Json.Refresh(Template property) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-282\Level1\src\Starcounter.XSON\Class Json\Json.cs:line 299
   at Starcounter.Json.InternalSetData(Object data, TValue template, Boolean updateBinding) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-282\Level1\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 94
   at Starcounter.Internal.TransactionManager.Scope[T1,T2](TransactionHandle handle, Action`2 action, T1 arg1, T2 arg2) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-282\Level1\src\Starcounter\TransactionManager.cs:line 476
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2](Json json, Action`2 action, T1 arg1, T2 arg2) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-282\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 84
   at Starcounter.Json.set_Data(Object value) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-282\Level1\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 38
   at HelloWorld.PersonJson.set_Data(Person value) in c:\www\warpech\HelloWorld\obj\x64\Debug\ViewModel\PersonJson.json.g.cs:line 0
   at HelloWorld.Program.<>c.<Main>b__0_2() in c:\www\warpech\HelloWorld\Program.cs:line 25
   at Starcounter.Db.Scope[TResult](Func`1 func, Boolean isReadOnly) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-282\Level1\src\Starcounter\Db.cs:line 484
   at HelloWorld.Program.<>c.<Main>b__0_1() in c:\www\warpech\HelloWorld\Program.cs:line 24
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-282\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-282\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-282\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 598
HResult=-2147467261

More information about this error may be available in the server error log.
```

The smallest app that reproduces it (with middleware): https://github.com/warpech/HelloWorld/tree/Starcounter_issue_3526

Steps to reproduce:

1. Start the project
2. Load `http://localhost:8080/helloworld` in your browser
3. Press the "Add" button 
4. You immediately get the stack trace in Administrator
5. Load `http://localhost:8080/helloworld` in your browser again
6. Now you also see the stack trace in the web browser

![2016-04-21 17_26_34-helloworld debugging - microsoft visual studio](https://cloud.githubusercontent.com/assets/566463/14714689/3de92830-07e6-11e6-9def-38ae4788b03a.png)

**Comment by chrhol** [comment]
Wow, this feels like the first thing to test. I assign it to me to fix

**Comment by chrhol** [comment]
It was not my intention to close this issue :) I have pushed a fix to develop though, and in a while to pnext. Will reopen it again so you can verify that it actually fixed the problem @warpech

**Comment by chrhol** [comment]
Just to clarify: If the binding is not explicitly specifed (I.e. using the default auto-binding, which means it will try to bind) the array will be treated as unbound if it is declared as untyped/empty.

If the binding is specified, an exception will be raised:

**Comment by chrhol** [comment]
I will just consider this issue resolved. If not, lets reopen it later.
