### ISSUE TITLE
Utilize newly installed memory with the same database image?

### ISSUE THREAD

**Issue by mtornwall** [Starcounter/Starcounter#3534]
It seems to be well-known (thought I'm not sure if it's clearly stated anywhere in the documentation) that the size of the initial database image is determined by the amount of installed memory at the time of its creation.

Now, suppose that I'd like to scale the capacity of my servers based on actual demand. I start off with a virtual machine with relatively low memory (say, 4 to 8 GiB). I then gradually increase the amount of memory allocated to the VM as database grows.

Can I expect this to work seamlessly, i.e., without requiring a database unload/reload?

**Comment by per-samuelsson** [comment]
cc @eriohl

**Comment by per-samuelsson** [comment]
@mtornwall, 

if you don't explicitly specify anything different, we are assuming 2.x-based version, either latest stable or nightly (i.e. not one of the pnext-builds, and neither 1.x).

**Comment by eriohl** [comment]
This is addressed in the latest version (2.3/pnext).

(Although you will still have to restart the server process. There is no support for hot add memory currently. But there is no need to an unload/reload.)

**Comment by mtornwall** [comment]
> if you don't explicitly specify anything different, we are assuming 2.x-based version, either latest stable or nightly (i.e. not one of the pnext-builds, and neither 1.x).

Oops, sorry. I've just switched to 2.2.x, so I'm not on `pnext`.

> (Although you will still have to restart the server process. There is no support for hot add memory currently. But there is no need to an unload/reload.)

Meaning that until I switch to `pnext` I will indeed have to unload and reload?

**Comment by eriohl** [comment]
> > (Although you will still have to restart the server process. There is no support for hot add memory currently. But there is no need to an unload/reload.)

> Meaning that until I switch to pnext I will indeed have to unload and reload?

I can't tell you this for sure since I'm not involved in planning at that level but I think that a pretty safe bet yes.

**Comment by mtornwall** [comment]
Then I will operate under that assumption.

Thanks for clarifying.

**Comment by k-rus** [comment]
It is not said explicitly, but I guess new database needs to be created, which means that data needs to be transferred from the old database to new one. We don't provide such functionality, so unload/reload can be used for it.

**Comment by dan31** [comment]
@mtornwall 2.3/pnext is to replace develop as a next major release that we plan for June. However, we already have a customer staging 2.3/pnext (because of a log streaming facility for replication). We carefully add all fixes and changes from develop (2.2.x) into 2.3. When we release 2.3, there will be no pnext and develop, but only single develop. 2.3/pnext has a new storage format, you will have to migrate the data via unload/reload. If the issue with memory is critical right now, you might stage 2.3 as well. It even has more tests today than 2.2/develop :) Tell me if you want to give it a try.

**Comment by mtornwall** [comment]
@dan31 So it turns out I can't unload the database either, due to a supposedly nonexistent table (added to the data model quite recently) that definitely does exist when you run the same query in the administrator:

~~~
Starcounter.DbException: ScErrFailingEntrypoint (SCERR4259): The user code entrypoint method raised an exception. Failed to process query: SELECT __o as __id,"AllowCommunityDownload","AllowCommunityUpload","CreatedAt","Owner" FROM "Blundermail"."Hive"."Concepts"."Ring4"."UserOrganizationPreferences" __o: Unknown class Blundermail.Hive.Concepts.Ring4.UserOrganizationPreferences. Unknown property or alias AllowCommunityDownload. Unknown property or alias AllowCommunityUpload. Unknown property or alias CreatedAt. Unknown property or alias Owner.
End position: -1

Version: 2.2.1877.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4259.
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application, Assembly assembly) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-290\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 600
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application, ApplicationDirectory applicationDir) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-290\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 263
   at Starcounter.Hosting.Package.Process() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-290\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 138
   at Starcounter.Hosting.Package.Process(IntPtr hPackage) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-290\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 55
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-290\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 66
ErrorCode=4259
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4259
---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application, Assembly assembly) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-290\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 587
HResult=-2146232828
---> Starcounter.SqlException: Failed to process query: SELECT __o as __id,"AllowCommunityDownload","AllowCommunityUpload","CreatedAt","Owner" FROM "Blundermail"."Hive"."Concepts"."Ring4"."UserOrganizationPreferences" __o: Unknown class Blundermail.Hive.Concepts.Ring4.UserOrganizationPreferences. Unknown property or alias AllowCommunityDownload. Unknown property or alias AllowCommunityUpload. Unknown property or alias CreatedAt. Unknown property or alias Owner.
   at Starcounter.Query.QueryPreparation.PrepareOrExecuteQuery[T](String query, Boolean slowSql, Object[] values) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-290\Level1\src\Starcounter\Query\QueryPreparation.cs:line 67
   at Starcounter.Query.Sql.SqlEnumCache.CacheOrExecuteEnumerator[T](String query, Boolean slowSQL, Object[] values) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-290\Level1\src\Starcounter\Query\SQL\_SqlEnumCache.cs:line 127
   at Starcounter.Db.FullQueryProcess[T](String query, Boolean slowSQL, Object[] values) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-290\Level1\src\Starcounter\Mock\Db.cs:line 123
   at Starcounter.Reload.Unload(String fileName, UInt64 shiftId, Boolean unloadAll) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-290\Level1\src\Starcounter\Mock\Reload.cs:line 97
   at UnloadDatabase.Program.Main(String[] args) in c:\Program Files\Starcounter\cli-apps\UnloadDatabase.cs:line 34
ScErrorCode=0
BeginPosition=-1
EndPosition=-1
HResult=-2146233088
~~~

**Comment by dan31** [comment]
@k-rus can you take a look? I thought we had such issue and you've been fixing it in unload/reload. probably the fix didn't span all the needed cases.

**Comment by k-rus** [comment]
Unload requires that old database classes are loaded. The above SQL error indicates that the class was not loaded for the existing table.

**Comment by mtornwall** [comment]
@k-rus The assembly containing the type was most definitely loaded. Any other reason this might occur?

**Comment by mtornwall** [comment]
Furthermore this particular class has never changed. It was committed in its entirety about a month back and has been present in the production databases since.

**Comment by k-rus** [comment]
@mtornwall It is better to start separate issue.
