### ISSUE TITLE
Database unload fails

### ISSUE THREAD

**Issue by mtornwall** [Starcounter/Starcounter#3536]
*This is a continuation of a discussion started in #3534.*

After upgrading to v2.2.1834 I tried to unload one of my production databases in order to rebuild it in a larger database image (mind you, I haven't tried unloading before so this could be present in v2.1.177 as well). Even though all relevant assemblies should be loaded I get the following exception:

~~~
Starcounter.DbException: ScErrFailingEntrypoint (SCERR4259): The user code entrypoint method raised an exception. Failed to process query: SELECT __o as __id,"AllowCommunityDownload","AllowCommunityUpload","CreatedAt","Owner" FROM "Redacted"."Hive"."Concepts"."Ring4"."UserOrganizationPreferences" __o: Unknown class Redacted.Hive.Concepts.Ring4.UserOrganizationPreferences. Unknown property or alias AllowCommunityDownload. Unknown property or alias AllowCommunityUpload. Unknown property or alias CreatedAt. Unknown property or alias Owner.
End position: -1

Version: 2.2.1877.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4259.
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application, Assembly assembly) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-290\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 600
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application, ApplicationDirectory applicationDir) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-290\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 263
   at Starcounter.Hosting.Package.Process() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-290\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 138
   at Starcounter.Hosting.Package.Process(IntPtr hPackage) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-290\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 55
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-290\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 66
ErrorCode=4259
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4259
---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application, Assembly assembly) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-290\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 587
HResult=-2146232828
---> Starcounter.SqlException: Failed to process query: SELECT __o as __id,"AllowCommunityDownload","AllowCommunityUpload","CreatedAt","Owner" FROM "Redacted"."Hive"."Concepts"."Ring4"."UserOrganizationPreferences" __o: Unknown class Redacted.Hive.Concepts.Ring4.UserOrganizationPreferences. Unknown property or alias AllowCommunityDownload. Unknown property or alias AllowCommunityUpload. Unknown property or alias CreatedAt. Unknown property or alias Owner.
   at Starcounter.Query.QueryPreparation.PrepareOrExecuteQuery[T](String query, Boolean slowSql, Object[] values) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-290\Level1\src\Starcounter\Query\QueryPreparation.cs:line 67
   at Starcounter.Query.Sql.SqlEnumCache.CacheOrExecuteEnumerator[T](String query, Boolean slowSQL, Object[] values) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-290\Level1\src\Starcounter\Query\SQL\_SqlEnumCache.cs:line 127
   at Starcounter.Db.FullQueryProcess[T](String query, Boolean slowSQL, Object[] values) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-290\Level1\src\Starcounter\Mock\Db.cs:line 123
   at Starcounter.Reload.Unload(String fileName, UInt64 shiftId, Boolean unloadAll) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-290\Level1\src\Starcounter\Mock\Reload.cs:line 97
   at UnloadDatabase.Program.Main(String[] args) in c:\Program Files\Starcounter\cli-apps\UnloadDatabase.cs:line 34
ScErrorCode=0
BeginPosition=-1
EndPosition=-1
HResult=-2146233088
~~~

The `UserOrganizationPreferences` class was created relatively recently and thus was added to the production database long after it was originally created. The class definition itself has never changed. Manually running the failing query from the exception above in the administrator works without any errors.

cc @k-rus

**Comment by k-rus** [comment]
Thank you for creating separate issue and reporting the problem.
I guess the version of Starcounter you are using do not implement app isolation. @dan31 right? So #3399 is not related.

I am wonder how to reproduce it on a simpler example.

Can you try to create a small app, which calls the above query? I believe you should not get the problem, but currently I am lack of ideas. Somehow it should be difference between Admin app and Unload app that the first get everything working, while the later does not get all database classes.

**Comment by mtornwall** [comment]
> I guess the version of Starcounter you are using do not implement app isolation. @dan31 right? So #3399 is not related.

@k-rus If you're talking about "SQL Isolation" I believe it's been implemented since sometime in September:

https://github.com/Starcounter/Starcounter/commit/b1ef8474bf4fa3469ee4dafeddc2c1018623e8d4

**Comment by k-rus** [comment]
> @k-rus If you're talking about "SQL Isolation" I believe it's been implemented since sometime in September:
> 
> b1ef847

I thought it was done in pnext, but actually it is in develop. I will check if Unload script was updated accordantly.

**Comment by k-rus** [comment]
This issue might be due to #3399, since isolated apps are implemented already in develop, while the fix for unload was made in pnext. I will implement the fix in develop.

**Comment by dan31** [comment]
Thanks for verifying @k-rus, frankly when it was introduced we haven't even shipped pnext to users (it was 2 months prior to the BAH initiative).

**Comment by k-rus** [comment]
@dan31 
Should this fix be part of 2.2.1 release?

**Comment by dan31** [comment]
@k-rus there is no chance for a fix to be part of any other release, since what you fix is already in Nightly, hence the fix will pop in 2.2.1.

**Comment by k-rus** [comment]
> @k-rus there is no chance for a fix to be part of any other release, since what you fix is already in Nightly, hence the fix will pop in 2.2.1.

The fix is not done, thus I am asking.

**Comment by dan31** [comment]
@k-rus I think it is better to do it the soonest, otherwise @mtornwall is impeded to upgrade his hardware.

**Comment by k-rus** [comment]
> @k-rus I think it is better to do it the soonest, otherwise @mtornwall is impeded to upgrade his hardware.

I will add it to the list and will try to fix today.

**Comment by dan31** [comment]
That'd be great @k-rus, thanks!

**Comment by k-rus** [comment]
Fixed in develop and correctly merged into pnext, however I was not able to exclude the test from daily build.

**Comment by mtornwall** [comment]
I can confirm that the fix resolves my problem. I just managed to unload 33 million objects without issue.

Thanks @k-rus !

**Comment by k-rus** [comment]
> I can confirm that the fix resolves my problem. I just managed to unload 33 million objects without issue.

Wow

Thank you for confirming!
