### ISSUE TITLE
Unable to create array of arrays in JSON

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3554]
I am trying to create array of arrays in my JSON view-model:

```json
"HotRows": [
    [
        { "HasValue": true, "Value: "" }
    ]
]
```

But getting the following error on compilation:

```
Expected "Object, string, boolean, event, number" but found a Array
  ([Object
      ([("HasValue", Boolean (true,Starcounter.Internal.JsonTemplate.DebugInfo));
        ("Value", String ("",Starcounter.Internal.JsonTemplate.DebugInfo))],
       Starcounter.Internal.JsonTemplate.DebugInfo)],
   Starcounter.Internal.JsonTemplate.DebugInfo)
```

cc @chrhol

**Comment by chrhol** [comment]
Thanks for reporting. This exception comes from the F# parser, so something there is not expecting an array. Will take a look.

**Comment by chrhol** [comment]
I've pushed a fix for this to develop now. As I suspected it was some old code in the parser that didn't allow having an array in an array. Should work now.

Will merge to pnext when the builds there succeeds again.

**Comment by chrhol** [comment]
Everything is merged now.

**Comment by miyconst** [comment]
Now I can create array of array, but using such view-model causes the following error:

```
"System.NullReferenceException: Object reference not set to an instance of an object.
   at Starcounter.Templates.TObjArr.Checkpoint(Json parent) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1621\Level1\src\Starcounter.XSON\Templates\TObjArr.cs:line 125
   at Starcounter.Json.CheckpointChangeLog(Boolean callStepSiblings) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1621\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 41
   at Starcounter.Templates.TObjArr.Checkpoint(Json parent) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1621\Level1\src\Starcounter.XSON\Templates\TObjArr.cs:line 127
   at Starcounter.Json.<>c.<CheckpointChangeLog>b__118_0(Json parent, TValue tjson) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1621\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 55
   at Starcounter.Internal.TransactionManager.Scope[T1,T2](TransactionHandle handle, Action`2 action, T1 arg1, T2 arg2) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1621\Level1\src\Starcounter\TransactionManager.cs:line 476
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2](Json json, Action`2 action, T1 arg1, T2 arg2) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1621\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 84
   at Starcounter.Json.CheckpointChangeLog(Boolean callStepSiblings) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1621\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 48
   at Starcounter.Templates.TObject.Checkpoint(Json parent) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1621\Level1\src\Starcounter.XSON\Templates\TObject.cs:line 84
   at Starcounter.Json.<>c.<CheckpointChangeLog>b__118_0(Json parent, TValue tjson) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1621\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 55
   at Starcounter.Internal.TransactionManager.Scope[T1,T2](TransactionHandle handle, Action`2 action, T1 arg1, T2 arg2) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1621\Level1\src\Starcounter\TransactionManager.cs:line 476
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2](Json json, Action`2 action, T1 arg1, T2 arg2) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1621\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 84
   at Starcounter.Json.CheckpointChangeLog(Boolean callStepSiblings) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1621\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 48
   at Starcounter.Internal.PuppetRestHandler.<>c.<RegisterJsonPatchHandlers>b__4_1(Request request, Session session) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1621\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 116
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1621\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1621\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1621\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 598
HResult=-2147467261
"
```

The example can be seen in my [Playground](https://github.com/miyconst/Playground/). Just start the app and go to `http://localhost:8080/playground`.

**Comment by chrhol** [comment]
It looks like some parts in the generated code is not correct, not only for arrays and it's been this way a long time :)

It always take some time to work with the codegenerator. It's quite difficult to debug and it's hard to change without messing something else up. I plan on having a fix for this pushed tomorrow.

**Comment by chrhol** [comment]
Actually, my previous comment was not correct. The code for checkpointing arrays was incorrectly implemented.

I will push a fix for this soon.

**Comment by chrhol** [comment]
Pushed now and tested in Playground.

**Comment by miyconst** [comment]
Thanks @chrhol, is there a daily build I can test?

**Comment by chrhol** [comment]
I can make one for you, do you have access to teamcity?

**Comment by miyconst** [comment]
I can build one myself, just checked maybe you already have it.

**Comment by chrhol** [comment]
Aha, yeah I started one so the last daily build should have an installer in artifacts

**Comment by miyconst** [comment]
Thanks. I have tested the build, the issue is fixed.
