### ISSUE TITLE
Database crashes when trying to access a nont existing JSON["property"]

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3571]
Found in Launcher, when an app responses with a `Json`, not a `Page`.

```
"System.NullReferenceException: Object reference not set to an instance of an object.
   at Starcounter.Json.get_Item(String key) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-298\Level1\src\Starcounter.XSON\Class Json\Json.cs:line 427
   at Launcher.LauncherHelper.OnJsonMerge(Request request, String callingAppName, IEnumerable`1 partialJsons) in C:\GitHub\Samples\Launcher\src\Launcher\Api\LauncherHelper.cs:line 235
   at Starcounter.Internal.JsonResponseMerger.JsonMergeCallback.<>c__DisplayClass2_0.<Invoke>b__0() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-298\Level1\src\Starcounter\Apps\JsonResponseMerger.cs:line 18
   at Starcounter.Internal.StarcounterEnvironment.RunWithinApplication(String desiredAppName, Action action) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-298\Level1\src\Starcounter.Internal\Mock\StarcounterEnvironment.cs:line 123
   at Starcounter.Internal.JsonResponseMerger.JsonMergeCallback.Invoke(Request request, String callingAppName, IEnumerable`1 mergedJsons) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-298\Level1\src\Starcounter\Apps\JsonResponseMerger.cs:line 17
   at Starcounter.Internal.JsonResponseMerger.TriggerAfterMergeCallback(Request request, Json json) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-298\Level1\src\Starcounter\Apps\JsonResponseMerger.cs:line 179
   at Starcounter.Internal.JsonResponseMerger.DefaultMerger(Request req, Response resp, List`1 responses) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-298\Level1\src\Starcounter\Apps\JsonResponseMerger.cs:line 42
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-298\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 253
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-298\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-298\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 598
HResult=-2147467261
"
```

cc @chrhol

**Comment by miyconst** [comment]
The returned `Json` should be without  `.json` file to cause this error.

**Comment by chrhol** [comment]
The problem is that the Json does not have a template. I'm not sure (as we discussed) that this is ok, since the whole point of TypedJson is to have the template define what values the instance has. Also there is a risk that other places will also not work. For example trying to serialize it, will probably fail (or maybe return empty result).

Anyway, this part is solved and pushed to develop. When using the `json["propertyName"] syntax, the template is checked so that it actually exists.
