### ISSUE TITLE
htmlmerger should ignore, but not crash if one of the provided values is empty

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3572]
Such url should not crash htmlmerger:

```
http://localhost:8080/sc/htmlmerger?Launcher=&SignIn=%2FSignIn%2Fviewmodels%2FSignInPage.html
```

```
System.ArgumentOutOfRangeException: Self should be called with URI starting with a slash.
Parameter name: %2FSignIn%2Fviewmodels%2FSignInPage.html
   at Starcounter.Self.DoSelfCall(UInt16 portNumber, String method, String relativeUri, Dictionary`2 headersDictionary, String body, Byte[] bodyBytes, HandlerOptions handlerOptions, Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-301\Level1\src\Starcounter.Internal\Rest\Self.cs:line 340
   at Starcounter.Self.GET(String uri) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-301\Level1\src\Starcounter.Internal\Rest\Self.cs:line 74
   at Launcher.LauncherHelper.<>c.<Init>b__0_10(String s) in C:\GitHub\MM\Launcher\src\Launcher\Api\LauncherHelper.cs:line 132
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-301\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-301\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-301\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 598
ParamName=%2FSignIn%2Fviewmodels%2FSignInPage.html
HResult=-2146233086

More information about this error may be available in the server error log.
```

cc @chrhol

**Comment by dan31** [comment]
CC @alemoi ?

**Comment by chrhol** [comment]
This is because the url needs to be decoded before the `Self.GET` is called. It's added in the htmlmerger in Starcounter and in prefab launcher, but probably not in the forked launchers.

**Comment by miyconst** [comment]
My bad, internal Starcounter's merger does not crash, it was an issue in the Launcher itself. Already fixed.

**Comment by miyconst** [comment]
@chrhol thank you for the tip.
