### ISSUE TITLE
Administrator crashes in TypedJson trying to show results of SELECT

### ISSUE THREAD

**Issue by linkdata** [Starcounter/Starcounter#3585]
Admittedly I'm pushing hard on it, but it shouldn't throw an exception when being asked to render a query result.

`select * from LogStreamerBulker.Record`

```
System.Exception: TypedJson serializer: written size is larger than size of destination! (written: 34, destination: 1)
Type: Starcounter.Json, DebugString: <value: Starcounter.Arr`1[Starcounter.Json]><app: <null>>{
   "_0":<value: 923>,
   "_1":<value: 426426>,
   "_2":<value: anteater/repl0>,
   "_3":<value: >,
   "_4":<value: >,
   "_5":<value: 9223372036854775806>,
   "_6":<value: 1>,
   "_7":<value: -4398046511101,772959>,
   "_8":<value: -3,40282346638529E+38>,
   "_9":<value: 2,77891869134219>,
   "_10":<value: 923>,
   "_11":<value: Ob>
}
   at Starcounter.Advanced.XSON.StandardJsonSerializerBase.AssertWrittenSize(Json json, Int32 realSize, Int32 destSize) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 110
   at Starcounter.Advanced.XSON.StandardJsonSerializerBase.Serialize(Json json, IntPtr dest, Int32 destSize) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 79
   at Starcounter.Json.ToJsonUtf8(IntPtr dest, Int32 destSize) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter.XSON\Class Json\Json.Serializing.cs:line 99
   at Starcounter.Advanced.XSON.StandardJsonSerializerBase.SerializeArray(TypedJsonSerializer serializer, Json json, IntPtr dest, Int32 destSize) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 547
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3,T4,TResult](Json json, Func`5 func, T1 arg1, T2 arg2, T3 arg3, T4 arg4) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 231
   at Starcounter.Advanced.XSON.StandardJsonSerializerBase.ScopeAndSerializeArray(TypedJsonSerializer serializer, Json json, Template template, IntPtr dest, Int32 destSize) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 526
   at Starcounter.Advanced.XSON.StandardJsonSerializerBase.SerializeObject(TypedJsonSerializer serializer, Json json, IntPtr dest, Int32 destSize) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 419
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3,T4,TResult](Json json, Func`5 func, T1 arg1, T2 arg2, T3 arg3, T4 arg4) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 231
   at Starcounter.Advanced.XSON.StandardJsonSerializerBase.ScopeAndSerializeObject(TypedJsonSerializer serializer, Json json, Template template, IntPtr dest, Int32 destSize) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 330
   at Starcounter.Advanced.XSON.StandardJsonSerializerBase.SerializeObject(TypedJsonSerializer serializer, Json json, IntPtr dest, Int32 destSize) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 419
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3,T4,TResult](Json json, Func`5 func, T1 arg1, T2 arg2, T3 arg3, T4 arg4) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 231
   at Starcounter.Advanced.XSON.StandardJsonSerializerBase.ScopeAndSerializeObject(TypedJsonSerializer serializer, Json json, Template template, IntPtr dest, Int32 destSize) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 330
   at Starcounter.Advanced.XSON.StandardJsonSerializerBase.<Serialize>b__7_0(TypedJsonSerializer tjs, Json j, IntPtr d, Int32 ds) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 70
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3,T4,TResult](Json json, Func`5 func, T1 arg1, T2 arg2, T3 arg3, T4 arg4) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 231
   at Starcounter.Advanced.XSON.StandardJsonSerializerBase.Serialize(Json json, IntPtr dest, Int32 destSize) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializer.cs:line 65
   at Starcounter.Json.ToJsonUtf8() in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter.XSON\Class Json\Json.Serializing.cs:line 70
   at Starcounter.Internal.JsonMimeConverter.Convert(Request request, IResource before, MimeType mimeType, MimeType& resultingMimeType) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\JsonMimeConverter.cs:line 36
   at Starcounter.Json.AsMimeType(MimeType mimeType, MimeType& resultingMimeType, Request request) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter.XSON\Class Json\Json.IResource.cs:line 42
   at Starcounter.Response.ConstructFromFields(Request req, Byte[] givenBuffer) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter.Internal\Http\Response.cs:line 809
   at Starcounter.Request.SendResponse(Response resp, Byte[] serializationBuf) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter.Internal\Http\Request.cs:line 1241
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 609
HResult=-2146233088
```

**Comment by chrhol** [comment]
What do you mean by pushing it hard? Executing the query several times, or do you get this every time? 

Anyhow, something is really wrong here, since what fails is that the buffer allocated for the json-response is way off so I guess either there is a bug calculating needed size or there is some synchronization issue when it comes to creating and returning sql from administrator.

**Comment by linkdata** [comment]
> What do you mean by pushing it hard?

Run the latest [LogStreamerBulker](https://github.com/StarcounterSamples/LogStreamerBulker) for a while, then start selecting from the table like this, incrementing `oid` by 1000 to select different portions:

`select * from LogStreamerBulker.Record where oid > 0`

I usually hit a crashing combination on the second or third select. Fully reproducible.

**Comment by chrhol** [comment]
Thanks, by coincidence @andwah just showed me how to reproduce #3589, using the same steps.

I think this problem and that one might be the same root cause. Some strings are not encoded correctly and either the output-buffer is not big enough due to this or characters that are not supported unencoded slips through. 

I'm looking into it now.

**Comment by chrhol** [comment]
(just saw the other issue that you already made that assumption)

**Comment by linkdata** [comment]
This was due to `double` being assumed to be at most 32 characters as a string, but using a `ToString("0.0#############################")` pattern that allowed more than 30 digits after the decimal point, meaning any large number with a repeating fractions pattern when converting to base-10 would overflow it.

Changing to `ToString("G17")` should fix it. [See here](https://msdn.microsoft.com/en-us/library/kfsatb94(v=vs.110).aspx) for a short discussion of the why and how's of double-to-string conversions.

**Comment by chrhol** [comment]
> Changing to ToString("G17") should fix it. See here for a short discussion of the why and how's of double-to-string conversions.

There is one problem with this, and that is that a couple of years ago we changed it so that doubles always are represented with decimal point if no decimals are present, so the double value `23` or `23.0` is always sent as `23.0` and not as `23`. I don't remember the exact reasoning for this, maybe to distinguish between integers and non-integers? But using ToString("G17") this is again present. 

So either this also need to be considered, before pushing the fix or we should reconsider always sending doubles with decimal point.

@andwah do you remember why we did it?

**Comment by linkdata** [comment]
I guess we could simply append `".0"` if the resulting string has no decimal point in it.

**Comment by linkdata** [comment]
Another thing: the "G17" format allows for the result to be in scientific notation if it would be more compact than otherwise. Is that a problem?

**Comment by chrhol** [comment]
> Another thing: the "G17" format allows for the result to be in scientific notation if it would be more compact than otherwise. Is that a problem?

I've looked through our (Starcounter) apps and external apps and could only find one place where double is used today (in TypedJSON) and that was in the Cartographer app, and that one doesn't seem to be updated for some time. At least I could not get it to work. 

Based on that together with that according to the Json rfc, scientific notation is a valid format for numbers, I cannot se any direct problems with changing the behaviour.

Maybe @warpech, @tomalec or @miyconst have some input regarding having numbers in scientific notation on the client? 

I will assume it's ok and move forward with the fix.

**Comment by andwah** [comment]
> @andwah do you remember why we did it?

im just guessing...

maybe by having a decimal point "." in the json on a number you maybe know what type to generate in the template? (when editing json directly in visual studio?)

**Comment by chrhol** [comment]
Fix pushed last night to develop and pnext, so it's included in the last nightly. 

After the fix I have not been able to reproduce this issue (or the other one).

**Comment by warpech** [comment]
We also use doubles in KitchenSink (Map Page aka "GeoPage"). I am fine with the change, I think it will work with no problem on the client.
