### ISSUE TITLE
Administrator doesn't support unsigned longs

### ISSUE THREAD

**Issue by linkdata** [Starcounter/Starcounter#3587]
`select * from LogStreamerBulker.Record r where t_ulong = 18446744073709551615`

```
System.OverflowException: Value was either too large or too small for an Int64.
   at System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   at Starcounter.Query.Sql.Creator.IntegerParse(String literal) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter\Query\SQL\_Creator.cs:line 2356
   at Starcounter.Query.Sql.Creator.CreateIntegerLiteral(Term literalTerm) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter\Query\SQL\_Creator.cs:line 2369
   at Starcounter.Query.Sql.Creator.CreateValueExpression(RowTypeBinding rowTypeBind, Term exprTerm, VariableArray varArray) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter\Query\SQL\_Creator.cs:line 2011
   at Starcounter.Query.Sql.Creator.CreateComparisonNumerical(RowTypeBinding rowTypeBind, Term opTerm, Term exprTerm1, Term exprTerm2, VariableArray varArray) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter\Query\SQL\_Creator.cs:line 1275
   at Starcounter.Query.Sql.Creator.CreateLogicalExpression(RowTypeBinding rowTypeBind, Term term, VariableArray varArray) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter\Query\SQL\_Creator.cs:line 1045
   at Starcounter.Query.Sql.Creator.MapTermsToOptimizerInput(RowTypeBinding rowTypeBind, Term nodeTreeTerm, Term whereCondTerm, Term orderbyComparerListTerm, Term fetchTerm, Term hintListTerm, VariableArray varArray, String query) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter\Query\SQL\_Creator.cs:line 133
   at Starcounter.Query.Sql.Creator.CreateOptimizerInput(RowTypeBinding rowTypeBind, Term term, VariableArray varArray, String query) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter\Query\SQL\_Creator.cs:line 76
   at Starcounter.Query.QueryPreparation.PrepareOrExecuteQuery[T](String query, Boolean slowSql, Object[] values) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter\Query\QueryPreparation.cs:line 69
   at Starcounter.Query.Sql.SqlEnumCache.CacheOrExecuteEnumerator[T](String query, Boolean slowSQL, Object[] values) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter\Query\SQL\_SqlEnumCache.cs:line 127
   at Starcounter.Db.FullQueryProcess[T](String query, Boolean slowSQL, Object[] values) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter\Mock\Db.cs:line 128
   at Starcounter.Db.SlowSQL(String query, Object[] values) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter\Mock\Db.cs:line 104
   at Starcounter.Internal.SqlRestHandler.ExecuteQuery(String query, Int32 maxResult) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\SqlRestHandler.cs:line 77
HResult=-2146233066
```

Also, `SELECT *` on the data has the unsigned values show as negative. Basically, the underlying code does a bitwise copy of the unsigned data and interprets it as a signed value.

**Comment by chrhol** [comment]
Does this really have something to do with Administrator? It looks like from the stacktrace, that it comes from the sqlparser when the literal is included in the query (i.e. using `Db.SlowSQL`)

**Comment by chrhol** [comment]
Duplicate of #2988

**Comment by linkdata** [comment]
> Does this really have something to do with Administrator? It looks like from the stacktrace, that it comes from the sqlparser when the literal is included in the query (i.e. using Db.SlowSQL)

Yeah, that sounds about right.

**Comment by linkdata** [comment]
Closing this since it's a duplicate of #2988
