### ISSUE TITLE
One or both of the image files are missing error

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3603]
There is a database called `playgruond`.

I try to start an app from Visual Studio with `-d=playground_0`, at this moment all Starcounter services are killed. This ends with the following error:

```
"Starcounter.DbException: ScErrCantFindImageFile (SCERR4117): One or both of the image files are missing. Version: 2.2.1.2075. Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4117. 
   at Starcounter.Server.DatabaseEngine.WaitUntilCodeHostOnline(Process codeHostProcess, Database database) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1621\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseEngine.cs:line 370
   at Starcounter.Server.Commands.Processors.StartDatabaseCommandProcessor.<>c__DisplayClass2_0.<Execute>b__3(CommandTask task) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1621\Level1\src\Server\Starcounter.Server\Commands\Processors\StartDatabaseCommandProcessor.cs:line 82
   at Starcounter.Server.Commands.CommandProcessor.<>c__DisplayClass68_0.<WithinTask>b__0(CommandTask t) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1621\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 484
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1621\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 510
   at Starcounter.Server.Commands.Processors.StartDatabaseCommandProcessor.Execute() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1621\Level1\src\Server\Starcounter.Server\Commands\Processors\StartDatabaseCommandProcessor.cs:line 87
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1621\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
ErrorCode=4117
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4117
"
```

cc @alemoi

**Comment by alemoi** [comment]
Thanks for reporting! I am not sure I'm the best to answer here. Would CC to @per-samuelsson

**Comment by per-samuelsson** [comment]
@miyconst 

That's weird. And you haven't moved any files around manually I presume?

Can you go into `\Documents\Starcounter\Personal\Databases\Playground` and look in `Playground.db.config`. It should have an `<ImageDirectory>` tag. Can you verify the image files are in that destination? 

If you are running a `2.x` version, there should be a set of files with a `.sci`-extension pattern. And for `pnext` versions, expect to see `.log` + `.cfg` files.

Could it be that you use the same repository and install/uninstall different main versions (i.e. `2.x` <-> `pnext`)?

**Comment by miyconst** [comment]
I didn't move any files manually.

Unfortunately I removed that folder manually, because administrator failed to start or remove database.

As I remember there were files with `.sci` extension. It was Starcounter `2.2.1.x` nightly build, and both of the databases were created under the same instance of Starcounter.

**Comment by per-samuelsson** [comment]
OK, then it's kind of hard to do anything at this point, if there's no faulty environment to investigate. I suggest we close this issue, and see if we should hit it again. You've got some other idea, @miyconst?

**Comment by miyconst** [comment]
I have a better idea :).

The issue is reproducible on my machine, running the latest nightly build (`Starcounter-DevelopNightlyBuilds-2.2.1.2086 (May 11, 2016 4:58:42 AM)`).

Structure of my `C:\Users\const\Documents\Starcounter\Personal\Data` folder:

```
Data
- playground_0
-- playground_0-20160511T111839102
--- playground_0.0.sci
--- playground_0.0.sci2
--- playground_0.1.sci
--- playground_0.1.sci2
```

Content of my `C:\Users\const\Documents\Starcounter\Personal\Databases\playground_0\playground_0.db.config` file:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Database xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.starcounter.com/configuration">
  <Runtime>
    <LoadEditionLibraries>true</LoadEditionLibraries>
    <WrapJsonInNamespaces>true</WrapJsonInNamespaces>
    <EnforceURINamespaces>false</EnforceURINamespaces>
    <MergeJsonSiblings>true</MergeJsonSiblings>
    <UriMappingEnabled>true</UriMappingEnabled>
    <OntologyMappingEnabled>true</OntologyMappingEnabled>
    <RequestFiltersEnabled>true</RequestFiltersEnabled>
    <TempDirectory>C:\Users\const\Documents\Starcounter\Personal\Temp\playground_0\playground_0-20160511T111839102</TempDirectory>
    <ImageDirectory>C:\Users\const\Documents\Starcounter\Personal\Data\playground_0\playground_0-20160511T111839102</ImageDirectory>
    <TransactionLogDirectory>C:\Users\const\Documents\Starcounter\Personal\Data\playground_0\playground_0-20160511T111839102</TransactionLogDirectory>
    <SQLProcessPort>8066</SQLProcessPort>
    <DefaultUserHttpPort>8080</DefaultUserHttpPort>
    <DefaultSessionTimeoutMinutes>20</DefaultSessionTimeoutMinutes>
    <ChunksNumber>65536</ChunksNumber>
    <SchedulerCount xsi:nil="true" />
  </Runtime>
  <Monitoring>
    <MaxRestartNumber xsi:nil="true" />
    <ResetFailureCountPeriod xsi:nil="true" />
    <GracePeriodAfterConnectionLost xsi:nil="true" />
    <StartupType>Manual</StartupType>
    <MonitoringType>Disabled</MonitoringType>
  </Monitoring>
  <TraceSources />
</Database>
```

I am not sure what else I can provide.

**Comment by per-samuelsson** [comment]
Wow, great. That's a much better idea! :+1: 

Let me consider it some and get back on that.

**Comment by per-samuelsson** [comment]
@miyconst 

The underscore in the name is the problem: reported and discussed previously in #2913. Closing this as a dup of that one.
