### ISSUE TITLE
An unhandled exception was detected.

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3604]
My Server crashed again. I have 3 following exceptions in SC Logs (I copied these from SC log file) :

First one is : 
`20160507T001301 Critical sc://owneror-pvpjthq/personal/administrator Starcounter - System.Exception: ScErrUnhandledException (SCERR1069): An unhandled exception was detected.\r\nVersion: 2.2.1834.\r\nHelp page: https://github.com/Starcounter/Starcounter/wiki/SCERR1069.\r\n   at StarcounterInternal.Hosting.Processor.RunTaskNoScheduling(Action userAction, String appName) in C:\\TeamCity\\TeamCity9\\buildAgent\\work\\sc-develop-nightly-283\\Level1\\src\\Hosting\\Starcounter.Hosting\\Processor.cs:line 102\r\n   at Starcounter.DbSession.GetAndExecuteQueuedTasks(Action 2 taskExecutionMethod) in C:\\TeamCity\\TeamCity9\\buildAgent\\work\\sc-develop-nightly-283\\Level1\\src\\Starcounter\\DbSession.cs:line 180\r\n   at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask) in C:\\TeamCity\\TeamCity9\\buildAgent\\work\\sc-develop-nightly-283\\Level1\\src\\Hosting\\Starcounter.Hosting\\Processor.cs:line 149\r\n   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\\TeamCity\\TeamCity9\\buildAgent\\work\\sc-develop-nightly-283\\Level1\\src\\Hosting\\Starcounter.Hosting\\Processor.cs:line 62\r\nHResult=-2146233088\r\nHelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR1069\r\n---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.\r\n   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)\r\n   at System.Collections.Generic.List 1.Enumerator.MoveNextRare()\r\n   at Starcounter.Json.CheckBoundArray(IEnumerable boundValue) in C:\\TeamCity\\TeamCity9\\buildAgent\\work\\sc-develop-nightly-283\\Level1\\src\\Starcounter.XSON\\Class Json\\Json.Object.ChangeLog.cs:line 390\r\n   at Starcounter.Templates.TArray 1.GetValue(Json parent) in C:\\TeamCity\\TeamCity9\\buildAgent\\work\\sc-develop-nightly-283\\Level1\\src\\Starcounter.XSON\\Templates\\TArray.cs:line 127\r\n   at Starcounter.Json.<LogObjectValueChangesWithDatabase>b__123_0(ChangeLog clog, Json json, Boolean css) in C:\\TeamCity\\TeamCity9\\buildAgent\\work\\sc-develop-nightly-283\\Level1\\src\\Starcounter.XSON\\Class Json\\Json.Object.ChangeLog.cs:line 187\r\n   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3](Json json, Action 3 action, T1 arg1, T2 arg2, T3 arg3) in C:\\TeamCity\\TeamCity9\\buildAgent\\work\\sc-develop-nightly-283\\Level1\\src\\Starcounter.XSON\\Class Json\\JsonExtension.cs:line 111\r\n   at Starcounter.Json.LogArrayChangesWithDatabase(ChangeLog changeLog, Boolean callStepSiblings) in C:\\TeamCity\\TeamCity9\\buildAgent\\work\\sc-develop-nightly-283\\Level1\\src\\Starcounter.XSON\\Class Json\\Json.Object.ChangeLog.cs:line 157\r\n   at Starcounter.Json.<LogObjectValueChangesWithDatabase>b__123_0(ChangeLog clog, Json json, Boolean css) in C:\\TeamCity\\TeamCity9\\buildAgent\\work\\sc-develop-nightly-283\\Level1\\src\\Starcounter.XSON\\Class Json\\Json.Object.ChangeLog.cs:line 219\r\n   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3](Json json, Action 3 action, T1 arg1, T2 arg2, T3 arg3) in C:\\TeamCity\\TeamCity9\\buildAgent\\work\\sc-develop-nightly-283\\Level1\\src\\Starcounter.XSON\\Class Json\\JsonExtension.cs:line 111\r\n   at Starcounter.Json.LogArrayChangesWithDatabase(ChangeLog changeLog, Boolean callStepSiblings) in C:\\TeamCity\\TeamCity9\\buildAgent\\work\\sc-develop-nightly-283\\Level1\\src\\Starcounter.XSON\\Class Json\\Json.Object.ChangeLog.cs:line 157\r\n   at Starcounter.Json.<LogObjectValueChangesWithDatabase>b__123_0(ChangeLog clog, Json json, Boolean css) in C:\\TeamCity\\TeamCity9\\buildAgent\\work\\sc-develop-nightly-283\\Level1\\src\\Starcounter.XSON\\Class Json\\Json.Object.ChangeLog.cs:line 219\r\n   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3](Json json, Action 3 action, T1 arg1, T2 arg2, T3 arg3) in C:\\TeamCity\\TeamCity9\\buildAgent\\work\\sc-develop-nightly-283\\Level1\\src\\Starcounter.XSON\\Class Json\\JsonExtension.cs:line 111\r\n   at Starcounter.Json.LogObjectValueChangesWithDatabase(ChangeLog changeLog, Boolean callStepSiblings) in C:\\TeamCity\\TeamCity9\\buildAgent\\work\\sc-develop-nightly-283\\Level1\\src\\Starcounter.XSON\\Class Json\\Json.Object.ChangeLog.cs:line 277\r\n   at Starcounter.XSON.ChangeLog.Generate(Boolean flushLog) in C:\\TeamCity\\TeamCity9\\buildAgent\\work\\sc-develop-nightly-283\\Level1\\src\\Starcounter.XSON\\Sessions\\JSON-Patch\\ChangeLog.cs:line 94\r\n   at Starcounter.XSON.JsonPatch.Generate(ChangeLog changeLog, Boolean includeNamespace, Boolean flushLog, Byte[]& patches) in C:\\TeamCity\\TeamCity9\\buildAgent\\work\\sc-develop-nightly-283\\Level1\\src\\Starcounter.XSON\\Sessions\\JSON-Patch\\JsonPatch.cs:line 112\r\n   at Starcounter.XSON.JsonPatch.Generate(Json json, Boolean flushLog, Boolean includeNamespace, Byte[]& patches) in C:\\TeamCity\\TeamCity9\\buildAgent\\work\\sc-develop-nightly-283\\Level1\\src\\Starcounter.XSON\\Sessions\\JSON-Patch\\JsonPatch.cs:line 90\r\n   at Starcounter.XSON.JsonPatch.Generate(Json json, Boolean flushLog, Boolean includeNamespace) in C:\\TeamCity\\TeamCity9\\buildAgent\\work\\sc-develop-nightly-283\\Level1\\src\\Starcounter.XSON\\Sessions\\JSON-Patch\\JsonPatch.cs:line 68\r\n   at Administrator.Server.Managers.ServerManager.GetModelChanges(Session session) in C:\\TeamCity\\TeamCity9\\buildAgent\\work\\sc-develop-nightly-283\\Level1\\src\\Starcounter.Administrator\\Server\\Managers\\ServerManager.cs:line 357\r\n   at Administrator.Server.Managers.ServerManager.<>c.<ServerModel_Changed>b__10_0(Session session, String sessionId) in C:\\TeamCity\\TeamCity9\\buildAgent\\work\\sc-develop-nightly-283\\Level1\\src\\Starcounter.Administrator\\Server\\Managers\\ServerManager.cs:line 342\r\n   at Starcounter.Session.Use(SessionTask action, String sessionId) in C:\\TeamCity\\TeamCity9\\buildAgent\\work\\sc-develop-nightly-283\\Level1\\src\\Starcounter.XSON\\Sessions\\Session.cs:line 712\r\n   at Starcounter.Task.Run() in C:\\TeamCity\\TeamCity9\\buildAgent\\work\\sc-develop-nightly-283\\Level1\\src\\Starcounter\\DbSession.cs:line 100\r\nHResult=-2146233079\r\n`

Second one is :
`20160507T001301 Error sc://owneror-pvpjthq/personal/service Starcounter - ScErrDatabaseEngineTerminated (SCERR10007): The server detected that the user code host executable (sccode.exe) unexpectedly terminated during a management operation.`

Third one is :
`20160507T001301 Error sc://owneror-pvpjthq/personal/service Starcounter - ScErrUnhandledException (SCERR1069): An unhandled exception was detected.`

**Comment by per-samuelsson** [comment]
@atifwaqar 

Hmm, those logs really don't look pretty. Sorry for that.

It seem to be something related to Typed JSON, even though I'm not sure. I'm basing this on the extracted:

```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.\r\n at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)\r\n at System.Collections.Generic.List 1.Enumerator.MoveNextRare()\r\n at Starcounter.Json.CheckBoundArray(IEnumerable boundValue) in C:\\TeamCity\\TeamCity9\\buildAgent\\work\\sc-develop-nightly-283\\Level1\\src\\Starcounter.XSON\\Class Json\\Json.Object.ChangeLog.cs:line 390
```

It's just a guess, but I'll label it like that now and pinging @chrhol to see if he's seen anything like that before.

**Comment by chrhol** [comment]
No never seen this before. Apparently the bound data is modified while looping through it, and I guess it's not bound to a result from a database query (then this shouldn't happen), but rather some generic list that is modified while the dirtycheck is running.

Do you know of any places in your code where you use data that is not database-data?

**Comment by atifwaqar** [comment]
No we are not using "not database-data", If by "not database-data" you mean the variable that can be declared in DB classes. We don't use those kind of variables at all.

But if that's not what you are referring to, then i'm not sure what is not database-data.

**Comment by chrhol** [comment]
Sorry, I was a bit unclear. What I meant was using an ordinary C# class that is not marked with `[Database]` attribute or inherit some other database class or array, which contains a list and setting that class to the `Data` property on the TypedJson. 

Or maybe a Json-property that is bound to a property in the code-behind that returns an enumerable of some sort.

```csharp
public class MyStateClass { // NOT a database class
    private List<object> list = new List<object>();

    public IEnumable<object> Items {
        get {
             return list;
        }
    }
}
```

**Comment by atifwaqar** [comment]
We have code like following in code-behind : 

```
        public IEnumerable CityList_
        {
            get
            {
                PublicationOwner po = Db.SQL<PublicationOwner>("SELECT po FROM AdFenix.Database.PublicationOwner po WHERE Domain=?", this.Domain).First;
                return Db.SQL<AdFenix.Database.BaseConcepts.City>("SELECT c FROM AdFenix.Database.BaseConcepts.City c WHERE GeneratedViaThisPublicationOwner=? AND GeneratedFromTypeOfListing=? fetch ?", po, "ClassifiedHomeAd", 50);
            }
        }
```

But this sort of code is always populated from Database.

**Comment by chrhol** [comment]
Thanks, yeah this code shouldn't cause any problems. I'm not really sure how to start investigating this, it gets a bit harder when it's not happening all the time. 

Can you provoke this error somehow, or do you have any guess if anything special is happening when this occurs? 

I will add some better errormessage for these cases, just to get somewhere to start looking.

**Comment by atifwaqar** [comment]
Honestly I have no idea how to reproduce this crash, it just happens. 
I tried to investigate the crash, but strange thing is when I'm monitor the servers, they dont crash, as soon as I leave the office, they start crashing :P

**Comment by chrhol** [comment]
> Honestly I have no idea how to reproduce this crash, it just happens. 
I tried to investigate the crash, but strange thing is when I'm monitor the servers, they dont crash, as soon as I leave the office, they start crashing :P

I was afraid of that :smile:

**Comment by chrhol** [comment]
Wait a minute here. Just noticed that in the beginning of the stacktrace it actually points to the administrator, totally missed that before. It makes more sense now. This problem does not come from anywhere in your code @atifwaqar.

```
at Administrator.Server.Managers.ServerManager.GetModelChanges(Session session) in C:\\TeamCity\\TeamCity9\\buildAgent\\work\\sc-develop-nightly-283\\Level1\\src\\Starcounter.Administrator\\Server\\Managers\\ServerManager.cs:line 357
 at Administrator.Server.Managers.ServerManager.<>c.<ServerModel_Changed>b__10_0(Session session, String sessionId) in C:\\TeamCity\\TeamCity9\\buildAgent\\work\\sc-develop-nightly-283\\Level1\\src\\Starcounter.Administrator\\Server\\Managers\\ServerManager.cs:line 342
```

So somewhere in the `ServerManager` there is some state that is not properly secured for access from multiple threads. @andwah, maybe we can take some time tomorrow and try to figure this one out.

**Comment by dan31** [comment]
@chrhol @andwah cc @alemoi as I recall, it's been a long-term story with Administrator doing some non-thread safe pattern for some reason. Probably after fixing the task queuing the problems resting under the carpet were made somewhat more surfaced. Maybe it is good time to review the code and identify what pattern is there to fix. This isn't only applicable to administrator, but to any other app using Starcounter and directly working with threads for some reason.

**Comment by per-samuelsson** [comment]
> @chrhol @andwah cc @alemoi as I recall, it's been a long-term story with Administrator doing some non-thread safe pattern for some reason.

I've noticed similar things, as hinted [here](https://github.com/Starcounter/Starcounter/issues/3566#issuecomment-218960279).

**Comment by andwah** [comment]
> @chrhol : maybe we can take some time tomorrow and try to figure this one out.

Sure. anytime.

**Comment by linkdata** [comment]
I also get this error occasionally. Attaching call stack for `Starcounter-PnextDailyBuilds-2.3.1464 (13 maj 2016 14:25:43`.

```
System.Exception: ScErrUnhandledException (SCERR1069): An unhandled exception was detected.
Version: 2.3.1464.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR1069.
   at StarcounterInternal.Hosting.Processor.RunTaskNoScheduling(Action userAction, String appName) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-daily-windows-334\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 121
   at Starcounter.DbSession.GetAndExecuteQueuedTasks(Action`2 taskExecutionMethod) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-daily-windows-334\Level1\src\Starcounter\DbSession.cs:line 180
   at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-daily-windows-334\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 168
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-daily-windows-334\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 81
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR1069
---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Starcounter.Json.CheckBoundArray(IEnumerable boundValue) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-daily-windows-334\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 403
   at Starcounter.Templates.TArray`1.GetValue(Json parent) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-daily-windows-334\Level1\src\Starcounter.XSON\Templates\TArray.cs:line 127
   at Starcounter.Json.<LogObjectValueChangesWithDatabase>b__125_0(ChangeLog clog, Json json, Boolean css) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-daily-windows-334\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 192
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3](Json json, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-daily-windows-334\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 111
   at Starcounter.Json.LogArrayChangesWithDatabase(ChangeLog changeLog, Boolean callStepSiblings) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-daily-windows-334\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 162
   at Starcounter.Json.<LogObjectValueChangesWithDatabase>b__125_0(ChangeLog clog, Json json, Boolean css) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-daily-windows-334\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 242
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3](Json json, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-daily-windows-334\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 111
   at Starcounter.Json.LogArrayChangesWithDatabase(ChangeLog changeLog, Boolean callStepSiblings) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-daily-windows-334\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 162
   at Starcounter.Json.<LogObjectValueChangesWithDatabase>b__125_0(ChangeLog clog, Json json, Boolean css) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-daily-windows-334\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 242
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3](Json json, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-daily-windows-334\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 111
   at Starcounter.Json.LogObjectValueChangesWithDatabase(ChangeLog changeLog, Boolean callStepSiblings) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-daily-windows-334\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 290
   at Starcounter.XSON.ChangeLog.Generate(Boolean flushLog) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-daily-windows-334\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\ChangeLog.cs:line 105
   at Starcounter.XSON.JsonPatch.Generate(ChangeLog changeLog, Boolean includeNamespace, Boolean flushLog, Byte[]& patches) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-daily-windows-334\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 110
   at Starcounter.XSON.JsonPatch.Generate(Json json, Boolean flushLog, Boolean includeNamespace, Byte[]& patches) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-daily-windows-334\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 88
   at Starcounter.XSON.JsonPatch.Generate(Json json, Boolean flushLog, Boolean includeNamespace) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-daily-windows-334\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 66
   at Administrator.Server.Managers.ServerManager.GetModelChanges(Session session) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-daily-windows-334\Level1\src\Starcounter.Administrator\Server\Managers\ServerManager.cs:line 357
   at Administrator.Server.Managers.ServerManager.<>c.<ServerModel_Changed>b__10_0(Session session, String sessionId) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-daily-windows-334\Level1\src\Starcounter.Administrator\Server\Managers\ServerManager.cs:line 342
   at Starcounter.Session.Use(SessionTask action, String sessionId) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-daily-windows-334\Level1\src\Starcounter.XSON\Sessions\Session.cs:line 689
   at Starcounter.Task.Run() in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-daily-windows-334\Level1\src\Starcounter\DbSession.cs:line 100
HResult=-2146233079
```

**Comment by atifwaqar** [comment]
Ok one reason of this `An unhandled exception was detected` crash is when the code have an exception and there is no try-catch body in a handler or in a `DbSession dbSession = new DbSession();`

**Comment by chrhol** [comment]
> Ok one reason of this An unhandled exception was detected crash is when the code have an exception and there is no try-catch body in a handler or in a DbSession dbSession = new DbSession();

These both stacktraces points to the administrator, where an managed array is read by TypedJson (through databinding) while some other thread updates it. Me and @andwah will sit down tomorrow and go through the code. 

The unhandled exception you point to is unrelated to these ones, and as you say comes from not catching exception from a scheduled task.

**Comment by atifwaqar** [comment]
SC Version: 2.2.1.2237
I got the exception again and the apps/DB crashed, but good thing is that now the error message have some more details.

```
System.Exception: ScErrUnhandledException (SCERR1069): An unhandled exception was detected.
Version: 2.2.1.2237.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR1069.
   at StarcounterInternal.Hosting.Processor.RunTaskNoScheduling(Action userAction, String appName) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-325\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 102
   at Starcounter.DbSession.GetAndExecuteQueuedTasks(Action`2 taskExecutionMethod) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-325\Level1\src\Starcounter\DbSession.cs:line 194
   at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-325\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 149
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-325\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 62
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR1069
---> System.Exception: ScErrUnspecified (SCERR999): An unspecified error caused the operation to fail. System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at Starcounter.NodeTask.PerformSyncRequest() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-325\Level1\src\Starcounter.Internal\Rest\NodeTask.cs:line 514
Version: 2.2.1.2237.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR999.
   at Starcounter.GatewayHandlers.RegisterHttpHandlerInGateway(UInt16 port, String appName, String methodSpaceUri, Byte[] nativeParamTypes, UInt16 managedHandlerIndex, UInt64& handlerInfo) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-325\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 617
   at Starcounter.Rest.UriHandlersManager.RegisterUriHandler(UInt16 port, String methodSpaceUri, Byte[] nativeParamTypes, Type messageType, Func`4 wrappedDelegate, NetworkProtocolType protoType, HandlerOptions ho) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-325\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 617
   at Starcounter.Rest.UriManagedHandlersCodegen.RegisterDelegate(UInt16 port, String methodSpaceUri, MethodInfo userDelegateInfo, Expression delegExpr, NetworkProtocolType protoType, HandlerOptions ho) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-325\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 615
   at Starcounter.Rest.RestRegistrationProxy.RegisterHandler[T1,T2,T3](UInt16 port, String methodSpaceUri, Func`4 handler, HandlerOptions ho) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-325\Level1\src\Starcounter.Rest\RestInitialization.cs:line 87
   at Starcounter.Handle.GET[T1,T2,T3](String uriTemplate, Func`4 code, HandlerOptions ho) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-325\Level1\src\Starcounter.Internal\Handle.GET.cs:line 229
   at AdFenix.Server.Handlers.CustomizedInterfaces.GeneralAPI.GeneralAPI.Register() in c:\adfenix-backend\src\Server\Handlers\CustomizedInterfaces\GeneralAPI\GeneralAPI.cs:line 752
   at AdFenix.Program.<>c__DisplayClassa.<Main>b__4() in c:\adfenix-backend\src\Program.cs:line 74
   at Starcounter.Task.Run() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-325\Level1\src\Starcounter\DbSession.cs:line 100
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR999
```

I can see my code reference in this exception, and when I go to my code (GeneralAPI.cs:line 752), I have a handler declaration : 

```
Handle.GET("/adfenix/config/orderdashboard?uniqueidentifier={?}&token={?}&domain={?}", (string uniqueIdentifier, string token, string domain) => 
```

**Comment by per-samuelsson** [comment]
@alemoi, anything you recognize?

**Comment by alemoi** [comment]
Hmm, yes stack trace says the connection was closed by gateway. @atifwaqar can this be constantly reproduced? Or just an occasion?

**Comment by alemoi** [comment]
The version seems also a bit old. Is it possible for you to install the latest nightly @atifwaqar?

**Comment by atifwaqar** [comment]
@alemoi this can not be constantly reproduced. I got this exception twice in entire week. and the occurrence is random.
Also, this is my live server, so i can not update my SC to latest right now. I will do that tonight.

**Comment by chrhol** [comment]
@atifwaqar: Do you still get these exceptions or have they been resolved now?

**Comment by atifwaqar** [comment]
I checked all of my logs, and it looks like we dont get this error anymore. So feel free to close this ticket, if I see the exception again, i will reopen this card. 
Thanks for follow up :)

**Comment by chrhol** [comment]
Awesome 😁 thanks for the feedback @atifwaqar!
