### ISSUE TITLE
System.OutOfMemoryException retrieving a short string from the database

### ISSUE THREAD

**Issue by linkdata** [Starcounter/Starcounter#3615]
This is a placeholder issue until I can reproduce this problem. Assuming it's reproducible. All of the strings in the table in question are less than 348 characters long and consists of characters randomly selected from this small set:
```
" \r\n\t\\!\"'#%&/()=?´`^@$<>|-_.:,;*~+{}[]ABCDEFGHIJKLMNOPQRSTUVWXYZÅÄÖabcdefghijklmnopqrstuvwxyzåäö0123456789"
```

```
System.Exception: ScErrUnhandledException (SCERR1069): An unhandled exception was detected.
Version: 2.3.1129.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR1069.
   at StarcounterInternal.Hosting.Processor.RunTaskNoScheduling(Action userAction, String appName) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 121
   at Starcounter.DbSession.GetAndExecuteQueuedTasks(Action`2 taskExecutionMethod) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter\DbSession.cs:line 194
   at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 168
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 81
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR1069
---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.String.CtorCharPtrStartLength(Char* ptr, Int32 startIndex, Int32 length)
   at Starcounter.Internal.DbState.ReadString(UInt64 oid, UInt64 address, Int32 index) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter\Internal\DbState.cs:line 684
   at LogStreamerBulker.Program.GetMD5(Record r) in C:\Proj\LogStreamerBulker\LogStreamerBulker.cs:line 258
   at LogStreamerBulker.Program.MutateRecord(Record r) in C:\Proj\LogStreamerBulker\LogStreamerBulker.cs:line 281
   at LogStreamerBulker.Program.<>c__DisplayClass33_0.<MutateRecord>b__0() in C:\Proj\LogStreamerBulker\LogStreamerBulker.cs:line 286
   at Starcounter.Db.Transact(Action action, UInt32 flags, TransactOptions opts) in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter\Db.cs:line 310
   at LogStreamerBulker.Program.MutateRecord(UInt64 oid) in C:\Proj\LogStreamerBulker\LogStreamerBulker.cs:line 285
   at LogStreamerBulker.Program.InsertRecords() in C:\Proj\LogStreamerBulker\LogStreamerBulker.cs:line 295
   at Starcounter.Task.Run() in C:\TeamCity\TeamCity9\buildAgent\work\sc-106\Level1\src\Starcounter\DbSession.cs:line 100
HResult=-2147024882
```

**Comment by linkdata** [comment]
Fixed by https://github.com/Starcounter/Starcounter/issues/3617
