### ISSUE TITLE
Unhandled exceptions are swallowed

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Starcounter#3629]
1. Add a handler in your code that throws NPE: `public void Handle(Input.Description action) { throw new NullReferenceException(); }`
1. Trigger it
1. The webpage shows disconnection dialog - it should show "internal error" dialog
1. There's nothing in log console in admin - there should be
1. Even on when debugging, the exception is not handled by IDE, it behaves as it nothing happened. - it should detect it and break execution (it may be that I have a misconfigured VS, but even so previous points stand)

**Comment by per-samuelsson** [comment]
> Even on when debugging, the exception is not handled by IDE, it behaves as it nothing happened. - it should detect it and break execution [...]

I think this is because it's not *unhandled* - the code host / "AppsRestServer" actually catch that exception, and return an error to the client. In terms of how the IDE behave, I think it's the correct and expected behavior, given that the exception is handled.

I tried using this

```cs
using System;
using Starcounter;

namespace Issue3629
{
    class Program
    {
        static void Main()
        {
            Handle.GET("/foo", () =>
            {
                throw new NullReferenceException();
            });
        }
    }
}
```

Invoked it, and see this in the browser:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Issue3629.Program.<>c.<Main>b__0_0() in c:\users\per\proj\Issue3629\Issue3629\Program.cs:line 12
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\Users\Per\Git\Starcounter\Develop\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\Users\Per\Git\Starcounter\Develop\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\Users\Per\Git\Starcounter\Develop\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 598
HResult=-2147467261

More information about this error may be available in the server error log.
```

**Comment by mtornwall** [comment]
> Even on when debugging, the exception is not handled by IDE, it behaves as it nothing happened.

The debugger has two modes for trapping exceptions: "Thrown" and "User-unhandled". In this case the exception is handled, so you'll have to set it to "Thrown" mode in order to intercept it while debugging.

To do so, go to the `Debug -> Exceptions ...` menu and check the `Thrown` checkbox for `Common Language Runtime Exceptions`. By expanding that category you can also mark specific exception types that you are interested in.

If the exception is occurring within Starcounter's own managed code, you may need to turn off `Just My Code` in the `Debugging` tab of the `Tools -> Options` dialog.

**Comment by joozek78** [comment]
@per-samuelsson try throwing inside Input handler

**Comment by per-samuelsson** [comment]
> @per-samuelsson try throwing inside Input handler

Now I did, and I still think the experience in the IDE is the one expected, and that's what I elaborated on above, and @mtornwall added to.

When I raise an exception in an input handler, this code in `AppsBootstrapper` is triggered:

```cs
catch (Exception exc) {
                // Logging the exception to server log.
                LogSources.Hosting.LogException(exc);
                resp = Response.FromStatusCode(500);
                resp.Body = AppRestServer.GetExceptionString(exc);
                resp.ContentType = "text/plain;charset=utf-8";
            }
```

**Comment by joozek78** [comment]
Okay, but there is still the issue of incorrect user communication - there's "disconnection" dialog, where "internal error" should be
