### ISSUE TITLE
What does ScErrCantCreateDbMemoryFile when starting database mean?

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3630]
As part of #3494, I've setup a rather large database (data directory 37GB) and when I try to start the database, I get this error:

```
Starcounter.DbException: ScErrCantCreateDbMemoryFile (SCERR4186): The memory manager was unable to create a memory file to store database memory.
Version: 2.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4186.
   at StarcounterInternal.Bootstrap.Control.ConnectDatabase(UInt32 schedulerCount, UInt64 hmenv, UInt64 hlogs) in C:\Users\Per\Git\Starcounter\Develop\Level1\src\Starcounter.Bootstrap\Control.cs:line 582
   at StarcounterInternal.Bootstrap.Control.Setup(String[] args) in C:\Users\Per\Git\Starcounter\Develop\Level1\src\Starcounter.Bootstrap\Control.cs:line 230
   at StarcounterInternal.Bootstrap.Control.Main(String[] args) in C:\Users\Per\Git\Starcounter\Develop\Level1\src\Starcounter.Bootstrap\Control.cs:line 55
ErrorCode=4186
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4186
```

Nothing else in the logs, and no further info provided.

I'm guessing it's because I don't have enough RAM installed?

**Comment by per-samuelsson** [comment]
Ah, I checked the help link, and there were actually some content there:

> This error occurs when the memory manager was unable to create a memory file for storing database data either when loading image or expanding database memory. If the failure is caused by an OS error code is logged seperatly. The error could also occur because the maximum number of memory files kept by the memory manager has been reached.

> If the memory manager fails to create a memory file because it was unable to allocate sufficient memory from the OS then a ScErrOUT_OF_MEMORY will be raised.

Guess that's enough.
