### ISSUE TITLE
Error : system.data.dll could not be found 

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3653]
SC version 2.2.1834

```
"ScErrWeavingError (SCERR2030): At least one error has been detected during weaving of the application code. Process exit code: 2147.
Arguments=--maxerrors=1 --ErrorParcelId=A4A7D6FA-EB34-442A-B579-DBB1DBB859E3 Weave ""C:\adfenix-backend\src\bin\Debug\AdFenix.exe"" --outdir=""C:\Users\Administrator\Documents\Starcounter\Personal\Temp\Default\Default-20160525T133727566\weaver\99BE94CF86C81F90C23A1841759E0BDE2AE039DB""
Output:
A4A7D6FA-EB34-442A-B579-DBB1DBB859E3ScErrWeaverFailedResolveReference (SCERR2147): The weaver failed to resolve a reference to an assembly. Referenced assembly: System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089. Probable referrer: Simplified.Data.Model.dll (in C:\Program Files\Starcounter\EditionLibraries). PostSharp.Sdk.CodeModel.AssemblyLoadException: Cannot load assembly System.Data_26.
============ PostSharp Assembly Loading Log ===================
LOG: Finding the assembly with binding identity 'system.data, version=2.0.0.0, culture=neutral, publickeytoken=b77a5c561934e089'.
LOG: Looking in GAC for System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=amd64.
LOG: Looking in GAC for System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=msil.
LOG: Looking in GAC for System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
LOG: Probing location 'C:\Program Files\Starcounter\System.Data.exe' because this directory contains an assembly that has already been loaded.
LOG: The file 'C:\Program Files\Starcounter\System.Data.exe' could not be found.
LOG: Probing location 'C:\Program Files\Starcounter\System.Data.dll' because this directory contains an assembly that has already been loaded.
LOG: The file 'C:\Program Files\Starcounter\System.Data.dll' could not be found.
LOG: Probing location 'C:\adfenix-backend\src\bin\Debug\System.Data.exe' because this directory is in the search path.
LOG: The file 'C:\adfenix-backend\src\bin\Debug\System.Data.exe' could not be found.
LOG: Probing location 'C:\adfenix-backend\src\bin\Debug\System.Data.dll' because this directory is in the search path.
LOG: The file 'C:\adfenix-backend\src\bin\Debug\System.Data.dll' could not be found.
LOG: Probing location 'C:\Program Files\Starcounter\EditionLibraries\System.Data.exe' because this directory is in the search path.
LOG: The file 'C:\Program Files\Starcounter\EditionLibraries\System.Data.exe' could not be found.
LOG: Probing location 'C:\Program Files\Starcounter\EditionLibraries\System.Data.dll' because this directory is in the search path.
LOG: The file 'C:\Program Files\Starcounter\EditionLibraries\System.Data.dll' could not be found.
LOG: Probing location 'C:\Program Files\Starcounter\LibrariesWithDatabaseClasses\System.Data.exe' because this directory is in the search path.
LOG: The file 'C:\Program Files\Starcounter\LibrariesWithDatabaseClasses\System.Data.exe' could not be found.
LOG: Probing location 'C:\Program Files\Starcounter\LibrariesWithDatabaseClasses\System.Data.dll' because this directory is in the search path.
LOG: The file 'C:\Program Files\Starcounter\LibrariesWithDatabaseClasses\System.Data.dll' could not be found.
LOG: Probing location 'C:\Program Files\Starcounter\System.Data.exe' because this directory is in the search path.
LOG: The file 'C:\Program Files\Starcounter\System.Data.exe' could not be found.
LOG: Probing location 'C:\Program Files\Starcounter\System.Data.dll' because this directory is in the search path.
LOG: The file 'C:\Program Files\Starcounter\System.Data.dll' could not be found.
LOG: The assembly 'System.Data_26' was not found.
===============================================================
   at PostSharp.Sdk.CodeModel.Domain.GetAssembly(IAssemblyName assemblyName, BindingOptions bindingOptions)
   at PostSharp.Hosting.PostSharpObject.LoadModuleRecursive(ModuleDeclaration module)
   at PostSharp.Hosting.PostSharpObject.ProcessAssemblies(ModuleLoadStrategy[] modules)
   at Starcounter.Weaver.CodeWeaver.Execute() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-283\Level1\src\scweaver\CodeWeaver.cs:line 364
Version: 2.2.1834.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR2147.A4A7D6FA-EB34-442A-B579-DBB1DBB859E3
ScErrWeaverFailedResolveReference (SCERR2147): The weaver failed to resolve a reference to an assembly. Referenced assembly: System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089. Probable referrer: Simplified.Data.Model.dll (in C:\Program Files\Starcounter\EditionLibraries). PostSharp.Sdk.CodeModel.AssemblyLoadException: Cannot load assembly System.Data_26.
============ PostSharp Assembly Loading Log ===================
LOG: Finding the assembly with binding identity 'system.data, version=2.0.0.0, culture=neutral, publickeytoken=b77a5c561934e089'.
LOG: Looking in GAC for System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=amd64.
LOG: Looking in GAC for System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=msil.
LOG: Looking in GAC for System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
LOG: Probing location 'C:\Program Files\Starcounter\System.Data.exe' because this directory contains an assembly that has already been loaded.
LOG: The file 'C:\Program Files\Starcounter\System.Data.exe' could not be found.
LOG: Probing location 'C:\Program Files\Starcounter\System.Data.dll' because this directory contains an assembly that has already been loaded.
LOG: The file 'C:\Program Files\Starcounter\System.Data.dll' could not be found.
LOG: Probing location 'C:\adfenix-backend\src\bin\Debug\System.Data.exe' because this directory is in the search path.
LOG: The file 'C:\adfenix-backend\src\bin\Debug\System.Data.exe' could not be found.
LOG: Probing location 'C:\adfenix-backend\src\bin\Debug\System.Data.dll' because this directory is in the search path.
LOG: The file 'C:\adfenix-backend\src\bin\Debug\System.Data.dll' could not be found.
LOG: Probing location 'C:\Program Files\Starcounter\EditionLibraries\System.Data.exe' because this directory is in the search path.
LOG: The file 'C:\Program Files\Starcounter\EditionLibraries\System.Data.exe' could not be found.
LOG: Probing location 'C:\Program Files\Starcounter\EditionLibraries\System.Data.dll' because this directory is in the search path.
LOG: The file 'C:\Program Files\Starcounter\EditionLibraries\System.Data.dll' could not be found.
LOG: Probing location 'C:\Program Files\Starcounter\LibrariesWithDatabaseClasses\System.Data.exe' because this directory is in the search path.
LOG: The file 'C:\Program Files\Starcounter\LibrariesWithDatabaseClasses\System.Data.exe' could not be found.
LOG: Probing location 'C:\Program Files\Starcounter\LibrariesWithDatabaseClasses\System.Data.dll' because this directory is in the search path.
LOG: The file 'C:\Program Files\Starcounter\LibrariesWithDatabaseClasses\System.Data.dll' could not be found.
LOG: Probing location 'C:\Program Files\Starcounter\System.Data.exe' because this directory is in the search path.
LOG: The file 'C:\Program Files\Starcounter\System.Data.exe' could not be found.
LOG: Probing location 'C:\Program Files\Starcounter\System.Data.dll' because this directory is in the search path.
LOG: The file 'C:\Program Files\Starcounter\System.Data.dll' could not be found.
LOG: The assembly 'System.Data_26' was not found.
===============================================================
   at PostSharp.Sdk.CodeModel.Domain.GetAssembly(IAssemblyName assemblyName, BindingOptions bindingOptions)
   at PostSharp.Hosting.PostSharpObject.LoadModuleRecursive(ModuleDeclaration module)
   at PostSharp.Hosting.PostSharpObject.ProcessAssemblies(ModuleLoadStrategy[] modules)
   at Starcounter.Weaver.CodeWeaver.Execute() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-283\Level1\src\scweaver\CodeWeaver.cs:line 364
Version: 2.2.1834.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR2147.
A4A7D6FA-EB34-442A-B579-DBB1DBB859E3ScErrWeaverFailedResolveReference (SCERR2147): The weaver failed to resolve a reference to an assembly. Referenced assembly: System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089. Probable referrer: Simplified.Data.Model.dll (in C:\Program Files\Starcounter\EditionLibraries).
Version: 2.2.1834.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR2147.A4A7D6FA-EB34-442A-B579-DBB1DBB859E3
ScErrWeaverFailedResolveReference (SCERR2147): The weaver failed to resolve a reference to an assembly. Referenced assembly: System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089. Probable referrer: Simplified.Data.Model.dll (in C:\Program Files\Starcounter\EditionLibraries).
Version: 2.2.1834.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR2147.

Version: 2.2.1834.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR2030."

```

**Comment by atifwaqar** [comment]
The same setup work perfectly fine on all of my server, But today I got a new server, I replicated the same setup on the new server but i am getting the above error.

**Comment by miyconst** [comment]
@atifwaqar please make sure that `System.Data.dll` is included into `weaver.ignore` file and ignored by Starcounter. Read more here: http://starcounter.io/guides/tools/weaver/.

**Comment by per-samuelsson** [comment]
@atifwaqar 

It's somewhat related to #3413, and after that, we made an initiative to help users help themselves a little better, described and implemented in #3420. 

Could you take a look there and see if it's possible for you to figure out some ways to try, before I help you with it? Would be good to test-case that stuff on someone that comes in with a fresh pair of eyes (you).

If you either don't have time, or think it's unrelated, let me know and I'll try to help hands on.

**Comment by atifwaqar** [comment]
I tried that aswell, But still the same.
According to my knowledge, I should include the dll in `weaver.ignore` if I can see it in `build` or `debug`. 
In other words if the dll is set to `Copy Local = true` in VS. On building the project, it will appear in my `debug` folder. And in this sort of case i have to include the dll name in `weaver.ignore`

**Comment by per-samuelsson** [comment]
> According to my knowledge, I should include the dll in weaver.ignore if I can see it in build or debug.

Not necessarily, no. Because not only **first-level** references are considered, but **references of references** recursively, and such references can be in the GAC for example. 

> @miyconst I tried that aswell, But still the same.

Could you try out diagnosing the way I instructed? Basically, you'll end up at [Troubleshooting weaver failures](http://starcounter.io/guides/tools/weaver/#troubleshooting-weaver-failures) and a hint here is that it's likely some assembly you reference, that in turn reference `System.Data` (just a qualified guess though).

**Comment by atifwaqar** [comment]
Ah, finally fixed it. The solution is as following : 
`Make sure that all the features under IIS are selected except CGI (in Add Program and Features)`
