### ISSUE TITLE
ScErrUnexpectedCommandException restarting application

### ISSUE THREAD

**Issue by linkdata** [Starcounter/Starcounter#3658]
```
ScErrUnexpectedCommandException (SCERR10016): Attempting to restart code host for repl1 failed due to an unexpected problem.
Version: 2.3.1561.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10016.
 System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Starcounter.Internal.ParcelledError.ExtractParcelledErrors(String[] content, String parcelID, List`1 errors, Int32 maxCount) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-162\Level1\src\Starcounter.Internal\ErrorHandling\ParcelledError.cs:line 70
   at Starcounter.Server.DatabaseEngine.CreateCodeHostTerminated(Process codeHostProcess, Database database, Exception serverException) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-162\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseEngine.cs:line 697
   at Starcounter.Server.DatabaseEngine.WaitUntilCodeHostOnline(Process codeHostProcess, Database database) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-162\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseEngine.cs:line 332
   at Starcounter.Server.DatabaseEngine.RestartCodeHost(ICommandProcessor processor, Int32 terminatingCodeHostProcessId, DatabaseInfo databaseInfo) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-162\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseEngine.cs:line 461
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-162\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
ParamName=length
HResult=-2146233086
```

**Comment by per-samuelsson** [comment]
:cry: 

Any other errors in the log? This error indicates a problem formatting an underlying error, which is kind of bad, because it hides the "real" error.

We need to fix both obv.

**Comment by linkdata** [comment]
Right. Sorry. Yeah, I got a few within a second or so. These are in reverse chronological order, so they occured prior that exception in the log, with the most recent listed first.

```
ScErrUnexpectedCommandException (SCERR10016): Attempting to restart code host for repl1 failed due to an unexpected problem.
Version: 2.3.1561.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10016.
 System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Starcounter.Internal.ParcelledError.ExtractParcelledErrors(String[] content, String parcelID, List`1 errors, Int32 maxCount) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-162\Level1\src\Starcounter.Internal\ErrorHandling\ParcelledError.cs:line 70
   at Starcounter.Server.DatabaseEngine.CreateCodeHostTerminated(Process codeHostProcess, Database database, Exception serverException) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-162\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseEngine.cs:line 697
   at Starcounter.Server.DatabaseEngine.WaitUntilCodeHostOnline(Process codeHostProcess, Database database) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-162\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseEngine.cs:line 332
   at Starcounter.Server.DatabaseEngine.RestartCodeHost(ICommandProcessor processor, Int32 terminatingCodeHostProcessId, DatabaseInfo databaseInfo) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-162\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseEngine.cs:line 461
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-162\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
ParamName=length
HResult=-2146233086
```

```
ScErrServerCommandFailed (SCERR10011): The operation "Starting LogStreamerBulker in repl1" failed.
Version: 2.3.1561.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10011.
```

```
Starcounter.DbException: ScErrDatabaseEngineTerminated (SCERR10007): The server detected that the user code host executable (sccode.exe) unexpectedly terminated during a management operation. , PID=26212, Database=repl1
Version: 2.3.1561.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10007.
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.<>c__DisplayClass4_0.<Execute>b__3(CommandTask task) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-162\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 180
   at Starcounter.Server.Commands.CommandProcessor.<>c__DisplayClass68_0.<WithinTask>b__0(CommandTask t) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-162\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 484
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-162\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 510
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.Execute() in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-162\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 194
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-162\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
ErrorCode=10007
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR10007
---> Starcounter.DbException: ScErrProcessExitCodeNotAvailable (SCERR10040): The exit code of the terminating process was not available.
Version: 2.3.1561.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10040.
ErrorCode=10040
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR10040
```

```
Starcounter.ConstraintViolationException: ScErrConstraintViolationAbort (SCERR8001): A transaction was aborted because a constraint was violated.
Version: 2.3.1561.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR8001.
   at Starcounter.Internal.TransactionManager.Commit(Int32 free) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-162\Level1\src\Starcounter\TransactionManager.cs:line 649
   at Starcounter.Db.Transact(Action action, UInt32 flags, TransactOptions opts) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-162\Level1\src\Starcounter\Db.cs:line 310
   at Starcounter.Hosting.Package.UpdateDatabaseSchemaAndRegisterTypes(String fullAppId, TypeDef[] unregisteredTypeDefs, TypeDef[] allTypeDefs) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-162\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 415
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application, ApplicationDirectory applicationDir) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-162\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 265
   at Starcounter.Hosting.Package.Process() in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-162\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 138
   at Starcounter.Hosting.Package.Process(IntPtr hPackage) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-162\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 55
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-162\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 85
ErrorCode=8001
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR8001
```

**Comment by per-samuelsson** [comment]
> Yeah, I got a few within a second or so.

Thanks! That should be enough for me to be able to setup an environment where I can test why the server-side error parcel parser fail and fix it.

If the originating `ConstraintViolationException` is unexpected at this point, and should be considered a bug, we need to open a separate issue for that.

**Comment by linkdata** [comment]
> If the originating ConstraintViolationException is unexpected at this point, and should be considered a bug, we need to open a separate issue for that.

Sure, I get those all the time when restarting applications. Just did a search, but I can't find an issue for them so I'll make one.
