### ISSUE TITLE
ScErrConstraintViolationAbort restarting applications

### ISSUE THREAD

**Issue by linkdata** [Starcounter/Starcounter#3660]
Lately I've been getting a lot of these. Usually just trying to start the app again will work.

```
Starcounter.ConstraintViolationException: ScErrConstraintViolationAbort (SCERR8001): A transaction was aborted because a constraint was violated.
Version: 2.3.1561.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR8001.
   at Starcounter.Internal.TransactionManager.Commit(Int32 free) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-162\Level1\src\Starcounter\TransactionManager.cs:line 649
   at Starcounter.Db.Transact(Action action, UInt32 flags, TransactOptions opts) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-162\Level1\src\Starcounter\Db.cs:line 310
   at Starcounter.Hosting.Package.UpdateDatabaseSchemaAndRegisterTypes(String fullAppId, TypeDef[] unregisteredTypeDefs, TypeDef[] allTypeDefs) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-162\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 415
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application, ApplicationDirectory applicationDir) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-162\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 265
   at Starcounter.Hosting.Package.Process() in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-162\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 138
   at Starcounter.Hosting.Package.Process(IntPtr hPackage) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-162\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 55
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-162\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 85
ErrorCode=8001
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR8001
```

**Comment by per-samuelsson** [comment]
Is this **pnext**? It looks to be internal transactions, done as part of bootstrapping apps, and that has changed a lot between versions; that's why I'm asking.

**Comment by linkdata** [comment]
Yep. `Starcounter-PnextNightlyBuilds-2.3.1561 (24 maj 2016 02:00:43)`

**Comment by per-samuelsson** [comment]
OK. Changing title accordingly. 

My initial guess is it concern some kind of refactoring, but hard to say for sure. Let's see who picks it up.
