### ISSUE TITLE
Unable to use Dictionary<string, object> as a JSON data source

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3686]
I am trying to bind my JSON view-model to a dictionary with data, but it throws an exception.

```json
{
    "Html": "/DictionaryPage.html",
    "Item": { }
}
```

```cs
Dictionary<string, object> data = new Dictionary<string, object>();
DictionaryPage page = new DictionaryPage();

data.Add("Name", "An item");
data.Add("Value", "A value");

page.Item.Data = data; // This line throws the exception.
```

```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Starcounter.Json.MarkAsDirty(Int32 templateIndex) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-351\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 102
   at Starcounter.Json.System.Collections.IList.Clear() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-351\Level1\src\Starcounter.XSON\Class Json\Json.IList.cs:line 352
   at Starcounter.Json.<set_Data>b__221_0(Json j, Object v) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-351\Level1\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 41
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2](Json json, Action`2 action, T1 arg1, T2 arg2) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-351\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 86
   at Starcounter.Json.set_Data(Object value) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-351\Level1\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 52
   at Starcounter.Json.Array_InitializeAfterImplicitConversion(Json parent, TObjArr template) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-351\Level1\src\Starcounter.XSON\Class Json\Json.Array.cs:line 84
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2](Json json, Action`2 action, T1 arg1, T2 arg2) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-351\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 86
   at Starcounter.Json.set_Data(Object value) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-351\Level1\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 52
   at Playground.DynItemsPage.OnData() in D:\GitHub\Miyconst\Playground\Playground\DynItemsPage.json.cs:line 12
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2](Json json, Action`2 action, T1 arg1, T2 arg2) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-351\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 86
   at Starcounter.Json.set_Data(Object value) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-351\Level1\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 52
   at Playground.Program.<>c.<Main>b__0_24() in D:\GitHub\Miyconst\Playground\Playground\Program.cs:line 223
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-351\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-351\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-351\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 765
ParamName=index
HResult=-2146233086

More information about this error may be available in the server error log.
```

cc @chrhol

**Comment by miyconst** [comment]
The full example is available in my [Playground](https://github.com/miyconst/Playground/) solution. See the commit referenced to this issue.

**Comment by chrhol** [comment]
Getting this kind of exception is of course incorrect and should be fixed. I think the proper behaviour in this case is to get a starcounter-exception that points to the fact that a dataobject is set on an untyped jsonobect (i.e. not possible to create any databindings).

What is this sample for? Just playing around, or is it something you are trying to solve?

**Comment by miyconst** [comment]
@chrhol this is not the case.

I can do exactly the same bindings to an anonymous type:

```cs
page.Item.Data = new { Name = "An item", Value: "A value" };
```

Moreover if I have:

```json
{
    "Items": [ { } ]
}
```

I can bind `Items` array with array of objects with different types. See the [example in here](https://github.com/miyconst/Playground/blob/master/Playground/DynItemsPage.json.cs#L13).

**Comment by chrhol** [comment]
This is functionality that is not added by me, and I don't really know why it was added from the beginning, since no time was spent on actually make it work. 

Anyways, if the json is an object, it will take **all** public properties on the dataobject and create corresponding properties on the template for the jsonobject (**if** the jsonobject have no template set, otherwise it will simply try to bind to the properties in the existing template). And if the json is an array, it will set each enumerable result as dataobject on new rows in the array.

However this feature have never been properly implemented (the whole dynamic part of json is really lacking in errorhandling and feature-completion) so using it might produce some strange behaviour.

That's the reason I wanted to throw a proper starcounter-exception here instead. If you want to add a dynamic object, you do as you otherwise do, assign a new jsonobject to the property. (Just an example on how I thought, this would probably still throw the same exception since it's not working as it should)

```csharp
Dictionary<string, object> data = new Dictionary<string, object>();
DictionaryPage page = new DictionaryPage();

data.Add("Name", "An item");
data.Add("Value", "A value");

dynamic dynJson = new Json(); // no template specified. 
dynJson.Data = data;

page.Item = dynJson;
```

With that said, my problem here, is that I honestly don't know what the expected result should be. Do you really want all public properties on the dictionary exposed to the client? Because that is probably what's happened, and the reason for the exception when it tries to map some property that is not properly supported.

**Comment by miyconst** [comment]
I would expect the dictionary to be treated as an object where keys are properties. Both Microsoft and Newtonsoft JSON serializers serialize dictionary into an object, and I would except the same behavior in Starcounter.

**Comment by chrhol** [comment]
Alright, lets keep this issue as a feature-request then. It doesn't work like this today, and I think we need to spend a lot of time cleaning and fixing the dynamic parts of TypedJSON to have it as a viable option.
