### ISSUE TITLE
Issue in SC Admin Panel SQL Query

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3688]
SC Version V2.2.1.2501

Following 2 queries work fine : 
1. `select count(a) from adfenix.database.classifiedhomead a where publicationowner.domain='www.lansfast.se' and home.hometype.name is null`
2. `select count(a) from adfenix.database.classifiedhomead a where publicationowner.domain='www.lansfast.se' and uniqueidentifier is not null`

But when I make 1 query out of the above 2, and execute them I get an exception : 
Query : `select count(a) from adfenix.database.classifiedhomead a where publicationowner.domain='www.lansfast.se' and home.hometype.name is null and uniqueidentifier is not null`

Exception : `System.NotSupportedException: Attempt to access a string attribute as something other then a string attribute.`

Image : 
![pasted_image_at_2016_06_07_02_47_pm](https://cloud.githubusercontent.com/assets/4388707/15858172/7b13f9e4-2cbf-11e6-9526-0317adf78157.png)

**Comment by k-rus** [comment]
Thank you for reporting the issue!
It would be great if you post entire stack trace by copy-pasting it in text. Screen shots are great, but it is difficult to use information from them. The stack trace will help us to understand which part of the system to look for the bug.

**Comment by per-samuelsson** [comment]
> It would be great if you post entire stack trace by copy-pasting it in text. Screen shots are great, but it is difficult to use information from them.

@andwah, can we at some point add a Copy-button to these dialogs allowing the user to copy all relevant content to the clipboard, or is that something not easliy done?

**Comment by miyconst** [comment]
As I remember `uniqueidentifier` is a reserved keyword and it should be escaped with `"`.

**Comment by k-rus** [comment]
> As I remember uniqueidentifier is a reserved keyword and it should be escaped with ".

`uniqueidentifier` cannot be a reserved keyword. `unique` is a reserved keyword. Furthermore, if I understood correctly, the second query works, but the third query, which is combination of the first and second, does not work.

**Comment by atifwaqar** [comment]
@k-rus here is the full stack trace : 
```
at Starcounter.Internal.DbState.View.GetObject(TypeBinding binding, Int32 index, Object proxy) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-325\Level1\src\Starcounter\Internal\DbState.cs:line 71
 at AdFenix.Database.Concept.Starcounter.IObjectView.GetObject(Int32 index)
 at Starcounter.Query.Execution.StringPath.EvaluateToString(IObjectView obj) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-325\Level1\src\Starcounter\Query\Execution\Paths\StringPath.cs:line 154
 at Starcounter.Query.Execution.ComparisonString.Evaluate(IObjectView obj) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-325\Level1\src\Starcounter\Query\Execution\LogicalExpressions\ComparisonString.cs:line 141
 at Starcounter.Query.Execution.LogicalOperation.Evaluate(IObjectView obj) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-325\Level1\src\Starcounter\Query\Execution\LogicalExpressions\LogicalOperation.cs:line 131
 at Starcounter.Query.Execution.LogicalOperation.Evaluate(IObjectView obj) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-325\Level1\src\Starcounter\Query\Execution\LogicalExpressions\LogicalOperation.cs:line 127
 at Starcounter.Query.Execution.LogicalOperation.Filtrate(IObjectView obj) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-325\Level1\src\Starcounter\Query\Execution\LogicalExpressions\LogicalOperation.cs:line 209
 at Starcounter.Enumerator.MoveNext() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-325\Level1\src\Starcounter\Mock\Enumerator.cs:line 253
 at Starcounter.Query.Execution.IndexScan.MoveNextManaged() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-325\Level1\src\Starcounter\Query\Execution\Enumerators\IndexScan.cs:line 475
 at Starcounter.Query.Execution.IndexScan.MoveNext() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-325\Level1\src\Starcounter\Query\Execution\Enumerators\IndexScan.cs:line 512
 at Starcounter.Query.Execution.Aggregation.MoveNext() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-325\Level1\src\Starcounter\Query\Execution\Enumerators\Aggregation.cs:line 188
 at Starcounter.Internal.SqlRestHandler.ExecuteQuery(String query, Int32 maxResult) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-325\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\SqlRestHandler.cs:line 138
```


@miyconst are you sure about `uniqueidentifier` when you say :

> As I remember uniqueidentifier is a reserved keyword and it should be escaped with ".

Because I can execute the following query :
```
select count(a) from adfenix.database.classifiedhomead a where publicationowner.domain='www.lansfast.se' and uniqueidentifier is not null
```

**Comment by atifwaqar** [comment]
Ok I installed the latest nightly build (2.2.1.2604) just now and here is the stacktrace : 

```
at Starcounter.Internal.DbState.View.GetObject(TypeBinding binding, Int32 index, Object proxy) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-373\Level1\src\Starcounter\Internal\DbState.cs:line 71
 at AdFenix.Database.Concept.Starcounter.IObjectView.GetObject(Int32 index)
 at Starcounter.Query.Execution.StringPath.EvaluateToString(IObjectView obj) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-373\Level1\src\Starcounter\Query\Execution\Paths\StringPath.cs:line 154
 at Starcounter.Query.Execution.ComparisonString.Evaluate(IObjectView obj) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-373\Level1\src\Starcounter\Query\Execution\LogicalExpressions\ComparisonString.cs:line 141
 at Starcounter.Query.Execution.LogicalOperation.Evaluate(IObjectView obj) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-373\Level1\src\Starcounter\Query\Execution\LogicalExpressions\LogicalOperation.cs:line 131
 at Starcounter.Query.Execution.LogicalOperation.Evaluate(IObjectView obj) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-373\Level1\src\Starcounter\Query\Execution\LogicalExpressions\LogicalOperation.cs:line 127
 at Starcounter.Query.Execution.LogicalOperation.Filtrate(IObjectView obj) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-373\Level1\src\Starcounter\Query\Execution\LogicalExpressions\LogicalOperation.cs:line 209
 at Starcounter.Enumerator.MoveNext() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-373\Level1\src\Starcounter\Mock\Enumerator.cs:line 253
 at Starcounter.Query.Execution.IndexScan.MoveNextManaged() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-373\Level1\src\Starcounter\Query\Execution\Enumerators\IndexScan.cs:line 475
 at Starcounter.Query.Execution.IndexScan.MoveNext() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-373\Level1\src\Starcounter\Query\Execution\Enumerators\IndexScan.cs:line 512
 at Starcounter.Query.Execution.Aggregation.MoveNext() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-373\Level1\src\Starcounter\Query\Execution\Enumerators\Aggregation.cs:line 188
 at Starcounter.Internal.SqlRestHandler.ExecuteQuery(String query, Int32 maxResult) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-373\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\SqlRestHandler.cs:line 142
```

**Comment by k-rus** [comment]
Thank you for reporting the stack trace! It gives information where to look for the problem. Now I want to reproduce it locally. Can you give description of the schema of classes and properties used in the query? If you can also provide query plan, it will be awesome.

**Comment by atifwaqar** [comment]
Will this work :
```
Tables(
 0 = AdFenix.Database.ClassifiedHomeAd
 1 = 
  TemporaryType(
   0 : Int64
  )
)
Projection(
 0 = 
  IntegerProperty(1, 0)
)
Aggregation(
 1
 IndexScan(
  auto ON AdFenix.Database.ClassifiedHomeAd
  0
  __id
  UIntegerDynamicRange(
  )
  LogicalOperation(
   AND
   LogicalOperation(
    AND
    ComparisonString(
     Equal
     StringPath(
      ObjectProperty(0, PublicationOwner)
      StringProperty(-1, Domain)
     )
     StringLiteral(www.lansfast.se)
    )
    ComparisonString(
     IS
     StringPath(
      ObjectProperty(0, Home)
      ObjectProperty(-1, HomeType)
      StringProperty(-1, Name)
     )
     StringLiteral()
    )
   )
   ComparisonString(
    ISNOT
    StringProperty(0, UniqueIdentifier)
    StringLiteral()
   )
  )
  Ascending
 )
 MultiComparer(
 )
 SetFunctions(
  IntegerSetFunction(
  COUNT
   ObjectThis(0)
  )
 )
 LogicalValue(TRUE)
)

```

**Comment by k-rus** [comment]
Thank you for the query plan. Just a note that the query plan comes from another machine by obtaining it from C# app, not from admin. Since the exception happened during query execution, Administrator should be able to provide the query plan.

@atifwaqar reported that the exception happens only on one server and does not happen on other machines. Thus it is also data related. Probably something with null values and comparing with strings.

**Comment by k-rus** [comment]
I was able to reproduce the same query plan, but not the error:

```
Tables(
 0 = Snippets.ClassifiedHomeAd
 1 = 
  TemporaryType(
   0 : Int64
  )
)
Projection(
 0 = 
  IntegerProperty(1, 0)
)
Aggregation(
 1
 IndexScan(
  auto ON Snippets.ClassifiedHomeAd
  0
  __id
  UIntegerDynamicRange(
  )
  LogicalOperation(
   AND
   LogicalOperation(
    AND
    ComparisonString(
     Equal
     StringPath(
      ObjectProperty(0, PublicationOwner)
      StringProperty(-1, Domain)
     )
     StringLiteral(www.lansfast.se)
    )
    ComparisonString(
     IS
     StringPath(
      ObjectProperty(0, Home)
      ObjectProperty(-1, HomeType)
      StringProperty(-1, Name)
     )
     StringLiteral()
    )
   )
   ComparisonString(
    ISNOT
    StringProperty(0, UniqueIdentifier)
    StringLiteral()
   )
  )
  Ascending
 )
 MultiComparer(
 )
 SetFunctions(
  IntegerSetFunction(
  COUNT
   ObjectThis(0)
  )
 )
 LogicalValue(TRUE)
)
```

**Comment by k-rus** [comment]
I cannot reproduce the issue on a small example. So I will need to obtain the database, where it fails. However, I will be on vacation and cannot do in nearest future.
@atifwaqar 
Can you let me know if the failing database will be provided to someone else in Starcounter for the other reason or if it is already available?

**Comment by atifwaqar** [comment]
I prepared the backup for you, where should I Share it?
Do you guys have any common space where people send you the DBs to investigate?

**Comment by k-rus** [comment]
> I prepared the backup for you, where should I Share it?

I can share a special folder on dropbox to your email address. I know one with attic sheikh87. Can I share to there? How big is the back up?

**Comment by atifwaqar** [comment]
Its a rar file of 3.29 GB

**Comment by k-rus** [comment]
> Its a rar file of 3.29 GB

I guess dropbox will be to slow. @dan31 do we have any place where such archive can be uploaded?

**Comment by dan31** [comment]
It would be difficult to trace the issue back. I am archiving it.

**Comment by atifwaqar** [comment]
I still have this issue in SC Version 2.3.0.5916
![image](https://cloud.githubusercontent.com/assets/4388707/23987285/1ed008a6-0a29-11e7-8126-3992da7530d9.png)
