### ISSUE TITLE
Weaver error

### ISSUE THREAD

**Issue by linkdata** [Starcounter/Starcounter#3697]
@per-samuelsson : is this something you want to look into?

2016-06-10 10:31:02	Error	#sc://anteater/personal	Starcounter.Server.Commands	
```
System.Exception:  ScErrUnhandledWeaverException (SCERR6066): An unhandled, unidentified (non-Starcounter) exception occurred in the weaver. Version: 2.3.1657. Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR6066. ---> System.IO.IOException: The process cannot access the file 'C:\Users\Johan\Documents\Starcounter\Personal\Temp\epl0\epl0-20160609T095036591\weaver\AC42E872EDFAF21729E3008468F81661389E403D\LogStreamer.exe' because it is being used by another process.    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)    at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)    at Starcounter.Internal.Weaver.ScCopyTask.Execute() in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-171\Level1\src\scweaver\Starcounter.Internal.Weaver\ScCopyTask.cs:line 76    at PostSharp.Sdk.Extensibility.Project.ExecutePhase(String phase)    at PostSharp.Hosting.PostSharpObject.ExecuteProjects()    at PostSharp.Hosting.PostSharpObject.ProcessAssemblies(ModuleLoadStrategy[] modules)    at Starcounter.Weaver.CodeWeaver.Execute() in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-171\Level1\src\scweaver\CodeWeaver.cs:line 400    at Starcounter.Weaver.CodeWeaver.ExecuteCurrent(CodeWeaver weaver) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-171\Level1\src\scweaver\CodeWeaver.cs:line 234    at Starcounter.Weaver.Program.ExecuteWeaveCommand(String inputDirectory, String outputDirectory, String cacheDirectory, String fileName, ApplicationArguments arguments) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-171\Level1\src\scweaver\Program.cs:line 205    at Starcounter.Weaver.Program.ApplyOptionsAndExecuteGivenCommand(ApplicationArguments arguments) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-171\Level1\src\scweaver\Program.cs:line 156    at Starcounter.Weaver.Program.Main(String[] args) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-171\Level1\src\scweaver\Program.cs:line 36    --- End of inner exception stack trace ---
   at Starcounter.Server.WeaverService.LogAndRaiseExceptionFromFailingWeaver(ToolInvocationException e) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-171\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 198
   at Starcounter.Server.WeaverService.Weave(String givenAssembly, String runtimeDirectory, Boolean disableEditionLibraries) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-171\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 121
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.<>c__DisplayClass4_0.<Execute>b__2(CommandTask task) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-171\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 99
   at Starcounter.Server.Commands.CommandProcessor.<>c__DisplayClass68_0.<WithinTask>b__0(CommandTask t) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-171\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 484
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-171\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 510
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.Execute() in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-171\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 108
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-171\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR6066
```

2016-06-10 10:31:02	Error	#sc://anteater/personal	Starcounter.Server.Weaver	 
```
 ScErrUnhandledWeaverException (SCERR6066): An unhandled, unidentified (non-Starcounter) exception occurred in the weaver. Version: 2.3.1657. Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR6066. ---> System.IO.IOException: The process cannot access the file 'C:\Users\Johan\Documents\Starcounter\Personal\Temp\
epl0\
epl0-20160609T095036591\weaver\AC42E872EDFAF21729E3008468F81661389E403D\LogStreamer.exe' because it is being used by another process.
    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
    at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)    at Starcounter.Internal.Weaver.ScCopyTask.Execute() in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-171\Level1\src\scweaver\Starcounter.Internal.Weaver\ScCopyTask.cs:line 76
    at PostSharp.Sdk.Extensibility.Project.ExecutePhase(String phase)
    at PostSharp.Hosting.PostSharpObject.ExecuteProjects() 
    at PostSharp.Hosting.PostSharpObject.ProcessAssemblies(ModuleLoadStrategy[] modules)
    at Starcounter.Weaver.CodeWeaver.Execute() in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-171\Level1\src\scweaver\CodeWeaver.cs:line 400
    at Starcounter.Weaver.CodeWeaver.ExecuteCurrent(CodeWeaver weaver) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-171\Level1\src\scweaver\CodeWeaver.cs:line 234
    at Starcounter.Weaver.Program.ExecuteWeaveCommand(String inputDirectory, String outputDirectory, String cacheDirectory, String fileName, ApplicationArguments arguments) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-171\Level1\src\scweaver\Program.cs:line 205   
    at Starcounter.Weaver.Program.ApplyOptionsAndExecuteGivenCommand(ApplicationArguments arguments) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-171\Level1\src\scweaver\Program.cs:line 156
    at Starcounter.Weaver.Program.Main(String[] args) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-171\Level1\src\scweaver\Program.cs:line 36
    --- End of inner exception stack trace ---
```

2016-06-10 10:31:02	Error	#sc://anteater/personal	Starcounter.Server
```
ScErrWeavingError (SCERR2030): At least one error has been detected during weaving of the application code. Process exit code: 6066.
Arguments=--nocache --maxerrors=1 --ErrorParcelId=A4A7D6FA-EB34-442A-B579-DBB1DBB859E3 Weave "C:\Proj\LogStreamer\bin\Debug\LogStreamer.exe" --outdir="C:\Users\Johan\Documents\Starcounter\Personal\Temp\
epl0\
epl0-20160609T095036591\weaver\AC42E872EDFAF21729E3008468F81661389E403D"
Output:
A4A7D6FA-EB34-442A-B579-DBB1DBB859E3System.Exception: ScErrUnhandledWeaverException (SCERR6066): An unhandled, unidentified (non-Starcounter) exception occurred in the weaver.
Version: 2.3.1657.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR6066. ---> System.IO.IOException: The process cannot access the file 'C:\Users\Johan\Documents\Starcounter\Personal\Temp\
epl0\
epl0-20160609T095036591\weaver\AC42E872EDFAF21729E3008468F81661389E403D\LogStreamer.exe' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at Starcounter.Internal.Weaver.ScCopyTask.Execute() in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-171\Level1\src\scweaver\Starcounter.Internal.Weaver\ScCopyTask.cs:line 76
   at PostSharp.Sdk.Extensibility.Project.ExecutePhase(String phase)
   at PostSharp.Hosting.PostSharpObject.ExecuteProjects()
   at PostSharp.Hosting.PostSharpObject.ProcessAssemblies(ModuleLoadStrategy[] modules)
   at Starcounter.Weaver.CodeWeaver.Execute() in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-171\Level1\src\scweaver\CodeWeaver.cs:line 400
   at Starcounter.Weaver.CodeWeaver.ExecuteCurrent(CodeWeaver weaver) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-171\Level1\src\scweaver\CodeWeaver.cs:line 234
   at Starcounter.Weaver.Program.ExecuteWeaveCommand(String inputDirectory, String outputDirectory, String cacheDirectory, String fileName, ApplicationArguments arguments) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-171\Level1\src\scweaver\Program.cs:line 205
   at Starcounter.Weaver.Program.ApplyOptionsAndExecuteGivenCommand(ApplicationArguments arguments) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-171\Level1\src\scweaver\Program.cs:line 156
   at Starcounter.Weaver.Program.Main(String[] args) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-171\Level1\src\scweaver\Program.cs:line 36
   --- End of inner exception stack trace ---A4A7D6FA-EB34-442A-B579-DBB1DBB859E3
System.Exception: ScErrUnhandledWeaverException (SCERR6066): An unhandled, unidentified (non-Starcounter) exception occurred in the weaver.
Version: 2.3.1657.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR6066. ---> System.IO.IOException: The process cannot access the file 'C:\Users\Johan\Documents\Starcounter\Personal\Temp\
epl0\
epl0-20160609T095036591\weaver\AC42E872EDFAF21729E3008468F81661389E403D\LogStreamer.exe' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at Starcounter.Internal.Weaver.ScCopyTask.Execute() in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-171\Level1\src\scweaver\Starcounter.Internal.Weaver\ScCopyTask.cs:line 76
   at PostSharp.Sdk.Extensibility.Project.ExecutePhase(String phase)
   at PostSharp.Hosting.PostSharpObject.ExecuteProjects()
   at PostSharp.Hosting.PostSharpObject.ProcessAssemblies(ModuleLoadStrategy[] modules)
   at Starcounter.Weaver.CodeWeaver.Execute() in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-171\Level1\src\scweaver\CodeWeaver.cs:line 400
   at Starcounter.Weaver.CodeWeaver.ExecuteCurrent(CodeWeaver weaver) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-171\Level1\src\scweaver\CodeWeaver.cs:line 234
   at Starcounter.Weaver.Program.ExecuteWeaveCommand(String inputDirectory, String outputDirectory, String cacheDirectory, String fileName, ApplicationArguments arguments) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-171\Level1\src\scweaver\Program.cs:line 205
   at Starcounter.Weaver.Program.ApplyOptionsAndExecuteGivenCommand(ApplicationArguments arguments) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-171\Level1\src\scweaver\Program.cs:line 156
   at Starcounter.Weaver.Program.Main(String[] args) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-171\Level1\src\scweaver\Program.cs:line 36
   --- End of inner exception stack trace ---

Version: 2.3.1657.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR2030
```

**Comment by per-samuelsson** [comment]
> [...] is this something you want to look into?

Define *want* to? :wink:

Looks very much like #3411.

**Comment by per-samuelsson** [comment]
Are you stuck, or can you get out of it with help of #3411?

If you're not stuck, I'll close this as a duplicate of that, and raise the prio of getting it fixed.

**Comment by linkdata** [comment]
It's a duplicate, so I'll close this one.
