### ISSUE TITLE
Upgrade mode: even though uninstallation failed, installation goes on

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Starcounter#3710]
I was upgrading SC and an error occurred during uninstallation step:
![image](https://cloud.githubusercontent.com/assets/6013217/16122819/d8ef9a66-33e8-11e6-8a12-bf6376d4bf66.png)
But then, installation went on like nothing ever happened. It hanged.
I don't have any reproduction available, I don't know why uninstallation has failed

**Comment by andwah** [comment]
Interesting.. It seems that the uninstallation was "cancelled" and a cleanup was executed. after uninstallation the new version checks if there is an existing version installed if not then the new version is installed.   
The question is why was the uninstallation aborted, i will take a look and see what i can find.

**Comment by andwah** [comment]
The installer generates a log file here:
%ProgramData%/Starcounter/ScSetup.log

Will you take a look and see if you can find some related error in the file?

**Comment by joozek78** [comment]
It seems that it was case of VS running (but I got no warning about it from installer)

```
16-Jun-16 17:34:17, 0%: --------- Starting new Starcounter setup session ---------
16-Jun-16 17:34:18, 0%: Removing Starcounter server service...
16-Jun-16 17:34:18, 0%: Removing Personal Server environment variables...
16-Jun-16 17:34:19, 0%: Deleting personal database server registry entries...
16-Jun-16 17:34:19, 0%: Deleting personal database server configuration...
16-Jun-16 17:34:19, 25%: Deleting Visual Studio 2015 Starcounter integration...
16-Jun-16 17:34:19, 25%: Using VS IDE installation directory "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE" (Exist: True).
16-Jun-16 17:34:19, 25%: System.Exception: ScErrInstallerVStudioIsRunning (SCERR11003): One or more instances of Microsoft Visual Studio (devenv.exe) are running. Please shut them down and press OK.
Version: 2.2.1.2534.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR11003.
   at Starcounter.InstallerEngine.UninstallEngine.UninstallAllComponents() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-357\Level1\src\Starcounter.Installer\Starcounter.InstallerEngine\UninstallEngine.cs:line 228
   at Starcounter.InstallerEngine.UninstallEngine.UninstallStarcounter(Boolean cleanup) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-357\Level1\src\Starcounter.Installer\Starcounter.InstallerEngine\UninstallEngine.cs:line 292
   at Starcounter.InstallerEngine.InstallerMain.StarcounterSetup(String[] args, String binariesPath, String setupConfigFile, EventHandler`1 progressCallback, EventHandler`1 messageboxCallback) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-357\Level1\src\Starcounter.Installer\Starcounter.InstallerEngine\InstallerMain.cs:line 691
16-Jun-16 17:34:19, 0%: Removing Starcounter server service...
16-Jun-16 17:34:19, 0%: Removing Personal Server environment variables...
16-Jun-16 17:34:20, 0%: Deleting personal database server registry entries...
16-Jun-16 17:34:20, 0%: Deleting personal database server configuration...
16-Jun-16 17:34:20, 16%: System.NullReferenceException: Object reference not set to an instance of an object.
   at Starcounter.InstallerEngine.VSIntegration.GetVisualStudioInstallationDirectory(String version) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-357\Level1\src\Starcounter.Installer\Starcounter.InstallerEngine\Components\VSIntegration.cs:line 34
   at Starcounter.InstallerEngine.VS2012Integration.Uninstall() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-357\Level1\src\Starcounter.Installer\Starcounter.InstallerEngine\Components\VS2012Integration.cs:line 98
   at Starcounter.InstallerEngine.UninstallEngine.UninstallAllComponents() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-357\Level1\src\Starcounter.Installer\Starcounter.InstallerEngine\UninstallEngine.cs:line 219
16-Jun-16 17:34:20, 16%: System.NullReferenceException: Object reference not set to an instance of an object.
   at Starcounter.InstallerEngine.VSIntegration.GetVisualStudioInstallationDirectory(String version) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-357\Level1\src\Starcounter.Installer\Starcounter.InstallerEngine\Components\VSIntegration.cs:line 34
   at Starcounter.InstallerEngine.VS2013Integration.Uninstall() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-357\Level1\src\Starcounter.Installer\Starcounter.InstallerEngine\Components\VS2013Integration.cs:line 91
   at Starcounter.InstallerEngine.UninstallEngine.UninstallAllComponents() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-357\Level1\src\Starcounter.Installer\Starcounter.InstallerEngine\UninstallEngine.cs:line 219
16-Jun-16 17:34:20, 16%: Deleting Visual Studio 2015 Starcounter integration...
16-Jun-16 17:34:20, 16%: Using VS IDE installation directory "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE" (Exist: True).
16-Jun-16 17:34:20, 16%: System.Exception: ScErrInstallerVStudioIsRunning (SCERR11003): One or more instances of Microsoft Visual Studio (devenv.exe) are running. Please shut them down and press OK.
Version: 2.2.1.2534.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR11003.
   at Starcounter.InstallerEngine.VSIntegration.CheckVStudioRunning() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-357\Level1\src\Starcounter.Installer\Starcounter.InstallerEngine\Components\VSIntegration.cs:line 175
   at Starcounter.InstallerEngine.VS2015Integration.Uninstall() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-357\Level1\src\Starcounter.Installer\Starcounter.InstallerEngine\Components\VS2015Integration.cs:line 102
   at Starcounter.InstallerEngine.UninstallEngine.UninstallAllComponents() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-357\Level1\src\Starcounter.Installer\Starcounter.InstallerEngine\UninstallEngine.cs:line 219
16-Jun-16 17:34:20, 16%: Deleting Starcounter Demo shortcut...
16-Jun-16 17:34:20, 16%: Deleting Starcounter base environment variables...
16-Jun-16 17:34:22, 16%: Deleting Starcounter entry from the 'Add/Remove Programs' list...
16-Jun-16 17:34:22, 16%: Deleting Starcounter Start Menu items...
16-Jun-16 17:34:22, 16%: Changing Windows Firewall exceptions for Starcounter components...
16-Jun-16 17:34:23, 0%: Uninstall process finished...
16-Jun-16 17:34:23, 0%: Starcounter.InstallerEngine.InstallerAbortedException: ScErrInstallerAborted (SCERR11015): Installation process has been aborted. Starcounter uninstallation has failed. User proceeded with clean up. Clean up finished.
Version: 2.2.1.2534.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR11015.
   at Starcounter.InstallerEngine.InstallerMain.StarcounterSetup(String[] args, String binariesPath, String setupConfigFile, EventHandler`1 progressCallback, EventHandler`1 messageboxCallback) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-357\Level1\src\Starcounter.Installer\Starcounter.InstallerEngine\InstallerMain.cs:line 773
16-Jun-16 17:34:23, 0%:    at Starcounter.InstallerEngine.InstallerMain.StarcounterSetup(String[] args, String binariesPath, String setupConfigFile, EventHandler`1 progressCallback, EventHandler`1 messageboxCallback) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-357\Level1\src\Starcounter.Installer\Starcounter.InstallerEngine\InstallerMain.cs:line 773
16-Jun-16 17:34:54, 0%: Deleting installation directory...
16-Jun-16 17:39:12, 0%: --------- Starting new Starcounter setup session ---------
16-Jun-16 17:39:13, 0%: Deleting Visual Studio 2015 Starcounter integration...
16-Jun-16 17:39:13, 0%: Using VS IDE installation directory "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE" (Exist: True).
16-Jun-16 17:39:19, 0%: One or more instances of Microsoft Visual Studio (devenv.exe) are running. Please shut them down and press OK.
16-Jun-16 17:39:29, 0%: Debug: deleting VS extension directory "C:\Users\joozek\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\5pqll4us.jfy".
16-Jun-16 17:39:29, 25%: Deleting Starcounter base environment variables...
16-Jun-16 17:39:30, 25%: Deleting Starcounter entry from the 'Add/Remove Programs' list...
16-Jun-16 17:39:30, 25%: Deleting Starcounter Start Menu items...
16-Jun-16 17:39:30, 25%: Changing Windows Firewall exceptions for Starcounter components...
16-Jun-16 17:39:30, 0%: Uninstall process finished...
16-Jun-16 17:39:44, 0%: Deleting installation directory...
16-Jun-16 17:40:02, 0%: --------- Starting new Starcounter setup session ---------
16-Jun-16 17:40:02, 0%: Setting rights for current user on installation directory...
16-Jun-16 17:40:02, 0%: Creating environment variables for installation base...
16-Jun-16 17:40:03, 0%: Creating base Start Menu items...
16-Jun-16 17:40:04, 0%: Adding Starcounter to the 'Add/Remove Programs' list...
16-Jun-16 17:40:04, 0%: Changing Windows Firewall exceptions for Starcounter components...
16-Jun-16 17:40:04, 20%: Creating environment variables for personal database engine...
16-Jun-16 17:40:04, 20%: Installing server...
16-Jun-16 17:40:04, 20%: Adding Starcounter server service...
16-Jun-16 17:40:04, 20%: Creating Personal Server shortcuts...
16-Jun-16 17:40:04, 40%: Creating TrayIcon shortcut
16-Jun-16 17:40:04, 80%: Evaluating if Visual Studio 2012 integration should and can be installed...
16-Jun-16 17:40:04, 80%: Evaluating if Visual Studio 2013 integration should and can be installed...
16-Jun-16 17:40:04, 80%: Evaluating if Visual Studio 2015 integration should and can be installed...
16-Jun-16 17:40:04, 80%: Installing Microsoft Visual Studio 2015 Starcounter integration...
16-Jun-16 17:40:04, 80%: Using VS IDE installation directory "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE" (Exist: True).
16-Jun-16 17:40:08, 0%: Installation process finished...
```

**Comment by andwah** [comment]
Thanks for the log.,  I will try to fix this.

**Comment by Mackiovello** [comment]
I had the same issue today.
This is the log:
```2016-11-29 11:06:01, 0%: --------- Starting new Starcounter setup session ---------

2016-11-29 11:06:02, 0%: Removing Starcounter server service...

2016-11-29 11:06:02, 0%: Removing Personal Server environment variables...

2016-11-29 11:06:06, 0%: Deleting personal database server registry entries...

2016-11-29 11:06:06, 0%: Deleting personal database server configuration...

2016-11-29 11:06:06, 25%: Deleting Visual Studio 2015 Starcounter integration...

2016-11-29 11:06:06, 25%: Using VS IDE installation directory "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE" (Exist: True).

2016-11-29 11:06:06, 25%: System.Exception: ScErrInstallerVStudioIsRunning (SCERR11003): One or more instances of Microsoft Visual Studio (devenv.exe) are running. Please shut them down and press OK.
Version: 2.2.2.3843.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR11003.
   at Starcounter.InstallerEngine.UninstallEngine.UninstallAllComponents() in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-584\Level1\src\Starcounter.Installer\Starcounter.InstallerEngine\UninstallEngine.cs:line 228
   at Starcounter.InstallerEngine.UninstallEngine.UninstallStarcounter(Boolean cleanup) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-584\Level1\src\Starcounter.Installer\Starcounter.InstallerEngine\UninstallEngine.cs:line 292
   at Starcounter.InstallerEngine.InstallerMain.StarcounterSetup(String[] args, String binariesPath, String setupConfigFile, EventHandler`1 progressCallback, EventHandler`1 messageboxCallback) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-584\Level1\src\Starcounter.Installer\Starcounter.InstallerEngine\InstallerMain.cs:line 691

2016-11-29 11:06:06, 0%: Removing Starcounter server service...

2016-11-29 11:06:06, 0%: Removing Personal Server environment variables...

2016-11-29 11:06:10, 0%: Deleting personal database server registry entries...

2016-11-29 11:06:10, 0%: Deleting personal database server configuration...

2016-11-29 11:06:10, 16%: System.NullReferenceException: Object reference not set to an instance of an object.
   at Starcounter.InstallerEngine.VSIntegration.GetVisualStudioInstallationDirectory(String version) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-584\Level1\src\Starcounter.Installer\Starcounter.InstallerEngine\Components\VSIntegration.cs:line 34
   at Starcounter.InstallerEngine.VS2012Integration.Uninstall() in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-584\Level1\src\Starcounter.Installer\Starcounter.InstallerEngine\Components\VS2012Integration.cs:line 98
   at Starcounter.InstallerEngine.UninstallEngine.UninstallAllComponents() in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-584\Level1\src\Starcounter.Installer\Starcounter.InstallerEngine\UninstallEngine.cs:line 219

2016-11-29 11:06:10, 16%: System.NullReferenceException: Object reference not set to an instance of an object.
   at Starcounter.InstallerEngine.VSIntegration.GetVisualStudioInstallationDirectory(String version) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-584\Level1\src\Starcounter.Installer\Starcounter.InstallerEngine\Components\VSIntegration.cs:line 34
   at Starcounter.InstallerEngine.VS2013Integration.Uninstall() in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-584\Level1\src\Starcounter.Installer\Starcounter.InstallerEngine\Components\VS2013Integration.cs:line 91
   at Starcounter.InstallerEngine.UninstallEngine.UninstallAllComponents() in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-584\Level1\src\Starcounter.Installer\Starcounter.InstallerEngine\UninstallEngine.cs:line 219

2016-11-29 11:06:10, 16%: Deleting Visual Studio 2015 Starcounter integration...

2016-11-29 11:06:10, 16%: Using VS IDE installation directory "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE" (Exist: True).

2016-11-29 11:06:10, 16%: System.Exception: ScErrInstallerVStudioIsRunning (SCERR11003): One or more instances of Microsoft Visual Studio (devenv.exe) are running. Please shut them down and press OK.
Version: 2.2.2.3843.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR11003.
   at Starcounter.InstallerEngine.VSIntegration.CheckVStudioRunning() in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-584\Level1\src\Starcounter.Installer\Starcounter.InstallerEngine\Components\VSIntegration.cs:line 175
   at Starcounter.InstallerEngine.VS2015Integration.Uninstall() in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-584\Level1\src\Starcounter.Installer\Starcounter.InstallerEngine\Components\VS2015Integration.cs:line 102
   at Starcounter.InstallerEngine.UninstallEngine.UninstallAllComponents() in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-584\Level1\src\Starcounter.Installer\Starcounter.InstallerEngine\UninstallEngine.cs:line 219

2016-11-29 11:06:10, 16%: Deleting Starcounter Demo shortcut...

2016-11-29 11:06:10, 16%: Deleting Starcounter base environment variables...

2016-11-29 11:06:23, 16%: Deleting Starcounter entry from the 'Add/Remove Programs' list...

2016-11-29 11:06:23, 16%: Deleting Starcounter Start Menu items...

2016-11-29 11:06:23, 16%: Changing Windows Firewall exceptions for Starcounter components...

2016-11-29 11:06:24, 0%: Uninstall process finished...

2016-11-29 11:06:24, 0%: Starcounter.InstallerEngine.InstallerAbortedException: ScErrInstallerAborted (SCERR11015): Installation process has been aborted. Starcounter uninstallation has failed. User proceeded with clean up. Clean up finished.
Version: 2.2.2.3843.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR11015.
   at Starcounter.InstallerEngine.InstallerMain.StarcounterSetup(String[] args, String binariesPath, String setupConfigFile, EventHandler`1 progressCallback, EventHandler`1 messageboxCallback) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-584\Level1\src\Starcounter.Installer\Starcounter.InstallerEngine\InstallerMain.cs:line 773

2016-11-29 11:06:24, 0%:    at Starcounter.InstallerEngine.InstallerMain.StarcounterSetup(String[] args, String binariesPath, String setupConfigFile, EventHandler`1 progressCallback, EventHandler`1 messageboxCallback) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-584\Level1\src\Starcounter.Installer\Starcounter.InstallerEngine\InstallerMain.cs:line 773

```

If I then close the window by clicking on `close` it opens the "Finalizing" screen that never finishes
