### ISSUE TITLE
ScErrWeaverFailedResolveReference (SCERR2147) when starting application

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3713]
After resolving #3711, weaving failed on the same application.

```
ScErrWeaverFailedResolveReference (SCERR2147): The weaver failed to resolve a reference
to an assembly. Referenced assembly: System.Data.SQLite, Version=1.0.90.0, 
Culture=neutral, PublicKeyToken=db937bc2d44ff139. 
Probable referrer: Starcounter.Extensions.dll
(in C:\Users\Per\Git\Starcounter\PNext\Level1\bin\Debug\LibrariesWithDatabaseClasses).         
PostSharp.Sdk.CodeModel.AssemblyLoadException: 
Cannot load assembly System.Data.SQLite. [Version mismatch]
============ PostSharp Assembly Loading Log ===================
LOG: Finding the assembly with binding identity 'system.data.sqlite, version=1.0.90.0, culture=neutral, publickeytoken=db937bc2d44ff139'.
LOG: Looking in GAC for System.Data.SQLite, Version=1.0.90.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139, processorArchitecture=amd64.
LOG: Looking in GAC for System.Data.SQLite, Version=1.0.90.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139, processorArchitecture=msil.
LOG: Looking in GAC for System.Data.SQLite, Version=1.0.90.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139.
LOG: Probing location 'C:\Users\Per\Git\Starcounter\PNext\Level1\bin\Debug\System.Data.SQLite.exe' because this directory contains an assembly that has already been loaded.
LOG: The file 'C:\Users\Per\Git\Starcounter\PNext\Level1\bin\Debug\System.Data.SQLite.exe' could not be found.
LOG: Probing location 'C:\Users\Per\Git\Starcounter\PNext\Level1\bin\Debug\System.Data.SQLite.dll' because this directory contains an assembly that has already been loaded.
LOG: The file 'C:\Users\Per\Git\Starcounter\PNext\Level1\bin\Debug\System.Data.SQLite.dll' could not be found.
LOG: Probing location 'C:\Users\Per\proj\Issue3711\System.Data.SQLite.exe' because this directory is in the search path.
LOG: The file 'C:\Users\Per\proj\Issue3711\System.Data.SQLite.exe' could not be found.
LOG: Probing location 'C:\Users\Per\proj\Issue3711\System.Data.SQLite.dll' because this directory is in the search path.
LOG: File 'C:\Users\Per\proj\Issue3711\System.Data.SQLite.dll' has identity 'system.data.sqlite, version=1.0.101.0, culture=neutral, publickeytoken=db937bc2d44ff139, processorarchitecture=msil'.
LOG: Invoking IClrHostBindingPolicyManager::EvaluatePolicy("System.Data.SQLite, Version=1.0.101.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139")
LOG: IClrHostBindingPolicyManager::EvaluatePolicy returns postPolicyName="system.data.sqlite, version=1.0.101.0, culture=neutral, publickeytoken=db937bc2d44ff139", policiesApplied=0x0.
LOG: File 'C:\Users\Per\proj\Issue3711\System.Data.SQLite.dll' does not match the reference.
LOG: Probing location 'C:\Users\Per\Git\Starcounter\PNext\Level1\bin\Debug\EditionLibraries\System.Data.SQLite.exe' because this directory is in the search path.
LOG: The file 'C:\Users\Per\Git\Starcounter\PNext\Level1\bin\Debug\EditionLibraries\System.Data.SQLite.exe' could not be found.
LOG: Probing location 'C:\Users\Per\Git\Starcounter\PNext\Level1\bin\Debug\EditionLibraries\System.Data.SQLite.dll' because this directory is in the search path.
LOG: The file 'C:\Users\Per\Git\Starcounter\PNext\Level1\bin\Debug\EditionLibraries\System.Data.SQLite.dll' could not be found.
LOG: Probing location 'C:\Users\Per\Git\Starcounter\PNext\Level1\bin\Debug\LibrariesWithDatabaseClasses\System.Data.SQLite.exe' because this directory is in the search path.
LOG: The file 'C:\Users\Per\Git\Starcounter\PNext\Level1\bin\Debug\LibrariesWithDatabaseClasses\System.Data.SQLite.exe' could not be found.
LOG: Probing location 'C:\Users\Per\Git\Starcounter\PNext\Level1\bin\Debug\LibrariesWithDatabaseClasses\System.Data.SQLite.dll' because this directory is in the search path.
LOG: The file 'C:\Users\Per\Git\Starcounter\PNext\Level1\bin\Debug\LibrariesWithDatabaseClasses\System.Data.SQLite.dll' could not be found.
LOG: Probing location 'C:\Users\Per\Git\Starcounter\PNext\Level1\bin\Debug\System.Data.SQLite.exe' because this directory is in the search path.
LOG: The file 'C:\Users\Per\Git\Starcounter\PNext\Level1\bin\Debug\System.Data.SQLite.exe' could not be found.
LOG: Probing location 'C:\Users\Per\Git\Starcounter\PNext\Level1\bin\Debug\System.Data.SQLite.dll' because this directory is in the search path.
LOG: The file 'C:\Users\Per\Git\Starcounter\PNext\Level1\bin\Debug\System.Data.SQLite.dll' could not be found.
LOG: The assembly 'System.Data.SQLite' was not found.
===============================================================
   at PostSharp.Sdk.CodeModel.Domain.GetAssembly(IAssemblyName assemblyName, BindingOptions bindingOptions)
   at PostSharp.Sdk.CodeModel.AssemblyRefDeclaration.GetAssemblyEnvelope()
   at Starcounter.Internal.Weaver.ScAnalysisTask.AddModuleDependencyRecursive(ModuleDeclaration moduleDependency) in C:\Users\Per\Git\Starcounter\PNext\Level1\src\scweaver\Starcounter.Internal.Weaver\ScAnalysisTask.cs:line 348
   at Starcounter.Internal.Weaver.ScAnalysisTask.AddModuleDependencyRecursive(ModuleDeclaration moduleDependency) in C:\Users\Per\Git\Starcounter\PNext\Level1\src\scweaver\Starcounter.Internal.Weaver\ScAnalysisTask.cs:line 348
   at Starcounter.Internal.Weaver.ScAnalysisTask.Execute() in C:\Users\Per\Git\Starcounter\PNext\Level1\src\scweaver\Starcounter.Internal.Weaver\ScAnalysisTask.cs:line 470
   at PostSharp.Sdk.Extensibility.Project.ExecutePhase(String phase)
   at PostSharp.Hosting.PostSharpObject.ExecuteProjects()
   at PostSharp.Hosting.PostSharpObject.ProcessAssemblies(ModuleLoadStrategy[] modules)
   at Starcounter.Weaver.CodeWeaver.Execute() in C:\Users\Per\Git\Starcounter\PNext\Level1\src\scweaver\CodeWeaver.cs:line 364
Version: 2.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR2147.
ScErrWeaverFailedResolveReference (SCERR2147): The weaver failed to resolve a reference to an assembly. Referenced assembly: System.Data.SQLite, Version=1.0.90.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139. Probable referrer: Starcounter.Extensions.dll (in C:\Users\Per\Git\Starcounter\PNext\Level1\bin\Debug\LibrariesWithDatabaseClasses).
Version: 2.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR2147.
```

**Comment by per-samuelsson** [comment]
After doing some tests and studying these assemblies in .NET Reflector, it appears the reason is a **version mismatch**, which is also indicated by the (to verbose) error: `Cannot load assembly System.Data.SQLite. [Version mismatch]`.

The problem turns out to be that the referencing assembly (the executable, not the library guessed by the weaver) reference version `1.0.90.0` of `System.Data.SQLite.dll` while the library deployed with the application was version `1.0.100.0`.

There are two ways to solve this:

1) Retarget (recompile) the exe to reference `1.0.100.0`, or
2) deploy `1.0.90.0` with the application

Regarding [2], it turns out the `1.0.90.0` version is discontinued and no longer published on NuGet. But it's still possible to manually reference / download it by either using `nuget.exe` CLI or go to `Visual Studio | Tools | NuGet Package Manager | Package Manager Console` and run 

> PM> Install-Package System.Data.SQLite -Version 1.0.90
