### ISSUE TITLE
pnext: Unable to install app from Warehouse

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3715]
Trying to install SignIn `3.2.0` from Warehouse in the latest pnext `2.3.1870 (Jun 20, 2016 2:44:50 AM)`, but getting the following errors on application start:

```
"System.Exception: ScErrDatabaseAlreadyExists (SCERR2047): A database with the specified name already exists. Can't register new codehost ""default. Version: 2.3.1870. Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR2047. 
   at Starcounter.Server.DatabaseEngine.WaitUntilCodeHostOnline(Process codeHostProcess, Database database) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-187\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseEngine.cs:line 332
   at Starcounter.Server.DatabaseEngine.RestartCodeHost(ICommandProcessor processor, Int32 terminatingCodeHostProcessId, DatabaseInfo databaseInfo) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-187\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseEngine.cs:line 461
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-187\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR2047
"
```

```
"System.Exception: ScErrDatabaseAlreadyExists (SCERR2047): A database with the specified name already exists. Can't register new codehost ""default.
Version: 2.3.1870.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR2047.
   at Starcounter.Internal.AppsBootstrapper.RegisterNewCodehostInGateway() in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-187\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 60
   at Starcounter.Internal.AppsBootstrapper.InitAppsBootstrapper(Byte numSchedulers, UInt16 defaultUserHttpPort, UInt16 defaultSystemHttpPort, UInt32 sessionTimeoutMinutes, String dbName, Boolean noNetworkGateway) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-187\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 134
   at StarcounterInternal.Bootstrap.Control.Setup(String[] args) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-187\Level1\src\Starcounter.Bootstrap\Control.cs:line 216
   at StarcounterInternal.Bootstrap.Control.Main(String[] args) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-187\Level1\src\Starcounter.Bootstrap\Control.cs:line 55
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR2047
"
```

```
"ScErrServerCommandFailed (SCERR10011): The operation ""Starting SignIn in default"" failed.
Version: 2.3.1870.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10011."
```

```
"Starcounter.DbException: ScErrFailingEntrypoint (SCERR4259): The user code entrypoint method raised an exception. System.MissingMethodException: Method not found: 'Void Starcounter.Db.Transact(System.Action, Boolean, Int32)'.    at SignIn.SignInOut.AssureAdminSystemUser()    at SignIn.Program.Main() in C:\GitHub\Samples\SignIn\src\SignIn\Program.cs:line 18 Version: 2.3.1870. Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4259. 
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.<>c__DisplayClass4_0.<Execute>b__3(CommandTask task) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-187\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 180
   at Starcounter.Server.Commands.CommandProcessor.<>c__DisplayClass68_0.<WithinTask>b__0(CommandTask t) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-187\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 484
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-187\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 510
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.Execute() in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-187\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 194
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-187\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
ErrorCode=4259
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4259
"
```

```
"Starcounter.DbException: ScErrFailingEntrypoint (SCERR4259): The user code entrypoint method raised an exception. System.MissingMethodException: Method not found: 'Void Starcounter.Db.Transact(System.Action, Boolean, Int32)'.
   at SignIn.SignInOut.AssureAdminSystemUser()
   at SignIn.Program.Main() in C:\GitHub\Samples\SignIn\src\SignIn\Program.cs:line 18
Version: 2.3.1870.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4259.
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application, Assembly assembly) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-187\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 533
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application, ApplicationDirectory applicationDir) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-187\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 265
   at Starcounter.Hosting.Package.Process() in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-187\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 138
   at Starcounter.Hosting.Package.Process(IntPtr hPackage) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-187\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 55
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-187\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 85
ErrorCode=4259
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4259
---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application, Assembly assembly) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-187\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 507
HResult=-2146232828
---> System.MissingMethodException: Method not found: 'Void Starcounter.Db.Transact(System.Action, Boolean, Int32)'.
   at SignIn.SignInOut.AssureAdminSystemUser()
   at SignIn.Program.Main() in C:\GitHub\Samples\SignIn\src\SignIn\Program.cs:line 18
HResult=-2146233069
"
```

The most confusing part is:

```
System.MissingMethodException: Method not found: 'Void Starcounter.Db.Transact(System.Action, Boolean, Int32)'
```

```
A database with the specified name already exists. Can't register new codehost ""default.
```

cc @andwah, @per-samuelsson

**Comment by miyconst** [comment]
After this exception database gets into a wrong state, impossible to start/stop/delete database from administrator. Requires to restart server.

```
"Starcounter.DbException: ScErrDatabaseRunning (SCERR10031): The database is running. Database: 'sc://ie11win10/personal/default'.
Version: 2.3.1870.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10031.
   at Starcounter.Server.Commands.DeleteDatabaseCommandProcessor.CheckPrerequisites(Database& database, DeleteDatabaseCommand& command) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-187\Level1\src\Server\Starcounter.Server\Commands\Processors\DeleteDatabaseCommandProcessor.cs:line 78
   at Starcounter.Server.Commands.DeleteDatabaseCommandProcessor.Execute() in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-187\Level1\src\Server\Starcounter.Server\Commands\Processors\DeleteDatabaseCommandProcessor.cs:line 27
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-187\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
ErrorCode=10031
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR10031
"
```

But the database is not actually running.

**Comment by chrhol** [comment]
This is the root problem:

```
System.MissingMethodException: Method not found: 'Void Starcounter.Db.Transact(System.Action, Boolean, Int32)'
```

The app needs ro be recompiled since the signature of `Db.Transact` have changed in pnext (`forceSnapshot` removed). It might be good practice to always recompile when switching versions since you cannot be sure that everything is the same (constant values for example). 

The errors that follows that one is more serious though, you shouldn't get in a state which you cannot recover from.

**Comment by per-samuelsson** [comment]
> But the database is not actually running.

> The errors that follows that one is more serious though, you shouldn't get in a state which you cannot recover from.

That's a known bug, isn't it: #3524?

**Comment by chrhol** [comment]
> That's a known bug, isn't it: #3524?

Ahh yeah looks like it is. And it was me that reported it :blush: Had no recollection of that. Nice catch!

**Comment by miyconst** [comment]
@per-samuelsson, @chrhol thank you for the fast reply. I will release another version of SignIn app compatible with pnext for now, and close this issue as the database state problem already reported.
