### ISSUE TITLE
Exception on accessing SQL Query result in code

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3724]
Tested on SC Versions : 2.2.1.2237 + 2.2.1.2628 + 2.2.1.2631

Query with 4 rows as result : 
```
SELECT * FROM AdFenix.Database.Budget.BudgetTemplate b WHERE b.PublicationOwner.Domain = 'krogsveen.no' AND b.Seller is null AND AdSetName like '%data%' AND CampaignSpecific=false
```

The same query in C# code gives me exception when I try to access the records (Using code like  `budgetTemplates.First`): 
![image](https://cloud.githubusercontent.com/assets/4388707/16413913/10cb0ed4-3d35-11e6-8324-95c1943aa4f9.png)

StackTrace Image : 
![image](https://cloud.githubusercontent.com/assets/4388707/16413917/14064366-3d35-11e6-87fd-253c7bfcc5a2.png)

StackTrace Text : 
```
   at System.Object.GetType()
   at Starcounter.Query.Execution.TypeVariable.SetValue(Object newValue) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-325\Level1\src\Starcounter\Query\Execution\Variables\TypeVariable.cs:line 199
   at Starcounter.Query.Execution.VariableArray.ProlongValues(IExecutionEnumerator destEnum) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-325\Level1\src\Starcounter\Query\Execution\Variables\VariableArray.cs:line 85
   at Starcounter.Query.Execution.LikeExecEnumerator.MoveNext() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-325\Level1\src\Starcounter\Query\Execution\Enumerators\LikeExecEnumerator.cs:line 239
   at System.Linq.SystemCore_EnumerableDebugView`1.get_Items()
```

**Comment by atifwaqar** [comment]
Query with 3 parameters in code works fine. Query with 4 parameters in code gives the crash.

Query with 4 parameters (which is crashing) : 
```
return Db.SQL<AdFenix.Database.Budget.BudgetTemplate>("SELECT b FROM AdFenix.Database.Budget.BudgetTemplate b WHERE b.PublicationOwner.Domain = ? AND b.Seller is ? AND AdSetName like ? AND CampaignSpecific=?", this.Domain, null, "%" + type + "%", false);
```

Query with 3 parameters (which is working fine) : 
```
return Db.SQL<AdFenix.Database.Budget.BudgetTemplate>("SELECT b FROM AdFenix.Database.Budget.BudgetTemplate b WHERE b.PublicationOwner.Domain = ? AND AdSetName like ? AND CampaignSpecific=?", this.Domain, "%" + type + "%", false);
```

**Comment by k-rus** [comment]
Thank you for reporting!
Can you provide the query plan? It might help to understand more or to reproduce.

**Comment by k-rus** [comment]
To keep in mind while investigating: #3226, #3688,

**Comment by atifwaqar** [comment]
Here is the query plan (got from SC Admin Panel)
```
Tables(
 0 = AdFenix.Database.Budget.BudgetTemplate
 1 = AdFenix.Database.PublicationOwner
)
Projection(
 0 = 
  StringProperty(0, Name)
 1 = 
  StringProperty(0, ObId)
 2 = 
  StringProperty(0, HardCodedInterests)
 3 = 
  BooleanProperty(0, ZipCode)
 4 = 
  IntegerProperty(0, MaxUsers)
 5 = 
  IntegerProperty(0, MinUsers)
 6 = 
  IntegerProperty(0, Radius)
 7 = 
  BooleanProperty(0, DynamicDailyBudget)
 8 = 
  IntegerProperty(0, DailySpend)
 9 = 
  DecimalProperty(0, BudgetToReachRatio)
 10 = 
  IntegerProperty(0, MaxCPM)
 11 = 
  IntegerProperty(0, InitialTestPeriod)
 12 = 
  ObjectProperty(0, PublicationOwner)
 13 = 
  ObjectProperty(0, Seller)
 14 = 
  StringProperty(0, AdSetName)
 15 = 
  StringProperty(0, BudgetAmount)
 16 = 
  IntegerProperty(0, AdSetStartTime)
 17 = 
  IntegerProperty(0, AdSetLifeHours)
 18 = 
  BooleanProperty(0, CustomerAudience)
 19 = 
  BooleanProperty(0, TargetAudience)
 20 = 
  BooleanProperty(0, ExcludeAudience)
 21 = 
  StringProperty(0, OptimizationGoal)
 22 = 
  StringProperty(0, BillingEvent)
 23 = 
  StringProperty(0, page_types)
 24 = 
  BooleanProperty(0, CampaignSpecific)
 25 = 
  BooleanProperty(0, DirectRetargeting)
 26 = 
  BooleanProperty(0, LeftOverAdSet)
 27 = 
  IntegerProperty(0, NewBudget)
 28 = 
  IntegerProperty(0, PercentageOfTotalBudget)
 29 = 
  StringProperty(0, GetHardCodedInterests)
 30 = 
  ObjectNoProperty(0, ObjectNo)
 31 = 
  ObjectIDProperty(0, ObjectID)
)
Join(
 Inner
 IndexScan(
  auto ON AdFenix.Database.Budget.BudgetTemplate
  0
  __id
  UIntegerDynamicRange(
  )
  LogicalOperation(
   AND
   LogicalOperation(
    AND
    ComparisonObject(
     IS
     ObjectProperty(0, Seller)
     ObjectLiteral()
    )
    ComparisonString(
     LIKEstatic
     StringProperty(0, AdSetName)
     StringLiteral(%data%)
    )
   )
   ComparisonBoolean(
    Equal
    BooleanProperty(0, CampaignSpecific)
    BooleanLiteral(False)
   )
  )
  Ascending
 )
 ReferenceLookup(
  1
  ObjectProperty(0, PublicationOwner)
  ComparisonString(
   Equal
   StringProperty(1, Domain)
   StringLiteral(www.vaningen.se)
  )
 )
)

http://www.vaningen.se/tillsalu/svalov-teckomatorp-tra-1437
```

**Comment by atifwaqar** [comment]
Question : 
Is there a way to get the query plan from code as well? 
And when you ask for query plan, do you expect it from SC Admin Panel or from Code?

**Comment by k-rus** [comment]
> Is there a way to get the query plan from code as well?

You need to get it programmatically by modifying program or by debugging and watching the enumerator variable. To get in the code you need to obtain enumerator instance explicitly and then ask for the string, e.g.:

```c#
var sqlenum = Db.SQL("select b from ...").GetEnumerator();
var queryPlan = sqlenum.ToString();
```

**Comment by k-rus** [comment]
By the way, can you try to run the same query, which retrieves object `b` in administrator (however you need to put parameters inside the variable)? Do you know which input values produce the error?



> And when you ask for query plan, do you expect it from SC Admin Panel or from Code?

I am interested to see the query plan of the failing query or even better both.

**Comment by atifwaqar** [comment]
@k-rus Thanks for the code sample, I had no idea how to get this from code. 
Here is the query plan : 
```
Tables(
	0 = AdFenix.Database.Budget.BudgetTemplate
	1 = AdFenix.Database.PublicationOwner
)
Projection(
	0 = 
		ObjectThis(0)
)
Join(
	Inner
	IndexScan(
		auto ON AdFenix.Database.Budget.BudgetTemplate
		0
		__id
		UIntegerDynamicRange(
		)
		LogicalOperation(
			AND
			LogicalOperation(
				AND
				LogicalOperation(
					AND
					IsTypePredicate(
						IS
						ObjectProperty(0, Seller)
						TypeVariable(<NULL>)
					)
					ComparisonString(
						GreaterThanOrEqual
						StringProperty(0, AdSetName)
						StringVariable(%data%)
					)
				)
				ComparisonString(
					LessThan
					StringProperty(0, AdSetName)
					StringOperation(
						AppendMaxChar
						StringVariable(%data%)
					)
				)
			)
			ComparisonBoolean(
				Equal
				BooleanProperty(0, CampaignSpecific)
				BooleanVariable(False)
			)
		)
		Ascending
	)
	ReferenceLookup(
		1
		ObjectProperty(0, PublicationOwner)
		ComparisonString(
			Equal
			StringProperty(1, Domain)
			StringVariable(svenskamaklarhuset.se)
		)
	)
)

```

**Comment by atifwaqar** [comment]
Here is a small project where I have reporduced the issue.
https://drive.google.com/open?id=0B3OphiyFByHRYkNSRXVHOW51TFk

**Comment by atifwaqar** [comment]
In this case, when i remove the keyword "Order By", the code works fine

**Comment by k-rus** [comment]
> Here is a small project where I have reporduced the issue.
> https://drive.google.com/open?id=0B3OphiyFByHRYkNSRXVHOW51TFk

Thank you for the example. Which version of VS was it created?

**Comment by k-rus** [comment]
> Thank you for the example. Which version of VS was it created?

I cannot open it in VS 2015, but I will create new project based on your C# code. I believe it should work.

**Comment by k-rus** [comment]
> Here is a small project where I have reporduced the issue.
> https://drive.google.com/open?id=0B3OphiyFByHRYkNSRXVHOW51TFk

Your example uses OffsetKey, which is not supported on query plans, which requires sorting.

I don't understand how it is related to this issue. There is no Offsetkey involved in the original issue to my understanding.

**Comment by atifwaqar** [comment]
@k-rus 
I guess these are 2 different issues, but our developers and I thought they are the same. Sorry for the confusion.
and this project is a VS 2015 project
