### ISSUE TITLE
HTTP header is corrupted!

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3731]
Reloading a page I have got the following exception:

```
System.ArgumentException: HTTP header is corrupted!
   at Starcounter.HttpRequestInternal.GetHeaderValue(String headerName, String& headersString) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-382\Level1\src\Starcounter.Internal\Http\Request.cs:line 1679
   at Starcounter.Request.get_Cookies() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-382\Level1\src\Starcounter.Internal\Http\Request.cs:line 813
   at SignIn.MainHandlers.GetSignInCookie() in D:\GitHub\MM\PalmaServer\SignIn\Api\MainHandlers.cs:line 214
   at SignIn.MainHandlers.<Register>b__2_0(Request req) in D:\GitHub\MM\PalmaServer\SignIn\Api\MainHandlers.cs:line 17
   at Starcounter.Handle.RunRequestFilters(Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-382\Level1\src\Starcounter.Internal\Handle.cs:line 490
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-382\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 755
HResult=-2147024809

More information about this error may be available in the server error log.
```

Here is the request details from Chrome.

```
GET / HTTP/1.1
Host: localhost:8080
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,ru;q=0.6,zh-CN;q=0.4,zh;q=0.2,uk;q=0.2
Cookie: soauthtoken=081df0a1-8bb4-4b1a-8f25-5fe4a92b232eAdmin
```

cc @alemoi

**Comment by miyconst** [comment]
I can reproduce it:

- Setup URL rewrite to rewrite `/` to `/launcher`.
- Run Launcher + SignIn.
- Open `/launcher`.
- Sign in with any user.
- Reload page.
- **Open `/` - exception happens.** It seems like URL rewrite does not deal with cookies well.

**Comment by alemoi** [comment]
Thanks for reporting! I will reproduce and check!

**Comment by dan31** [comment]
@alemoi let's assume this is high prio. The thing looks really weird.

**Comment by alemoi** [comment]
I just reproduced the issue. Looking into it.

**Comment by alemoi** [comment]
The problem was found in URI aliasing miscalculation in gateway. Fixing it now.

**Comment by miyconst** [comment]
It looks like the nightly build failed and I can't test the fix.
