### ISSUE TITLE
ScErrUnhandledTransactConflict (SCERR4090)

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3740]
SC Version: 2.2.1.2709

I guess this is my code's issue, but this error message dont give me any info or stacktrace. How can I point or get to my code which is executing the transaction?

```
Starcounter.UnhandledTransactionConflictException: ScErrUnhandledTransactConflict (SCERR4090): The operation failed because of an unhandled transaction conflict.
Version: 2.2.1.2709.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4090.
   at Starcounter.Internal.SqlRestHandler.<>c.<Register>b__0_1(Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-393\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\SqlRestHandler.cs:line 62
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-393\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-393\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-393\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 765
ErrorCode=4090
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4090
---> Starcounter.TransactionConflictException: ScErrTransactionConflictAbort (SCERR8002): A transaction was aborted because it was in conflict with another transaction.
Version: 2.2.1.2709.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR8002.
   at Starcounter.Internal.TransactionManager.Commit(Int32 tran_locked_on_thread, Int32 detach_and_free) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-393\Level1\src\Starcounter\TransactionManager.cs:line 704
   at Starcounter.Db.Transact(Action action, UInt32 flags, Boolean forceSnapshot, Int32 maxRetries) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-393\Level1\src\Starcounter\Db.cs:line 351
ErrorCode=8002
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR8002
```

**Comment by chrhol** [comment]
That's weird, the stacktrace should include your code as well. As you say, with this information it's not possible to find out where it happens.

I will take a look.

**Comment by atifwaqar** [comment]
> Did you find this in your logs, or did it cause something else to fail?

I found this in my logs. 
And is it possible to add/print the query in logs which generated this exception?

**Comment by chrhol** [comment]
> And is it possible to add/print the query in logs which generated this exception?

Yes, it's possible. The query is available. I will add another issue for enhancing the errormessage in this case for the sqlhandler.

**Comment by chrhol** [comment]
I added a new issue for enhancing the logged error. I will close this one, since you found the exception in the log and you can safely ignore it.

**Comment by atifwaqar** [comment]
@chrhol Thanks
