### ISSUE TITLE
The weaver failed to resolve a reference to an assembly

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3744]
I am trying to start an app with a `weaver.ignore` file which contains one entry - `EPPlus.dll`.

The application fails to start with the following error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The weaver failed to resolve a reference to an assembly.
Referenced assembly: System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089. 
Probable referrer: Starcounter.Extensions.dll (in C:\Program Files\Starcounter\LibrariesWithDatabaseClasses). 
PostSharp.Sdk.CodeModel.AssemblyLoadException: Cannot load assembly System.Xml. 

============ PostSharp Assembly Loading Log =================== 
LOG: Finding the assembly with binding identity 'system.xml, version=2.0.0.0, culture=neutral, publickeytoken=b77a5c561934e089'. 
LOG: Looking in GAC for System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=amd64. 
LOG: Looking in GAC for System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=msil. 
LOG: Looking in GAC for System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089. 
LOG: Probing location 'C:\Program Files\Starcounter\System.Xml.exe' because this directory contains an assembly that has already been loaded. 
LOG: The file 'C:\Program Files\Starcounter\System.Xml.exe' could not be found. 
LOG: Probing location 'C:\Program Files\Starcounter\System.Xml.dll' because this directory contains an assembly that has already been loaded. 
LOG: The file 'C:\Program Files\Starcounter\System.Xml.dll' could not be found. 
LOG: Probing location 'C:\GitHub\MM\PalmaServer\ItemSetEditor\bin\Debug\System.Xml.exe' because this directory is in the search path. 
LOG: The file 'C:\GitHub\MM\PalmaServer\ItemSetEditor\bin\Debug\System.Xml.exe' could not be found. 
LOG: Probing location 'C:\GitHub\MM\PalmaServer\ItemSetEditor\bin\Debug\System.Xml.dll' because this directory is in the search path. 
LOG: The file 'C:\GitHub\MM\PalmaServer\ItemSetEditor\bin\Debug\System.Xml.dll' could not be found. 
LOG: Probing location 'C:\Program Files\Starcounter\EditionLibraries\System.Xml.exe' because this directory is in the search path. 
LOG: The file 'C:\Program Files\Starcounter\EditionLibraries\System.Xml.exe' could not be found. 
LOG: Probing location 'C:\Program Files\Starcounter\EditionLibraries\System.Xml.dll' because this directory is in the search path. LOG: The file 'C:\Program Files\Starcounter\EditionLibraries\System.Xml.dll' could not be found. 
LOG: Probing location 'C:\Program Files\Starcounter\LibrariesWithDatabaseClasses\System.Xml.exe' because this directory is in the search path. 
LOG: The file 'C:\Program Files\Starcounter\LibrariesWithDatabaseClasses\System.Xml.exe' could not be found. 
LOG: Probing location 'C:\Program Files\Starcounter\LibrariesWithDatabaseClasses\System.Xml.dll' because this directory is in the search path. 
LOG: The file 'C:\Program Files\Starcounter\LibrariesWithDatabaseClasses\System.Xml.dll' could not be found. 
LOG: Probing location 'C:\Program Files\Starcounter\System.Xml.exe' because this directory is in the search path. 
LOG: The file 'C:\Program Files\Starcounter\System.Xml.exe' could not be found. 
LOG: Probing location 'C:\Program Files\Starcounter\System.Xml.dll' because this directory is in the search path. 
LOG: The file 'C:\Program Files\Starcounter\System.Xml.dll' could not be found. 
LOG: The assembly 'System.Xml' was not found. 
=============================================================== 
   at PostSharp.Sdk.CodeModel.Domain.GetAssembly(IAssemblyName assemblyName, BindingOptions bindingOptions)
   at Starcounter.Internal.Weaver.ScAnalysisTask.AddModuleDependencyRecursive(ModuleDeclaration moduleDependency) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-389\Level1\src\scweaver\Starcounter.Internal.Weaver\ScAnalysisTask.cs:line 348
   at Starcounter.Internal.Weaver.ScAnalysisTask.AddModuleDependencyRecursive(ModuleDeclaration moduleDependency) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-389\Level1\src\scweaver\Starcounter.Internal.Weaver\ScAnalysisTask.cs:line 347
   at Starcounter.Internal.Weaver.ScAnalysisTask.Execute() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-389\Level1\src\scweaver\Starcounter.Internal.Weaver\ScAnalysisTask.cs:line 472
   at PostSharp.Sdk.Extensibility.Project.ExecutePhase(String phase)
   at PostSharp.Hosting.PostSharpObject.ExecuteProjects()
   at PostSharp.Hosting.PostSharpObject.ProcessAssemblies(ModuleLoadStrategy[] modules)
   at Starcounter.Weaver.CodeWeaver.Execute() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-389\Level1\src\scweaver\CodeWeaver.cs:line 364 (ScErrWeaverFailedResolveReference (SCERR2147))
```

Starcounter version: `Starcounter-DevelopNightlyBuilds-2.2.1.2697 (Jul 8, 2016 5:06:57 AM)`.

What this could mean and how to try to resolve it? The application does does not contain any reference to the `System.Xml` assembly.

cc @per-samuelsson, @chrhol

**Comment by miyconst** [comment]
Tried with the latest `Starcounter-DevelopNightlyBuilds-2.2.1.2718 (Jul 14, 2016 5:06:09 AM)` version. Same issue.

Tried to reference the `System.Xml` assembly and include it to `weaver.ignore`. Nothing seems to work.

**Comment by Mnosek** [comment]
I just had a very similar problem (not System.Xml but System.Drawing) and for me it was enough to install ".NET Framework 3.5 (includes .NET 2.0 and 3.0)" Windows feature. I think that System.Xml v2.0.0.0 refers to another version of .NET

**Comment by miyconst** [comment]
Yes, it seems to be the reason. I will close the issue as soon as I have a chance to install .NET 3.5 and make sure that it solves the problem.

**Comment by miyconst** [comment]
Thanks @Mnosek, it really was missing .NET 3.5. Closing the issue.
