### ISSUE TITLE
Unhandled exception crashes all another apps

### ISSUE THREAD

**Issue by Mnosek** [Starcounter/Starcounter#3746]
I have four apps running in one db: SignIn, UserAdmin, Launcher and ChecklistDesigner (currently developed). After starting ChecklistDesigner uncaught exception occurs and then all running apps stop immediately. I think that the other apps should be untouched.

Exception in ChecklistDesigner app:
```
System.ArgumentException was unhandled by user code
  HResult=-2147024809
  Message=Application handler is not registered: (/ChecklistDesigner/app-name
  Source=Starcounter
  StackTrace:
       at Starcounter.UriMapping.Map(String appUriToMap, String mapUri, Func`2 converterTo, Func`2 converterFrom, String method) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-206\Level1\src\Starcounter\Apps\OntologyAndOrdinaryMapping.cs:line 314
       at Starcounter.UriMapping.Map(String appUriToMap, String mapUri, String method) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-206\Level1\src\Starcounter\Apps\OntologyAndOrdinaryMapping.cs:line 261
       at ChecklistDesigner.Program.Main() in C:\Projects\SweOffshore\Sweoffshore\ChecklistDesigner\Program.cs:line 33
  InnerException: 
```

Starcounter log message:
```
Starcounter.DbException: ScErrFailingEntrypoint (SCERR4259): The user code entrypoint method raised an exception. System.ArgumentException: Application handler is not registered: (/ChecklistDesigner/app-name
   at Starcounter.UriMapping.Map(String appUriToMap, String mapUri, Func`2 converterTo, Func`2 converterFrom, String method) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-206\Level1\src\Starcounter\Apps\OntologyAndOrdinaryMapping.cs:line 314
   at Starcounter.UriMapping.Map(String appUriToMap, String mapUri, String method) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-206\Level1\src\Starcounter\Apps\OntologyAndOrdinaryMapping.cs:line 261
   at ChecklistDesigner.Program.Main() in C:\Projects\SweOffshore\Sweoffshore\ChecklistDesigner\Program.cs:line 33
Version: 2.3.2083.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4259.
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application, Assembly assembly) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-206\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 533
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application, ApplicationDirectory applicationDir) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-206\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 277
   at Starcounter.Hosting.Package.Process() in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-206\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 138
   at Starcounter.Hosting.Package.Process(IntPtr hPackage) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-206\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 55
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-206\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 85
ErrorCode=4259
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4259
---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application, Assembly assembly) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-206\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 507
HResult=-2146232828
---> System.ArgumentException: Application handler is not registered: (/ChecklistDesigner/app-name
   at Starcounter.UriMapping.Map(String appUriToMap, String mapUri, Func`2 converterTo, Func`2 converterFrom, String method) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-206\Level1\src\Starcounter\Apps\OntologyAndOrdinaryMapping.cs:line 314
   at Starcounter.UriMapping.Map(String appUriToMap, String mapUri, String method) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-206\Level1\src\Starcounter\Apps\OntologyAndOrdinaryMapping.cs:line 261
   at ChecklistDesigner.Program.Main() in C:\Projects\SweOffshore\Sweoffshore\ChecklistDesigner\Program.cs:line 33
HResult=-2147024809
```

Starcounter v2.3.2083 pnext nigtly

**Comment by linkdata** [comment]
Known issue, being discussed in https://github.com/Starcounter/Starcounter/issues/3032

**Comment by warpech** [comment]
@linkdata are you sure it is the same? In @Mnosek's case, the code that causes the exception is not async.
