### ISSUE TITLE
Improve the error message in case of Starcounter.DbException: ScErrInvalidObjectAccess (SCERR4174): The operation failed because of an invalid object access.

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#3760]
A known issue is that when we are delete an object in the database, the JSON bindings stop working. One of such examples is [here](https://github.com/RemoteCloud/SweOffshore/commit/e3452bdf834f6581a3f8519e81e2407619a79572#diff-bd62e0a291241423282222c3507775c4R32): 

<img width="641" alt="screen shot 2016-07-22 at 09 52 23" src="https://cloud.githubusercontent.com/assets/566463/17050233/13cb1f64-4ff2-11e6-9dea-1aacde0a7eda.png">

At this point a struggle begins to identify _which binding_ exactly does not work. This can take hours to identify. 

@chrhol Would it be possible to make the exception a little bit more detailed? Provide the name of the view-model, name of the property, for example:

```
Starcounter.DbException: ScErrInvalidObjectAccess (SCERR4174): The operation failed 
because of an invalid object access. (Property `TemplateSections` 
in `TemplatePage.json.g.cs`)
```

Right now the exception stack trace is very vague (see below).

```
Starcounter.DbException: ScErrInvalidObjectAccess (SCERR4174): The operation failed
because of an invalid object access.
Version: 2.3.2083.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4174.
   at Starcounter.Internal.DbState.ReadString(UInt64 oid, UInt64 address, Int32 index) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-206\Level1\src\Starcounter\Internal\DbState.cs:line 683
   at lambda_method(Closure , Json )
   at Starcounter.Templates.Property`1.CheckAndSetBoundValue(Json parent, Boolean addToChangeLog) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-206\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 208
   at Starcounter.Json.<LogObjectValueChangesWithDatabase>b__124_0(ChangeLog clog, Json json, Boolean css) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-206\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 326
   at Starcounter.Internal.TransactionManager.Scope[T1,T2,T3](TransactionHandle handle, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-206\Level1\src\Starcounter\TransactionManager.cs:line 500
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3](Json json, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-206\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 109
   at Starcounter.Json.<LogObjectValueChangesWithDatabase>b__124_0(ChangeLog clog, Json json, Boolean css) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-206\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 302
   at Starcounter.Internal.TransactionManager.Scope[T1,T2,T3](TransactionHandle handle, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-206\Level1\src\Starcounter\TransactionManager.cs:line 500
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3](Json json, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-206\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 109
   at Starcounter.Json.<LogObjectValueChangesWithDatabase>b__124_0(ChangeLog clog, Json json, Boolean css) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-206\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 302
   at Starcounter.Internal.TransactionManager.Scope[T1,T2,T3](TransactionHandle handle, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-206\Level1\src\Starcounter\TransactionManager.cs:line 500
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3](Json json, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-206\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 109
   at Starcounter.Json.<LogObjectValueChangesWithDatabase>b__124_0(ChangeLog clog, Json json, Boolean css) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-206\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 357
   at Starcounter.Internal.TransactionManager.Scope[T1,T2,T3](TransactionHandle handle, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-206\Level1\src\Starcounter\TransactionManager.cs:line 500
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3](Json json, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-206\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 109
   at Starcounter.Json.LogArrayChangesWithDatabase(ChangeLog changeLog, Boolean callStepSiblings) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-206\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 239
   at Starcounter.Json.<LogObjectValueChangesWithDatabase>b__124_0(ChangeLog clog, Json json, Boolean css) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-206\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 302
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3](Json json, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-206\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 111
   at Starcounter.Json.LogObjectValueChangesWithDatabase(ChangeLog changeLog, Boolean callStepSiblings) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-206\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 369
   at Starcounter.XSON.ChangeLog.Generate(Boolean flushLog) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-206\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\ChangeLog.cs:line 86
   at Starcounter.XSON.JsonPatch.Generate(ChangeLog changeLog, Boolean includeNamespace, Boolean flushLog, Byte[]& patches) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-206\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 111
   at Starcounter.XSON.JsonPatch.Generate(Json json, Boolean flushLog, Boolean includeNamespace, Byte[]& patches) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-206\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 90
   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(Byte[] bs, WebSocket ws) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-206\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 62
   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 managedHandlerId, UInt32 groupId, WebSocket ws) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-206\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 289
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\TeamCity\TeamCity9\buildAgent\work\sc-pnext-nightly-206\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 784
ErrorCode=4174
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4174
```

**Comment by warpech** [comment]
@chrhol any chance of improving this?

**Comment by chrhol** [comment]
I agree, it would be nice to improve the message. I'm not sure exactly how though, since this exception can come from plenty of places (anywhere when the dataobject is accessed), so it's not just one catch where extra info can be added. 

I will take a look.

**Comment by chrhol** [comment]
I added another exception, on top of the original exception that includes the (full path) of the viewmodel and the property where the binding failed. This exception is thrown for all exceptions that happens when a binding is used.

To the see the cause, you check the inner exception (the one that is marked with `--->`)

It's currently only pushed to `pnext`, not sure if it should be added to develop or not.

```
System.Exception: ScErrDataBindingForJsonException (SCERR14012): An exception occurred when a databinding for a property in json was used. Property 'PlannedTime$' in 'Master.Applications.ApplicationContainer.ActionBoardApp.EditAction.ActionDetails'.
Version: 2.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR14012.
   at lambda_method(Closure , Json )
   at Starcounter.Templates.Property`1.CheckAndSetBoundValue(Json parent, Boolean addToChangeLog) in d:\code\Starcounter\Pnext\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 208
   at Starcounter.Json.<>c__DisplayClass125_0.<SetBoundValuesInTuple>b__0(Json json) in d:\code\Starcounter\Pnext\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 406
   at Starcounter.Internal.TransactionManager.Scope[T](TransactionHandle handle, Action`1 action, T arg) in d:\code\Starcounter\Pnext\Level1\src\Starcounter\TransactionManager.cs:line 478
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T](Json json, Action`1 action, T arg) in d:\code\Starcounter\Pnext\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 93
   at Starcounter.Json.SetBoundValuesInTuple(Boolean callStepSiblings) in d:\code\Starcounter\Pnext\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 391
   at Starcounter.Json.<>c__DisplayClass125_0.<SetBoundValuesInTuple>b__0(Json json) in d:\code\Starcounter\Pnext\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 402
   at Starcounter.Internal.TransactionManager.Scope[T](TransactionHandle handle, Action`1 action, T arg) in d:\code\Starcounter\Pnext\Level1\src\Starcounter\TransactionManager.cs:line 478
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T](Json json, Action`1 action, T arg) in d:\code\Starcounter\Pnext\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 93
   at Starcounter.Json.SetBoundValuesInTuple(Boolean callStepSiblings) in d:\code\Starcounter\Pnext\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 391
   at Starcounter.Json.<LogObjectValueChangesWithDatabase>b__124_0(ChangeLog clog, Json json, Boolean css) in d:\code\Starcounter\Pnext\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 295
   at Starcounter.Internal.TransactionManager.Scope[T1,T2,T3](TransactionHandle handle, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in d:\code\Starcounter\Pnext\Level1\src\Starcounter\TransactionManager.cs:line 500
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3](Json json, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in d:\code\Starcounter\Pnext\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 143
   at Starcounter.Json.LogObjectValueChangesWithDatabase(ChangeLog changeLog, Boolean callStepSiblings) in d:\code\Starcounter\Pnext\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 275
   at Starcounter.Json.LogValueChangesWithDatabase(ChangeLog changeLog, Boolean callStepSiblings) in d:\code\Starcounter\Pnext\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 189
   at Starcounter.Json.<LogObjectValueChangesWithDatabase>b__124_0(ChangeLog clog, Json json, Boolean css) in d:\code\Starcounter\Pnext\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 368
   at Starcounter.Internal.TransactionManager.Scope[T1,T2,T3](TransactionHandle handle, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in d:\code\Starcounter\Pnext\Level1\src\Starcounter\TransactionManager.cs:line 500
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3](Json json, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in d:\code\Starcounter\Pnext\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 143
   at Starcounter.Json.LogObjectValueChangesWithDatabase(ChangeLog changeLog, Boolean callStepSiblings) in d:\code\Starcounter\Pnext\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 275
   at Starcounter.Json.LogValueChangesWithDatabase(ChangeLog changeLog, Boolean callStepSiblings) in d:\code\Starcounter\Pnext\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 189
   at Starcounter.Json.LogArrayChangesWithDatabase(ChangeLog changeLog, Boolean callStepSiblings) in d:\code\Starcounter\Pnext\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 251
   at Starcounter.Json.LogValueChangesWithDatabase(ChangeLog changeLog, Boolean callStepSiblings) in d:\code\Starcounter\Pnext\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 187
   at Starcounter.Json.<LogObjectValueChangesWithDatabase>b__124_0(ChangeLog clog, Json json, Boolean css) in d:\code\Starcounter\Pnext\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 306
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3](Json json, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in d:\code\Starcounter\Pnext\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 145
   at Starcounter.Json.LogObjectValueChangesWithDatabase(ChangeLog changeLog, Boolean callStepSiblings) in d:\code\Starcounter\Pnext\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 275
   at Starcounter.Json.LogValueChangesWithDatabase(ChangeLog changeLog, Boolean callStepSiblings) in d:\code\Starcounter\Pnext\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 189
   at Starcounter.XSON.ChangeLog.Generate(Boolean flushLog, Change[]& changeArr) in d:\code\Starcounter\Pnext\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\ChangeLog.cs:line 96
   at Starcounter.XSON.JsonPatch.Generate(ChangeLog changeLog, Boolean includeNamespace, Boolean flushLog, Byte[]& patches) in d:\code\Starcounter\Pnext\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 115
   at Starcounter.XSON.JsonPatch.Generate(Json json, Boolean flushLog, Boolean includeNamespace, Byte[]& patches) in d:\code\Starcounter\Pnext\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 92
   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(Byte[] bs, WebSocket ws) in d:\code\Starcounter\Pnext\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 64
   at Starcounter.Internal.PuppetRestHandler.<>c.<RegisterJsonPatchHandlers>b__6_3(String s, WebSocket ws) in d:\code\Starcounter\Pnext\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 195
   at Starcounter.Internal.WsGroupInfo.DetermineAndRunHandler(WebSocket ws) in d:\code\Starcounter\Pnext\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 125
   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 managedHandlerId, UInt32 groupId, WebSocket ws) in d:\code\Starcounter\Pnext\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 288
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in d:\code\Starcounter\Pnext\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 791
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR14012
---> Starcounter.DbException: ScErrInvalidObjectAccess (SCERR4174): The operation failed because of an invalid object access.
Version: 2.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4174.
   at Starcounter.Internal.DbState.ReadInt64(UInt64 oid, UInt64 address, Int32 index) in d:\code\Starcounter\Pnext\Level1\src\Starcounter\Internal\DbState.cs:line 499
   at lambda_method(Closure , Json )
ErrorCode=4174
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4174
```

**Comment by chrhol** [comment]
I will push this change to develop as well.

**Comment by warpech** [comment]
Really nice, thanks!
