### ISSUE TITLE
SystemUser.SignInSystemUser(Username, Password) throwing object reference error

### ISSUE THREAD

**Issue by iliassays** [Starcounter/Starcounter#3778]
I am trying to use SystemUser.SignInSystemUser out of SignIn app. It is throwing me following error.  Please have a look.

```
System.NullReferenceException: Object reference not set to an instance of an object.
  at Simplified.Ring3.SystemUser.<>c__DisplayClass22_0.<AssureSystemUserSession>b__0() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-312\Simplified\Ring3\User\SystemUser.Static.cs:line 447
  at Starcounter.Db.Transact(Action action, UInt32 flags, Boolean forceSnapshot, Int32 maxRetries) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-312\Level1\src\Starcounter\Db.cs:line 369
  at Simplified.Ring3.SystemUser.AssureSystemUserSession(SystemUserTokenKey Token) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-312\Simplified\Ring3\User\SystemUser.Static.cs:line 459
  at Simplified.Ring3.SystemUser.<>c__DisplayClass8_0.<SignInSystemUser>b__0() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-312\Simplified\Ring3\User\SystemUser.Static.cs:line 216
  at Starcounter.Db.Transact(Action action, UInt32 flags, Boolean forceSnapshot, Int32 maxRetries) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-312\Level1\src\Starcounter\Db.cs:line 354
  at Simplified.Ring3.SystemUser.SignInSystemUser(String Username, String Password) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-312\Simplified\Ring3\User\SystemUser.Static.cs:line 221
  at AdFenix.Server.Handlers.CustomizedInterfaces.GeneralAPI.GeneralAPI.<>c.<Register>b__0_15(String Username, String Password, String RememberMe, Request r) in E:\development\adfenix\adfenix-backend\src\Server\Handlers\CustomizedInterfaces\GeneralAPI\GeneralAPI.cs:line 611
  at lambda_method(Closure , Request , IntPtr , IntPtr )
  at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-312\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
  at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-312\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
  at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-312\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 598
```

**Comment by miyconst** [comment]
@iliassays you can access the source code of the `Simplified` library here - [StarcounterPrefabs/Simplified](https://github.com/StarcounterPrefabs/Simplified).

The exception is pointing to this like:

```cs
userSession = Db.SQL<SystemUserSession>("SELECT o FROM Simplified.Ring5.SystemUserSession o WHERE o.SessionIdString=?", Session.Current.ToAsciiString()).First;
```

The most likely reason is that `Session.Current` is `null`, means you have not created `Starcounter.Session` in your app.

**Comment by miyconst** [comment]
@iliassays I am closing the issue since you have solved your problem. Feel free to reopen if there are still some questions left.
