### ISSUE TITLE
End of content reached unexpectedly

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3782]
I am seeing this exception for no visible reason:

```
Starcounter-DevelopNightlyBuilds-2.2.1.2865 (Aug 10, 2016 5:11:56 AM)
```

```
"System.FormatException: ScErrJsonUnexpectedEndOfContent (SCERR14005): End of content reached unexpectedly
Version: 2.2.1.2865.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR14005.
   at Starcounter.Advanced.XSON.JsonHelper.ThrowUnexpectedEndOfContentException() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-433\Level1\src\Starcounter.XSON\Serializer\Json\JsonHelper.cs:line 690
   at Starcounter.Advanced.XSON.JsonReader.SkipObjectOrArray(Byte startToken, Byte endToken) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-433\Level1\src\Starcounter.XSON\Serializer\Json\JsonReader.cs:line 131
   at Starcounter.XSON.JsonPatch.Apply(Json root, IntPtr patchArrayPtr, Int32 patchArraySize, Boolean strictPatchRejection) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-433\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 628
   at Starcounter.XSON.JsonPatch.Apply(Json root, Byte[] patchArray, Boolean strictPatchRejection) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-433\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 522
   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(Byte[] bs, WebSocket ws) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-433\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 57
   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 managedHandlerId, UInt32 groupId, WebSocket ws) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-433\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 289
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-433\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 784
HResult=-2146233033
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR14005
"
```

```
"System.Exception: Unknown WebSocket frame type: 0
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-433\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 714
HResult=-2146233088
"
```

```
"System.FormatException: ScErrJsonUnexpectedEndOfContent (SCERR14005): End of content reached unexpectedly
Version: 2.2.1.2865.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR14005.
   at Starcounter.Advanced.XSON.JsonHelper.ThrowUnexpectedEndOfContentException() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-433\Level1\src\Starcounter.XSON\Serializer\Json\JsonHelper.cs:line 690
   at Starcounter.Advanced.XSON.JsonReader.SkipObjectOrArray(Byte startToken, Byte endToken) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-433\Level1\src\Starcounter.XSON\Serializer\Json\JsonReader.cs:line 131
   at Starcounter.XSON.JsonPatch.Apply(Json root, IntPtr patchArrayPtr, Int32 patchArraySize, Boolean strictPatchRejection) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-433\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 628
   at Starcounter.XSON.JsonPatch.Apply(Json root, Byte[] patchArray, Boolean strictPatchRejection) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-433\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 522
   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(Byte[] bs, WebSocket ws) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-433\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 57
   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 managedHandlerId, UInt32 groupId, WebSocket ws) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-433\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 289
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-433\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 784
HResult=-2146233033
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR14005
"
```

cc @alemoi, @chrhol

**Comment by miyconst** [comment]
I don't know what debugging info I can provide, because it does not always file with the exception. Only fails when I manually debug app with `F10` on each line. If I don't debug it either goes well or server stops sending model changes to client side.

**Comment by miyconst** [comment]
After some more investigation with @chrhol we figured out that the reason for this exception is puppet reconnection.

- Server does not respond while the code execution is stopped for debugging.
- Puppet tries to reconnect sending multiple requests.
- The requests waits till debugging is finished.
- Puppet aborts the requests and sends new one.
- Once debugging is finished those aborted requests reach server, but with broken body.

**Comment by linkdata** [comment]
> Once debugging is finished those aborted requests reach server, but with broken body.

This sounds like a bug in the Websocket implementation. A WS frame should not be delivered to the application unless it's been fully received.
