### ISSUE TITLE
Starcounter.Cookie.ParseString crashes with "Invalid cookie part"

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#3804]
cc @alemoi 

Whenever `Starcounter.Cookie.ParseString` encounters a request with a cookie that it cannot parse, it crashes with an exception:

```
System.ArgumentException: Invalid cookie part: ooooops
   at Starcounter.Cookie.ParseString(String Value) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-440\Level1\src\Starcounter.Internal\Http\Cookie.cs:line 52
   at SignIn.MainHandlers.<>c.<GetSignInCookie>b__14_0(String x) in C:\www\SignIn\src\SignIn\Api\MainHandlers.cs:line 248
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SignIn.MainHandlers.GetSignInCookie() in C:\www\SignIn\src\SignIn\Api\MainHandlers.cs:line 248
   at SignIn.MainHandlers.<Register>b__2_0(Request req) in C:\www\SignIn\src\SignIn\Api\MainHandlers.cs:line 30
   at Starcounter.Handle.RunRequestFilters(Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-440\Level1\src\Starcounter.Internal\Handle.cs:line 490
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-440\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 755
HResult=-2147024809

More information about this error may be available in the server error log.
```

A behavior that I would expect is to skip unparseable cookies.

Steps to reproduce:

1. Load any Starcounter app in Google Chrome
2. Open Chrome Console and execute the following script to set a cookie with name and no value: `document.cookie = "ooooops"`
3. Refresh the page

You will see the exception:

![2016-08-23 21_19_06-products - microsoft visual studio](https://cloud.githubusercontent.com/assets/566463/17906484/d4b8582e-6977-11e6-8cec-118a7c5ea408.png)

**Comment by Mackiovello** [comment]
I hit this one again today cc @alemoi

**Comment by alemoi** [comment]
@miyconst sorry for pointing at you, but is it your Cookie class code?

**Comment by miyconst** [comment]
No, this is not "my" code, means I didn't write it. I took it from online sources. And from the cookie point of view it should throw an exception same as `int.Parse` should throw an exception if a string provided.

The host responsibility is to make sure that the exception is caught and properly resolved.

**Comment by alemoi** [comment]
> The host responsibility is to make sure that the exception is caught and properly resolved.

User code should do it in this case?

**Comment by miyconst** [comment]
>User code should do it in this case?

Yes. And in our case user code is Starcounter code.

**Comment by alemoi** [comment]
> Yes. And in our case user code is Starcounter code.

I thought that `Cookie` should ignore the wrong cookie and proceed with processing of other cookies. I don't know how its implemented underneath, but thought that if it would throw an exception, then proceeding with other cookies is not possible.

**Comment by miyconst** [comment]
I think we should treat such request as no cookies and send a header to clear cookies to browser. If that is possible.

**Comment by alemoi** [comment]
That would work, if I see any exception caught, I will return null. But again, after I push new blending stuff.
