### ISSUE TITLE
Starcounter 1.5.0.5, SC_E_SCHEMA_CODE_MISMATCH_ABORT 

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3813]
Hi!

I'm trouble shooting an error that occurs if we start a database from scratch without loading any dumps. So there can't very well be schema changes.

There is a plugin that creates a singleton instance of a system wide configuration class.
This class has 71 fields (not my design). Is there a limitation on fields?

**Would it be possible to get access to the .Net-layers of scdb 1.5? Since you've already made scdb2 .Net layer available on GitHub.**

Exception:
>ActivityID: 1194812249118605312
Category: 
DateTime: 2016-08-30 11:35:15
MachineName: HEADSUTV180
Source: Starcounter
Type: Critical
UserName: 
Message:
An unhandled exception was intercepted: Starcounter.TransactionAbortedException: SC_E_SCHEMA_CODE_MISMATCH_ABORT (0x80007): The transaction was aborted because pending writes didn't match the schema.
   at Sc.Server.Internal.DbState.InitInstantiated(Persistent obj, Persistent typeObj) in D:\Code\Legacy\OldStarcounter\src\Green\Mark4-1\Starcounter\Server.Internal\DbState.cs:line 122
   at Concepts.Ring1.Something..ctor(Persistent kind, Uninitialized protection) in d:\source\ScdbApps\Retail\+POS.Modules\+ServerCore\+SocietyObjects\Concepts\Ring1\Something.cs:line 626
   at Concepts.Ring8.Heads.SystemConfigurationSingleton..ctor(Persistent baseObj, Uninitialized dummy) in d:\source\ScdbApps\Retail\+POS.Modules\+ServerCore\Concepts\Ring8\Heads\Configuration\SystemConfigurationSingleton.cs:line 575
   at Concepts.Ring8.Heads.SystemConfigurationSingleton..ctor()
   at Sc.Generated.Concepts.Ring8.Heads.SystemConfigurationSingleton_Binding.NewDefaultCtorInst()
   at Sc.Server.Binding.SOKindTypeBinding.Instantiate(Persistent kind) in D:\Code\Legacy\OldStarcounter\src\Green\Mark4-1\Starcounter\Server.Binding\SOTypeBindings.cs:line 291
   at Concepts.Ring1.Something.Kind.New() in d:\source\ScdbApps\Retail\+POS.Modules\+ServerCore\+SocietyObjects\Concepts\Ring1\Something.cs:line 256
   at Concepts.Ring1.SingletonHelper.DoAssureSingleton(Type singletonKindType, Type interfaceType, Kind& singletonKind) in d:\source\ScdbApps\Retail\+POS.Modules\+ServerCore\+SocietyObjects\Concepts\Ring1\Instances\SingletonHelper.cs:line 74
   at Concepts.Ring1.SingletonHelper.AssureSingletons() in d:\source\ScdbApps\Retail\+POS.Modules\+ServerCore\+SocietyObjects\Concepts\Ring1\Instances\SingletonHelper.cs:line 56
   at Concepts.Ring1.SingletonStartupPlugin.Execute(HostContext hostContext, StartupLog startupLog) in d:\source\ScdbApps\Retail\+POS.Modules\+ServerCore\+SocietyObjects\Concepts\Ring1\StartupPlugin\SingletonStartupPlugin.cs:line 31
   at SocietyObjects.ApplicationStartup.ApplicationStartupManager.hostContext_HostStarted(Object sender, HostStartedEventArgs args) in d:\source\ScdbApps\Retail\+POS.Modules\+ServerCore\+SocietyObjects\ApplicationStartup\StartupManager\ApplicationStartupManager.cs:line 164
   at Starcounter.HostContext.OnHostStarted() in D:\Code\Legacy\OldStarcounter\src\Green\Mark4-1\Starcounter\HostContext.cs:line 253
   at Starcounter.Startup.DoExecute(StartupArgs args) in D:\Code\Legacy\OldStarcounter\src\Green\Mark4-1\Starcounter\_Startup.cs:line 259
   at Starcounter.Startup.Execute(StartupArgs args) in D:\Code\Legacy\OldStarcounter\src\Green\Mark4-1\Starcounter\_Startup.cs:line 44
   at Sc.Server.Internal.StartupCall.Execute() in C:\Users\eriohl\Projects\perforce\Starcounter\Dev\Green\Mark4-1\Sc.Server.Internal\StartupCall.cs:line 34
ErrorCode=524295

From the schema.pl file:
>
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','Name','String').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','Description','String').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','Quantity','Decimal').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','WhenActive','Int32').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','ObjectIDString','String').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','ObjectID','UInt64').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','IsNew','Boolean').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','FullClassName','String').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','ClassName','String').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','InstantiatedFrom','Concepts.Ring1.Something.Kind').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','SelectorString','String').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','IsActive','Boolean').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','WasActive','Boolean').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','WillBeActive','Boolean').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','MaxRowsProductSelection','Int32').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','MaxRowsSupplierOISelection','Int32').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','MaxNumberOfColumnsProductSelection','Int32').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','MaxNumberOfColumnsSupplierOISelection','Int32').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','SelectionExecutionTime','Int32').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','CustomerOfferPreferNetPrices','Boolean').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','CustomerOfferApprovalLimitRange','Int32').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','CustomerOfferApprovalLimitInterval','UInt64').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','CustomerOfferValidToRange','Int32').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','CustomerOfferValidToInterval','UInt64').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','CustomerOfferSeekerSelectionTemplate','Concepts.Ring8.Heads.Selection.Template.SelectionTemplate').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','SetDefaultDeliveryDate','Boolean').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','WantedDeliveryDateDaysAhead','Int32').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','MaxSearchingRowsPerPage','Int32').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','CustomerOrderSeekerSelectionTemplate','Concepts.Ring8.Heads.Selection.Template.SelectionTemplate').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','GlobalSeekerMaxRows','Int32').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','InvoiceStandardFee','Decimal').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','InvoiceDefaultCreditDays','Int32').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','InvoiceRoundOff','Decimal').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','BankDays','Int32').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','UseHeadsCreditLimit','Boolean').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','InvoiceReminderFee','Decimal').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','CustomerInvoiceSeekerSelectionTemplate','Concepts.Ring8.Heads.Selection.Template.SelectionTemplate').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','CustAgreementHideDiscountOnPrintout','Boolean').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','CustAgreementDefaultInclVAT','Boolean').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','CustAgreementDefaultConsiderMaxDiscount','Boolean').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','RepositoryFTPLoginUser','String').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','RepositoryFTPLoginPass','String').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','RepositoryFTPAddress','String').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','RepositoryWeight','Int32').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','RepositoryExternalAddress','String').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','RepositoryIsFtp','Boolean').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','AdSpaceIsActive','Boolean').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','AdSpaceSyncInterval','Int32').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','AdSpaceCleanupInterval','Int32').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','AdSpaceDefaultRotationInterval','Int32').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','AdSpacePrice','Decimal').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','AdSpaceDisplayTime','UInt32').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','AdSpaceOpeningHour','Int32').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','AdSpaceClosingHour','Int32').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','EmailServerFromAddress','String').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','EmailServerPassword','String').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','EmailServerPOP3ServerName','String').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','EmailServerUseSSL','Boolean').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','EmailServerPort','Int32').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','ManualSupplierIDs','Boolean').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','ProductImportBarcodes','Int32').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','ProductImportCategories','Int32').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','ProductImportExternalResources','Int32').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','ProductImportMaxDiscount','Int32').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','ProductImportPackages','Int32').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','ProductImportSearchWords','Int32').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','ProductImportSuppliers','Int32').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','BlockPasswordChange','Boolean').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','SendEmailNotifications','Boolean').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','EmailNotificationSubjectPrefix','String').
property('Concepts.Ring8.Heads.SystemConfigurationSingleton','IsReceiverApprove','Boolean').

**Comment by chrhol** [comment]
> Would it be possible to get access to the .Net-layers of scdb 1.5? Since you've already made scdb2 .Net layer available on GitHub.

@dan31
