### ISSUE TITLE
Exception: Exclusive access to the session could not be obtained

### ISSUE THREAD

**Issue by HRidge** [Starcounter/Starcounter#3842]
I'm inserting/creating huge amount of data inside a session that takes a few minutes to run.

This is the exception details:
```
System.Exception: ScErrUnhandledException (SCERR1069): An unhandled exception was detected.
Version: 2.2.1.3141.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR1069.
   at StarcounterInternal.Hosting.Processor.RunTaskNoScheduling(Action userAction, String appName) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-482\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 102
   at Starcounter.DbSession.GetAndExecuteQueuedTasks(Action`2 taskExecutionMethod) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-482\Level1\src\Starcounter\DbSession.cs:line 180
   at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-482\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 149
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-482\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 62
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR1069
---> System.Exception: ScErrAcquireSessionTimeout (SCERR5008): Exclusive access to the session could not be obtained. Id: EBCF795678DDE9F700000010
Version: 2.2.1.3141.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR5008.
   at Starcounter.Session.StartUsing() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-482\Level1\src\Starcounter.XSON\Sessions\Session.cs:line 523
   at Starcounter.Session.Use(SessionTask action, String sessionId) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-482\Level1\src\Starcounter.XSON\Sessions\Session.cs:line 728
   at Starcounter.Task.Run() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-482\Level1\src\Starcounter\DbSession.cs:line 100
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR5008```

**Comment by miyconst** [comment]
cc @linkdata, @eriohl, @alemoi, @per-samuelsson

**Comment by miyconst** [comment]
@HRidge thanks for reporting.

**Comment by chrhol** [comment]
While you are running someone else (a patch from the client for example) tries to get access to the same session. 
We only allow one at a time to access the view model, the timeout is 3 minutes I think. 

Would it be possible to do the long running updates outside of the session and switch back to it when it's really needed?

**Comment by dan31** [comment]
@miyconst have you managed to address it? (I do not recall we looked at this when running bigdata tests).

**Comment by miyconst** [comment]
@dan31 I have updated the big data generation, so not it takes much less time and not failing with this exception with fair number of generated data.

It is enough for now, and we should not spend more time on the project which just generates data. @HRidge what do you say?

**Comment by HRidge** [comment]
I'm happy with the fix @miyconst made, now a typical data generaton only takes a few seconds.

**Comment by miyconst** [comment]
Good. Then I close this issue.
