### ISSUE TITLE
Using Expression crashes the weaver

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Starcounter#3848]
```
Expression<Func<RolePersonGroup, Role>> expression = rpg => rpg.Role;
```
Mere adding a line like this to the code crashes the weaver on start with the following message in VS:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		An unhandled, unidentified (non-Starcounter) exception occurred in the weaver. (ScErrUnhandledWeaverException (SCERR6066))
```

And the following message in Log:

```
System.Exception:  ScErrUnhandledWeaverException (SCERR6066): An unhandled, unidentified (non-Starcounter) exception occurred in the weaver. Version: 2.2.1.3154. Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR6066. ---> System.NullReferenceException: Object reference not set to an instance of an object.    at ^R00FfLNj7vE0.^rk33N/hO(OpCodeNumber _0, MetadataDeclaration _1)    at PostSharp.Sdk.CodeModel.Instruction.Write(BaseInstructionWriter writer)    at PostSharp.Sdk.CodeModel.MethodBodyDeclaration.^uPrQJ6gs(InstructionBlock _0, IMethodBodyVisitor[] _1, InstructionAction _2, InstructionReader _3, InstructionBlockExceptionHandlingKind _4)    at PostSharp.Sdk.CodeModel.MethodBodyDeclaration.^uPrQJ6gs(InstructionBlock _0, IMethodBodyVisitor[] _1, InstructionAction _2, InstructionReader _3, InstructionBlockExceptionHandlingKind _4)    at ^zpGNRK5nUM9z.^e2BtLyuT(^Kh85h0nXrulm& _0, Int32& _1)    at ^zpGNRK5nUM9z.^SkiT(^ceSOybcTEumb _0)    at PostSharp.Sdk.Binary.ModuleWriter.WriteMethodBodies(^ceSOybcTEumb _0, UInt32 _1)    at ^Up6wxUIUnN6a.^VfvrABjR()    at ^Up6wxUIUnN6a.^SkiT()    at ^cyC/TYSlPGB/.^wvPm(^RtksFin57NJ8 _0, ^8gP93Xsl\+Imn _1)    at PostSharp.Sdk.Extensibility.Project.ExecutePhase(String phase)    at PostSharp.Hosting.PostSharpObject.ExecuteProjects()    at PostSharp.Hosting.PostSharpObject.ProcessAssemblies(ModuleLoadStrategy[] modules)    at Starcounter.Weaver.CodeWeaver.Execute() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-485\Level1\src\scweaver\CodeWeaver.cs:line 400    at Starcounter.Weaver.CodeWeaver.ExecuteCurrent(CodeWeaver weaver) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-485\Level1\src\scweaver\CodeWeaver.cs:line 234    at Starcounter.Weaver.Program.ExecuteWeaveCommand(String inputDirectory, String outputDirectory, String cacheDirectory, String fileName, ApplicationArguments arguments) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-485\Level1\src\scweaver\Program.cs:line 205    at Starcounter.Weaver.Program.ApplyOptionsAndExecuteGivenCommand(ApplicationArguments arguments) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-485\Level1\src\scweaver\Program.cs:line 156    at Starcounter.Weaver.Program.Main(String[] args) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-485\Level1\src\scweaver\Program.cs:line 36    --- End of inner exception stack trace ---
   at Starcounter.Server.WeaverService.LogAndRaiseExceptionFromFailingWeaver(ToolInvocationException e) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-485\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 198
   at Starcounter.Server.WeaverService.Weave(String givenAssembly, String runtimeDirectory, Boolean disableEditionLibraries) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-485\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 121
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.<>c__DisplayClass4_0.<Execute>b__2(CommandTask task) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-485\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 99
   at Starcounter.Server.Commands.CommandProcessor.<>c__DisplayClass68_0.<WithinTask>b__0(CommandTask t) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-485\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 484
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-485\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 510
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.Execute() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-485\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 108
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-485\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR6066
```
Both `RolePersonGroup` and `Role` are Database Classes.

1. I read somewhere that this is unsupported. Even so, is it really required to abort execution?
1. Even if so, the error messages should be clear about what happened

**Comment by per-samuelsson** [comment]
@joozek78 

I need a little more time to check what happens here, but I'm quite possitive we've had something similar reported before, and it showed that the old version of PostSharp we use for the weaver can't handle all the new .NET features of later runtimes / compilers.

**Comment by per-samuelsson** [comment]
> I need a little more time to check what happens here, but I'm quite possitive we've had something similar reported before, and it showed that the old version of PostSharp we use for the weaver can't handle all the new .NET features of later runtimes / compilers.

Could be this https://github.com/Starcounter/Starcounter/issues/3248#issuecomment-171950174 and related investigation I was thinking about.

Not sure what to do up front, but we certainly need to have a discussion on what we can do here, and what we can't, and prioritize what to go after, considering 2.x-limitation on old PostSharp. I need help from @dan31 for this.

**Comment by per-samuelsson** [comment]
Here's the relevant PostSharp exception:

> System.NullReferenceException: Object reference not set to an instance of an object.    at ^R00FfLNj7vE0.^rk33N/hO(OpCodeNumber _0, MetadataDeclaration _1)    at PostSharp.Sdk.CodeModel.Instruction.Write(BaseInstructionWriter writer)    at PostSharp.Sdk.CodeModel.MethodBodyDeclaration.^uPrQJ6gs(InstructionBlock _0, IMethodBodyVisitor[] _1, InstructionAction _2, InstructionReader _3, InstructionBlockExceptionHandlingKind _4)    at PostSharp.Sdk.CodeModel.MethodBodyDeclaration.^uPrQJ6gs(InstructionBlock _0, IMethodBodyVisitor[] _1, InstructionAction _2, InstructionReader _3, InstructionBlockExceptionHandlingKind _4)    at ^zpGNRK5nUM9z.^e2BtLyuT(^Kh85h0nXrulm& _0, Int32& _1)    at ^zpGNRK5nUM9z.^SkiT(^ceSOybcTEumb _0)    at PostSharp.Sdk.Binary.ModuleWriter.WriteMethodBodies(^ceSOybcTEumb _0, UInt32 _1)    at ^Up6wxUIUnN6a.^VfvrABjR()    at ^Up6wxUIUnN6a.^SkiT()    at ^cyC/TYSlPGB/.^wvPm(^RtksFin57NJ8 _0, ^8gP93Xsl\+Imn _1)    at PostSharp.Sdk.Extensibility.Project.ExecutePhase(String phase)    at PostSharp.Hosting.PostSharpObject.ExecuteProjects()    at PostSharp.Hosting.PostSharpObject.ProcessAssemblies(ModuleLoadStrategy[] modules)

**Comment by per-samuelsson** [comment]
> I read somewhere that this is unsupported. Even so, is it really required to abort execution?

Well, it's not optimal. But what options do we have? I think it's comparable to a compile-time error. It's a syntax 2.x does not support. Kind of like if you try to use `nameof` with the C# 2.0 compiler.

> Even if so, the error messages should be clear about what happened.

In essence, I really agree. However, since the error we get back from PostSharp is a non-informative `NullReferenceException`, it's kind of hard to make this happen. The situation is less from ideal. Do you have any suggestions?

One way we could "solve" this I guess., is to force Starcounter applications not to target the newer CLRs / frameworks. It's quite limiting for our users though, and I'm also not sure either how to enforce it nor exactly what new constructs it is we can't support. :cry:

**Comment by per-samuelsson** [comment]
> One way we could "solve" this I guess., is to force Starcounter applications not to target the newer CLRs / frameworks. It's quite limiting for our users though, and I'm also not sure either how to enforce it nor exactly what new constructs it is we can't support.

Another, non-technical way, given all above parameters to consider: we create a dedicated FAQ / Support page and point to that for all uncategorized weaver errors similar to this (i.e. those we can not really handle).

So, when you get the exception, it look like this:

```
System.Exception:  ScErrUnhandledWeaverException (SCERR6066): An unhandled, unidentified (non-Starcounter) exception occurred in the weaver. Version: 2.2.1.3154. We have dedicated help for this - please visit https://github.com/Starcounter/Starcounter/wiki/KnownWeaverProblems
```

And on that page, we list symptoms and what could be done to get pass them.

**Comment by joozek78** [comment]
That's a good idea. That would at least mitigate the feeling of being lost
and helpless :)

**Comment by per-samuelsson** [comment]
> That's a good idea. That would at least mitigate the feeling of being lost and helpless :)

Cool. Considering it more, I actually think is the best choice here, given

1. We have no real idea how to handle the underlying problem.
2. We are stuck with an old version of PostSharp in 2.x
3. The new Starcounter.Core version is an increasing priority, and this problem will not occur there.

@joozek78 

If I volonteer to write that page and sharpen the error message, could you provide me with an **isolated** code-snippet (as short as possible) that trigger the error to occur? By isolated, I mean

1. Create a `Starcounter Application`
2. Add no additionl references
3. Add some database class(es) if you have to
4. Write a single `Main` that trigger it.

If you want to try the weaver in isolation, it's simple:

1. Compile your application
2. Open a prompt
3. Run `scweaver path\to\your\app.exe`.

**Comment by per-samuelsson** [comment]
> If I volonteer to write that page and sharpen the error message, could you provide me with an **isolated** code-snippet (as short as possible) that trigger the error to occur?

I tried myself now, but the most trivial thing pass weaving:

```cs
using System;
using System.Linq.Expressions;
using Starcounter;

namespace Issue3848
{
    [Database] public class Foo
    {
        public Bar NewBar()
        {
            return new Bar();
        }
    }

    [Database]
    public class Bar {}

    class Program
    {
        static void Main()
        {
            var f = new Foo();
            Expression<Func<Foo, Bar>> e = x => f.NewBar();
        }
    }
}
```
