### ISSUE TITLE
Setting Array.Data = null throws exception

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3856]
I remember some time ago this worked fine and removed all the array items. Currently it throws an exception.

```cs
json.Array.Data = null;
```

```
"System.NullReferenceException: Object reference not set to an instance of an object.
   at Starcounter.Json.Array_InitializeAfterImplicitConversion(Json parent, TObjArr template) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Starcounter.XSON\Class Json\Json.Array.cs:line 81
   at Starcounter.Internal.TransactionManager.Scope[T1,T2](TransactionHandle handle, Action`2 action, T1 arg1, T2 arg2) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Starcounter\TransactionManager.cs:line 476
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2](Json json, Action`2 action, T1 arg1, T2 arg2) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 114
   at Starcounter.Json.set_Data(Object value) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 38
   at Playground.MatrixPage.Handle(RemoveClick Action) in C:\GitHub\Miyconst\Playground\Playground\MatrixPage.json.cs:line 55
   at Playground.MatrixPage.JsonByExample.Schema.<>c.<.ctor>b__0_20(Json pup, Input`1 input) in C:\GitHub\Miyconst\Playground\Playground\obj\x64\Debug\MatrixPage-2.json.g.cs:line 0
   at Starcounter.Templates.Property`1.InvokeHandler(Json parent, Input`1 input) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 262
   at Starcounter.Templates.Property`1.ProcessInput(Json parent, T value) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 284
   at Starcounter.XSON.DefaultPatchHandler.ParseAndProcess(TLong property, Json parent, IntPtr valuePtr, Int32 valueSize) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 118
   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Starcounter\TransactionManager.cs:line 454
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 64
   at Starcounter.XSON.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, IntPtr valuePtr, Int32 valueSize) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 37
   at Starcounter.XSON.JsonPatch.Apply(Json root, IntPtr patchArrayPtr, Int32 patchArraySize, Boolean strictPatchRejection) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 687
   at Starcounter.XSON.JsonPatch.Apply(Json root, Byte[] patchArray, Boolean strictPatchRejection) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 527
   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(Byte[] bs, WebSocket ws) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 57
   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 managedHandlerId, UInt32 groupId, WebSocket ws) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 288
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 784
HResult=-2147467261
"
```

You can see an example in my Playground solution by clicking the `Remove all` button in the matrix section.

**Comment by chrhol** [comment]
Reproduced. Quite easy fix, and pretty bad to miss in the first place :blush:

Fix pushed to develop and soon pnext

**Comment by chrhol** [comment]
I will close this issue, please reopen it @miyconst if the problem still exists.

**Comment by miyconst** [comment]
Thanks @chrhol for fixing, I will reopen the issue if I get the error ever again.
