### ISSUE TITLE
Calling OntologyMap in a mapper app sometimes crashes the previous app

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#3860]
I have 3 apps:

- HelloWorld
- Images
- HelloWorldMapper - defines `OntologyMap` for partials in HelloWorld and Images

Once every two-three occasions, when I restart **HelloWorldMapper** from Visual Studio, I get the following exception:

![2016-09-29 18_19_21-helloworld debugging - microsoft visual studio](https://cloud.githubusercontent.com/assets/566463/18962861/c4fb89ac-8672-11e6-8882-81144b5aca07.png)

```txt
System.NullReferenceException was unhandled by user code
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=Starcounter
  StackTrace:
       at Starcounter.UriMapping.OntologyMap(String appUriToMap, String mappedClassInfo, Func`2 converterToClass, Func`2 converterFromClass) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter\Apps\OntologyAndOrdinaryMapping.cs:line 535
       at HelloWorldMapper.Program.Main() in C:\www\HelloWorld\src\HelloWorldMapper\Program.cs:line 10
  InnerException: 
```

At this point **HelloWorld** crashes. Images and HelloWorldMapper keep running:

![2016-09-29 18_23_45-helloworld debugging - microsoft visual studio](https://cloud.githubusercontent.com/assets/566463/18962722/449a172e-8672-11e6-9bf1-330f8e93e3e9.png)

Fix for this is important, because currently it is very hard to write mapper apps.

Starcounter version 2.2.1.3234

cc @alemoi

**Comment by alemoi** [comment]
Hi @warpech Thanks for reporting! I will check tomorrow. I guess `HelloWorldMapper` just consists of this one Program.cs file, is it?

**Comment by warpech** [comment]
Yes. I will push it later to GH

**Comment by warpech** [comment]
Code is here:

- https://github.com/StarcounterSamples/HelloWorld/tree/images-integration-new-refactor2
- https://github.com/StarcounterSamples/Images/tree/images-integration-new-refactor2

**Comment by alemoi** [comment]
Sorry for delaying this. I wanted to address this issue as a part of big refactoring regarding mapping, and, in particular, ontology mapping.
