### ISSUE TITLE
Critical error on app/database start

### ISSUE THREAD

**Issue by ivarbergman** [Starcounter/Starcounter#3894]
Hi! After our latest SC update (Starcounter-DevelopNightlyBuilds-2.2.2.3449) we have had problems with one of our production servers. The log stack trace contains the following:

```
20161019T061200 Error sc://tunitycustomer2/personal/service Starcounter - ScErrNetworkGatewayTerminated (SCERR10021): The server detected that the network gateway executable (scnetworkgateway.exe) unexpectedly terminated.
20161019T061201 Error sc://tunitycustomer2/personal/service Starcounter - Process exitcode: 1070
20161019T061201 Critical sc://tunitycustomer2/personal/heads Starcounter - System.Exception: ScErrUnspecified (SCERR999): An unspecified error caused the operation to fail. System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at Starcounter.NodeTask.PerformSyncRequest() in C:\TeamCity\BuildAgent\work\sc-develop-nightly-531\Level1\src\Starcounter.Internal\Rest\NodeTask.cs:line 515
Version: 2.2.2.3449.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR999.
   at Starcounter.Internal.AppsBootstrapper.RegisterNewCodehostInGateway() in C:\TeamCity\BuildAgent\work\sc-develop-nightly-531\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 61
   at Starcounter.Internal.AppsBootstrapper.InitAppsBootstrapper(Byte numSchedulers, UInt16 defaultUserHttpPort, UInt16 defaultSystemHttpPort, UInt32 sessionTimeoutMinutes, String dbName, Boolean noNetworkGateway) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-531\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 130
   at StarcounterInternal.Bootstrap.Control.Setup(String[] args) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-531\Level1\src\Starcounter.Bootstrap\Control.cs:line 223
   at StarcounterInternal.Bootstrap.Control.Main(String[] args) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-531\Level1\src\Starcounter.Bootstrap\Control.cs:line 55
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR999
```

I'm not really able to recreate the problem, but it has happened twice when I try to start a new database/app on the server that has been running for some time.

Can you make any suggestions on how to proceed from the info in the stack trace, or do you need more details?

**Comment by per-samuelsson** [comment]
> Can you make any suggestions on how to proceed from the info in the stack trace, or do you need more details?

Let's give @alemoi a chance to answer that.

Thanks for reporting this @ivarbergman.

**Comment by alemoi** [comment]
Thanks for reporting!

The strangest thing that confuses me is this process exit code 1070 (SCERRUNEXPECTEDINTERNALERROR) which gateway process should never return. @ivarbergman so you are should that there are no other log entries before that?

**Comment by dan31** [comment]
@alemoi isn't it the version right after you moved to new ```llvm``` on files?

**Comment by alemoi** [comment]
> @alemoi isn't it the version right after you moved to new llvm on files?

Yes, it has a new schema. But there is no indication that its related to scllvm, so far.

**Comment by ivarbergman** [comment]
Hi! No other immediate log entries before the ones I posted. But I will
make other try on the server this weekend and see I can find anything that
reproduces the error.

**Comment by dan31** [comment]
Hi @ivarbergman! Have you experienced anything similar during last 3 weeks?

**Comment by dan31** [comment]
Archived.
