### ISSUE TITLE
Invalid error message: The error near or at position -1.

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3897]
@k-rus is it any how possible to fix this error message, so it will say the actual reason of the failure?

**Comment by k-rus** [comment]
What do you mean by invalid error message? The error message was valid in OP. It is just position number, which is confusing. Can you clarify your issue and post the actual error here?

**Comment by k-rus** [comment]
I see what yo mean, but it is very difficult to understand. Can you post the stack trace and emphasise the problem place? I agree that the error message is incorrect.

**Comment by miyconst** [comment]
I mean, it is not possible to have an error at position `-1`. And there is no error in the SQL syntax, it is error in somewhere else.

The error message should be informative or at least not misleading. 

For the stack trace, please see the linked issue.

**Comment by k-rus** [comment]
> For the stack trace, please see the linked issue.

The linked issue has 3 stack traces. It will be very difficult to understand what the issue is about if it is not self-contained.

**Comment by miyconst** [comment]
```
System.Exception: ScErrUnhandledException (SCERR1069): An unhandled exception was detected.
Version: 2.3.0.4331.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR1069.
   at StarcounterInternal.Hosting.Processor.RunTaskNoScheduling(Action userAction, String appName) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-293\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 121
   at Starcounter.DbSession.GetAndExecuteQueuedTasks(Action`2 taskExecutionMethod) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-293\Level1\src\Starcounter\DbSession.cs:line 180
   at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-293\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 168
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-293\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 81
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR1069
---> Starcounter.SqlException: ScErrConstraintViolationAbort (SCERR8001): A transaction was aborted because a constraint was violated.  The error near or at position -1.
In query: INSERT INTO "Starcounter"."Raw"."Palma"."Image"(__id,"FileHash","FilePath","FileSize","Name")VALUES(object 45063,NULL,'/uploads/vfst4j2g.qlj.jpg',333306,'temp.jpg'),(object 45067,NULL,'/uploads/0ozrirvm.mmv.gif',200288,'palma-d3-matrix.gif'),(object 45074,NULL,'/uploads/ymqqo5n4.v35.jpg',10422255,'20160905_113024.jpg')
Version: 2.3.0.4331.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR8001.
   at Starcounter.SqlProcessor.SqlProcessor.ExecuteQuerySqlProcessor(String query) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-293\Level1\src\Starcounter\SqlProcessor\SqlProcessor.cs:line 178
   at Starcounter.Reload.<>c__DisplayClass15_0.<Load>b__3() in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-293\Level1\src\Starcounter\Mock\Reload.cs:line 325
   at Starcounter.Reload.<>c__DisplayClass14_1`1.<DoParallelTransact>b__3() in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-293\Level1\src\Starcounter\Mock\Reload.cs:line 302
   at Starcounter.Db.Transact(Action action, UInt32 flags, TransactOptions opts) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-293\Level1\src\Starcounter\Db.cs:line 278
   at Starcounter.Internal.StarcounterEnvironment.RunWithinApplication(String desiredAppName, Action action) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-293\Level1\src\Starcounter.Internal\Mock\StarcounterEnvironment.cs:line 128
   at Starcounter.DbSession.<>c__DisplayClass6_0.<RunSync>b__0() in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-293\Level1\src\Starcounter\DbSession.cs:line 261
   at Starcounter.Task.Run() in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-293\Level1\src\Starcounter\DbSession.cs:line 100
ScErrorCode=8001
ErrorMessage= The error near or at position -1.
In query: INSERT INTO "Starcounter"."Raw"."Palma"."Image"(__id,"FileHash","FilePath","FileSize","Name")VALUES(object 45063,NULL,'/uploads/vfst4j2g.qlj.jpg',333306,'temp.jpg'),(object 45067,NULL,'/uploads/0ozrirvm.mmv.gif',200288,'palma-d3-matrix.gif'),(object 45074,NULL,'/uploads/ymqqo5n4.v35.jpg',10422255,'20160905_113024.jpg')
BeginPosition=-1
EndPosition=-1
Query=INSERT INTO "Starcounter"."Raw"."Palma"."Image"(__id,"FileHash","FilePath","FileSize","Name")VALUES(object 45063,NULL,'/uploads/vfst4j2g.qlj.jpg',333306,'temp.jpg'),(object 45067,NULL,'/uploads/0ozrirvm.mmv.gif',200288,'palma-d3-matrix.gif'),(object 45074,NULL,'/uploads/ymqqo5n4.v35.jpg',10422255,'20160905_113024.jpg')
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR8001
```

**Comment by k-rus** [comment]
I will emphasis that the main problem is:

> ErrorMessage= The error near or at position -1.

Also for such error type, reporting position in the query is unnecessary.

**Comment by miyconst** [comment]
Yes, this issue is to improve the error message, if that is possible without extreme effort.
