### ISSUE TITLE
pnext: Is it possible to refuse to start develop apps in pnext?

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3898]
Currently it is possible to try to start an app compiled for develop version in pnext and vise-versa. This ends up with weird and unpredictable exceptions.

Can we throw an exception in this case and refuse to load such apps? Something like when trying to run an `x64` executable on an `x86` system.

**Comment by per-samuelsson** [comment]
I actually had a similar concern quite some time ago, when we got more active on Starcounter.Core. That it would be nice with clearer boundaries between Bluestar and different workloads (2.2-based host, 2.3-based ("pnext") and Starcounter.Core). 

I raised an issue about it back then, and there might be some info there we want to pick up for this: https://github.com/Starcounter/Starcounter.Core/issues/38.

**Comment by per-samuelsson** [comment]
Also, 3-year kid #525 is also on a similar topic. 👴

**Comment by miyconst** [comment]
Yeah, I am definitely not the first one to rise it up, but this indicates how serious this issue is.

**Comment by bigwad** [comment]
For me, backward compatibility is a sign of maturity and respect to the user.

I'd suggest to keep API compatible for extended period of time (is it really impossible to keep 2.2 and 2.3 compatible on API level?). 
If it's inevitable to make a breaking change to the host interface, then use host-specific semantic versioning.
And finally, the host itself should check compatibility with the kernel. Again, based on semantic versioning.

**Comment by dan31** [comment]
@miyconst I would like to follow @bigwad point. @miyconst could you provide some particular samples of the weird behaviour? My firm belief is that those are really ```2.3``` glitches and should go away as ```2.3``` release matures.

**Comment by dan31** [comment]
@miyconst the problem for the version-based compatibility is more complex. Namely, on the incompatible changes __some__ things might stop working and __some__ things might work differently. However, is just such a potential a good reason to disallow running such apps entirely? Generally, to understand whether there are any problems running code compiled for the older version, the whole code and binary has to be analysed, which doesn't sound feasible. Only sometimes __any__ app compiled for version ```N-1``` will not work on version ```N```, but this case I believe is rarity, isn't it?

**Comment by miyconst** [comment]
@bigwad, @dan31, I thought it is not possible to maintain backwards compatibility between `develop` and `pnext`.

Answering your questions:

- I were never able to run an app compiled for `develop` under `pnext`. Maybe some small ones did run, but those are only samples, so I didn't even care.
- The errors are internal Starcounter errors about missing method, null reference, or wrong argument types.

Here is the stack trace of the last exception.

```
"System.MissingMethodException: Method not found: 'Void Starcounter.Db.Transact(System.Action, Int32)'.
   at Palma.Context.RunIt(ScenarioType scenario, Action code, Branch branch)
   at Palma.Context.InjectedContext(Action code) in D:\GitHub\MM\PalmaServer\Core\Model\System\Context.cs:line 383
   at Palma.Database.Init() in D:\GitHub\MM\PalmaServer\Core\Runtime\Startup\Database.cs:line 26
   at Test.Program.<>c.<Main>b__0_23(Int32 orgsCount, Int32 msCount, Int32 edits, Int32 seed) in D:\GitHub\MM\PalmaServer\Test\Program.cs:line 333
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-531\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-531\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-531\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 765
HResult=-2146233069
"
```

**Comment by miyconst** [comment]
>For me, backward compatibility is a sign of maturity and respect to the user.

+1, but if we don't yet have such level, it is better to tell, that it is not supposed to work, and the developers won't spend hours to debug, why it's not working.

**Comment by per-samuelsson** [comment]
> Here is the stack trace of the last exception:

> `"System.MissingMethodException: Method not found: 'Void Starcounter.Db.Transact(System.Action, Int32)'.

Yeah, I've hit that too. It's because some API change that has been done to `Db.Transact` and I guess because parameters from apps compiled for **develop** are not compatible with the ones you are expected to pass from a **pnext** host.

**Comment by miyconst** [comment]
That is why I say, it is much better to refuse to start such apps than fail with such error when trying to open the app.

**Comment by bigwad** [comment]
>parameters from apps compiled for develop are not compatible with the ones you are expected to pass from a pnext

This is the central and kind of political question. Technically it's possible to keep API compatible, but it costs additional efforts (though I think not much in this particular case) and API bloating. But on the positive side, a programmer is much more concerned with API cleanness if he knows he's going to support it virtually forever once he introduces it.

**Comment by per-samuelsson** [comment]
Technically, it would be quite simple to implement this constraint by means of the weaver. When we weave any application, we already tag it with a certain assembly-level attribute. We could enhance that attribute to include the version the app is weaved against.

And since we are in charge of loading / bootstrapping the application, we could easily read that attribute and compare it to the installed version, and refuse to start it if versions differ.

The unknowns in the mix is to

1. fetch the version from somewhere - is it available as a programmatic API already?
2. define compatible ranges. For example, an application compiled/weaved for 1.2.3 should be OK to run in 1.2.3.1 and possible even 1.2.4, but not 1.3. We don't have any enforcement of, or commitment to, semantic versioning today, hence we need to put some thinking into that if we decide to do this thing.

**Comment by miyconst** [comment]
Here is one of the exceptions I get when trying to use an app compiled for `develop` under `pnext`.

```
"System.TypeInitializationException: The type initializer for 'UserAdmin.EditPersonPage' threw an exception.
   at UserAdmin.EditPersonPage..ctor()
   at UserAdmin.SystemUsersHandlers.<>c.<Register>b__0_5(String uri, SystemUser personUser) in D:\GitHub\Samples\UserAdmin\src\UserAdmin\Api\SystemUsersHandlers.cs:line 85
   at Starcounter.Db.Scope[T1,T2,TResult](Func`3 func, T1 arg1, T2 arg2, Boolean isReadOnly) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-daily-windows-2428\Level1\src\Starcounter\Db.cs:line 567
   at UserAdmin.SystemUsersHandlers.<>c__DisplayClass0_0.<Register>b__4(String userid, Request request) in D:\GitHub\Samples\UserAdmin\src\UserAdmin\Api\SystemUsersHandlers.cs:line 84
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-daily-windows-2428\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-daily-windows-2428\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-daily-windows-2428\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 765
TypeName=UserAdmin.EditPersonPage
HResult=-2146233036
---> System.MissingMethodException: Method not found: 'Void Starcounter.Templates.Template.set_ClassName(System.String)'.
   at Smorgasbord.PropertyMetadata.PropertyMetadataPage.JsonByExample.Schema..ctor()
   at UserAdmin.SomebodyPage.JsonByExample.Schema..ctor()
   at UserAdmin.EditPersonPage.JsonByExample.Schema..ctor()
   at UserAdmin.EditPersonPage..cctor()
HResult=-2146233069
"
```

**Comment by miyconst** [comment]
The problem gets even more serious with shared libraries. There is no way to check for which version of Starcounter it was compiled without trying it.

Currently I have UserAdmin app crashing at some point, because the referenced `Smorgasbord` assembly was compiled under `develop`. Worth to note, that it crashes only when certain features are used, otherwise it works.

**Comment by aloscha** [comment]
Have the same situation as @miyconst, according that we should download the `Smorgasbord` from github and rebuild it using pnext.

**Comment by per-samuelsson** [comment]
I'm currently doing some investigation on this. My aim is to introduce something like it, but I think I'll do it in Develop/2.4 only. That way, we can make switch from 2.3 -> 2.4 less bumpy.

Reason I'm not planning to do this in 2.3

1. Majority of users are already on 2.3 now, or are just in the progress of making the 2.2 -> 2.3 switch.
2. I want to limit number of new features in 2.3 since it's already RC.

WDYT?

**Comment by per-samuelsson** [comment]
Having some problem implementing this in a satisfying way.

If it should be based on a version number emitted by the weaver, we must fail to load an assembly into the host if they are not semantically compatible. Problem is that for the case 2.3 -> 2.4, assemblies coming from 2.3 that have not be recompiled, will *neither be weaved*, because of our redesign in 2.4, [replacing build-time with build-time weaving](https://github.com/Starcounter/Starcounter/issues/3984).

I considered implementing a constraint in 2.4, forcing each application that bootstrap to actually be weaved, but that is not really optimal and I don't like to enforce such constraint. Also, it still wouldn't work with shared libraries - the library might not contain database code, and hence could (rightfully) be excluded from weaving.

The only approach I'm left with is to make this a load-time check in the host, but I must evaluate that some more. Basically, have the host to check if any assembly that load has a (direct) reference to Starcounter.dll, and if it does, it must match the version that is loaded in the host. Would be nice if I don't find drawbacks with that, since it has the least impact on our code (and actually feels most "right").

**Comment by per-samuelsson** [comment]
> The only approach I'm left with is to make this a load-time check in the host, but I must evaluate that some more. Basically, have the host to check if any assembly that load has a (direct) reference to Starcounter.dll, and if it does, it must match the version that is loaded in the host. Would be nice if I don't find drawbacks with that, since it has the least impact on our code (and actually feels most "right").

I just noticed that the assembly version is never automatically assigned to our assemblies, so `Starcounter.dll` will always have 2.0, no matter if you are running 2.2, 2.3 or 2.4, which makes above approach fail.

I guess we might as well change that though, so that we have same static version number approach, but where 2.3 and 2.4 get their respective major.minor specified.

**Comment by per-samuelsson** [comment]
> I guess we might as well change that though, so that we have same static version number approach, but where 2.3 and 2.4 get their respective major.minor specified.

That was pretty naive. Apps are already depending on 2.0.0.0 with that specific version, so it would break quite a lot. Need another strategy for this to work.
