### ISSUE TITLE
NOT LIKE is replaced with NOT STARTS WITH and fails

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3909]
I am trying to execute the following query:

```cs
string like = "%Person%";
string notLike = "Starcounter.%";
IEnumerable<string> tables = Db.SQL<string>("SELECT t.FullName FROM \"Starcounter\".\"Metadata\".\"Table\" t WHERE t.FullName NOT LIKE ? AND t.FullName LIKE ? ORDER BY t.FullName", notLike, like);
```

And it fails with the following exception:

```
"Starcounter.SqlException: ScErrSQLIncorrectSyntax (SCERR7021): Incorrect SQL syntax. Unexpected token. The error near or at position 80, near or at token: starts. Note that the token is a keyword.
In query:  select t.fullname from ""starcounter"".""metadata"".""table"" t where t.fullname not starts with ? and t.fullname like ? order by t.fullname
Version: 2.3.0.4443.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR7021.
   at Starcounter.Query.QueryPreparation.PrepareOrExecuteQuery[T](String query, Boolean slowSql, Object[] values) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-304\Level1\src\Starcounter\Query\QueryPreparation.cs:line 70
   at Starcounter.Query.Sql.SqlEnumCache.CacheOrExecuteEnumerator[T](String query, Boolean slowSQL, Object[] values) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-304\Level1\src\Starcounter\Query\SQL\_SqlEnumCache.cs:line 127
   at Starcounter.Query.Sql.SqlEnumCache.GetCachedEnumerator[T](String query, Boolean slowSQL, Object[] values) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-304\Level1\src\Starcounter\Query\SQL\_SqlEnumCache.cs:line 148
   at Starcounter.Query.Execution.LikeExecEnumerator.CreateLikeCombinations[T](String query, Boolean slowSql, Object[] values) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-304\Level1\src\Starcounter\Query\Execution\Enumerators\LikeExecEnumerator.cs:line 130
   at Starcounter.Query.QueryPreparation.PrepareOrExecuteQuery[T](String query, Boolean slowSql, Object[] values) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-304\Level1\src\Starcounter\Query\QueryPreparation.cs:line 87
   at Starcounter.Query.Sql.SqlEnumCache.CacheOrExecuteEnumerator[T](String query, Boolean slowSQL, Object[] values) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-304\Level1\src\Starcounter\Query\SQL\_SqlEnumCache.cs:line 127
   at Starcounter.Db.FullQueryProcess[T](String query, Boolean slowSQL, Object[] values) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-304\Level1\src\Starcounter\Mock\Db.cs:line 132
   at LogStreamer.AppConfigurationPage.AppConfigurationPageItems.Handle(Name Action) in C:\GitHub\Starcounter\LogStreamer\src\LogStreamer\ViewModels\AppConfigurationPage.json.cs:line 41
   at LogStreamer.AppConfigurationPage.AppConfigurationPageItems.JsonByExample.Schema.<>c.<.ctor>b__0_7(Json pup, Input`1 input) in C:\GitHub\Starcounter\LogStreamer\src\LogStreamer\obj\x64\Debug\ViewModels\AppConfigurationPage-3.json.g.cs:line 0
   at Starcounter.Templates.Property`1.InvokeHandler(Json parent, Input`1 input) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-304\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 262
   at Starcounter.Templates.Property`1.ProcessInput(Json parent, T value) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-304\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 284
   at Starcounter.XSON.DefaultPatchHandler.ParseAndProcess(TString property, Json parent, IntPtr valuePtr, Int32 valueSize) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-304\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 135
   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-304\Level1\src\Starcounter\TransactionManager.cs:line 467
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-304\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 68
   at Starcounter.XSON.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, IntPtr valuePtr, Int32 valueSize) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-304\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 37
   at Starcounter.XSON.JsonPatch.Apply(Json root, IntPtr patchArrayPtr, Int32 patchArraySize, Boolean strictPatchRejection) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-304\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 687
   at Starcounter.XSON.JsonPatch.Apply(Json root, Byte[] patchArray, Boolean strictPatchRejection) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-304\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 527
   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(Byte[] bs, WebSocket ws) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-304\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 61
   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 managedHandlerId, UInt32 groupId, WebSocket ws) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-304\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 289
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-304\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 784
ScErrorCode=7021
ErrorMessage=Unexpected token. The error near or at position 80, near or at token: starts. Note that the token is a keyword.
In query:  select t.fullname from ""starcounter"".""metadata"".""table"" t where t.fullname not starts with ? and t.fullname like ? order by t.fullname
Token=starts
BeginPosition=80
EndPosition=85
Query= select t.fullname from ""starcounter"".""metadata"".""table"" t where t.fullname not starts with ? and t.fullname like ? order by t.fullname
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR7021
"
```

cc @k-rus

**Comment by k-rus** [comment]
Thank you for reporting. Looks like a bug in the like replacement in the old query processor.

**Comment by k-rus** [comment]
Actually according [the documentation](http://starcounter.io/guides/sql/comparison-predicates/) `NOT LIKE` is not supported, thus never was tested.

**Comment by miyconst** [comment]
What is interesting is that it work in administrator window, not from `Db.SQL` though.

**Comment by k-rus** [comment]
> What is interesting is that it work in administrator window, not from Db.SQL though.

Thanks for the info. Interesting. I am trying to understand how `STARTS WITH` hack was implemented.

**Comment by andwah** [comment]
A side note, Administrator is using `Db.SlowSQL(...)`

**Comment by k-rus** [comment]
> A side note, Administrator is using Db.SlowSQL(...)

It works not because of this. It is because literal is used, not query parameters.

**Comment by miyconst** [comment]
@k-rus did you actually mean to close this issue in your commit or GitHub is trying to be too smart once again?

**Comment by k-rus** [comment]
I made quick fix to the problem. There is still a problem in other part, which we will investigate.



> @k-rus did you actually mean to close this issue in your commit or GitHub is trying to be too smart once again?

I closed the issue through commit, which fixed the problem.

**Comment by miyconst** [comment]
Thanks. I will test it as soon as new nightly (pnext) ready.

**Comment by k-rus** [comment]
> Thanks. I will test it as soon as new nightly (pnext) ready.

I fixed in develop and takes some time to merge it into pnext.

**Comment by k-rus** [comment]
> I fixed in develop and takes some time to merge it into pnext.

merged
