### ISSUE TITLE
Enable HTMLComposition API by default

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#3915]
The page http://starcounter.io/guides/web/import-html-compositions/ explains in brief how to import HTML compositions. Sadly, it requires to run Launcher or some other app that calls `Starcounter.HTMLComposition.Register();`.

It would be much better if the API availability would be controlled through the DB config file - ON by default.

cc @tomalec

**Comment by tomalec** [comment]
:+1:

**Comment by alemoi** [comment]
So, as I understand, `Starcounter.HTMLComposition.Register();` is totally independent from any app and if the DB config value `RegisterHTMLComposition` is `True` then it should be called upon the codehost start. Correct?

**Comment by tomalec** [comment]
Yes, at least it should be like this (few things requires a polish https://github.com/Starcounter/RebelsLounge/issues/47).

Starcounter delivers `<starcounter-include>` which should be enough to consume `HTMLComposition` on client side.

**Comment by alemoi** [comment]
I discovered that its not that easy to do this straight forward (calling an assembly with database classes during startup of codehost). So we are in tight negotiations with @per-samuelsson about this matter. And we might have a solution called "system apps" that would start for every codehost (if configured so), providing certain functionality, like HTML compositions registration or JSON patch handlers.

Actually there can be several "system apps" for several purposes, registering certain handlers, etc. We can start with one thick system app that would register all current "/sc/..." and "/__...." handlers, but in future it can be fine graded per system app.

There are tons of positive sides of it: empty codehost becomes very thin, apps are isolated, good for multi-process solution. If user decides not to run a system app for this codehost and wants a super simple app with one "/echo" REST handler, then he gets it, and no other handlers in there (which is also good for security). By that we can even more prove that our apps approach is working, no hakintosh :)

CC @warpech @dan31 @linkdata @per-samuelsson @chrhol

**Comment by warpech** [comment]
Can we have a straightforward solution for this in 2.3 and more elegant one in 2.4? This is strategically needed in 2.3.

**Comment by warpech** [comment]
Another idea is to create a middleware (maybe 2 middlewares) that enable HTMLComposition, including:

- enabling the REST API (OT in #3915)
- enabling LayoutInfo in the merged JSON tree (point 1 in https://github.com/Starcounter/RebelsLounge/issues/47#issue-187769469)

**Comment by linkdata** [comment]
Not sure if this is relevant or not, but please note that request routing will in the future be limited to HTTP verb and URI path, and possibly also hostname. Currently we also attempt to route on query parameters even though ordering of them is not guaranteed by HTTP.

So if a REST API requires performant request routing, please have this in mind.

**Comment by warpech** [comment]
I just discovered that running `Starcounter.HTMLComposition.Register();` in two apps results in an exception.

This is totally painful, because:

1. HTMLComposition API is not turned ON by default (see my request in the first post on this page)
2. two apps cannot attempt to turn it ON, because attempt to turn on the API will cause an exception if it's already.

```txt
Starcounter.DbException: ScErrFailingEntrypoint (SCERR4259): The user code entrypoint method 
raised an exception. ScErrHandlerAlreadyRegistered (SCERR13003): This handler has already 
been registered. POST /sc/partial/composition?key={?}&ver={?} on port 8080
Version: 2.2.2.3678.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR13003.
Version: 2.2.2.3678.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4259.
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application, Assembly assembly) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-561\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 600
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application, ApplicationDirectory applicationDir) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-561\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 275
   at Starcounter.Hosting.Package.Process() in C:\TeamCity\BuildAgent\work\sc-develop-nightly-561\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 138
   at Starcounter.Hosting.Package.Process(IntPtr hPackage) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-561\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 55
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-561\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 66
ErrorCode=4259
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4259
---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application, Assembly assembly) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-561\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 574
HResult=-2146232828
---> System.Exception: ScErrHandlerAlreadyRegistered (SCERR13003): This handler has already been registered. POST /sc/partial/composition?key={?}&ver={?} on port 8080
Version: 2.2.2.3678.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR13003.
   at Starcounter.Rest.UserHandlerInfo.TryAddProxyOrReplaceDelegate(Func`4 userDelegate, HandlerOptions ho) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-561\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 337
   at Starcounter.Rest.UriHandlersManager.RegisterUriHandler(UInt16 port, String methodSpaceUri, Byte[] nativeParamTypes, Type messageType, Func`4 wrappedDelegate, NetworkProtocolType protoType, HandlerOptions ho) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-561\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 569
   at Starcounter.Rest.UriManagedHandlersCodegen.RegisterDelegate(UInt16 port, String methodSpaceUri, MethodInfo userDelegateInfo, Expression delegExpr, NetworkProtocolType protoType, HandlerOptions ho) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-561\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 615
   at Starcounter.Rest.RestRegistrationProxy.RegisterHandler[T1,T2,T3](UInt16 port, String methodSpaceUri, Func`4 handler, HandlerOptions ho) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-561\Level1\src\Starcounter.Rest\RestInitialization.cs:line 87
   at Starcounter.Handle.POST[T1,T2,T3](String uriTemplate, Func`4 handler, HandlerOptions ho) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-561\Level1\src\Starcounter.Internal\Handle.cs:line 743
   at Starcounter.HTMLComposition.Register() in C:\TeamCity\BuildAgent\work\sc-develop-nightly-561\Level1\src\Starcounter.Extensions\HTMLComposition.cs:line 50
   at LauncherProvider.Program.Main() in C:\www\Launcher\src\LayoutProvider\Program.cs:line 13
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR13003
```
