### ISSUE TITLE
ScErrSchemaCodeMismatch (SCERR4177): Operation failed be because input does not match schema

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3916]
We had some (ChatBot) test project's data in Db and we started using that Db in live environment without cleaning it. The ChatBot db had lot of tables one of them is `ChatBot.Database.CustomerData.Maklarbokningen.OfficeArea`. 
The ChatBot app was not running for more than couple of months and our AdFenix project was running fine up till now. 
This error message is produced when the code tries to perform `Db.Sql<>`. but this does not happen all the time, only for some specific queries: 

```
Error : ScErrSchemaCodeMismatch (SCERR4177): Operation failed be because input does not match schema. CLR Class is not loaded for table ChatBot.Database.CustomerData.Maklarbokningen.OfficeArea
Version: 2.2.2.3511.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4177.

StackTrace :    at Starcounter.Binding.Bindings.CreateExceptionOnTypeDefNotFound(Int32 tableId) in C:\TeamCity\BuildAgent\work\sc-develop-daily-2309\Level1\src\Starcounter\Binding\Bindings.cs:line 460
   at Starcounter.Binding.Bindings.BuildTypeBindingFromTypeDef(Int32 tableId) in C:\TeamCity\BuildAgent\work\sc-develop-daily-2309\Level1\src\Starcounter\Binding\Bindings.cs:line 332
   at Starcounter.DbHelper.FromID(UInt64 oid) in C:\TeamCity\BuildAgent\work\sc-develop-daily-2309\Level1\src\Starcounter\Mock\DbHelper.cs:line 59
   at Starcounter.Query.Execution.ObjectIdentityLookup.EvaluateToObject() in C:\TeamCity\BuildAgent\work\sc-develop-daily-2309\Level1\src\Starcounter\Query\Execution\Enumerators\ObjectIdentityLookup.cs:line 174
   at Starcounter.Query.Execution.ObjectIdentityLookup.MoveNext() in C:\TeamCity\BuildAgent\work\sc-develop-daily-2309\Level1\src\Starcounter\Query\Execution\Enumerators\ObjectIdentityLookup.cs:line 118
   at Starcounter.QueryResultRows`1.get_First() in C:\TeamCity\BuildAgent\work\sc-develop-daily-2309\Level1\src\Starcounter\Query\SQL\SqlResultGeneric.cs:line 143
   at AdFenix.Database.Campaign.<>c__DisplayClass85_0.<CreateCampaignFromAPI>b__0() in C:\adfenix-backend\src\Database\Campaigns\AdFenix\Campaign.cs:line 1044
   at Starcounter.Db.Transact(Action action, UInt32 flags, Boolean forceSnapshot, Int32 maxRetries) in C:\TeamCity\BuildAgent\work\sc-develop-daily-2309\Level1\src\Starcounter\Db.cs:line 354
   at AdFenix.Database.Campaign.CreateCampaignFromAPI(NewCampaign campaign, PublicationOwner po, ClassifiedAd ad, String email, String sellerEmail, String sellerMessage, String objective, String productObId) in C:\adfenix-backend\src\Database\Campaigns\AdFenix\Campaign.cs:line 990
   at AdFenix.Server.Handlers.CustomizedInterfaces.GeneralAPI.GeneralAPI.<>c.<Register>b__0_10(String token, String domain, CampaignsCreate campaigns, Request r) in C:\adfenix-backend\src\Server\Handlers\CustomizedInterfaces\GeneralAPI\GeneralAPI.cs:line 453
```

Temporary solution : 
I ran the ChatBot app again, and code seems to be working fine for now.

**Comment by per-samuelsson** [comment]
@atifwaqar 

Thanks for reporting this.

I think it is related to the old and known issue that the database schema and loaded code need to be in sync for SQL to be fully operable. We have several known cases where this has been discussed already, and frankly, I'm not sure we still have a clear and precise answer on what can be done here (except asking you to load the code, which you already did as a workaround). This is of course not acceptable long-term and we are aware of that this really has to be fixed.

Some probably related issues: https://github.com/Starcounter/Starcounter/issues/2960, https://github.com/Starcounter/Starcounter/issues/2439, https://github.com/Starcounter/Starcounter/issues/3449, https://github.com/Starcounter/Starcounter/issues/3134

**Comment by dan31** [comment]
2.2. Archived.
