### ISSUE TITLE
Json use struct as Data

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3922]
I'm having problem binding a Json to a struct. Tried multiple alternatives.
Got a small failing example here:
https://github.com/careri/StarcounterIssues/tree/master/StructDataTest

**Comment by dan31** [comment]
CC @per-samuelsson @miyconst @chrhol

**Comment by miyconst** [comment]
Here is the exception stack trace:

```
"Starcounter.DbException: ScErrFailingEntrypoint (SCERR4259): The user code entrypoint method raised an exception. ScErrCreateDataBindingForJson (SCERR14006): Cannot create binding between typed json and dataobject. Unable to generate binding. Json property 'WrapperJson.StructData' (StructDataJson), binding 'StructData'.
Version: 2.2.1.3234.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR14006.
Version: 2.2.1.3234.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4259.
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application, Assembly assembly) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 600
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application, ApplicationDirectory applicationDir) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 275
   at Starcounter.Hosting.Package.Process() in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 138
   at Starcounter.Hosting.Package.Process(IntPtr hPackage) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 55
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 66
ErrorCode=4259
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4259
---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application, Assembly assembly) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 574
HResult=-2146232828
---> System.Exception: ScErrCreateDataBindingForJson (SCERR14006): Cannot create binding between typed json and dataobject. Unable to generate binding. Json property 'WrapperJson.StructData' (StructDataJson), binding 'StructData'.
Version: 2.2.1.3234.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR14006.
   at Starcounter.XSON.TemplateDelegateGenerator.GenerateBoundDelegates(TObject property, Json json) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.XSON\TemplateDelegateGenerator.cs:line 280
   at Starcounter.Templates.TObject.GenerateBoundGetterAndSetter(Json parent) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.XSON\Templates\TObject.cs:line 75
   at Starcounter.Templates.TValue.UseBinding(Json parent) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.XSON\Templates\Foundation\TValue.cs:line 237
   at Starcounter.Templates.TObject.BoundOrUnboundGet(Json parent) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.XSON\Templates\TObject.cs:line 161
   at Starcounter.Advanced.XSON.StandardJsonSerializerBase.ScopeAndEstimateObject(TypedJsonSerializer serializer, Json json, Template template, JsonSerializerSettings settings) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializerBase.cs:line 227
   at Starcounter.Advanced.XSON.StandardJsonSerializerBase.EstimateObject(TypedJsonSerializer serializer, Json json, JsonSerializerSettings settings) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializerBase.cs:line 266
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3,TResult](Json json, Func`4 func, T1 arg1, T2 arg2, T3 arg3) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 237
   at Starcounter.Advanced.XSON.StandardJsonSerializerBase.ScopeAndEstimateObject(TypedJsonSerializer serializer, Json json, Template template, JsonSerializerSettings settings) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializerBase.cs:line 237
   at Starcounter.Advanced.XSON.StandardJsonSerializerBase.<>c__DisplayClass5_0.<EstimateSizeBytes>b__0(TypedJsonSerializer tjs, Json j, JsonSerializerSettings s) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializerBase.cs:line 64
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3,TResult](Json json, Func`4 func, T1 arg1, T2 arg2, T3 arg3) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 237
   at Starcounter.Advanced.XSON.StandardJsonSerializerBase.EstimateSizeBytes(Json json, JsonSerializerSettings settings) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.XSON\Serializer\Json\StandardJsonSerializerBase.cs:line 50
   at Starcounter.Json.ToJson(JsonSerializerSettings settings) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.XSON\Class Json\Json.Serializing.cs:line 46
   at StructDataTest.Program.Main() in C:\Temp\StarcounterIssues-master\StructDataTest\Program.cs:line 33
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR14006
---> System.ArgumentException: Expression of type 'StructDataTest.MyStruct' cannot be used for return type 'System.Object'
   at System.Linq.Expressions.Expression.ValidateLambdaArgs(Type delegateType, Expression& body, ReadOnlyCollection`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, String name, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, Boolean tailCall, IEnumerable`1 parameters)
   at Starcounter.XSON.TemplateDelegateGenerator.GenerateBoundGetExpression[T](BindingInfo bInfo, Template origin) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.XSON\TemplateDelegateGenerator.cs:line 407
   at Starcounter.XSON.TemplateDelegateGenerator.GenerateBoundDelegates(TObject property, Json json) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.XSON\TemplateDelegateGenerator.cs:line 253
HResult=-2147024809
"
```

**Comment by miyconst** [comment]
And it crashes entire database.

**Comment by miyconst** [comment]
Seems to be a Typed JSON issue. Replacing `struct` with a `class` works as expected. This issue will wait for @chrhol, he is on vacation currently.
