### ISSUE TITLE
pnext: unable to add another database class

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3923]
I have an app with a class:

```cs
[Database]
public class Child
{
    public Parent Belongs { get; set; }
    public string Name { get; set; }
    public int Number { get; set; }
}
```

The app was started, and there are some values in the database. After adding another class I get an error.

```cs
[Database]
public class ChildB : Child
{
    public string B { get; set; }
}
```

```
Unexpected error during mapping different meta-data, which represent database classes and properties. Column 'B' in table 'Playground.ChildB' cannot be found in ColumnDefs. 
```

I can understand that I can't change parent of an existing class, but adding a new class should be possible.

cc @k-rus

**Comment by miyconst** [comment]
This exception, by the way crashes database.

**Comment by miyconst** [comment]
Log entries:

```
"ScErrServerCommandFailed (SCERR10011): The operation ""Attempting to restart code host for playground"" failed.
Version: 2.3.0.4584.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10011."
```

```
"System.Exception: ScErrDatabaseAlreadyExists (SCERR2047): A database with the specified name already exists. Can't register new codehost ""playground. Version: 2.3.0.4584. Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR2047. 
   at Starcounter.Server.DatabaseEngine.WaitUntilCodeHostOnline(Process codeHostProcess, Database database) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-314\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseEngine.cs:line 332
   at Starcounter.Server.DatabaseEngine.RestartCodeHost(ICommandProcessor processor, Int32 terminatingCodeHostProcessId, DatabaseInfo databaseInfo) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-314\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseEngine.cs:line 461
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-314\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR2047
"
```

```
"System.Exception: ScErrDatabaseAlreadyExists (SCERR2047): A database with the specified name already exists. Can't register new codehost ""playground.
Version: 2.3.0.4584.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR2047.
   at Starcounter.Internal.AppsBootstrapper.RegisterNewCodehostInGateway() in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-314\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 60
   at Starcounter.Internal.AppsBootstrapper.InitAppsBootstrapper(Byte numSchedulers, UInt16 defaultUserHttpPort, UInt16 defaultSystemHttpPort, UInt32 sessionTimeoutMinutes, String dbName, Boolean noNetworkGateway) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-314\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 134
   at StarcounterInternal.Bootstrap.Control.Setup(String[] args) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-314\Level1\src\Starcounter.Bootstrap\Control.cs:line 216
   at StarcounterInternal.Bootstrap.Control.Main(String[] args) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-314\Level1\src\Starcounter.Bootstrap\Control.cs:line 55
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR2047
"
```

**Comment by dan31** [comment]
CC @per-samuelsson

**Comment by per-samuelsson** [comment]
> CC @per-samuelsson

OK. I have started switching out my current work in favor of getting started documenting refactoring functionality, so I might as well assign this one to me to get answered.

Meanwhile, I think we need to consider this a bug.

**Comment by dan31** [comment]
Is that still 2.3 issue?

**Comment by per-samuelsson** [comment]
> Is that still 2.3 issue?

Doubt that, but maybe its best to set up for a test to make sure.
