### ISSUE TITLE
pnext: Removing a database class cause unload to fail (ScErrUnloadTableNoClass)

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3933]
Simply reproduced and deterministic. See reproducible steps below.

Version tested: `pnext / 2.3.0.4643`.

Can be worked around by adding `--allowPartial` flag to `staradmin unload`. Hence I don't know if we should treat this as a bug or not?

### How to reproduce
1. Create a new empty database.
2. Start an application with content listed as **app.cs (before)** below.
3. Stop the database.
4. Alter the content of the application to **app.cs (after)** (refactoring: removing a class).
5. Start the application.
6. Issue an unload (see error below):

**app.cs (before)**
```cs
using Starcounter;

namespace RemoveClass
{
    [Database]
    public class Foo { }

    [Database]
    public class Bar
    {
        public string Value { get; set; }
    }

    class Program
    {
        static void Main()
        {
            Db.Transact(() => { new Foo(); });
            Db.Transact(() => { new Bar() { Value = "Value" }; });
        }
    }
}
```

**app.cs (after)**
```cs
using Starcounter;

namespace RemoveClass
{
    [Database]
    public class Foo { }

    class Program
    {
        static void Main()
        {
            // Before and after
            Db.Transact(() => { new Foo(); });
        }
    }
}
```

**Error**
> [14:17:56, Critical, Starcounter (default)]
Starcounter.DbException: ScErrFailingEntrypoint (SCERR4259): The user code entrypoint method raised an exception. ScErrUnloadTableNoClass (SCERR4275): Unloading a table fails, since its class is not loaded. An application, where the class is declared, needs to be loaded before unload is called. Table RemoveClass.Foo cannot be unloaded.
Version: 2.3.0.4643.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4275.
Version: 2.3.0.4643.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4259.
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application, Assembly assembly) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-317\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 534
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application, ApplicationDirectory applicationDir) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-317\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 265
   at Starcounter.Hosting.Package.Process() in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-317\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 138
   at Starcounter.Hosting.Package.Process(IntPtr hPackage) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-317\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 55
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-317\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 85
ErrorCode=4259
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4259
---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application, Assembly assembly) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-317\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 521
HResult=-2146232828
---> Starcounter.DbException: ScErrUnloadTableNoClass (SCERR4275): Unloading a table fails, since its class is not loaded. An application, where the class is declared, needs to be loaded before unload is called. Table RemoveClass.Foo cannot be unloaded.
Version: 2.3.0.4643.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4275.
   at Starcounter.Reload.<GetTablesForUnload>d__3.MoveNext() in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-317\Level1\src\Starcounter\Mock\Reload.cs:line 86
   at Starcounter.Reload.Unload(String fileName, UInt64 shiftId, Boolean unloadAll) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-317\Level1\src\Starcounter\Mock\Reload.cs:line 239
   at UnloadDatabase.Program.Main(String[] args) in c:\Program Files\Starcounter\cli-apps\UnloadDatabase.cs:line 34
ErrorCode=4275
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4275

**Comment by k-rus** [comment]
Removing class is not distinguishable from not loading an app. So it is not a bug. It is an expected behaviour.

**Comment by per-samuelsson** [comment]
> Removing class is not distinguishable from not loading an app. So it is not a bug. It is an expected behaviour.

OK. I'm quite sure most our users would disagree this is not to be considered a bug, but let's close it as an expected behavior if you say so.
