### ISSUE TITLE
Json.ProcessInput throws when run in a vanilla process

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Starcounter#3935]
1. Use ProcessInput method of Json class inside a vanilla (i.e. non-starcounter) process
1. Behold the exception!
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Starcounter.Templates.Property`1.Checkpoint(Json parent) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-317\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 198
   at Starcounter.Authorization.Tests.PageSecurity.PageSecurityEnhanceClassTests.HandlerMarkedWithAttributeShouldAskForProperPermission_RequirePermission() in C:\TeamCity\BuildAgent\work\67175af33f914a5b\authorization\Authorization.Tests\PageSecurity\PageSecurityCheckClassTests.cs:line 94
```

[Teamcity build log](https://teamcity.starcounter.org/viewLog.html?buildId=13179&tab=buildResultsDiv&buildTypeId=Apps_StarcounterAuthorization_StarcounterAuthorizationMasterPnext#testNameId1672016435763413739)
[Repro code](https://github.com/Starcounter/authorization/blob/CA-95-page-security-tests/Authorization.Tests/PageSecurity/PageSecurityCheckClassTests.cs#L94)

**This currently hinders sweoffshore-centered development Starcounter.Authorization**

CC @chrhol

**Comment by Mnosek** [comment]
+1

**Comment by chrhol** [comment]
I will tske a look today.

**Comment by chrhol** [comment]
Pushed to develop, and hopefully soon to pnext.

**Comment by joozek78** [comment]
It works now. Thanks for your help, Christian!
