### ISSUE TITLE
pnext: One of more of the languages the database is configured for isn't supported by the current system

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3943]
@HRidge is trying to start the latest `pnext` which is `2.3.0.4735 (Nov 15, 2016 2:02:06 AM)` at the moment, and getting the following error.

```
ScErrServerCommandFailed (SCERR10011): The operation "Creating database Default" failed.
Version: 2.3.0.4735.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10011.

[11:13:57, Starcounter.Server.Commands (scadminserver)]
ScErrUnexpectedCommandException (SCERR10016): Creating database Default failed due to an unexpected problem.
Version: 2.3.0.4735.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10016.
 Starcounter.Server.ToolInvocationException: Error invoking ""C:\Program Files\Starcounter\sccreatedb.exe" -ip "C:\Users\HarriHarju\Documents\Starcounter\Personal\Data\Default\Default-20161115T111357104" -coll TurboText_en-GB_3.dll -oid 1 -lastoid 4611686018427387903 Default": exit code is 0x1. Tool output:

 Starcounter permanent storage creation utility.
Copyright (C) Starcounter AB 2007-2016. All rights reserved.

Error: ScErrDatabaseLangUnsupported (SCERR2023): One of more of the languages the database is configured for isn't supported by the current system.


   at Starcounter.Server.ToolInvocationHelper.InvokeTool(ProcessStartInfo processStartInfo, Boolean checkExitCode) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-327\Level1\src\Server\Starcounter.Server\ToolInvocationHelper.cs:line 167
   at Starcounter.Server.DatabaseStorageService.CreateStorage(String name, String imagePath, DatabaseStorageConfiguration configuration) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-327\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseStorageService.cs:line 163
   at Starcounter.Server.DatabaseSetup.CreateFiles() in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-327\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseSetup.cs:line 114
   at Starcounter.Server.DatabaseSetup.CreateDatabase() in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-327\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseSetup.cs:line 134
   at Starcounter.Server.Commands.CreateDatabaseCommandProcessor.Execute() in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-327\Level1\src\Server\Starcounter.Server\Commands\Processors\CreateDatabaseCommandProcessor.cs:line 33
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-327\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
ExitCode=1
HResult=-2146233088
```

What does this mean at all:

```
One of more of the languages the database is configured for isn't supported by the current system.
```

cc @alemoi, @bigwad, @per-samuelsson

**Comment by chrhol** [comment]
Is this the same problem as in #3343? Config files are not updated when installing a new version, so you have to make sure they are removed *before* installing.

**Comment by miyconst** [comment]
Yes, looks like a duplicate. Closing  this one.
