### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by andwah** [Starcounter/Starcounter#3952]
Im getting a couple of these errors from the Warehouse app

any idea what it can be?

```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.System.Collections.IList.get_Item(Int32 index)
   at Starcounter.XSON.JsonProperty.EvalutateCurrent(JsonPointer ptr, ViewModelVersion version, Boolean& nextIsIndex) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-570\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonProperty.cs:line 112
   at Starcounter.XSON.JsonProperty.<>c.<DoEvaluate>b__11_0(JsonProperty prop, JsonPointer ptr, ViewModelVersion pv, Boolean isIndex) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-570\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonProperty.cs:line 82
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3,T4,TResult](Json json, Func`5 func, T1 arg1, T2 arg2, T3 arg3, T4 arg4) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-570\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 265
   at Starcounter.XSON.JsonProperty.DoEvaluate(JsonPointer pointer, Json root) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-570\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonProperty.cs:line 79
   at Starcounter.XSON.JsonProperty.Evaluate(JsonPointer pointer, Json root) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-570\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonProperty.cs:line 59
   at Starcounter.XSON.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, IntPtr valuePtr, Int32 valueSize) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-570\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 18
   at Starcounter.XSON.JsonPatch.Apply(Json root, IntPtr patchArrayPtr, Int32 patchArraySize, Boolean strictPatchRejection) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-570\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 687
   at Starcounter.XSON.JsonPatch.Apply(Json root, Byte[] patchArray, Boolean strictPatchRejection) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-570\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 527
   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(Byte[] bs, WebSocket ws) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-570\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 61
   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 managedHandlerId, UInt32 groupId, WebSocket ws) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-570\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 289
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-570\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 796
ParamName=index
HResult=-2146233086
```

**Comment by miyconst** [comment]
It seems to be an old bug fixed by @chrhol. What version of Starcounter do you use?

**Comment by andwah** [comment]
Latest nightly.
2.2.2.3738

**Comment by miyconst** [comment]
Then @chrhol should take a look at it.

**Comment by chrhol** [comment]
I get the exception when creating a new organization and the notice in the top corner is closed. I'm not quite sure why it goes wrong, but the client seems to be sending a lot patches for the `Close` operation.

Not quite sure why the last patch sent from the client generates the error on the server instead of properly detecting that the row is removed (like the server does for the other patches).

This is taken from the debug-aid, after an organization is created (when the notice-popup disappears):
<img width="954" alt="patches" src="https://cloud.githubusercontent.com/assets/1658979/20403519/6adb3a48-ad01-11e6-8e05-16c37af08e60.PNG">

**Comment by chrhol** [comment]
Something is up with the closing of the notice popup. Sometimes (since you dont always get the argumentoutofrangeexception) it just keeps pushing patches for `Close` and the whole gui is responding slow. 

@andwah when you have time, could we take a look together?

**Comment by andwah** [comment]
i will also take a look at the notice component. ill be working from home

**Comment by andwah** [comment]
I think i found the reason. notices is auto close by a timer, when the timer hit it made a crazy loads of "closes" (talking thousands...) on the notice. not sure what was going on there. i refactored how the timer worked.  

@chrhol  Thanks for your first investigation that pointed out the "Notice" component.

**Comment by chrhol** [comment]
Going back to the original exception in this issue: in this case it was the client that misbehaved. When the exception is thrown, the client says that it's on the same version as the server which means that no transformation will take place and the patch contains a path to a row that has been removed.

I created another issue to enhance the exception and will consider this one resolved.
