### ISSUE TITLE
Weaver fails to proceed try catch when blocks

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3957]
I am trying to use the following construction:

```cs
try {
} catch (SocketException ex) when (ex.ErrorCode == 10058) {
}
```

And weaver fails with the following log entries:

```
"System.Exception:  ScErrUnhandledWeaverException (SCERR6066): An unhandled, unidentified (non-Starcounter) exception occurred in the weaver. Version: 2.3.0.4845. Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR6066. ---> PostSharp.Sdk.AssertionFailedException: Exception of type 'PostSharp.Sdk.AssertionFailedException' was thrown.    at ^4HxZxLvtf5Yj.^KopXnB2A(InstructionBlock _0, Int32 _1, Int32 _2)    at ^4HxZxLvtf5Yj.^6jyT8reb(InstructionBlock _0, Byte* _1, List`1 _2, Int32 _3, Int32 _4, InstructionBlock& _5)    at ^4HxZxLvtf5Yj.^Ole3r7qI(IDebugScope _0, InstructionBlock _1, Byte* _2, List`1 _3)    at ^4HxZxLvtf5Yj.^Ole3r7qI(IDebugScope _0, InstructionBlock _1, Byte* _2, List`1 _3)    at ^4HxZxLvtf5Yj.^Ole3r7qI(IDebugScope _0, InstructionBlock _1, Byte* _2, List`1 _3)    at ^4HxZxLvtf5Yj.^Ole3r7qI(IDebugScope _0, InstructionBlock _1, Byte* _2, List`1 _3)    at ^4HxZxLvtf5Yj.^pl+BddFU()    at PostSharp.Sdk.CodeModel.MethodDefDeclaration.get_MethodBody()    at Starcounter.Internal.Weaver.ScAnalysisTask.InspectLoadFieldAddress() in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Starcounter.Weaver\Starcounter.Internal.Weaver\ScAnalysisTask.cs:line 1534    at Starcounter.Internal.Weaver.ScAnalysisTask.Execute() in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Starcounter.Weaver\Starcounter.Internal.Weaver\ScAnalysisTask.cs:line 534    at PostSharp.Sdk.Extensibility.Project.ExecutePhase(String phase)    at PostSharp.Hosting.PostSharpObject.ExecuteProjects()    at PostSharp.Hosting.PostSharpObject.ProcessAssemblies(ModuleLoadStrategy[] modules)    at Starcounter.Weaver.CodeWeaver.Execute() in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Starcounter.Weaver\CodeWeaver.cs:line 321    at Starcounter.Weaver.CodeWeaver.ExecuteCurrent(CodeWeaver weaver) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Starcounter.Weaver\CodeWeaver.cs:line 153    at Starcounter.Weaver.Program.ExecuteWeaveCommand(WeaverHost host, String inputDirectory, String outputDirectory, String cacheDirectory, String fileName, ApplicationArguments arguments) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\scweaver\Program.cs:line 218    at Starcounter.Weaver.Program.ApplyOptionsAndExecuteGivenCommand(WeaverHost host, ApplicationArguments arguments) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\scweaver\Program.cs:line 166    at Starcounter.Weaver.Program.Main(String[] args) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\scweaver\Program.cs:line 47    --- End of inner exception stack trace ---
   at Starcounter.Server.WeaverService.LogAndRaiseExceptionFromFailingWeaver(ToolInvocationException e) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 198
   at Starcounter.Server.WeaverService.Weave(String givenAssembly, String runtimeDirectory, Boolean disableEditionLibraries) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 121
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.<>c__DisplayClass4_0.<Execute>b__2(CommandTask task) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 99
   at Starcounter.Server.Commands.CommandProcessor.<>c__DisplayClass68_0.<WithinTask>b__0(CommandTask t) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 484
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 510
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.Execute() in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 108
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR6066
"
```

```
 ScErrUnhandledWeaverException (SCERR6066): An unhandled, unidentified (non-Starcounter) exception occurred in the weaver. Version: 2.3.0.4845. Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR6066. ---> PostSharp.Sdk.AssertionFailedException: Exception of type 'PostSharp.Sdk.AssertionFailedException' was thrown.    at ^4HxZxLvtf5Yj.^KopXnB2A(InstructionBlock _0, Int32 _1, Int32 _2)    at ^4HxZxLvtf5Yj.^6jyT8reb(InstructionBlock _0, Byte* _1, List`1 _2, Int32 _3, Int32 _4, InstructionBlock& _5)    at ^4HxZxLvtf5Yj.^Ole3r7qI(IDebugScope _0, InstructionBlock _1, Byte* _2, List`1 _3)    at ^4HxZxLvtf5Yj.^Ole3r7qI(IDebugScope _0, InstructionBlock _1, Byte* _2, List`1 _3)    at ^4HxZxLvtf5Yj.^Ole3r7qI(IDebugScope _0, InstructionBlock _1, Byte* _2, List`1 _3)    at ^4HxZxLvtf5Yj.^Ole3r7qI(IDebugScope _0, InstructionBlock _1, Byte* _2, List`1 _3)    at ^4HxZxLvtf5Yj.^pl+BddFU()    at PostSharp.Sdk.CodeModel.MethodDefDeclaration.get_MethodBody()    at Starcounter.Internal.Weaver.ScAnalysisTask.InspectLoadFieldAddress() in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Starcounter.Weaver\Starcounter.Internal.Weaver\ScAnalysisTask.cs:line 1534    at Starcounter.Internal.Weaver.ScAnalysisTask.Execute() in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Starcounter.Weaver\Starcounter.Internal.Weaver\ScAnalysisTask.cs:line 534    at PostSharp.Sdk.Extensibility.Project.ExecutePhase(String phase)    at PostSharp.Hosting.PostSharpObject.ExecuteProjects()    at PostSharp.Hosting.PostSharpObject.ProcessAssemblies(ModuleLoadStrategy[] modules)    at Starcounter.Weaver.CodeWeaver.Execute() in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Starcounter.Weaver\CodeWeaver.cs:line 321    at Starcounter.Weaver.CodeWeaver.ExecuteCurrent(CodeWeaver weaver) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Starcounter.Weaver\CodeWeaver.cs:line 153    at Starcounter.Weaver.Program.ExecuteWeaveCommand(WeaverHost host, String inputDirectory, String outputDirectory, String cacheDirectory, String fileName, ApplicationArguments arguments) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\scweaver\Program.cs:line 218    at Starcounter.Weaver.Program.ApplyOptionsAndExecuteGivenCommand(WeaverHost host, ApplicationArguments arguments) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\scweaver\Program.cs:line 166    at Starcounter.Weaver.Program.Main(String[] args) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\scweaver\Program.cs:line 47    --- End of inner exception stack trace ---
```

```
"ScErrWeavingError (SCERR2030): At least one error has been detected during weaving of the application code. Process exit code: 6066.
Arguments=--nocache --maxerrors=1 --ErrorParcelId=A4A7D6FA-EB34-442A-B579-DBB1DBB859E3 Weave ""C:\GitHub\Miyconst\SyncEngine\SyncEngine\src\SyncEngine.Configurator\bin\Debug\SyncEngineConfigurator.exe"" --outdir=""C:\Users\const\Documents\StarcounterPnext\Personal\Temp\parent\parent-20161025T174743610\weaver\B6221DF574B12CB9EEDA2C897284A0909E37DC2B""
Output:
A4A7D6FA-EB34-442A-B579-DBB1DBB859E3System.Exception: ScErrUnhandledWeaverException (SCERR6066): An unhandled, unidentified (non-Starcounter) exception occurred in the weaver.
Version: 2.3.0.4845.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR6066. ---> PostSharp.Sdk.AssertionFailedException: Exception of type 'PostSharp.Sdk.AssertionFailedException' was thrown.
   at ^4HxZxLvtf5Yj.^KopXnB2A(InstructionBlock _0, Int32 _1, Int32 _2)
   at ^4HxZxLvtf5Yj.^6jyT8reb(InstructionBlock _0, Byte* _1, List`1 _2, Int32 _3, Int32 _4, InstructionBlock& _5)
   at ^4HxZxLvtf5Yj.^Ole3r7qI(IDebugScope _0, InstructionBlock _1, Byte* _2, List`1 _3)
   at ^4HxZxLvtf5Yj.^Ole3r7qI(IDebugScope _0, InstructionBlock _1, Byte* _2, List`1 _3)
   at ^4HxZxLvtf5Yj.^Ole3r7qI(IDebugScope _0, InstructionBlock _1, Byte* _2, List`1 _3)
   at ^4HxZxLvtf5Yj.^Ole3r7qI(IDebugScope _0, InstructionBlock _1, Byte* _2, List`1 _3)
   at ^4HxZxLvtf5Yj.^pl+BddFU()
   at PostSharp.Sdk.CodeModel.MethodDefDeclaration.get_MethodBody()
   at Starcounter.Internal.Weaver.ScAnalysisTask.InspectLoadFieldAddress() in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Starcounter.Weaver\Starcounter.Internal.Weaver\ScAnalysisTask.cs:line 1534
   at Starcounter.Internal.Weaver.ScAnalysisTask.Execute() in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Starcounter.Weaver\Starcounter.Internal.Weaver\ScAnalysisTask.cs:line 534
   at PostSharp.Sdk.Extensibility.Project.ExecutePhase(String phase)
   at PostSharp.Hosting.PostSharpObject.ExecuteProjects()
   at PostSharp.Hosting.PostSharpObject.ProcessAssemblies(ModuleLoadStrategy[] modules)
   at Starcounter.Weaver.CodeWeaver.Execute() in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Starcounter.Weaver\CodeWeaver.cs:line 321
   at Starcounter.Weaver.CodeWeaver.ExecuteCurrent(CodeWeaver weaver) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Starcounter.Weaver\CodeWeaver.cs:line 153
   at Starcounter.Weaver.Program.ExecuteWeaveCommand(WeaverHost host, String inputDirectory, String outputDirectory, String cacheDirectory, String fileName, ApplicationArguments arguments) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\scweaver\Program.cs:line 218
   at Starcounter.Weaver.Program.ApplyOptionsAndExecuteGivenCommand(WeaverHost host, ApplicationArguments arguments) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\scweaver\Program.cs:line 166
   at Starcounter.Weaver.Program.Main(String[] args) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\scweaver\Program.cs:line 47
   --- End of inner exception stack trace ---A4A7D6FA-EB34-442A-B579-DBB1DBB859E3
System.Exception: ScErrUnhandledWeaverException (SCERR6066): An unhandled, unidentified (non-Starcounter) exception occurred in the weaver.
Version: 2.3.0.4845.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR6066. ---> PostSharp.Sdk.AssertionFailedException: Exception of type 'PostSharp.Sdk.AssertionFailedException' was thrown.
   at ^4HxZxLvtf5Yj.^KopXnB2A(InstructionBlock _0, Int32 _1, Int32 _2)
   at ^4HxZxLvtf5Yj.^6jyT8reb(InstructionBlock _0, Byte* _1, List`1 _2, Int32 _3, Int32 _4, InstructionBlock& _5)
   at ^4HxZxLvtf5Yj.^Ole3r7qI(IDebugScope _0, InstructionBlock _1, Byte* _2, List`1 _3)
   at ^4HxZxLvtf5Yj.^Ole3r7qI(IDebugScope _0, InstructionBlock _1, Byte* _2, List`1 _3)
   at ^4HxZxLvtf5Yj.^Ole3r7qI(IDebugScope _0, InstructionBlock _1, Byte* _2, List`1 _3)
   at ^4HxZxLvtf5Yj.^Ole3r7qI(IDebugScope _0, InstructionBlock _1, Byte* _2, List`1 _3)
   at ^4HxZxLvtf5Yj.^pl+BddFU()
   at PostSharp.Sdk.CodeModel.MethodDefDeclaration.get_MethodBody()
   at Starcounter.Internal.Weaver.ScAnalysisTask.InspectLoadFieldAddress() in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Starcounter.Weaver\Starcounter.Internal.Weaver\ScAnalysisTask.cs:line 1534
   at Starcounter.Internal.Weaver.ScAnalysisTask.Execute() in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Starcounter.Weaver\Starcounter.Internal.Weaver\ScAnalysisTask.cs:line 534
   at PostSharp.Sdk.Extensibility.Project.ExecutePhase(String phase)
   at PostSharp.Hosting.PostSharpObject.ExecuteProjects()
   at PostSharp.Hosting.PostSharpObject.ProcessAssemblies(ModuleLoadStrategy[] modules)
   at Starcounter.Weaver.CodeWeaver.Execute() in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Starcounter.Weaver\CodeWeaver.cs:line 321
   at Starcounter.Weaver.CodeWeaver.ExecuteCurrent(CodeWeaver weaver) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Starcounter.Weaver\CodeWeaver.cs:line 153
   at Starcounter.Weaver.Program.ExecuteWeaveCommand(WeaverHost host, String inputDirectory, String outputDirectory, String cacheDirectory, String fileName, ApplicationArguments arguments) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\scweaver\Program.cs:line 218
   at Starcounter.Weaver.Program.ApplyOptionsAndExecuteGivenCommand(WeaverHost host, ApplicationArguments arguments) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\scweaver\Program.cs:line 166
   at Starcounter.Weaver.Program.Main(String[] args) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\scweaver\Program.cs:line 47
   --- End of inner exception stack trace ---

Version: 2.3.0.4845.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR2030."
```

**Comment by miyconst** [comment]
cc @per-samuelsson

**Comment by per-samuelsson** [comment]
Ouch, that's bad. We already know of other cases with new C# constructs our old, outdated version of PostSharp seem not to deal well with: https://github.com/Starcounter/Starcounter/issues/3848

I think we need to bring this up to discussion real soon, and put more resources into porting the weaver sooner rather than later.

**Comment by per-samuelsson** [comment]
@miyconst 

I tried reproduce this in isolation, and I can't trigger the error. Can you try the same? Actually the stacktrace indicate there is some other code that mess up (probably relating to fields in a database class).

Can I ask you to

1. Create a new Starcounter Application on 2.3
2. Replace Program.cs with the code below and build it
3. Open a prompt and run `scweaver path\to\your\app.exe` and see what it gives?

**Program.cs**
```cs
using System;
using Starcounter;
using System.Net.Sockets;

namespace StarcounterApplication22
{
    [Database] public class Foo {}

    class Program
    {
        static void Main()
        {
            try
            {
                new Foo();
            }
            catch (SocketException ex) when (ex.ErrorCode == 10058)
            {
            }
        }
    }
}
```

**Comment by miyconst** [comment]
@per-samuelsson this is strange, but your code snippet works, here is another one, which does not.

```cs
using System;
using System.Net.Sockets;
using Starcounter;

namespace StarcounterApplication1
{
    [Database]
    public class Foo { }

    class Program
    {
        static void Main()
        {
            
            
        }

        static void Read()
        {
            Socket socket = null;

            while (socket.Connected)
            {
                byte[] bytes = null;

                try
                {
                    socket.Receive(bytes);
                }
                catch (SocketException ex) when (ex.ErrorCode == 10058)
                {
                }
            }
        }
    }
}
```

**Comment by per-samuelsson** [comment]
> @per-samuelsson this is strange, but your code snippet works, here is another one, which does not.

Thanks @miyconst, I've set that up locally and can confirm it fails too. Strange enough, if you move `byte[] bytes = null;` out from the `while`-clause, it *does* work. So it's something really specific for sure. We might actually be able to fix this, even with our version of PostSharp. I hope I can find some time to look closer into it.

**Comment by per-samuelsson** [comment]
FWIW, this will no longer be an issue when we implement https://github.com/Starcounter/RebelsLounge/issues/43. The thing that fail here is some weirdness we have to do to make sure users don't use database fields in a "wrong way".

We might need to spend time fixing it though, since dropping fields have been pushed to 2.4.

**Comment by miyconst** [comment]
>We might need to spend time fixing it though, since dropping fields have been pushed to 2.4.

Why it was pushed to 2.4? I thought it is 2.3.

**Comment by per-samuelsson** [comment]
> Why it was pushed to 2.4? I thought it is 2.3.

Sorry, it's not fully decided, but an ongoing discussion. The rationale is that as of now, 2.3 don't contain any breaking changes to application code and we feel we want to get users from 2.2 -> 2.3 first (because of all the goodies underneath), and then postpone breaking changes to 2.4.

I will update the https://github.com/Starcounter/RebelsLounge/issues/43 to reflect that. Let's continue the discussion there, since it's kind of off-topic here.
