### ISSUE TITLE
got exception while ReLoading DB

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3964]
```
System.Exception: ScErrUnhandledException (SCERR1069): An unhandled exception was detected.
Version: 2.3.0.4845.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR1069.
   at StarcounterInternal.Hosting.Processor.RunTaskNoScheduling(Action userAction, String appName) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 121
   at Starcounter.DbSession.GetAndExecuteQueuedTasks(Action`2 taskExecutionMethod) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Starcounter\DbSession.cs:line 180
   at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 168
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 81
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR1069
---> System.NullReferenceException: Object reference not set to an instance of an object.
   at UserAdmin.CommitHooks.RefreshSignInState() in C:\adfenix-backend\UserAdmin-pnext\src\UserAdmin\Api\CommitHooks.cs:line 26
   at UserAdmin.CommitHooks.<>c.<Register>b__1_0(Object s, SystemUserSession a) in C:\adfenix-backend\UserAdmin-pnext\src\UserAdmin\Api\CommitHooks.cs:line 11
   at Starcounter.RuntimeInstalledHookDelegate`1.Invoke(Object triggeringObject) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Starcounter\Hooks\RuntimeInstalledHookDelegate.cs:line 37
   at Starcounter.InvokableHook.InvokeAllWithKey(HookKey key, Object instance) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Starcounter\Hooks\InvokableHook.cs:line 72
   at Starcounter.Internal.TransactionManager.InvokeHooks() in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Starcounter\TransactionManager.cs:line 727
   at Starcounter.Internal.TransactionManager.Commit(Int32 free) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Starcounter\TransactionManager.cs:line 655
   at Starcounter.Db.Transact(Action action, UInt32 flags, TransactOptions opts) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Starcounter\Db.cs:line 280
   at Starcounter.Internal.StarcounterEnvironment.RunWithinApplication(String desiredAppName, Action action) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Starcounter.Internal\Mock\StarcounterEnvironment.cs:line 128
   at Starcounter.DbSession.<>c__DisplayClass6_0.<RunSync>b__0() in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Starcounter\DbSession.cs:line 261
   at Starcounter.Task.Run() in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Starcounter\DbSession.cs:line 100
HResult=-2147467261
```

**Comment by atifwaqar** [comment]
1. I commented the `CommitHooks` in `UserAdmin-pnext` project, to avoid the exception.
2. Deleted the db again
3. Created DB
4. Started all apps
5. started Reload
6. Got this error now 
```
System.Exception: ScErrUnhandledException (SCERR1069): An unhandled exception was detected.
Version: 2.3.0.4845.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR1069.
   at StarcounterInternal.Hosting.Processor.RunTaskNoScheduling(Action userAction, String appName) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 121
   at Starcounter.DbSession.GetAndExecuteQueuedTasks(Action`2 taskExecutionMethod) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Starcounter\DbSession.cs:line 180
   at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 168
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 81
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR1069
---> Starcounter.SqlException: ScErrConstraintViolationAbort (SCERR8001): A transaction was aborted because a constraint was violated.  The error near or at position -1.
In query: INSERT INTO "Starcounter"."Raw"."Simplified"."Ring3"."SystemUserGroup"(__id,"Description","Name","Parent")VALUES(object 15,'System User Administrator Group','Admin (System Users)',NULL),(object 24,NULL,'webmaster',NULL),(object 37,NULL,'admin',NULL),(object 3430305,NULL,'webmaster',NULL),(object 3430359,NULL,'webmaster',NULL),(object 3637149,NULL,'webmaster',NULL),(object 4196869,NULL,'webmaster',NULL),(object 4198672,NULL,'webmaster',NULL),(object 4206519,NULL,'webmaster',NULL),(object 4224208,NULL,'webmaster',NULL),(object 4224331,NULL,'webmaster',NULL),(object 4639227,NULL,'webmaster',NULL),(object 4642407,NULL,'webmaster',NULL),(object 4660203,NULL,'webmaster',NULL),(object 4662369,NULL,'IndividualSeller',NULL),(object 5020562,NULL,'webmaster',NULL),(object 5273201,NULL,'webmaster',NULL),(object 5372461,NULL,'webmaster',NULL),(object 5381748,NULL,'webmaster',NULL),(object 5509778,NULL,'webmaster',NULL),(object 5763759,NULL,'webmaster',NULL),(object 5878969,NULL,'webmaster',NULL)
Version: 2.3.0.4845.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR8001
```

**Comment by miyconst** [comment]
Related https://github.com/Starcounter/Starcounter/issues/3949.

cc @k-rus, @bigwad.

**Comment by atifwaqar** [comment]
I removed the line from SQL dump file, where it said 
```
INSERT INTO "Starcounter"."Raw"."Simplified"."Ring3"."SystemUserGroup...
```
I had this sort of error multiple times, so i simply removed that row from SQL Dump file, and finally my DB is reloaded now.
But we cant do this exercise on all live servers, so the DB Reload needs to be enhanced so that it either ignores errors like these, or manage to fix them automatically. 

If this is not possible, then what would be best and easy for us to reload is that whenever exceptions like these occurs, they should be logged in a log file, so that we know what rows and how many rows have the issues or constraints. 

Let me know if this is not making any sense, i'll explain on Hangout call.

**Comment by k-rus** [comment]
> System.Exception: ScErrUnhandledException (SCERR1069): An unhandled exception was detected.
> Version: 2.3.0.4845.
> Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR1069.
>    at StarcounterInternal.Hosting.Processor.RunTaskNoScheduling(Action userAction, String appName) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 121
>    at Starcounter.DbSession.GetAndExecuteQueuedTasks(Action`2 taskExecutionMethod) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Starcounter\DbSession.cs:line 180
>    at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 168
>    at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\BuildAgent\work\sc-pnext-nightly-333\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 81
> HResult=-2146233088
> HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR1069
> ---> Starcounter.SqlException: ScErrConstraintViolationAbort (SCERR8001): A transaction was aborted because a constraint was violated.  The error near or at position -1.
> In query: INSERT INTO "Starcounter"."Raw"."Simplified"."Ring3"."SystemUserGroup"(__id,"Description","Name","Parent")VALUES(object 15,'System User Administrator Group','Admin (System Users)',NULL),(object 24,NULL,'webmaster',NULL),(object 37,NULL,'admin',NULL),(object 3430305,NULL,'webmaster',NULL),(object 3430359,NULL,'webmaster',NULL),(object 3637149,NULL,'webmaster',NULL),(object 4196869,NULL,'webmaster',NULL),(object 4198672,NULL,'webmaster',NULL),(object 4206519,NULL,'webmaster',NULL),(object 4224208,NULL,'webmaster',NULL),(object 4224331,NULL,'webmaster',NULL),(object 4639227,NULL,'webmaster',NULL),(object 4642407,NULL,'webmaster',NULL),(object 4660203,NULL,'webmaster',NULL),(object 4662369,NULL,'IndividualSeller',NULL),(object 5020562,NULL,'webmaster',NULL),(object 5273201,NULL,'webmaster',NULL),(object 5372461,NULL,'webmaster',NULL),(object 5381748,NULL,'webmaster',NULL),(object 5509778,NULL,'webmaster',NULL),(object 5763759,NULL,'webmaster',NULL),(object 5878969,NULL,'webmaster',NULL)
> Version: 2.3.0.4845.
> Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR8001

Such error often experienced when there is unique constraint and non-unique data are provided. For example, NULL values are not unique in Starcounter. See discussion in https://github.com/Starcounter/Starcounter/issues/3546

Do you have any indexes created when you load the dump?

In any case I believe the error indicates broken data. Removing broken data solves the problem of loading, but the data is missing. Treating such situation in generic way is not obvious.

**Comment by atifwaqar** [comment]
@k-rus I had clean DB. I deleted the db and create it every time i start the reload process.
Also i have commented out all code in my `Main` function. So I'm 100% confident that my apps launching are not creating any objects, and that my DB is completely empty when i start the reload process.

**Comment by k-rus** [comment]
> my apps launching are not creating any objects

Just to be clear: no indexes are there, right? You can check this by querying the app from Administrator: `select * from starcounter.metadata.\"index\"`.

The only other possibility for the error is if some app still creates data.

**Comment by atifwaqar** [comment]
Yes there are no indexes, just verified.

**Comment by per-samuelsson** [comment]
I'm quite sure this is due to the fact that some apps "auto-create" data on startup. Something that doesn't go well together with either replication, nor reloading.

I have a vague memory I struggled with that some year ago when helping out another customer that used on of those apps, and I raised an issue that it's a poor strategy. I'll see if I can find any traces of that old discussions / reports.

**Comment by per-samuelsson** [comment]
@atifwaqar 

Guess you dont have access to this: https://github.com/Starcounter/CompanyTrack/issues/179

Right?

It's basically me raising the question internally earlier this year.

Here's a reference to a specific occurance: https://github.com/StarcounterPrefabs/SignIn/issues/11

**Comment by per-samuelsson** [comment]
Found a similar pattern, this time in `UserAdmin`:

https://github.com/StarcounterPrefabs/UserAdmin/blob/master/src/UserAdmin/Program.cs#L49-L76

Is that one of the apps you are starting before doing the reload @atifwaqar?

**Comment by atifwaqar** [comment]
@per-samuelsson I am starting `UserAdmin-pnext`

**Comment by per-samuelsson** [comment]
> @per-samuelsson I am starting UserAdmin-pnext

It seem to suffer from the same flaw:

https://github.com/StarcounterPrefabs/UserAdmin/blob/pnext-adaptation/src/UserAdmin/Program.cs#L49-L74

**Comment by atifwaqar** [comment]
@per-samuelsson I agree with you.
Then i'll comment out the code in `Main` function of UserAdmin app, and then i'll try to re-do the test morning.

**Comment by per-samuelsson** [comment]
> Then i'll comment out the code in Main function of UserAdmin app, and then i'll try to re-do the test morning.

Good luck. Really sorry you have to take that path. I'm bumping it internally.

**Comment by atifwaqar** [comment]
@per-samuelsson No problem at all, Its ok with me.  :)

**Comment by mtornwall** [comment]
Possibly related to an old friend of mine, #3546.

**Comment by dan31** [comment]
Old way to migrate is deprecated in favor of StarDump:
2.2 -> 2.3: https://docs.starcounter.io/guides/working-with-starcounter/migrating-from-2.2-to-2.3+/
2.3 -> 2.(3+N): https://docs.starcounter.io/guides/working-with-starcounter/unload-reload/
