### ISSUE TITLE
Unable to execute SQL query with an unsigned int 64 value

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3968]
I am trying to execute the following SQL query:

```sql
SELECT *
FROM Starcounter.MetaData.Column
WHERE "Table".ObjectNo = 18446744073709547875
```

And it fails with the following exception:

```
System.OverflowException: Value was either too large or too small for an Int64. View the log for more details.
```

cc @andwah

**Comment by per-samuelsson** [comment]
cc @k-rus

**Comment by andwah** [comment]
@miyconst Not sure where the limitation is in the all the needed steps, Starcounter, JSON, JavaScript

**Comment by miyconst** [comment]
Most likely it is c# implementation of the administrator, which tries to treat the value as `long` or `Int64`, which is wrong in this case, since it is an unsigned value, means `ulong` or `UInt64`.

**Comment by miyconst** [comment]
Here is the stack trace.

```
"System.OverflowException: Value was either too large or too small for an Int64.
   at System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   at Starcounter.Query.Sql.Creator.IntegerParse(String literal) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-334\Level1\src\Starcounter\Query\SQL\_Creator.cs:line 2356
   at Starcounter.Query.Sql.Creator.CreateIntegerLiteral(Term literalTerm) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-334\Level1\src\Starcounter\Query\SQL\_Creator.cs:line 2369
   at Starcounter.Query.Sql.Creator.CreateValueExpression(RowTypeBinding rowTypeBind, Term exprTerm, VariableArray varArray) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-334\Level1\src\Starcounter\Query\SQL\_Creator.cs:line 2011
   at Starcounter.Query.Sql.Creator.CreateComparisonNumerical(RowTypeBinding rowTypeBind, Term opTerm, Term exprTerm1, Term exprTerm2, VariableArray varArray) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-334\Level1\src\Starcounter\Query\SQL\_Creator.cs:line 1275
   at Starcounter.Query.Sql.Creator.CreateLogicalExpression(RowTypeBinding rowTypeBind, Term term, VariableArray varArray) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-334\Level1\src\Starcounter\Query\SQL\_Creator.cs:line 1045
   at Starcounter.Query.Sql.Creator.CreateLogicalOperation(RowTypeBinding rowTypeBind, Term opTerm, Term exprTerm1, Term exprTerm2, VariableArray varArray) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-334\Level1\src\Starcounter\Query\SQL\_Creator.cs:line 1184
   at Starcounter.Query.Sql.Creator.CreateLogicalExpression(RowTypeBinding rowTypeBind, Term term, VariableArray varArray) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-334\Level1\src\Starcounter\Query\SQL\_Creator.cs:line 1033
   at Starcounter.Query.Sql.Creator.MapTermsToOptimizerInput(RowTypeBinding rowTypeBind, Term nodeTreeTerm, Term whereCondTerm, Term orderbyComparerListTerm, Term fetchTerm, Term hintListTerm, VariableArray varArray, String query) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-334\Level1\src\Starcounter\Query\SQL\_Creator.cs:line 133
   at Starcounter.Query.Sql.Creator.CreateOptimizerInput(RowTypeBinding rowTypeBind, Term term, VariableArray varArray, String query) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-334\Level1\src\Starcounter\Query\SQL\_Creator.cs:line 76
   at Starcounter.Query.QueryPreparation.PrepareOrExecuteQuery[T](String query, Boolean slowSql, Object[] values) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-334\Level1\src\Starcounter\Query\QueryPreparation.cs:line 69
   at Starcounter.Query.Sql.SqlEnumCache.CacheOrExecuteEnumerator[T](String query, Boolean slowSQL, Object[] values) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-334\Level1\src\Starcounter\Query\SQL\_SqlEnumCache.cs:line 127
   at Starcounter.Db.FullQueryProcess[T](String query, Boolean slowSQL, Object[] values) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-334\Level1\src\Starcounter\Mock\Db.cs:line 132
   at Starcounter.Db.SlowSQL(String query, Object[] values) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-334\Level1\src\Starcounter\Mock\Db.cs:line 104
   at Starcounter.Internal.SqlRestHandler.ExecuteQuery(String query, Int32 maxResult) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-334\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\SqlRestHandler.cs:line 97
HResult=-2146233066
"
```

**Comment by andwah** [comment]
@miyconst I need to take a closer look but the query string is not "treated" in the administrator it is sent directly to "Db.SlowSql(<the query>)".  
The result is does some convertions etcm UInt64 is converted to a string.

Do you get the same exception when you execute the query from c# ?

**Comment by per-samuelsson** [comment]
@miyconst 

> **Most likely it is c# implementation of the administrator**, which tries to treat the value as `long` or `Int64`, which is wrong in this case, since it is an unsigned value, means `ulong` or `UInt64`.

I don't. That's why I cc'd @k-rus. If I'm not mistaken, the administrator is indifferent to what you write in your queries. They are just passed forward to the server.

**Comment by per-samuelsson** [comment]
@miyconst 

This is really a long shot, but maybe read up on [SQL literals](https://starcounter.io/guides/sql/literals/) and try that thing with

```sql
SELECT e FROM Employee e WHERE e = OBJECT 123
```

in which case I guess your query could be rewritten something like

```sql
SELECT *
FROM Starcounter.MetaData.Column c
WHERE c."Table" = OBJECT 18446744073709547875
```

**Comment by miyconst** [comment]
@per-samuelsson I can execute the query using the string key `ObjectID`, so it does not stop me, but the exception is still there.

**Comment by per-samuelsson** [comment]
> @per-samuelsson I can execute the query using the string key ObjectID, so it does not stop me, but the exception is still there.

OK. Let's what to see what @k-rus can help us with.

**Comment by k-rus** [comment]
The stack trace shows that the problem is with the old query processor/optimiser, which seems to parse input value as signed integer.

@miyconst 
Can you post the query/execution plan?

**Comment by miyconst** [comment]
>Can you post the query/execution plan?

@k-rus the query fails to execute, there is no query plan for it.

**Comment by k-rus** [comment]
> @k-rus the query fails to execute, there is no query plan for it.

This means that Administrator does not show it. There is nothing to prevent this. Thanks for checking.

I will assign myself to this issue.
