### ISSUE TITLE
Unhandled exception & error: Cannot find or open the PDB file

### ISSUE THREAD

**Issue by Mnosek** [Starcounter/Starcounter#3969]
* I've had Starcounter v2.3.0.4787 and some apps running on that. Everything worked fine.
* I've updated Starcounter to current pnext (v2.3.0.4846). Everything worked fine.
* As I started debugging some other problems after many rebuilds and app restarts I've started facing a weird problem (even on codebase which worked fine before).
* Apps are starting fine, problem occurs when I try to use feature referring to classes using external library installed from nuget: https://www.nuget.org/packages/DotLiquid.
* After some time following error appears in db log:
 
```
System.Exception: ScErrUnhandledException (SCERR1069): An unhandled exception was detected.
Version: 2.3.0.4846.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR1069.
   at StarcounterInternal.Hosting.Processor.RunTaskNoScheduling(Action userAction, String appName) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-334\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 121
   at Starcounter.DbSession.GetAndExecuteQueuedTasks(Action`2 taskExecutionMethod) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-334\Level1\src\Starcounter\DbSession.cs:line 180
   at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-334\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 168
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-334\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 81
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR1069
---> Starcounter.DbException: ScErrTransactionModifiedButNotReferenced (SCERR4287): Data in the transaction is created or updated, but the transaction is not referenced and will be discarded.
Version: 2.3.0.4846.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4287.
   at Starcounter.Internal.TransactionManager.CheckForRefOrDisposeTransaction(TransactionHandle handle) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-334\Level1\src\Starcounter\TransactionManager.cs:line 266
   at Starcounter.Db.Scope(Action action, Boolean isReadOnly) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-334\Level1\src\Starcounter\Db.cs:line 361
   at DocumentGenerator.Program.<>c__DisplayClass1_0.<GenerateFile>b__0(Session session, String id) in C:\Projects\SweOffshore\Sweoffshore\DocumentGenerator\Program.cs:line 23
   at Starcounter.Session.Use(SessionTask action, String sessionId) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-334\Level1\src\Starcounter.XSON\Sessions\Session.cs:line 730
   at Starcounter.Task.Run() in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-334\Level1\src\Starcounter\DbSession.cs:line 100
ErrorCode=4287
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4287
```

* All apps are crashing after that.
* I've started to watch debugger output and found a moment/problem most likely related to this problem:

```
Starcounter.Host.AssemblyResolver:Asked to resolve reference to DotLiquid, Version=2.0.55.0, Culture=neutral, PublicKeyToken=82e46016ecf9f07c, requested by DocumentGenerator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
0.0 Starcounter.Host.AssemblyResolver:Could not resolve DotLiquid, Version=2.0.55.0, Culture=neutral, PublicKeyToken=82e46016ecf9f07c to loaded assembly.
0.0 Starcounter.Host.AssemblyResolver:Loading assembly DotLiquid, Version=2.0.55.0, Culture=neutral, PublicKeyToken=82e46016ecf9f07c from C:\Starcounter\Personal\Temp\default\default-20161122T110548896\weaver\589A14F0148EFCDE1E1CCA37789B1B57D836F25C\DotLiquid.dll
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'C:\Starcounter\Personal\Temp\default\default-20161122T110548896\weaver\589A14F0148EFCDE1E1CCA37789B1B57D836F25C\DotLiquid.dll'. Cannot find or open the PDB file.
Exception thrown: 'System.InvalidOperationException' in System.dll
Exception thrown: 'Starcounter.DbException' in Starcounter.dll
Exception thrown: 'System.Exception' in Starcounter.Hosting.dll
ScErrUnhandledException (SCERR1069): An unhandled exception was detected.
```

* I've tried restarting database, windows, deleting database, restarting apps, VS etc. Nothing worked. I found solution that helped me here: https://github.com/StarcounterSamples/KitchenSink/issues/13#issuecomment-173548235
* I deleted a folder listed in error above, rebuilt, restarted app and it works without any problems now.

Interesting thing: all folders located in `Starcounter\Personal\Temp\Default` were started from capital letter, new folder which just appeared is now started from small letter.

cc @per-samuelsson

**Comment by chrhol** [comment]
This exception: 

> Starcounter.DbException: ScErrTransactionModifiedButNotReferenced (SCERR4287): Data in the transaction is created or updated, but the transaction is not referenced and will be discarded.
Version: 2.3.0.4846.

means that somewhere a `Db.Scope` is created (if we follow the stacktrace it would be `DocumentGenerator.Program.<>c__DisplayClass1_0.<GenerateFile>b__0`), and some database object is modified, but there is no commit or any viewmodel that the scope can attach to (by either create a new json inside or call manual method on json). So you have an orphaned longrunning transaction with changes that will just be discarded. 

We added the exception since this is almost always unintended, and stems from some bug in usercode.

**Comment by Mnosek** [comment]
Yeah, I see and understand this exception, but when this error:
```
0.0 Starcounter.Host.AssemblyResolver:Loading assembly DotLiquid, Version=2.0.55.0, Culture=neutral, PublicKeyToken=82e46016ecf9f07c from C:\Starcounter\Personal\Temp\default\default-20161122T110548896\weaver\589A14F0148EFCDE1E1CCA37789B1B57D836F25C\DotLiquid.dll
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'C:\Starcounter\Personal\Temp\default\default-20161122T110548896\weaver\589A14F0148EFCDE1E1CCA37789B1B57D836F25C\DotLiquid.dll'. Cannot find or open the PDB file.
```

In debugger doesn't exist, there is no exception that you've described at all and everything works fine. No exceptions anymore. I mean all I needed to make it works was to delete this folder: `C:\Starcounter\Personal\Temp\default\default-20161122T110548896`.  Why? deleting a temp folder should not be a solution :)
