### ISSUE TITLE
LikeExecEnumerator: Index was outside the bounds of the array

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3970]
I am trying to execute the following query.

```cs
List<Starcounter.Metadata.Table> tables = Db.SQL<Starcounter.Metadata.Table>("SELECT t FROM Starcounter.Metadata.Table t WHERE t.Inherits IS NULL AND t.FullName NOT LIKE ? AND t.FullName NOT LIKE ?", "Concepts.%", "Starcounter.%").ToList();
```

Or

```cs
List<Starcounter.Metadata.Table> tables = Db.SQL<Starcounter.Metadata.Table>("SELECT t FROM Starcounter.Metadata.Table t WHERE t.Inherits = ? AND t.FullName NOT LIKE ? AND t.FullName NOT LIKE ?", null, "Concepts.%", "Starcounter.%").ToList();
```

And it fails with the following exception.

```
"System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Starcounter.Query.Execution.LikeExecEnumerator.MoveNext() in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-334\Level1\src\Starcounter\Query\Execution\Enumerators\LikeExecEnumerator.cs:line 219
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SQLiteDump.Program.<>c.<Main>b__2_0() in F:\SQLiteDump\SQLiteDump\Program.cs:line 78
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-334\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-334\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-334\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 765
HResult=-2146233080
"
```

The same query from administrator works.

```sql
SELECT *
FROM Starcounter.Metadata.Table t
WHERE t.Inherits IS NULL
    AND t.FullName NOT LIKE 'Concepts.%'
    AND t.FullName NOT LIKE 'Starcounter.%'
```

cc @k-rus

**Comment by k-rus** [comment]
Thank you for reporting the bug.
When I fixed #3909, I noticed that `NOT LIKE` was never supported syntactically. Currently I cannot say if the combination of `NOT` and `LIKE` does not work intentionally or it is just a bug.

I will assign it to me. Its priority needs to be decided.
