### ISSUE TITLE
How to sort Starcounter.Arr<T> in C#

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/Starcounter#3991]

**Comment by SenerDemiral** [comment]
I tried this with Linq
```
var taks = Db.SQL<TTDB.TurnuvaTakim>("SELECT o FROM TurnuvaTakim o where o.Turnuva = ?", turnuva).ToArray();

var sort = from s in taks
                 orderby  s.Ozet.Puan descending
                 select s;
```
But I can't convert sort to Takimlar.

**Comment by dan31** [comment]
CC @k-rus @miyconst

**Comment by miyconst** [comment]
@SenerDemiral it is not very clear of what you are trying to do.

Am I right that you want to sort items by some order inside a JSON view-model? If so, then you should not sort the JSON `Starcounter.Arr<T>` items itself, the data should be sorted.

Example:

```cs
TurnuvaTakimlarJson page = new TurnuvaTakimlarJson();

page.Takimlar.Data = Db.SQL("SELECT o FROM TurnuvaTakim o where o.Turnuva = ?", turnuva).OrderByDescending(x => x.Ozet.Puan);
```

**Comment by SenerDemiral** [comment]
Thank you.
It works.
I am trying to sort  records of table according to computed field (Ozet.Puan) of that table.
Because Db.SQL ORDER BY does not working on computed fields!
```
page.Takimlar.Data = Db.SQL("SELECT o FROM TurnuvaTakim o where o.Turnuva = ?", turnuva).OrderByDescending(x => x.Ozet.Puan);
```
should be
```
page.Takimlar.Data = Db.SQL<TurnuvaTakim>("SELECT o FROM TurnuvaTakim o where o.Turnuva = ?", turnuva).OrderByDescending(x => x.Ozet.Puan);
```

**Comment by miyconst** [comment]
>Because Db.SQL ORDER BY does not working on computed fields!

Can you please clarify? It should work on the computed fields.

What version of Starcounter do you use, and how it "does not work"? Any errors or the result is wrong?

>... should be

Yes, you are correct, the generic type `Db.SQL<TurnuvaTakim>` definition is required.

**Comment by SenerDemiral** [comment]
v2.3.0.5132
Error Log
```
Starcounter.SqlException: Failed to process query: SELECT o FROM TurnuvaTakim o where o.Turnuva = ? ORDER BY o.Ozet.Puan DESC: Unknown property Ozet of class TTDB.TurnuvaTakim. 
   at Starcounter.Query.QueryPreparation.PrepareOrExecuteQuery[T](String query, Boolean slowSql, Object[] values) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-355\Level1\src\Starcounter\Query\QueryPreparation.cs:line 70
   at Starcounter.Query.Sql.SqlEnumCache.CacheOrExecuteEnumerator[T](String query, Boolean slowSQL, Object[] values) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-355\Level1\src\Starcounter\Query\SQL\_SqlEnumCache.cs:line 127
   at Starcounter.Db.FullQueryProcess[T](String query, Boolean slowSQL, Object[] values) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-355\Level1\src\Starcounter\Mock\Db.cs:line 132
   at TT.TurnuvaTakimlarJson.RefreshData(String turnuvaID) in C:\Starcounter\Projects\TT\TT\TurnuvaTakimlarJson.json.cs:line 13
   at TT.TurnuvalarJson.TurnuvalarItemPage.Handle(TakimlarToggle inp) in C:\Starcounter\Projects\TT\TT\TurnuvalarJson.json.cs:line 62
   at TT.TurnuvalarJson.TurnuvalarItemPage.JsonByExample.Schema.<>c.<.ctor>b__0_29(Json pup, Input`1 input)
   at Starcounter.Templates.Property`1.InvokeHandler(Json parent, Input`1 input) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-355\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 272
   at Starcounter.Templates.Property`1.ProcessInput(Json parent, T value) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-355\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 294
   at Starcounter.XSON.DefaultPatchHandler.ParseAndProcess(TLong property, Json parent, IntPtr valuePtr, Int32 valueSize) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-355\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 118
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-355\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 70
   at Starcounter.XSON.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, IntPtr valuePtr, Int32 valueSize) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-355\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 37
   at Starcounter.XSON.JsonPatch.Apply(Json root, IntPtr patchArrayPtr, Int32 patchArraySize, Boolean strictPatchRejection) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-355\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 687
   at Starcounter.XSON.JsonPatch.Apply(Json root, Byte[] patchArray, Boolean strictPatchRejection) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-355\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 527
   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(Byte[] bs, WebSocket ws) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-355\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 61
   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 managedHandlerId, UInt32 groupId, WebSocket ws) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-355\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 289
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-355\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 796
ScErrorCode=0
BeginPosition=-1
EndPosition=-1
HResult=-2146233088
```

**Comment by miyconst** [comment]
@k-rus please take a look.

**Comment by SenerDemiral** [comment]
Source: [https://github.com/SenerDemiral/TT](url)

**Comment by k-rus** [comment]
Thank you for the issue.

It requires investigation if code properties are supported for sorting or not and requirements. It might be required to specify both getter and setter to make it work. May be @per-samuelsson remembers.

I see that the property `Ozet`, which is used in sorting, is quite expensive, since it creates new object in heap and executes several queries. I cannot say directly if the property is executed on every comparison during sorting or not. Requires some investigation. So it is important to be aware, the sorting can be seriously expensive in this case.

So actions for us:

1. We need to investigate and document using code properties in ORDER BY, which very likely to depend mainly on weaver and bootstrapping.
2.  We need to investigate and document how sorting is implemented in old SQL executor.

**Comment by per-samuelsson** [comment]
> It might be required to specify both getter and setter to make it work. May be @per-samuelsson remembers.

Not sure what I should remember? 

> We need to investigate and document using code properties in ORDER BY, **which very likely to depend mainly on weaver and bootstrapping**.

Can you expand on how ORDER BY can be influenced by the weaver? The weaver does one thing: decide if a property is to be considered persistent or not. It's considered persistent if there is **both a getter and a setter** and the implementations of those contain a **single instruction that read/write from/to a backing field**. Otherwise it's considered a code property, in which case the weaver don't bother with it at all (similar to any other method).

**Comment by per-samuelsson** [comment]
> Somehow the information about code properties is put into runtime metadata during bootstrap, which then is delivered to the query parser and type checker. If I don't mistake the input for the bootstrap is produced by the weaver.

Well, my question was more how the weaver could act in a different way to support ORDER BY on code properties, which is what this issue is about if I'm not mistaken. The weaver give the host a chance to determine if a property is a database ("persistent") property or not (in which case it is a property with code). What more could it possibly do? If there is missing analysis, I need to know what to share my view further.

**Comment by per-samuelsson** [comment]
Just to be very clear here, my bottomline is I don't understand that if we support a class such as this

```cs
[Database] public class Foo {
  public string Bar {
    get { return "I'm" + " a " + " computed property " + " for sure"; }
  }
}
```

being *queried* like this

```sql
var f = Db.SQL<Foo>("SELECT f FROM Foo f WHERE f.Bar = ?", "Won't hit much at all");
```

then how the *weaver* could enable this to work:

```sql
var f = Db.SQL<Foo>("SELECT f FROM Foo f ORDER BY f.Bar");
```

**Comment by per-samuelsson** [comment]
@miyconst suggested we move the kind of low-level discussions in-house, not to clutter this issue about what area in Starcounter is in need of improvement here, and he's totally right. I should have thought about that. Thanks for pointing it out, @miyconst.

I'll create an internal issue where we can keep research and see if we can reach some better understanding about what the options are for this case.

@SenerDemiral, we'll get back to you as soon as we have something valuable to share!

**Comment by SenerDemiral** [comment]
@per-samuelsson,  I solved my problem simply using Linq.
After that it is up to your decision.
```
page.Takimlar.Data = Db.SQL<TurnuvaTakim>("SELECT o FROM TurnuvaTakim o where o.Turnuva = ?", turnuva).OrderByDescending(x => x.Ozet.Puan);
```

**Comment by SenerDemiral** [comment]
It can be like OldSQL View or StoredProcedure in DB.
No real table but produced from other tables and can be used as readOnly table.

**Comment by per-samuelsson** [comment]
> @per-samuelsson, I solved my problem simply using Linq.
After that it is up to your decision.

Thanks for sharing that @SenerDemiral and sorry for the inconvenience. We will do a round of in-house discussion at least, and let's see where it gets us.
