### ISSUE TITLE
SC PnextNightly 2.3.0.5282 not running any app

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3995]
I installed latest PnextNightly to test https://github.com/Starcounter/Starcounter/issues/3798.
But im not able to run any app (Including AdFenix app). 

![image](https://cloud.githubusercontent.com/assets/4388707/21002822/08ca9ccc-bd28-11e6-8162-edf25ee07415.png)

and this is what I can see in SC Logs when i try to run AdFenix app :
```
System.Exception: ScErrUnexpMetadata (SCERR7035): Internal error in unmanaged meta-data population.
Version: 2.3.0.5282.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR7035.
   at Starcounter.SqlProcessor.SqlProcessor.MetalayerThrowIfError(UInt32 err) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-363\Level1\src\Starcounter\SqlProcessor\SqlProcessor.cs:line 379
   at Starcounter.SqlProcessor.SqlProcessor.PopulateRuntimeMetadata() in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-363\Level1\src\Starcounter\SqlProcessor\SqlProcessor.cs:line 275
   at Starcounter.Hosting.StarcounterPackage.UpdateDatabaseSchemaAndRegisterTypes(String fullAppId, TypeDef[] unregisteredTypeDefs, TypeDef[] allTypeDefs) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-363\Level1\src\Hosting\Starcounter.Hosting\StarcounterPackage.cs:line 43
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application, ApplicationDirectory applicationDir) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-363\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 265
   at Starcounter.Hosting.Package.Process() in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-363\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 138
   at Starcounter.Hosting.Package.Process(IntPtr hPackage) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-363\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 55
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-363\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 85
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR7035
```

**Comment by atifwaqar** [comment]
I just installed all these versions and I had the same issue in all : 
2.3.0.5282 (Dec 7, 2016 2:02:09 AM)
2.3.0.5267 (Dec 6, 2016 2:00:12 PM)
2.3.0.5257 (Dec 6, 2016 2:02:08 AM)
2.3.0.5212 (Dec 5, 2016 11:27:03 AM)
2.3.0.5209 (Dec 5, 2016 2:02:05 AM)
2.3.0.5205 (Dec 4, 2016 2:02:00 AM)
2.3.0.5192 (Dec 3, 2016 2:02:03 AM)
2.3.0.5159 (Dec 2, 2016 2:02:05 AM)
2.3.0.5132 (Dec 1, 2016 2:02:08 AM)
2.3.0.5110 (Nov 30, 2016 2:01:45 AM)

Now I have installed PnextDaily 2.3.0.4583 (Nov 3, 2016 11:11:32 PM). And things work for me now. 
Is it possible that there is some issue in my Machine? or is this SC issue?

**Comment by bigwad** [comment]
Looks like format of metadata has changed. Then you need to drop or reload your database.
cc @k-rus

**Comment by k-rus** [comment]
@atifwaqar What version of Starcounter was used to create the database?

**Comment by atifwaqar** [comment]
@k-rus I dont remember the version number, i remember the date. It was 21st November's Nightly Build

**Comment by atifwaqar** [comment]
So I tried to unload/reload, but it was taking too much time so I just deleted my local DB, installed SC again, and things work fine now. Except `UserAdmin` app (version 4.0.3 Nov 17 build). I installed it from `App Warehouse`.

**Comment by dan31** [comment]
@atifwaqar just to let you know - @miyconst and @ubbeK are working on the proper Unload/Reload tool which, as we expect, solves all the current glitches with Unload/Reload and allows to take data migrations into fine control. We will keep you tuned on that matter. We hope to have it at pre-release state in the end of December.

**Comment by dan31** [comment]
@atifwaqar we are well aware of the issue and in the middle of providing a proper solution!
could you pls share the approximate data sizes that you should migrate on live servers? (CC @miyconst)

**Comment by atifwaqar** [comment]
@dan31 We have 8 live servers. And one of the largest server's DB size is 69 GB.

**Comment by atifwaqar** [comment]
`UserAdmin` app in `App Warehouse` is not working with latest SC Nightly build 2.3.0.5282.
How can I fix it?

**Comment by atifwaqar** [comment]
@bigwad The startup time is ok. my apps start in a couple of seconds if my DB is empty. 
But I am not the right person for this question. because I havent successfully done Unload/Reload completely on 2.3. I started Unload, and I was getting lot of missing Table/Column errors, so I just deleted the database and installed the latest nightly.

**Comment by dan31** [comment]
@atifwaqar could you share your current startup time on 2.2.x with 69 Gb DB?

**Comment by atifwaqar** [comment]
Sure, I'll check this on weekend, when I have no traffic on live server.

**Comment by k-rus** [comment]
> @k-rus I dont remember the version number, i remember the date. It was 21st November's Nightly Build

Thank you. It should be good enough for me. I will try to reproduce it and see how the problem looks like.

**Comment by atifwaqar** [comment]
I think we can close this?

**Comment by dan31** [comment]
Archived.
