### ISSUE TITLE
DbException: ScErrReadOnlyTransaction (SCERR4093): The transaction is readonly and cannot be changed to write-mode.

### ISSUE THREAD

**Issue by fiyazadfenix** [Starcounter/Starcounter#3999]
I used timeu polymer wizard. In my html i have 

```
<div id="Step4">
                                <h4>Fill the required instagram configuration fields?</h4>
                                <div class="horizontal layout">
                                    <div class="flex-4"></div>
                                    <div class="flex-4">
                                        <paper-input name="InstagramUserName" label="Intagram User Name" value="{{model.SelectedSeller$.Advertiser.InstagramAccount.UserName$}}"></paper-input>
                                        <paper-input name="InstagramPassword" label="Intagram Password" value="{{model.SelectedSeller$.Advertiser.InstagramAccount.Password$}}"></paper-input>
                                    </div>
                                    <div class="flex-4"></div>
                                </div>
                            </div> 
```
in .json i have 

```
{
  "$": { "Namespace": "AdFenix.Server.Partials.DomainConfigurations" },
  "Html": "",
  "$SelectedSellerID$": { "Bind": "SelectedSellerID_" },
  "SelectedSellerID$": "",
  "$SelectedSeller$": { "Bind": "SelectedSeller_" },
  "SelectedSeller$": {
    "Advertiser": {
      "FacebookPage": {
        "FbPageUrl$": "",
        "FbPageRequest$": false,
        "IsVerified$": false
      },
      "InstagramAccount": {
        "UserName$": "",
        "Password$":  ""
      }
    },
    "AutomaticallyPublish$": false
  },
  "WizardStep$": 0,
  "Next$": 0,
  "Previous$": 0,
  "Connect$": 0,
  "Verify$": 0,
  "TwitterPin$": "",
  "GetPinRequest$": 0,
  "VerifyPin$": 0,
  "ErrorMessage$": "",
  "StatusMessage$": "",
  "AutoPublishNo$": 0,
  "AutoPublishYes$":  0
}
```

but when i try to write something on this page i got these issues of connection error...
![1](https://cloud.githubusercontent.com/assets/20770666/21045364/3d933448-be2a-11e6-8216-49363fb3ccb6.png)

here is the sc log 

```
Starcounter.DbException: ScErrReadOnlyTransaction (SCERR4093): The transaction is readonly and cannot be changed to write-mode.
Version: 2.2.1.3234.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4093.
   at Starcounter.Internal.DbState.WriteString(UInt64 oid, UInt64 address, Int32 index, String value) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter\Internal\DbState.cs:line 1174
   at AdFenix.Database.Instagram.InstagramAccount.set_UserName(String value)
   at Starcounter.Templates.Property`1.BoundOrUnboundSet(Json parent, T value) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 41
   at Starcounter.Templates.Property`1.ProcessInput(Json parent, T value) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 304
   at Starcounter.XSON.DefaultPatchHandler.ParseAndProcess(TString property, Json parent, IntPtr valuePtr, Int32 valueSize) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 137
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 66
   at Starcounter.XSON.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, IntPtr valuePtr, Int32 valueSize) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 37
   at Starcounter.XSON.JsonPatch.Apply(Json root, IntPtr patchArrayPtr, Int32 patchArraySize, Boolean strictPatchRejection) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 682
   at Starcounter.XSON.JsonPatch.Apply(Json root, Byte[] patchArray, Boolean strictPatchRejection) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 522
   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(Byte[] bs, WebSocket ws) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 61
   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 managedHandlerId, UInt32 groupId, WebSocket ws) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 289
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-497\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 784
ErrorCode=4093
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4093
```

**Comment by atifwaqar** [comment]
I suspect you need to have `Db.Scope` when you create the View-Model object in your handler.

**Comment by miyconst** [comment]
>I suspect you need to have `Db.Scope` when you create the View-Model object in your handler.

Exactly. Otherwise transaction is readonly. Remember to commit the changes when finished.

**Comment by fiyazadfenix** [comment]
I've used but stilling having the same issue @miyconst 
 Db.Scope(() =>
                    {
                        SellerConfiguration.Html = "/client/partials/domainconfig/SellerConfiguration.html";
                        SellerConfiguration.SelectedSellerID = seller?.ObId;
                        SellerConfiguration.WizardStep = 1;
                    });

**Comment by miyconst** [comment]
Please go through [Hello World](https://starcounter.io/hello-world/first-interactive-ui-hello-world-part-3/) Starcounter tutorial to see how to use `Db.Scope`.
