### ISSUE TITLE
Reloading Database in 2.4

### ISSUE THREAD

**Issue by MujahidRashid** [Starcounter/Starcounter#4003]
I have been trying to reload database from the dump file created in 2.2.1.3234
 I get the following errors 

18:27:32, Critical, Starcounter (default)]
System.Exception: ScErrUnhandledException (SCERR1069): An unhandled exception was detected.
Version: 2.4.0.25.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR1069.
   at StarcounterInternal.Hosting.Processor.RunTaskNoScheduling(Action userAction, String appName) in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 121
   at Starcounter.DbSession.GetAndExecuteQueuedTasks(Action`2 taskExecutionMethod) in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Starcounter\DbSession.cs:line 180
   at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask) in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 168
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 81
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR1069
---> Starcounter.SqlException: ScErrConstraintViolationAbort (SCERR8001): A transaction was aborted because a constraint was violated.  The error near or at position -1.
In query: INSERT INTO "Starcounter"."Raw"."AdFenix"."Database"."Ads"."AdFenix"."AdTemplate"(__id,"AdDescriptionTemplate","AdHeadlineTemplate","AdMessageTemplate","AdNetworkName","AttributeType","Name","PublicationOwner")VALUES(object 499373,'','<<ModifiedTransactionType>> ~ <<DisplayNameClassifiedAd>>','<<BaseText>>','facebook','ClassifiedHomeAd','HomeAd',Object 81),(object 504709,' ','Book your free valuation today.','<<TransactionType>> by Douglas & Gordon ~ <<DisplayNameClassifiedAd>> Asking price œ<<A
Version: 2.4.0.25.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR8001.
   at Starcounter.SqlProcessor.SqlProcessor.ExecuteQuerySqlProcessor(String query) in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Starcounter\SqlProcessor\SqlProcessor.cs:line 205
   at Starcounter.Reload.<>c__DisplayClass15_0.<Load>b__3() in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Starcounter\Mock\Reload.cs:line 325
   at Starcounter.Reload.<>c__DisplayClass14_1`1.<DoParallelTransact>b__3() in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Starcounter\Mock\Reload.cs:line 302
   at Starcounter.Db.TransactAsync(Action action, UInt32 flags, TransactOptions opts) in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Starcounter\Db.cs:line 280
   at Starcounter.Db.Transact(Action action, UInt32 flags, TransactOptions opts) in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Starcounter\Db.cs:line 333
   at Starcounter.Internal.StarcounterEnvironment.RunWithinApplication(String desiredAppName, Action action) in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Starcounter.Internal\Mock\StarcounterEnvironment.cs:line 128
   at Starcounter.DbSession.<>c__DisplayClass6_0.<RunSync>b__0() in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Starcounter\DbSession.cs:line 261
   at Starcounter.Task.Run() in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Starcounter\DbSession.cs:line 100
ScErrorCode=8001
ErrorMessage= The error near or at position -1.
In query: INSERT INTO "Starcounter"."Raw"."AdFenix"."Database"."Ads"."AdFenix"."AdTemplate"(__id,"AdDescriptionTemplate","AdHeadlineTemplate","AdMessageTemplate","AdNetworkName","AttributeType","Name","PublicationOwner")VALUES(object 499373,'','<<ModifiedTransactionType>> ~ <<DisplayNameClassifiedAd>>','<<BaseText>>','facebook','ClassifiedHomeAd','HomeAd',Object 81),(object 504709,' ','Book your free valuation today.','<<TransactionType>> by Douglas & Gordon ~ <<DisplayNameClassifiedAd>> Asking price œ<<A
BeginPosition=-1
EndPosition=-1
Query=INSERT INTO "Starcounter"."Raw"."AdFenix"."Database"."Ads"."AdFenix"."AdTemplate"(__id,"AdDescriptionTemplate","AdHeadlineTemplate","AdMessageTemplate","AdNetworkName","AttributeType","Name","PublicationOwner")VALUES(object 499373,'','<<ModifiedTransactionType>> ~ <<DisplayNameClassifiedAd>>','<<BaseText>>','facebook','ClassifiedHomeAd','HomeAd',Object 81),(object 504709,' ','Book your free valuation today.','<<TransactionType>> by Douglas & Gordon ~ <<DisplayNameClassifiedAd>> Asking price œ<<AskingPrice>>','facebook','ClassifiedHomeAd','AgentAd',Object 81),(object 587022,'We need text','We need text','We need text ','facebook','ClassifiedHomeAd','AgentAd',Object 123285),(object 622924,'Vi „r lokala m„klare med kunskap och erfarenhet av ditt omr†de och troligtvis „ven din f”rening.','Kontakta mig, jag v„rderar g„rna din bostad.','Jag arbetar som din lokala m„klare i <<Home.Area.Name>>. Funderar du p† att s„lja din bostad? Kontakta mig redan idag.','facebook','ClassifiedHomeAd','AgentAd',Object 409190)
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR8001

[18:27:32, Critical, Starcounter (default)]
System.Exception: ScErrUnhandledException (SCERR1069): An unhandled exception was detected.
Version: 2.4.0.25.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR1069.
   at StarcounterInternal.Hosting.Processor.RunTaskNoScheduling(Action userAction, String appName) in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 121
   at Starcounter.DbSession.GetAndExecuteQueuedTasks(Action`2 taskExecutionMethod) in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Starcounter\DbSession.cs:line 180
   at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask) in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 168
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 81
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR1069
---> Starcounter.SqlException: ScErrConstraintViolationAbort (SCERR8001): A transaction was aborted because a constraint was violated.  The error near or at position -1.
In query: INSERT INTO "Starcounter"."Raw"."AdFenix"."Database"."Facebook"."LikeUpdate"(__id,"ClassifiedAd","Created","Delayed","FacebookProfile","Name")VALUES(object 362912,Object 67311,636142547401522919,False,Object 362911,NULL),(object 383052,Object 67311,636143429518840816,False,Object 383051,NULL),(object 400127,Object 67311,636144273911468109,False,Object 400126,NULL),(object 440356,Object 67311,636146017578711086,False,Object 440355,NULL),(object 440362,Object 78430,636146017607224031,False,Object 
Version: 2.4.0.25.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR8001.
   at Starcounter.SqlProcessor.SqlProcessor.ExecuteQuerySqlProcessor(String query) in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Starcounter\SqlProcessor\SqlProcessor.cs:line 205
   at Starcounter.Reload.<>c__DisplayClass15_0.<Load>b__3() in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Starcounter\Mock\Reload.cs:line 325
   at Starcounter.Reload.<>c__DisplayClass14_1`1.<DoParallelTransact>b__3() in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Starcounter\Mock\Reload.cs:line 302
   at Starcounter.Db.TransactAsync(Action action, UInt32 flags, TransactOptions opts) in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Starcounter\Db.cs:line 280
   at Starcounter.Db.Transact(Action action, UInt32 flags, TransactOptions opts) in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Starcounter\Db.cs:line 333
   at Starcounter.Internal.StarcounterEnvironment.RunWithinApplication(String desiredAppName, Action action) in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Starcounter.Internal\Mock\StarcounterEnvironment.cs:line 128
   at Starcounter.DbSession.<>c__DisplayClass6_0.<RunSync>b__0() in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Starcounter\DbSession.cs:line 261
   at Starcounter.Task.Run() in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Starcounter\DbSession.cs:line 100
ScErrorCode=8001
ErrorMessage= The error near or at position -1.
In query: INSERT INTO "Starcounter"."Raw"."AdFenix"."Database"."Facebook"."LikeUpdate"(__id,"ClassifiedAd","Created","Delayed","FacebookProfile","Name")VALUES(object 362912,Object 67311,636142547401522919,False,Object 362911,NULL),(object 383052,Object 67311,636143429518840816,False,Object 383051,NULL),(object 400127,Object 67311,636144273911468109,False,Object 400126,NULL),(object 440356,Object 67311,636146017578711086,False,Object 440355,NULL),(object 440362,Object 78430,636146017607224031,False,Object 
BeginPosition=-1
EndPosition=-1
Query=INSERT INTO "Starcounter"."Raw"."AdFenix"."Database"."Facebook"."LikeUpdate"(__id,"ClassifiedAd","Created","Delayed","FacebookProfile","Name")VALUES(object 362912,Object 67311,636142547401522919,False,Object 362911,NULL),(object 383052,Object 67311,636143429518840816,False,Object 383051,NULL),(object 400127,Object 67311,636144273911468109,False,Object 400126,NULL),(object 440356,Object 67311,636146017578711086,False,Object 440355,NULL),(object 440362,Object 78430,636146017607224031,False,Object 440361,NULL),(object 457191,Object 67311,636146862140987895,False,Object 457190,NULL),(object 457198,Object 78430,636146862170522641,False,Object 457195,NULL),(object 457200,Object 78430,636146862171079949,False,Object 457199,NULL),(object 496072,Object 67311,636147738786212778,False,Object 496071,NULL),(object 504944,Object 78430,636148143737747032,False,Object 504943,NULL),(object 595483,Object 67311,636149472363187656,False,Object 595482,NULL),(object 595500,Object 67311,636149658533524788,False,Object 595499,NULL),(object 1492170,Object 78430,636150326125603702,False,Object 1492167,NULL),(object 1744884,Object 404365,636150804333918373,False,Object 1744882,NULL),(object 1744886,Object 404365,636150804335161709,False,Object 1744885,NULL),(object 1744888,Object 404365,636150804336374875,False,Object 1744887,NULL),(object 2218324,Object 1735095,636150869250753251,False,Object 2218323,NULL),(object 2495948,Object 390824,636151192774528882,False,Object 2495947,NULL),(object 2495950,Object 390824,636151192775083639,False,Object 2495949,NULL),(object 2495966,Object 1735095,636151192854450469,False,Object 2495965,NULL),(object 2495968,Object 1735095,636151192855015054,False,Object 2495967,NULL)
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR8001

[18:27:32, Critical, Starcounter (default)]
System.Exception: ScErrUnhandledException (SCERR1069): An unhandled exception was detected.
Version: 2.4.0.25.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR1069.
   at StarcounterInternal.Hosting.Processor.RunTaskNoScheduling(Action userAction, String appName) in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 121
   at Starcounter.DbSession.GetAndExecuteQueuedTasks(Action`2 taskExecutionMethod) in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Starcounter\DbSession.cs:line 180
   at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask) in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 168
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 81
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR1069
---> Starcounter.SqlException: ScErrConstraintViolationAbort (SCERR8001): A transaction was aborted because a constraint was violated.  The error near or at position -1.
In query: INSERT INTO "Starcounter"."Raw"."AdFenix"."Database"."SoldCheckerAttribute"(__id,"Name","NotContains","PublicationOwner","StringToFind")VALUES(object 2208745,NULL,False,Object 81,'data-property-type="sold"'),(object 2208883,NULL,False,Object 81,'data-property-type="let"')
Version: 2.4.0.25.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR8001.
   at Starcounter.SqlProcessor.SqlProcessor.ExecuteQuerySqlProcessor(String query) in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Starcounter\SqlProcessor\SqlProcessor.cs:line 205
   at Starcounter.Reload.<>c__DisplayClass15_0.<Load>b__3() in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Starcounter\Mock\Reload.cs:line 325
   at Starcounter.Reload.<>c__DisplayClass14_1`1.<DoParallelTransact>b__3() in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Starcounter\Mock\Reload.cs:line 302
   at Starcounter.Db.TransactAsync(Action action, UInt32 flags, TransactOptions opts) in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Starcounter\Db.cs:line 280
   at Starcounter.Db.Transact(Action action, UInt32 flags, TransactOptions opts) in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Starcounter\Db.cs:line 333
   at Starcounter.Internal.StarcounterEnvironment.RunWithinApplication(String desiredAppName, Action action) in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Starcounter.Internal\Mock\StarcounterEnvironment.cs:line 128
   at Starcounter.DbSession.<>c__DisplayClass6_0.<RunSync>b__0() in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Starcounter\DbSession.cs:line 261
   at Starcounter.Task.Run() in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Starcounter\DbSession.cs:line 100
ScErrorCode=8001
ErrorMessage= The error near or at position -1.
In query: INSERT INTO "Starcounter"."Raw"."AdFenix"."Database"."SoldCheckerAttribute"(__id,"Name","NotContains","PublicationOwner","StringToFind")VALUES(object 2208745,NULL,False,Object 81,'data-property-type="sold"'),(object 2208883,NULL,False,Object 81,'data-property-type="let"')
BeginPosition=-1
EndPosition=-1
Query=INSERT INTO "Starcounter"."Raw"."AdFenix"."Database"."SoldCheckerAttribute"(__id,"Name","NotContains","PublicationOwner","StringToFind")VALUES(object 2208745,NULL,False,Object 81,'data-property-type="sold"'),(object 2208883,NULL,False,Object 81,'data-property-type="let"')
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR8001

[18:27:32, Critical, Starcounter (default)]
System.Exception: ScErrUnhandledException (SCERR1069): An unhandled exception was detected.
Version: 2.4.0.25.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR1069.
   at StarcounterInternal.Hosting.Processor.RunTaskNoScheduling(Action userAction, String appName) in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 121
   at Starcounter.DbSession.GetAndExecuteQueuedTasks(Action`2 taskExecutionMethod) in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Starcounter\DbSession.cs:line 180
   at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask) in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 168
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 81
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR1069
---> Starcounter.SqlException: ScErrConstraintViolationAbort (SCERR8001): A transaction was aborted because a constraint was violated.  The error near or at position -1.
In query: INSERT INTO "Starcounter"."Raw"."AdFenix"."Database"."Facebook"."LookAlikeCreation"(__id,"Campaign","CreateTime","Name","status")VALUES(object 43118,NULL,636131834195103577,NULL,False),(object 119880,NULL,636135161361354974,NULL,False),(object 326485,NULL,636141315066407005,NULL,False),(object 327508,NULL,636141321861519473,NULL,False),(object 331935,Object 331918,636141384300057494,NULL,False),(object 342288,Object 342282,636141951219782462,NULL,False),(object 411095,Object 411087,636144755801384757,NULL,False),(object 413479,Object 413469,636144808961416394,NULL,False),(object 733245,Object 733223,636149874255680142,NULL,False),(object 736660,Object 736599,636149876220765177,NULL,False),(object 2207118,Object 2206568,636150860081215672,NULL,False)
Version: 2.4.0.25.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR8001.
   at Starcounter.SqlProcessor.SqlProcessor.ExecuteQuerySqlProcessor(String query) in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Starcounter\SqlProcessor\SqlProcessor.cs:line 205
   at Starcounter.Reload.<>c__DisplayClass15_0.<Load>b__3() in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Starcounter\Mock\Reload.cs:line 325
   at Starcounter.Reload.<>c__DisplayClass14_1`1.<DoParallelTransact>b__3() in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Starcounter\Mock\Reload.cs:line 302
   at Starcounter.Db.TransactAsync(Action action, UInt32 flags, TransactOptions opts) in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Starcounter\Db.cs:line 280
   at Starcounter.Db.Transact(Action action, UInt32 flags, TransactOptions opts) in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Starcounter\Db.cs:line 333
   at Starcounter.Internal.StarcounterEnvironment.RunWithinApplication(String desiredAppName, Action action) in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Starcounter.Internal\Mock\StarcounterEnvironment.cs:line 128
   at Starcounter.DbSession.<>c__DisplayClass6_0.<RunSync>b__0() in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Starcounter\DbSession.cs:line 261
   at Starcounter.Task.Run() in C:\TeamCity\TeamCity10\buildAgent\work\sc-126\Level1\src\Starcounter\DbSession.cs:line 100
ScErrorCode=8001
ErrorMessage= The error near or at position -1.
In query: INSERT INTO "Starcounter"."Raw"."AdFenix"."Database"."Facebook"."LookAlikeCreation"(__id,"Campaign","CreateTime","Name","status")VALUES(object 43118,NULL,636131834195103577,NULL,False),(object 119880,NULL,636135161361354974,NULL,False),(object 326485,NULL,636141315066407005,NULL,False),(object 327508,NULL,636141321861519473,NULL,False),(object 331935,Object 331918,636141384300057494,NULL,False),(object 342288,Object 342282,636141951219782462,NULL,False),(object 411095,Object 411087,636144755801384757,NULL,False),(object 413479,Object 413469,636144808961416394,NULL,False),(object 733245,Object 733223,636149874255680142,NULL,False),(object 736660,Object 736599,636149876220765177,NULL,False),(object 2207118,Object 2206568,636150860081215672,NULL,False)
BeginPosition=-1
EndPosition=-1
Query=INSERT INTO "Starcounter"."Raw"."AdFenix"."Database"."Facebook"."LookAlikeCreation"(__id,"Campaign","CreateTime","Name","status")VALUES(object 43118,NULL,636131834195103577,NULL,False),(object 119880,NULL,636135161361354974,NULL,False),(object 326485,NULL,636141315066407005,NULL,False),(object 327508,NULL,636141321861519473,NULL,False),(object 331935,Object 331918,636141384300057494,NULL,False),(object 342288,Object 342282,636141951219782462,NULL,False),(object 411095,Object 411087,636144755801384757,NULL,False),(object 413479,Object 413469,636144808961416394,NULL,False),(object 733245,Object 733223,636149874255680142,NULL,False),(object 736660,Object 736599,636149876220765177,NULL,False),(object 2207118,Object 2206568,636150860081215672,NULL,False)
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR8001

**Comment by per-samuelsson** [comment]
Seem to me the problem here is this:

> Starcounter.SqlException: ScErrConstraintViolationAbort (SCERR8001): A transaction was aborted because a constraint was violated. The error near or at position -1. In query: INSERT INTO "Starcounter"."Raw"."AdFenix"."Database"."Ads"."AdFenix"."AdTemplate"(__id,"AdDescriptionTemplate","AdHeadlineTemplate","AdMessageTemplate","AdNetworkName","AttributeType","Name","PublicationOwner")VALUES(object 499373,'','<<ModifiedTransactionType>> ~ <<DisplayNameClassifiedAd>>','<<BaseText>>','facebook','ClassifiedHomeAd','HomeAd',Object 81),(object 504709,' ','Book your free valuation today.','<<TransactionType>> by Douglas & Gordon ~ <<DisplayNameClassifiedAd>> Asking price œ<<A Version: 2.4.0.25. Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR8001

@k-rus, is there any particular case in the reload that can cause this? Can it be that the database being reloaded into is already somewhat populated?

**Comment by per-samuelsson** [comment]
@MujahidRashid 

Probably suffering from the same thing as was discussed in #3964. And unfortunately, there is no simple answer. It's how the reload is designed - it's flawed (or almost useless) because it require you to load any code before you can successfully reload, and if you load user code, you can assure it does not create data. And if it does, the reload (often) fail.

**Comment by MujahidRashid** [comment]
Yes i tried this on 2.3 versions as well and got the same errors and because we cant reload on the newer versions we cannot migrate to new versions. Is there any other way to get the databases running in 2.2 to work on 2.4 other then reload i mean ?

**Comment by per-samuelsson** [comment]
>  Is there any other way to get the databases running in 2.2 to work on 2.4 other then reload i mean ?

At this point, I'm afraid there isn't. Other than manual doing some kind of export/import. But as soon as we realized just how flawy our migration routine (i.e. unload/reload) is, we kickstarted implementing a new tool that would overcome all the problems we know about. In fact, the idea we have right now is that the unload/reload as it is today will be deprecated as a whole, in favor of our new tool.

We have an ambition to be able to test this new tool within weeks. I don't dare to promise anything more exact than that. 

How does your need look right now? How long can you wait to get this to happen? We really want to help you guys get pass this.

**Comment by per-samuelsson** [comment]
cc @miyconst @ubbeK @dan31

**Comment by per-samuelsson** [comment]
@MujahidRashid 

I've raised the issue internally, trying to get you some more specifics. Good thing is that guys working on the new tool already are on the case being able to grab 2.2-dumps and initialize 2.4-databases with them, so it's "just" a matter of time now I guess.

Please let us know your timetable and if there is anything more we can do to help you at this point. I'll ask guys working on the tool to comment on this too.

**Comment by ubbeK** [comment]
@MujahidRashid 

I am currently working on a 2.2 migration dump tool which will generate a SQLite dump of a Starcounter database version 2.2.X. This dump may be reloaded into a Starcounter database version 2.4 with another tool called Stardump. The intention of Stardump is to be able to unload and reload a snapshot of any 2.4 Starcounter database or any future version of Starcounter. The first version of this tool has been implemented.

**Comment by MujahidRashid** [comment]
Thank you very much guys for your support.

**Comment by dan31** [comment]
Hi @MujahidRashid! In 2.3 which is now RC we are about to ship a proper tool for data migration. We will also provide a special 2.2 app to unload data from 2.2 in a format compatible with 2.3 data dump format. Once the tool is in distribution (about 1 week from now), we will let @atifwaqar and you know.

**Comment by MujahidRashid** [comment]
Hello @dan31 
Any updates regarding the migration tool ?

**Comment by miyconst** [comment]
Hello @MujahidRashid!

Sorry for the delay. The migration tool has been released in alpha version. Please read the following page - [Migrating from 2.2 to 2.4](https://starcounter.io/guides/tools/migrating-2-2-2-4/).

**Comment by ubbeK** [comment]
@MujahidRashid please note that the argument for the output file has just been changed from `--dump` to --file. So Release Candidate version 2.3.0.5456 and Develop version 2.4.0.429 still has that argument as `--dump`. Then builds from tomorrow will use the new one.
