### ISSUE TITLE
Decimal binding problems in JSON

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#4023]
Using Starcounter 2.3.0.5406

I have a decimal field in database:

```cs
public decimal Amount;
```

and a declaration like this in my JSON file:

```
"Amount$": 0.0
```

When I type a number with more than 6 digits after a decimal point (e.g. `1.2323432`), the application crashes with a not very informative exception:

> System.Exception: ScErrDataBindingForJsonException (SCERR14012): An exception occurred when a databinding for a property in json was used. Property 'Amount$' in 'PersonJson.Expenses.ExpenseJson'.
Version: 2.3.0.5406.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR14012.
   at lambda_method(Closure , Json , Decimal )
   at Starcounter.Templates.Property`1.BoundOrUnboundSet(Json parent, T value) in C:\TeamCity\BuildAgent\work\sc-669\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 48
   at Starcounter.Templates.Property`1.ProcessInput(Json parent, T value) in C:\TeamCity\BuildAgent\work\sc-669\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 295
   at Starcounter.XSON.DefaultPatchHandler.ParseAndProcess(TDecimal property, Json parent, String valueStr) in C:\TeamCity\BuildAgent\work\sc-669\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 87
   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\TeamCity\BuildAgent\work\sc-669\Level1\src\Starcounter\TransactionManager.cs:line 471
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-669\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 68
   at Starcounter.XSON.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, String value) in C:\TeamCity\BuildAgent\work\sc-669\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 38
   at Starcounter.XSON.JsonPatch.HandleOnePatch(Json root, JsonPatchOperation op, JsonPointer ptr, String value, Int32 patchCount, ChangeLog changeLog, Object sourceJson, Boolean strictRejection) in C:\TeamCity\BuildAgent\work\sc-669\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 537
   at Starcounter.XSON.JsonPatch.Apply(Json root, JsonTextReader reader, Boolean strictPatchRejection, Object sourceJson, Int32& patchCount) in C:\TeamCity\BuildAgent\work\sc-669\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 444
   at Starcounter.XSON.JsonPatch.Apply(Json root, String patch, Boolean strictPatchRejection, Int32& patchCount) in C:\TeamCity\BuildAgent\work\sc-669\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 367
   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(String bs, WebSocket ws) in C:\TeamCity\BuildAgent\work\sc-669\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 59
   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 managedHandlerId, UInt32 groupId, WebSocket ws) in C:\TeamCity\BuildAgent\work\sc-669\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 289
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\TeamCity\BuildAgent\work\sc-669\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 796
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR14012
---> Starcounter.DbException: ScErrCLRDecToX6DecRangeError (SCERR4246): The CLR Decimal cannot be converted to a Starcounter X6 decimal without data loss. Range error.
Version: 2.3.0.5406.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4246.
   at Starcounter.Internal.X6Decimal.ToRaw(Decimal value) in C:\TeamCity\BuildAgent\work\sc-669\Level1\src\Starcounter.Internal\X6Decimal.cs:line 105
   at Starcounter.Internal.DbState.WriteDecimal(UInt64 recordID, UInt64 recordAddr, Int32 columnIndex, Decimal value) in C:\TeamCity\BuildAgent\work\sc-669\Level1\src\Starcounter\Internal\DbState.cs:line 978
   at HelloWorld.Expense.set_Amount(Decimal value)
   at lambda_method(Closure , Json , Decimal )
ErrorCode=4246
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4246

What is the suggested way to proceed? I don't like my apps to crash when the user types an unsupported value. Any simple way to catch the exception?

**Comment by mtornwall** [comment]
Sounds like the underlying issue might be the one described in #3841.

**Comment by warpech** [comment]
Yeah, I think so. #3841 did not mention that direct binding in JSON also causes the crash. This is really bad.

Is it fixable? 

On the client side, we can add an explicit Custom Element to prohibit more than 6 digits after the decimal point in number inputs. We cannot do it on PuppetJs level, because there is no type metadata in JSON.

BTW. why is the information about the core problem hidden so deeply in the stack trace? I mean I see SCERR14012 on the surface, but it does not give me good information about the reason of the problem. SCERR4246 gives better information, but is buried in the stack trace.

**Comment by mtornwall** [comment]
Can't you just make the input handler truncate to six decimal places (if that's the appropriate action)?

**Comment by warpech** [comment]
Yeah, that's alternative version of:

> On the client side, we can add an explicit Custom Element to prohibit more than 6 digits after the decimal point in number inputs.

Your suggestion is more hacky but less verbose. Mine is more verbose but standards based. Always a tradeoff :)

----

Since it is server's limitation, perhaps it the server not the client who should handle it more gracefully? If I type `0.1234567`, the Typed JSON parser reverts it back to `0.123456` in the patch response.

**Comment by mtornwall** [comment]
> Since it is server's limitation, perhaps it the server not the client who should handle it more gracefully? If I type 0.1234567, the Typed JSON parser could revert it back to 0.123456 in the patch response.

Seconded. If you fix it on the server you only need to fix it once. Besides, the limitation is on the server side, so it seems like a natural choice.

**Comment by chrhol** [comment]
> > Since it is server's limitation, perhaps it the server not the client who should handle it more gracefully? If I type 0.1234567, the Typed JSON parser could revert it back to 0.123456 in the patch response.

> Seconded. If you fix it on the server you only need to fix it once. Besides, the limitation is on the server side, so it seems like a natural choice.

Alright, sounds like a good place, and a workaround until we get the underlying issue solved. 

> BTW. why is the information about the core problem hidden so deeply in the stack trace?

It's two separate exceptions. This sign `---> ` in the printed message denotes an inner exception. For a lot of exceptions in Starcounter, the inner one is the one that actually describes the cause and the outer one is a wrapper that adds a nice errorcode since inner ones does not always have an errorcode (for example nullreference exceptions or other unhandled exceptions).

**Comment by chrhol** [comment]
Should this be added to 2.3 or only develop? @warpech, @dan31

**Comment by warpech** [comment]
I don't think there is a big rush on this.

Is it a regression in 2.3 or was it always like that?

**Comment by chrhol** [comment]
> Is it a regression in 2.3 or was it always like that?

It's always been like this for 2.x versions (or at least since we changed format in database to X6Decimal). Decimal has never been used much which is why we never encountered this before.

Since this is a workaround and not a major bug, I think I will add it to develop only.

**Comment by chrhol** [comment]
Since the decision on todays meeting was that we should remove X6Decimal and support a wider type, I think I will not add this workaround. Since it's not a critical fix, it's better to wait for the proper solution.
