### ISSUE TITLE
Failed to create database

### ISSUE THREAD

**Issue by LimaPer** [Starcounter/Starcounter#4048]
Is this a known issue. First i deleted a database and then i created a new one with the same name and got the exception below. Havent seen this issue before when i have deleted/created a db. To solve the problem I ended up doing a complete reinstall with a later Starcounter version. 

ScErrServerCommandFailed (SCERR10011): The operation "Creating database wms" failed.
Version: 2.3.0.5489.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10011.

ScErrUnexpectedCommandException (SCERR10016): Creating database wms failed due to an unexpected problem.
Version: 2.3.0.5489.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10016.
System.IO.DirectoryNotFoundException: Could not find a part of the path.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at Starcounter.Server.DatabaseSetup.CreateFiles() in C:\TeamCity\BuildAgent\work\sc-1195\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseSetup.cs:line 124
   at Starcounter.Server.DatabaseSetup.CreateDatabase() in C:\TeamCity\BuildAgent\work\sc-1195\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseSetup.cs:line 134
   at Starcounter.Server.Commands.CreateDatabaseCommandProcessor.Execute() in C:\TeamCity\BuildAgent\work\sc-1195\Level1\src\Server\Starcounter.Server\Commands\Processors\CreateDatabaseCommandProcessor.cs:line 33
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\TeamCity\BuildAgent\work\sc-1195\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
HResult=-2147024893

**Comment by per-samuelsson** [comment]
@LimaPer 

Thanks for reporting this.

> Is this a known issue.

Not sure, but I don't think so. I do recall there was once some problem with deleting databases after it had installed applications from a warehouse, I'll see if I can find that old issue and see what the conclusion was in that case.

Let us get back to you.

**Comment by per-samuelsson** [comment]
@LimaPer 

It turned out it actually was already reported and confirmed: #3523. It was just never prioritized to fix I guess. I'll make sure we bump that and get it fixed.

Meanwhile, I think that other issue can give you a hint on what can be done as a workaround if it should happen again. Let us know if you need help with a better explanation for that! Please do so in that issue, if so.

Closing this as a dup of #3523.

**Comment by chrhol** [comment]
Huh, it was reported by me...I had no memory of that one what so ever! Good that you found it.
