### ISSUE TITLE
Setting StringValue of an item from an empty array crashes database

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#4056]
Coming from - [Starcounter throws System.ArgumentOutOfRangeException when primitive array in view-model contains strings and ints](https://github.com/Starcounter/Starcounter/issues/4055).

I am trying to workaround the issue above.

```json
{
    "Items": [ [] ]
}
```

```cs
public void RefreshItems()
{
    foreach (var item in this.SelectItems())
    {
        var json = this.Items.Add();
        
        json.Add().StringValue = item.Name;
        json.Add().IntegerValue= item.Count;
    }
}
```

This throws the following exception and crashes database.

```
"System.Exception: ScErrUnhandledException (SCERR1069): An unhandled exception was detected.
Version: 2.3.0.5523.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR1069.
   at StarcounterInternal.Hosting.Processor.RunTaskNoScheduling(Action userAction, String appName) in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 121
   at Starcounter.DbSession.GetAndExecuteQueuedTasks(Action`2 taskExecutionMethod) in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Starcounter\DbSession.cs:line 180
   at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask) in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 168
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 81
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR1069
---> System.InvalidOperationException: This instance does not have a string value.
   at Starcounter.Json.set_StringValue(String value) in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Starcounter.XSON\Class Json\Json.Object.GetSetValue.cs:line 366
   at SyncEngine.Configurator.DemoPage.RefreshStatistics() in D:\GitHub\Starcounter\SyncEngine\src\SyncEngine.Configurator\ViewModels\DemoPage.json.cs:line 63
   at SyncEngine.Configurator.DemoPage.<>c__DisplayClass5_1.<StartRefreshTimer>b__2() in D:\GitHub\Starcounter\SyncEngine\src\SyncEngine.Configurator\ViewModels\DemoPage.json.cs:line 114
   at Starcounter.Internal.StarcounterEnvironment.RunWithinApplication(String desiredAppName, Action action) in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Starcounter.Internal\Mock\StarcounterEnvironment.cs:line 128
   at SyncEngine.Configurator.DemoPage.<>c__DisplayClass5_0.<StartRefreshTimer>b__1(Session s, String id) in D:\GitHub\Starcounter\SyncEngine\src\SyncEngine.Configurator\ViewModels\DemoPage.json.cs:line 98
   at Starcounter.Session.Use(SessionTask action, String sessionId) in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Starcounter.XSON\Sessions\Session.cs:line 742
   at Starcounter.DbSession.<>c__DisplayClass6_0.<RunSync>b__0() in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Starcounter\DbSession.cs:line 261
   at Starcounter.Task.Run() in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Starcounter\DbSession.cs:line 100
HResult=-2146233079
"
```

**Comment by chrhol** [comment]
Thank you for reporting this. Unfortunately the dynamic parts doesn't seem to work at all when it comes to using single values. 

The workaround for now (until we fix it) is to manually specify the template to use for each new item. 

```csharp
foreach (var item in this.SelectItems())
    {
        var json = this.Items.Add();
        
        Json innerJson = json.Add();
        innerJson.Template = new TString();
        innerJson.StringValue = item.Name; 
        
        innerJson = json.Add();
        innerJson.Template = new TLong();
        innerJson.IntegerValue = item.Count; 
   }
```

There is an older issue to review and fix the current syntax, #2720. I make sure this problem is also included.

**Comment by chrhol** [comment]
I've pushed a fix for this to both `v2.3` and `v2.4`.

The syntax in the example in the first comment should now work fine, and setting the template manually should not be needed anymore.

**Comment by miyconst** [comment]
It looks like the `v2.3` build has failed and I can't check it today.

**Comment by chrhol** [comment]
I will consider this issue and close it. @miyconst please reopen it, if you find anything that still doesn't work with this.

**Comment by miyconst** [comment]
@chrhol thanks for fixing. I have just tested, it works.
