### ISSUE TITLE
ScErrJsonValueWrongType in 2.3.0.5523

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#4060]
When reviewing a new live environment, this error was noted twice in the log. Things kept working, just thought we might want to have it reported.

```
System.FormatException: ScErrJsonValueWrongType (SCERR14004): The value does not correspond to the template property type. Property="UniqueID (String)", Value=10777542
Version: 2.3.0.5523.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR14004.
  at Starcounter.XSON.ExceptionHelper.ThrowWrongValueType(Exception innerException, String name, String type, String value) in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Starcounter.XSON\ExceptionHelper.cs:line 17
  at Starcounter.XSON.NewtonSoftSerializer.DeserializeString(Json json, Template template, JsonTextReader reader, JsonSerializerSettings settings) in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Starcounter.XSON\Serializer\NewtonSoftSerializer.cs:line 392
  at Starcounter.XSON.NewtonSoftSerializer.DeserializeObject(Json json, Template template, JsonTextReader reader, JsonSerializerSettings settings) in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Starcounter.XSON\Serializer\NewtonSoftSerializer.cs:line 433
  at Starcounter.XSON.NewtonSoftSerializer.Deserialize(Json json, TextReader textReader, JsonSerializerSettings settings) in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Starcounter.XSON\Serializer\NewtonSoftSerializer.cs:line 123
  at Starcounter.Rest.UriManagedHandlersCodegen.ReadMessageParam(Request req) in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 215
  at lambda_method(Closure , Request , IntPtr , IntPtr )
  at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
  at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
```

@chrhol any ideas?

cc @atifwaqar

**Comment by chrhol** [comment]
It looks like some value is specified as string in JsonByExample, but the incoming value when deserializing is a number (integer in this case). 

Currently this is treated as an error, since it's not a valid string in json. But maybe we need to be more allowing for these cases.

**Comment by chrhol** [comment]
The change needed to allow this is quite small. Added an issue for implementing this change: #4062.

I will close this issue since the original question is answered.

**Comment by per-samuelsson** [comment]
> The change needed to allow this is quite small. Added an issue for implementing this change: #4062.

Great. If we treat it as a bug, we might want to have it in 2.3 already.

cc @atifwaqar, make sure you follow that to see when it get realized.

**Comment by Ripipip** [comment]
I investigated the other issue we had the ScErrJsonValueWrongType issue. That was actually quite obvious, just that we didn't have time to look at it in the confusion. In SC 2.2 you could send an integer where the typed json expected a string. The integer would just convert to a string. In SC 2.3 you need to send an integer or the request is not accepted.

**Comment by Ripipip** [comment]
A suggested improvement would be to have either a reference to the typed json or the file in the error message - then it easier for everyone to identify not only the code error but the acutal use case that caused it.

**Comment by chrhol** [comment]
> I investigated the other issue we had the ScErrJsonValueWrongType issue. That was actually quite obvious, just that we didn't have time to look at it in the confusion. In SC 2.2 you could send an integer where the typed json expected a string. 

Yeah, the serializer/parser in 2.2 was a bit more forgiving. But I will readd that functionality. I have most bits in place for #4062 and then the behaviour will be back like before. I'm aiming at getting it pushed today so you have it in a 2.3 version tomorrow.

> A suggested improvement would be to have either a reference to the typed json or the file in which the handler is located in the error message - then it easier for everyone to identify not only the code error but the acutal use case that caused it.

Good suggestion 👍 I think at least adding which typedjson it belongs to will be possible, not sure about the handler. I will take a look on how to improve it.
