### ISSUE TITLE
ScErrThreadNotAttached in Db.Transact

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#4090]
Hey!
Starcounter-RC-2.3.0.5501 (12 jan 2017 02:01:14) 

Got this strange error reading a database field from in an attached thread. At least it should be attached:
![image](https://cloud.githubusercontent.com/assets/4263597/22878081/92a0209a-f1d8-11e6-8386-0fc59a617532.png)

I don't have a session, but ThreadData.Current in the image above seems to indicate that I'm attached. 
I just remembered asking a question about checking if attached #3895 
````Starcounter.Internal.StarcounterEnvironment.IsOnScheduler()```` returns true

**Comment by careri** [comment]
I'm using:
````cs
Session.RunSync
````

Is that the problem, maybe I need to switch to Scheduling.ScheduleTask?

**Comment by bigwad** [comment]
Indeed, looks strange. Is it reproducible?

**Comment by careri** [comment]
Thinking it might be debugger related, an evaluation of a field in the local/watch view fails and messes up the session. 
I don't get any good logs though

**Comment by miyconst** [comment]
I had a similar situation when calling async delay in handler wrapped with a long running transaction.

```cs
await System.Threading.Tasks.Task.Delay(1000);
```

**Comment by careri** [comment]
Got it again, this time the sccode.exe crasched.
````
System.Exception: ScErrThreadNotAttached (SCERR1004): The operation failed because the current thread wasn't attached to the scheduler.

Version: 2.3.0.5501.

Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR1004.

   at Starcounter.ThreadData.GetContextHandleExcept() in C:\TeamCity\BuildAgent\work\sc-1271\Level1\src\Starcounter\Internal\ThreadData.cs:line 70

   at Starcounter.Internal.TransactionManager.SetCurrentTransaction(TransactionHandle handle) in C:\TeamCity\BuildAgent\work\sc-1271\Level1\src\Starcounter\TransactionManager.cs:line 352

   at Starcounter.Internal.TransactionManager.Cleanup() in C:\TeamCity\BuildAgent\work\sc-1271\Level1\src\Starcounter\TransactionManager.cs:line 382

   at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask) in C:\TeamCity\BuildAgent\work\sc-1271\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 187

   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\BuildAgent\work\sc-1271\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 81

HResult=-2146233088

HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR1004
````

I was stepping in the debugger, might be that I paused the thread to long in the debugger?
