### ISSUE TITLE
No compatibility check in Starcounter for 2.3 for breaking changes; error message not comprehendable

### ISSUE THREAD

**Issue by dan31** [Starcounter/Starcounter#4119]
Related:
https://github.com/Starcounter/Starcounter/issues/3743
https://github.com/Starcounter/Starcounter/issues/3843
https://github.com/Starcounter/StarDump/issues/36
Wednesday, March 1, a breaking change was introduced to 2.3 RC (in metadata) on the way to a release, in order to support vacuum. It appears that currently there is no mechanism in Starcounter components and management facilities for understanding incompatibility of versions in 2.3. With this being said, uninstalling build 5767 and installing 5816, running program afterwards gives me this:

![image](https://cloud.githubusercontent.com/assets/7162535/23578211/bfc12364-00d1-11e7-8a23-3ca1ba394460.png)

From this, no customer would understand what is going on. This is currently a showstopper: because of this, now I have to go to every single user of Starcounter and kindly ask to reload database in order to move forward with releases. However, it is close to impossible to do this promptly, thus I expect a big flow of questions with similar reports in the next few days from our users. (There is another question why one should reload whole database just to get adopted to a small change in metalayer, but we leave it for next talks).

@andwah has removed a workaround where such check for incompatibility was done in the installer previously and only for the kernel itself. This is a workaround since, if I disagree with the installer or not pay attention to what it says, I will still run new Starcounter on database of the old format and likely get incomprehensible errors.

What is more scary, I can actually run a database right now. I firmly think this should not be possible however, as the database being run does not have all the new added and thus needed metadata. Please tell me if I am thinking incorrectly.

The check for incompatibility should not be workaround-ed in the installer, this should be a native part of Starcounter instead: versions in the kernel, metalayer and other components involved should be bumped on any incompatible change, on them being bumped it becomes possible to take the old image, compare version to the one installed, and emit a nice message instructing the user what to do. Very-very likely version info should become part of metadata too (but, as being said, I am not telling how to implement it; I am only suggesting the ideas). Installer, being produced for the recent version, will be able to also perform such check, relying on the same function for checking: it only needs to keep the previous version of Starcounter around, and then it can instruct the user early on by calling to ```staradmin``` or related management utility, which will look at the previously installed Starcounter and will say: "my friend, the previous version is not compatible, you'll need to undertake the migration procedure; here are the links for the tools and instructions, feel free to post questions there".

Since I don't see how there is any single person who can implement this (the topic goes through whole Starcounter), and since this thing is not present yet, in the assignees there are all people involved into this story. So let's start by sharing ideas: how we should implement this? Apparently there is some cascading involved: ```star``` should be able to catch some error response from one of other Starcounter parts which knows that what is being now attempted to be started is not compatible anymore + provide a log message with instructions to the caller.

I kindly remind this is a showstopper.

**Comment by dan31** [comment]
There is also trace of work regarding the versioning: https://github.com/Starcounter/CompanyTrack/issues/290. It is hard to say whether this work is forgotten/abandoned/... .

**Comment by per-samuelsson** [comment]
Just to make things even clearer, can we get an idea of what exactly the breaking change was? 

I wonder if one thing to do is to somehow try to list what *kind* of changes are breaking, like

* Changing of public APIs exposed to application developers
* Changing of public APIs exposed by Bluestar (to more "outer" bits)
* Binary changes in metadata
* Binary changes in storage
* Etc ...

With that, we could formulate some strategy that cover where we need to get busy implementing checks and how it should be done.

**Comment by dan31** [comment]
In respect to this issue, I have one question. Is not it a very common sense that the party introducing changes should be in control of verifying compliance to this changes? E.g., metalayer has added a breaking change: now it is metalayer implementing such version checking function that refuses to start database of a particular previous version that is not compatible with the current implementation anymore; advsing user on an action. If now boostraper tries to start, it will get/catch this from the metalayer. Hierarchy of checks in the end: the same for kernel and everything else. This makes things scalable and reliable. But so far, what I read up and what has developed in there https://github.com/Starcounter/CompanyTrack/issues/290, it appears that somehow by ones expectation this is the installer which is expected to provide such verification for other components. Which is, I think, a very faulty approach.

**Comment by per-samuelsson** [comment]
> I have one question. Is not it a very common sense that the party introducing changes should be in control of verifying compliance to this changes?

I would think so too, yes. Just throwing everything on the installer seem like a bad idea. 

If I introduce some change in some module, that I know is incompatible with a previous version (one still considered "alive" o/c, meaning it's in use), I need to spend time thinking about the *whole story*, not just that my change pass some tests in isolation.

WTBS, it's not sure I can correctly address everything. That's in order. But the least I must make sure is

1. I can safely spot the condition, and **leave data/code in a consistent state**
2. I can report to consumers about the condition in a predicable way, normally using a specific error code. With that code (and/or message), consuming code can take appropriate action.

**Comment by dan31** [comment]
@per-samuelsson I deeply appreciate your will to address this on your own. I believe it is important to involve owners of the parts that do introduce breaking changes time to time, which are currently: metalayer, kernel. There is already initial work being done to introduce version functions: https://github.com/Starcounter/CompanyTrack/issues/290, in hope installer will deal with it. There @alemoi asked other parties to introduce those. Version functions are not enough to address the subject in uniform way.

First we all need to come to an agreement that it is not an installer which should deal with such fail-out logic on incompatibility, nor that is any other special place that deals with it. Instead, it is a cascade of checks that span everything which deal or might deal with it. Then the main question to this story would be: how would you (@per-samuelsson) receive the active feedback from underlying parties that you touch when starting; and how those parties will verify the versioning, where would they get it from (might well be — from metadata? it also might be a file on disk too).

**Comment by per-samuelsson** [comment]
> Version functions are not enough to address the subject in uniform way.

Of course not. Like I wrote, those that introduce breaking changes will always know best what was broken, and have to consider the bigger picture for the relevant change. The minimum required when introducing such change is [1] and [2] from my comment above.

**Comment by per-samuelsson** [comment]
> Then the main question to this story would be: how would you (@per-samuelsson) receive the active feedback from underlying parties that you touch when starting; and how those parties will verify the versioning, **where would they get it from (might well be — from metadata? it also might be a file on disk too)**.

That would depend on the context, wouldn't it. As an example, if a breaking change is introduced in binary storage format, then the corresponding strategy has to be considered there. And returning a clear and precise error when incompatible (i.e. "old") data is detected.

**Comment by per-samuelsson** [comment]
@dan31, regarding this:

>  This is currently a showstopper: because of this, now I have to go to every single user of Starcounter and kindly ask to reload database in order to move forward with releases. However, it is close to impossible to do this promptly, thus I expect a big flow of questions with similar reports in the next few days from our users.

Would this

1. Revert the breaking change (I mean, after all, breaking changes in a RC is something we really should try everything to avoid).
2. Delete any version built with said change from our download page.

be possible?

Then maybe we don't have to put all users through this same pain.

**Comment by dan31** [comment]
@per-samuelsson "Revert the breaking change (I mean, after all, breaking changes in a RC is something we really should try everything to avoid)." — I can definitely say no: the breaking change is purposeful and its aim is to remove long-standing bug of non-ability to get rid of deleted data inside the database rather than by re-creating database (for most customers this is no-go, to be more precise). Hence, this breaking change is to support vacuum. No vacuum in 2.3 means that this either goes to 2.4 (too long), and since it is too long, in the end we introduce such change in 2.3.x, which isn't an option either. The best time is about right now, while customers still undertake migration and still more eager to adopt to such changes. Short story put: such problems only have one way forward — to be fixed asap, not to be wrapped into something acceptable.

**Comment by per-samuelsson** [comment]
> Hence, this breaking change is to support vacuum.

@dan31, I hear what you are saying. I just have a hard time understanding why we need a breaking change to accomplish that, and that there is really no other way to introduce support for vacuuming without forcing users to undergo a database rebuild (unload/reload).

I probably just don't get the implementation good enough.

But sure, vacuum in 2.3 is a necessity, I understand that. But then exactly what are we chasing here - I mean short term? 

Long term, we want to improve on how we surface error conditions caused by breaking changes (in any form), but to accomplish that, there is no quick fix. Most importantly, it's about increasing responsibility of anyone pushing something to any branch that is in production - really ensuring that everytime that is done, the responsible person for introducing the breaking change must also have a waterproof solution to how that change will hit the consuming app-developer.

Short term, the only somewhat simple and *general* approach I can see to these kind of problems when looking at them all at once, is to introduce some high-level version on the database (or database configuration) level. That is

1. When you create a new database, we tag that with the version of the installed distribution, including major.minor.build - the full identity.
2. When we load a database into memory, we compare the number with the current version. If there is any kind of mismatch, we refuse to go further and force users to rebuild the database.

It's not convenient for our users, for sure. But until we have formulated a strategy and implemented a way to make sure everyone really *care* about the topic of being backwards-compatible (in RC+-versions), I can't see any other possible approach to tackle this in a way general enough to support each case.

As one relaxation, I guess we could support a way for users to forcefully - and very explicitly - bypass the whole thing, by means of updating the database version tag, and allow an "old" version to load. But then it's on their own judgement. That way, we could advice our partner-like customers what versions we *know* are compatible, and where that approach would work. The experience could could be something like:

```cmd
staradmin upgrade db

You are upgrading the database "default" from 2.3.12345 to 2.3.123567 
without rebuilding it. Do this only if you KNOW those versions are
compatible. The safest option is to issue a rebuild.

Type "rebuild" to let us instead rebuild the database to 2.3.123567.
Type "upgrade" to perform the upgrade without rebuilding.
Press ENTER to cancel.

```

**Comment by dan31** [comment]
@per-samuelsson It is an addition info field in metalayer (@k-rus can explain more). Really maybe there is a way to not treat it as a breaking change, but instead, on load, implement a versioning logic in the metalayer and adopt to this change instead. This will be even more plausible solution. But only @k-rus can judge whether there is such way.

**Comment by per-samuelsson** [comment]
> Really maybe there is a way to not treat it as a breaking change, but instead, on load, implement a versioning logic in the metalayer which will adopt to this change instead.

That's why I asked this earlier:

> Just to make things even clearer, can we get an idea of what exactly the breaking change was?

I might be wrong, but my experience is that it's often possible to introduce changes without having them to be breaking, just that it takes some more time and thinking.

**Comment by per-samuelsson** [comment]
Expanding on my proposal from yesterday on a short term validation scheme based on tagging each database with a version: 

If we can get some predicable versioning going on, so that when any change go into the main-track of a RC+ version, me as a developer can somehow easily note if what I now push is breaking or not, things will be more relaxed for the developer.

Like: I'm pushing patch(es) `p`. I know `p` is *not* breaking, hence not requiring a database rebuild. Then I can explicitly say so, and the next time a new version is to be built and published, the distribution contains that knowledge, knowing that it should be fine to load any database without prompting the user for a rebuild.

(The opposite scheme - forcing instead tagging *when* a change is breaking - is of course also possible, and easier. But then if someone forget, trouble will hit our users).

**Comment by k-rus** [comment]
This issue was known for long time and was brought few times, but it was ignored. It is very unfortunate that such issues only become important when they hit our customers.

It was decided to implement the check in the installer. This would prevent the most of our users from hitting incapability problem, since they would deal with it at installation time. It is important that the installer does the check, since it will provide opportunity for users to unload their databases before they replaced old binaries with new binaries, which cannot run the databases.

Obviously, fixing just installer is not enough, since there will be cases, which cannot be covered in this way. Before I read the issue I made suggestion in https://github.com/Starcounter/RebelsLounge/issues/86

Above @per-samuelsson suggests to use major.minor.build version, but such numbers can be generated at commit or build time, thus metalayer cannot really utilise it. However, adding this values to database configuration file can allow to produce more meaningful error message than using internal metalayer or kernel version numbers. Internal metaschema version says nothing to user, while version of the build allows our users to know, which binary of Starcounter to use for unload.

I am not in favour of putting description of error resolution into error message. First of all, the message becomes too big. Second, there are usually several ways of resolving an error. The resolutions can be different in different situations and known resolutions might not be suitable for some new case.

I don't think we can just rely on components owners that they properly handle breaking changes. It might be missed and breaking change will not be bumped. To reduce such risk we need to automate test of trying to start database and applications created with old Starcounter version on new build of Starcounter. And have such test in, e.g., nightly regression.

Avoiding breaking change or resolving incapability internally without user interaction is currently impossible in metalayer. We looked into this issue, when metalayer initialisation was designed, and found that it is too complex to do. Furthermore, we don't see how it can be done reliably, which means we cannot guarantee correctness. We might look into this issue again, but it is expected to require considerable amount of time.

**Comment by dan31** [comment]
@bigwad @per-samuelsson 
Currently we have some people trying to move from 2.2 to 2.3, but not using 2.2 really. We did not instruct them to manually do unload/reload and wipe the old images. As a result, the error message when running 2.3 after de-installing 2.2 is not comprehendable:

![image](https://cloud.githubusercontent.com/assets/7162535/23975553/bc29a01e-09e1-11e7-9621-be7a62cb306c.png)

In that case, of course, manual deletion of the image file was not performed — I only asked active 2.x users to look into that. So, last release planning we explicitly mentioned that the kernel check for image incompatibility is there for ages. Let is be so, but the result of this check is currently not useful and the final state is not comprehendable. We need to address this really systematically, together with metalayer. As been said before:

> I believe it is important to involve owners of the parts that do introduce breaking changes time to time, which are currently: metalayer, kernel.

Apparently, both should not only panic when incompatibility is detected, but provide a meaningful, pleasant and easy to understand error message which the outer components carefully carry towards the user. Currently the behavior is offensive to the user: even though we have such check in the kernel for ages, we don't care about the user knowing of its results. We all should care.

**Comment by per-samuelsson** [comment]
I don't want to be harsh, but re-stating that "something have to be done" and that "everyone will need to help out" will not get us far.

What we need is

1. Some proposals: what options to we have?
2. Very explicit instructions what versions should include these compatibility checks
    * 1.x -> 2.2?
    * 2.2 -> 2.3?
    * 2.3 -> 2.4?
    * 2.4 -> 3.x?
3. Forcing everybody that should be involved to drop everything else they are busy with and get started.

It's actually not much harder than that.

As for [1], I already proposed one approach that is quite general: https://github.com/Starcounter/Starcounter/issues/4119#issuecomment-284233516

As for [2] and [3], I guess you @dan31 has to take those decisions. Regarding [2], if you want my advice, I'd say "2.3 and up".

**Comment by per-samuelsson** [comment]
Question about schema version numbers here: https://github.com/Starcounter/CompanyTrack/issues/290#issuecomment-287026826.

**Comment by per-samuelsson** [comment]
I will setup a test for this, following this info:

> With this being said, uninstalling build 5767 and installing 5816, running program afterwards gives me this.

1. Install 5767. Create and run an application.
2. Update to 5816. Start the application.

Let me know if that is wrong.

**Comment by per-samuelsson** [comment]
I've now simulated the exact case, using said approach. Summary:

* Metadata APIs is the cause to crashing the code host.
* Metadata API provide no specific error code.
* Web administrator handle this correctly if starting the app from there. 
* Using `star.exe`, you also get the "correct" error (i.e. the correct one as in "the one produced by metalayer", but that error is giving no one no help whatsoever).

Here's the more detailed version:

When the code host start, it calls some method `PopulateRuntimeMetadata()`. This method raise an exception. The exception has the error code 8001, meaning it's a constraint violation in a commit.

```
"Starcounter.ConstraintViolationException: ScErrConstraintViolationAbort (SCERR8001): A transaction was aborted because a constraint was violated.
Version: 2.3.0.5851.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR8001.
   at Starcounter.Internal.TransactionManager.Commit(UInt64 handle, Int32 free) in C:\TeamCity\BuildAgent\work\sc-3291\Level1\src\Starcounter\TransactionManager.cs:line 724
   at Starcounter.Internal.TransactionManager.<>c__DisplayClass50_0.<Commit>b__0() in C:\TeamCity\BuildAgent\work\sc-3291\Level1\src\Starcounter\TransactionManager.cs:line 667
   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\TeamCity\BuildAgent\work\sc-3291\Level1\src\Starcounter\TransactionManager.cs:line 551
   at Starcounter.Internal.TransactionManager.Commit(TransactionHandle handle) in C:\TeamCity\BuildAgent\work\sc-3291\Level1\src\Starcounter\TransactionManager.cs:line 678
   at Starcounter.SqlProcessor.SqlProcessor.<>c__DisplayClass40_1.<run_continuations>b__0() in C:\TeamCity\BuildAgent\work\sc-3291\Level1\src\Starcounter\SqlProcessor\SqlProcessor.cs:line 244
   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\TeamCity\BuildAgent\work\sc-3291\Level1\src\Starcounter\TransactionManager.cs:line 551
   at Starcounter.Transaction.Scope(Action action) in C:\TeamCity\BuildAgent\work\sc-3291\Level1\src\Starcounter\Transaction.cs:line 224
   at Starcounter.SqlProcessor.SqlProcessor.run_continuations(continuation cont) in C:\TeamCity\BuildAgent\work\sc-3291\Level1\src\Starcounter\SqlProcessor\SqlProcessor.cs:line 237
   at Starcounter.SqlProcessor.SqlProcessor.run_continuations(continuation cont) in C:\TeamCity\BuildAgent\work\sc-3291\Level1\src\Starcounter\SqlProcessor\SqlProcessor.cs:line 262
   at Starcounter.SqlProcessor.SqlProcessor.run_continuations(continuation cont) in C:\TeamCity\BuildAgent\work\sc-3291\Level1\src\Starcounter\SqlProcessor\SqlProcessor.cs:line 262
   at Starcounter.SqlProcessor.SqlProcessor.run_continuations(continuation cont) in C:\TeamCity\BuildAgent\work\sc-3291\Level1\src\Starcounter\SqlProcessor\SqlProcessor.cs:line 262
   at Starcounter.SqlProcessor.SqlProcessor.run_continuations(continuation cont) in C:\TeamCity\BuildAgent\work\sc-3291\Level1\src\Starcounter\SqlProcessor\SqlProcessor.cs:line 262
   at Starcounter.SqlProcessor.SqlProcessor.run_continuations(continuation cont) in C:\TeamCity\BuildAgent\work\sc-3291\Level1\src\Starcounter\SqlProcessor\SqlProcessor.cs:line 262
   at Starcounter.SqlProcessor.SqlProcessor.run_continuations(continuation cont) in C:\TeamCity\BuildAgent\work\sc-3291\Level1\src\Starcounter\SqlProcessor\SqlProcessor.cs:line 262
   at Starcounter.SqlProcessor.SqlProcessor.run_continuations(continuation cont) in C:\TeamCity\BuildAgent\work\sc-3291\Level1\src\Starcounter\SqlProcessor\SqlProcessor.cs:line 262
   at Starcounter.SqlProcessor.SqlProcessor.run_continuations(continuation cont) in C:\TeamCity\BuildAgent\work\sc-3291\Level1\src\Starcounter\SqlProcessor\SqlProcessor.cs:line 262
   at Starcounter.SqlProcessor.SqlProcessor.run_continuations(continuation cont) in C:\TeamCity\BuildAgent\work\sc-3291\Level1\src\Starcounter\SqlProcessor\SqlProcessor.cs:line 262
   at Starcounter.SqlProcessor.SqlProcessor.PopulateRuntimeMetadata() in C:\TeamCity\BuildAgent\work\sc-3291\Level1\src\Starcounter\SqlProcessor\SqlProcessor.cs:line 268
   at Starcounter.Hosting.StarcounterPackage.UpdateDatabaseSchemaAndRegisterTypes(String fullAppId, TypeDef[] unregisteredTypeDefs, TypeDef[] allTypeDefs) in C:\TeamCity\BuildAgent\work\sc-3291\Level1\src\Hosting\Starcounter.Hosting\StarcounterPackage.cs:line 43
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application, ApplicationDirectory applicationDir) in C:\TeamCity\BuildAgent\work\sc-3291\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 265
   at Starcounter.Hosting.Package.Process() in C:\TeamCity\BuildAgent\work\sc-3291\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 138
   at Starcounter.Hosting.Package.Process(IntPtr hPackage) in C:\TeamCity\BuildAgent\work\sc-3291\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 55
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\BuildAgent\work\sc-3291\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 85
ErrorCode=8001
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR8001
"
```

This error, the code host capture and write as being critical to the server log, before exiting, using that error as the exit code. What else could it do?

If the code host was started on demand from starting the application from web administrator, I get an error there saying the application could not be started and this:

![image](https://cloud.githubusercontent.com/assets/2902045/24002375/d879026c-0a60-11e7-8a21-9ae24748c665.png)

If I start from `star.exe`, it looks like this:

![image](https://cloud.githubusercontent.com/assets/2902045/24002546/51f58b9c-0a61-11e7-98b6-1a358691179b.png)
