### ISSUE TITLE
Starcounter.Logging throws External component has thrown an exception with no further explanation

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#4121]
I have left my database with apps running over the night, and one of the databases crashed with the following exception in the logs. The database itself is still in the "Running" state, but all of it's apps stopped.

```
Starcounter-RC-2.3.0.5799 (Mar 2, 2017 7:22:52 PM)
```

```
"System.Runtime.InteropServices.SEHException: External component has thrown an exception.
   at System.Diagnostics.StackTrace.GetStackFramesInternal(StackFrameHelper sfh, Int32 iSkip, Exception e)
   at System.Diagnostics.StackTrace.CaptureStackTrace(Int32 iSkip, Boolean fNeedFileInfo, Thread targetThread, Exception e)
   at System.Diagnostics.StackTrace..ctor(Exception e, Boolean fNeedFileInfo)
   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Exception.GetStackTrace(Boolean needFileInfo)
   at System.Exception.ToString(Boolean needFileLineInfo, Boolean needMessage)
   at Starcounter.Logging.ExceptionFormatter.ExceptionToString(Exception exception) in C:\TeamCity\BuildAgent\work\sc-3159\Level1\src\Starcounter.Logging\ExceptionFormatter.cs:line 55
   at StarcounterInternal.Hosting.ExceptionManager.HandleUnhandledException(Exception ex) in C:\TeamCity\BuildAgent\work\sc-3159\Level1\src\Hosting\Starcounter.Hosting\ExceptionManager.cs:line 37
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\BuildAgent\work\sc-3159\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 99
ErrorCode=-2147467259
HResult=-2147467259
"
```

The Windows log has the following entry at the same time:

```
Application: github.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OutOfMemoryException
   at GitHub.AppStartup.PreStartupSequence.ExtractNativeBinaries()
   at GitHub.App..ctor()
   at GitHub.App.Main()
```

Could it be related to the insufficient amount of RAM?

@alemoi, @k-rus, @chrhol, @bigwad, @per-samuelsson, sorry for cc every one of you, I just really don't know who can help here.

**Comment by per-samuelsson** [comment]
> Application: github.exe

Huh? What's that?

> Could it be related to the insufficient amount of RAM?

Sure looks so, given:

> System.OutOfMemoryException

**Comment by miyconst** [comment]
>Huh? What's that?

It is a Windows desktop app fro GitHub access. The Windows log does not contain any entries from Starcounter or `sccode.exe`.

**Comment by k-rus** [comment]
I guess crash dump will be useful. See https://github.com/Starcounter/Starcounter/issues/3297#issuecomment-174574035

**Comment by miyconst** [comment]
Thanks @k-rus, I have enabled the dumps, and will see how it works out.
