### ISSUE TITLE
Exception in SC Admin Logs

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#4124]
SC Version : 2.3.0.5828

Message : 
```
"System.NullReferenceException: Object reference not set to an instance of an object.
   at Starcounter.Response.EstimateNeededSize(Byte[] bytes) in C:\TeamCity\BuildAgent\work\sc-3234\Level1\src\Starcounter.Internal\Http\Response.cs:line 1118
   at Starcounter.Response.ConstructFromFields(Request req, Byte[] givenBuffer) in C:\TeamCity\BuildAgent\work\sc-3234\Level1\src\Starcounter.Internal\Http\Response.cs:line 870
   at Starcounter.Request.SendResponse(Response resp, Byte[] serializationBuf) in C:\TeamCity\BuildAgent\work\sc-3234\Level1\src\Starcounter.Internal\Http\Request.cs:line 1241
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\BuildAgent\work\sc-3234\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 811
HResult=-2147467261
"
```

Source :
`Starcounter.Host`

Type :
`Error`

**Comment by atifwaqar** [comment]
I keep getting this exception again and again. Please let me know when more details are added for this exception, so we install that SC version.
