### ISSUE TITLE
App crashes if sql query length is longer than 5000 Chars

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#4125]
SC Version : 2.3.0.5828

My app crash if the query is longer than 5000 chars. I can avoid the crash by putting a try catch body around the query. But SC Server should handle that instead of crashing the app.

**Comment by k-rus** [comment]
Can you provide information about the crash?

**Comment by atifwaqar** [comment]
If I don't have try catch around this kind of long SQL, the app crashes and I can see following error logged in SC Admin Logs: 
```
Starcounter.DbException: ScErrFailingEntrypoint (SCERR4259): The user code entrypoint method raised an exception. ScErrOutputBufferToSmall (SCERR4197): Operation failed because the output buffer was to small for the output.
Version: 2.3.0.5828.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4197.
Version: 2.3.0.5828.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4259.
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application, Assembly assembly) in C:\TeamCity\BuildAgent\work\sc-3234\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 563
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application, ApplicationDirectory applicationDir) in C:\TeamCity\BuildAgent\work\sc-3234\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 277
   at Starcounter.Hosting.Package.Process() in C:\TeamCity\BuildAgent\work\sc-3234\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 138
   at Starcounter.Hosting.Package.Process(IntPtr hPackage) in C:\TeamCity\BuildAgent\work\sc-3234\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 55
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\BuildAgent\work\sc-3234\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 85
ErrorCode=4259
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4259
---> Starcounter.DbException: ScErrOutputBufferToSmall (SCERR4197): Operation failed because the output buffer was to small for the output.
Version: 2.3.0.5828.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4197.
   at Starcounter.Query.Execution.FilterKeyBuilder.Append(String value, Boolean appendMaxChar) in C:\TeamCity\BuildAgent\work\sc-3234\Level1\src\Starcounter\Query\Execution\Ranges\FilterKeyBuilder.cs:line 470
   at Starcounter.Query.Execution.CodeGenFilterPrivate.GetDataStream(Row obj) in C:\TeamCity\BuildAgent\work\sc-3234\Level1\src\Starcounter\Query\Execution\CodeGeneration\CodeGenFilterPrivate.cs:line 248
   at Starcounter.Query.Execution.FullTableScan.CreateEnumeratorWithNativeFilter() in C:\TeamCity\BuildAgent\work\sc-3234\Level1\src\Starcounter\Query\Execution\Enumerators\FullTableScan.cs:line 298
   at Starcounter.Query.Execution.FullTableScan.MoveNext() in C:\TeamCity\BuildAgent\work\sc-3234\Level1\src\Starcounter\Query\Execution\Enumerators\FullTableScan.cs:line 411
   at Starcounter.QueryResultRows`1.get_First() in C:\TeamCity\BuildAgent\work\sc-3234\Level1\src\Starcounter\Query\SQL\SqlResultGeneric.cs:line 143
   at AdFenix.Program.Main() in C:\adfenix-backend\src\Program.cs:line 16
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application, Assembly assembly) in C:\TeamCity\BuildAgent\work\sc-3234\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 529
ErrorCode=4197
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4197
```

and my SQL query looks like following : 
```
            AdFenix.Database.AdminNotification adminNotification = Db.SQL<AdFenix.Database.AdminNotification>("SELECT an FROM AdFenix.Database.AdminNotification an WHERE Name = ? and message = ?","Error","Atif Loop is needed here. access_token : . FacebookResponse : {\"data\":[{\"id\":\"340610986124628\",\"access_token\":\"EAAXIjoK155YBAAr0jwhpDFLcq62QdA5IC65pyxQ7bUjBjeKMgrPXbPHBhuBuIm8lYwnFdmMWL4t72DxngYQ7ZArzmDflZCf5QZCed2X79JXTZCs4k1c94QTlLBkluTqcwT99ZCGvABIf8a3qib4u4KRlgq5rlWmsZD\"},{\"id\":\"519032314800824\",\"access_token\":\"EAAXIjoK155YBAJPAy9PHpX843G4ilxmOw2uZADJrZAt3F6TBdH9GaKfglg2VEzLPwF3U4oIxyQWNwxoPltxzCs3KKMfidzLQxuCoGZAeN21Y0DhtCXbJigfKbLGrJ5pMMAO0PzNn4IDo06U9ZBFV3dKtu4OjxiEZD\"},{\"id\":\"655360354521598\",\"access_token\":\"EAAXIjoK155YBAGwdl2GFExWVqIxAIx38ZBNNeanBNPGVCP6w0IZB8TtdTARddrFDCMU5gTOZBtvNgvgbHtT0ZA7ub5ZAOj3r6zPXrZBOkZA1ZC0iXZCsAJrZAgmZCDPZBXSGdkSKcrQtUKjBLcVpzlSo7UbHZAHsiXMToaj8ZD\"},{\"id\":\"1704697563083322\",\"access_token\":\"EAAXIjoK155YBAMDIQGTxsO3ve4FbhktdCPjkf1W8bxVxGRDGVqHYZBQQEBacpH89UTTOOWidJLKe0UZA7LPkfzdcDlwbzHg1J078YsoWvxUPINq6iTFyqR6eVINvNPb9iKYjdxghU522zH0tPOsTizlcdqzD4ZD\"},{\"id\":\"359645484208200\",\"access_token\":\"EAAXIjoK155YBAG7pGQwJpVy7jrUtr90AiNraA1tMkJ0sDRWdhKWJQj9xQ9v2lntAZBK09LaIWgGK0AXcZCodcorUfTVeYPqweZBZCw8nUim3xcrcN50sUhDJzrHQTTax3LBByh2gLkEZBGrrwBKeoiTYZCTMBzlngZD\"},{\"id\":\"144901165573093\",\"access_token\":\"EAAXIjoK155YBAMiaCS7adn2kVJPn3e6znCxVZC2xSjCRuKoDtHSMoef2do2zjiePQOWcBridfIwUuUoqN6idCSx2ZCS22Y0osSYtAv0XrC4hVFSKhsLECS9gMm4AGXdSlquzRiYKbDmaouv8qSsd00p3HxiE4ZD\"},{\"id\":\"1750032658595600\",\"access_token\":\"EAAXIjoK155YBAOYbEdzE73WgERyDzimuiBpgTERkg4AzBYZAm0a7CAZBp8YSaFxYUykPbXfBy8SpMxysn9mjpZCQNBZBpFDjnNNwylmGbVpyOZC6dZAMt8bZCmJGeZCZBf4ZBz7hE33BT5pPNq43yOFbYxwZATC91l9cf0ZD\"},{\"id\":\"675010686005721\",\"access_token\":\"EAAXIjoK155YBAPr8cO1XclZA61dJJqR9XxpxNpefCPYhH2mkYcwSZA4ORKnVgwjpbqRrH8IheLpmBO1nc3z2tlcCZAQLGrPVS3G9l5v1avYliPxCscVWZAZBC8rLH6PckJdkHRhxIE29EvLQtUNjjZCA4ZCXriCByUZD\"},{\"id\":\"143127979373232\",\"access_token\":\"EAAXIjoK155YBAEQLnbPxpCqOZAXsZAu1P1W4hc9KFq1r1ZBgTWr4mZAe5UyNC8jgkDUXbKdYIEtPoi2pLNCvJsfb9RQHYsd7nlABdhNPND4j4M6YYXlGtRQEcmH53qXyUMGlLa9sVSlIYlLHf6tYYZAYaI47THOgZD\"},{\"id\":\"431493470200667\",\"access_token\":\"EAAXIjoK155YBADbwJRulVZA6tqGSFQEgbwKPz1N6ZAtO18WQmoeMx5ix0iN6YyuD52MaqPBCpZC2n23kUWFYlj3VEnNXwcdGzxebX4BdbqtleBQx8zrA5eTuQ5ZAeX6mDuNW7wASa1ZAZBAF9wct1a2uY2Le5WBUwZD\"},{\"id\":\"130359540396943\",\"access_token\":\"EAAXIjoK155YBAMGmnZCmdoQCBOk2KwijX2fyxbjMVLCPXtnc3DiuAwNiPRgR0Yb3ULZBV0o26ckDuVLzA22XGzZA3noZB8RdoM0UdhBE0ZBbZBxMemJvN3ra0gY3ZAVKsUbZCIqVGO8D4YdNdMuG1Q1ZB9doK34XLqSoZD\"},{\"id\":\"1109290612469508\",\"access_token\":\"EAAXIjoK155YBAEQ53BAEWK9WIDvZAZBRnOXIJmpNxSaJGTllwa5u3nWN1nGqeuncT0wSqOVwlfh1nHsfZBjPhPZA5UnHMLI6MyO8hwQTW6RD2DXXv0qUxskY9mR916BZAJCEZCxtzKkCMOLqiQZBSt4aXswhqt19rcZD\"},{\"id\":\"236344823091523\",\"access_token\":\"EAAXIjoK155YBAMErRS6I9RoZBCiotoxRJAuZA0vPixMec0KYC9bb8IhOA4jbAsRydhjGe9D016tW98KNTzjWIAZCYDqc4NnuRYbxCgA8BY7CZBwZB2gN7EMvKvXkDwOk7WDxqbAZBVgwZB5uIISg6vHIjv85B2ZCmzgZD\"},{\"id\":\"991050567684354\",\"access_token\":\"EAAXIjoK155YBAJaoDKaudVpRB1esUiJEFmdupUSNiPBGJFw34vWQKmU3vVv9FaPV0eBZAQZACLIZA45ZAc1fZBzmrZANBM3BIdJn4WZCuS4UFftjL0aqzoCNCz0MIrRH8rrka3jBV7ZCypQHU4BF2GVTbmZBNHZBf7azAZD\"},{\"id\":\"1765614830326890\",\"access_token\":\"EAAXIjoK155YBAFH0wwfR1SuQTwblTn1M7YsHivKTmTSP6SEO04ZCtjdEtzz0pMsQRwz5EinCmQ3h2NYZCl8PedlKqZALMsU610S5NkDIdFAfbDLiKHYr5PBZBPEdXpOdwaZBSGn1QPbKPealUt9NBbwl6iNe7wFYZD\"},{\"id\":\"209834102365020\",\"access_token\":\"EAAXIjoK155YBAMhJya5Cf4oHcBu3lF6o64vDZAocOOxhj7IpS9lbX97oNa8PscdxajrBJRAOJJp3Nm7w2Ga6tsTDNqowNl1BhyBIrZB02E3XloFTyWLUNjWQZAYGrWipZCZBImX5U9n1XeENtbTf3lIZCpiRtAYmUZD\"},{\"id\":\"229046097141150\",\"access_token\":\"EAAXIjoK155YBABgyjlbKIRxQPWWuHA00ZCIA8qvZA9258JE5dr2mpO6BvmK2CWk2yhLCDuWWZBZAXtBSNT371oukbWVLZCocP0tu5bw2EbPmNoFTus9xJlm9VZAORNOi5VEetAKsnJPiEHILOuNHGdXoI0xci4JjYZD\"},{\"id\":\"758566990872595\",\"access_token\":\"EAAXIjoK155YBABKa7uN4w7ZB6RQpQIZBCxXhgDBzvrKldHu4JGlZBYZBx70aZBgtBeaiBh7WraK3Hc7XkkP3JOLR2ZCXZAQYcSnVOQziC150O2RgZBkEQNQ3IqZCYuQBgfVeSMxOUkv81ZBZCAfpEXgLJw2rwLxkQAYtvIZD\"},{\"id\":\"1548825022017660\",\"access_token\":\"EAAXIjoK155YBAKWZB5sAJfUZBVLPDTjbTeI4NaQtSgmqvgHs9R2mPE5NtW1DCFIGNYwfrMHd2QZCBewpI6z0WlKZBk8CZBXGcHVM3dtW8lFAGbkJYvDVbBu0zGy2dTi58wu9lfHK93U4EgiBMhujm8NVoYTWb5lMZD\"},{\"id\":\"469508789766127\",\"access_token\":\"EAAXIjoK155YBAOHAbL16kQUUmswMYfZC8HWZBlNqKkJcJzdmmOMym17DmVIR1KZBPInPkmlimxA1Dg8jiuBppUywoLlm2mwUvZCKMhwhnHWrWpZAxZAuUMe7TnlIJawZBBAJSz2Wy0DdZCdWQU1e9ZB0GLbuRvGPHFJAZD\"},{\"id\":\"166919983658845\",\"access_token\":\"EAAXIjoK155YBANDo6lgV0rvShmJ7UXtfZC3pmNrWfGThwOBIa07WqyhTWkYO3ZBrXIOxFX79TD0dXZAG4BqM5BHqb29nKT9n64WVcEwtyZCJy8Ibl7tV71esbZBSwWx5HIxdKtgscRxIXmZCZCdZB795g51udLaMvRYZD\"},{\"id\":\"245675752203091\",\"access_token\":\"EAAXIjoK155YBAEqw48lbvqTpQAaMZBtMuoCMmORj9gVegqwroHXSJqMmmQQQ8ewM2CHNWtpUr8AWTmvvQOVcsiPnlhRM0Eu3p7Ew0SC3HgZCAZBgnXnNYAwrQk7VZCuc3vo9QUeZBiOksZBjMQ1K6wMSzZAENcin3oZD\"},{\"id\":\"168529166910028\",\"access_token\":\"EAAXIjoK155YBALp2mmhJX44ARmZCX7lcDRKE2vdK08YjIwZBInCZBeLzbkCYObEf4ZBD5IbhicZAMBZCE3lhw7CrOYTZC6jGIz1Iz7RJ3QfgMvGsWaaTwxqxFnT3mF3jZBDCFC8itYtEHALB56lvopgOWgn5M155Ov8ZD\"},{\"id\":\"104798976371196\",\"access_token\":\"EAAXIjoK155Y'").First;
```

**Comment by miyconst** [comment]
It looks like the issue title is misleading. The `Db.SQL` crashes when passing a string parameter with length more than 5000 characters. @atifwaqar please update the title.

In your example the SQL query is only this:

```
"SELECT an FROM AdFenix.Database.AdminNotification an WHERE Name = ? and message = ?"
```

And the rest are parameters.

As a solution for this situation I would recommend not passing entire response from Facebook as a query parameter, instead take a SHA1/256 or MD5 hash of the response and perform comparison by it.

**Comment by atifwaqar** [comment]
@miyconst that's a good solution, I'll implement it. But in any case, App should not crash, it should generate an error notification in SC Admin Logs.

**Comment by miyconst** [comment]
>But in any case, App should not crash, it should generate an error notification in SC Admin Logs.

Absolutely. Starcounter has to be very user friendly, and if something goes wrong, it should be clear what is wrong, and not just a crash.

**Comment by dan31** [comment]
![image](https://cloud.githubusercontent.com/assets/7162535/23704863/2fa4ee26-0407-11e7-8a7d-70fc61997336.png)

**Comment by dan31** [comment]
The fix would be a better error message for such one case.

**Comment by k-rus** [comment]
> Starcounter.Query.Execution.FilterKeyBuilder.Append(String value, Boolean appendMaxChar) in C:\TeamCity\BuildAgent\work\sc-3234\Level1\src\Starcounter\Query\Execution\Ranges\FilterKeyBuilder.cs:line 470
>    at Starcounter.Query.Execution.CodeGenFilterPrivate.GetDataStream(Row obj)

According the stack trace the crash happens in the key filter builder. cc @alemoi

**Comment by alemoi** [comment]
We checked the code with @k-rus and its not that easy to put the check for size in one place, because the involved code is in many places. There are different ways to create a better error message but it would require rewriting a lot of code, and the exception message would be approximately the same. So we have to deal with it now by simply instructing customers not to use extremely long search keys.

**Comment by alemoi** [comment]
To be precise the size limitation is in filter key construction managed code. There is no precalculation of the key size, because of performance reasons, so streaming into fixed size buffer is used.

**Comment by alemoi** [comment]
@k-rus do you think we can close the issue?

**Comment by alexanderstc** [comment]
Metalayer also currently limits key buffers sizes.
There should be a relevant gitlab issue, if sclerosis serves.

**Comment by alexanderstc** [comment]
Oh yeah, @k-rus already mentioned https://git.starcounter.org/BlueStar/level0/issues/140
