### ISSUE TITLE
Unable to Query from a certain table

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#4126]
SC Version : 2.3.0.5828

When I execute query `select * from AdFenix.Database.FacebookPage` I get the following Exception :

```
System.InvalidCastException: Unable to cast object of type 'AdFenix.Database.Concept' to type 'AdFenix.Database.Content'.
   at AdFenix.Database.Publication.get_Content()
   at Starcounter.Internal.DbState.View.GetObject(TypeBinding binding, Int32 index, Object proxy) in C:\TeamCity\BuildAgent\work\sc-3234\Level1\src\Starcounter\Internal\DbState.cs:line 71
   at AdFenix.Database.Concept.Starcounter.IObjectView.GetObject(Int32 index)
   at Starcounter.Query.Execution.Row.GetObject(Int32 index) in C:\TeamCity\BuildAgent\work\sc-3234\Level1\src\Starcounter\Query\Execution\Row\Row.cs:line 709
   at Starcounter.Internal.SqlRestHandler.ExecuteQuery(String query, Int32 maxResult) in C:\TeamCity\BuildAgent\work\sc-3234\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\SqlRestHandler.cs:line 245
HResult=-2147467262
```

**Comment by k-rus** [comment]
I guess it is due to your refactoring. I believe there are objects in `FacebookPage`, which contain references to `AdFenix.Database.Concept`, while the type of the property was changed from `AdFenix.Database.Concept` to `AdFenix.Database.Content`.

**Comment by dan31** [comment]
@atifwaqar does @k-rus answer your question?

**Comment by atifwaqar** [comment]
Yes, but we are trying to find a way to fix it. 
Do you guys have any suggestions on how to fix this?

**Comment by k-rus** [comment]
I believe you want to keep data, right? Have you entered any new data, i.e., do you have a mix of `AdFenix.Database.Concept` and `AdFenix.Database.Content` instances in the column now?

**Comment by k-rus** [comment]
Can you describe what kind of refactoring have you done? Have you just changed a type of a property from `AdFenix.Database.Concept` to `AdFenix.Database.Content`?

**Comment by k-rus** [comment]
> Have you just changed a type of a property from AdFenix.Database.Concept to AdFenix.Database.Content?

If so, then, for example, you can change the type of the property into a base class.

**Comment by atifwaqar** [comment]
Found and fixed the issue. and to me it looks like it had nothing to do with property changed from `AdFenix.Database.Concept` to `AdFenix.Database.Content`.

this piece of code was the issue : 
```cs
        public Advertiser _Advertiser;
        public Advertiser Advertiser
        {
            get
            {
                if (this._Advertiser == null)
                {
                     this._Advertiser = = Db.SQL<AdFenix.Database.Advertiser>("SELECT a FROM AdFenix.Database.Advertiser a WHERE a.FacebookPage = ?", this).First;
                }
                return this._Advertiser;
            }
```

Where as the code in if condition should have been in `Db.Transact`

**Comment by atifwaqar** [comment]
My bad, this the above solution is another issue's fix. I still get the same exception when i query in SC Admin Panel.

**Comment by atifwaqar** [comment]
Ok this is weird only 1 following object is messed up:
`SELECT * FROM AdFenix.Database.FacebookPage offset 38`

and if I exclude this object which is at offset 38, everything works fine for me. 
Now how can I investegate or may be fix this one object?

**Comment by atifwaqar** [comment]
> Can you describe what kind of refactoring have you done? Have you just changed a type of a property from AdFenix.Database.Concept to AdFenix.Database.Content?

I am not aware of it, To my knowledge there was no refactoring done on this table ever.

**Comment by miyconst** [comment]
From the stack trace I may assume that somehow it happens that `AdFenix.Database.Publication.get_Content`  method returns `AdFenix.Database.Concept` instead.

This may happen for different reasons, and to be able to investigate it would be good too see the full class declaration (without static methods).

**Comment by atifwaqar** [comment]
Is this what you asked for?

```cs
using Starcounter;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;

namespace AdFenix.Database
{
    public class FacebookPage : WebPublication
    {
        public string FacebookName;
        public string ExternalId;
        public bool IsVerified;
        public string FbPageUrl
        {
            get
            {
                return this.Url;
            }
            set
            {
                ...
            }
        }
        public bool FbPageRequest
        {
            get
            {
                return false;
            }

            set
            {
                ...
            }
        }
        public string access_status;
        public string ImageUrl
        {
            get
            {
                return "http://graph.facebook.com/" + ExternalId + "/picture";
            }
        }

        public DateTime ApprovalRequestSent;

        public int TimesChecked;

        public Advertiser _Advertiser;
        public Advertiser Advertiser
        {
            get
            {
                if (this._Advertiser == null)
                {
                    Advertiser _Adv = Db.SQL<AdFenix.Database.Advertiser>("SELECT a FROM AdFenix.Database.Advertiser a WHERE a.FacebookPage = ?", this).First;
                    Db.Transact(() =>
                    {
                        this._Advertiser = _Adv;
                    });
                }
                return this._Advertiser;
            }
        }
    }
}
```

**Comment by miyconst** [comment]
>Is this what you asked for?

Sorry, but no. The `Content` property causes the exception, I need to see the class which declares this property.

**Comment by atifwaqar** [comment]
Ok, Is this what you asked for?

```cs
using Starcounter;
using System.Collections.Generic;
using System;

namespace AdFenix.Database {

    public class Publication : Relation {

        [SynonymousTo("WhatIs")]
        public Content Content;

        [SynonymousTo("ToWhat")]
        public Agent Publisher;

        public double Age {
            get
            {
                DateTime now = DateTime.Now;
                TimeSpan age = now - this.Created;
                double howOld = age.TotalHours;
                return howOld;
            }
        }
        public double hoursSinceUpdated
        {
            get
            {
                DateTime now = DateTime.Now;
                TimeSpan age = now - this.Updated;
                double howOld = age.TotalHours;
                return howOld;
            }
        }

        public DateTime Created;

        public DateTime Updated;
        
        public Publication Parent;
        public IEnumerable<Publication> Children {
            get {
                return Db.SQL<Publication>("SELECT P FROM AdFenix.Database.Publication P WHERE Parent=?", this);
            }
        }
    }
}
```

**Comment by miyconst** [comment]
Okay, now the issue is obvious.

The database somehow ended up with wrong data.

The `Publication` class inherits `Relation`, and the `Content` property is a synonym for `WhatIs`, while the `WhatIs` is of very base type `Something`. 

I assume that both `AdFenix.Database.Concept` and `AdFenix.Database.Content` are inherited from `Something`, which means it's possible to set `WhatIs` to either of those values.

For `Publication` class only `AdFenix.Database.Content` is valid though. The class names are very similar, and it very well may be, that there is a typo somewhere, setting `WhatIs` to `Concept` instead of `Content`.

**Comment by atifwaqar** [comment]
Ok I'm kind of lost here. I can see that the following type of code is in some places in our solution: 
```cs
        [SynonymousTo("WhatIs")]
        public Content Content;

        [SynonymousTo("ToWhat")]
        public Agent Publisher;
```

I have no idea how `WhatIs` and `ToWhat` works, If you have any documentation somewhere please do share so I can understand whats happening here.

**Comment by miyconst** [comment]
There is not much to tell. The `WhatIs` and `ToWhat` are just property names, it could be named `Right` and `Left` or `Top` and `Bottom`.

The properties just store reference to two objects which are related to each other through a `Relation`.

**Comment by k-rus** [comment]
@miyconst Thank you for asking right questions.

I don't know what is expected behaviour f `SynonymousTo` and how it is implemented. It is not described anywhere and my question about it was never answered.

May be @per-samuelsson knows more, related to the issue.

**Comment by per-samuelsson** [comment]
> May be @per-samuelsson knows more, related to the issue.

It's pretty straightforward: `[SynonomousTo]` is just a convenient way to shorten writing properties that narrow down (by cast) a more general property. More explicitly, this declaration

```csharp
[SynonymousTo("WhatIs")]
public Content Content;
```

will simply just translate to this:

```csharp
[SynonymousTo("WhatIs")]
public Content Content {
  get { return (Content) WhatIs; }
}
```

**Comment by k-rus** [comment]
> will simply just translate to this:
> 
> [SynonymousTo("WhatIs")]
> public Content Content {
>   get { return (Content) WhatIs; }
> }

Does it mean that if `WhatIs` contains instances of other class than `Content` the cast will fail? And therefor the issue error?

**Comment by miyconst** [comment]
>Does it mean that if `WhatIs` contains instances of other class than `Content` the cast will fail? And therefor the issue error?

Yes.

**Comment by per-samuelsson** [comment]
While the underlying problem here is not that synonyms are in use, I think the fact that we are again having to consider how synonyms affect the user experience (and developers clearly don't fully understand how they work) is getting us closer to [the proposal to drop support for synonyms](https://github.com/Starcounter/CompanyTrack/issues/180).
