### ISSUE TITLE
Issue in Simplified.Ring3.EmailAddressRelation

### ISSUE THREAD

**Issue by iliassays** [Starcounter/Starcounter#4137]
There is no Email address in SystemUserTable. I was trying to create a relationship with following snippet for existing users.

```
Simplified.Ring2.Person person = new Simplified.Ring2.Person() { FirstName = user.Username, LastName = user.Username };
                    user.WhatIs = person;                    
                    // Add ability to also sign in with email
                    EmailAddress emailRel = new EmailAddress();

                    EmailAddressRelation eRel = new EmailAddressRelation();
                    eRel.ToWhat = user;
                    eRel.WhatIs = emailRel;

                    //emailRel.SetToWhat(systemUser);
                    emailRel.EMail = email.Trim().ToLowerInvariant();
```
Now when i try to call Simplified.Ring3.SystemUser.GetSystemUserByEmail(email), i am fetching bellow error:

System.InvalidCastException: Unable to cast object of type 'Simplified.Ring3.SystemUser' to type 'Simplified.Ring1.Somebody'.
   at Simplified.Ring2.ContactInfoRelation.get_Somebody()
   at Simplified.Ring1.Something.Starcounter.IObjectView.GetObject(Int32 index)
   at Starcounter.Query.Execution.Row.GetObject(Int32 index) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-531\Level1\src\Starcounter\Query\Execution\Row\Row.cs:line 709
   at Starcounter.Internal.SqlRestHandler.ExecuteQuery(String query, Int32 maxResult) in C:\TeamCity\BuildAgent\work\sc-develop-nightly-531\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\SqlRestHandler.cs:line 245
HResult=-2147467262

**Comment by miyconst** [comment]
This line of code should be replaced:

```cs
eRel.ToWhat = user;
```

With:

```cs
eRel.ToWhat = person;
```
