### ISSUE TITLE
System.ArgumentOutOfRangeException: Self should be called with URI starting with a slash.

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#4145]
SC Version : 2.3.0.5319

A handler that used to return a Json as response is now returning this error. 
Is it because of latest SC Version?

```
System.ArgumentOutOfRangeException: Self should be called with URI starting with a slash.
   at Starcounter.Self.DoSelfCall(UInt16 portNumber, String method, String relativeUri, Dictionary`2 headersDictionary, String body, Byte[] bodyBytes, HandlerOptions handlerOptions, Request req) in C:\TeamCity\TeamCity10\buildAgent\work\sc-3487\Level1\src\Starcounter.Internal\Rest\Self.cs:line 340
   at Starcounter.Self.GET[T](String uri, HandlerOptions ho) in C:\TeamCity\TeamCity10\buildAgent\work\sc-3487\Level1\src\Starcounter.Internal\Rest\Self.cs:line 22
   at Starcounter.HtmlFromJsonProvider.ProvideFromFilePath[T](String filePath) in C:\TeamCity\TeamCity10\buildAgent\work\sc-3487\Level1\src\Starcounter\Middleware\HtmlFromJsonProvider.cs:line 56
   at Starcounter.HtmlFromJsonProvider.Invoke(MimeProviderContext context, Action next) in C:\TeamCity\TeamCity10\buildAgent\work\sc-3487\Level1\src\Starcounter\Middleware\HtmlFromJsonProvider.cs:line 53
   at Starcounter.Internal.JsonMimeConverter.Convert(Request request, IResource before, MimeType mimeType, MimeType& resultingMimeType) in C:\TeamCity\TeamCity10\buildAgent\work\sc-3487\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\JsonMimeConverter.cs:line 18
   at Starcounter.Json.AsMimeType(MimeType mimeType, MimeType& resultingMimeType, Request request) in C:\TeamCity\TeamCity10\buildAgent\work\sc-3487\Level1\src\Starcounter.XSON\Class Json\Json.IResource.cs:line 43
   at Starcounter.Response.ConstructFromFields(Request req, Byte[] givenBuffer) in C:\TeamCity\TeamCity10\buildAgent\work\sc-3487\Level1\src\Starcounter.Internal\Http\Response.cs:line 809
   at Starcounter.Request.SendResponse(Response resp, Byte[] serializationBuf) in C:\TeamCity\TeamCity10\buildAgent\work\sc-3487\Level1\src\Starcounter.Internal\Http\Request.cs:line 1241
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\TeamCity10\buildAgent\work\sc-3487\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 811
ParamName=
HResult=-2146233086

More information about this error may be available in the server error log.
```

**Comment by atifwaqar** [comment]
My Json : 
```
{
  "PublicationOwner": [
    {
      "Name": "",
      "ListingsToday": 0,
      "AgentAdOrderToday": 0,
      "HomeboosterOrderToday": 0,
      "Listings7Days": 0,
      "AgentAdOrder7Days": 0,
      "HomeboosterOrder7Days": 0,
      "ListingsMTD": 0,
      "AgentAdOrderMTD": 0,
      "HomeboosterOrderMTD": 0,
      "HomeboosterOrderYTD": 0,
      "HomeboosterRevenue7Days": 0.0,
      "HomeboosterGrossMargin7Days": 0.0,
      "ClassifiedHomeAds": [
        {
          "ObId": "",
          "Url": "",
          "Home": {
            "Latitude": 0.0,
            "Longitude": 0.0
          }
        }
      ]
    }
  ]
}
```

My Handler : 
```
Handle.GET("/AdFenix/API/PlayGround", () =>
            {
                //return Db.Scope(() =>
                //{
                    Jsons.SalesStats salesStats = new Jsons.SalesStats();
                    salesStats.PublicationOwner.Data = Db.SQL<AdFenix.Database.PublicationOwner>("select c from AdFenix.Database.PublicationOwner c where IsCustomerLiveOnThisServer = ?", true);
                    foreach (Jsons.SalesStats.PublicationOwnerElementJson salesStat in salesStats.PublicationOwner)
                    {
                        try
                        {
                            DateTime date = DateTime.Now;
                            var firstDayOfMonth = new DateTime(date.Year, date.Month, 1);
                            var firstDayOfYear = new DateTime(date.Year, 1, 1);

                            PublicationOwner po = Db.SQL<AdFenix.Database.PublicationOwner>("select po from AdFenix.Database.PublicationOwner po where Name = ?", salesStat.Name).First;
                            if (po != null)
                            {
                                salesStat.ListingsToday = Db.SQL<Int64>("select count(e) from adfenix.database.email.email e where name = ? and publicationowner = ? and IsConfirmed = ? and dated >= ?", "SinglePublicationEmail", po, true, DateTime.Today).First;
                                salesStat.Listings7Days = Db.SQL<Int64>("select count(e) from adfenix.database.email.email e where name = ? and publicationowner = ? and IsConfirmed = ? and dated >= ?", "SinglePublicationEmail", po, true, DateTime.Now.AddDays(-7)).First;
                                salesStat.ListingsMTD = Db.SQL<Int64>("select   count(e) from adfenix.database.email.email e where name = ? and publicationowner = ? and IsConfirmed = ? and dated >= ?", "SinglePublicationEmail", po, true, firstDayOfMonth).First;

                                //select count(c) from adfenix.database.campaign c where not name like '%agent%' and publicationowner.name = 'krogsveen' and  start > date'2016-11-17'
                                salesStat.AgentAdOrderToday = Db.SQL<Int64>("select count(c) from adfenix.database.campaign c where _publicationowner = ? and start >= ? and name like ? ", po, DateTime.Today, "%agent%").First;
                                salesStat.AgentAdOrder7Days = Db.SQL<Int64>("select count(c) from adfenix.database.campaign c where _publicationowner = ? and start >= ? and name like ? ", po, DateTime.Now.AddDays(-7), "%agent%").First; ;
                                salesStat.AgentAdOrderMTD = Db.SQL<Int64>("select   count(c) from adfenix.database.campaign c where _publicationowner = ? and start >= ? and name like ? ", po, firstDayOfMonth, "%agent%").First;

                                //select count(c) from adfenix.database.campaign c where not name like '%home%' and publicationowner.name = 'krogsveen' and  start > date'2016-11-17'
                                salesStat.HomeboosterOrderToday = Db.SQL<Int64>("select count(c) from adfenix.database.campaign c where _publicationowner = ? and start >= ? and not name like ?", po, DateTime.Today, "%agent%").First;
                                salesStat.HomeboosterOrder7Days = Db.SQL<Int64>("select count(c) from adfenix.database.campaign c where _publicationowner = ? and start >= ? and not name like ?", po, DateTime.Now.AddDays(-7), "%agent%").First;
                                salesStat.HomeboosterOrderMTD = Db.SQL<Int64>("select   count(c) from adfenix.database.campaign c where _publicationowner = ? and start >= ? and not name like ?", po, firstDayOfMonth, "%agent%").First;
                                salesStat.HomeboosterOrderYTD = Db.SQL<Int64>("select   count(c) from adfenix.database.campaign c where _publicationowner = ? and start >= ? and not name like ?", po, firstDayOfYear, "%agent%").First;

                                salesStat.HomeboosterRevenue7Days = Db.SQL<Decimal>("select sum(Product.CampaignPriceSEK) from adfenix.database.campaign where _publicationowner = ? and product is not null and start > ? and product.agentad = ?", po, firstDayOfYear, false).First;
                                try
                                {
                                    salesStat.HomeboosterGrossMargin7Days = Db.SQL<Decimal>("select ((sum(Product.LastFetchedCampaignPriceSEK)/sum(Product.LastFetchedCampaignBudgetSEK))-?)*? from adfenix.database.campaign where _publicationowner = ? and product is not null and start > ? and product.agentad = ?", 1, 100, po, firstDayOfYear, false).First;
                                }
                                catch (Exception ex)
                                {
                                    AdFenix.Database.AdminNotification.CreateOrUpdateNotification(AdFenix.Database.NotificationMessages.Critical, "Error : " + ex.Message, "StackTrace : " + ex.StackTrace, ex.Source);
                                }

                                QueryResultRows<dynamic> classifiedHomeAds = Db.SQL<dynamic>("select Ad.AdvertisedPublication from AdFenix.Database.Campaign where _publicationowner  = ? and start >= ? and Synced = ? and running = ? ", po, DateTime.Today, true, true);
                                salesStat.ClassifiedHomeAds.Data = classifiedHomeAds;
                            }
                        }
                        catch (Exception ex)
                        {
                            AdFenix.Database.AdminNotification.CreateOrUpdateNotification(AdFenix.Database.NotificationMessages.Critical, "Error : " + ex.Message, "StackTrace : " + ex.StackTrace, ex.Source);
                        }
                    }
                    return salesStats;
                //});
            }, new HandlerOptions() { SkipRequestFilters = true });
```

**Comment by miyconst** [comment]
cc @alemoi

**Comment by alemoi** [comment]
I checked the code and `HtmlFromJsonProvider.cs` calls `Self.GET` via `var result = Self.GET<T>(filePath);` so the value of `filePath` contains something not a valid URI i suppose. @chrhol can you some insight on what this value can contain?

**Comment by atifwaqar** [comment]
Any luck with this one guys?

**Comment by miyconst** [comment]
>My Json :

@atifwaqar, I don't see the `Html` property in your view-model? Is it defined at all? What is it value?

**Comment by atifwaqar** [comment]
We never needed Html property, because this is not a page, its a simple Json response. like RestAPI

**Comment by miyconst** [comment]
>We never needed Html property, because this is not a page, its a simple Json response. like RestAPI

Then it might be a bug in the `PartialToStandaloneHtmlProvider` class. Please try comment out the lines with it's usage and try again.

```
Application.Current.Use(new Tool.PartialToStandaloneHtmlProvider());
```

**Comment by atifwaqar** [comment]
Ok commenting out following line fixed the issue : 
`Application.Current.Use(new HtmlFromJsonProvider());`

**Comment by miyconst** [comment]
Then it's a bug in the `HtmlFromJsonProvider`. It is trying to determine HTML for a view-mode, which is does not have HTML.

**Comment by miyconst** [comment]
cc @warpech

**Comment by warpech** [comment]
@atifwaqar can you make a local copy of these classes:

- https://github.com/Starcounter/Starcounter/blob/develop/src/Starcounter/Middleware/HtmlFromJsonProvider.cs
- https://github.com/Starcounter/Starcounter/blob/develop/src/Starcounter/Middleware/PartialToStandaloneHtmlProvider.cs

Use your local copy and tell me where it goes wrong? With intended usage you should not be getting these kind of exception.

**Comment by atifwaqar** [comment]
@warpech Sorry I couldn't test this thing, since commenting `Application.Current.Use(new HtmlFromJsonProvider());` fixed the issue for us.
Do you still need to test this code?

**Comment by warpech** [comment]
By commenting out `Application.Current.Use(new HtmlFromJsonProvider());` you have most likely removed the possibility to run your app standalone (without Launcher). This can hurt you in the long term, because we want to be able to run any app standalone - to prove composability, for elegant testing, etc.

If the problem is gone for you, and we cannot reproduce it otherwise, then I think you can close it. But if the problem returns, I will be happy to investigate further.

**Comment by atifwaqar** [comment]
lets fix this issue now, so we dont have to worry about it in future. I have setup a test server with this issue, you can login there and investigate the issue.
