### ISSUE TITLE
Unable to install Starcounter via an installer after local builds

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#4149]
I have set up the environment for Level1 compilation, and after that I am not able to install Starcounter via an installer.

Running installer shows the following window:

![image](https://cloud.githubusercontent.com/assets/6435556/23945435/c5ff214c-0976-11e7-8a30-2f2d01b5d3a7.png)

Successfully "uninstalls" Starcounter and exits. Running the installer again produces exactly the same result.

```
Starcounter-RC-2.3.0.5943-Setup.exe
```

cc @andwah, @alemoi

**Comment by chrhol** [comment]
Can it be tied to the changes for the VS extension? As I understand it, the extension is no longer uninstalled when uninstalling Starcounter, and maybe the installer still looks for it when deciding if you have Starcounter installed or not.

**Comment by miyconst** [comment]
Could be. I have also checked the old installers, they all "think", that Starcounter is still installed.

**Comment by miyconst** [comment]
I also have VS2017 installed, if that may be the reason, somehow.

**Comment by miyconst** [comment]
Okay, so with help of @alemoi we discovered that the new Installer does not uninstall Visual Studio extensions.

While old (and new) installers believe that Starcounter is installed if extension is installed.

**Comment by andwah** [comment]
A bit related https://github.com/Starcounter/Starcounter/issues/4141 about old and new installer

**Comment by miyconst** [comment]
Manually removing the extension from Visual Studio solved the problem.

**Comment by miyconst** [comment]
Now I am able to install Starcounter, but not start the server.

```
D:\GitHub> staradmin start server
Starting server (starting server)

ScErrBadServerConfig (SCERR2115): Server configuration is invalid.
Version: 2.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR2115.

Type "star -h" to see help
Type "star 2115" to launch the help page for error 2115

Stack trace:
   at Starcounter.Server.ServerServiceProcess.WaitUntilServerIsOnlineOrSignalExit[T](Func`2 checkExited, T context) in D:\GitHub\Starcounter\Level1\src\Server\Starcounter.Server\ServerServiceProcess.cs:line 219
   at Starcounter.Server.ServerServiceProcess.WaitUntilServerIsOnline(Process serverProcess) in D:\GitHub\Starcounter\Level1\src\Server\Starcounter.Server\ServerServiceProcess.cs:line 176
   at Starcounter.Server.ServerServiceProcess.StartInteractiveOnDemand(Boolean withNoWindow) in D:\GitHub\Starcounter\Level1\src\Server\Starcounter.Server\ServerServiceProcess.cs:line 103
   at Starcounter.CLI.StartServerCLICommand.RunWithinContext() in D:\GitHub\Starcounter\Level1\src\Server\Starcounter.CLI\StartServerCLICommand.cs:line 51
   at Starcounter.CLI.StartServerCLICommand.Run() in D:\GitHub\Starcounter\Level1\src\Server\Starcounter.CLI\StartServerCLICommand.cs:line 39
Could not find a part of the path 'D:\GitHub\.srv\personal\Personal.server.config'.
D:\GitHub>
```

Why it's looking for the config file in a relative path?

**Comment by per-samuelsson** [comment]
Regarding

> Okay, so with help of @alemoi we discovered that the new Installer does not uninstall Visual Studio extensions.

that is by design, and written explicitly in OP of #4141:

> One major *functional* change is installing/uninstalling the Visual Studio extension:

> * If you choose to do so, we will launch the *standard Visual Studio extension installer* at the *end of the installation*. This one will simply take over where we finish - in a new window.
> * When you uninstall, we never touch the extension - you have to uninstall it manually if you want to.
