### ISSUE TITLE
Node WebSockets test failure

### ISSUE THREAD

**Issue by linkdata** [Starcounter/Starcounter#4156]
https://teamcity.starcounter.org/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=21207#_focus=12472

> [01:50:58][umbrella_node_test-bat] Finished echoes: 13349 out of 30000, last second: 13349
[01:51:00][umbrella_node_test-bat] Finished echoes: 22960 out of 30000, last second: 9611
[01:51:01][umbrella_node_test-bat] Finished echoes: 23410 out of 30000, last second: 450
[01:51:02][umbrella_node_test-bat] Finished echoes: 23410 out of 30000, last second: 0
[01:51:03][umbrella_node_test-bat] Finished echoes: 23410 out of 30000, last second: 0
[01:51:04][umbrella_node_test-bat] Finished echoes: 23410 out of 30000, last second: 0
[01:51:05][umbrella_node_test-bat] Finished echoes: 23410 out of 30000, last second: 0
[01:51:06][umbrella_node_test-bat] Finished echoes: 23410 out of 30000, last second: 0
[01:51:07][umbrella_node_test-bat] Finished echoes: 23410 out of 30000, last second: 0
[01:51:08][umbrella_node_test-bat] Finished echoes: 23410 out of 30000, last second: 0
[01:51:08][umbrella_node_test-bat] 2: test crashed: System.Exception: Failed to get WebSocket response in time!
[01:51:08][umbrella_node_test-bat]    at NodeTest.NodeTestInstance.PerformSyncWebSocket4NetEcho(Byte[] bodyBytes, Byte[] respBytes) in C:\TeamCity\BuildAgent\work\sc-3724\Level1\src\Samples\NodeTest\NodeTest.cs:line 475
[01:51:08][umbrella_node_test-bat]    at NodeTest.NodeTestInstance.PerformTest(Node node) in C:\TeamCity\BuildAgent\work\sc-3724\Level1\src\Samples\NodeTest\NodeTest.cs:line 578
[01:51:08][umbrella_node_test-bat]    at NodeTest.Worker.WorkerLoop() in C:\TeamCity\BuildAgent\work\sc-3724\Level1\src\Samples\NodeTest\NodeTest.cs:line 802
[01:51:08][umbrella_node_test-bat] Test failed: incorrect echo received.

**Comment by per-samuelsson** [comment]
Dup of https://github.com/Starcounter/AdminTrack/issues/258
