### ISSUE TITLE
Could not load file or assembly

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#4164]
SC Version 2.3.0.5943

```
Starcounter.DbException: ScErrFailingEntrypoint (SCERR4259): The user code entrypoint method raised an exception. System.IO.FileNotFoundException: Could not load file or assembly 'Google.Ads.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=52807268f2b614dc' or one of its dependencies. The system cannot find the file specified.
File name: 'Google.Ads.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=52807268f2b614dc'
   at AdFenix.Program.Main()
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application, Assembly assembly) in C:\TeamCity\BuildAgent\work\sc-3563\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 529

=== Pre-bind state information ===
LOG: DisplayName = Google.Ads.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=52807268f2b614dc
 (Fully-specified)
LOG: Appbase = file:///C:/Program Files/Starcounter/
LOG: Initial PrivatePath = NULL
Calling assembly : (Unknown).
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Program Files\Starcounter\sccode.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Google.Ads.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=52807268f2b614dc
LOG: Attempting download of new URL file:///C:/Program Files/Starcounter/Google.Ads.Common.DLL.
LOG: Attempting download of new URL file:///C:/Program Files/Starcounter/Google.Ads.Common/Google.Ads.Common.DLL.
LOG: Attempting download of new URL file:///C:/Program Files/Starcounter/Google.Ads.Common.EXE.
LOG: Attempting download of new URL file:///C:/Program Files/Starcounter/Google.Ads.Common/Google.Ads.Common.EXE.

Version: 2.3.0.5943.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4259.
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application, Assembly assembly) in C:\TeamCity\BuildAgent\work\sc-3563\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 563
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application, ApplicationDirectory applicationDir) in C:\TeamCity\BuildAgent\work\sc-3563\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 277
   at Starcounter.Hosting.Package.Process() in C:\TeamCity\BuildAgent\work\sc-3563\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 138
   at Starcounter.Hosting.Package.Process(IntPtr hPackage) in C:\TeamCity\BuildAgent\work\sc-3563\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 55
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\BuildAgent\work\sc-3563\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 85
ErrorCode=4259
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4259
---> System.IO.FileNotFoundException: Could not load file or assembly 'Google.Ads.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=52807268f2b614dc' or one of its dependencies. The system cannot find the file specified.
   at AdFenix.Program.Main()
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application, Assembly assembly) in C:\TeamCity\BuildAgent\work\sc-3563\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 529
FileName=Google.Ads.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=52807268f2b614dc
FusionLog==== Pre-bind state information ===
LOG: DisplayName = Google.Ads.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=52807268f2b614dc
 (Fully-specified)
LOG: Appbase = file:///C:/Program Files/Starcounter/
LOG: Initial PrivatePath = NULL
Calling assembly : (Unknown).
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Program Files\Starcounter\sccode.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Google.Ads.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=52807268f2b614dc
LOG: Attempting download of new URL file:///C:/Program Files/Starcounter/Google.Ads.Common.DLL.
LOG: Attempting download of new URL file:///C:/Program Files/Starcounter/Google.Ads.Common/Google.Ads.Common.DLL.
LOG: Attempting download of new URL file:///C:/Program Files/Starcounter/Google.Ads.Common.EXE.
LOG: Attempting download of new URL file:///C:/Program Files/Starcounter/Google.Ads.Common/Google.Ads.Common.EXE.

HResult=-2147024894
```

**Comment by miyconst** [comment]
Are you sure that `Google.Ads.Common.dll` is in the `/bin/` folder?

**Comment by atifwaqar** [comment]
@miyconst I had to fix the issue somehow, so I removed the entire code base in my local machine, and synced everything from Github again, and everything fixed.
and yes, i made sure all the dlls were in bin folder and in weaver file. I will reopen this issue if it appears again.
