### ISSUE TITLE
starpack does not work with VS 2017

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#4176]
`starpack` fails to find msbuild with Visual Studio 2017. The error that I get:

```
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Starcounter.Apps.Package.Archive.Create(String file, Boolean build, String projectConfiguration, String executable, String resourceFolder)
   at StarPack.ArchivePack.Execute(PackOptions options) in C:\TeamCity\BuildAgent\work\sc-3977\Level1\src\Programs\StarPack\ArchivePack.cs:line 11
   at StarPack.Program.Main(String[] args) in C:\TeamCity\BuildAgent\work\sc-3977\Level1\src\Programs\StarPack\Program.cs:line 22

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

Possibly relevant discussion: https://github.com/Starcounter/Guidelines/issues/15

![2017-03-22 14_53_40-c__windows_system32_cmd exe](https://cloud.githubusercontent.com/assets/566463/24201137/79512900-0f0f-11e7-9c97-202cf42aa284.png)

**Comment by warpech** [comment]
cc @andwah

**Comment by andwah** [comment]
Can i assume that you do not have vs 2015 installed along side with vs 2017?

**Comment by warpech** [comment]
Correct

**Comment by warpech** [comment]
@KmaTTi89 asked as relevant question: Does `starpack` actually build the project using `msbuild`? We thought it only packs the existing binaries.

**Comment by andwah** [comment]
`starpack` can build ( there is an option for that, but it's an experimental thing, i have not solved how to specify the 'configuration' Release/Debug yet.

`starpack` uses the `Microsoft.Build.dll` assembly to read the project file, so maybe it depends on `msbuild `stuff.  I need to investigate some more on how that works.

**Comment by andwah** [comment]
`starpack` does not directly call `msbuild.exe`
