### ISSUE TITLE
Using UriMapping.OntologyMap results in an exception

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#4183]
Using UriMapping.OntologyMap results in an exception in Starcounter 2.3.0.6089 I am getting the following exception:

```
Starcounter.SqlException occurred
  HResult=0x80131500
  Message=Failed to process query: select t from starcounter.metadata.table t where fullname = ?: Unknown class starcounter.metadata.table. Unknown property or alias fullname. 
  Source=Starcounter
  StackTrace:
   at Starcounter.Query.QueryPreparation.PrepareOrExecuteQuery[T](String query, Boolean slowSql, Object[] values)
   at Starcounter.Query.Sql.SqlEnumCache.CacheOrExecuteEnumerator[T](String query, Boolean slowSQL, Object[] values)
   at Starcounter.Db.FullQueryProcess[T](String query, Boolean slowSQL, Object[] values)
   at Starcounter.UriMapping.OntologyMap(String appUriToMap, String mappedClassInfo, Func`2 converterToClass, Func`2 converterFromClass)
   at RoomManagement.API.OntologyHooks.<>c.<MapRoomWithImageApp>b__1_0() in C:\www\Resource-Scheduler\RoomManagementApp\RoomManagementWeb\API\OntologyHooks.cs:line 21
   at Starcounter.Internal.StarcounterEnvironment.RunWithinApplication(String desiredAppName, Action action)
   at RoomManagement.API.OntologyHooks.MapRoomWithImageApp() in C:\www\Resource-Scheduler\RoomManagementApp\RoomManagementWeb\API\OntologyHooks.cs:line 17
   at RoomManagement.API.OntologyHooks.Register() in C:\www\Resource-Scheduler\RoomManagementApp\RoomManagementWeb\API\OntologyHooks.cs:line 10
   at RoomManagement.Program.Main() in C:\www\Resource-Scheduler\RoomManagementApp\RoomManagementWeb\Program.cs:line 10
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application, Assembly assembly)
```

@alemoi is this some new thing? What is the last Starcounter version that does not have this problem?

**Comment by TakhirMamirov** [comment]
2.2 didn't have that problem.

**Comment by alemoi** [comment]
I can just think of something was changed around metadata. But lets ask @k-rus maybe he knows the reason? Should `fullname` field be available?

**Comment by alemoi** [comment]
CC @k-rus
