### ISSUE TITLE
Handler doesn't accept payload in POST requests in unexpected ways

### ISSUE THREAD

**Issue by Ripipip** [Starcounter/Starcounter#4184]
I make the 1st request to a handler that receives POST payloads that matches a typed json file. It works fine. 

When I make the 2nd request I get this error: 

System.NullReferenceException: Object reference not set to an instance of an object.
   at Starcounter.Response.EstimateNeededSize(Byte[] bytes) in C:\TeamCity\TeamCity10\buildAgent\work\sc-3487\Level1\src\Starcounter.Internal\Http\Response.cs:line 1118
   at Starcounter.Response.ConstructFromFields(Request req, Byte[] givenBuffer) in C:\TeamCity\TeamCity10\buildAgent\work\sc-3487\Level1\src\Starcounter.Internal\Http\Response.cs:line 870
   at Starcounter.Request.SendResponse(Response resp, Byte[] serializationBuf) in C:\TeamCity\TeamCity10\buildAgent\work\sc-3487\Level1\src\Starcounter.Internal\Http\Request.cs:line 1241
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\TeamCity10\buildAgent\work\sc-3487\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 811
HResult=-2147467261

More information about this error may be available in the server error log.

**The only difference as far as I can tell is that there is a space after FacebookAd.Image in the working request.** 

This doesn't make sense to me and we have some issues with it because developers use libraries to send json where you don't have control to the extent to control some spaces (but not all) in a json object. 

1st: 
{
    "Campaigns": [
        {
            "UniqueID": "11139615",
            "ContactEmail": "gadd@gmail.com",
            "PublicFacebookpost": true,
            "UseTwitter": false,
            "UseInstagram": false,
            "UseGoogle": false,
            "LandingPageUrl": "",
            "TypeOfAd": 0,
            "ProductObId": "",
            "FacebookAd": {
                "Message": "fem",
                "UrlDescription": "Njutbart läge!!!",
                "Headline": "Gatan 27",
                "Image":"http://krogsveen.no/var/krogsveen/storage/images/itmobjects/437911650/pict/436277632_main_full.jpg",
                "VideoFile": ""
            },
            "TwitterAd": {
                "Message": "",
                "Image": "",
                "VideoFile": ""
            },
            "InstagramAd": {
                "Message": "",
                "Image": "",
                "VideoFile": ""
            },
            "ListingImages": []
        }
    ]
}

2nd: 
{
    "Campaigns": [
        {
            "UniqueID": "11139615",
            "ContactEmail": "gadd@gmail.com",
            "PublicFacebookpost": true,
            "UseTwitter": false,
            "UseInstagram": false,
            "UseGoogle": false,
            "LandingPageUrl": "",
            "TypeOfAd": 0,
            "ProductObId": "",
            "FacebookAd": {
                "Message": "fem",
                "UrlDescription": "Njutbart läge!!!",
                "Headline": "Gatan 27",
                "Image": "http://krogsveen.no/var/krogsveen/storage/images/itmobjects/437911650/pict/436277632_main_full.jpg",
                "VideoFile": ""
            },
            "TwitterAd": {
                "Message": "",
                "Image": "",
                "VideoFile": ""
            },
            "InstagramAd": {
                "Message": "",
                "Image": "",
                "VideoFile": ""
            },
            "ListingImages": []
        }
    ]
}

**Comment by miyconst** [comment]
cc @alemoi

**Comment by Ripipip** [comment]
@alemoi Any idea on this? It is a little bit of a blocker.

**Comment by alemoi** [comment]
Hi @ripipip! Can you please paste some code that sends these requests?

**Comment by Ripipip** [comment]
@alemoi No, it is a client that tries to connect to our API. They use ruby and curl. But it is reproducable with any web debugging tool.

**Comment by miyconst** [comment]
@Ripipip please show us your handler declaration at least.

**Comment by alemoi** [comment]
Ok thank you! So this happens when handler is processed and tries to send the response back. You have no control over the order? I just was thinking what if 2 comes first, and then 1.

**Comment by alemoi** [comment]
I have looked at the code and the stack trace leads to a very misleading code. @Ripipip can I ask you to paste a portion of the actual handler code? Maybe there is some threading there involved? Thanks!
