### ISSUE TITLE
ORDER BY seems not working in 2.3

### ISSUE THREAD

**Issue by TakhirMamirov** [Starcounter/Starcounter#4192]
Trying to run the next SQL:

```
Db.SQL<long>("SELECT COUNT(sh) FROM StatusHistory sh WHERE sh.\"From\" < ? AND sh.\"To\" > ? AND sh.Room = ? ORDER BY sh.\"From\" DESC, sh.\"To\" DESC", 
            DateTime.Today, 
            DateTime.Today, this)
```
and it throws an exception:

```
Starcounter.SqlException: Failed to process query: SELECT COUNT(sh) FROM StatusHistory sh WHERE sh."From" < ? AND sh."To" > ? AND sh.Room = ? ORDER BY sh."From" DESC, sh."To" DESC: Incorrect order-by-clause w.r.t. group-by-clause. 
   at Starcounter.Query.QueryPreparation.PrepareOrExecuteQuery[T](String query, Boolean slowSql, Object[] values) in C:\TeamCity\TeamCity10\buildAgent\work\sc-4040\Level1\src\Starcounter\Query\QueryPreparation.cs:line 70
   at Starcounter.Query.Sql.SqlEnumCache.CacheOrExecuteEnumerator[T](String query, Boolean slowSQL, Object[] values) in C:\TeamCity\TeamCity10\buildAgent\work\sc-4040\Level1\src\Starcounter\Query\SQL\_SqlEnumCache.cs:line 127
   at Starcounter.Db.FullQueryProcess[T](String query, Boolean slowSQL, Object[] values) in C:\TeamCity\TeamCity10\buildAgent\work\sc-4040\Level1\src\Starcounter\Mock\Db.cs:line 132
   at RoomManagementDataModel.Room.get_Status() in C:\Development\Resource-Scheduler\RoomManagementApp\RoomManagementDataModel\Room.cs:line 27
   at lambda_method(Closure , Json )
ScErrorCode=0
BeginPosition=-1
EndPosition=-1
HResult=-2146233088
```

I can remove DESC, and it still doesn't work.

**Comment by miyconst** [comment]
@TakhirMamirov why did you close the issue without a message?

**Comment by TakhirMamirov** [comment]
Not a valid problem, I tried to remove the issue, but couldn't find out how to do it.
